### ISSUE TITLE
Option to hide copies of main subject in replies

### ISSUE THREAD

**Issue by realrandal** [Kunena/Kunena-Forum#1010]
I have simple feature request & I thought it should be simple to do and very useful to clean out topic view.
 
I mean, Hide message subject if it is the same as main topic subject. So show only those who are different (off topic or custom)
 
Already it's visually junk on screen, to have all way long the same subject above every single message.
It's also harder to catch if someone make off topic or just own title for added message.  

So I ask you, how it can be done? It should be option in Kunena config or any different way to recreate that effect. 
By adding even class on message container so topic can be hided be CSS.
 
Can you do this simple thing as feature or tell be how can I do it in template?

**Comment by 810** [comment]
We are doing it like: 
User created the topic: subject
and user replies:
User2 replied the topic: subject

So i will close this issue for now
