### ISSUE TITLE
Introduce The Ability To Show Only Sub-Category

### ISSUE THREAD

**Issue by coder4life** [Kunena/Kunena-Forum#1030]
Introduce a menu item with the ability to show only children from a parent and not a grandparent. Think index page but farther down in the category tree structure. This is good for multiple site section solution where a specific set of children could be shown on a different menu item for the site.

**Comment by 810** [comment]
@coder4life still open?

**Comment by coder4life** [comment]
Yup, specific feature needs to be added.  @mahagr and I did some minor discussion in how we would display this in the interface, it is probably a later version.

**Comment by 810** [comment]
Its included in K4.0 Closing this one
