### ISSUE TITLE
Backend Trash menu: No item 

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#1181]
Number of Items:            Items being Deleted: 
0

When you select a few item and click on purge, You don't see any items on "Are you sure page". But the items are deleted when you click on delete

**Comment by joomlagate** [comment]
I met this same problem today on Kunena 5.1.10 and Joomla 3.9.4.

Only one thing different: no items deleted at all after I click "Purge" button.

That is to say, I can NOT delete any item in the trash of Kunena.

Could you please add a new button named "empty the trash" to detele ALL items with one single click?

Thank you.
