### ISSUE TITLE
Add option to prevent users from reporting their own post

### ISSUE THREAD

**Issue by GoremanX** [Kunena/Kunena-Forum#1205]
In most cases, users should not be able to report their own post. This can be used to abuse the notification system in an effort to gain more attention to a post.

However, sometimes it's necessary for users to be able to report their own post. For example, if a user can't edit his own posts and he has made a mistake in the post.

Therefore, a backend option to prevent users from reporting their own post would be useful.

**Comment by 810** [comment]
merged
