### ISSUE TITLE
Menu Creation During Upgrade

### ISSUE THREAD

**Issue by coder4life** [Kunena/Kunena-Forum#1218]
It was discussed that running menu creation after each upgrade is creating some more problems then it is solving.  Double items are created if a person has move the original menu items.  It was determined the possible best course of action is to only create menu structure on first install.  Instead of having menus created during each upgrade if Kunena cannot find them, it was determined to move the menu creation to the backend if a user needed to do a restore instead of forcing a user for each upgrade to have the new menu.

**Comment by 810** [comment]
@coder4life is this fixed yet :)

**Comment by 810** [comment]
closing this issue, no response on it
