### ISSUE TITLE
Display "Reply" or "Create Topic" buttons before a person has logged-in

### ISSUE THREAD

**Issue by ktbgreat2** [Kunena/Kunena-Forum#1246]
I noticed that a feature that was in earlier Kunena versions, has disappeared from recent versions.

Earlier, in version 1.7 I think, you could see the "Reply" or "Make post" buttons before the person has logged in. Now you cant see those buttons until you have registered, or logged in. 

Personally when I want to reply to a topic in a forum, I always look for those buttons first, then Im prompted to register... It hardly occurs to me to go register before Ive seen the buttons. I feel it puts an unnecessary bump in the road, that doesnt need to be there. I dont like that my visitors will have to scratch their heads, for even a second. 

So yeh, can I see those buttons, while not being logged in, or registered?

**Comment by 810** [comment]
I have added this to the new crypsis template: 
"Please  Log in or Create an account to join the conversation. " With modal on login and create. Im closing this issue

**Comment by steeve00004** [comment]
[Jewelry ](http://swiperock.com/)or earrings includes ornamental objects worn for private adornment, inclusive of [brooches](https://swiperock.com/), [earrings](https://swiperock.com/), [necklaces](https://swiperock.com/), [jewelry](https://swiperock.com/), [pendants](https://swiperock.com/), [bracelets](https://swiperock.com/), and [cufflinks](https://swiperock.com/). [Jewelry ](https://swiperock.com/)may be attached to the body or the garments. From a western angle, the term is limited to long-lasting embellishes, aside from flora for instance. For many Centuries metal such as gold often combined with gems, has been the everyday fabric for jewelry, however other substances which include shells and different plant materials may be used.for more information visit our website:
[Swipe Rock](https://swiperock.com/)
