### ISSUE TITLE
URL BBCode Doesn't Work Like It Used To

### ISSUE THREAD

**Issue by GoremanX** [Kunena/Kunena-Forum#1258]
The [url] bbcode used to (back in K1.7.x) convert relative links that didn't start with a / but now it requires  a leading / (ie index.php vs /index.php)

This can be a bit annoying for existing posts that didn't use a leading slash in their relative urls and now don't display properly after an upgrade to K2.0

http://www.kunena.org/forum/154-Miscellaneous-off-topic-and-general-Joomla/126017-url-tag-can-not-use-relative-dynamic-original-link

**Comment by 810** [comment]
im closing this one, duplicated: https://github.com/Kunena/Kunena-Forum/issues/1267
