### ISSUE TITLE
Lazy load images

### ISSUE THREAD

**Issue by mahagr** [Kunena/Kunena-Forum#137]
Check this:
http://davidwalsh.name/lazyload-plugin

We will also need <noscript> tag for browsers that do not have JS support enabled.

**Comment by 810** [comment]
@xillibit what shall we do, redo it again?

**Comment by xillibit** [comment]
For now i don't want to increase the weight of Kunena package, i will don't add it until the package is under 2 MB

**Comment by 810** [comment]
@xillibit could you update it to K5.0
