### ISSUE TITLE
Include SC Editor as optional editor

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#1458]
http://www.sceditor.com/

This is a Creative Commons BB Code WYSIWYG editor that could exist along side of, or in place of, the current Kunena editor.  This would hopefully be easier to implement than full HTML or a regular Joomla editor for Kunena. ;-)

**Comment by GJSchaller** [comment]
Is this still needed, with the new BBCode editor in 3.1?

**Comment by 810** [comment]
I choosed  wysibb editor for K5.1. Closing this issue
