### ISSUE TITLE
"Print Topic" and "Print Message" buttons

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#1475]
Using the existing Print template / functionality in Joomla, add a Print Topic / Print Message functionality that allows a user to print a topic / message, without all of the Joomla stuff around it, similar to printing Content / Articles. (i.e. - brings up a clean page with no template, and formatted for printing.)

**Comment by 810** [comment]
You can use reading views on the modern browsers now. closing this one
