### ISSUE TITLE
Menu Highlight for Kunena Menu

### ISSUE THREAD

**Issue by Jiminimonka** [Kunena/Kunena-Forum#1650]
Kunena Menu is never highlighted in the Main Menu, unless you do a fancy trick with Alias (which I am not sure even works).

http://screencast.com/t/Sb5m7phm - Home is highlighted (blue bar)

http://screencast.com/t/5m2kEPmfcgvE - Forum is NOT highlighted.

This is a minor bug but I can't think of a single website with Kunena where I have seen the Kunena menu item highlighted.

**Comment by 810** [comment]
we need to add:

```
<?php
$config = KunenaFactory::getConfig ();
if($config->sef) {
	$sef = '/forum';
} else {
	$sef = '/index.php?option=com_kunena';
}
?>
<script>
	var j = jQuery.noConflict();
	var isForumActive = <?php if (strpos($_SERVER['REQUEST_URI'],  $sef) !== false){ echo "true"; } else echo "false";?>;
	if(isForumActive){
		j(".item123").addClass("active");
	}
</script>
```
only we need to add the itemid from the alias

**Comment by 810** [comment]
merged
