### ISSUE TITLE
URL Auto-Link enable/disable option needed in Backend

### ISSUE THREAD

**Issue by Jiminimonka** [Kunena/Kunena-Forum#1692]
Looks like the option to turn off/on rendering of URLs into links is gone.

https://github.com/Kunena/Kunena-2.0/blob/master/administrator/components/com_kunena/libraries/bbcode/bbcode.php#L43

Toggle option for line 43 needs to be enabled in the backend of Kunena.

**Comment by joomlagate** [comment]
It seems that this option has not been added till now?

**Comment by 810** [comment]
Its there since K3.0 you can find it on the configuration - bbcode - Auto-Link URLs

**Comment by joomlagate** [comment]
Thank you, I found that option.
