### ISSUE TITLE
  [master][3.0.7] Menu item Profile >  Use Integration = No: Click in Kunena profile on edit gives a redirect to the CP Profile

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#1835]
http://www.kunena.org/forum/12-Community-Builder/128034-kunena-profile-edit-wrong-link

**Comment by mahagr** [comment]
Unfortunately it cannot be fixed like suggested in #2751. Becomes a top priority bug as the fix causes regression in a few sites.

**Comment by mahagr** [comment]
Reverted the change, so it will not block the release. We might still want to fix this, though.

**Comment by 810** [comment]
closing this one, because cb have all kunena settings and other settings.
