### ISSUE TITLE
Template chooser in user params.

### ISSUE THREAD

**Issue by realrandal** [Kunena/Kunena-Forum#1843]
We have nice working dev switcher module based on cookies. But after clear browser cookies setting is reset & user in every browser need to choose again. So even if chooser will be still based on cookies, it's far better to run it from user settings which remember status for all time.

Then module should coworking with this settings (change user setting on-the-fly) when user are logged. If not (as guest) working still on cookie only.

**Comment by 810** [comment]
I don't think this should be a default feature. Closing this one
