### ISSUE TITLE
Better inline code documentation

### ISSUE THREAD

**Issue by fxstein** [Kunena/Kunena-Forum#19]
We need to dramatically improve the documentation of our functions and APIs inside the Kunena code base. We currently have only minimal documentation inside the code, which makes it much harder to follow and understand what certain functions and classes are supposed todo. Especially for out-side contributors we need to make sure they can find their way into the Kunena code base without much handholding.

Especially since we are now on github, the code become the medium to collaborate, discuss and argue. The better the inline documentation the better.

While we really need this on all branches, I would focus on the master (2.0) as this is the new next generation platform.

**Comment by 810** [comment]
we are using phpdoc now, closing this one
