### ISSUE TITLE
[master][3.0.7]: BBcode issues : bold on center

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#1901]
See :http://www.kunena.org/forum/kunena-3-0-support/127860-bbcode-bugs#145139 related to #1801

**Comment by xillibit** [comment]
@rich20 : is-it fixed with CKeditor ?

**Comment by rich20** [comment]
Quotes from ths bug report:
> -linked images not shown when size value entered

There are no options for size value in the CKeditor


> -when a word firs centered and then made bolded, it still shown not bold

Is fixed with CKeditor

**Comment by rich20** [comment]
This can be closed, because the CKEditor has no size values for images and centered text can be marked as bold.
