### ISSUE TITLE
Outdated icons and fields

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#1934]
Outdated icons and fields in users profile:

MSN, GTALK etc.

**Comment by xillibit** [comment]
It's realted to this one : https://github.com/Kunena/Kunena-Forum/issues/977

**Comment by 810** [comment]
I think this is the new list, we can always add more.
- twitter
- facebook
- Instagram
- skype
- linkedin
- delicious
- google
- QQ 
- Qzone
- Weibo
- Wechat
- microsoft
- Apple
- VK
- Telegram
- icq
- myspace
- blogger
- flickr

depricated still the data, but not in the template anymore:
- friendfeed
- dig
- yim
- aim
- bebo

**Comment by 810** [comment]
merged
