### ISSUE TITLE
Add ability to override default Topic Icons without making a new theme, or overwriting files

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2262]
Requesting a way to override the images in /media/kunena/topicicons/system without needing to make a new template, or having the files overwritten when Kunena is upgraded.

Suggestions include making theme-based folders that can be selected from the template options, so that it's easy to use a default template (Crypsis, Blue Eagle) and just upload a new set of graphics into a discrete folder, maybe even as a Joomla package.  Kunena would see the list of folders, let you choose one in the Template settings, and use that path / folder for all images.  (Default would still be an option, of course.)

**Comment by 810** [comment]
I close this issue, 

The new way is:
copy the dir to: media/kunena/topic_icons/yourdir

Then you can select topic icon on each category, on the category manager - edit category - category settings- "Topic Icons"
