### ISSUE TITLE
  [develop][3.1.0] Crypsis : The button Approve Posts in sub categories does not work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2371]
It will no topics or messages unlocked.

![b87678](https://f.cloud.github.com/assets/888847/2392313/dd332d72-a975-11e3-80d3-064cd7c8f4d5.jpg)

**Comment by 810** [comment]
i have hidden the button for now, until we can fix this

**Comment by 810** [comment]
closing this one, because approve is removed
