### ISSUE TITLE
  [master][3.0.7] Attachment icon is displayed without attachments

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2387]
If you (permanent)delete all messages with attachment in topics, it will still displayed the symbol. Also if you delete all attachments in backend it's the same. It works only, if you edit and delete the attachments directly in messages.
![attachment](https://f.cloud.github.com/assets/888847/2438325/5a37dc68-adf0-11e3-9c6b-0418b1971385.jpg)

**Comment by 810** [comment]
Seems fixed on K5.0, I have no longer this issue. @rich20 could you confirm?

**Comment by rich20** [comment]
You must still manually count statistics.

**Comment by 810** [comment]
- [ ] Deleting topics from backend
- [ ] Deleting messages from backend
- [ ] Deleting permanently topics in frontend
- [ ] Deleting permanently messages in frontend
- [ ] Deleting attachments directly in messages
- [x] Delete attachment backend attachment manager
- [x] Delete attachment profile - attachment manager

**Comment by 810** [comment]
merged
