### ISSUE TITLE
Email addresses in posts are cloaked, despite Joomla's cloaking being disabled

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2427]
If the Email Cloaking plug-in is disabled in Joomla, email addresses within forum posts are still cloaked, giving the text "This e-mail address is being protected from spambots. You need JavaScript enabled to view it."

This interferes with some clients that may not use Java (such as Tapatalk), and should be a configurable option rather than hard-coded into Kunena.

**Comment by 810** [comment]
fixed and merged
