### ISSUE TITLE
User profile does not show deleted or unapproved posts to forum moderators or administrators

### ISSUE THREAD

**Issue by sozzled** [Kunena/Kunena-Forum#2430]
When a forum moderator or administrator goes to a user's profile and looks at the Posts ("Recent Posts") tab, the moderator/administrator can select one or more messages and use the "Delete selected" action from the pulldown below the list.

Deleted messages are not shown on this list.  This means that the option "Undelete selected" has no usefulness.

Unapproved messages are also not shown on this list.  This means that the option "Approve selected" has no usefulness either.

**Comment by 810** [comment]
we need to filter the options in the dropdown.

**Comment by xillibit** [comment]
I'am not sure if this one is still valid, because in profile under "posts" tab you have access to "delete selected" and "permanent delete selected"

**Comment by 810** [comment]
we need a check, that all available options must showed correct.

like if you have already delete a topic, then the delete option should be hidden.

**Comment by 810** [comment]
this is stil valid on thank you tab.
