### ISSUE TITLE
Ability to filter for Users / Posts by IP address in backend

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2542]
My site recently came under heavy load from a handful of IPs, and most of them resolved back to local, residential ISPs that I knew my users used.  However, I was not able to associate specific IPs with specific users, to determine if one of them was causing the load.

I would like to see a function where if an IP address is entered, all Users & Posts associated with that address are displayed.  This can help with site security, as the admin will then know who to potentially contact for issues with that IP.

**Comment by 810** [comment]
merged
