### ISSUE TITLE
[develop][K3.1.0] It would be good if you could quickly identify public write permissions

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2567]
Is just a suggestion for the future. 
Such as here for the Polls.
![public_write](https://cloud.githubusercontent.com/assets/888847/3607946/90c681ee-0d54-11e4-8d2a-8f9e30014d5b.jpg)

**Comment by 810** [comment]
I have checked this, and I believe this is not perfect to show the settings on the main category page, there are to many options, then it looks bad.

So I closing this issue.
