### ISSUE TITLE
K 3.0 / K 3.1 - Categories with no topics with subcategories: does not display "No topics to display" message.

### ISSUE THREAD

**Issue by sozzled** [Kunena/Kunena-Forum#2590]
If you have a category with no topics, when you look at the category index you will see the message "There are no topics to display" as you can see demonstrated here:  http://k25demo.enduring.com.au/forum/category-with-no-topics-and-no-sub-categories

However, if a category has a subcategory (or sub-categories) and the category has not topics, the display is different (as demonstrated here : http://k25demo.enduring.com.au/forum/category-with-no-topics-with-sub-categories)

This is a bug in all versions of *Kunena*, including K 3.1 and it looks untidy.  There are probably only a couple of lines of PHP missing to fix this.  Can someone explain why the message "There are no topics to display" is missing from the category index if the category has a subcategory (or subcategories) and the category has not topics.

**Comment by 810** [comment]
Yes the view is different because creating topics for guests. otherwise you can't create a new topic in the sub category. Im closing this issue.
