### ISSUE TITLE
[develop][3.1.0]: Add Context Sensitive Filters

### ISSUE THREAD

**Issue by coder4life** [Kunena/Kunena-Forum#2591]
As per a private conversation with @mahagr he needs to add context specific filters.  This is so we can actively do filters on layouts that already have some default type of filtering like Recent Topic (recent topics is a default filter that we do not show an interface for).  if we try to clear a normal filter this will clear the main filter on the intended layout on Recent Topic.  So the problem is although we will be in the Recent Topic layout if we currently tried to clear a filter it would still be the Recent Topic layout but would clear it and become the normal topic list.

**Comment by 810** [comment]
closing for now, can be reopend if wanted
