### ISSUE TITLE
[develop]: Implement way to manage user legend to affect to them Joomla! group and image rank

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#2598]
Some users complaining that user legend/role can't be edited easily, i'am talking the the legend/role that we can see in bottom in statistics, actually the users need to modify code to change behaviour of default legend/role : 

![sansdfsdfddfsdfsgfdtitre](https://cloud.githubusercontent.com/assets/876395/3794954/f8dc7216-1bb4-11e4-940b-1639de739373.png)

For each user role should be affected to a Joomla! group and a specific rank too by using default image or an image that user has uploaded. This can be managed with a view in backend to let user do it by himself. I'am not sure if this should be done with ranks view or should be have it's separate view.

**Comment by 810** [comment]
same as https://github.com/Kunena/Kunena-Forum/issues/621 closing this one
