### ISSUE TITLE
Allow use of .PNG images (as well as .GIF images) as category icons

### ISSUE THREAD

**Issue by sozzled** [Kunena/Kunena-Forum#2599]
.GIF files do not look good as category icons.  This is an issue that has been with Kunena ever since Fireboard and no-one has attempted to do anything about it.  If Kunena can use .PNG images (e.g. default.png and default_sm.png) as the "default" category icons, why not allow .PNG files for user-defined category icons?

We explain in the Wiki how it is possible for people to define category icons:  http://www.kunena.org/docs/Category_icons

I also explained in the forum, how people can change the source code to use .PNG icons instead:  http://www.kunena.org/forum/k-3-0-general-questions-archive/127879-how-to-create-category-and-sub-category-icons-in-k-3-0#145243.  Unfortunately, if people make this hack to the source code, they have to remember to reapply it when they upgrade.  Also, this hack means that people can only use .PNG files.

It would be better to allow people to use either PNG or GIF.  Can we do this for K 3.0, please?  If we do this small thing, we will improve the marketability of Kunena as we move ahead into K 3.1.

Making this change in K 3.0.7 would be an important step forward to keeping the community interested.  It demonstrates that the development team is sincere and interested in people who continue to use K 3.0 (especially those who are unlikely to upgrade from J! 2.5 for a long time) and it would be a nice way to close out the development of K 3.0 before it reaches end of life.

**Comment by 810** [comment]
yes same as https://github.com/Kunena/Kunena-Forum/issues/41 closing this one
