### ISSUE TITLE
[develop][3.1.0]: Update media directory structure from current to better naming scheme.

### ISSUE THREAD

**Issue by coder4life** [Kunena/Kunena-Forum#2602]
The media directory has some rally bad organization due from legacy additions.  Goal is to optimize this under a good structure using proper terminology that is commonly used in applications and especially games where media directories are named efficiently with purpose.

Note as discussed with @mahagr this has potential to have backward compatibility issues.  Due to the fact we are in a minor release we cannot break existing installations.  Here are a few options:
* Preserve mapping path but add new directories, if we detect old path we have a warning in back-end that assets need to be moved manually for future versions to support.  (NOTE: No existing directories should clash as all the names are different)
* During Migration we migrate all the directories and associated files in those directories to the new locations for the fact people may have added custom files (NOTE 1: 2e should not be supporting custom files in media directory and need to encourage a more proper place to do this) (NOTE 2: The current directories that cannot be migrated efficiently are those that contain a dynamic range of files specifically attachments and avatars)
* We provide dynamic conversion as we load pages. (NOTE 1: Has a potential to have performance problems, mostly for the active people up front.)
* Create a migration tool that uses Javascript to continually keep a request going until migration is done (NOTE 1: Our installer and AkeebaBackup do something similar) (NOTE 2: The current directories that cannot be migrated efficiently are those that contain a dynamic range of files specifically attachments and avatars)

Here is the proposal of directory structure that is modeled after some common applications for media items, there definitions have been verified with purpose:
* assets (distributed, static) --> e.g. js, css, less, ext (specific to Kunena and not any third party package)
* cache (generated, dynamic) --> e.g. attachment pointers, user avatar sizes
* resources (distributed, managed, dynamic) --> e.g. icons sets, rank sets, emoticon sets, ext
* user (managed, dynamic) -> e.g. user avatar, user attachemtns
* external (git-submodule, svn, or imported NOT distributed) --> e.g. bootstrap, font-awesome

**Comment by 810** [comment]
closing for now, can be reopend if wanted
