### ISSUE TITLE
[K3.1] Make sure that attachments aren't overwritten with the new code

### ISSUE THREAD

**Issue by mahagr** [Kunena/Kunena-Forum#2630]
This issue is related to #2613 as we need to apply similar fix to K3.1 as well.

Basically we have two usecases in Kunena 3.1:

* Protected files which have random md5 based attachment names stored into disk and there's task to handle file downloads
* Files are stored and directly accessed by the browser

In the first case the real filename doesn't have to change (filesystem has random filename)-- and it shouldn't. So basically we can pass the original filename to the users who are attempting to access the file.

In the second case (direct access to the files) we still need to filter the filename as before and make sure that the new uploaded file doesn't have the same name as the previous file.

**Comment by xillibit** [comment]
I had done a PR to fix that : https://github.com/Kunena/Kunena-Forum/commit/2d36913114b3bdd4489370e3f115bf3658371c99
