### ISSUE TITLE
K3.1 - Crypsis : implement jquery uploader by blue imp to handle attachments

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#2641]
Implement jquery uploader by blue imp to handle attachments to replace mootools one in Crypsis.

- [x] Make upload of new attachments working
- [x] Take care of Kunena configuration to limit attachments number
- [x] Insert image in messages
- [x] Load attachments already uploaded previously by user when it edit message
- [x] Let user remove attachments already uploaded on filesystem
- [x] Add JText strings in javascript to be able to translations
- [x] Use minimal number of js files from plugins
- [x] Limit Attachments default is 8, I can upload maximum 4 Images (Joomla 3.3.6 php 5.5) and on the other pages with php 5.3 and php 5.4 only 3 Images =>  Limit number of attachments in editor has no effect in jquery uploader
- [x] Add label with max attachments + size
- [ ] Add a button to upload all files present in the message form
- [x] Add dropzone with text to describe to drag&drop files and still keeping usage of buttons (drag&drop works by default)
- [x] Image uploaded doesn't opened in a lightbox
- [x] Issue :  PHP Warning: is_uploaded_file() expects parameter 1 to be string, array given in C:\wamp\www\master\components\com_kunena\lib\kunena.upload.class.php on line 191 (still exists ?)
- [ ] Design tweaks ?

**Comment by xillibit** [comment]
@rich20 : i'am not able to reproduce your issue if i drag several images then i upload them, and i submit the message at the end i don't see errors

**Comment by rich20** [comment]
Yes, with this new fix it works, but not with the previous.
- [x] Drag several images or attachments - Success

**Comment by 810** [comment]
This one is merged, if you find any issues, please open a new issue for it
