### ISSUE TITLE
[develop][3.1.0]: Avatar add animated gif support

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2658]

**Comment by 810** [comment]
I just found out that the gifs are working. The gifs need to be 90x90 or less.

**Comment by 810** [comment]
im closing this issue. If users want animated avatars, they need resized it to 90x90

**Comment by xillibit** [comment]
Why do-you said that the avatar need to be resized tp 90x90 ? I don't find where that it's explained

**Comment by 810** [comment]
i found out that other forum software have the same issue. see: http://www.minecraftforum.net/forums/forums/forum-discussion-info/512021-avatar-isnt-animated?comment=2

So the resizer is just picking the first layer. so it will loose the layers.

**Comment by mahagr** [comment]
We could add support for this when we have image manipulation library that supports animation resizing.
