### ISSUE TITLE
[master][3.0.6] Poll: If you split/move only the first message it creates a additional poll

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2660]
http://www.kunena.org/forum/k-3-0-general-questions/131821-can-t-merge-topics-few-drop-down-menu-options
I've tested it.
If you split/move only the first message it creates a additional poll. Then you have more topics with polls. But it works simultan. If you vote in a topic, your vote is also in the others topics.

**Comment by rich20** [comment]
- [x] Success

**Comment by 810** [comment]
merged
