### ISSUE TITLE
[K3.1] Crypsis: New topic. no category selected, wrong error

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2708]
When you click on save, without a categorie, you are getting the wrong error:
You do not have permissions to access this page.

**Comment by xillibit** [comment]
I don't remember in which case you don't have a category selected by default

**Comment by 810** [comment]
config -  frontend - Force users to pickup a category - "Yes"
Go to new topic. (menu), then enter subject and message, click on save. So selecting without category
