### ISSUE TITLE
[K3.1] Crypsis: Fatal Error: Maximum function nesting level of '300' reached

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2713]
Fatal Error was detected!

The error was detected in the Libraries.

Fatal Error: Maximum function nesting level of '300' reached, aborting! in libraries/joomla/date/date.php on line 102

Moderate a message,   move the message to a new topic. On saving you get the error

**Comment by 810** [comment]
Have the same error on k3.0.7

**Comment by xillibit** [comment]
I'am not able to reproduce this issue, i have tested on K3.1 and K3.0.6

**Comment by 810** [comment]
create topic "test2" as user, then do a quick reply same user. login as admin. 
click on moderate on the second message. change subject to "test3" click on proceed. (make sure new topic is selected)

**Comment by xillibit** [comment]
I have followed your steps but i'am not encountering your error : 

- Connected as registred user, i have created a new topic then replied to it with quick reply
- Then as admin i have clicked on moderate on second message, changed the subject and right selected new topic
- Then the topic has been slipted successfully without your error

**Comment by 810** [comment]
i have tried to fix the recount issue, so i get this error on recount. I will close this issue
