### ISSUE TITLE
[develop][3.1.0] Teaser : guests can read all messages via search

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2721]
A guest can see the topic title. If he uses "Search titles only", he sees the complete topic.

**Comment by xillibit** [comment]
I have tried to reproduce this issue but i'am not able, i have set the category suggestion box to only register users. Then when i'am a guest i try to search with "Search titles only" but i don't find the topic into suggestion box.

**Comment by 810** [comment]
I can read the first message, and the first message from the last page.

https://newf1.nl/forum/search?query=Welcome%20to%20Kunena%20V3.1!&titleonly=1&searchdate=all&childforums=1&ids=

**Comment by rich20** [comment]
> i have set the category suggestion box to only register users.

If you set a category only for registered users, then the teaser is useless. Guests cannot see the first message. You must set the category to public.
