### ISSUE TITLE
[3.1] Category Image Path: does not work

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2726]
When "Config => Frontend => Category Image Path" is set in the Kunena config, and the icons are present...

Crypsis still pulls from:
/components/com_kunena/template/crypsis/media/topic_icons/default/system/(icon).png

Blue Eagle pulls from:
/media/kunena/topic_icons/default/system/(icon).png

**Comment by xillibit** [comment]
Maybe this setting should be put directly for each template settings

**Comment by GJSchaller** [comment]
I would agree with @xillibit

**Comment by xillibit** [comment]
We should keep this setting in Kunena configuration settings because old templates may still use it. In templates shipped this setting shouldn't be used

**Comment by GJSchaller** [comment]
This looks similar to #2262 - can we close old ones to get them out of the system?

**Comment by 810** [comment]
fixed and merged
