### ISSUE TITLE
[K3.1] bbcode: Tweet isn't working anymore

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2737]
[tweet]tweeted numbers[/tweet] doesn't work anymore, api update?

**Comment by xillibit** [comment]
I will take a look if something has been changed in twitter API

**Comment by 810** [comment]
you need an authentication now with OAuth

**Comment by xillibit** [comment]
Joomla has something to handle it: https://api.joomla.org/cms-3/classes/JOAuth1Client.html, i will take a look later

**Comment by 810** [comment]
http://www.microsofttranslator.com/BV.aspx?ref=IE8Activity&a=http%3A%2F%2Fwww.spazioalchimia.it%2Fcoding%2F140-joomla-integrazione-social-network

**Comment by xillibit** [comment]
Thanks it was what i was looking for

**Comment by xillibit** [comment]
Some tips to make it working : 

https://github.com/BabDev/Tweet-Display-Back
http://ghijklmno.net/twitter-migration-to-v1-1-api/

**Comment by 810** [comment]
I get only get the right date -time, but no content or name ect

**Comment by xillibit** [comment]
Did-you have tried to remove cached things about kunena_twitter ?

**Comment by 810** [comment]
Yes: 
![kunena topic dwcdwcdw cdw dc wd c](https://cloud.githubusercontent.com/assets/876623/6425757/65de4ff0-bf3a-11e4-8a3a-862365807222.png)

**Comment by xillibit** [comment]
There is an issue with caching part, if i remove it the tweet dis displayed...

**Comment by xillibit** [comment]
You can try now it should work

**Comment by 810** [comment]
yes, get the content.

There are spaces on the twitter name, so link to profile doesn't work

**Comment by xillibit** [comment]
Try now

**Comment by 810** [comment]
![untitled](https://cloud.githubusercontent.com/assets/876623/6426586/c71364ea-bf62-11e4-9002-f92c5eea84dc.png)

Could you also add reply, retweet, favorite

**Comment by xillibit** [comment]
> Could you also add reply, retweet, favorite

Done

Need to find a way to parse links into the tweet

**Comment by xillibit** [comment]
@810 : now the links into the tweet are parsed into URL, can-you improve layouts now ?

**Comment by 810** [comment]
fixed, and merged
