### ISSUE TITLE
[3.1] Crypsis : Show E-mail = No has no effect (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2747]
I'm sorry, but I had forgotten to test one option https://github.com/Kunena/Kunena-Forum/pull/2744

> Show E-mail = No : 
- [x] Administrators can see it
- [x] Members cannot see it
- [x] Guests cannot see it

> Show E-mail = Yes - User setting in the profile : Hide E-mail = Yes
- [x] Administrators can see it
- [x] Members cannot see it
- [x] Guests cannot see it

> Show E-mail = Yes - User setting in the profile : Hide E-mail = No
- [x] Administrators can see it
- [x] Members can see it
- [x] Guests can see it

Show E-mail = No - User setting in the profile : Hide E-mail = No
- [x] Administrators can see it
- [ ] Members can see it
- [ ] Guests can see it

**Comment by 810** [comment]
I have fixed this issue, is now in branch. 

@rich20 could you confirm this

**Comment by rich20** [comment]
- [x] Success
