### ISSUE TITLE
[K3.1] Crypsis: index Notice: Uninitialized string offset: 1

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2748]
Notice: Uninitialized string offset: 1 in C:\wamp\www\master\libraries\joomla\filesystem\path.php on line 209

Call Stack

#

Time

Memory

Function

Location

1 0.0005 242896 {main}( ) ..\index.php:0 
2 0.0642 3500968 JApplicationCms->execute( ) ..\index.php:40 
3 0.0642 3501168 JApplicationSite->doExecute( ) ..\cms.php:251 
4 0.1472 8393368 JApplicationSite->dispatch( ) ..\site.php:230 
5 0.1534 8486608 JComponentHelper::renderComponent( ) ..\site.php:191 
6 0.1555 8544880 JComponentHelper::executeComponent( ) ..\helper.php:360 
7 0.1560 8613024 require_once( 'C:\wamp\www\master\components\com_kunena\kunena.php' ) ..\helper.php:380 
8 0.6316 10676408 KunenaControllerApplicationDisplay->execute( ) ..\kunena.php:83 
9 0.7176 13117216 KunenaLayout->render( ) ..\display.php:105 
10 0.7177 13117424 KunenaLayoutBase->render( ) ..\layout.php:60 
11 0.7185 13139192 include( 'C:\wamp\www\master\components\com_kunena\template\crypsis\pages\category\list\default.php' ) ..\base.php:165 
12 0.7185 13139320 KunenaLayoutPage->execute( ) ..\default.php:13 
13 0.7198 13206344 KunenaControllerDisplay->execute( ) ..\page.php:46 
14 0.7198 13207720 ComponentKunenaControllerCategoryIndexDisplay->before( ) ..\display.php:29 
15 0.7284 13997448 KunenaForumCategory->getRSSUrl( ) ..\display.php:140 
16 0.7284 13997704 KunenaRoute::_( ) ..\category.php:248 
17 0.7284 13997880 KunenaRoute::prepare( ) ..\route.php:108 
18 0.7298 14199880 KunenaRouteLegacy::convert( ) ..\route.php:475 
19 0.7300 14202120 JLog::add( ) ..\legacy.php:548 
20 0.7301 14203648 JLog->addLogEntry( ) ..\log.php:151 
21 0.7322 14267704 JLogLoggerFormattedtext->addEntry( ) ..\log.php:262 
22 0.7322 14267880 JLogLoggerFormattedtext->initFile( ) ..\formattedtext.php:120 
23 0.7337 14401840 JFolder::create( ) ..\formattedtext.php:219 
24 0.7346 14447760 JFolder::exists( ) ..\folder.php:181 
25 0.7346 14447760 JPath::clean( ) ..\folder.php:483

**Comment by xillibit** [comment]
Which Joomla! version do-you have ? This error wasn't here before

**Comment by 810** [comment]
K3.4 nighly build. I got it sometimes, when i visit the index page for the first time.

**Comment by 810** [comment]
Im closing this one. if later needed, i will reopen again

**Comment by 810** [comment]
I still got this issue:

After remove cache, then go to forum menu item, you get the error. Only on the first time:

Call Stack


#

Time

Memory

Function

Location

1 0.0169 239344 {main}( ) ..\index.php:0 
2 0.2830 3490512 JApplicationCms->execute( ) ..\index.php:40 
3 0.2830 3490712 JApplicationSite->doExecute( ) ..\cms.php:251 
4 0.6516 8594224 JApplicationSite->dispatch( ) ..\site.php:230 
5 0.6761 8689792 JComponentHelper::renderComponent( ) ..\site.php:191 
6 0.6885 8751352 JComponentHelper::executeComponent( ) ..\helper.php:360 
7 0.6910 8819528 require_once( 'C:\wamp\www\master\components\com_kunena\kunena.php' ) ..\helper.php:380 
8 0.8247 9848224 ComponentKunenaControllerApplicationHomeDefaultDisplay->execute( ) ..\kunena.php:83 
9 0.8520 10120480 KunenaControllerApplicationDisplay->execute( ) ..\display.php:108 
10 3.6161 17350080 KunenaLayout->render( ) ..\display.php:105 
11 3.6162 17350288 KunenaLayoutBase->render( ) ..\layout.php:60 
12 3.6203 17372048 include( 'C:\wamp\www\master\components\com_kunena\template\crypsis\pages\category\list\default.php' ) ..\base.php:165 
13 3.6204 17372176 KunenaLayoutPage->execute( ) ..\default.php:13 
14 3.6303 17439184 KunenaControllerDisplay->execute( ) ..\page.php:46 
15 3.6303 17440560 ComponentKunenaControllerCategoryIndexDisplay->before( ) ..\display.php:29 
16 3.7008 18271888 KunenaForumCategory->getRSSUrl( ) ..\display.php:140 
17 3.7009 18272144 KunenaRoute::_( ) ..\category.php:248 
18 3.7009 18272320 KunenaRoute::prepare( ) ..\route.php:108 
19 3.7067 18474328 KunenaRouteLegacy::convert( ) ..\route.php:475 
20 3.7077 18476568 JLog::add( ) ..\legacy.php:548 
21 3.7082 18478096 JLog->addLogEntry( ) ..\log.php:151 
22 3.7218 18541144 JLogLoggerFormattedtext->addEntry( ) ..\log.php:262 
23 3.7218 18541320 JLogLoggerFormattedtext->initFile( ) ..\formattedtext.php:120 
24 3.7227 18541824 JFolder::create( ) ..\formattedtext.php:219 
25 3.7229 18542128 JFolder::exists( ) ..\folder.php:181 
26 3.7230 18542224 JFilesystemWrapperPath->clean( ) ..\folder.php:487 
27 3.7230 18542304 JPath::clean( ) ..\path.php:100

**Comment by xillibit** [comment]
I have tried under J!3.4.0 to reproduce this issue but i'am still not able to do it

**Comment by 810** [comment]
change default page to index. then clean cache. then go to forum item.

**Comment by xillibit** [comment]
> change default page to index. then clean cache. then go to forum item.

I have done that but i don't have this issue, from call the Joomla! logger try to create a directory for log with a file in it but it is not able to do that

**Comment by 810** [comment]
i still get that error, when i update a new build. Its just showed 1 time, after install , when you refresh the error is gone

**Comment by xillibit** [comment]
Joomla! has enough to write into /logs directory ?

**Comment by 810** [comment]
i get no error on blue eagle

**Comment by 810** [comment]
the error is on:
https://github.com/Kunena/Kunena-Forum/blob/develop/components/com_kunena/site/controller/category/index/display.php#L140

**Comment by 810** [comment]
so the error comes from:
https://github.com/Kunena/Kunena-Forum/commit/8fb90f58e6c6d5bc91ed0f5e8fb71848ec332508

**Comment by xillibit** [comment]
no, the error come form here : https://github.com/Kunena/Kunena-Forum/blob/develop/libraries/kunena/route/legacy.php#L677 if you try to comment this line the issue should disapprear

**Comment by 810** [comment]
yes, its gone

**Comment by 810** [comment]
* error.php
* joomla_update.php
* kunena.php

**Comment by 810** [comment]
turn off Support Legacy URLs, would fix this, closing this issue
