### ISSUE TITLE
[K3.1] Subscription : The option "Check Subscription Box = Yes or No" should be in the profile available

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2759]
http://www.kunena.org/forum/77-General-Talk-about-Kunena/132300-user-setting-auto-subscribe-thread
The option should only to be available when global setting is "Allow Subscriptions = Yes"

**Comment by 810** [comment]
see: https://github.com/Kunena/Kunena-Forum/pull/2777
