### ISSUE TITLE
[K3.1] Backend Feature: add option to remove subscriptions

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2805]

**Comment by xillibit** [comment]
I had keeped that since a long time : 

FYI if someone wants to remove all subscriptions from a user
UPDATE `jjj_kunena_user_categories` SET `subscribed` =0 WHERE `user_id` =1234;
 of course prefix and userid needs to change..

**Comment by 810** [comment]
I tried it, add the function on controllers/user.php but the function couldn't loaded from that, on users.php its loaded. but no userid. so sql error

**Comment by 810** [comment]
merged
