### ISSUE TITLE
Discuss plugin conflict with forum moderating

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#2807]
These functions are not available, if a topic was created by the Kunena Discuss (3.0.7):

- Move only selected message
- Move selected message and all x messages posted after it

http://www.kunena.org/forum/kunena-3-0-support/132474-after-update-to-kunena-3-0-7-i-have-moderating-problems

**Comment by 810** [comment]
Do you still have the conflict?
