### ISSUE TITLE
[develop] Crypsis RSS Feed : rss.png will not showing (NetworkError: 404)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2809]
Firebug shows:
"NetworkError: 404 Category not found - ../media/kunena/images/icons/rss.png"
rss.png

**Comment by 810** [comment]
I don't have this issue. Where do you get this?

**Comment by rich20** [comment]
hm.. maybe it's only with Firefox. The rss.png on the right hand side does not appear.

**Comment by 810** [comment]
I don't have it with FF38.a2 and Firebug 3a.
Try now, i have removed some images on the css.

**Comment by rich20** [comment]
In Blue Eagle the path is "/components/com_kunena/template/blue_eagle/images/icons/rss.png" and it works.

With Crypsis the path is "/media/kunena/images/icons/rss.png" but in this folder is definitely no rss.png.

**Comment by 810** [comment]
is this on index? or any page

**Comment by rich20** [comment]
On any pages.

**Comment by 810** [comment]
for me the icon is showed. on chrome/ff/ie

**Comment by rich20** [comment]
Which path has your icon?

**Comment by 810** [comment]
iconmoon icon

**Comment by rich20** [comment]
I've no more idea. Joomla cache is empty and tried with a new Firefox profile. But maybe is this issue not so important that you wasted much time.
![bildschirmfoto vom 2015-03-10 16 58 59](https://cloud.githubusercontent.com/assets/888847/6579181/dcc9133c-c748-11e4-90c0-5a8e1e60e67f.png)

**Comment by 810** [comment]
oh on rss itself. yes we should remove it.

**Comment by rich20** [comment]
- [x] Success
