### ISSUE TITLE
[master][3.0.8] Menu item Recent Posts shows only own posts

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2816]
Menu item Recent Posts shows only own posts but guests see all posts. If you write something in the field "User", also members can see all posts.
![bildschirmfoto vom 2015-03-09 20 18 56](https://cloud.githubusercontent.com/assets/888847/6563364/ddb29d48-c6a0-11e4-85f5-e4c1f318eddf.png)

**Comment by xillibit** [comment]
Is fixed this one ?

**Comment by rich20** [comment]
Now se all users the recent posts.

**Comment by rich20** [comment]
For me it's correct.
