### ISSUE TITLE
Fatal Error: Class 'JFolder' not found in components/com_kunena/models/rank.php on line 75

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#2826]
edit rank and you get this error

**Comment by xillibit** [comment]
I have just tried that and i don't have this issue, i'am on J!3.4.0 and last build of K3.1

**Comment by 810** [comment]
i Have tried 4 branches, all have the same error.

**Comment by rich20** [comment]
Confirmed this error. It breaks also the Joomla control panel.

Warning: array_merge() [function.array-merge]: Argument #2 is not an array in ../administrator/modules/mod_quickicon/helper.php on line 163

**Comment by 810** [comment]
fixed and merged
