### ISSUE TITLE
[develop][3.1.0] Menu item Moderator Topics shows nothing

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2834]
Menu item description: Displays recent topics which haven't been replied by moderators.
I've tried all settings but it's failed.
Crypsis shows : Topics Needing Attention (Clear Filter)
Blue Eagle : Access Denied - You do not have permissions to access this page.

**Comment by mahagr** [comment]
Not implemented in blue eagle, in crypsis it should display topics which have post from topic starter after the last reply from any moderator of that category including global.

**Comment by 810** [comment]
This one is working normal, closing this issue.

PS this feature is hmvc only
