### ISSUE TITLE
[3.0.7] Bad display on mobile when looking a topic

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#2842]
There is a bad display on mobile : 

![screenshot_2015-02-15-10-58-19](https://cloud.githubusercontent.com/assets/876395/6713823/195d2f84-cd95-11e4-818b-e195c6201eb3.png)

**Comment by 810** [comment]
fixed:
http://www.kunena.org/forum/k-3-0-blue-eagle-templates/132420-position-of-editing-toolbars-and-statistics-on-mobile?limitstart=0
