### ISSUE TITLE
[develop] Crypsis : If you create a new topic the subject is already included.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2902]
If you create a new topic the subject is already included. It's always the same title, as in the first topic.

**Comment by rich20** [comment]
hmm.. it seems a cache problem. It's always the titel from the topic where was last written.

**Comment by 810** [comment]
Its the new feature, that saved data, for recovery and from quickreply to normal editor

**Comment by rich20** [comment]
Now you get no warning if you forgot a topic title.

**Comment by xillibit** [comment]
The last entry shouldn't appear in inputs if you submit your message

**Comment by rich20** [comment]
You can easy test it. Read a message (no matter which one) and then create a new topic. In input field is the same subject like those of the last read message.

**Comment by rich20** [comment]
I see now, the same problem gives with Reply. 
Example:
The topic is "Welcome to Kunena!"
Click on Reply and change the topic title for this one message to "Welcome to Kunena testpage"
now click at the first message on Reply
in the input field is "Welcome to Kunena testpage" and not "Welcome to Kunena!"

**Comment by xillibit** [comment]
Is-it fixed now ?

**Comment by rich20** [comment]
- [x] SCuccess
