### ISSUE TITLE
[develop] Crypsis : the search options "Normal Posts, Unapproved Posts, Deleted Posts" are not selectable

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2910]

**Comment by xillibit** [comment]
Where exactly ? Because on search tab it works perfectly

**Comment by rich20** [comment]
The checkboxes are missing.

![bildschirmfoto vom 2015-04-03 17 04 30](https://cloud.githubusercontent.com/assets/888847/6983958/18b19958-da24-11e4-976d-25a852704905.png)

**Comment by 810** [comment]
yes, will fix this

**Comment by 810** [comment]
should be fixed now
