### ISSUE TITLE
[develop] Crypsis : Edit messages with attachments such as zip, pdf etc..

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2925]
Attachments are displayed as not loaded images.

![bildschirmfoto vom 2015-04-04 18 43 47](https://cloud.githubusercontent.com/assets/888847/6993966/10fc51a6-db07-11e4-8e98-c8646b5fee79.png)

**Comment by 810** [comment]
Can't find the source code, @xillibit do you know where?

**Comment by xillibit** [comment]
I will look in the evening

**Comment by 810** [comment]
merged
