### ISSUE TITLE
Gender Options - On / Off, more choices

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2937]
Currently, the icon for gender is always enabled, meaning it always displays either Male, Female, or N/A.

Two requests:

1) Make a toggle to enable / disable this feature, so the icon display and field can be turned off if it is not wanted.

2) Expand the list to include a more inclusive set of genders (some of my users are trans, or asexual) - I will work on getting a comprehensive list.

**Comment by 810** [comment]
See:
https://github.com/Kunena/Kunena-Forum/pull/2453

**Comment by GJSchaller** [comment]
Thank you - this can be folded into that request.

**Comment by 810** [comment]
its should be on the todo list

**Comment by 810** [comment]
I'm closing this one, because this need to be a plugin, not in the core.
