### ISSUE TITLE
[develop] [4.0] Category moderators are displayed as moderator in all categories

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2950]
In Crypsis with rank image and moderator color (blue)
and in blue eagle only with moderator color

**Comment by xillibit** [comment]
I have tried, i have a moderator which is set on suggestion category, it appear not in blue : 

![moderator](https://cloud.githubusercontent.com/assets/876395/7236240/055831fa-e794-11e4-870a-bd1b5f6e417a.png)

**Comment by rich20** [comment]
Maybe I had written it incomprehensible.
In Crypsis with rank image and user name is with moderator-color (blue) in all categories
and in blue eagle the user name is with moderator-color blue in all categories

![055831fa-e794-11e4-870a-bd1b5f6e417a](https://cloud.githubusercontent.com/assets/888847/7236674/8c0919f6-e796-11e4-8200-fa9e5f8dfab5.png)

**Comment by xillibit** [comment]
> In Crypsis with rank image and user name is with moderator-color (blue) in all categories
> and in blue eagle the user name is with moderator-color blue in all categories

Crypsis and blue eagle have the same behaviour so i don't understand the issue

![ddd](https://cloud.githubusercontent.com/assets/876395/7337761/9586dbd2-ec35-11e4-83cd-ef7aeb112bc2.png)

**Comment by rich20** [comment]
In this category is user richi not moderator. You can see the difference.


![bildschirmfoto vom 2015-04-26 18 41 55](https://cloud.githubusercontent.com/assets/888847/7338233/14ee2d7a-ec46-11e4-9983-e5f263407d09.png)

**Comment by mahagr** [comment]
Works otherwise, but category index and category view are missing catid for the user link.
