### ISSUE TITLE
[develop] [4.0] Backend File Manager : Attachments such as zip are displayed as not loaded images

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2961]
Attachments such as zip, pdf etc.. are displayed as not loaded images.

**Comment by xillibit** [comment]
This one ddidn't the trick : https://github.com/Kunena/Kunena-Forum/issues/2925 ?

**Comment by rich20** [comment]
This one solved it only in the editor.

**Comment by 810** [comment]
fixed and merged
