### ISSUE TITLE
[develop] Crypsis : Lightbox doesn't work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#2963]

**Comment by rich20** [comment]
It's only at images in messages. It works in profile - attachment manager.

**Comment by rich20** [comment]
It is an interesting bug. He is only present, if you are logged in. Only guestes can show lightbox.

**Comment by 810** [comment]
Its conflicting with pr, with thankyou. 

In the developer branch, there is no issue, so I'm closing this one
