### ISSUE TITLE
4.0 Beta - when in Backend, in Config, the Joomla site preview link is broken

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2964]
Sample URL:

http://template.knightrealms.com/administrator/index.php?option=com_kunena&view=config

When you click on the link in the upper right of Joomla to go to the main site, it takes you to this URL instead: http://template.knightrealms.com/media/kunena/attachments/

This does NOT happen in other parts of the Joomla backend, only in Kunena's config.

![screen shot 2015-04-13 at 7 26 49 pm](https://cloud.githubusercontent.com/assets/2761607/7127493/11701984-e213-11e4-8a68-12822f5200cd.png)

**Comment by 810** [comment]
fixed and merged
