### ISSUE TITLE
When put only confidential tag with content in it, on submit error : the message is empty

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#3006]
When put only confidential tag with content in it, on sumbit you have an error saying that the message is empty. So the workaround to submit the post is the put some text outside of confidential tag

**Comment by rich20** [comment]
I think, it's the same. https://github.com/Kunena/Kunena-Forum/pull/3001

**Comment by xillibit** [comment]
I hadn't seen the 3001, so i close this one
