### ISSUE TITLE
[master] [3.0.9] Admin kunena.views.ini line 150 (the text should be changed) 

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3009]
Require E-mail - These option works only for guests, not for registered users.

Require an e-mail address when users or visitors make a post. Set to No if you want this feature to be skipped on the front end. Posters will not be asked for their e-mail address.

Should be

Require an e-mail address when visitors make a post. Set to No if you want this feature to be skipped on the front end. Posters will not be asked for their e-mail address.

**Comment by 810** [comment]
merged
