### ISSUE TITLE
[develop] Crypsis: Wrong link at announcements

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3028]
In Blue Eagle users can see all public announcements with a click on the bar.
![bildschirmfoto vom 2015-04-27 03 16 04](https://cloud.githubusercontent.com/assets/888847/7340349/0e2817da-ec8c-11e4-8350-fe47d0552846.png)
With Crypsis is it not possible. The link is the same like Read More..
![bildschirmfoto vom 2015-04-27 03 03 17](https://cloud.githubusercontent.com/assets/888847/7340308/ec89ae32-ec8a-11e4-91dd-f92efc1ef47b.png)

**Comment by 810** [comment]
fixed and merged

**Comment by rich20** [comment]
The link works now but the toolinfo is wrong.
class="btn-link" rel="follow" title="**Announcement 2**" href="/.../forum/announcement/list"> **Announcement 2**
