### ISSUE TITLE
When reply/create a new topic as guest tab goes to message

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#3029]
When reply/create a new topic as guest when you do tab from name, you goes directly to message

See: http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/133186-wrong-tab-order-guest-new-topic#163967

**Comment by rich20** [comment]
- [x] Success
But a similar problem exists at the login. When guests click on reply/create a new topic and he want login before writing,, it switch from the login form from username to "Enter the name of author".
![path2987](https://cloud.githubusercontent.com/assets/888847/7361599/9e150fe0-ed5b-11e4-88ef-d92c62950fc9.png)

**Comment by xillibit** [comment]
Updated

**Comment by rich20** [comment]
The login form works now. But if you  reply/create topics without login guest must 3x press to go in the next field.

**Comment by xillibit** [comment]
Should be ok now

**Comment by rich20** [comment]
- [x] Success
