### ISSUE TITLE
Catagory Drag Sort Not working

### ISSUE THREAD

**Issue by KingZogg** [Kunena/Kunena-Forum#3071]
I can sort Joomla menus but can't get the move icon to appear on the catagories no matter what sort dropdown I choose.

Joomla 3 and Kunena latest updates as of this post.

**Comment by rich20** [comment]
There is no support here. If you have problems, ask in the forum.

**Comment by KingZogg** [comment]
I don't need support.
It's a bug.

**Comment by rich20** [comment]
Sorry, I had misunderstood.

**Comment by xillibit** [comment]
First click on the icons like here in red : 

![dgfgfhhgfg1](https://cloud.githubusercontent.com/assets/876395/7555870/9677a136-f75a-11e4-9b71-c2570ca62f94.png)

Then you can drag&drop categories:

![xcvxv2](https://cloud.githubusercontent.com/assets/876395/7555872/a57dc64c-f75a-11e4-80cd-838f6d892c32.png)

**Comment by KingZogg** [comment]
It worked.
Thanks.
Why it can sort menus without clicking that button but not categories is a mystery to me though.
