### ISSUE TITLE
[develop] [4.0] Blue Eagle : Time zone issue

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3079]
If you set : 
##### Message Time Format = Date (11.May 2015)
Notice: Kunena: Timezone issue! in libraries/kunena/date.php on line 151

If you set : 
##### Message Time Format = Yesterday
Notice: Kunena: Timezone issue! in libraries/kunena/date.php on line 151
Warning: DateTime::setTimezone() expects parameter 1 to be DateTimeZone, string given in /libraries/joomla/date/date.php on line 396

**Comment by xillibit** [comment]
I will look later, it's the same that there was in crypsis : https://github.com/Kunena/Kunena-Forum/pull/3074
