### ISSUE TITLE
[K4.0] Crypsis: 3 party plugins don't showed on new topic

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3095]
KunenaBbCodeEditorButton not working

**Comment by xillibit** [comment]
Which third parties plugins aren't showed on new topic ?

**Comment by 810** [comment]
like tex plugin, or my own plugins

Looks like onKunenaBbcodeEditorInit don't work

**Comment by xillibit** [comment]
This one needs a couple of hours to be totally working
