### ISSUE TITLE
[K4.0] Crypsis: The Plugin Captcha - ReCaptcha (version 2.0) does not work with Kunena

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3098]
http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/133648-recaptcha-not-working-beta3
The code is not accepted: 
Error
Incorrect captcha. Please try again.
But the code is correct. For the Joomla registration the captcha works.

**Comment by Ruud68** [comment]
@xillibit fix works for me if I remove the if ( $template->getTemplateDetails()->kversion > 4.0) check :)

**Comment by xillibit** [comment]
Do-you use crypsis or blue eagle template ? This check is to make it working with crypsis

**Comment by Ruud68** [comment]
crypsis, but I think the issue is that the value for the check is not yet in b3. I have only patched this single file, not all the changes (waiting for rc1) :)

**Comment by xillibit** [comment]
It seems that a previous change that i had done has been forgot, will look in the evening

**Comment by xillibit** [comment]
Try now i have updated it
