### ISSUE TITLE
Page Class value from menu item

### ISSUE THREAD

**Issue by Flowman** [Kunena/Kunena-Forum#3112]
Can we add the pageclass_sfx to Kunena 4.0 views and layout? As this gives option to style specific menu options differently, and its a built in function in Joomla.

**Comment by 810** [comment]
Could you check if this is working ^^

**Comment by Flowman** [comment]
Guess that will work for the template blue_eagle. But in crypsis /components/com_kunena/template/crypsis/layouts/page/default.php there is no option for pageclass_sfx.

Only thing that needs to be change in default.php is this:
<div id="kunena" class="layout">
to:
<div id="kunena" class="layout<?php echo $this->options->get('pageclass_sfx'); ?>">

Cheers

**Comment by 810** [comment]
I have added the code, I'm closing the issue.
