### ISSUE TITLE
[K4.0] Wrong messages on Allowed File Types and Allowed Image Types

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3117]
It is the other way around.

If not allowed file types, there are the message: 
You need to use allowed file extension (.jpg, .jpeg, .gif, .png).

If not allowed image types, there are the message: 
You need to use allowed file extension (txt,rtf,pdf,zip,tar.gz,tgz,tar.bz2).

**Comment by 810** [comment]
crypsis or blue eagle or both

**Comment by rich20** [comment]
both templates

**Comment by xillibit** [comment]
It always the same message which is used when you have wrong file extension or wrong image extension : ``` You need to use allowed file extension```

**Comment by 810** [comment]
So the filetype name are switched

**Comment by 810** [comment]
On crypsis I get:
You need to use allowed file extension (.jpg, .jpeg, .gif, .png, .txt, .rtf, .pdf, .zip, .tar.gz, .tgz, .tar.bz2).

**Comment by 810** [comment]
You need 1 file extension on the setting. for getting the right error msg. 


Closing this issue for now.

**Comment by xillibit** [comment]
> You need 1 file extension on the setting. for getting the right error msg.

What you mean ?

**Comment by 810** [comment]
There is no issue, you get:
" You need to use allowed file extension (txt,rtf,pdf,zip,tar.gz,tgz,tar.bz2)."

**Comment by rich20** [comment]
It shows only allowed types in the message. That's ok. 
Example: If everything is forbidden there is the message:
You need to use allowed file extension ().
