### ISSUE TITLE
K4.0 Captcha setting stops new message

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3127]
When CAPTCHA Challenge for Guests = 1, and you have no setting for reCAPTCHA then the topics isn't working anymore. 

We need to return topic if there is no settings.

**Comment by xillibit** [comment]
In this case you have reCaptcha plugin enabled ?

**Comment by rich20** [comment]
This error exists only with Crypsis when reCaptcha plugin is enabled.
