### ISSUE TITLE
[K4.0] Template Manager : You can't install templates

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3165]
http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/133792-back-end-i-can-t-install-template-when-upload-zip-file

I've tested it. With Kunena 3.0 you can install Crypsis without poblem.

With Kunena 4.0 it gives the message:
Notice
Missing file to extract

**Comment by xillibit** [comment]
> I've tested it. With Kunena 3.0 you can install Crypsis without poblem.

Do-you have tested on same Joomla! version with k3.0 and k4.0 ?

**Comment by rich20** [comment]
Yes, tested with Joomla 3.4.1 and J3.4.2dev. Also with Joomla 2.5.
With Kunena 3.0 it works everywhere, but not with Kunena 4.0
