### ISSUE TITLE
Enable Category CSS Class Suffix in actual Topic / Posts view

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#3167]
The Category CSS Class Suffix works for the view of the category, but not for the messages themselves when you click on a topic, meaning you lose any styling you want to apply to the messages inside that category.

I would like to see the same suffix applied to the messages, so that if I add the suffix "ingame" to a category, the topic view picks up "messageingame" or similar, to allow for styling of all messages in that category.

**Comment by GJSchaller** [comment]
Example:

http://template.knightrealms.com/forum/The-Dragons-Claw-Inn.html

The category view has the fancy handwriting font, but when you go into a topic, that styling is lost.

**Comment by 810** [comment]
should be fixed now,, could you test it

**Comment by GJSchaller** [comment]
Was there a pull or patch?  Or is this in the current release (4.0.3) ?

**Comment by GJSchaller** [comment]
Under 4.0.3 - the main Category Listing is OK, as is the Category view, but in the Topics, the "kmsg" class is still unmodified by the new class.

**Comment by 810** [comment]
ok, so you want have .kmsg .category-ingame classes?

Ps We won't change blue eagle anymore.

**Comment by GJSchaller** [comment]
or even just .kmsg .ingame, so I can apply things to .ingame in my CSS.

Boss doesn't like Crypsis, prefers Blue Eagle - what are my options for support?

**Comment by GJSchaller** [comment]
Testing this on Crypsis on 4.0.5, the Category suffix is " ingame" (note the space in the front):

http://template.knightrealms.com/forum/The-Dragons-Claw-Inn.html

The Category listing is OK, but the Topics are still missing the suffix.

**Comment by 810** [comment]
I can add this, because like if your category color is red, then everything is red in the topic, it doesn't look good. 

If you still want it, then you need to make a template override
