### ISSUE TITLE
[K4.0] Crypsis : When ReCaptcha plugin is enabled registered users can't write

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3173]
The problem exists, when ReCaptcha plugin is enabled and CAPTCHA Challenge for Guests = Yes. Registered users can't write. Even if the correct code is entered.

**Comment by Ruud68** [comment]
Hi @rich20 , is this the bug for this report? http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/133757-bug-registered-user-cannot-post-in-kunena

**Comment by rich20** [comment]
In principle it's the same. With your workaround only users and guests can write. But not admins or moderators.

**Comment by 810** [comment]
@rich20 could you check the fix. For me it worked.
- Plugin enabled and with keys
- Enabled CAPTCHA Challenge for Guests
- CAPTCHA Challenge for Users = 0
- kunena keys empty

- [x] Reply guests
- [x] Reply users
- [x] Reply admin
- [x] New Topic guests
- [x] New Topic users
- [x] New Topic admin

**Comment by rich20** [comment]
- [x] Reply guests
- [x] New Topic guests
- [ ] Reply users
- [ ] Reply admin
- [ ] New Topic users
- [ ] New Topic admin

This is the last version which works for me. https://github.com/Kunena/Kunena-Forum/pull/3105 All later versions have this error.

**Comment by xillibit** [comment]
Let me look to this one
