### ISSUE TITLE
Cyrpsis 4.0.1 - Custom Topic Icons / Selectable Topic Icons

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#3193]
When Kunena Config "Selectable Topic Icons" is set to No, Crypsis 4.0.1 displays the default Topic Icons, even when a custom icon set is selected in the Category manager.  It appears to work fine when set to Yes.

**Comment by GJSchaller** [comment]
This looks like it applies to Blue Eagle, too.

**Comment by xillibit** [comment]
It was a bit intented to do it in this way

**Comment by GJSchaller** [comment]
That would mean I can only use custom topic icons, if I want to allow the users to choose them when posting.  This may be a language / wording issue - is the "Selectable Topic Icons" meant for the User to select them when posting, or the Admin to select them in the config?

**Comment by xillibit** [comment]
> is the "Selectable Topic Icons" meant for the User to select them when posting, or the Admin to select them in the config?

The admin can choose it in the backend

**Comment by GJSchaller** [comment]
Suggested fix - work it the same way the Category Icon is configured / chosen.  You can set a global option in the Crypsis settings, that is overridden by the Category manager.  Do the same with Topic Icons - it can already set in Category Manager, just add the global option to the Crypsis settings.

**Comment by GJSchaller** [comment]
This is also an issue in 5.0

**Comment by 810** [comment]
fixed and merged
