### ISSUE TITLE
[K4.0] Ban: delete all posts isnt working 

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3228]
I saw this issue since K3.0.6/K3.0.7.

When you ban a spammer, and select the option delete all posts.

Then its deleted. But you can still see the topic in the category, but delete. But you can't delete it fully.

**Comment by xillibit** [comment]
> But you can still see the topic in the category, but delete.

You mean deleted ?

**Comment by 810** [comment]
yes, but you can't remove it totally.
