### ISSUE TITLE
Load finfo only when exists

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3234]
https://github.com/Kunena/Kunena-Forum/blob/373adb19127d9f9b0fea46105e3cad09a64a38dd/libraries/kunena/attachment/attachment.php#L460

http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/133777-no-uploads-and-no-smileys?start=10#166077

**Comment by xillibit** [comment]
The other method instead finfo is deprecated is the reason why i use finfo

**Comment by 810** [comment]
do we need it? Or is it extra info, then we can just add if exists

**Comment by xillibit** [comment]
We need it to check if the attachment is an image or not

**Comment by xillibit** [comment]
FINFO extension is available in php default installation since php 5.3.0
