### ISSUE TITLE
Blue Eagle 4.0.1 - Responsive layout does not follow Tab Color settings

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#3247]
I have tab colors set for Blue Eagle 4.0, that can be seen on the right.  On the left, the default colors are being used for some of the Kunena Menu items.

![screen shot 2015-06-20 at 11 59 40 am](https://cloud.githubusercontent.com/assets/2761607/8268011/3204eb46-1744-11e5-8ad4-1e7188d513d9.png)

**Comment by 810** [comment]
I tried to fix it, ut then something else will break.

So I'm closing this issue, because we don't need to waste any time on Blue eagle anymore. We are deprecating the templating in the next version
