### ISSUE TITLE
[K4.0] Moderators can permanently delete

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3262]
It works via Permanent delete selected

![bildschirmfoto vom 2015-06-25 21 33 24](https://cloud.githubusercontent.com/assets/888847/8363857/329a197c-1b82-11e5-8def-94ab53567b8a.png)

**Comment by xillibit** [comment]
I had changed the rigths to have the permanent delete to be displayed for global moderators. You see that when you are a moderator or global moderator ?

**Comment by rich20** [comment]
Also category manager can permanently delete in his category. But if you change the rights for global moderators, it should also to be possible, choose this option in messages. Here missing the permanently delete option (see image). The moderator can permanent delete topics, but not single messages.
![bildschirmfoto vom 2015-06-26 16 38 02](https://cloud.githubusercontent.com/assets/888847/8380236/f56b3dd0-1c24-11e5-9183-386f66d9e15e.png)

**Comment by xillibit** [comment]
What i should do here ? I have done a PR which modify the behaviour : https://github.com/Kunena/Kunena-Forum/commit/4a68830a3096bb9d1116288bbfe1dc50de688e7e

**Comment by rich20** [comment]
When I wrote this report, I did not know yet, that it's a new feature.
Ok, your PR works. But the moderator can permanent delete only complete topics, not a single message. When moderators can permanently delete topics, then it should the same possible at a single message. In addition a setting would be optimal in the backend, whether it should be allowed for moderators.

**Comment by xillibit** [comment]
> Ok, your PR works. But the moderator can permanent delete only complete topics, not a single message.

Maybe i should revert the previous PR : https://github.com/Kunena/Kunena-Forum/commit/4a68830a3096bb9d1116288bbfe1dc50de688e7e

> When moderators can permanently delete topics, then it should the same possible at a single message. In addition a setting would be optimal in the backend, whether it should be allowed for moderators.

Maybe the rights should be managed in the category manager

**Comment by 810** [comment]
We need to add Global Moderator.

For now reverted back to Admin.
