### ISSUE TITLE
Crypsis - pagination always loaded

### ISSUE THREAD

**Issue by JoomFX** [Kunena/Kunena-Forum#3280]
In Crypsis the pagination is always loaded, even if there is no need for it, ie if there is only one page.

In Blue Eagle the pagination is loaded only if there are 2+ pages.

Sorry, forgot to mention that this is for Kunena/Crypsis 4.0.2 (it was the same in 4.0.1 as well).

**Comment by 810** [comment]
This has be done by purpose, its fixed also a issue, when a moderator is on the second page, and there is just 1 row, and he is moving that topic. The K3.x version stays on the second page, but there are no pagination, so you can't go back to page 1.
