### ISSUE TITLE
Blue Eagle (4.0.x) - Sub-Forum icons for Responsive CSS

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#3289]
In the 4.0.x Responsive CSS, need to add:

#Kunena span.kreadforum-sm, #Kunena span.knotloginforum-sm, #Kunena span.kunreadforum-sm {display:none}

At the current moment, the Top Level Category icons vanish when the responsive width kicks in, but the Sub-Category icons do not.

**Comment by 810** [comment]
merged
