### ISSUE TITLE
[K4.0] Use English On Missing Strings not working

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3292]
http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/134096-k4-0-3-error-use-english-on-missing-strings
http://www.kunena.org/forum/k-4-0-general-questions/134137-use-english-on-missing-strings-not-working-as-expected

This problem exists with both templates Blue Eagle and Crypsis.

**Comment by rich20** [comment]
I've tested it on 4 different pages. It seems it has something to do with Joomla. It works on Joomla 2.5 pages, but not on pages with Joomla 3.4.

**Comment by 810** [comment]
I'm closing this one for now, if its back, we can reopen it again

**Comment by rich20** [comment]
> I've tested it on 4 different pages. It seems it has something to do with Joomla. It works on Joomla 2.5 pages, but not on pages with Joomla 3.4.

I'm not sure whether these tests were correctly. I know no longer whether I had tested with debug mode. Without debug it works also on my pages.

But we have again two users with this problem. No idea if it's a bug or not.

**Comment by rich20** [comment]
http://www.kunena.org/forum/k-4-0-installation-and-upgrade/134423-language-problem-in-crypsis-template#167589
http://www.kunena.org/forum/k-4-0-general-questions/134463-crypsis-not-translate
I think, we should reopen it. I found the bug, but don't know why is it so. Use English On Missing Strings works for .kunena_tmpl_crypsis.ini only then, if you this file or all included strings completely removing.
