### ISSUE TITLE
private/public ban reason not shown

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3302]
As user who has been banned gets no further info why he has been banned (private reason?)
There's just a notice on top: "You have been banned! You do not have access to this function."

Also the public reason is not shown at all, not for guests nor registered users.

Same for all three templates.

**Comment by xillibit** [comment]
Which version of Kunena are-you using ?

**Comment by betteryouthanme** [comment]
4.0.3

Don't know if it's a bug or just never been available.

But as you can enter these information on a new ban, it would be nice if shown somewhere.

**Comment by rich20** [comment]
Choose in the configuration (tab) User the option "Show Banned Reason = Yes" and you see it in his profile.

**Comment by betteryouthanme** [comment]
Shame on me. Can be closed.
Though i don't really understand the difference between private reason and ban comment.
