### ISSUE TITLE
Subscribe's box is always enabled

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#3303]
If I create a new topic then the subscribe's box is always enabled, but I didn't allow this feature.

Kunena 4.0.3
![image](https://cloud.githubusercontent.com/assets/1657924/8763677/b7ca6050-2da9-11e5-8a33-5d0b62aae6e2.png)
Crypsis 4.0.3
![image](https://cloud.githubusercontent.com/assets/1657924/8763671/9256329a-2da9-11e5-845b-712d51750bb3.png)
Blue Eagle 4.0.3
![image](https://cloud.githubusercontent.com/assets/1657924/8763721/cc2a832a-2dab-11e5-8570-ef3dde21d222.png)

**Comment by 810** [comment]
click on edit user. Go to settings There you will see the setting by the user.

change it to no, then the it will be disabled.

For blue eagle its only the kunena configuration setting.

**Comment by 810** [comment]
We have improved the subscribme.

But if you wan to disable this function, then you need to set in the database everyone on 0, then you need to hide the field by css.

This feature is always turned on.

**Comment by csbalazs** [comment]
I think it would be better if it was turned off by default, who want this feature to turn on. I think the people are so accustomed to this thing.
On other hand, I set everyone on 0, and what happens with the new registration?

**Comment by 810** [comment]
Forums are mentioned for communicating, so receiving mails that there are new replies, improved the interactive. So its needed by default.

In the next version we updated the sql, it will be -1 (default) on new users, so if you set No on the configuration, then the checkbox is unselected.

If you don't like the features you must hide the feature by the css.
