### ISSUE TITLE
Meaningless string value

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#3306]
Meaningless string value.

In Crypsis:
![image](https://cloud.githubusercontent.com/assets/1657924/8765392/f233f4e4-2e09-11e5-85ae-83ceadf31b52.png)
In Transifex:
![image](https://cloud.githubusercontent.com/assets/1657924/8765396/245ae87e-2e0a-11e5-8d31-3f6aa857ac05.png)
en-GB.com_kunena.views.ini (site)

Kunena 4.0.3
Crypsis 4.0.3

**Comment by 810** [comment]
No its correct.


Like "Please login or register to join the conversation" there are 2 option, if the settings are enabled
