### ISSUE TITLE
[K4.0] Crypsis : Wrong avatars in the menu item Recent Posts

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3307]
It shows the avatar of the user, which has recently written in this topic. You can see it in your profile.

![bildschirmfoto vom 2015-07-20 20 27 45](https://cloud.githubusercontent.com/assets/888847/8784270/65664008-2f21-11e5-9b67-f42a523c3b80.png)

**Comment by xillibit** [comment]
It seems that the avatar is different because your are using discuss plugin ?

**Comment by rich20** [comment]
No discuss plugin and tested on two different pages.
Blue eagle shows my post time and avatar correctly. The New indicator shows that someone has written afterwards.
![bildschirmfoto vom 2015-07-21 15 15 19](https://cloud.githubusercontent.com/assets/888847/8802506/538d0f5a-2fc2-11e5-8892-987c232e2919.png)


Crypsis also shows the New indicator. But even the post time and avatar comes from the user which has written afterwards.
![path5719](https://cloud.githubusercontent.com/assets/888847/8802900/48c8c012-2fc4-11e5-9ad7-3b3b6dfd85e9.png)

**Comment by 810** [comment]
which view is this?

**Comment by 810** [comment]
please test fix

**Comment by rich20** [comment]
- [x] Success
