### ISSUE TITLE
AUP not working on hmvc.

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3309]
Also fatal error when enable aup profile.

**Comment by xillibit** [comment]
With which AUP version do-you have tried ?

**Comment by 810** [comment]
2.0.1

**Comment by xillibit** [comment]
You men the followign fatal error : Warning: array_merge(): Argument #2 is not an array in C:\wamp\www\joomla3.4.1\libraries\cms\router\router.php on line 350
Fatal error: Unsupported operand types in C:\wamp\www\joomla3.4.1\libraries\cms\router\router.php on line 234

To avoid this kind of issue you need to create an menu item pointing to AUP

**Comment by 810** [comment]
Yes, indeed.

But I can't see any points under the message profile box. The code is there
