### ISSUE TITLE
Support PDO Driver

### ISSUE THREAD

**Issue by acs-ferreira** [Kunena/Kunena-Forum#3310]
Since 3.4 PDO driver is the new reference for us when deploying Joomla.
Is PDO support on the Roadmap ?

Thanks.

**Comment by xillibit** [comment]
Are-you talking about that : https://github.com/joomla/joomla-cms/pull/6175 ?

**Comment by acs-ferreira** [comment]
No, when upgrading Kunena, we've a message ````PDO is not supported, please switch to MySQL````

**Comment by xillibit** [comment]
The check in install part check database settings against mysql or mysqli, i will modify it to check against PDO too

**Comment by xillibit** [comment]
How to reproduce the issue ? In your php.ini what extensions do-you have enabled ?

**Comment by acs-ferreira** [comment]
# To reproduce
1. Install Kunena 4.0 with MySQL(i) as driver on on Joomla Configuration
2. Swicth to PDO on Joomla Configuration
3. Try to update from 4.0 to 4.0.3

# php.ini
````
--enable-fpm
--enable-opcache
--enable-sockets
--enable-pcntl
--with-readline
--enable-ftp
--enable-shmop
--with-snmp
--enable-soap
--enable-zip
--enable-calendar
--with-openssl
--with-curl
--with-mysql
--with-mysqli
--with-pgsql
--with-pdo-mysql
--with-pdo-sqlite
--with-pdo-pgsql
--with-unixODBC
--with-pdo-odbc
--with-bz2
--with-zlib
--with-gd
--enable-gd-native-ttf
--with-freetype-dir=/usr
--with-jpeg-dir=/usr
--with-png-dir=/usr
--enable-exif
--with-xsl
--enable-xslt
--with-xslt-sablot
--with-mcrypt
--enable-mbstring
--enable-intl
--enable-bcmath
--with-gettext
--with-tidy
--with-imap
--with-imap-ssl
--with-kerberos
````

**Comment by 810** [comment]
Ok we have added pdo support from the next kunena version 4.0.11
