### ISSUE TITLE
[K4.0] Max Links in message will divided by three if you insert a image link

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3318]
You have to many links in your message, please decrease it!
Example:
Max Links in message = 6
You can put in the message either 2 image links - or 1 image and 1 normal link
Max Links in message = 9
You can put in the message either 3 image links - or 2 images and 1 normal link, and so on

**Comment by 810** [comment]
Don't have this issue on K4.0.4.dev2

Max Links in message = 6
Can upload 4 links and 2 inserted images from attachments


Or are you use embed images

**Comment by rich20** [comment]
Images via url such as [img]address.png[/img]

**Comment by xillibit** [comment]
> Max Links in message = 6
> You can put in the message either 2 image links - or 1 image and 1 normal link

I can put six embed images via url such as [img]address.png[/img], so i'am not able to reproduce the issue

**Comment by rich20** [comment]
You've tried as admin? A admin has no limit. Please try it as registered user.

**Comment by xillibit** [comment]
I have tested as registered user and i'am to reprodue the issue, but if you insert two images (with [img]address.png[/img]) it counts 6 because there 4 http and 2 href
