### ISSUE TITLE
[K4.0] Crypsis B3: Status Text

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3321]
Nothing happens on click.
![status-text](https://cloud.githubusercontent.com/assets/8537297/8924517/eb4cc6d2-34fe-11e5-83dd-5a9044426620.jpg)

**Comment by 810** [comment]
for me it works:
![modal](https://cloud.githubusercontent.com/assets/876623/8936146/e9349de6-3550-11e5-9852-c3f2583fdcf8.jpg)

**Comment by betteryouthanme** [comment]
Okay maybe i did something wrong. Just copied the recent github development files and replaced the crypsisb3 folder in templates. There's no setting in Kunena which enables/disables the status message or?

**Comment by 810** [comment]
nope not yet

**Comment by 810** [comment]
This is a bug on t3 framework, works normal on stock Bootstrap 3.3.5 template
