### ISSUE TITLE
[K4.0] Images not showing in RSS feed	

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3328]
http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/134352-images-not-showing-in-rss-feed

It's the same on k.org. It shows only the code  [File Attachment: imagename.jpg]

**Comment by sozzled** [comment]
Images used to show in RSS feeds from http://kunena.org/forum when the site was using K 3.0.8

If it doesn't work now (at K.org) is it something that has changed since the site was updated to K 4.0

**Comment by 810** [comment]
merged
