### ISSUE TITLE
[K4.0] Hide image for guests - Hint does not appear 2

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3333]
#### Blue Eagle

- [ ] If you only add images in messages (without attachments), guests see both. Image and the text:
"This message has an attachment image.
Please log in or register to see it.". 

The same is if you only add a attachment directly in the message:
This message has an attachment file.
Please log in or register to see it. 

Sorry, I had found the error too late.

**Comment by xillibit** [comment]
I have tried by inserting just images without attachments, i have only one message : 

![sdqsdre](https://cloud.githubusercontent.com/assets/876395/9139603/8bd6eec8-3d2b-11e5-8bc9-cd973dbe687a.jpg)

**Comment by rich20** [comment]
If you set "Show Images for Guests = Yes" guests see both (image and text).

**Comment by xillibit** [comment]
I have just tried and set "Show Images for Guests = Yes" guests see both (image and text), as a guest i can see the image but i can't see the messages text

**Comment by rich20** [comment]
With which version have you tested? The error exists since this merge https://github.com/Kunena/Kunena-Forum/pull/3327. Try it with the newest develop and you will see it.

**Comment by rich20** [comment]
This problem still exists. Tested with a new Joomla and Kunena-Dev installation.
Please try followings:
Set "Show Images for Guests = No" and save it. Then go back to set "Show Images for Guests = Yes" and save it again. Then you see the error.

**Comment by 810** [comment]
fixed and merged

**Comment by rich20** [comment]
#### Crypsis and Blue Eagle

Now is missing the hint for hidden attachments if is set:
Show Images for Guests = Yes
Show Attachments for Guests = No

**Comment by 810** [comment]
fixed
