### ISSUE TITLE
Feature: Read only state

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3363]
https://www.akeebabackup.com/documentation/akeeba-ticket-system/off-line-schedule.html

So users can read messages, but can't write.

**Comment by xillibit** [comment]
If you change categories to remove write permissions, is-it don't do the trick ?

**Comment by 810** [comment]
If you have <30 categories you need to reverse all settings. With just 1 option should be better to set in read only mode

On Wed, Sep 2, 2015 at 7:59 AM -0700, "Florian DAL FITTO" notifications@github.com wrote:
If you change categories to remove write permissions, is-it don't do the trick ?

---

**Comment by 810** [comment]
merged on k50
