### ISSUE TITLE
When you logout on the user page, you need to login again

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3378]
When you have enabled: "Allow Guests to see User Profiles"

You should see the profile, when you logout on the users profile. Now you get a login page.

**Comment by xillibit** [comment]
Only on crypsis ?

**Comment by 810** [comment]
Both. Because its protected

On Wed, Sep 2, 2015 at 7:58 AM -0700, "Florian DAL FITTO" notifications@github.com wrote:
Only on crypsis ?

---

**Comment by 810** [comment]
Ok, seems fixed now. closing this one
