### ISSUE TITLE
Crypsis: Replace calendar with datepicker jquery plugin

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3379]
For Crypsis and Crypsisb3
- [x] Poll modal
- [ ] Edit announcement

**Comment by xillibit** [comment]
I would put this into 4.1 only

**Comment by 810** [comment]
that's fine

**Comment by xillibit** [comment]
There is this one : https://bootstrap-datepicker.readthedocs.org/en/latest/#, is-it ok to use this one ?
