### ISSUE TITLE
[K4.0] poll, "see more" link does not work

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3380]
![screenshot_1](https://cloud.githubusercontent.com/assets/8537297/9423088/fab651e6-48b4-11e5-8a01-9535b76a8d22.png)

Instead of showing all voters the site jumps to the top.

**Comment by 810** [comment]
also on blue eagle, right?

**Comment by betteryouthanme** [comment]
Sorry have not checked, but yes for all 3 of 'em

**Comment by xillibit** [comment]
I need to check how it worked with K3.0.8
