### ISSUE TITLE
[K4.0] Crypsis B3 - Editor

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3393]
- [x] bbcode colors do not match (see red & orange)
- [x] theres a space in the image start tag [img ](still usable though)
- [x] i'd suggest to remove the popdown menu for emoticons, a simple click on the icon is sufficient
- [x] new tab-based preview solution does not work yet

**Comment by 810** [comment]
The space on img tag, is the param for size, so if you don't have entered a size, you see an extra space
