### ISSUE TITLE
Kunena 5.0

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3396]
#### Features K5.0.0
- [x] Bootstrap Datepicker
- [x] Easy Social
- [x] Easy Profile
- [x] Instagram
- [x] Soundcloud
- [x] Backend: filter by ip on user manager
- [x] Administrator to manage (edit/change) another user's data
- [x] Easy Blog
- [x] Read only State https://github.com/Kunena/Kunena-Forum/pull/3548
- [x] Social icons
- [x] Social Share https://github.com/Kunena/Kunena-Forum/pull/3465
- [x] Administrator to manage (edit/change) another user's data #276  
- [x] Altauserpoints
- [x] Announcements: publish and end date
- [x] Add the possibility to generate report configuration in anonymous way
- [x] PHP7 Support
- [x] Codeception unit tests
- [x] 5 star rating
- [x] Labels
#### Features K5.1.x TODO
- [ ] Unread
- [ ] Auto subscription
- [ ] @ mention
- [ ] WYSIWYG editor plugin
#### Removed
- [x] `Joomla < 3.4`
- [x] None Hmvc Templates (blue Eagle)
#### Improvements
- [x] Removed deprecated code
- [ ] Remove legacy code

**Comment by xillibit** [comment]
> More Genders

What is that ?

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/pull/2453

**Comment by 810** [comment]
Bugs after removing deprecated code:
- [x] fix save config
- [x] Remove old captcha settings
- [x] Add save button on edit user
- [ ] Show more user settings
- [x] File manager: No items to show. ?> 
- [x] Smilies: Fatal Error: Class 'KunenaAdminTemplate30' not found in components/com_kunena/template/layouts/pagination/list/default.php on line 16
- [x] Recreate menu is broken/ also on new install no kunenamenu
- [x] Report Configuration: add copy button
- [x] Tools: change icon github

**Comment by sozzled** [comment]
"Removed Joomla" in K 5.0?  I understand what you mean but it was a clumsy way to write "All J! 2.5 code has been removed from K 5.0"

**Comment by 810** [comment]
@sozzled the markdown parser has hidden the text after it.
