### ISSUE TITLE
Enable Continous Integration testing via Travis CI

### ISSUE THREAD

**Issue by fxstein** [Kunena/Kunena-Forum#3406]
Perform automatic integration testing for every commit and pull request via free Travis CI testing and enforce coding best practices via code linting. 

Example:
https://github.com/sonnym/travis-ci-drupal-module-example

**Comment by 810** [comment]
Could you do a pr, with the travis.yml , and the install xml ect.

I have set it up. only needing the files

**Comment by 810** [comment]
ok, travis is up and working, I only need to find how to implant codestyl check

**Comment by fxstein** [comment]
I did a little searching and found this: 

http://stackoverflow.com/questions/378959/is-there-a-static-code-analyzer-like-lint-for-php-files

PHP Code Sniffer seems to be a good choice.

**Comment by 810** [comment]
I have included that one already in the travis, but when I add it. I get a error:
577ERROR: the "/home/travis/build/810/Kunena-Forum/.travis/phpcs/Joomla" coding standard is not installed. The installed coding standards are PHPCS, PSR1, Squiz, MySource, PEAR, Zend and PSR2

I need to find out how to do that symlink on git. (git submodules)
https://github.com/redCOMPONENT-COM/redCORE/tree/develop/.travis/phpcs

I asked Javier Gómez how to do that. waiting for a response.

**Comment by 810** [comment]
ok, all is running, closing this one
