### ISSUE TITLE
Add new event plugin: new topic

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3437]
So plugins can add new features on the new topic page.

**Comment by aishafarooq** [comment]
Do you need a loan? Are you in a financial crisis and need money?. Do you need loan to settle your debt or pay your bills or start a business?. You have a low credit score and you are finding it hard to obtain any kind of loan?. Here's your chance!. We are a private financial lender offering unsecured loans at an interest rate of 3% ranging from 6 months to 20 years which you can pay in installments. Flexible repayment terms from 6 months to 20 years.The amount applied for gets deposited directly into your bank account as soon as possible.The loan is unsecured, no collateral is required No Credit checks No Branch visits Minimal Documents Required Contact via Email: skyfunddept@gmail.com
