### ISSUE TITLE
[K4.0] Crypsis B3 - anonymous posts

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3442]
(re)style editor for b3 template if "anonymous post" is activated in back-end. (same for quick reply)

![screenshot_1](https://cloud.githubusercontent.com/assets/8537297/9830560/8fb30c56-5933-11e5-81e7-742617d50a29.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/8537297/9830587/d762e200-5934-11e5-8872-778541a24b63.png)

The info box "You are posting the message as a 'Guest'" is confusing (at least for me) ;)

**Comment by sozzled** [comment]
It may be better if we could give this issue a more "public" airing by discussing it at the forum http://www.kunena.org/forum

I cannot say that I've seen this issue before and I do not know the circumstances required to reproduce the message, either.  As you say, this may be something that occurs only for you.

GitHub is primarily a software development repository where ideas and code are considered, discussed, debated and (sometimes) rejected.  The forum at K.org has the benefit of allowing more people to contribute to the discussion—it also has the advantage of better security and the ability to post your Kunena configuration report.  It's possible that you've identified a defect but, until we've had a better opportunity to look at the evidence, I wouldn't jump in too quickly and say this is a GitHub issue at this time.

**Comment by betteryouthanme** [comment]
updated the report. Sorry for the inconvenience

**Comment by betteryouthanme** [comment]
"You are posting the message as a 'Guest'" is still confusing imo because you are **not** posting as a guest, until you have checked the "anonymous post" box..
You can change your username but it has no effect if you do not tick the anonymous option.

I don't see why this guest message even comes up at all.

It would be clearer if theres the anonymous option with explanation, and if selected, the username becomes editable. "You are posting the message as a 'Guest' should be removed as it does not make sense to me but maybe i got something wrong?

**Comment by 810** [comment]
Its there, because you don't reply under your own name, so you are a guests, That's why its there, to inform you, you reply with a different name or not logged in.

**Comment by betteryouthanme** [comment]
Even registered users get this message, no matter if they want to post as a guest or not. Only if you change your username you post anonymously (as guest). But the message suggests you post always as guest.
Not going to use anonymous option anyway as I don't need it. For me it was misunderstanding.
