### ISSUE TITLE
Check attachments size on upload take care of avatar setting instead of images/files settings

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#3466]
See : http://www.kunena.org/forum/k-4-0-general-questions/134726-update-4-0-6#168954

**Comment by 810** [comment]
avatar size = 290kb

test 1:
avatar size setting = 350kb
upload image size setting = 1500kb

Result:
Avatar uploaded correct

test 2:
avatar size setting = 150kb
upload image size setting = 1500kb

Result:
Avatar not uploaded, showed correct error

test 3:
avatar size setting = 350kb
upload image size setting = 150kb

Result:
Avatar uploaded correct.

test 4:
avatar size setting = 150kb
upload image size setting = 150kb

Result:
Avatar not uploaded, showed correct error.

**Comment by xillibit** [comment]
You have done the test in reverse, you need to check the upload of attachments images

Just re-do the same test but by uploading attachments images

**Comment by 810** [comment]
Should be fixed now, can someone confirm

**Comment by rich20** [comment]
-  [ ] Failed - Image upload needs both settings. 

Larger images can be uploaded only if you set both options higher
Maximum Image File Size 
and 
Maximum File Size

**Comment by rich20** [comment]
It's only with Blue Eagle. With Crypsis works the setting corect.

**Comment by 810** [comment]
lasted build:

1) template: blue eagle
2) max avatar size = 2400kb , max image size = 150kb, max file = 120kb
3) Avatar 380kb
4) Result: Avatar uploaded successfully.
Your profile has been saved.

**Comment by rich20** [comment]
> You have done the test in reverse, you need to check the upload of attachments images
> Just re-do the same test but by uploading attachments images

I've tested also this. Or did he meant avatars? Now is the problem with upload images in messages. That's what I meant. With avatars it works.

**Comment by 810** [comment]
yes, this issue is only with the avatar upload.

**Comment by 810** [comment]
fixed
