### ISSUE TITLE
[K4.0]  Wrong text info in admin views.ini line 723

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3469]
> The Prune Categories function allows you to prune topics where there have not been any new posts during the specified number of days. **This does not remove stickies or locked topics and these must be removed manually. Topics in locked categories cannot be pruned.**

The sentences 2 and 3 are not correct. With this setting you can remove all topics. Also in locked categories.
![bildschirmfoto vom 2015-10-04 03 35 43](https://cloud.githubusercontent.com/assets/888847/10266058/2f1b9f60-6a4b-11e5-9ddf-d7b89b1a91ee.png)

**Comment by xillibit** [comment]
I need to check why it prune too topics in locked categories or stickies topics

**Comment by 810** [comment]
The function is correct, we only need to change the text.
because you selected "All Topics" and the other option "Keep sticky: no"
