### ISSUE TITLE
Crypsis : Template Basic Settings - Three options should be removed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3470]
These three options are only for Blue Eagle

![bildschirmfoto vom 2015-10-06 01 58 15](https://cloud.githubusercontent.com/assets/888847/10297070/b319865e-6bce-11e5-8593-18ce189c4bc7.png)

**Comment by 810** [comment]
I think, if we remove this, some features don't work anymore, need to look at it.

**Comment by 810** [comment]
We still support this for k5.0, closing this issue
