### ISSUE TITLE
[K4.0] Blue Eagle : Anonymous Image Upload didn´t run (Error 500)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3471]
http://www.kunena.org/forum/kunena-4-0-support-reporting-defects/134787-anonymous-image-upload-didn-t-run-in-kunena-4-x
The exact error message is: You need to use allowed file extension ().
This error exists only with Blue Eagle.

**Comment by 810** [comment]
Seems to be fixed on new build @rich20 could you test it again.

**Comment by rich20** [comment]
Still the error message:

 Error
You need to use allowed file extension ()

**Comment by 810** [comment]
what are your settings for this, I don't have this error message

**Comment by rich20** [comment]
Category Setting:
Allow anonymous messages: = Yes
By default post replies as: = Anonymous user

**Comment by 810** [comment]
looks like a js conflict or something, on hmvc its working, can't find it yet. but I think we can close this one, on K5.0. So the issue stay open until K5.0

**Comment by rich20** [comment]
There also a missing script in Crypsis. If you mark the checkbox it changes no to anounymous name. You must manualy edit the name.

![bildschirmfoto vom 2015-11-13 22 07 59](https://cloud.githubusercontent.com/assets/888847/11157977/370b63b6-8a55-11e5-91c9-2b840b6efe80.png)

**Comment by 810** [comment]
could you retest this for K5.0

**Comment by rich20** [comment]
With Crypsis is the upload bug not present.
