### ISSUE TITLE
[K4.0]  You can't quote hidden text

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3474]
http://www.kunena.org/forum/k-4-0-general-questions/134806-quote-hide-text#169257
Confirmed.

output is:
`[quote="rich" post=170][/quote]`
should be
`[quote="rich" post=170][hide]text[/hide][/quote]`

**Comment by 810** [comment]
This is because the extra security check, so hidden text should never showed for normal users.

if we remove that, then everyone can read the hidden text.

**Comment by rich20** [comment]
> This is because the extra security check, so hidden text should never showed for **normal users**.

You mean guests? When quote is `[quote="rich" post=170][hide]text[/hide][/quote]`, guests see only
Part of the message is hidden for the guests. Please log in or register to see it.

**Comment by 810** [comment]
yes, correct for guests.

If we allow the hidden in quote, then also the rss can see the hidden text.
