### ISSUE TITLE
Dashboard -> Options -> ACL permission - Joomla or Kunena issue?

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3480]
If you create a own Kunena Administrator group it works fine. Kunena admins receive only acces for Kunena in the backend. 

![bildschirmfoto vom 2015-10-10 19 32 05](https://cloud.githubusercontent.com/assets/888847/10413084/f621f5d0-6f9d-11e5-9259-c7324923b3c0.png)

So far so god. But if you logout and login again in the backend, it's missing the navigation. You find Kunena only via url `/administrator/index.php?option=com_kunena`

![empty](https://cloud.githubusercontent.com/assets/888847/10413110/87416384-6f9e-11e5-837b-c03e7764f369.png)

**Comment by 810** [comment]
try with the help page, if there is the same. Then its a joomla bug

**Comment by rich20** [comment]
Ok, it's a Joomla bug. I've tested it with others features such as (Joomla) user manager. I can edit users but it is missing the navigation above.
