### ISSUE TITLE
Strange container height

### ISSUE THREAD

**Issue by MineMine** [Kunena/Kunena-Forum#3503]
![image](https://cloud.githubusercontent.com/assets/6129171/10875096/f1ad43a2-8171-11e5-92ce-4ca93d100530.png)

kpost-topicicons and kpost-toolbar have strange height 
and I want to know what is the problem :) 

I'm using Kunena 4.0.6 with Joomla 3.4.5

**Comment by 810** [comment]
Please use the kunena support forum, for questions about a conflict with your joomla template.

**Comment by MineMine** [comment]
okay :D 
thanks for replying
