### ISSUE TITLE
Can't upload svg with fileinfo module

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3507]
When you have enable fileinfo module you can't upload a svg file.

mime: image/svg+xml

**Comment by xillibit** [comment]
Why you can't send a svg file ? The mime type for svg is right defined in all settings ?

**Comment by 810** [comment]
yes, when I disable the fileinfo module, then I can upload the svg, but when turned on, I can't upload.

**Comment by sozzled** [comment]
See also #3260 
I thought Matias suggested that the PHP fileinfo() module was unnecessary?  Many sites do not include fileinfo().  I thought you abandoned fileinfo() in K 4.0.  Perhaps I was wrong.  Perhaps it would be a better idea to put this on the agenda for K 5.0?

**Comment by 810** [comment]
No. Its still there. There is a check for it.

**Comment by sozzled** [comment]
Ah, sorry, #3260 was a different issue entirely—a check made during the Kunena installation process in installation.script.php—and this file in K 4.0.6 is the same as the file in K 4.0.3.  I was confused where I read "fileinfo()" and wondered what you were talking about.  Forget my interruption.

**Comment by 810** [comment]
mhh now its working again, maybe fix on php

fyi:
add svg on filetype and add image/svg+xml on mime type

**Comment by 810** [comment]
reopen, crypsis upload isn't working with svg
