### ISSUE TITLE
Crypsis: Target topic does not change to another category

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3517]
Move topic or move message. If you want move to another category, the target topics stays from the first category.
Example: Move from "Welcome Mat" to "Suggestion Box". You see the target topics from Welcome Mat (image 1). Now I switch to Suggestion Box. The target topics are the same (image 2)
![bildschirmfoto vom 2015-11-11 19 37 18](https://cloud.githubusercontent.com/assets/888847/11099978/b6c38ed8-88ae-11e5-9517-230e1f57c7aa.png)
![bildschirmfoto vom 2015-11-11 19 39 22](https://cloud.githubusercontent.com/assets/888847/11099984/c1a72652-88ae-11e5-817d-ee300853beb3.png)

**Comment by 810** [comment]
Looks like we miss some js from media\kunena\js\default.js

@xillibit could you convert this to jquery on the crypsis

**Comment by 810** [comment]
merged
