### ISSUE TITLE
[K4.0.7]  Blue Eagle: It shows nowhere topic icons (Recent Topics, Editor etc..)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3521]

**Comment by 810** [comment]
For me it works.

**Comment by 810** [comment]
mh on  J35 not

j34:
/components/com_kunena/template/blue_eagle/images/topicicons/user/default.png

j35:
/media/kunena/topicicons/default/user/default.png

**Comment by 810** [comment]
fixed
