### ISSUE TITLE
Issue with Crypsis 4.0.7 for Kunena - tablet only

### ISSUE THREAD

**Issue by collector00** [Kunena/Kunena-Forum#3540]
I was hoping someone could assist with this issue within Crypsis. Everything looks good on a desktop and mobile device, but not on a tablet. The columns are not spaced appropriately and because of that, the replies/views column is so narrow, the Replies/Views do not align properly. On a tablet, the Last Post column takes up about 75%, subject is about 25% and the replies/view and mark (on the right side of the page) take up the remaining 25%. In fact the mark column (on the right side of the page) appears outside the main "box". See image.
![crypsis_tablet_view](https://cloud.githubusercontent.com/assets/15931591/11282797/42cab886-8ecf-11e5-957b-fa5a763c9743.png)

**Comment by 810** [comment]
Hi, do you have a link for me. so I can check it, also what is the screen size, when you have this issue.

**Comment by collector00** [comment]
go2screening.com is the URL (click Forum). I also noticed that once you select a thread, within the messages the users information appears below the message box (should be to the right or not visible). This is only occurring on tablets.

**Comment by 810** [comment]
I can't access your site, blacklisted (nl)

**Comment by collector00** [comment]
I'm not sure what you mean. Where is it blacklisted? Perhaps you can provide more detail but I receive visitors all the time and have had no issues that I'm aware of. http://go2screening.com/

**Comment by 810** [comment]
![2015-11-22 1](https://cloud.githubusercontent.com/assets/876623/11324301/3cc4e0f4-912e-11e5-9308-bc04ef9eb630.png)
