### ISSUE TITLE
[K4.0.7] Upgrade:  Profile setting "Select subscription as default = Yes" (not default)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3541]
This fix https://github.com/Kunena/Kunena-Forum/pull/3304 works only with a new installation. If you upgrade from a older version the setting is "Select subscription as default = Yes". (tested upgrades from K 3.x versions to K4.0.7)

![bildschirmfoto vom 2015-11-19 19 43 00](https://cloud.githubusercontent.com/assets/888847/11283719/59632df8-8f06-11e5-9ed0-92dc9eae220a.png)

**Comment by 810** [comment]
No the database has changed the table correct "canSubscribe default = 1" to "canSubscribe default= -1" 

But this doesn't changed old users, only new users. Because otherwise the user settings are gone, then the user will complain that he has disabled the option. and now he is receiving mails

**Comment by rich20** [comment]
Then I can close this issue?
