### ISSUE TITLE
Backend: Attachement link to image 404

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3545]
The link to the image are wrong, it opens the link with administrator between them.

**Comment by xillibit** [comment]
I had fixed that in 4.0.4 or 4.0.5, i don't remeber exactly

**Comment by 810** [comment]
that's ok, but you forgot to change also line 16

https://github.com/Kunena/Kunena-Forum/pull/3447/files

The images are loaded correct, but a link is wrong

**Comment by 810** [comment]
I will upload a fix now

**Comment by 810** [comment]
fixed and merged
