### ISSUE TITLE
Crypsis shows no captcha field with Joomla 3.5 beta

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3579]
I've tested it on more pages. The captcha works correct with Joomla registration. 
At Reply it shows only the text "Enter code here" and at Quick Reply it shows nothing.

**Comment by xillibit** [comment]
Do-you have tested with a more recent build of Joomla! 3.5 ?

**Comment by rich20** [comment]
Yes I've tested it with more Joomla 3.5. Also a upgrade from Joomla 3.4 to 3.5. After upgrade the captcha field is gone.

**Comment by rich20** [comment]
~~Ok, it was a Joomla bug. With Joomla 3.5.6 dev it works again.~~

**Comment by rich20** [comment]
We need a fix for this. Otherwise we have no captcha with Joomla 3.5
https://github.com/joomla/joomla-cms/pull/8867
