### ISSUE TITLE
Backend user edit produced an error

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3583]
Fatal Error: Class 'Joomla\String\Stringhelper' not found in components/com_kunena/template/user/edit.php on line 103

**Comment by 810** [comment]
try the lasted version, I merged it already

Only J3.5.X is supported from now

**Comment by rich20** [comment]
I test only with J 3.5.0 beta now. But this error is with K 5.0 from today. I wanted to test your last merge "Show Moderators in Category Index"

**Comment by 810** [comment]
fixed

**Comment by rich20** [comment]
hm.. not fixed.

**Comment by 810** [comment]
fixed and merged
