### ISSUE TITLE
You can't edit user profiles after a clean installation (database error)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3584]
Error
Unknown column 'aim' in 'field list' SQL=UPDATE `#__kunena_users` SET `view`='',`signature`='',`moderator`='0',`ordering`='0',`posts`='0',`karma`='0',`karma_time`='0',`group_id`='1',`uhits`='0',`personalText`='',`gender`='0',`birthdate`='1-1-1',`location`='',`websitename`='',`websiteurl`='',`rank`='0',`hideEmail`='1',`showOnline`='1',`icq`='',`aim`='',`yim`='',`microsoft`='',`skype`='',`twitter`='',`facebook`='',`google`='',`myspace`='',`linkedin`='',`delicious`='',`friendfeed`='',`digg`='',`blogspot`='',`flickr`='',`bebo`='',`thankyou`='0',`canSubscribe`='-1',`userListtime`='-2',`status`='0',`status_text`='',`instagram`='',`qq`='',`qzone`='',`weibo`='',`wechat`='',`apple`='',`vk`='',`telegram`='' WHERE `userid`='218'

**Comment by 810** [comment]
can you try again.

Don't have this issue on lasted version

**Comment by rich20** [comment]
The error still exits. Did you have before installation removed Kunena along with database? The error exists only with a new installation.

**Comment by 810** [comment]
fixed and merged
