### ISSUE TITLE
Read only mode: It are missing the action buttons for admins and mods.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3592]

**Comment by 810** [comment]
Read only should not have any buttons, Because nothing must/can be changed.

**Comment by rich20** [comment]
Ok, but then this incomplete button must be removed.

![bildschirmfoto vom 2015-12-09 15 00 22](https://cloud.githubusercontent.com/assets/888847/11687317/470f5fd4-9e86-11e5-938a-0e5c03d375b0.png)

**Comment by 810** [comment]
fixed and merged
