### ISSUE TITLE
 Crypsis template will not remove the Powered by link 

### ISSUE THREAD

**Issue by k4lch** [Kunena/Kunena-Forum#3603]
I have tried to remove the powered by link in this template but not changing if i switch to the blue eagle template it gone.
Where is this picking up the credits as they that been changed in the view.php file?

**Comment by xillibit** [comment]
We won't giving the method to remove the powered by link, see  : http://www.kunena.org/forum/77-General-Talk-about-Kunena/39871-please-help-me-understand-the-gpl-for-kunena-and-removing-the-powered-by-kunena-link
