### ISSUE TITLE
Creating Topic SQL Insert

### ISSUE THREAD

**Issue by JonnyUK** [Kunena/Kunena-Forum#3614]
Hello,

When creating a topic in Kunena which tables/rows do I need to add information to in the database?

I'm trying to create a webform that creates a topic with the field values as the topic message and I need to know which rows in the database need updating when doing this.

Thank you,

**Comment by 810** [comment]
prefix_kunena_messages
prefix_kunena_messages_text
prefix_kunena_topics
prefix_kunena_user_topics

Please use the forum for questions

**Comment by JonnyUK** [comment]
Hello,

Thank you for your reply :)

I have just 1 more question

With regards to message ID's and topic ID's, Do I need a php script to generate this in the database or does this "Auto Increment" do it automatically?

Thank you,

**Comment by 810** [comment]
its Auto Increment
