### ISSUE TITLE
Poll : Users can vote without write access

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3618]
https://www.kunena.org/forum/k-4-0-general-questions/135806-permissions-for-polls

Example : 
You have a category with Primary User Group: = Public
User Groups Allowed To Post = Manager
User Groups Allowed To Reply = Manager

Registered user can't create new topic and also not reply. So far, so good. But he can take part in a vote.

**Comment by 810** [comment]
merged
