### ISSUE TITLE
When Direct Component Access and Protect Attachments is active, Images will not appear in the backend

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3635]
https://www.kunena.org/forum/k-4-0-general-questions/135913-attachment-images-missing-in-back-end-after-migration
This problem exists if you choose both settings:
Protect Attachments = Yes
Direct Component Access = No

**Comment by xillibit** [comment]
I think i have found the root of the issue, but i'am looking to do a fix for it

**Comment by rich20** [comment]
- [ ] Failed
