### ISSUE TITLE
CrypsisB3: language strings missing in back-end

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3653]
![cb3_language_backnd](https://cloud.githubusercontent.com/assets/8537297/12718134/b953c09a-c8ec-11e5-8057-1b5baf8a2cab.png)

**Comment by rich20** [comment]
These strings are in the wrong file /components/com_kunena/language/en-GB/en-GB.kunena_tmpl_crypsis.ini
The complete section "new Crypsis" starting with row 228 should be moved to /administrator/components/com_kunena/language/en-GB/en-GB.com_kunena.views.ini
