### ISSUE TITLE
Fatal Error with Blue Eagle

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3662]
Fatal Error: Call to undefined method KunenaBbcode::escape() in libraries/kunena/bbcode/bbcode.php on line 282

It is needed the changes in line 282 and line 1166 
from
`if (strpos($this->escape($this->url), '/index.php') !== 0)`
to
`if (strpos($url, '/index.php') !== 0`

This fix has been already successfully tested.

**Comment by 810** [comment]
whats the bbcode you used.

**Comment by 810** [comment]
Is already in the new build:

https://github.com/Kunena/Kunena-Forum/blob/develop/libraries/kunena/bbcode/bbcode.php#L281

**Comment by xillibit** [comment]
Why we have this issue whic appear now ? How to reproduce this issue ?

**Comment by 810** [comment]
I forgot to create a pr. 

@xillibit with this code, he is adding the follow on the link. Is new improvement

**Comment by 810** [comment]
see: https://github.com/Kunena/Kunena-Forum/pull/3655

**Comment by 810** [comment]
Merged, closing this issue
