### ISSUE TITLE
Dashboard - Changelog should not be opened with a modal window

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3668]
Example: 
The button Help opens a minimized browser window and you can navigate in it. 
The button Changelog opens a modal window, where the links to Github do not work.

Summarized should be corrected:
- [ ] Changelog opened with browser window
- [x] Faq: How to Setup - the link goes to the old address
- [x] Faq: Setup Categories - the link goes to the old address

**Comment by 810** [comment]
Changelog, we need to find a way to show it correct.
