### ISSUE TITLE
Blue Eagle and Protect Attachments = Yes: It loads the lightbox with fixed size width="640" height="360"

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3673]
https://www.kunena.org/forum/kunena-support-reporting-defects/134714-lightbox-image-size-is-bigger-the-lightbox?start=10#172866

**Comment by 810** [comment]
@rich20 is still also on crypsis?

Else im closing the issue

**Comment by rich20** [comment]
It's only a Blue Eagle issue.

**Comment by 810** [comment]
ok, then i will close it.
