### ISSUE TITLE
Moderator missing new topics, because unlocked on new.topics.actions

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3686]
#### Steps to reproduce the issue

Login as moderator. On new category, you need to see actions.
#### Expected result

see new topic button
#### Actual result

none
#### System information (as much as possible)

Joomla version: J3.4
Kunena version: K4.0.11-dev
Php version: All
Database version: All

**Comment by xillibit** [comment]
By "new category", you mean with no topics in it ?

**Comment by rich20** [comment]
Yes, a empty category which is locked.  After this fix https://github.com/Kunena/Kunena-Forum/issues/3679, it remains a category but it are missing the buttons.

**Comment by 810** [comment]
yes, because https://github.com/Kunena/Kunena-Forum/blob/develop/libraries/kunena/forum/category/category.php#L611

Also other buttons are hidden

**Comment by 810** [comment]
looks it fixed now on K5.0. Closing this issue
