### ISSUE TITLE
Crypsis shows the module by post number in a topic

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3687]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k-4-0-general-questions/135961-crypsis-module-positions-uploads-not-working-properly?start=10#173132
Example kunena_msg_1 : The module will displayed after the first message in a topic (page 1)
#### Expected result

The module should be displayed after the first message also on all pages
#### Actual result

The module will be displayed only once in a topic
#### System information (as much as possible)

Joomla version: 3.4.8 and 3.5.0 beta
Kunena version: 4.0.10 and 4.0.11 dev
Php version: 5.6.17-nmm1
Database version: 5.5.46-nmm1-log

**Comment by 810** [comment]
Is now a new module position: kunena_msg_row_*
