### ISSUE TITLE
BBCodes for maps should be hardcoded

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3690]
#### Steps to reproduce the issue

https://www.kunena.org/forum/kunena-support-reporting-defects/136268-wrong-map-bbcode-syntax-on-non-english-4-0-10
1. Use a different language as English
2. Editor - click on map symbol -> Map Settings -> Choose a translated type of map -> Add 
#### Expected result

`[map type=Terrain zoom=2][/map]`
#### Actual result

`[map type=Gelände zoom=2][/map]` (depending on the language translation)
#### System information (as much as possible)

Joomla version: All
Kunena version: K 4.0.10
Php version:
Database version:
#### Additional comments

**BBCode works only with english language but it shows the text from the ini file.**
Line 39 in "components/com_kunena/template/crypsis/layouts/topic/edit/editor/default.php". These 4 options should be hardcoded.
`JText::_('COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_HYBRID') ?></option><option type="ROADMAP"><?php echo JText::_('COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_ROADMAP') ?></option><option type="TERRAIN"><?php echo JText::_('COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_TERRAIN') ?></option><option type="SATELLITE"><?php echo JText::_('COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_SATELLITE') ?></option></select><br />`

**These strings are then unnecessary:**
`COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_HYBRID="Hybrid"
COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_ROADMAP="Roadmap"
COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_TERRAIN="Terrain"
COM_KUNENA_EDITOR_MODAL_MAP_SETTINGS_SATELLITE="Satellite"`
(components/com_kunena/language/en-GB/en-GB.kunena_tmpl_crypsis.ini lines 113 - 116)

**Comment by 810** [comment]
merged
