### ISSUE TITLE
Fatal error: Class 'KunenaFactory' not found

### ISSUE THREAD

**Issue by alexonbalangue** [Kunena/Kunena-Forum#3693]
#### Steps to reproduce the issue

after install show this error
#### Expected result

Fatal error: Class 'KunenaFactory' not found in /var/www/website/administrator/components/com_kunena/install/model.php on line 1025
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Where exactly you have seen this error ?

Which Kunena version are-you using ?

**Comment by alexonbalangue** [comment]
1st install after to see the warning on panel admin "indicate: kunena not still complet" so now its ok.

it's the latest 4.0.10 of kunena,

**Comment by 810** [comment]
looks the file isn't overwrited, can reproduce this issue.
