### ISSUE TITLE
Poll Setting : The calendar stays on 11 January and life span date is -1-11-30 

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3694]
#### Steps to reproduce the issue

Click on poll symbol and check the calendar setting
#### Expected result

In the calendar - current date
life span date - should it be 0000-00-00?
#### Actual result

**Kunena 4.0**
The calendar stays on 11 January
life span date is -1-11-30
**Kunena 5.0**
you can't open the calendar - the button has no reaction
life span date field is empty
**Joomla 2.5.28 and Kunena 4.0**
Only this combination works correctly.
#### System information (as much as possible)

Joomla version: 3.4.8, 3.5.0 beta 2
Kunena version: 4.0.10, 4.0.11 dev, 
Php version: 5.6.17-nmm1
Database version: 5.5.46-nmm1-log

**Comment by xillibit** [comment]
On kunena 4.0 i can't open the calendar like on k5.0, i think for the calendar on crypsis i need to replace it by something using bootstrap to make it working

**Comment by xillibit** [comment]
> Kunena 4.0
> The calendar stays on 11 January
> life span date is -1-11-30

Which crypsis or blue eagle ?

**Comment by rich20** [comment]
With both templates
