### ISSUE TITLE
Categories ordering doesn't work correctly over several pages (pagination)

### ISSUE THREAD

**Issue by panopt** [Kunena/Kunena-Forum#3704]
#### Steps to reproduce the issue
1. The bug occurs in the category management view (back office). 
2. Need to have several categories in order that the pagination appears.
   For a single parent category, **children must be spread over several pages (pagination)**.
3. On **any page where the parent category is not showed**, reorder the children categories with the left handle.
4. Go to the page where the parent category is showed.
#### Expected result

The child categories are ordered relatively to their position in the parent category.
#### Actual result

The child categories are ordered relatively to their position in the page.
If I place a child category in the first position on the page, it will take the first position on the parent category.
#### System information (as much as possible)

Joomla version: 3.4.8
Kunena version: 4.0.10
Php version: 5.5.12
Database version: 5.6.17
(WAMP)
#### Additional comments

**Because of this bug there is no way to organize many categories.**

Add a **depth level filter** for categories (like with joomla categories) would allows to have no pagination when one wishes to organize categories.

**Comment by 810** [comment]
We have a depth filter.

Select the go icon, then it showed only the category and the sub. Else you need to increase the filter total categories.
