### ISSUE TITLE
To much empty spaces when profile position is top or bottom

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3730]
#### Steps to reproduce the issue

Backend: Select in the Crypsis template setting - Profile Position = Top (or Bottom)
Frontend: Write a post and to add a image or video
#### Expected result

The distance should be the same, as with Profile Positions left (right)
![bildschirmfoto vom 2016-03-10 02 49 14](https://cloud.githubusercontent.com/assets/888847/13674520/0a63da4c-e6de-11e5-9887-10dab725461b.png)
#### Actual result

To much spacing
![path5127](https://cloud.githubusercontent.com/assets/888847/13674838/57d8241c-e6df-11e5-9b7b-b9dea9f688a7.png)
#### System information (as much as possible)

Joomla version: 3.4.8 and 3.5
Kunena version: 4.0.11 and 5.0
Php version: 5.6
Database version:   5.5.46-nmm1-log

**Comment by 810** [comment]
merged
