### ISSUE TITLE
It lacks the topic title in the first post when profile position is top or bottom

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3737]
#### Steps to reproduce the issue

Change the profile position to top or bottom and look the first message in a topic
#### Expected result

rich created the topic: Topic title
#### Actual result

rich created the topic:
#### System information (as much as possible)

Joomla version: 3.5.0-rc4
Kunena version: Kunena 5.0.0-ALPHA4
Php version: 5.6
Database version: 5.5.46-nmm1-log

**Comment by 810** [comment]
merged
