### ISSUE TITLE
KunenaSpamRecaptcha not found

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3746]
#### Steps to reproduce the issue

home with article and discuss
#### Expected result

article with discuss
#### Actual result

Fatal error: Class 'KunenaSpamRecaptcha' not found in public_html/components/com_kunena/views/topic/view.html.php on line 143 
#### System information (as much as possible)

Joomla version: J3.5.0
Kunena version: K5.0.0
Php version:
Database version:

**Comment by Ruud68** [comment]
same for Kunena 4.0.10 and Discuss 3.1.2 (on Joomla 3.5)

**Comment by 810** [comment]
ik can't see any error with k4 and discuss 3.1.2

**Comment by Ruud68** [comment]
sorry, no error but captcha is not displaying at all, it is displaying fine on the forum itself just not in discuss.
should I create separate issue on forum or is this related?

**Comment by 810** [comment]
because the display init has changed, we need only add it on the plugins.

**Comment by Ruud68** [comment]
https://github.com/Kunena/Kunena-Addons/pull/191 for KunenaDiscuss :)

**Comment by 810** [comment]
closing this issue, is an addon issue
