### ISSUE TITLE
ebay api has changed

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3751]
#### Steps to reproduce the issue

add ebay item
#### Expected result

see the ebay item
#### Actual result

The ebay item id given is invalid, no result has been sent
#### System information (as much as possible)

Joomla version:  J3.4/J3.5
Kunena version: 4.0.10
Php version: All
Database version: All

**Comment by 810** [comment]
ok the eBay AppID key was empty, we need to check why its empty.

**Comment by xillibit** [comment]
It check both if the eBay App ID is set and if the ID of object item is empty, so you have in both cases the same error message : 

`The ebay item id given is invalid, no result has been sent`
