### ISSUE TITLE
Star rating : Only one user can to rate a topic

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3755]
#### Steps to reproduce the issue
1. Login as user 1 and to rate a topic
2. Login as user 2 and to rate the same topic
#### Expected result

Success 
The star has been successfully saved
#### Actual result

Warning!
undefined
#### System information (as much as possible)

Joomla version: 3.5.0
Kunena version: 5.0.0 ALPHA 5
Php version: 5,6 and 7.0
Database version: 5.5.46-nmm1-log

**Comment by xillibit** [comment]
Try to delete the table kunena_rate and install after the last build

**Comment by rich20** [comment]
Yes, after delete this table and install the new build the error is gone. So I close this issue.
