### ISSUE TITLE
Missing language string in toolbar

### ISSUE THREAD

**Issue by severdia** [Kunena/Kunena-Forum#3760]
#### Steps to reproduce the issue

![screen shot 2016-03-29 at 10 14 03 pm](https://cloud.githubusercontent.com/assets/355924/14132700/8d63bab0-f5fd-11e5-8146-2f673241129f.png)
#### Expected result

The string should be normal text.
#### Actual result

Key is displayed.
#### System information (as much as possible)

Joomla version: 3.5
Kunena version: 4.0.10
Php version: 5.6
Database version:

**Comment by sozzled** [comment]
As a matter of interest, does the same thing occur with the **Crypsis** template?

**Comment by severdia** [comment]
I haven't tried it, but it should be broken there as well since that key probably resides in en-GB.com_kunena.templates.ini

**Comment by 810** [comment]
should be working, i see no issue on my localhost, or k.org.

the strings are in this file:
en-GB.com_kunena.libraries.ini

**Comment by severdia** [comment]
That's strange. You have some editor help text in one file and some in another. if you look in the repo, the key/string is NOT in the file:

https://github.com/Kunena/Kunena-Forum/blob/develop/components/com_kunena/admin/language/en-GB/en-GB.com_kunena.libraries.ini

I checked the rest of the repo and it looks like you only made the change to one template instead of making it a global string. It looks like you have duplicate keys/strings in 

en-GB.com_kunena.views.ini
en-GB.kunena_tmpl_crypsis.ini

Moving these strings to the correct files and removing the duplicate key pairs should fix the issue.

**Comment by 810** [comment]
fixed on K5.0
