### ISSUE TITLE
Fatal error in the Kunena menu manager

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3792]
#### Steps to reproduce the issue

Go in backend to Tools -> Menu Manager
#### Expected result

Menu Manger with restore option
#### With php 5.6

Fatal Error: Call to undefined method KunenaMenuFix::getConflicts() in components/com_kunena/views/tools/view.html.php on line 91
##### An error has occurred.

0 Call to undefined method KunenaMenuFix::getConflicts() 

Call stack  
##### Function Location

1 JApplicationCms->execute() /administrator/index.php:51  
2 JApplicationAdministrator->doExecute() /libraries/cms/application/cms.php:257 
3 JApplicationAdministrator->dispatch() /libraries/cms/application/administrator.php:152  
4 JComponentHelper::renderComponent() /libraries/cms/application/administrator.php:98  
5 JComponentHelper::executeComponent() /libraries/cms/component/helper.php:380  
6 require_once() /libraries/cms/component/helper.php:405  
7 KunenaController->execute() /administrator/components/com_kunena/kunena.php:72  
8 KunenaController->executeTask() /libraries/kunena/controller.php:219  
9 KunenaController->display() /libraries/kunena/controller.php:161  
10 KunenaView->displayAll() /libraries/kunena/controller.php:403  
11 KunenaView->displayLayout() /libraries/kunena/view.php:120  
12 KunenaAdminViewTools->displayMenu() /libraries/kunena/view.php:205
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.5.2 dev
Kunena version: 4.0.10 and 5.0.0 Alpha 6
Php version: 5.6 and 7.0
Database version:
#### Additional comments

This error is not present in Kunena 4.0

**Comment by 810** [comment]
merged
