### ISSUE TITLE
Subcategories get the same name as the main category

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3795]
#### Steps to reproduce the issue

Create a subcategory and go to the Index 
#### Expected result

Subcategories with own names
#### Actual result

Subcategories get the same name as the main category
![rect2989](https://cloud.githubusercontent.com/assets/888847/14514394/94def30a-01f0-11e6-90a2-74542fe4f8e5.png)
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.5.2 dev
Kunena version: 5.0.0-ALPHA6
Php version: 5.6 and 7.0
Database version:

**Comment by 810** [comment]
merged
