### ISSUE TITLE
Deleting categories is not possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3796]
#### Steps to reproduce the issue
1. Go to category manager
2. Mark a category and click Delete 
#### Expected result

Category is removed
#### Actual result

There is only a page refresh without result
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.5.2 dev
Kunena version: 5.0.0-ALPHA6
Php version: 5.6 and 7.0
Database version:

**Comment by 810** [comment]
merged
