### ISSUE TITLE
Support Emoji symbols

### ISSUE THREAD

**Issue by 4digitalworld** [Kunena/Kunena-Forum#3805]
#### Steps to reproduce the issue

If i'm put "Emoji symbol" on forum, i'm see just "?" symbol instead "Emoji symbol"
#### Expected result

😊😎😒 - this symbols support native support on Joomla 3.x on com_content and also you can see graphics smiles via Mozilla Firefox. this symbols also support native in Windows 8 and 10, and native on last Android and iOS.
#### Actual result

?
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 4.0.10
Php version: 3.4
Database version: 5.5
#### Additional comments

Emoji symbols for test - https://vk.com/emoji_vk?w=page-42154384_44490007

**Comment by 810** [comment]
Hi you need to use admin tools then change the collation to UTF-8 Multibyte

Now the kunena tables aren't switches to new collation, so it doesn't work yet.

![emoji](https://cloud.githubusercontent.com/assets/876623/14587941/e05ab6ba-04bc-11e6-82d8-fa0509544f18.png)

**Comment by 4digitalworld** [comment]
![fd](https://cloud.githubusercontent.com/assets/3662519/14588227/8c481e4a-04cc-11e6-9792-676fd9641fd5.png)

i'm no have problem with Joomla com_content. i have this problem only with Kunena forum.

**Comment by 810** [comment]
Yeah, because the upgrade does only effect the joomla tables, so you need to use the admin tools, or you can change the kunena tables to utf8mb4

**Comment by 4digitalworld** [comment]
@810 maybe Kunena with next update, also update tables to utf8mb4?

why not? Joomla update tables to utf8mb4and Kunena can do it also.
