### ISSUE TITLE
Feed link doesn't update from configuration

### ISSUE THREAD

**Issue by severdia** [Kunena/Kunena-Forum#3845]
#### Steps to reproduce the issue

The HREF value for RSS is not updated by the field in the Kunena configuration settings. At the bottom of the RSS tab in the settings, there is a field to replace the URL (for Feedburner or other feed service). That URL is not updated in the head of the page. It should also be updated for the RSS icon at the bottom of each page.
#### Expected result

If I enter a custom feed URL in the settings. it should be displayed in the RSS link. My example URL is:

http://feed.press/myfeed.xml

So the link in the head should be:

`<link rel="alternate" type="application/rss+xml" title="get the latest posts directly to your desktop" href="http://feed.press/myfeed.xml" />`

The link on the RSS icon should also be this same URL. 
#### Actual result

The link doesn't change no matter what you enter.

`<link rel="alternate" type="application/rss+xml" title="get the latest posts directly to your desktop" href="/forum/recent?format=feed" />`

The link at the bottom of each page is:

`/forum/recent?format=feed`
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 4.0.10
Php version: 5.6.19
Database version: 5.5.31

**Comment by xillibit** [comment]
This setting seems to be used anywhere
