### ISSUE TITLE
3rt party plugin: error on new topic

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3860]
#### Steps to reproduce the issue

new topic
#### Expected result

Show preview
#### Actual result

newtopic:71 Uncaught TypeError: window.addEvent is not a function
markitup.set.js:166 Uncaught ReferenceError: kunena_showvideotag is not defined
#### System information (as much as possible)

Joomla version: 3.4
Kunena version: 5.0
Php version: 5.6
Database version:

**Comment by xillibit** [comment]
The plugin Ktex need to be updated to work with jQuery

**Comment by 810** [comment]
yes, closing this one
