### ISSUE TITLE
Identify OP In A Topic

### ISSUE THREAD

**Issue by GoremanX** [Kunena/Kunena-Forum#387]
This is an idea for a new feature beyond K2.0.

When viewing a topic, add a unique css class to posts made by the original poster, so that that user's posts can be styled differently (ie. add shading or different colour or whatever). This way, replies made by the original poster stand out more.

An administration option could be added to enable/disable the unique display of posts made the OP.

The template would need to support this.

This would be a unique feature that no existing forum has as far as I know (someone correct me if I'm wrong).

**Comment by 810** [comment]
This can be done on the template itself.

I'm using moderator and solved on the new crypsis. So I'm closing this one. If you want the features, then you can easy add it on the override or on your own template.
