### ISSUE TITLE
Improvement: move bbcode editor to widget/editor/bbcode

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3882]
#### Steps to reproduce the issue

Move the code to widget/editor/bbcode, so we can add later other editors
#### Expected result

Own widget item
#### Actual result

now its included in the topic/edit.
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by JoshWobbles** [comment]
Yes please! WysiBB is easy enough to splice in, but would rather not make all the core, template changes needed to make it work.
