### ISSUE TITLE
Error when combining Topic Icons = Default and  Show Labels = enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3904]
#### Steps to reproduce the issue

Select Topic Icons = Default
and
Show Labels = Topic ID (or Custom ID)
then go to Recent Topics
#### Actual result

Notice: Undefined variable: icons in components/com_kunena/template/crypsis/layouts/widget/label/default.php on line 29
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.6 dev
Kunena version: 5.0-Beta 4.0-dev
Php version: 5.6 and 7.0
Database version:

**Comment by 810** [comment]
already fixed
