### ISSUE TITLE
Category setting - Set topic icons for this category = System produces an error

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3923]
#### Steps to reproduce the issue
1. Selrct in the Configuration -> Frontend -> Selectable Topic Icons = Yes
2. Select in the Category Settings -> Topic Icons: = System
#### Expected result

No Error
#### Actual result

Fatal Error: Method KunenaLayout::__toString() must not throw an exception, caught Error: Call to a member function attributes() on null in components/com_kunena/template/crypsis/layouts/topic/list/default.php on line 0
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.6
Kunena version: 5.0.0-BETA4_DEV
Php version: 5.6 and 7.0
Database version:
#### Additional comments

Can you exclude these folders in the selection? In my opinion he should be hidden in this option.
![bildschirmfoto vom 2016-05-09 21 37 39](https://cloud.githubusercontent.com/assets/888847/15126720/9e47f840-1633-11e6-9fe4-09595cd6f31b.png)

**Comment by 810** [comment]
System dir has been removed
