### ISSUE TITLE
 Call to a member function get() on string when PHP7 is enabled

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#3934]
#### Steps to reproduce the issue

I moved site with Kunena 4.0.10 from localhost to hosting. Installed Kunena 5beta4 over 4.0.10. Then  overwrote files at the server with new ones taken from Github branch.
#### Expected result

Forum must work.
#### Actual result

As a result, when PHP 7.0.6 is enabled, forum does not working.

Forum home page shows: 

> Call to a member function get() on string
>  (no Joomla template loaded)

Discussion page shows: 

> 404 Not Found
> You do not have permissions to access this page.
> (Joomla template loaded with Kunena menu) 

If I turning PHP to old 5.4, forum works.
Kunena Latest module is disabled.
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5 beta 4
Php version: 7.0.6
Database version: 5.5.37-MariaDB-wsrep
#### Additional comments

Could this issue occurs due to server configuration?

**Comment by 810** [comment]
There is a change from PHP 7.0.5 to PHP 7.0.6
it has something todo with
public function __get($property)

but I haven't working yet

**Comment by 810** [comment]
see: https://bugs.php.net/bug.php?id=72117

**Comment by mahagr** [comment]
To me the error looks like that $category->params is a string, not Registry object. Not sure if it is related to the above change in PHP or not.

**Comment by Twincarb** [comment]
I am having a similar issue
php 7.0.6
The category page loads correctly but unable to click to open a category to view the topics.

Notice: Uninitialized string offset: 0 in /var/www/vhosts/mysite.org/test.mysite.org/libraries/kunena/html/html/kunenaforum.php on line 193

**Comment by sakicnet** [comment]
Please see [https://www.kunena.org/forum/kunena-support-reporting-defects/137045-php-7-0-6-and-kunena-4-0-10-and-5-0b4#175137](https://www.kunena.org/forum/kunena-support-reporting-defects/137045-php-7-0-6-and-kunena-4-0-10-and-5-0b4#175137)

**Comment by mahagr** [comment]
The change will make the number of SQL calls to explode, so I don't recommend doing it in that way.

**Comment by xillibit** [comment]
There is something strange on PHP 7.0.6, in the constructor of the category there is `$registry = new JRegistry();
        if (!empty($this->params))
        {
            $registry->loadString($this->params);
        }
        $this->params = $registry;`

I don't know why what is the issue with PHP 7.0.6

**Comment by mahagr** [comment]
Maybe PHP7 isn't calling a constructor? That would be PHP bug though..

**Comment by sakicnet** [comment]
It is calling the constructor, but in PHP 7.0.6 $this in KunenaForumCategory is empty object, while in 7.0.5 and below $this is set to the DB object.

I will dig some more and propose another solution.

**Comment by mahagr** [comment]
So it looks like that something has changed in `$instances = (array) $db->loadObjectList('id', 'KunenaForumCategory');` call. 

I need to install PHP 7.0.6 in order to test this.

BTW, can you take a look how the resulting `$instances` look like? Do they have any data in them? If not, its clearly a bug either in PHP or Joomla.

**Comment by mahagr** [comment]
I think there's a bug in PHP itself:

```
    protected function fetchObject($cursor = null, $class = 'stdClass')
    {
        return mysqli_fetch_object($cursor ? $cursor : $this->cursor, $class);
    }
```

**Comment by mahagr** [comment]
Since 5.6.21 and PHP 7.0.6 mysqli_fetch_object() sets the properties of the object AFTER calling the object constructor. Not BEFORE as was in previous versions.

http://php.net/manual/en/mysqli-result.fetch-object.php

**Comment by sakicnet** [comment]
That's it.

**Comment by mahagr** [comment]
Yeah, they already reverted the change, but I think we cannot trust PHP team from not breaking this again as the functionality is a bit questionable, so I think we should still change it.

**Comment by mahagr** [comment]
I've fixed the issue in https://github.com/gantry/gantry5/commit/8fe33f4a4a25d69f44351bc8bcadf8c2e28ffc21

Note: All the object classes need to update their `initialize()` function to be public and make sure it can only be called once.

BTW: my code is based on Kunena; might not be bad idea to update Kunena to use the new version of the object/finder classes. In the future I still want to get rid of `JObject` stuff, but for now I've tried to keep the code as close as possible to allow you guys to update it easier.

**Comment by Twincarb** [comment]
Is this an issue with Joomla, Kunena or Templates?

**Comment by mahagr** [comment]
Its a bug in PHP 5.6.21 and PHP 7.0.6 which will be fixed for the next version. It affects at least Kunena and Gantry 5 as they were using a feature in PHP which broke.

**Comment by 810** [comment]
I Just tried PHP 7.0.7 and it looks like it fixed now. 

Only there are now errors on joomla backend, so again no go version

**Comment by Kubik-Rubik** [comment]
@810 Thank you for testing. Could you please report the errors in the official issue tracker of Joomla!? Thanks! https://issues.joomla.org/

**Comment by 810** [comment]
@Kubik-Rubik see https://github.com/joomla/joomla-cms/pull/10452

**Comment by Kubik-Rubik** [comment]
@810 Great, thank you!

**Comment by 810** [comment]
This issue has been fixed on PHP7.0.7 closing this issue
