### ISSUE TITLE
CrypsisBS3 and Poll feature: PHP Warning:  implode() in error.log

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#3935]
Just been examined error.log and found some entries. It's not an issue, but maybe it's minor thing, that can be fixed.

[Wed May 11 16:29:42 2016] [warn] [client 177.233.9.22] mod_fcgid: stderr: PHP Warning:  implode(): Invalid arguments passed in /var/web/components/com_kunena/template/crypsisb3/layouts/topic/poll/results/default.php on line 67, referer: http://mysite.com/index.php/welcome-mat
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5 beta4
Php version: 5.4.45
Database version: 5.5.37-MariaDB-wsrep

**Comment by xillibit** [comment]
I had checked this but when there are more that 5 users which have voted for the poll, i haven't see this error in m php log

**Comment by Sulpher** [comment]
I just been checked out error.log again and see lot of such entries referred to the poll.
There is a poll with more than 8 users voted and Helix 3 template framework (Bootstrap 3) in use.

**Comment by 810** [comment]
confirmed, you need 6 voters to have this issue

**Comment by 810** [comment]
also I can't change my vote.
