### ISSUE TITLE
Can't switch between avatar galleries in profile

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3936]
#### Steps to reproduce the issue

Create 2 or more new folders inside media/kunena/avatars/gallery with images contained
Login as user and go to your Profil > Edit > Avatar image
Try to choose another avatar gallery in the dropdown
#### Expected result

If you choose another gallery/folder, the images contained should be displayed so users can select them
#### Actual result

Does not do anything
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5.0.0-BETA4
Php version: 5.6.8
Database version: 5.6.24
##

**Comment by xillibit** [comment]
I had forgot to convert javascript from blue eagle to handle this part

**Comment by rich20** [comment]
- [ ] Failed - If you switch the folder, it shows only empty symbols

![bildschirmfoto vom 2016-05-13 19 42 25](https://cloud.githubusercontent.com/assets/888847/15256717/194b1632-1943-11e6-9815-92d40c56a1fe.png)
