### ISSUE TITLE
Wrong colors in CrypsisBS3 for [color] BBCode

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#3940]
#### Steps to reproduce the issue

Colorize text in different colors using BBCode.

[color=#000000]Color black[/color]
[color=#000044]Color orange[/color]
[color=#000088]Color red[/color]
[color=blue]Color blue[/color]
[color=purple]Color purple[/color]
[color=green]Color green[/color]
[color=white]Color white[/color]
[color=gray]Color grey[/color]
#### Expected result

Correct colors.
#### Actual result

There is a misprint for red color. There is #000088 value, but must be #880000
Orange color: there is #000044, it supposedly there should be #440000
See picture:
http://img.prntscr.com/img?url=http://i.imgur.com/QhiJlSt.png

Please define correct color values.
#### System information (as much as possible)

Kunena version: 5 beta 4
Crypsis BS3
#### Additional information

Github strips heximal code at the front-end, but I hope you understood the idea.

**Comment by 810** [comment]
I can't reproduce this issue:

All colors are names no hex

See:
https://github.com/Kunena/Kunena-Forum/blob/d9faeff18a182a2c003efad56f65310c53c49195/src/components/com_kunena/template/crypsisb3/assets/js/markitup.editor.js
