### ISSUE TITLE
embedded video resizing

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#3971]
#### Steps to reproduce the issue

Load bs3 template
Create new post with video url
Reduce view (smart phone)
#### Expected result

Video is getting resized so it does not break layout
#### Actual result

not resized
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5.0.0-BETA5
Php version: 5.6.8
Database version: 5.6.24 
#### Additional comments

works for Crypsis, not for B3 version
see #3511

**Comment by 810** [comment]
Then your B3 template doesn't have the "embed-responsive" "embed-responsive-16by9" css classes

**Comment by betteryouthanme** [comment]
I've added embed-responsive/ -16by9 to my custom.css, but i don't see embed-responsive class inside iframe?
![iframe-video](https://cloud.githubusercontent.com/assets/8537297/15647247/b509279a-2662-11e6-87cd-64ea217a705a.jpg)

**Comment by 810** [comment]
it should be there before iframe see:
![wc](https://cloud.githubusercontent.com/assets/876623/15647412/a4321494-2663-11e6-9520-7b08132d5dba.jpg)

**Comment by 810** [comment]
else you have a outdated libraries/kunena/bbcode/bbcode.php file

or you have inserted the vid by the bbcode. Its only working by the auto link from youtube.

**Comment by betteryouthanme** [comment]
yes by bbcode. auto link works

**Comment by 810** [comment]
I can't add it to bbcode, because else the width and height option doesn't work.

**Comment by betteryouthanme** [comment]
with the b2 version it works fine, if that helps anyhow
