### ISSUE TITLE
Confidential informations : With quote button all users can see it

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3990]
#### Steps to reproduce the issue

1.Write a confidential text and save
2. Login as other user and click on quote
#### Expected result

No confidential informations
#### Actual result

The confidential text is included
![bildschirmfoto vom 2016-06-04 17 47 53](https://cloud.githubusercontent.com/assets/888847/15800621/6ee380ba-2a7e-11e6-9e30-9b48489872e7.png)
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.6.0 Alpha-2
Kunena version: 4.0.10 , 4.0.11-DEV , 5.0.0-RC-DEV
Template: Blue Eagle and Crypsis
Php version: 5.6
Database version:

**Comment by sozzled** [comment]
Oh my God!  I just saw this.  This means that anyone who is able to use the QUOTE feature can now see any "confidential" information posted by others!  This is quite a security problem.

The most important target at this time is to fix this first for K 4.0.  I will also check to see if K 3.0.8 is vulnerable.

EDIT:  K 3.0.8 is not affected
