### ISSUE TITLE
Fatal error on upgrade to Kunena 5.0 when old topic icon directory is keeped

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#3997]
#### Steps to reproduce the issue

On upgrade from a previous version to Kunena 5.0, the directory /media/kunena/topic_icons is keeped so it cause a fatal error.
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:
#### Additional comments

See : https://www.kunena.org/forum/k5-0-bugs/137152-500-internal-server-error?start=20#175809

**Comment by 810** [comment]
so we need to move icons, then delete the dir.

**Comment by 810** [comment]
can't reproduce this issue

**Comment by rich20** [comment]
I can reproduce the error. But only if the system folder exists and if is selected "Set topic icons for this category = system".
/media/kunena/topic_icons/**system**

**Comment by 810** [comment]
fixed and merged
