### ISSUE TITLE
Error in Duplicated Alias for Categories 

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3999]
#### Steps to reproduce the issue

https://www.kunena.org/forum/kunena-support-reporting-defects/137298-k-4-0-11-error-in-duplicated-alias-for-categories
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
I can't reproduce this issue on K5.0 rc1

**Comment by rich20** [comment]
This error accrues only then if you empty the checkbox before save.
![path3304](https://cloud.githubusercontent.com/assets/888847/15942753/146e7700-2e86-11e6-8121-53a6bc072cf8.png)

**Comment by 810** [comment]
the error is correct. you can't have the same aliases.

**Comment by rich20** [comment]
> the error is correct. you can't have the same aliases.

Yes, I know and it will also not saved. But after click on save, the category in frontend is broken and it gives a 404 error.

**Comment by 810** [comment]
@rich20 is just fixed the alias delete, try now again, because for me the correct alias is loaded.

**Comment by rich20** [comment]
If you enter a duplicate alias and the checkbox is empty, then the check box disappears after save and that causes the error. For me is not a problem, I've only confirmed this mistake (report by chiripas).
![bildschirmfoto vom 2016-06-10 16 59 01](https://cloud.githubusercontent.com/assets/888847/15969085/a20a9604-2f2e-11e6-8a9a-db9aa0a20e46.png)
