### ISSUE TITLE
Most used forum button, the reply button, should not only not be buried in a menu, but should be green.

### ISSUE THREAD

**Issue by JoshWobbles** [Kunena/Kunena-Forum#4002]
Breakout (or at least give the option to be broken out) the Action menu for posts and forum page. Collapsing these items into a dropdown serves little purpose and makes one of the most commonly used buttons, the reply button, buried.

Not only should reply be its own button, but it should also be stylized green just as the new topic buttons are.

A couple of these dropdown menus should be re-thought for similiar reasons.

**Comment by JoshWobbles** [comment]
Of course I can easily modify the template myself to do this, I just think it should be done as default.

**Comment by 810** [comment]
i have added a option to show all actions as seperate buttons, but i wouldn't change the color.
