### ISSUE TITLE
CrypsisB3 Search Options - problem with collapsing

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#4006]
#### Steps to reproduce the issue

Load CrypsisB3
Go to Kuena search menu
Collapse (hide) Search Options
#### Expected result

Search Options collapsing and stay collapsed
#### Actual result

After a few seconds the Search Options expand again
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5.0.0-RC1
Php version: 5.6.8
Database version: 5.6.24
#### Additional comments

also bugged in previous releases of CrypsisB3 template

**Comment by 810** [comment]
merged
