### ISSUE TITLE
"Subscribe" always ticked by default

### ISSUE THREAD

**Issue by brianmcardle** [Kunena/Kunena-Forum#4007]
#### Steps to reproduce the issue

Set 'Check Subscription Box' to 'No' within Configuration->Users->Subscriptions

![config](https://cloud.githubusercontent.com/assets/7878905/15924778/cf78e5d6-2e2b-11e6-83d3-9cb50ffa43a3.png)
#### Expected result

When a user replies to a topic, the 'Subscribe (Check this box to be notified of replies to this topic.)' is not ticked by default.
#### Actual result

When a user replies to a topic, the 'Subscribe (Check this box to be notified of replies to this topic.)' is ticked by default.

This is the same whether 'Check Subscription Box' is set to 'Yes' or 'No'.

![reply](https://cloud.githubusercontent.com/assets/7878905/15924779/cf8c54c2-2e2b-11e6-82f2-46816e164bfc.png)
#### System information (as much as possible)

Running on a hosted server, I can't seem to work out what version of MySQL it is.

Joomla version: 3.5.0
Kunena version: 4.0.11
Php version: 5.5
Database version: ?

**Comment by 810** [comment]
https://www.kunena.org/forum/k-4-0-support-archive/134474-k-4-0-3-crypsis-automatically-subscribes-to-topic-blue-eagle-does-not
