### ISSUE TITLE
Feature: All Unread Topics view

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#4016]
Similar to Recent Topics or My Topics, an "All Unread Topics" view would enable users to make sure they are current on all discussions, and not missing anything from an older visit.  It would also be helpful if they are added to a restricted board, and have a lot to catch up on - this way, they know that they are not missing any old topics they did not have access to before.

Thank you!

**Comment by 810** [comment]
duplicated issue: https://github.com/Kunena/Kunena-Forum/issues/840
