### ISSUE TITLE
With "Adds Suffix to URL = Yes" no attachments and images are available in the forum

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4017]
#### Steps to reproduce the issue

https://www.kunena.org/forum/general-user-contributions/137356-attachment-downloads-generating-404-file-not-found-error
Select in the Joomla global configuration "Adds Suffix to URL = Yes"
#### Expected result

Images and attachments should be available in the forum
#### Actual result

Images are hidden and attachments will not be found (filename.html 404 File Not Found)
#### System information (as much as possible)

Joomla version: 3.5.1 and 3.6 alpha dev
Kunena version: 4.0.11 and 5.0.0 RC2-dev
Php version: 5.6 and 7.0
Database version:

**Comment by leadingcode** [comment]
bad idea fix it only in version 5.x, because you have made the change from version 4 to 5 very time consuming and hard :(

**Comment by 810** [comment]
From tomorrow the K4.0 branch will be depricated.

The last k4.0 version will be released tomorrow.
