### ISSUE TITLE
html is lost on submit

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4022]
#### Steps to reproduce the issue

if you enter html on a message, it will be removed on the message:

example: 
[code]
<button type="button">test</button>
[/code]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
I don't understood the issue, in the bbcode [code][/code] you have entered HTML ?

**Comment by 810** [comment]
@xillibit GitHub has the same issue.

you need to enter `[code]
<button type="button">test</button>
[/code]`

**Comment by 810** [comment]
Leave a comment
