### ISSUE TITLE
CrypsisB3: display issues of poll settings

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#4035]
#### Actual result

![poll-settings-b3](https://cloud.githubusercontent.com/assets/8537297/16108643/afac24f6-33a4-11e6-95dc-7b36d6123e1f.jpg)
#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5.0.0-RC2 
Php version:
Database version:

**Comment by xillibit** [comment]
We know this issue, if i set the correct display of options fields then when we try to fill it the options fields disappear
