### ISSUE TITLE
[feature request] Add events in Kunena

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#4050]
A feature request to implement events that let 3rd party developers to extend Kunena with custom plugins. Here is link on thread post with details and screenshots: 
https://www.kunena.org/forum/kunena-feature-requests/134573-new-events-for-developers?limitstart=0#169557

I am ready to help with events beta testing.

**Comment by GJSchaller** [comment]
Could this be done with JEvents?  It's free at the basic level, so this would make it ideal as a 3rd Party partner.

**Comment by Sulpher** [comment]
I am talking about plugin events for developers. Direct analogue:
https://docs.joomla.org/Plugin/Events

It seems JEvents provides events content, this is another way...

**Comment by GJSchaller** [comment]
Yes, I realized that about 30 seconds after I made the comment.  Sorry! :-)

**Comment by 810** [comment]
@Sulpher i have added 2 new events for you:

- onKunenaUserTabs
- onKunenaUserTabsEdit

And 1 more module position on the profile page.
 - kunena_summary

**Comment by 810** [comment]
example:

````
public function onKunenaUserTabsEdit()
	{
		$tab               = new stdClass;
		$tab->title        = JText::_('44');
		$tab->content      = '<div class="tab-content"><div class="tab-pane fade active in"><h2>Wheeeeeeee</h2></div></div>';
		$tab->active       = false;
		$tabs['test']      = $tab;

		return $tabs['test'];
	}
````

**Comment by Sulpher** [comment]
Hi @810, this is really nice addition to Kunena! :-) We shall try to use events soon. Thank you!

**Comment by Sulpher** [comment]
Hi @810,
I have sent you an e-mail a few days ago concerning events. Have you received it?

**Comment by Ibrahim1** [comment]
Hello @Sulpher I didn't receive any post about events! not me maybe the other get it.

**Comment by Sulpher** [comment]
Hi @Ibrahim1 , the message was sent to @810 according to the conversation in this issue. I did not send you any message, but it seems you have mistaken :-)
