### ISSUE TITLE
Invalid URI in request GET /../images/stars.svg

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#4074]
#### Steps to reproduce the issue

See : https://www.kunena.org/forum/k5-0-bugs/137581-k-5-0-rc3-apache-2-4-error-invalid-uri-in-request-get#176693
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
I have no issue:

```
Name    Protocol    Method  Result  Content type    Received    Time    Initiator
http://localhost/develop/components/com_kunena/template/crypsis/assets/images/stars.svg HTTP    GET 200 image/svg+xml   (from cache)    0 s 
```

**Comment by 810** [comment]
Local server issue, closing this one
