### ISSUE TITLE
K5.0 RC3 - Crypsis - Old DIV not in use still present

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#4076]
In Kunena 5.0 RC3 Crypsis, on the Topic View, the Report Post button and IP Address of the post were moved to new locations to better utilize space.

The old DIV that contained them is still present on each message, but empty - it only shows when someone with the proper permissions is viewing the board.  This comes after (DIV class="ksig") for each message:  (div class="row") and all content inside that DIV

**Comment by 810** [comment]
I can't reproduce this issue, for me i can't see that html in the message.

login as admin

**Comment by GJSchaller** [comment]
![screen shot 2016-07-04 at 12 11 33 pm](https://cloud.githubusercontent.com/assets/2761607/16566167/82eba9f6-41e0-11e6-81e5-014c631d8d78.png)

Screenshot from K5RC3, logged in as SuperUser.  I can give you access to this (test) site if you would like.
