### ISSUE TITLE
Crypsisb3: Quick reply only first message is working

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4083]
#### Steps to reproduce the issue

I have update the quick reply, but only for crypsisb3 it doesn't work correct. Only the first message is working.

This is the code that must be fixed:
https://github.com/Kunena/Kunena-Forum/blob/K5.0/src/components/com_kunena/template/crypsisb3/assets/js/edit.js#L111 
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
I will check it later to see why on crypsis b3 it doesn't work
