### ISSUE TITLE
maps key needed

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4086]
#### Steps to reproduce the issue

add map
#### Expected result

see map
#### Actual result

Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
I will add a new setting in Kunena config to enter API key from Google
