### ISSUE TITLE
Old Kunena Media Files not removed during version upgrade

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#4087]
#### Steps to reproduce the issue

See : https://www.kunena.org/forum/k5-0-bugs/137597-k-5-0-rc3-old-kunena-media-files-not-removed-during-version-upgrade
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
I tested this, but for me it updated correct, maybe this is just a local issue. Closing this one
