### ISSUE TITLE
Subscription notifications that contain iframe are considered like spam

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#4140]
#### Steps to reproduce the issue

See : https://www.kunena.org/forum/kunena-feature-requests/137664-subscription-notifications-that-contain-whole-message-spam#177148
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
this is just created by the bbcode. so if we block this , then youtube ect, will also not be working.

This is not a correct spam protection.

**Comment by xillibit** [comment]
I just want to remove iframe elements in subscription mails

**Comment by 810** [comment]
ok, we should also hide file attachments on the mail

**Comment by xillibit** [comment]
I think we can hide too attachments on the mail
