### ISSUE TITLE
Desirable to Clone Crypsis template to look like Blue Eagle template, or update Blue Eagle

### ISSUE THREAD

**Issue by pintobuck** [Kunena/Kunena-Forum#4169]
So far, the Blue Eagle template is the most popular Kunena template of all time, and in many eyes it is the most attractive template.  However, Blue Eagle was discontinued in Kunena 5.0.

From reading around, I understand that Crypsis was developed on a template framework which is almost exclusively used by Kunena.  (I think I read that Joomla.org was approached, but decided not to adopt  Kunena's new template framework.)

Gantry 5 is a very popular, state of the art template framework, which is also a Github project.
For example: https://www.kunena.org/forum/index seems to use a Rockettheme Gantry template for Joomla and the Blue Eagle template for it's Kunena forum.

Perhaps Kunena's Blue Eagle template should be rebuilt for Kunena 5.0 on a widely used template framework like Gantry 5.  Or the Crypsis template could be forked to look like Blue Eagle.

**Comment by 810** [comment]
Crypsis template is fully working on Gantry 5.

**Comment by pintobuck** [comment]
> Crypsis template is fully working on Gantry 5.<

Very true. I'm using Kunena's Crypsis template on Joomla 3.6 with Gantry 5 Hydrogen (customized) template.  But, that is not the issue that I hoped to address.

I proposed that the look and function of the Kunena's most popular and attractive template (the Blue Eagle template) should be recreated using a fork of Crypsis template, or build from scratch on the Gantry 5 template framework, or by any method they choose.  Hopefully, someone will consider this to be a desirable project / enhancement.  Thank you kunena (Jelle Kok) for any consideration of this proposal.

**Comment by 810** [comment]
After K5.0 is released, there will be come more template, available by (paid templates) us and our 3rth party template partners.  They are waiting for the final release.
