### ISSUE TITLE
Suggested improvements to Kunena 5 RC5 and Crypsis template

### ISSUE THREAD

**Issue by pintobuck** [Kunena/Kunena-Forum#4187]
I'm using Joomla 3.6, Kunena 5 RC5, and Crypsis template.

I posted some [suggested improvements in Kunena.org](https://www.kunena.org/forum/k5-0-bugs/137890-k5-rc5-possible-crypsis-menu-bug#177615). 

I'm posting the suggested improvements here as a more direct pipeline to the Kunena developers.

1) Have a post-installation message explain what should be done next to make Kunena work with the Joomla menu system.

2) Kunena should not use the menu alias "Forum," because that is the natural menu item title and alias that people will use when they create a Joomla menu item to link to Kunena. As it is, people cannot save their "Forum" menu item because they get an error message from Joomla about a duplicate alias. Perhaps Kunena could use a different alias like forum-k.

3) Make the Kunena menu show up on all forum pages including "forum" and "category list." When the Kenuna menu does not show up, people could think they have to create an entire Kunena menu themselves (which was my impression before I received your advice).

4) In Joomla backend / Menus / Menu Items / New / Menu Item Type / Kunena Forum /, offer the option to link to Kunena's index page, which is not available now.

5) When people do follow the recommended Kunena menu procedure, the menu item opens to Kunena's "Recent Topics" page. Many people would rather have Kunena open to Kunena's Index page.

6) Put the word "Login" next to the login icon in the Crypsis template.

7) In the login drop down box, include the option to create an account.

8) On the index page, I collapsed the category titles so that only section titles showed.
Joomla backend / components / Kunena forum / categories / open a Section category / category settings / display sub-categories / Never in category index
But then the index page was misleading on the front end. Under each Section Title was the following statement:
See Complete List of Subjects (1 hidden)
That confuses and discourages the reader into thinking there is only one topic posted in the section category. Actually, dozens of topics are posted under that Section Category. It would be better to say:
See Complete List of Subjects (113 topics)
or just say
See Complete List of Subjects

Thank you for considering these suggestions.

**Comment by 810** [comment]
1) Kunena menu alias is the same as in K1.0, we never changed this behavior. installation doc is here: https://www.kunena.org/docs/en/installation
2) If you want to use the foruma alias, then you need to remove it, also on trash.
3) All kunena menu items are showed on the kunena menu, on all kunena pages. If you can't see it, then you have a wrong setting on your new menu item
4) You need to use the alias.
5) You can choose you option, on the menu item, 90% will use recent topics
6) Sorry this is a personal improvement, we don't add custom strings, if you want, you can create a template override.
7) The option is there, if you have enabled the create account on joomla user options
8) category index is not the index menu item itself, its the view between index and the category item. Category item is only see the category without the topics on the bottom.

**Comment by pintobuck** [comment]
Thank you for the detailed reply and information.
