### ISSUE TITLE
whois.domaintools.com is limited and ask captcha in some cases

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#4193]
#### Steps to reproduce the issue

If you do a lot of queries to whois.domaintools.com, when you reach the limit, it will show you the message that you need to pay.

In somes cases it ask captcha and it's annoying for users.

See : https://www.kunena.org/forum/k-4-0-general-questions/135216-whois-domaintools-com-asking-for-captcha?start=10#177660
#### Changes to made

Use an API like : https://packagist.org/packages/geoip2/geoip2 to do query directly and show near to the ip the country.
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
Just in case, here are some alternate APIs:
http://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_APIs

**Comment by sshcli** [comment]
Just in case, here is a good source for country flags: 
https://github.com/lipis/flag-icon-css

**Comment by 810** [comment]
we changed the service
