### ISSUE TITLE
Last edit: no check if moderator is moderator on this category

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4210]
#### Steps to reproduce the issue

On the topic a normal moderator, has a user color on the name on a other category, but when he edit his message, then the last edit message, the user got the global moderator color on the last edit message. on the left (profilebox) the color is ok.
#### System information (as much as possible)

Joomla version:
Kunena version: 
Php version: 
Database version:

**Comment by xillibit** [comment]
Can-you make a screenshot because i don't see exactly where it's located ?

**Comment by 810** [comment]
see: https://www.kunena.org/forum/k5-0-support/138001-k-5-0-rc5-feature-add-lock-option-in-recent-topics-view

**Comment by xillibit** [comment]
> see: https://www.kunena.org/forum/k5-0-support/138001-k-5-0-rc5-feature-add-lock-option-in-recent-topics-view

That's is different, it's for add en new option to lock multiples in same time
