### ISSUE TITLE
Recent Topics page shows correct admin and moderator colors according to the random principle

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4212]
### Steps to reproduce the issue

@810 You can see this error also on your own test page. Go to recent topics. You see "Last Post by admin" has color of registered user, Now go page two. "Last Post by admin". Here is the correctly admin color.
Maybe there is a relation with this bug? https://github.com/Kunena/Kunena-Forum/issues/4210

![path2987](https://cloud.githubusercontent.com/assets/888847/17301047/60209de6-5815-11e6-98b7-78230dcfd08e.png)
#### System information (as much as possible)

Joomla version:  3.6.0 , 3.6.1-rc2 and 3.7-DEV
Kunena version: 5.0.0-RC6-DEV 
Php version: 7.0.8
Database version:

**Comment by 810** [comment]
also on the first page for me.

**Comment by rich20** [comment]
Is not the cache. I've tested with 3 different browsers.
![bildschirmfoto vom 2016-08-01 18 35 45](https://cloud.githubusercontent.com/assets/888847/17301424/4572122a-5817-11e6-8932-4fccd56baf36.png)

On page 2 it's correct.

**Comment by xillibit** [comment]
It seems that the last author color is taken from topic author, i don't find where is the issue

**Comment by rich20** [comment]
I seems a little more complicated. It has only affect in the corresponding category.
![g5685](https://cloud.githubusercontent.com/assets/888847/17330550/7e2cfbf6-58c7-11e6-970a-82ad81df979d.png)

Here is the last post from the topic autor:
![path5906](https://cloud.githubusercontent.com/assets/888847/17330881/e05406de-58c8-11e6-97fe-668cf28e96a7.png)
