### ISSUE TITLE
Empty messages will not automatic removed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4214]
#### Steps to reproduce the issue

https://www.kunena.org/forum/164-Fairground/123795-quoted-images#128463
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Except with a tool whic check all messages and delete the empty one, i don't see how to remove this kind of messages

**Comment by 810** [comment]
I have added a check that you don't get any empty messages
