### ISSUE TITLE
The option "Message title length" has always 50 characters

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4218]
#### Steps to reproduce the issue

Crypsis -> Basic settings -> Message title length
No matter if you chose more or less it are always 50 characters although default should be 80 characters
#### System information (as much as possible)

Joomla version: 3.6.1-rc2 and 3.7.0-dev
Kunena version: 5.0.0-RC6-DEV
Php version: 7.0.8
Database version:

**Comment by 810** [comment]
Leave a comment
