### ISSUE TITLE
Spoiler tag overrules also all included spoilers.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4241]
#### Steps to reproduce the issue
1. Paste a configuration report within spoiler tags.
2. To open the spoiler
3. Close a spoiler such as Kunena menus details in the configuration report
#### Expected result

Only Kunena menu details should be closed
#### Actual result

The complete spoiler will closed
#### System information (as much as possible)

Joomla version: 3.6.2 and 3.7.0-dev
Kunena version: 4.0.11 and 5.0.RC6-dev
Php version: 5.6 and 7.0.8
Database version:

**Comment by 810** [comment]
because the top spoiler is active, so all close will collapse the spoiler, you shouldn't user the spoiler.
i think we can't change this.
