### ISSUE TITLE
After Remove Kunena the update pages remain in backend

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4244]
#### Steps to reproduce the issue

Foum Tools -> Uninstall Kunena
This option should be remove everithing but the update sites remain in "Extensions -> Manage -> Update sites
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
In j!3.6 there is a new feature to delete obsolete updates sites, so i'am not sure that is needed in Kunena

**Comment by xillibit** [comment]
I have digged on this issue, the update sites are remaining after uninstall because the uninstall is done when removing Kunena component, by doing that it uninstall everything except update sites. The uninstall of the update sites too is done by uninstalling the kunena package.
