### ISSUE TITLE
Upgrade from K4 to K5 : Warning Destination folder already exists

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4248]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/138107-warning-destination-folder-already-exists
You can test it:
Downgrade to K4.0.11
then upgrade to K5. Now you see this error. 
![bildschirmfoto vom 2016-08-07 21-15-20](https://cloud.githubusercontent.com/assets/888847/17465140/e807543c-5cef-11e6-8965-7cdbf96358ea.png)

Rename or remove the folder topic_icons in media/kunena and the installation works.
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
how to get this error, because we need to have that dir
