### ISSUE TITLE
Language string problems

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#4253]
In Kunena 5.0, I found some language string problems.
1. In Members stat, the "Member" and the "Guest" words are inherited. This solution is not good, because in the Hungarian language has not capitalized nouns. It would be better if we use a dedicated string.
   ![image](https://cloud.githubusercontent.com/assets/1657924/17487438/190569c0-5d95-11e6-9d01-a3145056f58e.png)
2. In com_kunena.views.ini (site) file the COM_KUNENA_LOGIN_PLEASE string has the following value: Please %s %s to join the conversation. This value also has inherited words. When loaded the %s values, then the sentence is meaningless in Hungarian language.
   ![image](https://cloud.githubusercontent.com/assets/1657924/17488037/c1590a44-5d97-11e6-95bd-8efc09d5c064.png)
3. The share button texts are hardcoded.
   ![image](https://cloud.githubusercontent.com/assets/1657924/17488294/01e905f4-5d99-11e6-96e3-9b2c5d845dc8.png)

**Comment by 810** [comment]
1) could you show me how it should be seen on Hungarian language
2) %s are for the login and the second for create an account
3) Yes this is a know issue

**Comment by csbalazs** [comment]
I.
![image](https://cloud.githubusercontent.com/assets/1657924/17493730/eef2dee8-5db1-11e6-9f9a-1ff1c2f2b16b.png)

II. 
![image](https://cloud.githubusercontent.com/assets/1657924/17493855/63d73b64-5db2-11e6-91a6-f5e85aebe66e.png)

If I rewrite the value then the other will be wrong/meaningless.

**Comment by 810** [comment]
1) You need to translated the string on transifex
2) Can also be changed on transifex
3) Already fixed
