### ISSUE TITLE
Announcements will not published

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4271]
#### Steps to reproduce the issue

create announcement, fill every option
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by Hoffi1** [comment]
@xillibit : Please do the same fix on line 172 too (getCount()), thanks. :smile:

**Comment by xillibit** [comment]
> @xillibit : Please do the same fix on line 172 too (getCount()), thanks. :smile:

Thanks to have looked, i will made the change at this line too
