### ISSUE TITLE
Seo: Add nofollow on unread items

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4275]
#### Steps to reproduce the issue
1. Backend->components->kunena forum->configuration->frontend->Show New posts =YES
2. View source code of a page showing unread items
#### Expected result

example.com/category/topic/unread should have a "nofollow"
#### Actual result

Missing "nofollow" in example.com/category/topic/unread
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0
Php version: 7.0.9
Database version: 5.6.31
#### Additional comments

This have a negative impact in SEO performance.
if needed, please add also a noindex

**Comment by 810** [comment]
its has already a nofollow

**Comment by 810** [comment]
I think its the latest module, that has no nofollow

**Comment by sshcli** [comment]
recent topics?

**Comment by 810** [comment]
All on kunena pages it has nofollow

**Comment by sshcli** [comment]
Please skip my procedure to reproduce the error, it could be wrong.
Something is causing /unread pages being indexed, I don't know where to find it, but is there.

**Comment by 810** [comment]
closig this one for new issue
