### ISSUE TITLE
Hardcoded texts in the Log Manager

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#4281]
![image](https://cloud.githubusercontent.com/assets/1657924/17574689/a09cf658-5f63-11e6-8f8e-17aa435665b4.png)
![image](https://cloud.githubusercontent.com/assets/1657924/17574770/2bab645a-5f64-11e6-9bd1-225f345acfca.png)
![image](https://cloud.githubusercontent.com/assets/1657924/17574792/4d754b96-5f64-11e6-87e1-5a3359fbcf8c.png)

**Comment by xillibit** [comment]
I will take care of this one
