### ISSUE TITLE
Seo: need some improvements

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4289]
#### Steps to reproduce the issue

forum/user/
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
for K5.1 we need to add: 

```
$doc->setMetaData('robots', 'index, follow');
```

options, and add it on the topic item

**Comment by sshcli** [comment]
Other issue has been created for these pending changes in K5.1:
https://github.com/Kunena/Kunena-Forum/issues/4300
