### ISSUE TITLE
Page broken when ebay link with allow_url_fopen turned off

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4290]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
When set allow_url_fopen to Off nothing happens, i see no errors and no white page

Try to enable debug mode in both Joomla! and Kunena config to see what's happen

**Comment by 810** [comment]
first create topic, with the follow text:

```
test

http://www.ebay.it/itm/182138870128
```

enable auto embed ebay.

then disable allow_url_fopen.

Then the page can't be opened anymore

**Comment by xillibit** [comment]
I had tried like you said but i don't have a white page and no errors neither

Did-you have enabled debug mode in Joomla! and Kunena config ? Did-you have looked in the Php or apache error log to see the error if there is one ?

**Comment by 810** [comment]
debug is on, no error on the log, just white page, when i turn on the php option, then it showed the page again

**Comment by xillibit** [comment]
which php version ?

**Comment by 810** [comment]
7.0.9

**Comment by xillibit** [comment]
With this php version, i still don't have the issue

**Comment by 810** [comment]
when you disabled the allow_url_fopen, then clean cache. then you will get the white page

**Comment by xillibit** [comment]
I have found the issue : 

`Rendering Error in layout topic/default: Cannot use a stream transport when "allow_url_fopen" is disabled. in C:\wamp64\www\joomla36RC1\libraries\kunena\bbcode\bbcode.php on line 2815
Layout was rendered in C:\wamp64\www\joomla36RC1\index.php on line 49`

I will made a check to see if allow_url_fopen is enabled before to fetch ebay object, in Joomla! requirements it's recommended to enabled it : https://docs.joomla.org/Security_Checklist/Hosting_and_Server_Setup#Use_allow_url_fopen
