### ISSUE TITLE
The minus symbol at the Poll options is inactive

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4296]
#### Steps to reproduce the issue
1. Create a new poll
   add options then try remove a option
2. If you add all allowed options - the minus symbol disappears complete
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1-DEV
Php version: 7.0.8 and 5.6
Database version:

**Comment by xillibit** [comment]
You mean the plus button : 

![plus](https://cloud.githubusercontent.com/assets/876395/17604760/83aad100-6017-11e6-8a91-4053a156a36d.png)

**Comment by 810** [comment]
for me, the minus button do nothing anymore

**Comment by rich20** [comment]
@xillibit the plus button works. But the minus button is inactive. And if the maximum numbers of poll options has been reached, the minus button disappears completely.
