### ISSUE TITLE
Unwanted spaces in the editor

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#4303]
![image](https://cloud.githubusercontent.com/assets/1657924/17619166/ef5d6eaa-6083-11e6-9098-5cc41c8f38f2.png)
![image](https://cloud.githubusercontent.com/assets/1657924/17619271/86dfd60a-6084-11e6-966d-d60ba2247cca.png)
![image](https://cloud.githubusercontent.com/assets/1657924/17619343/09c1deba-6085-11e6-9d86-c91b3d71023f.png)

**Comment by 810** [comment]
why would you not want spaces, the links are hyperlinks, so the whole word, not just a part on a long word.

For the attachments, we use a new line before and after, because the image is on 100% width of the message, so there is no space for something else.

**Comment by csbalazs** [comment]
The url and betwen the punctuation mark will be a unwanted space.
![image](https://cloud.githubusercontent.com/assets/1657924/17624652/c7f6ce02-60a5-11e6-86ee-544b34344c96.png)

**Comment by 810** [comment]
ok, then i will remove only the last space

**Comment by 810** [comment]
then you need to add the ! after exampleurl

so like this:

```
[url=www.example.com]exampleurl![/url]
```

**Comment by csbalazs** [comment]
I think, is is much better if the user can decide whether he need the space or not. If he need it he can insert one. On the other hand there is no space the Github or the phpBB editor.

![image](https://cloud.githubusercontent.com/assets/1657924/17806045/9e204e2a-6602-11e6-9c79-809e81158d9a.png)

**Comment by 810** [comment]
ok found a solution for you:
Add this on your custom.less file

```
.kmsg {
   display: inline-flex;
}
```

mhh is only working on small text, but if longer hten it will break the styling

**Comment by csbalazs** [comment]
It's works, thx!

**Comment by csbalazs** [comment]
Yes, at first it seems like good, but if I have a longer text, it will break the styling, if the text has a bbcode.
![image](https://cloud.githubusercontent.com/assets/1657924/19020756/d8a1bf8a-88b1-11e6-82cb-8163ac4bc692.png)

**Comment by 810** [comment]
then it must be done in the bbcode, because the browser is adding space to it.
Closing this issue
