### ISSUE TITLE
Inherited text message

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#4305]
Feature request

If I wrote something in the Quick Replay area and I click the "Go the editor" then I need to copy the texts to the editor.

![image](https://cloud.githubusercontent.com/assets/1657924/17619589/9e8e7dc2-6086-11e6-82c8-08d28a624980.png)

**Comment by 810** [comment]
this can be done already, if you turn on Recover crash and store fields on the template setting

**Comment by csbalazs** [comment]
https://youtu.be/jUuI_8nzU0U (Recover crash and store fields = Yes)

**Comment by rich20** [comment]
> this can be done already, if you turn on Recover crash and store fields on the template setting

Does not help. It restores only in the same field where you have written.

**Comment by 810** [comment]
duplicated issue, i will close this one.
