### ISSUE TITLE
Date errors

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Forum#4306]
Dates error If I use a different language than the "default language".

In my case: 

Default frontend/backend language: Hungarian.
If I change the default language to English, I get the following errors:

![image](https://cloud.githubusercontent.com/assets/1657924/17620080/020124c4-608a-11e6-8b6c-d5bff1b00d97.png)

![image](https://cloud.githubusercontent.com/assets/1657924/17620121/58207a94-608a-11e6-932d-7025dc8abbbe.png)

In video: https://www.youtube.com/watch?v=HJJnV1j6GBE

**Comment by 810** [comment]
You need to press f5, refresh the site. Then the strings are showed correct. Or clean cache frontend and backend

**Comment by csbalazs** [comment]
It doesn't help.

**Comment by xillibit** [comment]
Do-you have the language strings in the hungarian package ?

**Comment by csbalazs** [comment]
@xillibit: Yes the package has these strings. These strings are displayed, if the backend/frontend language are the same.
![160822](https://cloud.githubusercontent.com/assets/1657924/17867766/2cb97a66-68ac-11e6-9213-16e36bf0ccd9.png)

**Comment by 810** [comment]
should be fixed now, closing this one
