### ISSUE TITLE
No longer view GM+ ban history

### ISSUE THREAD

**Issue by TheEMP** [Kunena/Kunena-Forum#4310]
#### Steps to reproduce the issue

Go any user who is ranked above section moderator
#### Expected result

I should be able to use the ban history of ANY user regardless of their current rank.
#### Actual result

Ban history is no longer displayed...
#### System information (as much as possible)

Joomla version: 3.6(latest)
Kunena version:5.0(latest)
Php version:5.6
Database version:
#### Additional comments

I'm not sure why this was changed from past versions, but I see no reason to hide this information from admin/moderators...

**Comment by 810** [comment]
I can't reproduce this issue, i can see the bann history as moderator/global moderator and admins

**Comment by TheEMP** [comment]
I can see the ban history of regular users fine, but can no longer view the ban history of users who are Global Moderator and above.

**Comment by 810** [comment]
Ok, i see your point.

I will make the history only showed for admins, so mods can't ban other mods, but admins can ban moderators.

But moderators should not be banned.
