### ISSUE TITLE
Display user group from Joomla!, CB into user profile part in messages and in profile

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#4317]
Add in the integration plugins the ability to get user group from Joomla!, CB... to display it under profile part in messages and in profile

**Comment by GJSchaller** [comment]
This can currently be done using the sidebar replacement feature of CB.  I do like this idea a lot, but wanted to be sure it was known the feature already exists in another form.

**Comment by 810** [comment]
that's correct, we have sidebar for that.
