### ISSUE TITLE
Thumbnail image is broken when protect attachments = yes

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4329]
#### Steps to reproduce the issue
1. Protect Attachments = YES
2. Create a new topic , attach an image and save.
3. Edit the topic
#### Expected result

The thumbnail image should be visible
#### Actual result

![broken](https://cloud.githubusercontent.com/assets/12942731/17699845/2174c8ec-6391-11e6-80d7-c675cfcebf0c.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0
Php version: 7.0.9
Database version: 5.6.31

**Comment by xillibit** [comment]
I will take a look in the evening, but this change could have caused the issue : https://github.com/Kunena/Kunena-Forum/commit/c87082905019cfb5614f4509671095b7d448ee9c, i think if you revert it you will able to see protected attachments but not non protected attachments

**Comment by sshcli** [comment]
Ok. I know you can fix this.
Take your time, nobody is complaining about this yet.
