### ISSUE TITLE
Error message in bottom of articles when use discuss plugin

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#4348]
#### Steps to reproduce the issue

With discuss plugin in version 5.0, open an article where the form of plugin is displaying and you should see at bottom of the page the following error message : 

Rendering Error in layout Topic/Item: Property "topic" is not defined in /components/com_kunena/template/crypsis/layouts/topic/item/default.php on line 15
Layout was rendered in /libraries/kunena/layout/base.php on line 183

Settings of discuss plugin : 

Post Order => Latest Posts 
Show on Front Page => Link 
Show on Blog Pages => Link 
Quick Reply Location => Before Posts 
Create Topic on => First Visit 
#### Expected result

No error message
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.0
Php version: 7.0.9
Database version: 10.0.26-MariaDB

**Comment by 810** [comment]
seems to be fixed, i don't have this issue, clossing this issue

**Comment by xillibit** [comment]
I'am not able to reproduce the issue, so i have putted it here to see if someone else is able to reproduce the issue
