### ISSUE TITLE
SEO: Meta Description is Duplicated in Recent Topics

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4354]
#### Steps to reproduce the issue
1. Put a description here: Kunena Menu->Recent Topics ->Metadata->Meta Description 
2. view-source:example.com/forum/recent 
3. view-source:example.com/forum/recent?start=20
#### Expected result

Meta Description should be unique on each page:
example.com/forum/recent
example.com/forum/recent?start=20
#### Actual result

Meta Description is duplicate for both pages:
example.com/forum/recent
example.com/forum/recent?start=20
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0
Php version: 7.0.9
Database version: 5.6.31
#### Additional comments

if possible limit to 160 characters

**Comment by 810** [comment]
For me its: Recent Topics: Kunena Forum - Page 2
