### ISSUE TITLE
Guest users are able to skip the name field

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4366]
#### Steps to reproduce the issue
1. Allow Guests to Post/Write = Yes
2. As a guest, create or reply a topic and insert a blank space in the Name Field
#### Expected result

The Name Field should not allow a blank space as the only value.
#### Actual result

Anyone can skip this field by only inserting a blank space on it.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.9
Database version: 5.6.31

**Comment by 810** [comment]
I don't think this is a problem for me, so users can be Anonymous.

**Comment by sshcli** [comment]
OK.
in that case, please close this issue.

**Comment by xillibit** [comment]
I think the spaces in the name aren't cleaned when the message is saved

**Comment by sshcli** [comment]
In my opinion, a checkbox for anonymous (beside the name field) provides a better UX
