### ISSUE TITLE
Add option to replace brand image in notification emails

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4375]
#### Steps to reproduce the issue
1. Subscribe to any topic or category
2. Wait for someone to reply or create a new topic
3. You will receive a notification email with a generic brand image
#### Expected result

There must be an option in the backend to replace the brand image that is used in notification emails.
It could be in some place around here:
![suscriptions](https://cloud.githubusercontent.com/assets/12942731/17834810/970e9e70-671f-11e6-9b6d-bb0671a28c8b.PNG)
#### Actual result

There's no option to replace the brand image that is used in notification emails (/media/kunena/email/hero-wide.png)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.9
Database version: 5.6.31

**Comment by JoshWobbles** [comment]
Where is this? I dont see the option.

**Comment by 810** [comment]
config - users - Subscriptions - Email Header Image
