### ISSUE TITLE
Cannot upload attachment

### ISSUE THREAD

**Issue by MoleDJ** [Kunena/Kunena-Forum#4380]
#### Steps to reproduce the issue

I am the developer of tapatalk kunena plugin, i am in final stage of launch the plugin with support for kunena 5, but I have a problem uploading attahcment. I use the function libraries\kunena\attachment\attachment.php upload($key = 'kattachment', $catid = null)
The issue come from file libraries\kunena\upload\upload.php, upload($fileInput, $destination, $type = 'attachment'), expecifically in this lines:
if ($type != 'attachment' && $config->attachment_utf8)
        {
            $file->tmp_name = $fileInput['tmp_name'];
        }
        else
        {
            $file->tmp_name = JFile::makeSafe($fileInput['tmp_name']);
        }

the line $file->tmp_name = JFile::makeSafe($fileInput['tmp_name']); generate invalid path (as it sends to the function something like '/tmp/kjsadhk.jpg', and it converst to something like 'kljsadhasd8' that is not a file in the filesystem.

I changed all this "if" sentence to a simple  $file->tmp_name = $fileInput['tmp_name']; like it is in kn4, and all work as expected. So, i dont know if this change is intented or it is really a bug.
#### Expected result

upload success
#### Actual result

cant upload because cannot move uploaded file
#### System information (as much as possible)

Joomla version: 
Kunena version: 5.0.1
Php version: 7.0.7
Database version:

**Comment by 810** [comment]
We have added this kunena configuration option, because some software (akeeba backup) can't handle the ut8 (like chinese) filenames when add the files to the jpa backup.

We suggest to not use this option, but there are a few people who wanted this. 

```
Kunena 帖子中站内链接 nofollow 问题.txt
```

becomes Kunenanofollow.txt

and the file is correct uploaded to:
media/kunena/attachments/237/Kunenanofollow.txt

**Comment by MoleDJ** [comment]
the main problem i think is JFile::makeSafe() expect that file parameter is the name of the file, not the full path, so it breaks the real filename. 

I rechecked the code and I propose this change in your upload.php library, function upload, lines around 655

if ($type != 'attachment' && $config->attachment_utf8)
{
            $file->tmp_name = $fileInput['tmp_name'];
}
else
{
//this is my proposed change
$pathInfo = pathinfo($fileInput['tmp_name']);
$file->tmp_name = $pathInfo['dirname'] . '/' . JFile::makeSafe($pathInfo['basename']);
}

this preserve your new logic and make tmp name working in case upload is 'attachment'

**Comment by 810** [comment]
Ok, the code is still working, if you can do a pr. then i will merge it

**Comment by MoleDJ** [comment]
I sent the pr, thanks! i will procced in any case on the release of a beta tapatalk plugin for kunena 5 in next days (and i will advice users that attachment functionality will need a kunena update). As always, from Tapatalk, if you have any questions regarding our plugin, or you see something in our plugin that hurts you, feel free contact me directly ;)
