### ISSUE TITLE
The option Use English On Missing Strings works not for the file site-com_kunena.ini

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4391]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/138276-kunena-5-0-1-language-strings-problem-com_kunena_x_topics-etc
1. Install another language
2. Comment out following language strings in site-com_kunena.ini
; COM_KUNENA_X_TOPICS_0 = "No topics"
; COM_KUNENA_X_TOPICS_1 = "%s topic"
; COM_KUNENA_X_TOPICS_MORE = "%s topics"
3. Configuration:
    Enable Debug Mode = No
    Use English On Missing Strings = Yes
4. Go in frontend to index
#### Expected result

Engish language for missing strings
#### Actual result

It shows only language codes
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1 and 5.0.2-DEV
Php version: 5.6 and 7.0.8
Database version:
#### Additional comments

This problem exists only with the site-com_kunena.ini,  when some string are already to translated. Is in this ini file nothing translated, or the file is empty (or removed), then works the option "Use English On Missing Strings".
But once a translated string is available in this file, then the option "Use English On Missing Strings " no longer works.

**Comment by 810** [comment]
Works fine for me:

Before:
(136 onderwerpen) 

adding ; before strings

```
;COM_KUNENA_X_TOPICS_0 = "Geen onderwerpen"
;COM_KUNENA_X_TOPICS_1 = "%s onderwerp"
;COM_KUNENA_X_TOPICS_MORE = "%s onderwerpen"
```

after saving:
(136 topics)
