### ISSUE TITLE
The word "Donate" is not translated

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4394]
#### Steps to reproduce the issue
1. Go to /credits page
#### Expected result

The word "Donate" should be translated to all languages.
#### Actual result

The word "Donate" is not translated
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.9
Database version: 5.6.31

**Comment by xillibit** [comment]
You mean on the image ?

**Comment by sshcli** [comment]
I mean this word
![thisword](https://cloud.githubusercontent.com/assets/12942731/18127269/4a28d176-6f4d-11e6-9f9e-fa2607a741e5.PNG)
