### ISSUE TITLE
search pagination broken

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4397]
#### Steps to reproduce the issue

use search, go to second page
#### Expected result

see page 2
#### Actual result

new search
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
What's happen when you go on second page ?

**Comment by 810** [comment]
you are redirected to a new search page

see: https://www.kunena.org/forum/search?query=test&searchdate=all&childforums=1
