### ISSUE TITLE
Add option to disable signatures

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4399]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by demis-palma** [comment]
I've found that often spammers participate with regular posts, but after a few days, they change their signature, adding spam in it. That automatically creates spam on each message they send previously, and it's really hard to detect.

Is that the reason why you are planning to add an option to disable signatures, or there is something else?

**Comment by 810** [comment]
it was just for visual, but what you said is also true, so we can fix both issues, with the same option
