### ISSUE TITLE
Add suffix breaks preview

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4401]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
Leave a comment

**Comment by 810** [comment]
https://www.kunena.org/forum/k5-0-support/148835-preview-does-not-work-with-5-0-11-either#194956

**Comment by xillibit** [comment]
this one is fixed ?

**Comment by 810** [comment]
no, its still there, will add a addScriptOptions for it.
