### ISSUE TITLE
Feature: Private reply for topics/messages

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4405]
#### Expected result

Public and Private replies should be allowed in kunena
#### Actual result

Only public replies are allowed in kunena 
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by mahagr** [comment]
Its already implemented in rtv3 branch :) Though in there I have restriction that only moderators and the person sees the messages, but it was pretty simple hadcoded limitation.

https://github.com/rockettheme/Kunena-Forum/tree/rtv3

**Comment by xillibit** [comment]
I have started to implement it in Kunena 5.0 : https://github.com/xillibit/Kunena-forum/commits/k5.0_private_message_2, it's missing the handle of attachments when the message is private and another thing that i'am not remember

**Comment by xillibit** [comment]
Done in this PR in Kunena 6.0 just merged : https://github.com/Kunena/Kunena-Forum/pull/6626
