### ISSUE TITLE
Backend: fix deleting topics/messages for large sites

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4408]
#### Steps to reproduce the issue

Delete topics
#### Expected result

deleted
#### Actual result

error 500 or error 524 after some time the query is running
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Error 524 doesn't exist it's only with cloufare when something goes wrong

**Comment by 810** [comment]
when removing the recount, i getting this error

Lock wait timeout exceeded; try restarting transaction SQL=DELETE FROM #__kunena_topics WHERE `id` = '136422'

after removing the recount, its works. So we need to move the recount after the function is used.

libraries\kunena\forum\topic\topic.php function delete

**Comment by cybersholt** [comment]
Same problem with:

Joomla version: 3.6
Kunena version: 5.0.1
Php version: 7.0.9
Database version: MySQL 5.7.14

Confirmed that disabling the recount did fix the issue. 

Medium sized forum > 100k users & ~ 550 k posts. 

EDIT: Forgot to mention that the problem exists for the frontend as well.
