### ISSUE TITLE
Feature: Notification email when topic/message is approved

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4414]
#### Steps to reproduce the issue

There's no issue. It's a feature request
#### Expected result

Visitors should receive a notification email when the topic/message has been approved.
#### Actual result

Visitors don't receive any notification when a topic/message has been approved.
#### System information (as much as possible)

Joomla version:
Kunena version: 
Php version: 
Database version:

**Comment by pgasiorowski** [comment]
I think this one has already been solved?
Works fine in 5.1.1

**Comment by sshcli** [comment]
> I think this one has already been solved?
> Works fine in 5.1.1

Yes, it is working.
Thanks
I'm closing this one

**Comment by sshcli** [comment]
A new issue has been created to change the message received after topic approval:
See https://github.com/Kunena/Kunena-Forum/issues/7446
