### ISSUE TITLE
No permadelete link on recent post

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4416]
#### Steps to reproduce the issue

menu item:
recent posts - deleted messages
#### Expected result

see the permadelete option in the dropdown
#### Actual result

only delete
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
You have tested with moderators and admins ?

**Comment by 810** [comment]
global moderator.

We removed yesterday all deleted topics and messages on k.org. With posts there was a perm delete on the dropdown. Only for messsages there was just 2 options.

**Comment by 810** [comment]
mhh now its working correct, closing this issue
