### ISSUE TITLE
SEO:  Meta Robots not working as expected in Search Menu 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4424]
#### Steps to reproduce the issue
1. Backend->Menus->Kunena Menu->Edit menu item "Search"->Metadata->Robots = Index, Follow
2. view-source:http://example.com/forum/search
#### Expected result

You should see this:
<meta name="robots" content="index, follow" />
#### Actual result

You will get this:
<meta name="robots" content="nofollow, noindex" />
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by 810** [comment]
search page should never be indexed by a search crawler
