### ISSUE TITLE
Html tags in topic title have a negative impact

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4427]
#### Steps to reproduce the issue

Enter a html tag such as `<button>` (without end tag) in the topic title
#### Actual result

The newchar shows the html commands
Example: topic title is `Test<br><br><br><h1><button>Test`
![bildschirmfoto vom 2016-08-29 20-32-12](https://cloud.githubusercontent.com/assets/888847/18062746/6f2f4e9e-6e28-11e6-8a6b-84a77945e84d.png)
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
Confirmed. 
![bug2](https://cloud.githubusercontent.com/assets/12942731/18063104/a2b6b3b4-6df7-11e6-823c-dbe50752bd48.PNG)
