### ISSUE TITLE
Submit button is enabled during upload process

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4429]
#### Steps to reproduce the issue
1. Create a new topic and upload a big file (For example: 7 MB)
2. Click the submit button before the upload process is complete.
#### Expected result

The submit button should be disabled until the upload process is complete.
Progress bar should be displayed.
#### Actual result

The new topic is created without the uploaded file.
Progress bar not being shown.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by xillibit** [comment]
I will look to disable submit button when the file is uploading, to show a progress bar i will do it in Kunena 5.1

**Comment by sshcli** [comment]
Agree with your decision

**Comment by xillibit** [comment]
> I will look to disable submit button when the file is uploading, to show a progress bar i will do it in Kunena 5.1

Add a new entry for progress bar else it will forgotten

**Comment by sshcli** [comment]
> Add a new entry for progress bar else it will forgotten

Done. https://github.com/Kunena/Kunena-Forum/issues/4498
