### ISSUE TITLE
Opera mini ignores defined value in message title length

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4432]
#### Steps to reproduce the issue
1. Crypsis->Basic settings->Message title length = 50
2. Install Opera Mini web browser in your smartphone
3. Using Opera Mini, Create a new topic and insert in the subject field more than 50 characters 
#### Expected result

You should be restricted to only 50 characters 
#### Actual result

You can insert unlimited characters in the subject field
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by xillibit** [comment]
If i change the setting "Message title length", when i check with firefox the maxlength in the input has the correct value. I don't know if with opera mini you have access to a developement console to check that.

**Comment by sshcli** [comment]
if such option exist, I don't know how to activate it

**Comment by 810** [comment]
looks like me its a browser issue, closing this issue

**Comment by sshcli** [comment]
> looks like me its a browser issue, closing this issue

Opera mini is not compatible with kunena, there are too many errors / issues.
Can you add a notification / warning?
"Your browser is not compatible with this website, you must use another browser bla bla bla"

**Comment by xillibit** [comment]
I can detect which browser is used and display this kind of message

**Comment by sshcli** [comment]
Great.
Because there other browsers not compatible with kunena, not only Opera mini.
Another one is: UC Mini, and I'm sure there are many others.

Do you need a new issue for this? or you will use this one?

**Comment by sshcli** [comment]
If possible, Please include a solution in the message.
When I say a solution, I mean a reference or download link to the most recommended browsers for kunena.

**Comment by xillibit** [comment]
I will use this issue

**Comment by sshcli** [comment]
Ok.
Then please reopen this issue.
It can be forgotten if remains closed

**Comment by 810** [comment]
Could you update opera mini and check it again.

It should work: http://caniuse.com/#feat=maxlength

**Comment by 810** [comment]
http://forums.opera.com/discussion/1882186/html-element-text-input-types-maxlength-attribute-is-not-working/p1

**Comment by 810** [comment]
closing this one, if you want you can report the issue on opera.
