### ISSUE TITLE
Removing in new Reply Attachments doesn't work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4452]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/138306-removing-in-new-reply-attachments-doesn-t-work
1. Click on reply and add one or more attachments
2. Click on Remove All
3. Click on Submit
#### Expected result

A replied message without attachments
#### Actual result

The attachments will removed from the preview but nevertheless inserted in the message
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2-DEV
Php version:
Database version:

**Comment by xillibit** [comment]
The first time when i had tried, i was able to reproduce the issue now i'am not able to reproduce the issue

**Comment by 810** [comment]
on crypsisb3 there is no delete all button

**Comment by 810** [comment]
With crypsis, the bug is still there

**Comment by xillibit** [comment]
> on crypsisb3 there is no delete all button

I may have forgot to add the delete all button to crypsis b3

**Comment by 810** [comment]
you need to insert the image before clicking remove all

**Comment by xillibit** [comment]
I'am still not able to reproduce the issue

**Comment by 810** [comment]
new topic, add picture, insert picture. then click remove all.

then you see the [attachment=237]03_title.jpg[/attachment] tag is still in the message

**Comment by 810** [comment]
also in message, is still active (green color)

**Comment by 810** [comment]
there must be done 4 things:

1) add on $('#insert-all').on('click', function (e)

```
$('#insert-all').removeClass('btn-primary');
$('#insert-all').addClass('btn-success');
$('#insert-all').html('<i class="icon-upload"></i>' + Joomla.JText._'COM_KUNENA_EDITOR_IN_MESSAGE'));
```

2) when delete all, hide insert and delete buttons
3) When adding file again, they need to show up again
4) When delete all, remove the attachement tags in the message

**Comment by 810** [comment]
still a issue, the attachments are still added to the message

**Comment by rich20** [comment]
issue is still there

**Comment by xillibit** [comment]
Issue still exist ?

**Comment by xillibit** [comment]
Similar issue that this one : https://github.com/Kunena/Kunena-Forum/issues/5716
