### ISSUE TITLE
Can't search by specific date

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4465]
#### Steps to reproduce the issue
1. Go to example.com/forum/search
2. Try to search all the posts created on April 29 2016 (Example date, you can use another)
#### Expected result

You should be able to see only the posts created on April 29 2016
#### Actual result

There is no option in the drop down list to choose a specific date
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by xillibit** [comment]
If we want to search at a specific date,  i think we can add a datepicker to choose the date

**Comment by sshcli** [comment]
A datepicker seems to be a good idea. 
Whatever you do will be fine.
