### ISSUE TITLE
status is set offline

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4469]
#### Steps to reproduce the issue

The status from the users are always offline.

Color on the avatar is correct, only the label is offline
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
on new jversion i don't have this issue, let wait until the new joomla is released

**Comment by xillibit** [comment]
It should be fixed with J3.6.3

**Comment by 810** [comment]
its strange suddenly its working on k.org

**Comment by sshcli** [comment]
Sometimes memcache/dynamic cache/JSGcache cause this kind of issues
