### ISSUE TITLE
"last post" link points to "quick reply input box" instead of the correct post message

### ISSUE THREAD

**Issue by joomlagate** [Kunena/Kunena-Forum#4472]
#### Steps to reproduce the issue

Login Kunena as a registered user.
open any category (topic list) page
choose a topic contains several posts (the more the better)
click on the "last post" link in the right end column
#### Expected result

This link should open the topic detail page and show the last post message (automatically scroll down if necessary)
#### Actual result

It show me the "quick reply" input box , this means: it scrolls down TOO MUCH.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 5.6.26
Database version: 5.5

**Comment by 810** [comment]
could you give me your settings from cypsis for the Show default actions and Type Quickreply

**Comment by joomlagate** [comment]
My Kunena configuration about template Crypsis:

Show default actions: No
Type Quickreply:  Always visible

Thank you.

**Comment by 810** [comment]
I had already fixed this: https://github.com/Kunena/Kunena-Forum/pull/4467
