### ISSUE TITLE
RSS Exclude Categories not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4480]
#### Steps to reproduce the issue
1. Create a new category: category1 (write down the ID of this category)
2. Go to configuration->RSS->Exclude Categories=Put here the ID of category1
3. Go to example.com/topics/mode-topics/catid-9?format=feed (Replace the "9" by your ID#)
#### Expected result

The category should be also excluded in this view:
example.com/topics/mode-topics/catid-9?format=feed
#### Actual result

The category is only excluded in this view:
example.com/topics/mode-topics?format=feed
#### System information (as much as possible)

Joomla version:  3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by xillibit** [comment]
I'am looking to this issue, to exclude or include some categories it woks only when you use this kind or URL : example.com/topics/mode-topics?format=feed

I will change a bit the logic to make it working

**Comment by sshcli** [comment]
> I will change a bit the logic to make it working

Ok.
If you are going to touch the URL behavior, please take into consideration the use of SEF.
example.com/rss
example.com/rss/categoryname1
example.com/rss/categoryname2
.........

**Comment by xillibit** [comment]
I'am not sure if i can change the URLs like that, i can't remove the format=feed at the end

**Comment by sshcli** [comment]
Ok, no problem.

**Comment by 810** [comment]
Leave a comment
