### ISSUE TITLE
Rss button on IE not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4483]
#### Steps to reproduce the issue
1. Open your website with Microsoft Internet Explorer
2. Go to any category (example.com/main-forum) and click the rss button located in the command bar
   ![rssbutton](https://cloud.githubusercontent.com/assets/12942731/18417600/e748f6e4-7802-11e6-8515-6b55adfd89c1.PNG)
#### Expected result

The RSS for the specific category should be opened.
#### Actual result

It opens the rss from the entire website, not only for the specific category
#### System information (as much as possible)

Joomla version:  3.6.2
Kunena version: 5.0.2
Php version: 7.0.10
Database version: 5.6.1
#### Additional comments

A good reference website for feed behavior is: news.google.com

**Comment by 810** [comment]
this can't be changed, because the view is loaded on all topics page, we need to recode everything on rss. If we still wanted to support rss.

**Comment by sshcli** [comment]
Ok. No problem
