### ISSUE TITLE
Improve Rating Feature

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4484]
#### Steps to reproduce the issue
1. Configuration->Frontend->Allow rating = YES
2. Categories->CategoryX->Category settings->Allow rating = YES
3. Rate a topic
#### Expected result

You should be able to delete/undo the rating, at least as a moderator/super admin.
Other features already provide such option, here are some:
subscribe
Thank you
Favorite
Karma
#### Actual result

You can't  delete/undo a rating, even a moderator/super admin can't do it.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31
#### Additional comments

As a plus, consider to add these options:
Edit rating
Add comment to rating
Show quantity of ratings

**Comment by xillibit** [comment]
> As a plus, consider to add these options:
> Edit rating
> Add comment to rating
> Show quantity of ratings

In K5.1

**Comment by sshcli** [comment]
> In K5.1

Done. https://github.com/Kunena/Kunena-Forum/issues/4499
