### ISSUE TITLE
Can't see target category full name

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4488]
#### Steps to reproduce the issue
1. Create a new category (32 Characters)
2. Create a sub category for that category (32 Characters)
3. Create a topic in the category
4. Moderate topic->Move options
#### Expected result

You should see the whole name of the category.
![goodcat](https://cloud.githubusercontent.com/assets/12942731/18439788/a4415076-78d4-11e6-8993-b8aa84c9681c.PNG)
#### Actual result

You can only see a part of the category name.
![badcat](https://cloud.githubusercontent.com/assets/12942731/18439780/9fc97e60-78d4-11e6-84fe-a4346c8ba02b.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.10
Database version: 5.6.31

**Comment by 810** [comment]
When you select the select box, you will see the full name

**Comment by sshcli** [comment]
Yes, I am aware of that. 
In that case, if this is not considered as a bug, please close this issue. 
Thanks in advance
