### ISSUE TITLE
Ctrl+z doesn't work for bbcode tags

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4489]
#### Steps to reproduce the issue
1. Go to example.com/forum/newtopic and put the cursor in the message field
2. Press Ctrl+b
3. Press Ctrl+z
#### Expected result

[b][/b] should be removed from editor
#### Actual result

Ctrl+z doesn't have any effect here
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by 810** [comment]
For me crtl-z is working

**Comment by sshcli** [comment]
That's strange, I have tested on 3 websites with 2 browsers (IE and Chrome).
In that case, please put this issue on hold until get test results from someone else.

**Comment by sshcli** [comment]
just in case you are testing in this way...
while you are testing, you should not press the delete button to test if Ctrl+z is working or not

The test is only by inserting the element and then remove the element by pressing  Ctrl+z.

It works for standard characters like A,B,C.. but doesn't work if only insert bbcode tags like [b][/b]

**Comment by 810** [comment]
sometimes only [b][/b] is deleted and sometimes everything is deleted, depends on the typ speed
