### ISSUE TITLE
Map: The city field is optional

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4493]
#### Steps to reproduce the issue
1. Create a new post and insert a Map
#### Expected result

The city field should be a required field
![map](https://cloud.githubusercontent.com/assets/12942731/18477753/bf5adde6-799c-11e6-9113-ed87f8cb4e8a.PNG)
#### Actual result

The city field is an optional field
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31
#### Additional comments

Note1: The city field doesn't have a placeholder or hint.
Note2: There could be other problems with the map feature that are not reported here.

**Comment by 810** [comment]
We can't do that, then you need to fill the field.

Also when you don't need a map. Because the modals are always loaded.

**Comment by sshcli** [comment]
OK, no problem.
