### ISSUE TITLE
Map not working if API key is restricted

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4495]
#### Steps to reproduce the issue
1. Go to https://console.developers.google.com/projectselector/apis/credentials and create an API key.
2.  Restrict your API key to _.example.com/_
3. Configuration->BBCode Settings->BBCode->Google maps API key to get better stats usage of google API = Insert your restricted API key here
4. Create a new topic and insert a map in the content
#### Expected result

You should be able to see the map if your website is example.com
#### Actual result

You will get this error: 
![restricted](https://cloud.githubusercontent.com/assets/12942731/18480077/53b7bb28-79a5-11e6-8a1c-702b3e835895.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by 810** [comment]
yes, the message is correct, you have entered a wrong domain on the api at googles website.

**Comment by xillibit** [comment]
> Restrict your API key to .example.com/

Why you don't enter www.example.com or example.com ?

**Comment by sshcli** [comment]
@810 said: yes, the message is correct, you have entered a wrong domain on the api at googles website.
@sshcli said:
No, the domain is not wrong, I have tested with 2 domains simultaneously and the results are the same

@xillibit said: Why you don't enter www.example.com or example.com ?
@sshcli said: Because this is the suggested format by google. Please take a look to the picture below:

![suggested](https://cloud.githubusercontent.com/assets/12942731/18481433/2e0084be-79aa-11e6-97e9-b585830d895d.PNG)

**Comment by xillibit** [comment]
And what it said in javascript console ?

**Comment by sshcli** [comment]
> And what it said in javascript console ?

This is the error:
![console](https://cloud.githubusercontent.com/assets/12942731/18484604/24215c0e-79b7-11e6-919c-abc499894c1f.PNG)

The problem is solved if I enter the complete URL in google API console.

**Comment by 810** [comment]
this is a issue on google part. we can't change that,so im closing this issue

**Comment by sshcli** [comment]
Ok, no problem

**Comment by jsd3** [comment]
isn't the mapping text just wrong - it needs wildcards or more accuracy for matching? e.g. 
\*.example.com/\*
