### ISSUE TITLE
Avatar image not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4500]
#### Steps to reproduce the issue
1. Crypsis->features->Avatar Type = Circle
2. Go to your profile and upload an avatar 144x44
3. Go to example.com/forum/index
#### Expected result

![example4](https://cloud.githubusercontent.com/assets/12942731/18491443/6d8504d2-79d4-11e6-8e05-e80cbbc21d98.PNG)
#### Actual result

![example3](https://cloud.githubusercontent.com/assets/12942731/18491447/717cd4fc-79d4-11e6-985b-840ebf7f1a10.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by 810** [comment]
this is a feature called: Avatar Cropping its on the avatar tab on the kunena config
Set this to No and try again

**Comment by sshcli** [comment]
> Set this to No and try again

it's NO by default.
I have switched between YES and NO several times, also delete and upload avatar several times.
Problem persist.

**Comment by 810** [comment]
then try resize method to bicubic

**Comment by sshcli** [comment]
> then try resize method to bicubic

Doesn't work.

Attached is the image being used as an avatar
![avatar](https://cloud.githubusercontent.com/assets/12942731/18536197/0983ac22-7ac9-11e6-9be4-ce61b991f40b.jpg)

**Comment by sshcli** [comment]
Another solution to prevent this could be add the option to "Preview image" before it is uploaded and saved.
This will make sure the image will be uploaded and saved in the expected way.
The same technique used here in GitHub:
https://github.com/settings/profile

**Comment by xillibit** [comment]
In Kunena 5.1, i want to implement avatar upload by ajax, so you will preview it in the form before save. It will work in a similar way than attachments upload.

**Comment by sshcli** [comment]
Do you mean this issue?
https://github.com/Kunena/Kunena-Forum/issues/3885

**Comment by xillibit** [comment]
Yes it's this one

**Comment by sshcli** [comment]
Ok, in that case let's close this request.

This issue has been closed because it will fixed in K.5.1 with this feature: https://github.com/Kunena/Kunena-Forum/issues/3885
