### ISSUE TITLE
Page title is the same for every RSS

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4507]
#### Steps to reproduce the issue
1. Go to any category and open the rss for that category
2. Take a look to the page title
#### Expected result

The RSS should contain the category name in the page title, For example:

Sports - Kunena
example.com/forum/topics/mode-topics/catid-1?format=feed

Health - Kunena
example.com/forum/topics/mode-topics/catid-2?format=feed

Technology - Kunena 
example.com/forum/topics/mode-topics/catid-3?format=feed
#### Actual result

The Page title is the same for every RSS

Recent topics - Kunena
example.com/forum/topics/mode-topics/catid-1?format=feed
example.com/forum/topics/mode-topics/catid-2?format=feed
example.com/forum/topics/mode-topics/catid-3?format=feed
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31
#### Additional comments

RSS Feeds from news.google.com are a good reference.

**Comment by 810** [comment]
because limitation we can't change this.

**Comment by sshcli** [comment]
Ok, no problem.
