### ISSUE TITLE
username instead of name in search results

### ISSUE THREAD

**Issue by owgpz** [Kunena/Kunena-Forum#4508]
#### Steps to reproduce the issue

Set the forum to display name instead of username
Open a search dialog in the forum - enter a search term
Perform the search
#### Expected result

Search results with **name** in the topic header like: "Ricky replied to the topic..."
#### Actual result

**User name** is displayed: instead of "Ricky", "rz" is displayed, which is the user name. The name is properly displayed when doing anything except search results
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 5.3
Database version: ?

**Comment by 810** [comment]
thnx for the report, but we have already fixed it. Will be on the next version
