### ISSUE TITLE
Attached image not supported by social networks

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4509]
#### Steps to reproduce the issue
1. Create a new website with K.4.0.11+Blue Eagle
2. Create a topic and attach this image: https://goo.gl/Qejb9a
3. Share the topic in LinkedIn and google+
4. Create a new website with K.5.0.1+Crypsis
5. Create a topic and attach this image: https://goo.gl/Qejb9a
6. Share the topic in LinkedIn and google+
#### Expected result

LinkedIn and Google+ will automatically display the image attached in the topic for Both (K4 and K5)
#### Actual result

LinkedIn and Google+ will automatically display the image attached in the topic only if you are using K4+Blue Eagle (Doesn't work in K5+Crypsis)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31
#### Additional comments

Source code for k4 landing page:
[k4.txt](https://github.com/Kunena/Kunena-Forum/files/471245/k4.txt)

Source code for k5 landing page:
[K5.txt](https://github.com/Kunena/Kunena-Forum/files/471246/K5.txt)

**Comment by 810** [comment]
for me its ok, try https://www.kunena.org/forum/k5-0-support/138500-how-to-have-label-question,-solved,-loved,-idea-near-topic-title

**Comment by sshcli** [comment]
Please try with these conditions:

Topic with only 1 image attached. 
The image is not inserted in the message, only attached.
The author doesn't have a custom avatar.
A topic without replies.
Test with Google+

For example::
https://www.kunena.org/forum/general-questions-archive/137011-forum-is-cutting-off-some-of-the-user-message-plz-see-pic

**Comment by sshcli** [comment]
Maybe the position of the image in the source code.
when compare source code from both versions (K4 and K5) you will notice that the image in k4 is loaded in a better position.
K4 = Line 243
K5 =  Line 644

**Comment by 810** [comment]
Looks like a issue on the 3rt party plugin, because with the facebook its ok.

**Comment by sshcli** [comment]
Is up to you if you want to keep this issue open until is solved, I did my part (Detect a bug and report it)
