### ISSUE TITLE
Can't see who deleted the topic or message

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4570]
#### Steps to reproduce the issue
1. Delete a topic or message
2. Go to deleted topics or deleted posts menu
#### Expected result

As a moderator or super admin, you should be able to see who deleted the topic or message.
You need to know if it was deleted by the user itself or if it was deleted by one of your moderators.
#### Actual result

You can't see who deleted the topic or message
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by xillibit** [comment]
You don't see it in the logs in the backend ?

**Comment by sshcli** [comment]
Yes, I can see it.
But not every moderator has access to the backend.

**Comment by 810** [comment]
this is coming to K5.1 closing this one

**Comment by sshcli** [comment]
> this is coming to K5.1 closing this one

is there an issue already created for this or do I need to create a new one?

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/issues/3879

**Comment by sshcli** [comment]
Ok. Got it
