### ISSUE TITLE
Show Edited Mark Up not working during moderate topic process

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4583]
#### Steps to reproduce the issue
1. Configuration->users->user related->Show Edited Mark Up = YES
2. Move a topic from Category1 to Category2 and set a new subject during the process.
#### Expected result

Topic should contain the "Last Edit" label at the bottom.
#### Actual result

The topic is not marked as edited.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.10
Database version: 5.6.31

**Comment by 810** [comment]
this is correct, the topic is only moved, not changed any text in the message

**Comment by sshcli** [comment]
If you change the topic title here, you will the Edited Mark Up:

![here2](https://cloud.githubusercontent.com/assets/12942731/18698237/834c602c-7f96-11e6-9752-c005c75718a6.PNG)

If you change the topic title here, you won't see the Edited Mark Up:

![here](https://cloud.githubusercontent.com/assets/12942731/18698245/9611358e-7f96-11e6-88e6-3bd1a64f3639.PNG)

My question is:
Is this a bug or not ?

**Comment by 810** [comment]
No, you haven't changed the message
