### ISSUE TITLE
Can't edit a topic from deleted user twice

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4591]
#### Steps to reproduce the issue
1. User1 create a topic (Topic1)
2. With admin account, delete the user account (User1)
3. Moderator edit Topic1
4. Moderator try to edit Topic1 again 
#### Expected result

Moderator should be able to edit Topic1 infinite times
#### Actual result

Moderator can only edit Topic1 once, because the Submit button does not response on the second edit.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.9
Database version: 5.6.31

**Comment by xillibit** [comment]
Now that you have delete the user, the user in the topic is now considered like a guest and ask you to enter an user name but the field to enter it isn't here

**Comment by sshcli** [comment]
Ok, that's why. it make sense
What's the plan?

**Comment by xillibit** [comment]
The field for username has just a display:none so i need to look to remove it completly when not need

**Comment by sshcli** [comment]
OK.

**Comment by 810** [comment]
could you check again, i can edit inlimited times the topic, only I see no name

**Comment by sshcli** [comment]
Confirmed.
The problem is now solved in pkg_kunena_v5.0.3-DEV_2016-10-20.zip

**Comment by joomlabid** [comment]
Is there a plan for release date for v5.0.3 or its estimated?

**Comment by 810** [comment]
we have a plan, we are doing the final tests

**Comment by sshcli** [comment]
I see the bug again in 5.0.4.1

**Comment by sshcli** [comment]
Now that name field is optional again, seems like this problem doesn't exist anymore. 
I'm closing this one now.
