### ISSUE TITLE
Checkbox Toggle (check all / uncheck all) not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4593]
#### Steps to reproduce the issue
1. Go to recent topics view: example.com/forum/recent
2. Select two topics and then check the "Check all"
#### Expected result

![good1](https://cloud.githubusercontent.com/assets/12942731/18799728/2905034a-81a7-11e6-8887-e68eb3209d33.PNG)![good2](https://cloud.githubusercontent.com/assets/12942731/18799729/2905c938-81a7-11e6-8cc9-c57c171f887b.PNG)
#### Actual result

![bad1](https://cloud.githubusercontent.com/assets/12942731/18799731/2ddb0c16-81a7-11e6-971b-a652c3366859.PNG)![bad2](https://cloud.githubusercontent.com/assets/12942731/18799730/2dd8a35e-81a7-11e6-90b9-d1d21c425876.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1 and 4.0.11
Php version: 7.0.9 and 7.0.11
Database version: 5.6.33

**Comment by rich20** [comment]
- [x] Success
