### ISSUE TITLE
User can't delete a topic with replies, only post

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4597]
#### Steps to reproduce the issue
1. Backend->Components->Kunena forum->Configuration->Security
#### Expected result

This option should be available in the backend:
User can delete own topics = Always
#### Actual result

Only this option is available in the backend:
User can delete own post = Always
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.11
Database version: 5.6.33

**Comment by xillibit** [comment]
So, you mean that it's missing an option in the backend nammed : "User can delete own topics = Always" ?

**Comment by rich20** [comment]
#### Expected result

This option should be available in the backend:
User can delete **own topics** = Always

In my opinion this would be incorrect. The user would delete with this option answers from other users.

**Comment by sshcli** [comment]
> @xillibit said: So, you mean that it's missing an option in the backend nammed : "User can delete own topics = Always" ?

I'm suggesting a new option named: "User can delete own **topics**" with 2 possible options: NO, YES

>  @rich20 said: In my opinion this would be incorrect. The user would delete with this option answers from other users.

That's correct,
1. but if the user has deleted the original post, then all the replies has no sense. 
2. Also, the first reply will become the main topic, which is wrong because the reply could a simple and vague word such as "Ok"
3. Also all the users subscribed in the topic still receive notifications emails for a non existing topic, just replies.
4. New members will get confuse about the purpose of that topic, because the original post has been deleted. 
5. The owner of the first reply haven't authorized a switch from a reply to a main topic.

In my opinion, it's a decision that the site owner should take, not us, that's why the option is needed.

**Comment by xillibit** [comment]
or maybe in the setting "User can delete own post" add a new option to prevent user to delete his post if it's the first of the topic and allow to delete posts if it's not the first of topic

**Comment by sshcli** [comment]
> or maybe in the option "User can delete own post" add a new option to prevent user to delete his post if it's the first of the topic and allow to delete posts if it's not the first of topic

Sounds a good idea.

Options:
Never
When no replies
**All, except main when replies**
Always

Maybe you have a shorter name in your mind

**Comment by GJSchaller** [comment]
Suggested option names:
- Never
- Only if no replies
- Yes, but replies remain
- Yes, and all replies as well
