### ISSUE TITLE
Word "Topics" being used in a wrong place

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4603]
#### Steps to reproduce the issue

Go to: example.com/forum/profile/000-exampleusername
#### Expected result

The word "Posts" should be used instead.
#### Actual result

The word "Topics" is being used in a wrong place

![wrongword](https://cloud.githubusercontent.com/assets/12942731/18887739/52ed60b6-84c3-11e6-8e03-04396474920a.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.11
Database version: 5.6.33

**Comment by 810** [comment]
I see messages not topics

**Comment by sshcli** [comment]
My test was on 5.0.1
And yours?

**Comment by 810** [comment]
not for that pr, but another. yes.
