### ISSUE TITLE
Name out of margin when Show Avatar on Recent Topics

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4622]
#### Steps to reproduce the issue
1. Show Avatar on Category Index and Recent Topics = YES
2. As a guest create a new topic and insert a name of 35 chars
3. Go to recent topics
#### Expected result

The name should be adjusted to properly fit on its own space
#### Actual result

![out](https://cloud.githubusercontent.com/assets/12942731/19002137/a2c07266-8718-11e6-941c-941568bf28a2.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.11
Database version: 5.6.33

**Comment by 810** [comment]
we have already a issue for this, but we can't fix this, it should be done on joomla.

i thought it will be in 3.7. or 4.0 max characters name

**Comment by sshcli** [comment]
max characters name for guest users is handled here in kunena, joomla is for registered users
if that is the only way to fix (reducing max characters name) then I can make a pr here in kunena project for that.

**Comment by 810** [comment]
it should be in joomla, when you add a space into the name, then its ok. 

There are no issues reporting this.
