### ISSUE TITLE
Size drop menu is blank

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4629]
#### Steps to reproduce the issue

Create a new topic and make a click in the size drop menu
#### Expected result

![sizegood](https://cloud.githubusercontent.com/assets/12942731/19016623/7b5dc892-87ed-11e6-8a0d-99ea620ec277.png)
#### Actual result

![sizebad](https://cloud.githubusercontent.com/assets/12942731/19016622/77447c2e-87ed-11e6-821c-e7c40df4942b.png)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.11
Database version: 5.6.33

**Comment by 810** [comment]
Ah forgot to add rebuild on update.

Go to backend - plugins - click rebuild

**Comment by sshcli** [comment]
Yes, it works after rebuild.

**Comment by 810** [comment]
@xillibit could you execute the function on after update.
