### ISSUE TITLE
Squashed up boxes

### ISSUE THREAD

**Issue by rightinfront** [Kunena/Kunena-Forum#4631]
![problem forum](https://cloud.githubusercontent.com/assets/22566000/19016685/bb590548-8832-11e6-91e5-4ac9bb58aef0.jpg)

squashed up boxes
#### System information (as much as possible)

PHP Version     5.4.45
Web Server  LiteSpeed
WebServer to PHP Interface  litespeed
Joomla! Version     Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
Kunena Version:     4.0.11

Just upgraded

**Comment by 810** [comment]
I just released a 4.0.12 version.

And we don't give any support anymore for K4.x

**Comment by sshcli** [comment]
Kunena 4.0.11 is deprecated. Please update to 5.xx
