### ISSUE TITLE
Date picker not working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4632]
#### Steps to reproduce the issue

example.com/forum/search
#### Expected result

You should be able to select a date
#### Actual result

Not responding when clicked
![datepicker](https://cloud.githubusercontent.com/assets/12942731/19016864/a91ee322-87f4-11e6-9abc-f717a9d1f435.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.11
Database version: 5.6.33
#### Additional comments

There could be others bugs related to this like:
Search for old dates not working

**Comment by 810** [comment]
for me it works:
https://www.kunena.org/forum/search

**Comment by sshcli** [comment]
Try to search something from yesterday,

**Comment by sshcli** [comment]
is responding after clear all cache I'am using.
Still having problems searching for old dates

**Comment by rich20** [comment]
It seems the date picker used different data infos. Or is this only a wrong definition in the language?
![path3338](https://cloud.githubusercontent.com/assets/888847/19017429/46ff153c-8839-11e6-8633-625637f4b99d.png)

**Comment by 810** [comment]
its us based so month/day/year

**Comment by sshcli** [comment]
Again, 
Try to search something from yesterday.
You will see that nothing happens.
After test it, please change label from "unconfirmed" to "bug"
