### ISSUE TITLE
It lacks the delete button in K 5.0.2

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4633]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
the issue is on User Can Delete Own Post option, its seems to be also for mods

**Comment by rich20** [comment]
Yes, confirmed. But also for Admins.

**Comment by xillibit** [comment]
If i understand right, now nobody can see the button delete ?

**Comment by 810** [comment]
no, only if you select other then never option

**Comment by rich20** [comment]
> If i understand right, now nobody can see the button delete ?

Yes, you're rght, but there are still more problems.

**User Can Delete Own Post = Always**
- [x] User
- [x] Admin and Moderator

**User Can Delete Own Post = When no Replies**
- [x] User
- [x] Admin and Moderator

**User Can Delete Own Post = Never**
- [x] User cannot delete
- [ ] Admin and Moderator cannot delete

**User Can Delete Own Post = All, except first message of topic**
- [ ] User can nothing delete
- [ ] Admin and Moderator can delete only the first message
