### ISSUE TITLE
Warning: reset() expects parameter 1 to be array

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4639]
#### Steps to reproduce the issue

Hide Super Users in user list = yes
#### Actual result

Warning: reset() expects parameter 1 to be array, null given in \libraries\kunena\forum\statistics.php on line 298

Warning: reset() expects parameter 1 to be array, null given in libraries\kunena\forum\statistics.php on line 445
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
I think this change :  https://github.com/Kunena/Kunena-Forum/pull/4636 has caused the issue, i will look later to make a fix

**Comment by 810** [comment]
mhh today i can't see the error anymore
