### ISSUE TITLE
CrypsisB3: Default category icon not displayed on Font Awesome

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#4641]
#### Steps to reproduce the issue

Default installation of Joomla 3.6.2, Kunena 5.0.2 and a bs3 joomla template
Now change to Kunena crypsisb3
Change Topic Icons to Font Awesome
Check index page
#### Expected result

Default category icon should be displayed even if it's still set to "glyphicon-folder-open glyphicon-big"
#### Actual result

Conflict between fa and glyphicon ("fa glyphicon glyphicon-folder-open glyphicon-big fa-big")
Icons is not correctly displayed
![capture1](https://cloud.githubusercontent.com/assets/8537297/19032538/9a325ee0-895a-11e6-8ac5-0336fe2ff723.PNG)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version:
Database version:
#### Additional comments

If I use fa default icon i only need to enter: e.g "fa-bars", fa and fa-big are set automatically, if you do not know you're experiencing problems (double classes)

For glyphicon entering "glyphicon-folder-open" only won't work, there you need to write complete syntax ("glyphicon glyphicon-folder-open glyphicon-big")

**Comment by 810** [comment]
i moved it to the topic icon type option, so if you have selected there Bootstrap 3 , then you need only add the glyphicon-folder-open

But yes, if you want to use both, then there will be conflicts.
