### ISSUE TITLE
We need the option "User Edits = When No Replies"

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4649]
#### Steps to reproduce the issue

Problem:
We have the option "User Can Delete Own Post = When No Replies"
But user can nevertheless delete own post via Edit (see here: https://github.com/Kunena/Kunena-Forum/issues/4611. Therefore, we need a way to prevent it.
The option "User Edits = When No Replies" would fix it. 
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
I have fixed it on a different way
