### ISSUE TITLE
User is able to repeat same content several times

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4651]
#### Steps to reproduce the issue
1. Login as registered user
2. Create a new topic
3. Reply the topic with example content and insert an attachment into content
4. Reply the same topic again with the same example content and insert the same attachment into content.
#### Expected result

Attachments inserted into content should not count as text content
#### Actual result

Attachments inserted into content are considered as text content and when you upload the same attachment more than once the filename is renamed.
For that reason the users are able to make several replies using the same text content, they just need to insert an attachment in every reply.
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.1
Php version: 7.0.11
Database version: 5.6.33

**Comment by 810** [comment]
because not all content is the same, so we allow it.
