### ISSUE TITLE
Delete Doesn't Work for Trash Items in the Admin

### ISSUE THREAD

**Issue by eSilverStrike** [Kunena/Kunena-Forum#4684]
#### Steps to reproduce the issue
- Log into the backend
- Go to Components -> Kunena Forum -> Trashbin
- Select all items for delete (I had about 6 items)
- Press Purge items button and then the delete button
- Received error
#### Expected result

Delete all trash items
#### Actual result

500 Internal Server Error
Fatal Error was detected!

The error was detected in the Kunena Component.

Fatal Error: Call to undefined method KunenaForumTopic::totalrecount() in components/com_kunena/controllers/trash.php on line 118

(Items actual did delete though)
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version:5.0.2
Php version:5.6.22
Database version:

**Comment by 810** [comment]
Already fixed on other pr.

**Comment by 810** [comment]
see: https://github.com/Kunena/Kunena-Forum/pull/4638
