### ISSUE TITLE
BBcode: Hide Doesn't Work

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4688]
#### Steps to reproduce the issue

Create a new topic and insert this in the content:
[hide]Example Content[/hide]
#### Expected result

Message should be detected as valid and saved
#### Actual result

Error: Cannot save message: Message body is empty!
#### System information (as much as possible)

Joomla version: 3.6.3-rc1
Kunena version: 5.0.2
Php version: 7.0.9
Database version: 5.6.33

**Comment by 810** [comment]
this message is correct, for guests they see nothing, so we have protected the input for that, so users need to enter something else also, not just bbcode

**Comment by sshcli** [comment]
Please try with more content and you will see it doesn't work even if you are a moderator.
