### ISSUE TITLE
Letters missing in title 

### ISSUE THREAD

**Issue by rightinfront** [Kunena/Kunena-Forum#4694]
The letting is only half there in title, see file

![problem](https://cloud.githubusercontent.com/assets/22566000/19111919/1857f01e-8b13-11e6-949d-f9c2a21f601f.png)

PHP Version     5.6.26 
Joomla! 3.6.2 Stable
Version:     5.0.2

**Comment by 810** [comment]
Hi, this looks more like a joomla template issue.

could you create a topic on k.org
