### ISSUE TITLE
Announcements do not display!

### ISSUE THREAD

**Issue by rotech1** [Kunena/Kunena-Forum#4706]
#### Steps to reproduce the issue

upgrade K4 to K5
#### Expected result

announcements continue to show (FrontEnd Show Announcement=yes, Crypsis features Show Announcements= yes)
#### Actual result

announcements are invisible - admin can still **add or edit** them, but they do not display for any user
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version:5.0.2
Php version: 5.6.26
Database version: 5.5.52

**Comment by 810** [comment]
maybe you collapsed the window, and from K5.0 he is saving the state. 

try:
frontend - kunena - profile - edit - forum settings - clean cache

**Comment by rotech1** [comment]
I have no 'clean cache'  settings available in frontend. We're using latest Community Builder - perhaps there is a 'profile' conflict there?

**Comment by 810** [comment]
ok, then the only way is to remove the kunena cookies on your browser.

**Comment by rotech1** [comment]
But - YES, that is what happened. If you close the Window ( even public access, nobody logged in) then you never see the announcement again in that browser. Not even logged in with different users. Would like to make Announcements persistent again... (and clearing browser cache doesn't restore it!).

If I change to a new browser I see them, but once the box is closed, that browser then **never brings them up again** ( unless I manually enter in a URL like  /announcement/list  or /announcement/id-8

So, cookie clean is not very user-friendly, can we make this a feature request to bring back the V4 "persistent announcements" functionality?? We prefer that the Announcements to stay up until we decide to take them down...

**Comment by 810** [comment]
when there is a new announcement, then the new one will appear again.
If you don't want this feature, then you need to remove this:
https://github.com/Kunena/Kunena-Forum/blob/K5.0/src/components/com_kunena/template/crypsis/assets/js/main.js#L20

**Comment by rotech1** [comment]
OK, will use that as 'workaround' for now... everything else is working OK for me!
