### ISSUE TITLE
suffix will break upload

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4715]
#### Steps to reproduce the issue

https://www.kunena.org/forum/installation-issues/138738-upload-deson-t-work
enable suffix on global configuration
#### Expected result

Attachment is uploaded.
#### Actual result

Upload file failed
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by ggppdk** [comment]
I ll test with a local copy, to see where and why exactly, this is failing for the specific web-site, 
and i will post back here

maybe it is wrong document type being created
https://github.com/joomla/joomla-cms/issues/7459

maybe it is other reason

**Comment by ggppdk** [comment]
I found, it is happening, because a bad .htaccess rule for custom URL rewritting is being triggered,
i fixed the rule and file uploading is now working.
This issue can be closed

**Comment by 810** [comment]
ok thnx
