### ISSUE TITLE
preg_replace() is deprecated in PHP 5.5.x

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4726]
#### Steps to reproduce the issue

You can find the use of preg_replace() here:
/scripts/convertlanguage.php
/scripts/findlanguagestrings.php
/scripts/initlanguage.php
/src/administrator/components/com_kunena/install/install.script.php
/src/administrator/components/com_kunena/install/model.php
/src/administrator/components/com_kunena/install/plugins/plg_kunena_joomla/access.php
/src/administrator/components/com_kunena/install/schema.php
/src/administrator/components/com_kunena/install/sql/updates/php/2.0.0-2011-12-14_aliases.php
/src/administrator/components/com_kunena/models/config.php
/src/administrator/components/com_kunena/models/tools.php
/src/components/com_kunena/layout/search/results.php
/src/components/com_kunena/router.php
/src/components/com_kunena/views/category/view.feed.php
/src/components/com_kunena/views/common/view.html.php
/src/components/com_kunena/views/topic/view.html.php
/src/components/com_kunena/views/topics/view.feed.php
/src/components/com_kunena/views/topics/view.html.php
/src/install.php
/src/libraries/kunena/access.php
/src/libraries/kunena/attachment/attachment.php
/src/libraries/kunena/attachment/helper.php
/src/libraries/kunena/bbcode/bbcode.php
/src/libraries/kunena/controller/display.php
/src/libraries/kunena/error.php
/src/libraries/kunena/external/lessc/lessc.php
/src/libraries/kunena/external/nbbc/nbbc.php
/src/libraries/kunena/form/fields/kunenacategorylist.php
/src/libraries/kunena/forum/forum.php
/src/libraries/kunena/forum/message/message.php
/src/libraries/kunena/forum/topic/topic.php
/src/libraries/kunena/html/parser.php
/src/libraries/kunena/layout/base.php
/src/libraries/kunena/layout/layout.php
/src/libraries/kunena/layout/page.php
/src/libraries/kunena/request/request.php
/src/libraries/kunena/route/route.php
/src/libraries/kunena/template/helper.php
/src/libraries/kunena/template/template.php
/src/libraries/kunena/view.php
/src/plugins/plg_quickicon_kunena/kunena.php
#### Expected result

Should use preg_replace_callback() instead
#### Actual result

preg_replace() is deprecated in PHP 5.5.x
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.11
Database version: 5.6.33

**Comment by xillibit** [comment]
The preg_replace method isn't deprecated, it's just the /e modifier which is deprecated

**Comment by sshcli** [comment]
You are right.
If there's no need to change anything then we can close this issue now
