### ISSUE TITLE
Description corrupted if there's an email within content

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4756]
#### Steps to reproduce the issue
1. Create a new topic and insert an email in the content.
2. Go to recent topics and hover the mouse over the topic title
#### Expected result

Description should be OK.
#### Actual result

Description is corrupted if there's an email within content
![broken](https://cloud.githubusercontent.com/assets/12942731/19252970/e7c6ea7a-8f15-11e6-98ee-bc8a97cb2cb0.png)
#### System information (as much as possible)

Joomla version: 3.6.2 / 3.6.3-rc1
Kunena version: 5.0.2
Php version: 7.0.11 / 7.0.9
Database version: 5.6.33

**Comment by sshcli** [comment]
Problem persist
J3.6.4 + K5.0.3

**Comment by 810** [comment]
For me its working correct
![naamloos](https://cloud.githubusercontent.com/assets/876623/19706659/6268752e-9b13-11e6-9441-f9bdb5f43355.jpg)

**Comment by sshcli** [comment]
Please insert this email in the content (Not in the title)
sasgfg@fsdfg-dsdfgd.com

![fail](https://cloud.githubusercontent.com/assets/12942731/19707449/ac106458-9ae5-11e6-964b-ce3fef16ed6b.png)

**Comment by 810** [comment]
confirmed, now try without - in name behind at

**Comment by sshcli** [comment]
Yes, I'm aware that the problem here is the dash (-)
The question is, can be fix?
