### ISSUE TITLE
Search box unaligned when install language

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4769]
#### Steps to reproduce the issue
1. Create a new topic with a lot of replies (18+ Pages, depends on language text if long or short) 
2. Install kunena language package (Spanish used in this example)
#### Expected result

![good](https://cloud.githubusercontent.com/assets/12942731/19313730/8b96dd40-9065-11e6-9cd5-c745e04216d9.PNG)
#### Actual result

![bad](https://cloud.githubusercontent.com/assets/12942731/19313732/8e720e4a-9065-11e6-8807-4b25fda2fc8d.PNG)
#### System information (as much as possible)

Joomla version: 3.6.3-rc3 and 3.6.2
Kunena version: 5.0.2
Php version: 7.0.9 and 7.0.11
Database version: 5.6.33
#### Additional comments

The problem comes when these words are translated to other languages and use more characters for the translation:

Start
Prev
Next
End

You can see an example here:
http://webpage.gq/welcome-mat/7-sghsgh?start=34

**Comment by 810** [comment]
this is the correct behaviour, you need to have less numbers

**Comment by sshcli** [comment]
I don't want to close the topic only because there are too many replies and they are generating more pages, all the replies are good and valid and I want to keep them.
Also, increasing the number of messages per page will be a general change, not only for that topic.

In the meanwhile, I will do a “half fix” on transifex, but the half fix will be only for Spanish.

If you don't have more comments regarding this, feel free to close this issue.

Regards

**Comment by sshcli** [comment]
upsss
Cannot change on transifex, strings are from Joomla.

**Comment by sshcli** [comment]
Solved only in my website with language override
JLIB_HTML_END
JLIB_HTML_START
JNEXT
JPREV

**Comment by sshcli** [comment]
![good](https://cloud.githubusercontent.com/assets/12942731/19360097/0dde0c34-914b-11e6-98b6-54d9a1cd59b4.PNG)
