### ISSUE TITLE
Save data from quickreply to editor

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Forum#4790]
#### Steps to reproduce the issue

Type text in quickreply
Press button "Go to editor"
#### Expected result

text already typed in quickreply shoud be transfered to the editor input field
#### Actual result

you loose all data
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version:
Database version:
#### Additional comments

There was an pr made for CrypsisB2: #2839
however it's not working in recent versions

**Comment by sshcli** [comment]
Did you try this?
![this](https://cloud.githubusercontent.com/assets/12942731/19486655/42fa897a-952d-11e6-8e6c-3914e47a3ad6.PNG)

**Comment by betteryouthanme** [comment]
Yes activated
