### ISSUE TITLE
FA Icons in kunena menu

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4793]
#### Steps to reproduce the issue

Not a bug.
Feature/Enhance request
#### Expected result

![yes](https://cloud.githubusercontent.com/assets/12942731/19535935/cbdfc2d8-9617-11e6-81b8-b2f56723075d.PNG)
#### Actual result

![no](https://cloud.githubusercontent.com/assets/12942731/19535939/cfd91434-9617-11e6-916b-62233f690048.PNG)
#### System information (as much as possible)

Joomla version: 3.6.3
Kunena version: 5.0.2
Php version: 7.0.11
Database version: 5.6.33

**Comment by 810** [comment]
on the menu item, add fa fa-user on the "Link CSS Style" option
