### ISSUE TITLE
Recurring PHP Notices in error.log

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#4795]
#### Expected result

No warnings in error.log
#### Actual result

I found lot of recurring notices in error.log:

> PHP Notice: Undefined property: KunenaViewTopics::$caching in /public_html/components/com_kunena/views/topics/view.feed.php on line 36
#### System information (as much as possible)

Joomla version: 3.6.2
Kunena version: 5.0.2
Php version: 7.0.12
Database version: 5.5.50-MariaDB

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/pull/4783

**Comment by Sulpher** [comment]
Ok, good to know it's already fixed.
