### ISSUE TITLE
Subscription lost when convert a post into a topic

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4802]
#### Steps to reproduce the issue
1. user1 create topic1  (Subscribe=Yes)
2. user2 reply topic1 (Subscribe=Yes)
3. Moderator move reply from user2 to a new topic and change the name to topic2
#### Expected result

Option 1. Keep subscription from topic1 and create subscription for topic2
Option 2. Delete subscription from topic1 and create subscription for topic2
#### Actual result

No subscription is created for topic2.
user2 is losing all the notification from its own topic, even when "Select subscription as default = YES"
#### System information (as much as possible)

Joomla version: 3.6.3
Kunena version: pkg_kunena_v5.0.3-DEV_2016-10-20
Php version: 7.0.9
Database version: 5.6.33

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/issues/3861 there is already a issue for it.
