### ISSUE TITLE
View in a web browser not working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4803]
#### Steps to reproduce the issue
1. Go to your Microsoft Outlook and look for any email from kunena
2. Click the option: If there are problems with how this message is displayed, click here to view it in a web browser 
#### Expected result

You should see the email content in your browser without any problem.

![notification](https://cloud.githubusercontent.com/assets/12942731/19578747/1a1242c2-96eb-11e6-8987-0c731f730d66.PNG)
#### Actual result

A blank page will be opened with no content
#### System information (as much as possible)

Joomla version: 3.6.3 
Kunena version: 5.0.2 and 5.0.3-dev
Php version: 7.0.9 and 7.0.12
Database version: 5.6.33
#### Additional comments

Remove this option or fix it

**Comment by joomlabid** [comment]
Yes I have same problem page will be opened with big blue image that from header!

**Comment by 810** [comment]
From now on, you can leave the option blank. Then the image will not be loaded.
