### ISSUE TITLE
Emoticons button doesn't fit 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4806]
#### Steps to reproduce the issue
1. Enable all buttons in Templates->Crypsis->BBcode
2. Go to example.com/forum/newtopic
#### Expected result

Emoticons button should fit in the same line as the rest of the buttons
#### Actual result

Emoticons button doesn't fit in the same line as the rest of the buttons

![fit](https://cloud.githubusercontent.com/assets/12942731/19600363/ab6d0676-9772-11e6-88f7-7e8088c8b953.PNG)
#### System information (as much as possible)

Joomla version: 3.6.3
Kunena version: 5.0.3-DEV 2016-10-21 and 5.0.2
Php version: 7.0.9 and 7.0.12
Database version: 5.6.33

**Comment by 810** [comment]
This is because the width from you joomla template.
You need to adjust to fix.

**Comment by sshcli** [comment]
Protostar, default value
Fluid Layout = Static
