### ISSUE TITLE
rss mode-topics not working

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4840]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
What is the issue with the mode-topics ?

**Comment by 810** [comment]
when you click on the rss on a category then i don't see any message. on the index page

**Comment by 810** [comment]
example:

url: https://www.kunena.org/forum/topics/mode-topics/catid-253?format=feed
topics showed on rss: 1

settings:
RSS Feed type = Recent topics
RSS History (timelimit) = 1 month
RSS Limit = 100
Include Categories = 
Exclude Categories = 
Limit Number of Characters Per Item = all
Caching Interval = 15

**Comment by sshcli** [comment]
I can't reproduce this.
I think this bug does not exist anymore.

Please test it again

**Comment by 810** [comment]
check https://www.kunena.org/forum/installation-issues

there you see that there are more topics within the month
