### ISSUE TITLE
Can't see post author and/or content in unapproved view

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4848]
#### Steps to reproduce the issue

1.Create category1 and set as moderated (Review=ON)
2. user1 create topic1 in category1
3. Moderator approve topic1
3. user2 reply topic1 (Let's call it reply1)
4. Go to unapproved view (index.php?option=com_kunena&view=topics&layout=posts&mode=unapproved&userid=*)
#### Expected result

You should be able to see user2 or reply1 before approve it.
#### Actual result

Can't see user2 or reply1
#### System information (as much as possible)

Joomla version: 3.6.3
Kunena version: 5.0.3-DEV 2016-10-22
Php version: 7.0.9
Database version: 5.6.33

**Comment by 810** [comment]
I can see the topic who have unapproved messages.

On the view you see the topic details, and the last message that is approved.

You can't see any info from the new message

**Comment by sshcli** [comment]
> You can't see any info from the new message

Exactly, this is what I'm reporting. Can't see the author or content of the new message.

**Comment by sshcli** [comment]
After update to 5.0.3
The target URLs are wrong

**Comment by 810** [comment]
its correct, it load the unread item, or first message.

(unaproved isn't showing direct, because its not aproved)

**Comment by sshcli** [comment]
The behavior we have now in 5.0.3 it's an undo for this fix:
https://github.com/Kunena/Kunena-Forum/issues/4249

So now, it's more difficult again
