### ISSUE TITLE
Descriptions are missing in Profile Information

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4879]
#### Steps to reproduce the issue

Edit Profile Information (example.com/forum/profile/edit/0-user)
#### Expected result

You should be able to see the description for every field.
#### Actual result

You can't see any description in the frontend but if you view source code your will notice that all the descriptions are there.
#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.3
Php version: 7.0.12
Database version: 5.6.33

**Comment by 810** [comment]
i can;t see the description
