### ISSUE TITLE
SEO: rel=canonical target contains a noindex

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4892]
#### Steps to reproduce the issue
1. Go to http://webpage.gq/welcome-mat/1-welcome-to-kunena
2. Right click-> View source code
#### Expected result

You should remove the **rel="canonical"** to **/user/894-test** because the target page contains a noindex robots meta tag.
#### Actual result

There is a **rel="canonical"** for the page **/user/894-test**
#### System information (as much as possible)

Joomla version:  3.6.4
Kunena version: 5.0.4-dev 2016-10-29
Php version: 7.0.12
Database version: 5.6.33

**Comment by 810** [comment]
canonical is only for the view itself, its not looking on targets.
