### ISSUE TITLE
Editor tooltips - Keyboard shortcut opens browser commands

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#4894]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/139020-text-sizing-and-colour-selection-not-showing-drop-down-as-it-does-here
1. Click on reply
2. Place the cursor in the text field
3. Press Ctrl+S or Ctrl+T
![bildschirmfoto vom 2016-10-31 18-27-02](https://cloud.githubusercontent.com/assets/888847/19865133/40dcf8b2-9f9b-11e6-87ae-61a0bb29a88e.png)

#### Expected result

It should be entered the code tags

#### Actual result

Ctrl+S opens a browser modal
Ctrl+T opens a new browser tab

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.0  - 5.0.3 - 5.0.4-dev
Php version:
Database version:

#### Additional comments

Tested with Chromium, Firefox and Opera.
The tooltips for Strikethrough, Subscript and Superscript are at all Ctrl+T

Maybe we should remove the tootips?

**Comment by 810** [comment]
closing this issue for the new issue

**Comment by sshcli** [comment]
New issue is: https://github.com/Kunena/Kunena-Forum/issues/4895
