### ISSUE TITLE
Start default icons

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#4908]
#### Steps to reproduce the issue

Started on the dropdown menu on profilebox. (location,gender)

@betteryouthanme could you help me with transferring the b2 icons to the old icons.
see: https://github.com/Kunena/Kunena-Forum/pull/4907/files
#### Expected result

Old icons from K4.x (assets/iconsets/profile/default/default.png)

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by betteryouthanme** [comment]
@810 which icons else you want to replace?

**Comment by 810** [comment]
icons on the rows, like my posts (flag icon), favorite (star), poll

**Comment by sshcli** [comment]
Only to let you know this icon is also wrong:
![icon](https://cloud.githubusercontent.com/assets/12942731/19928571/564a793c-a0d5-11e6-831d-dc06e5327732.PNG)

**Comment by 810** [comment]
ps i have add a new type: image, because else the update will break.
