### ISSUE TITLE
Cannot save topic: Subject is empty when you need to select from categorylist

### ISSUE THREAD

**Issue by joomlagate** [Kunena/Kunena-Forum#4923]
Today I went to kunena.org forum to post a new topic, after I filled both "subject" and "message" for my new topic, I clicked "submit" button, but the forum returned with following warning:

> Error
> Cannot save topic: Subject is empty!

Acturally  I SURELY had filled the subject box.

I tried again, but got the same result. 

I switched to another browser, but got the same result again!

Something is wrong with your official forum. Please fix it.

Thank you.

**Comment by 810** [comment]
ok, fixed. 

There is a new bug. Need to check it.
