### ISSUE TITLE
Start subject/message with capital letter

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4934]
#### Steps to reproduce the issue
create a new topic

#### Expected result
By default, every paragraph/sentence must start with a capital letter. (Subject and Message)

![goodcap](https://cloud.githubusercontent.com/assets/12942731/20084413/7ee5670a-a538-11e6-8f55-a8a08045e990.PNG)

#### Actual result
You must insert the capital letter manually because the editor is not performing this task.

![badcap](https://cloud.githubusercontent.com/assets/12942731/20084411/7b2d6586-a538-11e6-9060-e33852f55c22.PNG)

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev-7Nov16
Php version: 7.0.12
Database version: 5.6.33

**Comment by 810** [comment]
then you need:

```
.input {
    text-transform: lowercase;
}


.input:first-letter {
    text-transform: uppercase;
}
```

**Comment by sshcli** [comment]
This is a very low enhance suggestion (grammar).
Please feel free to close this issue if this is not aligned/targeted to kunena goals or priorities.
