### ISSUE TITLE
Missing Strings on Edit Profile Information

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4936]
#### Steps to reproduce the issue
Go to Edit Profile Information

#### Expected result
All languages strings should be OK

#### Actual result
These strings are missing:
COM_KUNENA_MYPROFILE_INSTAGRAM_DESC
COM_KUNENA_MYPROFILE_GOOGLE_DESC
COM_KUNENA_MYPROFILE_MICROSOFT_DESC
COM_KUNENA_MYPROFILE_QQ_DESC
COM_KUNENA_MYPROFILE_QZONE_DESC
COM_KUNENA_MYPROFILE_WEIBO_DESC
COM_KUNENA_MYPROFILE_WEBCHAT_DESC
COM_KUNENA_MYPROFILE_APPLE_DESC
COM_KUNENA_MYPROFILE_VK_DESC
COM_KUNENA_MYPROFILE_TELEGRAM_DESC

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev-7Nov16
Php version: 7.0.12
Database version: 5.6.34

**Comment by 810** [comment]
on the information tab, there is no desc at all.

I don't think we need it.

**Comment by sshcli** [comment]
Hover the mouse over the field and you will see it
![desc](https://cloud.githubusercontent.com/assets/12942731/20218633/eb1290d6-a7fb-11e6-969d-539bc5a47d1d.png)
