### ISSUE TITLE
BBCODE to EasySocial on Reply Posts Not Posting correctly

### ISSUE THREAD

**Issue by EverStaR1** [Kunena/Kunena-Forum#4938]
#### Steps to reproduce the issue
Create a post in Kunena 5.03 with system details below.
Add images
Submit

Reply to message above
Add images via either attachment or BBcode from Flikr
Submit

Check Easy Social Stream 2.02 and 2.03 and first original post displays images, the reply does not in the stream.

#### Expected result
All image posts in both original post and replies should display in stream feed.

#### Actual result
Only images in the original post display

#### System information (as much as possible)

Joomla version: 3.64
Kunena version: 5.03 and 4.x
Php version: 5.6
Database version: 5.5.49-cll-lve
EasySocial 2.03

#### Additional comments

Occurs on Windows Chrome, Firefox and IE
Occurs on iPad Chrome, safari and other browsers

Setting	Value
 
PHP Built On	Linux  2.6.32-673.26.1.lve1.4.15.el6.x86_64 #1 SMP Sun Jul 17 09:01:31 EDT 2016 x86_64
Database Version	5.5.49-cll-lve
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.25
Web Server	Apache/2.4.23
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by 810** [comment]
Could you try the nightly build, on the download page on kunena.org
Or try the commit above

**Comment by EverStaR1** [comment]
Tried 5.04 Nightly, did not resolve the issues, see stream on Nikkorglass.com

This is the result in stream:
Test 2 5.04 [attachment=1451]YellowStone-0665.jpg[/attachment]

Thanks!
Mark

**Comment by 810** [comment]
i have contacted the easysoical team, and they have fixed it. Will be in the next easysocial update.
