### ISSUE TITLE
Crypsisb3 double main menu and double login menu

### ISSUE THREAD

**Issue by shoulders** [Kunena/Kunena-Forum#4940]
#### Steps to reproduce the issue

When playing around with the templates I noticed this. Most of my settings are default and I did upgrade from Kunena 5.0.2 but I do not know if the issue was present before the upgrade.

Then just go to the Kunena Hompage, index.php?option=com_kunena&view=home&defaultmenu=999

**Double Menus**
![double-menu-1](https://cloud.githubusercontent.com/assets/319997/20210589/459313f0-a7f2-11e6-9b7e-8c8d7ca41086.png)

**Sub Main Menu**
![double-menu-2](https://cloud.githubusercontent.com/assets/319997/20210593/48ea8f10-a7f2-11e6-887a-5ce216a59f14.png)

#### Expected result

single iteration of the menus

#### Actual result

Double menus

#### System information (as much as possible)

Joomla version: 3.5.1
Kunena version: 5.0.3
Php version: 5.5.38 
Database version: MySQL 5.5.5-10.1.18-MariaDB 
Template: Gantry Helium 5.6.7

#### Additional comments

Probably a simple template issue.

**Comment by 810** [comment]
if you see the 2 menu's. then you don't have the responsive bootstrap css loaded.
Or you have the wrong kunena template enable, i see you have helium, then set cryspsis as default.

**Comment by shoulders** [comment]
I have enabled the cryspsis template and I do not have the issue. I was not 100% sure whether this was an issue or not. thanks for the update. (I will not be the only one, lol)
