### ISSUE TITLE
Can't update Kunena: "The requested URL /updater/pkg_kunena_v4.0.12_2016-06-05.zip was not found on this server"

### ISSUE THREAD

**Issue by ChefMC** [Kunena/Kunena-Forum#4976]
Can't update Kunena on 2.5.28 (before updating to 3.x), it gives me next error:

![image](https://cloud.githubusercontent.com/assets/3519015/20240980/4cfb4288-a938-11e6-9789-6441bcd597e4.png)

**Comment by 810** [comment]
fixed
