### ISSUE TITLE
Error after updating Kunena to 4.0.12 on Joomla 2.5.28

### ISSUE THREAD

**Issue by ChefMC** [Kunena/Kunena-Forum#4978]
![image](https://cloud.githubusercontent.com/assets/3519015/20243821/d0aab88a-a978-11e6-979d-54d72471ca56.png)

![image](https://cloud.githubusercontent.com/assets/3519015/20243813/ac1b9ca0-a978-11e6-9728-645eb8b8123e.png)

**Comment by 810** [comment]
J2.5 is not supported, but you see the issue is on a other plugin noextlinks. disable that plugin
