### ISSUE TITLE
Search by username not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4982]
#### Steps to reproduce the issue
1. Make a new installation of kunena and don't delete the example topic "Welcome to Kunena!"
2. Go to example.com/forum/search and insert only the author name of the topic "Welcome to Kunena!", leave everything else as is.

#### Expected result
You should see the results

#### Actual result
No results. You get this message:
Your search did not match any topics.

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-DEV 2016-11-14
Php version: 7.0.9
Database version: 56.34

**Comment by 810** [comment]
you need to remove the space after the username

**Comment by sshcli** [comment]
Problem persist in 5.0.4
