### ISSUE TITLE
Load Bootstrap css / Icomoon icons not available for crypsisb3 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4986]
#### Steps to reproduce the issue
components-> Kunena forum->Templates->Crypsisb3->Basic settings

#### Expected result
Load Bootstrap css and Load Icomoon icons should be available also for crypsisb3

#### Actual result
Load Bootstrap css and Load Icomoon icons are not available for crypsisb3

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev
Php version: 7.0.12
Database version: MySQL 5.6.34

**Comment by 810** [comment]
Because joomla doesn't have bootstrap 3 in the core. And icomoon is only for B2.

**Comment by sshcli** [comment]
OK, understood.
