### ISSUE TITLE
Location not linkeable in more drop menu

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4991]
#### Steps to reproduce the issue
Go to your profile and insert a location then go to the more drop menu 

#### Expected result
When click the location icon located in more drop menu , it should open a new window with the google map, just like it does in the profile view

![locationlink](https://cloud.githubusercontent.com/assets/12942731/20289233/1b72dd7a-aaaf-11e6-86cd-7ab96dfdaf4a.PNG)

#### Actual result
The location icon located in more drop menu is not linkeable
![location](https://cloud.githubusercontent.com/assets/12942731/20289237/22763068-aaaf-11e6-83aa-ef0976838ad8.PNG)

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev
Php version: 7.0.12
Database version: MySQL 5.6.34

**Comment by 810** [comment]
it should only inform the user, should not be clickable.
