### ISSUE TITLE
Missing icons when Topic Icons = Images - Legacy

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4996]
#### Steps to reproduce the issue
Templates->Crypsis->Features->Topic Icons->Images - Legacy

#### Expected result
All buttons should have icons

#### Actual result
Icons are missing when Topic Icons = Images - Legacy
![icons1](https://cloud.githubusercontent.com/assets/12942731/20291920/2304aa62-aac0-11e6-8564-18618ea3f0f1.PNG)
![icons2](https://cloud.githubusercontent.com/assets/12942731/20291919/230354dc-aac0-11e6-9c4f-73b13f508fe0.PNG)

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev 2016-11-15
Php version: 7.0.12
Database version: MySQL 5.6.34

**Comment by 810** [comment]
when images - lecacy is set, then there should be no icon at all.

**Comment by sshcli** [comment]
Ok,
I get confused because the quick reply button have an icon.

**Comment by 810** [comment]
need to check why, also need to check if we have some icons on the sprite image

**Comment by sshcli** [comment]
The icon for quickreply is not there anymore.
For me, you can close this issue right now as solved, unless you have something else in your mind.

**Comment by 810** [comment]
I have added css classes for all actions, if template makers want to use images, then they can use the classes from now on.
