### ISSUE TITLE
Some socials are not working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#4997]
#### Steps to reproduce the issue
1. Go to Edit Profile Information and fill out all fields
2. Go to example.com/forum/profile/001-user and try to click all socials icons

#### Expected result
All socials should work

#### Actual result
Socials marked with a red line are not working (Not responding to click)
![socials](https://cloud.githubusercontent.com/assets/12942731/20292190/02730990-aac2-11e6-894b-78a98cc14942.PNG)

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev 2016-11-15
Php version: 7.0.12
Database version: MySQL 5.6.34

**Comment by 810** [comment]
they are unlinked because they have not a public social url.

only google plus, other chines/vk/telegram i don't know.
