### ISSUE TITLE
Last subcategory wrong total topics on top

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5001]
#### Steps to reproduce the issue
Create a category with subcategories and create a few topics within it 

#### Expected result
The total amount of topics indicated at the top should match with the actual topics

#### Actual result
The total amount of topics indicated at the top is wrong

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev-15nov16
Php version: 7.0.12
Database version: MySQL 5.6.34

**Comment by 810** [comment]
i just tried it, for me its ok. Try to recount categories, then try again

**Comment by sshcli** [comment]
Yes, you are right.
Problem is solved after recount statistics.
Thanks

I'm closing this as solved
