### ISSUE TITLE
Search user

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5004]
#### Steps to reproduce the issue

search - by user

#### Expected result

no errors

#### Actual result

errors on backend - kunena -logs

<pre>{ &quot;type&quot;: 1, &quot;message&quot;: &quot;Call to a member function from() on string&quot;, &quot;file&quot;: &quot;/home/www/public_html/components/com_kunena/models/user.php&quot;, &quot;line&quot;: 88 }</pre>

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
temp fix:
reverted the change: https://github.com/Kunena/Kunena-Forum/pull/5005

**Comment by xillibit** [comment]
i will try to look at it
