### ISSUE TITLE
impossible create subjet (default config)

### ISSUE THREAD

**Issue by alexonbalangue** [Kunena/Kunena-Forum#5007]
#### Steps to reproduce the issue
Without config the component in backend, on frontend i trying but have error 401 when click new subjet

#### Expected result
Impossible to create subjet

#### Actual result
error 401

#### System information (as much as possible)

Joomla version:  6.x lastest
Kunena version: 5.0.3
Php version: 7.0.10
Database version:

**Comment by 810** [comment]
already fixed, try the nightly build

**Comment by alexonbalangue** [comment]
hey i just saw now bad config
