### ISSUE TITLE
Insert all not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5008]
#### Steps to reproduce the issue
1. Go to example.com/forum/newtopic
2. Attachements->Add files (insert any supported file)
3. Click the "Insert all" button
4. Click the "Remove all" button
5. Delete the tag inserted in message content
6. Add another file
7. Click the "Insert all" button again

#### Expected result
The "Insert all" button should be blue as the initial state

#### Actual result
The "Insert all" button now says "In message" even when there's nothing there

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev-16nov16
Php version: 7.0.13
Database version: MySQL 5.6.34

#### Additional comments
Also, when insert file by using the "Insert" button, the "Insert all" button should change to "In message"
![capture](https://cloud.githubusercontent.com/assets/12942731/20347602/53cf00ac-abd8-11e6-9047-484ce7f17015.PNG)

**Comment by rich20** [comment]
> Add another file
> Click the "Insert all" button again"

Please try after step 6 the Submit button. It uploads all attachments along with the files which you have removed before. Likely it is related to this bug. https://github.com/Kunena/Kunena-Forum/issues/4452 The fact is that the removed attachments continue to exist.
