### ISSUE TITLE
Improve emoji support

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5009]
#### Actual result
1. Illegal mix of collations.
2. Can't use it in categories

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by 810** [comment]
can't reproduce:
![rrr](https://cloud.githubusercontent.com/assets/876623/20362481/0e806f22-ac3c-11e6-9555-4f189aedbbec.png)

**Comment by sshcli** [comment]
Please try with other emoji.
This for example: 😉

![emoji](https://cloud.githubusercontent.com/assets/12942731/20363477/af7f622e-ac15-11e6-912e-86004b886ce7.PNG)
![noemoji](https://cloud.githubusercontent.com/assets/12942731/20363516/dafb0e30-ac15-11e6-8bc4-aa3d74497f7c.PNG)

**Comment by 810** [comment]
again, no issue

**Comment by sshcli** [comment]
Ok, thanks for give me a clue.
The problem has been solved by changing all tables to utf8mb4_general_ci
