### ISSUE TITLE
Show sub-category image not working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5010]
#### Steps to reproduce the issue
1. Make a new installation of kunena 5.0.4-dev 17Nov16 + J.3.7.0-dev
2. Create sub categories in kunena
3. Configuration->Frontend->Show Sub-Category Image = Yes

#### Expected result
You should see Sub-Category Image

#### Actual result
Unable to see Sub-Category Image 

#### System information (as much as possible)

Joomla version: 3.7.0-dev
Kunena version: 5.0.4-dev 17Nov16
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by rich20** [comment]
Conversely, it does not work. You can't disable it.
After a new installation, you need to define the type of symbols. "Crypsis -> Basic Settings -> Default category icon".
Example:
**icon-folder**  for bootstrap2 icons
**glyphicon-folder** for bootstrap3 icons
**fa-folder** for FontAwesome icons

**Comment by sshcli** [comment]
@rich20 
Exactly, You can't disable it.
So, definitely this is a little bug
