### ISSUE TITLE
Postion Kunena_logout not working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5023]
#### Steps to reproduce the issue
1. Show dropdown content = NO
2. Try to use a module in the position Kunena_logout

#### Expected result
It should work

#### Actual result
Not working

#### System information (as much as possible)

Joomla version: 3.7.0-dev
Kunena version: 5.0.4-dev 19Nov16
Php version: 7.0.9
Database version: MySQL 5.6.34

**Comment by 810** [comment]
thats why we have now kunena_logout_bottom

**Comment by sshcli** [comment]
Sorry, didn't notice the change.

I'm closing this issue now.
