### ISSUE TITLE
Subcategories are not aligned in the right way

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5032]
#### Steps to reproduce the issue
Create a category and then add several subcategories into it

#### Expected result
Subcategories should keep a good appearance, must be well aligned.
![categorygood](https://cloud.githubusercontent.com/assets/12942731/20539072/2c611a40-b0ca-11e6-992b-6ab96bad0766.PNG)

#### Actual result
Subcategories looks a little messy and disordered.

![categoriesbad](https://cloud.githubusercontent.com/assets/12942731/20539067/2897da8e-b0ca-11e6-896a-69beb9ceea6c.PNG)

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by 810** [comment]
This can be better a own custom class:

````
.subcategories li {
    width: 33%;
}
````

**Comment by sshcli** [comment]
OK, thanks
