### ISSUE TITLE
crypsisb3: Update bootstrap css

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5039]
#### Expected result
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

#### Actual result
http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4-dev
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by 810** [comment]
I haven't updated the icons cdn, because there is no update for icons fon cdn.

**Comment by sshcli** [comment]
Ok, 
In that case, 
Let's create an issue and/or pull request for this when needed.
Let's close this as N/A (Not Applicable)
