### ISSUE TITLE
Can't search all deleted posts

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5080]
#### Steps to reproduce the issue
1. Login as moderator or admin
2. Go to: example.com/forum/search
3. Advanced Search->Search by Keyword->Keywords = *
4. Search Options->Show = Deleted Posts

#### Expected result
You should see all deleted items

#### Actual result
At least 3 characters are required, so, there is no way to find all deleted posts with a single search.

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4.1
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by 810** [comment]
The search shouldn't check for all deleted topics. You have a menu item for that.
