### ISSUE TITLE
Wrong sticky symbols

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5083]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support-archive/139246-sticky-message-icon-issue#182030
There are declared wrong symbols in the xml files

#### Expected result

Should be changed in both files system- and topicicons.xml to:

b2="pin" b3="pushpin" fa="map-pin"

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
This issue can be closed as solved
