### ISSUE TITLE
Page generation fails in thread with deleted posts

### ISSUE THREAD

**Issue by brianmcardle** [Kunena/Kunena-Forum#5088]
#### Steps to reproduce the issue
Create a new thread, post 23 posts in it (including initial post). Delete 3 posts. The thread now has 20 posts, and therefore only one page for regular users (who can't see the deleted posts), assuming default 20 posts per page is set.

Post again in the same thread.

#### Expected result
The post is visible on a new page to regular users.

#### Actual result
No new page is created, meaning the post is invisible to regular users. Moderators who can see deleted posts can see the new page.

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 4.0.12
Php version: 5.5.38
Database version: 5.6.33-cll-lve

#### Additional comments
As a workaround, another post by a moderator in the same thread will trigger the new page generation.

**Comment by xillibit** [comment]
Hello,

We don't support Kunena 4.0 series, so please update your Kunena version to 5.0.4.1
