### ISSUE TITLE
Improve page title to widget login

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5090]
#### Steps to reproduce the issue
1. Create a new language override for COM_KUNENA_LOGIN_FORUM and insert html code in the content
2. Menu item Kunena Forum » Create Topic = Public
3. Go to example.com/forum/newtopic

#### Expected result
You should use the same page title as in the current view
or
create a new language string just for the page title
or
something else you consider a better solution  

#### Actual result
Actual page title is:
Only community members can participate in this forum. You must register or log in to 

If you want to use language override to change that message, you can do it, but...
You can't use html because the html code will be visible in the page title

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4.1
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by 810** [comment]
Joomla has protected the title, you can't use html in the titles.
