### ISSUE TITLE
View All Deleted Posts not Working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5091]
#### Steps to reproduce the issue
1. Make sure you have some deleted messages / posts in your forum (Not topics)
2. Create new menu item: Kunena Forum » Recent Posts

##Details Tab
3. Select View = Deleted posts
4. UserId = *
5. Access = Especial

##Main Settings Tab
6. Category Filter in Recent Topics = Show Categories
7. Category List in Recent Topics = All categories
8. Deleted Topics = Show
9. Recent Topics Time = All

#### Expected result
You should see all deleted messages

#### Actual result
Can't see any deleted message

#### System information (as much as possible)

Joomla version: 3.6.4
Kunena version: 5.0.4.1
Php version: 7.0.13
Database version: MySQL 5.6.34

**Comment by sshcli** [comment]
If the topic has replies
and
the author of the topic delete the first message (its own message)

As a moderator, you will not able to see that deleted message via menu item, it's only visible via backend.

**Comment by rich20** [comment]
In principle you can see only your own deleted messages.

Also tested with Joomla 3.7-dev and K 5.0.5-dev

**Comment by sshcli** [comment]
I think the bug is in the UserID field
