### ISSUE TITLE
It lacks the option @import 'custom.less'; in the crypsis.less

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5102]
#### Steps to reproduce the issue

Without this import you need "!important" for the most changes in you custom.less.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
we can't add custom.less, else on every update it will be cleared.

**Comment by rich20** [comment]
hm.. If you use the custom.less so you must to add the line "import custom.less" in the crypsis.less. You must to add this line after all updates again.

**Comment by 810** [comment]
if i add it on the crypsis.less, then you will get a warning missing file, on clean sites.

mhh maybe i need to add a custom.less on update if the file isn't there.
