### ISSUE TITLE
Fatal Error on  logs

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5104]
#### Steps to reproduce the issue
<pre>{ &quot;type&quot;: 1, &quot;message&quot;: &quot;Call to a member function from() on string&quot;, &quot;file&quot;: &quot;/home/kunena/public_html/components/com_kunena/models/user.php&quot;, &quot;line&quot;: 88 }</pre>

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Is-it a recent entry in log manager or an old one ? When i look on file /components/com_kunena/models/user.php at line 88 it shouldn't throw this error now
