### ISSUE TITLE
Untranslated word: 404 Not Found

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5107]
#### Actual result
![404](https://cloud.githubusercontent.com/assets/12942731/21228866/d843c6d0-c2b5-11e6-8f66-085d9a33354b.PNG)

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.4.1
Php version: 7.0.14
Database version: MySQL 5.6.34

**Comment by 810** [comment]
these are standard error codes, we can't translate them
