### ISSUE TITLE
Untranslated word: 403 Forbidden

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5108]
#### Actual result
![403](https://cloud.githubusercontent.com/assets/12942731/21229087/beb4ad14-c2b6-11e6-9295-f720bdcb298f.PNG)

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.4.1
Php version: 7.0.14
Database version: MySQL 5.6.34

**Comment by 810** [comment]
these are standard error codes, we can't translate them
