### ISSUE TITLE
Allow Guests to see Userlist - Wrong value in the configuration report

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5115]
#### Steps to reproduce the issue

Choose Allow Guests to see Userlist = Yes (configuration - security)
It shows userlist_allowed":"0" but Yes should be value 1

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
The issue isn't on report configuration but in the select of config, because if you set Allow Guests to see Userlist = Yes, ti's defined on 0 and llow Guests to see Userlist = No it's defined on 1
