### ISSUE TITLE
Kunena Forum and easysocial - wrong Avatars/Links 

### ISSUE THREAD

**Issue by siaolong** [Kunena/Kunena-Forum#5117]
Hello!

Recently updated Kunena to 5.0.4.1 and the avatars and user profiles link plugin for Easysocial no longer works.
Updated both the ES Application and ES-Kunena Plugin to 2.0.15 
Issue remains and Kunena is displaying user's email although it is set to hide. 

#### System information (as much as possible)

Joomla version: 3 6 5
Kunena version: 5 0 4 1
Php version:
Database version:

#### Additional comments

thanks!

**Comment by 810** [comment]
please contact easysocial. We only copy the code from their plugin.
