### ISSUE TITLE
Hide file attachment info on moderator emails

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5118]
#### Steps to reproduce the issue
1. Configuration->security settings->E-mail Moderators = All new posts
2. As a "Registered" user, reply any topic and insert an attachment into the message content .

#### Expected result
The attachment should be hidden on emails
or
Fix the language string problem
or 
Another solution

#### Actual result
The notification email (moderator only) is displaying a string:
![bad](https://cloud.githubusercontent.com/assets/12942731/21338523/4c04e582-c64d-11e6-93e2-08d5e3858680.PNG)

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0
Kunena version: 5.0.4.1 and 5.0.5-DEV
Php version: 7.0.14 and 7.0.9
Database version: MySQL 5.6.34

**Comment by sshcli** [comment]
@810 @xillibit you have fixed this before, but I think the fix was only for default subscription emails, not moderators.

**Comment by xillibit** [comment]
I'am remember that i have done something, but you are right it wasn't done for moderators too, i will look at it

**Comment by sshcli** [comment]
@xillibit I think this was the solution: 
https://github.com/Kunena/Kunena-Forum/pull/4387/files

**Comment by 810** [comment]
Leave a comment
