### ISSUE TITLE
StopForumSpam partially removed

### ISSUE THREAD

**Issue by demis-palma** [Kunena/Kunena-Forum#5127]
It seems that this PR https://github.com/Kunena/Kunena-Forum/pull/3219 has removed the integration with StopForumSpam.
However, pieces of PHP code and a few language strings related to StopForumSpam are still present in the current version of Kunena, so it raises a lot of doubts.
Is it planned to restore the support for StopForumSpam in future?

Unfortunately, the [changelog](https://www.kunena.org/bugs/changelog) does not help.

**Comment by 810** [comment]
The feature "was only sending data to the StopForumSpam " not protecting stuff. So we have removed it.
Until there is a solution to prevent spam, then we maybe want to add it again.

**Comment by demis-palma** [comment]
There are basically two kinds of stopforumspam users:

1. those who benefit from the database, and
2. those who feed the database, and **make things possible**.

Technically speaking, **it's not** up to Kunena to protect Joomla users registrations from spammers. Third party plugins already exists for that, and they works very good. They query the stopforumspam database to offer the protection that you mentioned above, to our Joomla/Kunena based websites.
Of course this is possible **only if** other people have already reported the spammer, perhaps using and outdated version of Kunena, since the latest doesn't implement spam reports. :rage:

It makes perfectly sense for us (as webmasters) to report our spammers to the spam database. It doesn't cost us money, but it helps a lot. Of course someone else will benefit from our specific submission, but this is how it works. On the other hand, when we query the spam database **we benefit from someone else's specific submission**.

Ethically speaking, the decision to remove the submission feature just because currently Kunena does not receive anything in return, is at least questionable. Specially for an open source project.
Not to mention that our Joomla/Kunena based websites **do** receive protection by StopForumSpam, as explained above.
With this decision, **all the Kunena administrators have lost an effective tool to fight spam**, by submitting abuses to the spam database.

If at least the ban action raised an "OnUserBan" event, I could write a stopforumspam submission plugin, to decouple this piece of code from the main Kunena component.

**Comment by xillibit** [comment]
I can re-introduce the code, if you write a plugin which check onlogin if the user is in stopforumspam database it could be cool

**Comment by xillibit** [comment]
@demis-palma : i have done the PR to re-introduce the code  removed,  so tell me if it's enough to work on your plugin ?
