### ISSUE TITLE
Poll Modal buttons : Add and Close button have the same function

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5128]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/139434-polls-problem
I've tested it and confirm this issue.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by rich20** [comment]
The Clear button works but the Close button is now unnecessary. He has still the same function as the Add button.

**Comment by 810** [comment]
Add = adding data/updating
close = cancel changes
Clear = remove input data

**Comment by rich20** [comment]
> close = cancel changes

Cancel does not work. If you click on Add button or somewhere in the browser window is the same result. There is no difference.

**Comment by sshcli** [comment]
For me, Close modal button and Clear modal button has the same function.
When clicked, both buttons will close the poll settings modal.
