### ISSUE TITLE
Public users can see categories for Registered users

### ISSUE THREAD

**Issue by ChefMC** [Kunena/Kunena-Forum#5129]
Site: *** (Joomla 3.6.5, Kunena 4.0.12)

There are you can see categories which you can't see here:

*** (Joomla 2.5.28, Kunena 4.0.11)

**Comment by 810** [comment]
Kunena 4.0.12 isn't supported anymore. please update.

**Comment by ChefMC** [comment]
But version 5 is very raw and full of bugs. From template to double login forms which unable to fix
Please, make exception for that cause

**Comment by 810** [comment]
Try with blue eagle, and check again, i think its a tk template issue. That dev is gone already 4 years ago, so no updates since K2.0.4

**Comment by ChefMC** [comment]
I've tested, but nothing fixed (even with Crypsis)

**Comment by 810** [comment]
then check the permission on the categories

**Comment by iBars** [comment]
![image](https://cloud.githubusercontent.com/assets/3519015/21710055/17426240-d3f7-11e6-89ce-642b12832db1.png)

Checked, but not

**Comment by ChefMC** [comment]
Solved. Default Joomla guests group was wrong as I debug
