### ISSUE TITLE
Thumbnail image for attachements files

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5138]
#### Steps to reproduce the issue
Create a new topic and insert a file (Not image)

#### Expected result
Popular extension files like .doc, .zip, .pdf, .txt, etc... should have their own thumbnail image or icon.

#### Actual result
![image](https://cloud.githubusercontent.com/assets/12942731/21734394/8731faf6-d439-11e6-9237-55af75edad8e.png)

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.5
Php version: 7.0.14
Database version: MySQL 5.6.34

**Comment by 810** [comment]
Then we need to have 90+ images for all extensions, i don't think we should do that.

**Comment by sshcli** [comment]
OK, no problem.
I'm closing this one.
