### ISSUE TITLE
add option to disable quick reply

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5142]
#### Steps to reproduce the issue

https://www.kunena.org/forum/kunena-feature-requests/139481-quickreply-how-to-disable-and-or-hide

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by rotech1** [comment]
need this URGENTLY - because "go to editor" is BROKEN ( editor comes up EMPTY ).
Just had a user lose ONE HOUR OF TYPING:

"Just spent 1 hour replying to Mr S's reply to my question and instead of sending it, was tempted to send it to the editor. Upon finding this page, decided to return back to the written page and found that my text had disappeared.

Can you recover it ?

In total anguish."

**Comment by sshcli** [comment]
@rotech1 in the meanwhile go to: \components\com_kunena\template\crypsis\layouts\message\item\actions\default.php
and replace that file with the one I'm attaching here: [default.zip](https://github.com/Kunena/Kunena-Forum/files/703023/default.zip) 
Note: Must unzip first

**Comment by rotech1** [comment]
Hmmm! that didn't solve it for me, but it got me on track... instead I commented out

\components\com_kunena\template\crypsis\layouts\message\edit\full.php

line 136 like this

`<!--<a href="index.php?option=com_kunena&view=topic&layout=reply&catid=<?php echo $message->catid;?>&id=<?php echo $message->thread;?>&mesid=<?php echo $message->id;?>&Itemid=<?php echo KunenaRoute::getItemID();?>" role="button" class="btn btn-small btn-link pull-right" rel="nofollow"><?php echo JText::_('COM_KUNENA_GO_TO_EDITOR'); ?></a>-->`



that hides the "go to editor..." link when I have the  Crypsis template QuickReply configuration set to "Always Visible' (which removes Quickreply button from next to the Actions dropdown, and has a main Quickeditor panel at the bottom of the thread)

hope this helps somebody!

I suppose the same edit to 
\components\com_kunena\template\crypsis\layouts\message\edit\quickreply.php could be helpful as well, if using modal configuration, etc

**Comment by sshcli** [comment]
> Hmmm! that didn't solve it for me

You are right, I forgot to say that you must have "Show default actions = No"

Anyway, just stay alert, the definite solution could be available at any time.

Regards,

**Comment by sshcli** [comment]
We can use "btn_qreply" to perform this task
