### ISSUE TITLE
issue with file/image upload

### ISSUE THREAD

**Issue by raramuridesign** [Kunena/Kunena-Forum#5145]
#### Steps to reproduce the issue
reply to a forum topic, add a file error as per screen shot

![image](https://cloud.githubusercontent.com/assets/902376/21794054/9036ae58-d6ff-11e6-8c21-43800bb31400.png)

#### Expected result
file does not upload

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: Kunena 5.0.5
Php version: 7.0.14
Database version: 5.5.52-cll

**Comment by 810** [comment]
I think you use a old .htaccess file, please rename the file, then rename the new htaccess.txt to .htaccess

**Comment by raramuridesign** [comment]
Thank you, this helped.
