### ISSUE TITLE
"Kunena Forum Package" is not being removed

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5158]
#### Steps to reproduce the issue
Components->Kunena Forum->Tools->Uninstall kunena

#### Expected result
All kunena files / directories / tables / packages should be removed at once.

#### Actual result
"Kunena Forum Package" is not being removed

#### System information (as much as possible)

Joomla version: 3.7.0-dev
Kunena version: 5.0.6-dev
Php version: 7.0.9
Database version: 5.6.35

**Comment by 810** [comment]
duplicated issue, closing this one
