### ISSUE TITLE
Maximum Image File Size doesn't work

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5162]
#### Steps to reproduce the issue
1. Cofiguration->Uploads->Images->Maximum Image File Size = 2048
2. Create a new topic and attach a 6KB .png image 

#### Expected result
You should be able to attach the image

#### Actual result
You will get this error:
Attachment image size exceed limit allowed by configuration

#### System information (as much as possible)

Joomla version: 3.7.0-dev
Kunena version: 5.1.0-ALPHA-DEV
Php version: 7.0.9
Database version: 5.6.35

#### Additional comments
I think this has been already fixed in 5.0.xx and just need to merge it into 5.1.xx 
But I'm not sure.

**Comment by rich20** [comment]
Sorry, I see now, this is the same https://github.com/Kunena/Kunena-Forum/issues/5175

**Comment by sshcli** [comment]
No problem, let's close this one in order to avoid duplicate.
