### ISSUE TITLE
Method getBBcodesEnabled() is not defined

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5165]
#### Steps to reproduce the issue
1. Install 5.1.0-ALPHA-DEV 2017-01-25 + Blue Eagle5 v.1.0.2
2. Go to example.com/forum/newtopic

#### Expected result
You shouldn't get an error

#### Actual result

Rendering Error in layout Topic/Edit/Editor: Method getBBcodesEnabled() is not defined in /home/user/public_html/example.com/components/com_kunena/template/blue_eagle5/layouts/topic/edit/editor/default.php on line 14
Layout was rendered in /home/user/public_html/example.com/components/com_kunena/template/blue_eagle5/layouts/topic/edit/default.php on line 208

![error](https://cloud.githubusercontent.com/assets/12942731/22345688/82017cca-e3d7-11e6-8a50-2432f337ca83.JPG)

#### System information (as much as possible)

Joomla version: 3.7.0-dev
Kunena version: 5.1.0-ALPHA-DEV 2017-01-25 + Blue Eagle5 v.1.0.2
Php version: 7.0.9
Database version: 5.6.35

**Comment by sshcli** [comment]
I don't see the problem in:
J 3.7.0-beta1 dev + K 5.0.6.1 + BE 1.0.2.1

**Comment by 810** [comment]
Please test only crypsis and crypsisb3, for k5.1 we need to update the template later.

**Comment by sshcli** [comment]
Sure, no problem.
