### ISSUE TITLE
 K5.0.6 Released update error in backednd and frontend is blank

### ISSUE THREAD

**Issue by bunnachart** [Kunena/Kunena-Forum#5170]
#### Steps to reproduce the issue

Download package and install is error

#### System information (as much as possible)

Joomla version: Joomla! 3.7.0-alpha2  —  © 2017 รอบรู้.com

Kunena version:     5.0.5
Php version:  5.3.29 
Database version: 5.5.31

**Comment by rich20** [comment]
Upgrade your php verson.

**Comment by 810** [comment]
[pkg_kunena_v5.0.6_2017-01-27.zip](https://github.com/Kunena/Kunena-Forum/files/736936/pkg_kunena_v5.0.6_2017-01-27.zip)
Please try this package.

i can't test any php 5.4 versions, because all my env settings are x64
