### ISSUE TITLE
Click on Name Member for profile details it show 500 Internal Server Error

### ISSUE THREAD

**Issue by bunnachart** [Kunena/Kunena-Forum#5173]
#### Steps to reproduce the issue
Click on Name member for see more details user profile is Error

500 Internal Server Error
Fatal Error was detected!

Please contact the site owner.

but in version  K5.0.5 Released can see user profile

#### System information (as much as possible)

Joomla version: Joomla! 3.7.0-alpha2

Kunena version:  K5.0.6.1 Released 
Php version:  5.3.29 
Database version: 5.5.31 

#### Additional comments

![2017-01-28_23-20-03](https://cloud.githubusercontent.com/assets/25403222/22397958/57b6d5a2-e5b0-11e6-8f58-99d4000b1ed8.jpg)

**Comment by bunnachart** [comment]
now everything is ok work well. Thank you programmer.

**Comment by rich20** [comment]
If you have problems in the future, ask in the forum https://www.kunena.org/
Github is for development and not for support.
