### ISSUE TITLE
May be can add function for save drafts when need to don't publish now.

### ISSUE THREAD

**Issue by bunnachart** [Kunena/Kunena-Forum#5174]
#### Steps to reproduce the issue
I don't know where to suggestion some feature and than i think here better.

#### System information (as much as possible)

Joomla version: Joomla! 3.7.0-alpha2
Kunena version:  5.0.6.1
Php version:     5.6.28 
Database version: 5.5.31

**Comment by xillibit** [comment]
I had already opened an issue for that : https://github.com/Kunena/Kunena-Forum/issues/2346
