### ISSUE TITLE
Upload attachments is not possible  (no matter which setting)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5175]
#### Steps to reproduce the issue

Try upload a attachment

#### Actual result

No matter which configuration, it shows always the message
"Attachment image size exceed limit allowed by configuration"

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0 beta 1
Kunena version: 5.1 Alpha
Php version: 7.0.14
Database version:

**Comment by rich20** [comment]
Sorry, the label Crypsis was my mistake. The error exists with all templates.

**Comment by 810** [comment]
For me its running fine, did you checked the file limit, also which file extensions did you tried.

**Comment by sshcli** [comment]
I have tested again and the problem persist:
J.3.7.0-beta3 + K.5.1.0-ALPHA-DEV 2017-02-18 + Crypsis

**How to reproduce it?**
Create a new topic and attach a 5KB .png image

**You will get the following error:**
![error](https://cloud.githubusercontent.com/assets/12942731/23087892/1044930a-f54e-11e6-991d-f679649916a4.JPG)

**Comment by Couby** [comment]
Problem still alive with 5.1.1 :(

**Comment by cyrez** [comment]
@Couby Could you test this PR with a Fix (i add the same issue) : https://github.com/Kunena/Kunena-Forum/pull/6016

**Comment by 810** [comment]
@Couby please try the nightly build, its on our download page on our site.

**Comment by Couby** [comment]
All seems to work back fine with the last nightly (5.1.2-DEV) 😊 ...

Many thanks for this orientation and for the job on Kunena.

Best regards.
