### ISSUE TITLE
Wysiwyg Editor | Configuration report breaks the editor layout

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5176]
#### Steps to reproduce the issue

Click Reply or Reply Topic
Add a configuration report

#### Expected result

No layout error

#### Actual result

It breaks the complete page layout

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0-beta1
Kunena version: 5.1.0-ALPHA-DEV
Php version: 7.0.14
Database version:

#### Additional comments

This error exists not with Quick Reply

**Comment by 810** [comment]
The correct way to post the settings:

1) click on bbcode
2) paste the code


Because there is also a issue with confidential, when you d by bbcode, then its working.

**Comment by rich20** [comment]
At quick reply this problem not exists but it's the same editor window.

**Comment by 810** [comment]
this is a 3rt party issue, closing this one. This is only a issue for our website. we need to think about it,  we are still going to use bbcode editor.
