### ISSUE TITLE
Attachment Manager tab should be hidden

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5178]
#### Steps to reproduce the issue
1. Configuration->Uploads->Images->Allow Image Uploads = Nobody
2. Configuration->Uploads->Files->Allow File Uploads = Nobody
3. Login as registered user
4. Go to profile view (example.com/forum/profile/id-username)

#### Expected result
The "Attachment Manager" Tab should be hidden if the options mentioned above are disabled and the user doesn't have any attachment.
 
![hidden](https://cloud.githubusercontent.com/assets/12942731/22412849/0010de86-e689-11e6-9743-52d63a057ddd.JPG)

#### Actual result
The user is able to see the "Attachment Manager" Tab, even when the user doesn't have any files and the option to upload files is disabled in the backend.

![visible](https://cloud.githubusercontent.com/assets/12942731/22412846/fc95adcc-e688-11e6-9672-70bd058a3bf7.JPG)

#### System information (as much as possible)

Joomla version: 3.7.0-beta1
Kunena version: 5.0.6.1
Php version: 7.0.9
Database version: MySQL 5.6.35

**Comment by rich20** [comment]
You can disable it in the configuration.
Display profile tab to manage attachments = Yes or No

**Comment by sshcli** [comment]
What about add a new option:
1. Yes
2. No
3. Only if there are attachments (Default)

**Comment by sshcli** [comment]
For a better world we still need an additional condition.

Show the "Attachment Manager Tab" if the user has at least 1 file.

Even when the configuration in the backend is like this:
Allow Image Uploads = Nobody
Allow File Uploads = Nobody
Display profile tab to manage attachments = No
