### ISSUE TITLE
Profile Global Settings | The editor selection should be between BBCode and Wysiwyg

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5180]
#### Steps to reproduce the issue

With the Wysiwyg editor it's not possible to create a poll. So might a moderator to switch to the BBCode editor. 
Currently we have selection between: CodeMirror, None and TinyMCE. But these editors are not usable.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
we will not support editors for joomla. I'm closing this one.

This should be a global setting, not a personal setting
