### ISSUE TITLE
Configuration - Users | Show E-mail = No has no effect

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5185]
#### Steps to reproduce the issue

Backend setting - Show E-mail = No (it's default setting)
Go in your Profile -> Form Setting and choose Hide E-mail = No 

#### Expected result

Nevertheless the address should not be visible

#### Actual result

The address is visible for all (also guests)

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7-beta2
Kunena version: 5.0.6.1 and 5.1-alpha 
Php version: 7.0.14
Database version:

**Comment by 810** [comment]
Hide E-mail = No

Means show email, so the option is correct.

**Comment by rich20** [comment]
> Hide E-mail = No

Yes this option is correct, but it shows the address also, when the admin in backend has set Show E-mail = No

**Comment by 810** [comment]
where do you see the email address

**Comment by rich20** [comment]
You see the address in his profile

**Comment by 810** [comment]
are you sure you are a normal user. try with guest

**Comment by rich20** [comment]
Sorry, it was my mistake. You see the addess in the profile box beside the message. Also as guest.

**Comment by rich20** [comment]
In principle it's not a problem,, but I think, the user profile setting should not override the admin setting.
