### ISSUE TITLE
Editor | Link Description does not work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5187]
#### Steps to reproduce the issue

1. Mark a text passage in the editor
2. Click on the Link Symbol
3. To enter a link
4. Click on Add

#### Expected result

1. The link description should be in the modal text insert field 
2. Only the link description should be displayed in the message

#### Actual result

It shows both
In the editor `[url=https://www.kunena.org/]https://www.kunena.org/Link Description[/url]`
In the message `https://www.kunena.org/Link Description`

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7 beta2
Kunena version: 5.0.6.1 and 5.1 Alpha
Php version: 7.0.14
Database version:

**Comment by Ruud68** [comment]
some more info in this thread: it's not only the hyperlink... https://www.kunena.org/forum/k4-0-kunena-support/134759-not-fixed-unordered-and-ordered-list-not-working-as-expected-3372#169221

**Comment by xillibit** [comment]
Is-it fixed now with CKeditor ?

**Comment by rich20** [comment]
Yes, the CKeditor solves this issue.
