### ISSUE TITLE
User->isBanned fix bolean now its date

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5188]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Can-you explain what the issue with that part ?

**Comment by 810** [comment]
somethimes you will get the date instead of 0 or 1

**Comment by xillibit** [comment]
Where ? Can-you explain please how to reproduce the issue ?

**Comment by 810** [comment]
````
/**
	 * @return bool
	 */
	public function isBanned()
	{
		if (!$this->banned)
		{
			return false;
		}

		if ($this->blocked || $this->banned == $this->_db->getNullDate ())
		{
			return true;
		}

		$ban = new JDate ($this->banned);
		$now = new JDate ();

		return ($ban->toUnix () > $now->toUnix ());
	}
````

Here you see it wants a boolean, but on the end you will see its getting a date format.
So for some code it will breaking it. I had a link, but i can't found it anymore, on our site.

**Comment by enes-oerdek** [comment]
Related PR and Issues
#5391 #5377 

Another relation: /libraries/kunena/user:
`			// Change user state also in #__kunena_users
			$profile = KunenaFactory::getUser($this->userid);
			$profile->banned = $this->expiration;
			$profile->save(true);`
