### ISSUE TITLE
Press share Facebook button but when share the display don't show image attachment in post

### ISSUE THREAD

**Issue by bunnachart** [Kunena/Kunena-Forum#5202]
#### Steps to reproduce the issue
Press share Facebook button but when share the display don't show image attachment in post
![2560-02-21 11 00 17](https://cloud.githubusercontent.com/assets/25403222/23150338/68739b82-f825-11e6-8a32-bb2a953e242f.png)

![2560-02-21 11 05 03](https://cloud.githubusercontent.com/assets/25403222/23150379/9e456f42-f825-11e6-938e-97e7d78b34bf.png)

 my url

http://www.รอบรู้.com/%E0%B8%9F%E0%B8%AD%E0%B8%A3%E0%B8%B1%E0%B9%88%E0%B8%A1/%E0%B8%84%E0%B8%AD%E0%B8%A1%E0%B9%82%E0%B8%9E%E0%B9%80%E0%B8%99%E0%B9%89%E0%B8%99%E0%B8%97%E0%B9%8C/105-%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87-sitemap-xml-%E0%B8%87%E0%B9%88%E0%B8%B2%E0%B8%A2%E0%B9%86%E0%B9%83%E0%B8%AB%E0%B9%89%E0%B8%81%E0%B8%B1%E0%B8%9A%E0%B8%88%E0%B8%B9%E0%B8%A1%E0%B8%A5%E0%B9%88%E0%B8%B2%E0%B8%94%E0%B9%89%E0%B8%A7%E0%B8%A2%E0%B8%84%E0%B8%AD%E0%B8%A1%E0%B9%82%E0%B8%9E%E0%B9%80%E0%B8%99%E0%B9%89%E0%B8%99%E0%B8%97%E0%B9%8C-aimy-sitemap.html

#### System information (as much as possible)

Joomla version: Joomla! 3.7.0-beta2
Kunena version:     5.0.6.1
Php version: 5.6.28 
Database version: 5.5.31

**Comment by 810** [comment]
could you give your joomla sef settings.

**Comment by bunnachart** [comment]
I wonder now working normally.
I enable cache plugins / gzip enable / install  JotCache: Component

Before the image when share on facebook not showing but now is ok.

Thank you for reply.
