### ISSUE TITLE
Red Validator fires upon first body click

### ISSUE THREAD

**Issue by JoshJourney** [Kunena/Kunena-Forum#5206]
#### Steps to reproduce the issue

Create a new topic
Click the text body field

#### Expected result

Validator showing blue around the text area.

![good-validator](https://cloud.githubusercontent.com/assets/4361528/23275517/aa0ef5fe-f9bb-11e6-8063-5b58f11729a9.png)

#### Actual result

![validator-onclick](https://cloud.githubusercontent.com/assets/4361528/23275523/b099f5ea-f9bb-11e6-8a47-e9357b5c0130.png)

Validator immediately indicates that something is wrong. Red validation should only show upon clicking submit when failing validation instead of giving an error vibe upon first field click.

#### System information (as much as possible)

Joomla version: 3.5.5
Kunena version: 5.0.6.1
Php version: 7.0.16
Database version: 5.6.28-76.1-log

**Comment by JoshJourney** [comment]
I'm glad the validation color goes away upon adding text. However there are still a few issues:

1. Upon first click it still highlights red as if something is wrong. Perhaps this is planned to be fixed in Kunena 5.0.10?

2. The title field does not validate red even if you click submit that a title is not present (mandatory field).

3. Your text becomes red when clicking outside of the field when blank and then clicking back in as seen here:

![invalid text](https://cloud.githubusercontent.com/assets/4361528/26524890/ce121d32-42f9-11e7-8fbd-e89bfce1fa01.png)

**Comment by 810** [comment]
Try now again, the classes will be added on after clicking submit.

**Comment by JoshJourney** [comment]
It shows blue validation in the title field after clicking submit. This doesn't indicate the title is the issue (the Joomla message at the top of course mentions it).
