### ISSUE TITLE
Active class not being assigned upon first view

### ISSUE THREAD

**Issue by JoshJourney** [Kunena/Kunena-Forum#5208]
#### Steps to reproduce the issue

In the backend open up a forum category or the main configuration. Sometimes the first tab has an active class, sometimes it doesn't. I think this is dependent on cache or a cookie. Either way there should always be an active class on the current tab you opened.

#### Expected result

![showing-active-class](https://cloud.githubusercontent.com/assets/4361528/23276233/66753cce-f9be-11e6-9c4e-e43ca2559269.png)

#### Actual result

![non-highlighted active item](https://cloud.githubusercontent.com/assets/4361528/23276240/6e2aa65c-f9be-11e6-9933-28f8830b5310.png)

This is due to the active class not loading into the DOM on first view:

![non-active](https://cloud.githubusercontent.com/assets/4361528/23276260/7dd1d260-f9be-11e6-9359-53333e387946.png)

#### System information (as much as possible)

Joomla version: 3.5.5
Kunena version: 5.0.6.1
Php version: 7.0.16
Database version: 5.6.28-76.1-log

**Comment by 810** [comment]
i think this has something todo with joomla.

Could you please check the joomla 3.7 beta 3, i can't reproduce this anymore with j3.7

**Comment by JoshJourney** [comment]
Indeed when upgrading my test site to J 3.7 the issue goes away. Thanks for looking into this, I'll be patient for J 3.7 for this to be fixed.
