### ISSUE TITLE
Forum Menu slight display issue

### ISSUE THREAD

**Issue by JoshJourney** [Kunena/Kunena-Forum#5209]
#### Steps to reproduce the issue

Go to Kunena index in Protostar template.

#### Expected result

![menu-fixed](https://cloud.githubusercontent.com/assets/4361528/23277904/797170bc-f9c4-11e6-924e-4db413a664af.png)

#### Actual result

![menu](https://cloud.githubusercontent.com/assets/4361528/23277908/7df833f0-f9c4-11e6-9bdc-f2720308bfb9.png)

To fix this I used the following:
`/media/kunena/cache/crypsis/css/kunena.css (line 1709)

#kunena.layout .navbar .nav {
    margin-bottom: -2px;
}`

#### System information (as much as possible)

Joomla version: 3.5.5
Kunena version: 5.0.6.1
Php version: 7.0.16
Database version: 5.6.28-76.1-log

**Comment by 810** [comment]
there was only a issue when your are logged in, so i fixed somewhere else the issue
