### ISSUE TITLE
Layout problem at installation on Joomla 3.6.5

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5216]
#### Steps to reproduce the issue

Install Kunena 5.0.7-dev on Joomla 3.6.5

#### Expected result

A popup with "Kunena has been successfully installed!"

#### Actual result

![bildschirmfoto von 2017-02-24 04-09-16](https://cloud.githubusercontent.com/assets/888847/23289288/ee0eb4fa-fa48-11e6-8afd-02a88762d571.png)

#### Additional comments

This error exists only with Joomla 3.6.5 but not with Joomla 3.7 beta or 3.7 rc1
Tested on 4 different pages

**Comment by 810** [comment]
should now be fixed
