### ISSUE TITLE
Backend: Uploading new emoticon failed

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#522]
Error. Unable to upload emoticon

**Comment by JoshuaLewis** [comment]
I found out in my case this is because I was uploading a smile.png when an image with the exact same name already existed.

**Comment by 810** [comment]
@xillibit could you fix this on libraries\kunena\upload\helper.php

**Comment by xillibit** [comment]
I will check to see what's going on with that

**Comment by 810** [comment]
@JoshuaLewis Thnx for reporting, it would be fixed in the next version. I'm closing this one again
