### ISSUE TITLE
BBCode Editor | The poll symbol is inactive (it opens no modal window)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5225]
#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0-rc1
Kunena version: 5.1-dev
Php version:7.0.14 and 7.1.1
Database version:

**Comment by xillibit** [comment]
Do-you have javascript errors in developpement console of firefox ?

**Comment by rich20** [comment]
Firefox tool shows : Pass empty string in getElementById() (jquery-min.js)
Other browser tools (Chromium and Opera) shows no error messages, there is absolutely no reaction if you click at the symbol.

**Comment by rich20** [comment]
It works now so I close this.issue.
