### ISSUE TITLE
After upgrade the thumbnails below the message are not recognized

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5227]
#### Steps to reproduce the issue

1. Set Protect Attachments = Yes
2. Upload images
3. Now Upgrade to Kunena 5.1

#### Expected result

The thumbnails should be visible

#### Actual result

The requested content cannot be loaded
There are encrypted addresses such as : 
data:image/png;base64,iVBORw0KGgoAAAAN..... (I've cut off the address)

![bildschirmfoto von 2017-03-06 20-22-35](https://cloud.githubusercontent.com/assets/888847/23626540/8e24d624-02ad-11e7-96f6-7797d34facb4.png)

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
@rich20  could you recheck it again, i don't have this issue anymore.

**Comment by rich20** [comment]
It seems thas ok now. But check also in your profile (tab Attachment Manager) wehther you can see the thumbnails. I'm not 100% sure, I've two identical test pages, but it works only with one.

**Comment by rich20** [comment]
> <strike>But check also in your profile (tab Attachment Manager) wehther you can see the thumbnails. I'm not 100% sure, I've two identical test pages, but it works only with one.</strike>

I'm sorry, forget it. I had enabled LazyLoad

**Comment by 810** [comment]
ok, is lazyload still working correct?

**Comment by rich20** [comment]
Thumbnails in the profile will not loaded with LazyLoad. But images in posts will loaded.

**Comment by 810** [comment]
closing for now, looks like it has been fixed.
