### ISSUE TITLE
Crypsisb3 | It seems there are a conflict with the modal window and bootstrap 3.3.7

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5228]
#### Steps to reproduce the issue

https://www.kunena.org/forum/general-questions-and-how-tos/139989-modal-forms-are-not-accessible-in-editor

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by Ruud68** [comment]
Same for crypsis and Joomla built in bootstrap version: https://www.kunena.org/forum/general-questions-and-how-tos/139989-modal-forms-are-not-accessible-in-editor?start=10#184286

**Comment by 810** [comment]
@Ruud68 could you try the nightly build

**Comment by Ruud68** [comment]
tested, not working :(

**Comment by 810** [comment]
could you test it again with the new nightly build

**Comment by Ruud68** [comment]
Top, I saw you removed the backdrop altogether: it works now (without the backdrop).
