### ISSUE TITLE
Improve Bootstrap Button Style

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5232]
#### Steps to reproduce the issue
Templates->Crypsis->Basic settings->Show default actions = No
Templates->Crypsisb3->Basic settings->Show default actions = No

#### Expected result
![with-right_class](https://cloud.githubusercontent.com/assets/12942731/23796857/790a0f7a-0573-11e7-986b-a918f8e760ba.JPG)

#### Actual result
![default](https://cloud.githubusercontent.com/assets/12942731/23796850/72cdd9b6-0573-11e7-8c4d-513cdaddd64f.JPG)

#### System information (as much as possible)

Joomla version: 3.7.0-rc1
Kunena version: 5.0.7-DEV 2017-03-08
Php version: 7.1.2
Database version: MySQL 5.6.35

**Comment by 810** [comment]
on basic you are right, but for visual i don't like the bright colors. This will look the forum very outdated, so i will close this issue.

**Comment by sshcli** [comment]
Ok, No problem
