### ISSUE TITLE
Crypsis - "Topic Icons: Images - Legacy" does not show "New" icons

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#5237]
#### Steps to reproduce the issue

In Crypsis => Features, set Topic Icons to "Images - Legacy"

#### Expected result

Icons will use the *_new.png version when the topic has new posts.

#### Actual result

The normal (non-new) icon is used instead.

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.6.1
Php version: 7.0.16

#### Additional comments

As discussed / shown at: https://www.kunena.org/forum/k5-0-support/140079-new-post-topic-icons-not-showing-new-version

**Comment by GJSchaller** [comment]
I suspect this changed when the new Bootstrap / FontAwesome icons were introduced - the same icon is used, but in a different color.  With legacy PNG files, a different file needs to be called instead.

**Comment by 810** [comment]
could you do a screenshot where you have your custom image.

We have moved the default system icons to media\kunena\topic_icons\default\system
instead of media\kunena\topic_icons\system

**Comment by GJSchaller** [comment]
Screenshot attached.  I can give you access to a test version of the site, if you like.

The custom icons work fine - the issue seems to be that the code is not calling the "new" version of the icon, for either the Default icons or the Custom ones.  The default icons have a green starburst on them for New, which is not showing here.

![screen shot 2017-03-19 at 6 18 14 pm](https://cloud.githubusercontent.com/assets/2761607/24085345/c659a4b6-0cd0-11e7-9e4c-1bb3f93eb28e.png)

**Comment by GJSchaller** [comment]
Here's the default icon screenshot:
![capture](https://cloud.githubusercontent.com/assets/2761607/24085356/f8fc284e-0cd0-11e7-9722-e890fe6e8cea.png)

**Comment by GJSchaller** [comment]
Here's the Normal, and Normal New, in Kunena 5.0.6.1 - you can see the New does not show up in the screenshot above.
![normal](https://cloud.githubusercontent.com/assets/2761607/24085387/96d2c974-0cd1-11e7-9b08-8739dbf812dd.png)
![normal_new](https://cloud.githubusercontent.com/assets/2761607/24085389/9b45f666-0cd1-11e7-9631-c271a1525857.png)

**Comment by 810** [comment]
Ok fixed,

I you have custom images with custom systemicons.xml file then you need to update your systemicons.xml file

**Comment by GJSchaller** [comment]
Thank you!

**Comment by GJSchaller** [comment]
I'm testing this on the March 29th build, and it does not seem to be working, even with the Default Topic Icons.
