### ISSUE TITLE
Users are able to post identical messages

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5244]
#### Steps to reproduce the issue
1. UserX creates a new topic from IP x.x.x.1
2. UserX creates the same topic from IP x.x.x.2

#### Expected result
Identical messages should be ignored, no matter what.

#### Actual result
Users are able to post identical messages

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7-DEV 2017-03-15
Php version: 7.1.2
Database version: MySQL 5.6.35

**Comment by 810** [comment]
Did you enabled Flood Protection? default is off

**Comment by sshcli** [comment]
Yes, it's enabled. 60 Seconds
You can use this free proxy to test with another IP simultaneously
https://hide.me/en/proxy

**Comment by 810** [comment]
We should to block same text by different ips.
