### ISSUE TITLE
.svg is not supported by bbcode [img][/img]

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5245]
#### Steps to reproduce the issue
Create a new topic and insert the following line in the content:
[img]https://privacy.google.com/images/overview/shields.svg[/img]

#### Expected result
.svg should be supported by bbcode [img][/img]

#### Actual result
.svg is not supported by bbcode [img][/img]

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7-DEV 2017-03-15
Php version: 7.1.2
Database version: MySQL 5.6.35

#### Additional comments
There are also other popular image formats that are not supported, such as: 
.bmp
.ico
.webp

**Comment by rich20** [comment]
All this formats are supported, but they have no standard file extension. If you want allow this types of files you must set in the configuration (tab BBCode) "Display Images With Non-standard File Extensions = Image"

**Comment by sshcli** [comment]
I agree.
I'm closing this one.
