### ISSUE TITLE
Small typo in error message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5259]
#### Steps to reproduce the issue

> The maps can't be displayed, you haven't specified the city

The text should not be written in the plural (map**s**). https://github.com/Kunena/Kunena-Forum/commit/e3ae584d3d6eb75ec5b13e1dd8a035fa4d5c2bf9 Each map has a own message. 

![bildschirmfoto von 2017-03-20 15-40-25](https://cloud.githubusercontent.com/assets/888847/24105963/e3a68c94-0d86-11e7-8615-163fd3da1d93.png)

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
Please close this one
