### ISSUE TITLE
Edit profile: Can't change name

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5264]
#### Steps to reproduce the issue

edit profile, change the name and click on save

#### Expected result

name has changed

#### Actual result

old name

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
I can confirm it.
it's a bug

**Comment by 810** [comment]
everything isn't working only password is working on that page

**Comment by sshcli** [comment]
Change name and username not working
Tested with J.3.7.0-rc1 +K.5.0.7-DEV 2017-03-21

**Comment by sshcli** [comment]
Test results: Success ✅
