### ISSUE TITLE
Map tag being inserted when press Enter

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5265]
#### Steps to reproduce the issue
Using Google Chrome or Microsoft Edge
1. Go to example.com/forum/newtopic
2. Make a click in the subject field.
3. Make a click in the message field.
4. Make a click in the subject field again.
5. Press the Enter key 

#### Expected result
Nothing should happen

#### Actual result
The following tag is inserted in the content:
[map type=HYBRID zoom=2][/map]

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7-DEV 2017-03-21
Php version: 7.1.2
Database version: MySQL 5.6.35

**Comment by rich20** [comment]
Open the modal for links, video or image, enter a link and press enter. It's always the same result. [map type=HYBRID zoom=2][/map]
Tested with K5.0.9 and Opera, Chromium and Firefox

**Comment by sshcli** [comment]
@rich20 you are right. I can confirm it.
Definitely this is a bug
