### ISSUE TITLE
Include IP in message reported

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5267]
#### Steps to reproduce the issue
UserX reports a topic.

#### Expected result
The moderator should be able to see the IP of UserX in the notification email.

#### Actual result
The IP of Userx is not included in the notification email

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7-DEV 2017-03-20
Php version: 7.1.2
Database version: MySQL 5.6.35

**Comment by sshcli** [comment]
Ok,
The IP is in the log,
is just add it to the notification email

**Comment by 810** [comment]
for protecting the users information, it should not be visible outside the database.

**Comment by sshcli** [comment]
Ok.
in that case, I'm closing this one
