### ISSUE TITLE
Sort by title not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5275]
#### Steps to reproduce the issue
1. Create 4 sections (A, B, C, D)
2. Try to sort them by title

#### Expected result
All categories should be sorted by name in an easy way

#### Actual result
Sort by title not working as expected
![sort](https://cloud.githubusercontent.com/assets/12942731/24378703/e8fb55e0-1311-11e7-8162-469fb50c8688.png)

#### System information (as much as possible)

Joomla version: 3.7.0 rc1 and 3.6.5
Kunena version: 5.0.7-DEV 2017-03-27
Php version: 7.1.3
Database version: MySQL 5.6.35

**Comment by 810** [comment]
for me its working correct

**Comment by sshcli** [comment]
try renaming your actual categories and/or sections and put them all as top level, then try it again.
@rich20 can you please check if you have any issue sorting by title?

**Comment by rich20** [comment]
With me is this with all sort options. It changes only the order. Either is the first section on top or it's the last section. There is no difference no matter whether you sort by title, ID or whatever. The result is always the same.

**Comment by sshcli** [comment]
> There is no difference no matter whether you sort by title, ID or whatever. The result is always the same.

Exactly, that's what I mean.  The "Sort by" feature is not working as it should be.
Thank you for your additional tests.

**Comment by xillibit** [comment]
@sshcli @rich20 : is-it working after the couples of changes of jelle ?

**Comment by sshcli** [comment]
@xillibit 
No, the title of the commit is wrong, it's not related to this issue.
So, until now, there is no fix for this issue yet.

**Comment by rich20** [comment]
Here a example with sort by status. On right you see the result. You get always the same result, no matter whether you sort by title, ID or whatever.
![bildschirmfoto von 2017-04-18 16-03-20](https://cloud.githubusercontent.com/assets/888847/25135352/7080b982-2452-11e7-9197-9e538c3d9106.png)

**Comment by sshcli** [comment]
Additionally:
There should be a save button, so you can easy save changes after sort categories.
