### ISSUE TITLE
Show labels by custom ID not working as expected

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5278]
#### Steps to reproduce the issue

1. Set in the configuration (tab Frontend) Selectable Topic Icons = No
2. Select in the template setting Show Labels = Custom id
3. Moderate a topic in the frontend
4. Try to change a label

#### Expected result

The label should be changed

#### Actual result

It shows always the default label (Question)

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0 rc1
Kunena version: 5.0.7-DEV
Php version: 7.0.14 and 7.1.1
Database version:

#### Additional comments

If you set in the configuration (tab Frontend) Selectable Topic Icons = Yes then you have no label selection. It shows also only the default label.

**Comment by 810** [comment]
it not a bug, because the feature is depending on the topic icons.

Later we will extarct it to his own function.
