### ISSUE TITLE
Fatal error if you want to open a message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5279]
#### Steps to reproduce the issue

Try to open a message

#### Expected result

No error

#### Actual result

Fatal Error: Method KunenaLayout::__toString() must not throw an exception, caught ParseError: syntax error, unexpected 'endif' (T_ENDIF), expecting end of file in components/com_kunena/template/crypsis/layouts/topic/item/message/default.php on line 0

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0
Kunena version: 5.1.0-ALPHA-DEV
Php version: 7.0.14 and 7.1.1
Database version:

**Comment by 810** [comment]
fixed
