### ISSUE TITLE
Can't use image with long URL

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5294]
#### Steps to reproduce the issue
Create a new topic and insert this image:
[img]https://www.google.com.do/imgres?imgurl=http%3A%2F%2Fmarianoabreu.com%2Fwp-content%2Fuploads%2F2011%2F09%2Fservicio-cliente.png&imgrefurl=http%3A%2F%2Fmarianoabreu.com%2Fseminarios%2Fservicio-al-cliente-mucho-mas-que-mercadeo%2F&docid=Bp9wQjv3oPrs0M&tbnid=JScA_Dvrg-uc2M%3A&vet=10ahUKEwihiYixtobTAhVLciYKHY_sDGI4yAEQMwhjKGEwYQ..i&w=155&h=215&bih=651&biw=1366&q=servicio%20al%20cliente&ved=0ahUKEwihiYixtobTAhVLciYKHY_sDGI4yAEQMwhjKGEwYQ&iact=mrc&uact=8[/img]

#### Expected result
You should see the image
or 
You should get an error saying that the image URL is in a wrong format

#### Actual result
The image won't display.
Also, the template layout is a mess in the preview mode.

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7
Php version: 7.1.3
Database version: MySQL 5.6.35

**Comment by rich20** [comment]
You have linked via google to a website. The link to the image is 
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZX9LXCsM-9DP3Z8MoybXncbxGvA8GF8iIJ-HKgw7MCpmmrWVH

**Comment by sshcli** [comment]
it doesn't matter. 
it doesn't work either

**Comment by rich20** [comment]
hm.. at me it works. You have set "Display Images With Non-standard File Extensions = Images" ?

**Comment by sshcli** [comment]
sorry, I was using the default "text" value.
Thanks for your tests.
I'm closing this one now.
