### ISSUE TITLE
Can't change subject on edit

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5296]
#### Steps to reproduce the issue
1. Configuration->Frontend->Allow to let user to change subject on replies = No
2. UserX tries to edit the subject of its own topic (Not the subject of a reply)

#### Expected result
UserX should be able to edit the subject of its own topic always

#### Actual result
UserX can't edit the subject of its own topic .
This is caused by a conflict with the feature "Allow to let user to change subject on replies"

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7
Php version: 7.1.3
Database version: MySQL 5.6.35

**Comment by 810** [comment]
we need to improve the language string, should be "Allow user to change their subjects"
