### ISSUE TITLE
Message "There are no topics to display" is not available in categories

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5299]
#### Expected result
The message "There are no topics to display" or "COM_KUNENA_VIEW_NO_TOPICS" should be available in the category view. (Crypsis and Crypsisb3)

![yes1](https://cloud.githubusercontent.com/assets/12942731/24764802/87794188-1ac3-11e7-8c40-5245379cc838.PNG)

#### Actual result
The message "There are no topics to display" or "COM_KUNENA_VIEW_NO_TOPICS" is not available in the category view. (Crypsis and Crypsisb3)

![no1](https://cloud.githubusercontent.com/assets/12942731/24764787/7dc72330-1ac3-11e7-8045-64496a39796e.PNG)

#### System information (as much as possible)

Joomla version:  3.6.5
Kunena version: 5.0.7
Php version: 7.1.3
Database version: MySQL 5.6.35

#### Additional comments
The message "There are no topics to display" or "COM_KUNENA_VIEW_NO_TOPICS" may be missing in other views not mentioned above.
For example: Blue eagle use this string on 3 different views
blue_eagle\html\topics\user_embed.php
blue_eagle\html\topics\default_embed.php
blue_eagle\html\category\default.php

**Comment by sshcli** [comment]
I think this is the file to be modified:
/components/com_kunena/template/crypsis/layouts/category/index/default.php

The format used in the other view is this:
<td colspan="4" class="center"><?php echo JText::_('COM_KUNENA_VIEW_NO_TOPICS') ?></td>

**Comment by sshcli** [comment]
Do you plan to do an additional pr for this issue? 
Or should be closed right now?

**Comment by xillibit** [comment]
I will do an another PR to put the text into a box to be more visible

**Comment by sshcli** [comment]
ok, thanks for your response

**Comment by xillibit** [comment]
I didn't found the way to hide this text when there is sub-categories displayed, i will try to look later
