### ISSUE TITLE
Error when trying to post a topic when Kunena-Finder plugin is enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5300]
#### Steps to reproduce the issue

Fatal error:  Cannot call abstract method FinderIndexer::index() in /site/plugins/finder/kunena/kunena.php on line 312

https://www.kunena.org/forum/general-questions-and-how-tos/140238-error-during-post#184888
https://www.kunena.org/forum/k5-0-support/140200-error-500-when-trying-to-post-a-topic-in-kunena-5-0-7

#### System information (as much as possible)

Joomla version:  3.6.5
Kunena version: 5.0.7
Php version: 7.0.17
Database version:

**Comment by xillibit** [comment]
I will take a look if i'am able to reproduce the issue, i had already tried but i wan't able to reproduce the issue
