### ISSUE TITLE
Avatar and status are unaligned (Mobile only)

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5317]
#### Steps to reproduce the issue
With your smartphone go to example.com/user/id-username

#### Expected result
![right](https://cloud.githubusercontent.com/assets/12942731/25160099/f0f20b32-2481-11e7-9417-8a9316688b88.PNG)

#### Actual result
![wrong](https://cloud.githubusercontent.com/assets/12942731/25160094/ede69f02-2481-11e7-8fb9-24563148a183.PNG)

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0-rc3
Kunena version: 5.0.8-dev
Php version: 7.1.3
Database version: MySQL 5.6.35

**Comment by 810** [comment]
its set to center, for now its ok.

But on Kunena 6.0 we will change the default template. So i would like to close this issue.
