### ISSUE TITLE
Move or Trash of user messages is limited to 20

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5321]
#### Steps to reproduce the issue

Backend -> Kunena -> Users
Mark in backend a user and click on Trash- or Move Messages

#### Expected result

All messages should be moved

#### Actual result

It will move only 20 messages

#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0-rc3
Kunena version: 5.1.0-ALPHA-DEV
Php version: 7.0.14 and 7.1.1
Database version:

**Comment by xillibit** [comment]
Is-it the same behaviour on K5.0.x ?

**Comment by rich20** [comment]
No, is only with K5.1
