### ISSUE TITLE
Subscrition: Plain Text Emails do not contain posted text (but HTML mails)

### ISSUE THREAD

**Issue by nextgen-networks** [Kunena/Kunena-Forum#5322]
#### Steps to reproduce the issue

1. In Kunena Configuration / Users / Subscription / Plain Text Emails -> set to "yes"
2. Subscribe to an category or topic

#### Expected result

Receive an plain text mail with everything WITH the postet text.

#### Actual result

Receive an plain text mail with everything except the postet text :-/

If you set the plain text option to "no" the HTML formatted mail will be send.
This version contains the posted text.

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version: 5.0.7
Php version: 7.1.4
Database version: 5.5.54

**Comment by 810** [comment]
Maybe you posted text is with bbcode, we are hiding the bbcode

So if you post a message only with a image, then you will see nothing

**Comment by nextgen-networks** [comment]
@810 nope the posted text consists only of standard characters.

_In this case it was:_
`Interessant, der Text der Nachricht wird offenbar im Plaintextmodus nicht mitgesendet ...`

**Comment by sshcli** [comment]
@nextgen-networks which template you are using? Crysisb3?

**Comment by nextgen-networks** [comment]
@sshcli Im using protostar (default joomla 3.6.5 theme) to be maximum compatible

**Comment by sshcli** [comment]
@nextgen-networks I mean the Kunena template.

Also who is receiving the blank email, the moderator or the user ?

**Comment by nextgen-networks** [comment]
@sshcli :-) aah, sorry - for kunena i use "Crypsis"

The mail was received by an user of the forum.
The mail itself was not completely blank - only the text of the post was missing.

Here is the complete text of the mail content:
```A new reply has been posted on the XXX Forum

Message Subject : Test 2
Category : Willkommen
Posted by : raupe

URL: https://XXX.tld/index.php/de/forum/willkommen/1-willkommen-bei-kunena#4
Message: 
...

You can unsubscribe from this topic by visiting it and clicking the Unsubscribe button near the top or bottom of the page.

Do not answer to this e-mail notification as it is a generated e-mail.
```
**So, my explanation was not absolutely correct - the text has been replaced by three dots.**

**Comment by sshcli** [comment]
Can you send us the exact text content you have  in the topic content?
Maybe there is an unsupported character in the content

**Comment by nextgen-networks** [comment]
@sshcli as requested here is the complete content of the subscribed forum:

**Start Message (created by Kunena install):**
```raupe created the topic: Willkommen bei Kunena!
Willkommen bei Kunena! 

Danke, dass du dich für Kunena als Forumslösung entschieden hast.

Kunena - aus Swahili übersetzt - bedeutet „Sprechen“ und wird von einem Team aus Open-Source-Experten entwickelt, mit dem Ziel, eine qualitativ hochwertige und leichte Forumslösung für Joomla zu schaffen.


Zusätzliche Kunena Ressourcen 

Kunena Dokumentation: https://www.kunena.org/docs 

Kunena Support Forum: https://www.kunena.org/forum 

Kunena Downloads: https://www.kunena.org/download 

Kunena Blog: https://www.kunena.org/blog 

Folge Kunena auf Twitter: https://www.kunena.org/twitter
```

**1st reply**
```raupe replied the topic: Test 2
Prüfung ob Real oder Nickname versendet wird
```

**2nd reply**
```raupe replied the topic: Test 2
Interessant, der Text der Nachricht wird offenbar im Plantextmodus nicht mitgesednet ...
```

**3rd reply**
```raupe replied the topic: Test 2
Noch'n Reply nach Anpassung der Mailfunktion
```

**Comment by nextgen-networks** [comment]
Ok did another test with a new topic and also changed php version (to 7.0.18) while testing.
**Here is a screenshot of its content:**
![2017-04-24_kunena_testtopic_001](https://cloud.githubusercontent.com/assets/21206978/25336416/aa27fc32-28f7-11e7-8eb8-238705bcd237.jpg)

**This is the content of the subscription mail that has been send to an subscribing user (not the author):**
```A new reply has been posted on the Brandenmark Forum

Message Subject : TestTopic for subscription
Category : Willkommen
Posted by : raupe

URL: https://URL.tld/index.php/de/forum/willkommen/2-testtopic-for-subscription#10
Message: 
blubb...

You can unsubscribe from this topic by visiting it and clicking the Unsubscribe button near the top or bottom of the page.

Do not answer to this e-mail notification as it is a generated e-mail.
```
The mail contains only the first word of the new post that has been made.

It also seems to make no difference wether you use php 7.1.4 or 7.0.18.

**Comment by rich20** [comment]
Thank you for testing. Confirmed, it's a bug. The message will cutted if you send with plain text. The same is with mails to mderators and if you report a message.

@810 @xillibit 

`$full .= $this->message->displayField('message', false);`
Should be the value true instead the value false?

/components/com_kunena/template/crypsis/layouts/email/subscription/default.php
/components/com_kunena/template/crypsis/layouts/email/subscription/moderator.php
/components/com_kunena/template/crypsis/layouts/email/report/default.php

**Comment by 810** [comment]
@rich could you try this fix:
https://github.com/Kunena/Kunena-Forum/pull/5334

**Comment by 810** [comment]
You can download the nightly build on the website.
