### ISSUE TITLE
backend common view is now blocked

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5327]
#### Steps to reproduce the issue

install nightly build
go to kunena backend

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
Bug confirmed.

![404](https://cloud.githubusercontent.com/assets/12942731/25286443/c2deaaa0-268b-11e7-9425-519fae5e085f.PNG)
