### ISSUE TITLE
Incorrect username shown in topic when name contains "

### ISSUE THREAD

**Issue by Twincarb** [Kunena/Kunena-Forum#5333]
#### Steps to reproduce the issue
Have a user who's name includes " and post a topic using the user

#### Expected result
John "big dog" created the topic: Important Vehicle 

#### Actual result
John &quot;big dog&quot; created the topic: Important Vehicle 

#### System information (as much as possible)

Joomla version: 3.6.5
Kunena version:5.0.7
Php version:7.1.4
Database version:

**Comment by rich20** [comment]
Please use the code tags so we can see the difference between expected and actual result.

**Comment by Twincarb** [comment]
Thanks for the swift action, completely forgot that github would interpret the code and translate it, mental note made for next time! 👍
