### ISSUE TITLE
Show total attachments in backend

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5347]
#### Steps to reproduce the issue
Backend->Components->Kunena Forum->Attachments

#### Expected result
The total number of attachments should be visible.

#### Actual result
There is no way to know how many attachments are stored in the server.

#### System information (as much as possible)

Joomla version: 3.7.0
Kunena version: 5.0.8-DEV
Php version: 7.1.4
Database version: MySQL 5.6.35

**Comment by xillibit** [comment]
Where that should appear ?

**Comment by 810** [comment]
On top i think

**Comment by sshcli** [comment]
i think it could be one of these:
<img width="152" alt="1" src="https://cloud.githubusercontent.com/assets/12942731/26067159/33ba411a-3967-11e7-9d39-f3137a8d04ad.PNG">
<img width="510" alt="2" src="https://cloud.githubusercontent.com/assets/12942731/26067158/33b9f246-3967-11e7-9938-7c61fa0d6139.PNG">
<img width="320" alt="3" src="https://cloud.githubusercontent.com/assets/12942731/26067160/33d4ea56-3967-11e7-801d-6f45a0cb8b74.PNG">
