### ISSUE TITLE
Hide Premium Templates Section after install

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5348]
#### Steps to reproduce the issue

Backend->Components->Kunena Forum->Templates

#### Expected result
The "Premium Templates" section should be hidden after install Premium Templates.
![good7](https://cloud.githubusercontent.com/assets/12942731/25624506/95eb57a6-2f27-11e7-892b-90950ff88cd8.JPG)

#### Actual result
The "Premium Templates" section is always visible.

![bad7](https://cloud.githubusercontent.com/assets/12942731/25624495/8c70bdce-2f27-11e7-80dd-3e1ead078614.JPG)

#### System information (as much as possible)

Joomla version: 3.7.0
Kunena version: 5.0.8-DEV
Php version: 7.1.4
Database version: MySQL 5.6.35

**Comment by Ruud68** [comment]
Should it also be invisible when there are multiple premium templates available? Currently there is only one you can purchase but I can imagine that in the future there will be more?

**Comment by sshcli** [comment]
> Should it also be invisible when there are multiple premium templates available?
Not a good idea.

If there will be more templates in the future, then I suggest to only hide the "Blue Eagle" section, Not "Premium Templates"

And

if there are no more templates available, then show the message:
"Great ! You have installed all premium templates"

**Comment by xillibit** [comment]
We need in xml file of template a way to differenciate normal templates than premium templates, then after we need to add something which check if one or more premium templates are installed

**Comment by 810** [comment]
we have now more template providers added. So I'm closing this issue
