### ISSUE TITLE
Update rss landing page

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5352]
#### Steps to reproduce the issue
1. Open internet explorer
2. Type your domain name followed by /rss in the address bar. (example.com/rss)

#### Expected result
You should be redirected to:
example.com/topics/mode-topics?format=feed

#### Actual result
You will be redirected to:
example.com/topics/mode-topics/sel-720?type=rss&format=feed

#### System information (as much as possible)

Joomla version: 3.7.0
Kunena version: 5.0.8-DEV
Php version: 7.1.4
Database version: MySQL 5.6.35

**Comment by 810** [comment]
This is correct,he is loading the 720 (default setting = month) if you change the option on the config, then you will get a other number, this is the timefilter. (cache = 15 min), so you need to clear cache before see the change
