### ISSUE TITLE
Attachment button doen't work on edit

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5362]
#### Steps to reproduce the issue

edit a message, click on attachments button

#### Expected result

attachment  upload opens

#### Actual result

nothing

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
Issue is on the pollcheck.js

**Comment by xillibit** [comment]
Which one editor did-you had tried ?

**Comment by 810** [comment]
the old one

**Comment by rich20** [comment]
No matter which editor. It's with both the same.

**Comment by rich20** [comment]
I think this problem is more complex. When the attachment button not work, then also it lacks the code symbol bar in the editors. If you have the toolbar (such as at New Topic), the attachment button work.
Also on Reply lacks the toolbar and you can't insert attachmennts.

**Comment by kunenaservice** [comment]
There is a small conflict on the js file. When you remove the lines. Then everything is working again.
