### ISSUE TITLE
"Report this" button has wrong icon 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5367]
#### Steps to reproduce the issue
Backend->Kunena Forum->Templates->Features->Topic Icons = Bootstrap2

#### Expected result

 icon-exclamation-sign

#### Actual result

icon-flag
![bad](https://cloud.githubusercontent.com/assets/12942731/25962304/272ed6aa-364b-11e7-8e10-0ba418edf343.JPG)

#### System information (as much as possible)

Joomla version: 3.7.0
Kunena version: 5.0.8-DEV
Php version: 7.1.4
Database version: MySQL 5.6.35

**Comment by 810** [comment]
I think icon-exclamation-sign is more a warning icon.
And flag, is something reporting.

**Comment by sshcli** [comment]
In that case, FA should also use a flag icon
