### ISSUE TITLE
Failed to add avatars

### ISSUE THREAD

**Issue by SilasSit** [Kunena/Kunena-Forum#5369]
#### Steps to reproduce the issue
Profile for <username> > Avatar Image > Add avatar
Then choose one picture
#### Expected result

Avatar chosen

#### Actual result
Message "You can only add one avatar into your profile." appears

#### System information (as much as possible)

Joomla version: 3.7.1-dev
Kunena version: v5.1.0-ALPHA-DEV_2017-05-13
Php version: 7.1.1
Database version: MySQLi 5.5.5-10.1.21-MariaDB

#### Additional comments
![image](https://cloud.githubusercontent.com/assets/8351034/26030177/68373fbe-387d-11e7-822e-3d8757f28ce5.png)

**Comment by 810** [comment]
check https://github.com/Kunena/Kunena-Forum/pull/5365

**Comment by SilasSit** [comment]
Now i edited the code from #5365 
The drag and drop function redirects me to the file in my drive
And after choosing a picture using the button it has no response

![image](https://cloud.githubusercontent.com/assets/8351034/26030269/ac409766-3880-11e7-9f33-0beef7f5999b.png)

**Comment by 810** [comment]
could you use the add avatar, then select a image, then it will be uploaded by ajax.

**Comment by rich20** [comment]
I've tested it now. It works with the add button and also with drag&drop with this code. But the avatar galery is obsolete now. You can't add images from the avatar galery.

**Comment by SilasSit** [comment]
Found that i have mis-pasted one extra code.
now it says "Avatar size exceed limit allowed by configuration"
will it be resized during the edit?

![image](https://cloud.githubusercontent.com/assets/8351034/26030322/da775690-3882-11e7-9378-edaba5f80c76.png)

**Comment by 810** [comment]
that is a know issue, florian is working on it.

**Comment by xillibit** [comment]
The image is resized after upload but it check before that the filesize before upload

**Comment by SilasSit** [comment]
![image](https://cloud.githubusercontent.com/assets/8351034/26529052/3dd28dae-43eb-11e7-978e-bce46126fc22.png)

The problem still exists

**Comment by xillibit** [comment]
In Kunena configuration panel, under tab avatar which value do-you have for max avatar file size ?

**Comment by SilasSit** [comment]
2048KB, while my photo is only 16KB
