### ISSUE TITLE
Instagram: remove ?taken-by=username

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5371]
#### Steps to reproduce the issue

instagram is now adding the text.

We should remove the text before parsing the url. on the bbcode Doinstagram

#### Expected result

embed is displayed

#### Actual result

error

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
you mean that in url pasted in instagram bbcode there is the ?taken-by=username ?

**Comment by 810** [comment]
no, when you opened a photo on the instagram website, there is now a extra text ?taken-by=username on the url. 

like `www.instagram.com/p/BTndlnmATeF/?taken-by=k.o.s.t.i.n.a.a `
so we should remove the group with regex. 


See: https://www.kunena.org/forum/installation-issues/139169-instagra-stopped-working-again

**Comment by kingofmercy** [comment]
It is not the first issue of Instagram, it has also a lot of ghosts. Personally I use things like https://spamguardapp.com/dashboard to keep my profile away from them, but isn't it the deal of IG?
