### ISSUE TITLE
Menu item "My Topics" is not accurate

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5383]
#### Steps to reproduce the issue
Kunena Menu-> My topics-> Select View = My Recent Topics or Posted by me

#### Expected result
The total topics/messages shown here:
https://www.kunena.org/forum/mylatest
<img width="124" alt="1" src="https://cloud.githubusercontent.com/assets/12942731/26161479/08b96edc-3af2-11e7-9ae7-b7cce5e811f7.PNG">

Should match with total topics/messages shown here:
https://www.kunena.org/forum/profile/43643-ssh
<img width="141" alt="2" src="https://cloud.githubusercontent.com/assets/12942731/26161487/0b551772-3af2-11e7-913d-591ac2550875.PNG">

#### Actual result
Values does not match

#### System information (as much as possible)

Joomla version: 3.7.0
Kunena version: 5.0.8
Php version: 7.1.5
Database version: MySQL 5.6.35

**Comment by 810** [comment]
1) is topics
2) are messages

**Comment by sshcli** [comment]
Language strings are different, I agree.
But the menu item has the option "Posted by me" which means "Messages"
Am I Right?

**Comment by sshcli** [comment]
and the view "My Recent Topics" is also showing replies/messages. (Not only started topics)
