### ISSUE TITLE
Issue on IMG-Tag

### ISSUE THREAD

**Issue by enes-oerdek** [Kunena/Kunena-Forum#5386]
Dear Kunena-Developers,
I would like to report two vulnerabilities in kunena.

#### Expected result
No execution of Javascript.

#### Actual result
Execution of Javascript.

#### System information (as much as possible)

Joomla version:  Joomla! 3.7.1 Stable [ Amani ] 17-May-2017 14:00 GMT 
Kunena version: 5.0.8
Php version: 5.6.30-0+deb8u1
Database version: 5.5.55-0+deb8u1-log 

#### Additional comments
Fixes:
1. /components/com_kunena/template/crypsisb3/layouts/bbcode/image/default.php (also in other templates)
Search:
`$attributesImg .= $alt ? ' alt="' . $alt . '"' : '';`
Replace:
`$attributesImg .= $alt ? ' alt="' . htmlspecialchars($alt) . '"' : '';`

2. /libraries/kunena/bbcode/bbcode.php: function DoImage
Search: 
`$fileurl = $bbcode->UnHTMLEncode(trim(strip_tags($content)));`
Replace:
`
$fileurl = $bbcode->UnHTMLEncode(trim(strip_tags($content)));
		if (!$bbcode->IsValidURL($fileurl, false, true))
		{
			return htmlspecialchars($params['_tag'], ENT_COMPAT, 'UTF-8') . $content . htmlspecialchars($params['_endtag'], ENT_COMPAT, 'UTF-8');
		}
`

Kind regards,
Enes

**Comment by 810** [comment]
Hello,

Thank you for the report, but i can't reproduce the xss, for me its Always encoded correct.
Could you test it on my test server: www.newf1.nl/forum  demo/demo

And for the next time, never open an issue on git about security issues, but email the developers.
For us: security@kunena.org

**Comment by enes-oerdek** [comment]
I'm sorry, I looked for an e-mail address, but could not find this on the documentation page. Please consider to insert this address on the README-page of this repository or more visible on the kunena homepage.

You are correct. On the testing-forum it does not work. This could be because there is another kunena version installed or other cloudflare-configs are used. On the main kunena-forum it works. Just try the following:


Kind regards,
Enes

**Comment by 810** [comment]
Hi Enes.
It has the same version.
I have also tried it on my local wamp, just default php and same version 5.0.8, also i couldn't reproduce.


I will add it on the readme files. Its on our team page.

**Comment by enes-oerdek** [comment]
I don't know why it can not be reproduced in the testing-systems. I just tried it on the kunena.org-forum, on the playground and was successful:
https://www.kunena.org/forum/164-Fairground/139094-acssac#185663

If it's not an issue in kunena-component, you can close this issue. But I recommend to at least check this issue on the kunena.org-forum.

**Comment by 810** [comment]
yes thnx,i will check it.

**Comment by 810** [comment]
ok, i have merged your pr, and it looks it has been solved.
I will do a new release soon.
