### ISSUE TITLE
BBCode Editor | image code goes not in the message field

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5406]
#### Steps to reproduce the issue

Upload a image and click Insert

#### Expected result

Inserted code in the message field such as `[attachment=68]image.png[/attachment]`

#### Actual result

Only the Insert button will green

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: Kunena 5.1.0-ALPHA-DEV
Php version: 7.0.14 and 7.1.1
Database version:

**Comment by xillibit** [comment]
~~If i click on button insert, the code is right inserted in message field and the button insert goes green, i don't understand the issue~~ 

The issue appear with J! 3.7.2 but not in J!3.7.0

P.S. : now i'am not able anymore to reproduce the issue

**Comment by 810** [comment]
I have now changed the both editors textarea's to "#editor", so we can improve our js.
