### ISSUE TITLE
Wysiwyg Editor | Insert image in message needs 2 clicks

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5407]
#### Steps to reproduce the issue

1. Add a image
2. Click Insert (now the button is green)
3. You must click again at the green button "In Message"
#### System information (as much as possible)

Joomla version: 3.6.5 and 3.7.0-beta1
Kunena version: 5.1.0-ALPHA-DEV
Php version: 7.0.14 and 7.1.1
Database version:

**Comment by xillibit** [comment]
So, you mean that you an improved behaviour to avoid to click two times to the attachment in message ?

**Comment by 810** [comment]
The issue, is that you need to select outside the message box,then you will see the added image.

There should be a refresh

**Comment by rich20** [comment]
Yes, the Insert button is the only button which needs a double click.

**Comment by 810** [comment]
i have tried several fixes but it doesn't work.

The function is only working on Firefox.

**Comment by rich20** [comment]
https://www.kunena.org/forum/general-questions-and-how-tos/159846-inserting-pictures-doesn-t-work-properly
I've noticed, if you click on the button BBCODE before, it works correctly.
![path817](https://user-images.githubusercontent.com/888847/86381813-db11aa00-bc8d-11ea-9917-2b0d6f4e1e03.png)

**Comment by rich20** [comment]
Replaced by CKeditor
