### ISSUE TITLE
Two strings needs another definition

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5416]
#### Steps to reproduce the issue

Site com_kunena.templates ini lines 353 and 354
COM_KUNENA_TEMPLATE_DISPLAY_FONTAWESOME="Load External CDN Fontawesome"
COM_KUNENA_TEMPLATE_DISPLAY_FONTAWESOME_DESC="Load External CDN Fontawesome"

Should be so (or similar)
"Load External Icons Type"
and for desk
"Load External CDN Fontawesome Icons Type"

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
wait these strings should be corrected:

COM_KUNENA_A_TEMPLATE_MANAGER_TOPICICONS="Icon Type"
COM_KUNENA_A_TEMPLATE_MANAGER_TOPICICONS_DESC="Select the icon type"
