### ISSUE TITLE
Modal window - nothing happens when press Enter

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5417]
#### Steps to reproduce the issue

It seems, the Enter key is deactivated if is open the modal window. You can't insert the code with Enter key.

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.10  dev
Php version: 7.0.14 and 7.1.1
Browsers: Chromium, Firefox and Opera
Database version:

**Comment by 810** [comment]
Could you say where it isn't working, i checked editor these modals are working.

**Comment by rich20** [comment]
Example: Go to the editor and insert a URL in the modal. Then press Enter. The URL should be added in the text field now, but nothing happens.
Tested with Firefox, Chromium and Opera.

**Comment by sshcli** [comment]
It doesn't work either in 5.0
You need to click the add button

@810 I think @rich20 is talking about this modal:
<img width="777" alt="link" src="https://user-images.githubusercontent.com/12942731/35477627-9d44287a-039d-11e8-946f-0cd27f58083c.PNG">

@rich20 please correct me if I'm wrong

**Comment by rich20** [comment]
@sshcli  Yes I mean this modal. Originally I had marked it as bug for K 5.0.

**Comment by 810** [comment]
for me it is working

**Comment by rich20** [comment]
Yes, you're right. You must use after text insertion the tabulator key (it goes to the next option) and then press enter. So I close this issue.
