### ISSUE TITLE
The tooltip for the topic opener link shows last post author name instead

### ISSUE THREAD

**Issue by fabibio** [Kunena/Kunena-Forum#5420]
#### Steps to reproduce the issue
1) go to topic list for a choosen category
2) hover over the first post author name link (topic opener) just under the topic subject and wait for the tooltip to show up.

#### Expected result
The tooltip shows the first post author (topic opener)

#### Actual result
The tooltip shows the last post author name (the one also returned in the rightmost column).

#### System information (as much as possible)

Kunena version: 5.0.9
Template: Crypsis

Joomla version: 3.7.2
Php version:    7.1.5
Database version: MariaDB 10.1.23

**Comment by rich20** [comment]
Confirmed. But it's only the tooltip wrong, the link goes to the correctly profile.

![bildschirmfoto von 2017-06-07 17-57-40](https://user-images.githubusercontent.com/888847/26888820-772b4c94-4bac-11e7-8f53-173058492e45.png)
