### ISSUE TITLE
Email icon is not visible

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5421]
#### Steps to reproduce the issue
Line 146
src\components\com_kunena\template\crypsis\layouts\user\profile\default.php

#### Expected result
The email icon should be visible

#### Actual result
<img width="96" alt="email" src="https://user-images.githubusercontent.com/12942731/26912348-aff937ae-4be1-11e7-8c31-8128519cf6c4.PNG">

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.10-DEV
Php version: 7.1.5
Database version: MySQL 5.6.35

**Comment by xillibit** [comment]
It's works you need to enable show email into Kunena profil and into Kunena configuration

**Comment by sshcli** [comment]
It should be visible for admin even when hidden.
Also, it should respond to a click

**Comment by sshcli** [comment]
Like this one:
<img width="550" alt="email2" src="https://user-images.githubusercontent.com/12942731/26941890-1e67c91e-4c4e-11e7-930e-1312761daa0d.PNG">
