### ISSUE TITLE
The modal window reset the cursor

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5430]
#### Steps to reproduce the issue

https://www.kunena.org/forum/36-German/141211-position-beim-einf%C3%BCgen-von-links-und-bildern
1. Enter a word and press enter (now the cursor is on the next line)
2. Enter a link or image link with the modal

#### Expected result

The link should be in the next line

#### Actual result

The cursor goes back and the link is placed without blank space after the word

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.9
Php version:
Database version:

#### Additional comments

It doesn't always happen, but very often. Also on k.org

**Comment by xillibit** [comment]
This still exist with ckeditor ?

**Comment by rich20** [comment]
The CKeditor solves this issue.
