### ISSUE TITLE
Conflict between Joomla and Kunena Smart Search

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5434]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/141249-indexing-hangs-smart-search-plugin
Confirmed. If you enable the Kunena smart search plugin, hangs also the Joomla indexing.

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.9 and 5.0.10-dev
Php version: 7.0.14 and 7.1.1 and 7.1.4
Database version:

**Comment by 810** [comment]
we don't have getErrorNum anymore, so im closing this one.
3rt party code has still this code.
