### ISSUE TITLE
Confiuration | It should be a warning when image value is missing

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5436]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/141261-kunena-not-attaching-files-check-your-settings
1. Configuration -> Uploads
2. Let a value Height or Width emty (or both)
3. Try upload a image
 
#### Expected result

The second value should be adjusted automatically (in the right proportion)
Or you should get a warning

#### Actual result

The attachment button at the message box is inactive (you cannot add attachments)
You see the error only with the browser console (image)

![bildschirmfoto von 2017-06-21 15-25-41](https://user-images.githubusercontent.com/888847/27387853-29481ec8-569a-11e7-905a-801267123165.png)

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.9 and 5.0.10
Php version: 7.0.14
Database version:

**Comment by xillibit** [comment]
> The attachment button at the message box is inactive (you cannot add attachments)
> You see the error only with the browser console (image)

It's normal that you have these errors in javascript console because imageheight and imagewidth aren't defined here
