### ISSUE TITLE
SEO: Anchor Text is Missing

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5437]
#### Steps to reproduce the issue
1. Go to https://www.kunena.org/forum/index
2. With Google chrome, right click and view source code 

#### Expected result
It should have an anchor text. 
in this example, the anchor text should be: General Questions Archive

#### Actual result
The anchor text is missing.
Line 1218 
<a href="/forum/general-questions-archive"><i class="fa fa fa-folder fa-5 " alt="New Posts" aria-hidden="true"> </i></a>

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.10-DEV
Php version: 7.1.6
Database version: MySQL 5.6.35

#### Additional comments
Feed pages should also use anchor text:
https://example.com/category?format=feed

**Comment by 810** [comment]
i can see the anchor: General Questions Archive

**Comment by sshcli** [comment]
Hold on please, I will attach an screenshot

**Comment by sshcli** [comment]
There should be 2 anchor text, and there is only one:
<img width="326" alt="anchor" src="https://user-images.githubusercontent.com/12942731/27615743-6d434b60-5b78-11e7-81a9-29f6e9f14fc0.PNG">

**Comment by sshcli** [comment]
You can make an additional test with this online tool:
http://www.seoreviewtools.com/internal-link-analyzer/

**Comment by 810** [comment]
on the first ````<a>```` we have no text, because we only display the icon

**Comment by sshcli** [comment]
In that case the `<a>` tag should be removed and use a more appropriate element for this case.
Because we both know what's happening, but crawlers don't, they are expecting an anchor text.
