### ISSUE TITLE
Include youtube in profile Information

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5440]
#### Steps to reproduce the issue
Go to example.com/forum/profile/edit/id-username

#### Expected result
Youtube should be included in the profile information

#### Actual result
Youtube is not available in the profile information

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.10 -dev
Php version: 7.1.6
Database version: MySQL 5.6.35

**Comment by mc-hovanskiy** [comment]
Users are in demand in YouTube.
For Russian speakers ask to add Odnoklassniki (ok).

Icons:
![youtube-icon](https://user-images.githubusercontent.com/29813939/28009577-93a977c0-6564-11e7-9c7f-6adb2bfb0d2d.png) - youtube.png     ![odnoklassniki-icon](https://user-images.githubusercontent.com/29813939/28009588-9d5e38b4-6564-11e7-91a0-14625189ec35.png) -ok.png

Link YouTube: https://www.youtube.com/###
`' youtube ' => array ( ' url ' => ' https://www.youtube.com/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_YOUTUBE ' ), ' nourl ' => ' 0 ' ),`

Odnoklassniki: https://ok.ru/username
`'ok ' => array ( ' url ' => ' https://ok.ru/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_OK ' ), ' nourl ' => ' 0 ' ),`
