### ISSUE TITLE
Add support for twitter cards

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5445]
#### Steps to reproduce the issue
https://dev.twitter.com/cards/overview
https://dev.twitter.com/cards/types/summary-large-image
https://cards-dev.twitter.com/validator

#### Expected result
When sharing a link on twitter, an image should be loaded automatically.

#### Actual result
kunena does not have any meta tags for twitter 

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.10-dev
Php version: 7.1.6
Database version: MySQL 5.6.35

**Comment by 810** [comment]
This is working now on K5.1 right?

**Comment by sshcli** [comment]
No, is not added yet.
What has been added in K5.1 was the og:imge

But for this issue, what we need is to add these lines in  components/com_kunena/controller/topic/item/display.php  (Line 387 for K.5.0):
```
$doc->setMetaData('twitter:card', 'summary', 'name');
$doc->setMetaData('twitter:title', $this->topic->displayField('subject'), 'name');
$doc->setMetaData('twitter:description', 'A variable to show the description');	
```
