### ISSUE TITLE
Links in messages shows page title of target

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5446]
#### Steps to reproduce the issue

Enter a link such as:
`[url=https://www.kunena.org/forum/recent]test[/url]`

#### Expected result

In the message it should show my description "test"

#### Actual result

It shows the page title from source code
`Recent Topics - Forum - Kunena - To Speak! Next Generation Forum Component for Joomla`

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.1.0-Alpha-dev
Php version: 7.0.14 and 7.1.1
Database version:

**Comment by 810** [comment]
This is a new feature called, Smart Auto Linking

The setting is on the configurations: bbcode
