### ISSUE TITLE
Google icon does not have a link

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5456]
#### Steps to reproduce the issue
<img width="362" alt="capture" src="https://user-images.githubusercontent.com/12942731/27750231-e6f4f41c-5da4-11e7-95c3-7aa54ad32f8e.PNG">

#### Expected result
Should link to: https://plus.google.com/+username

#### Actual result
Does not have a link

#### System information (as much as possible)

Joomla version: 3.7.2
Kunena version: 5.0.10
Php version: 7.1.6
Database version: MySQL 5.6.35

**Comment by mc-hovanskiy** [comment]
and vk, skype, telegram

**Comment by xillibit** [comment]
> and vk, skype, telegram

Can-you give please an example for links to user for vk and telegram ?

**Comment by mc-hovanskiy** [comment]
VK  https://vk.com/username
telegram  https://t.me/username
