### ISSUE TITLE
Menu item Recent Posts - It show onlys the avatar of the topic starter

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5461]
#### Steps to reproduce the issue

Go in a user profile and you will see it.
It show always the avatar of the topic starter instead avatar from user which have at last posted.

This error exists only with Crypsis because this fix https://github.com/Kunena/Kunena-Forum/pull/5460 is not included in Crypsisb3.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
I will add too in crypsisB3

**Comment by rich20** [comment]
@810 
xillibit has only added the missing fix https://github.com/Kunena/Kunena-Forum/pull/5460 for Cripsyb3 
This bug "Menu item Recent Posts - It show onlys the avatar of the topic starter" still exists. This is a new bug.

Go in a user profile and you will see it.
It show always the avatar of the topic starter instead avatar from user which have at last posted.

**Comment by xillibit** [comment]
> This bug "Menu item Recent Posts - It show onlys the avatar of the topic starter" still exists. This is a new bug.
> 
> Go in a user profile and you will see it.
> It show always the avatar of the topic starter instead avatar from user which have at last posted.

I will look to it
