### ISSUE TITLE
Add posted prefix to unapproved / my topics (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5462]
#### Steps to reproduce the issue

It lacks this fix https://github.com/Kunena/Kunena-Forum/pull/5452 for Crypsisb3

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
OK, I think can do it without any problems.
I will take a look later
