### ISSUE TITLE
Double "e" in URL when use "ü"

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5470]
#### Steps to reproduce the issue
1. Create a new topic and put this word as subject: **bilingüe**
2. Go to the address bar and tale a look to the url

#### Expected result
example.com/category/id-biling**u**e

#### Actual result
example.com/category/id-biling**ue**e

#### System information (as much as possible)

Joomla version: 3.7.3
Kunena version: 5.0.10
Php version: 7.1.6
Database version: MySQL 5.6.35

**Comment by rich20** [comment]
Thats correctly. 
ä = ae
ö = oe
ü = ue
If you have üe = ue+e = uee

**Comment by sshcli** [comment]
> Thats correctly.

You mean that's correct,  we should keep it that way
or 
You mean that's correct,  I also can confirm this bug

**Comment by sshcli** [comment]
Because maybe it make sense in other languages, but not in Spanish.

**Comment by 810** [comment]
Joomla Global Configuration - SEO Settings - Unicode Aliases: Set to Yes

http://localhost/develop/forum/welcome-mat/34-bilingüe

else:
http://localhost/develop/forum/welcome-mat/35-bilinguee
