### ISSUE TITLE
Include whatsapp in profile Information

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5471]
#### Steps to reproduce the issue
Go to example.com/forum/profile/edit/id-username

#### Expected result
Whatsapp should be included in the profile information

#### Actual result
Whatsapp is not available in the profile information

#### System information (as much as possible)

Joomla version: 3.7.3
Kunena version: 5.0.10
Php version: 7.1.6
Database version: MySQL 5.6.35

**Comment by xillibit** [comment]
Do-you have an example of waht's app link profile ?

**Comment by sshcli** [comment]
no link, only show phone number

**Comment by sshcli** [comment]
Tested with: pkg_kunena_v5.1.0-ALPHA3-DEV_2017-07-18.zip
I got this fatal error:

```
The error was detected in the Kunena Component.

Fatal Error: Method KunenaLayout::__toString() must not throw an exception, caught Error: Call to undefined method KunenaUser::socialButton() in components/com_kunena/template/crypsis/layouts/user/item/summary/default.php on line 0
```

**Comment by sshcli** [comment]
Still pending:
1. Add COM_KUNENA_MYPROFILE_WHATSAPP_DESC
2. Add WhatsApp icon
3. WhatsApp Information is not being saved

**Comment by xillibit** [comment]
In my commit from yesterday i had added the missign string : COM_KUNENA_MYPROFILE_WHATSAPP_DESC, i will fix the two others things later today
