### ISSUE TITLE
RSS Feed type not working as expected

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5475]
#### Steps to reproduce the issue
1. Kunena Forum->Configuration->RSS->RSS Feed type = **By Topic**
2. Go to front end and reply a topic in category "Welcome Mat"
3. Go to example.com/welcome-mat?format=feed

#### Expected result
RSS should only show topics 

#### Actual result
RSS is showing posts 

#### System information (as much as possible)

Joomla version: 3.7.3
Kunena version: 5.0.10
Php version: 7.1.6
Database version: MySQL 5.6.35

#### Additional comments
There is no problem with the main rss (example.com/topics/mode-topics?format=feed)
The problem only occurs in rss for specific categories (example.com/welcome-mat?format=feed)

**Comment by sshcli** [comment]
This bug is causing a lot of problems, because there are several services that relies on rss.
I don't know how to fix it.
I will really appreciate your help here.
Thanks in advance

**Comment by xillibit** [comment]
I Will try to look

**Comment by sshcli** [comment]
> I Will try to look

Thanks @xillibit

**Comment by 810** [comment]
I can't reproduce this issue, for me its working.

Topics = i see 2 items
Posts = i see 3 items
Recent = i see 2 items

You can't refresh the site, its a different url, so if you use any sef component, then you need to exclude this url.

**Comment by sshcli** [comment]
> if you use any sef component, then you need to exclude this url.

No, I don't use any sef component (Testing environment joomla+kunena only)

> I can't reproduce this issue, for me its working.

What I'm reporting its only the message description, not the quantity of items.
<img width="280" alt="rsswrong" src="https://user-images.githubusercontent.com/12942731/28229805-37930d38-68b2-11e7-8a54-c2cdf9f2f231.PNG">

**Comment by sshcli** [comment]
> You can't refresh the site, its a different url, 

I don't understand what you mean. I'm not refreshing the page.
This url "**example.com/welcome-mat?format=feed**" is found in category index:
<img width="344" alt="secondversion" src="https://user-images.githubusercontent.com/12942731/28230570-8a717e42-68b5-11e7-8757-53170f38ce18.PNG">

**Comment by xillibit** [comment]
I have just tried when open the rss for a category, i can see 3 topics like in the category. In this catgory i have 5 posts

**Comment by rich20** [comment]
I think sshcli is right. There is no difference between **by Topic** and **by Recent Topics**

The descriptions in the backend are:
Topic - Show the latest topics from the forum (**topics only**).
Recent topics - **Show the latest post** from recently updated topics.

Both options show the latest post from updated topics.

**Comment by 810** [comment]
Please re test, because new fix added for rss.

**Comment by sshcli** [comment]
I have tested again,
Maybe something else has been fixed, but this issue is still present
