### ISSUE TITLE
Unapproved tab not available in crypsis

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5489]
#### Steps to reproduce the issue
1. UserX creates a new topic in a moderated category
2. ModeratorX try to see all unapproved messages from UserX 

#### Expected result
<img width="534" alt="be" src="https://user-images.githubusercontent.com/12942731/28631900-d0d4579c-71fc-11e7-9a85-9670d3539582.PNG">

#### Actual result
<img width="415" alt="crypsis" src="https://user-images.githubusercontent.com/12942731/28631905-d42eb32e-71fc-11e7-9bb1-52a9b73be468.PNG">

#### System information (as much as possible)

Joomla version: 3.7.4
Kunena version: 5.0.10
Php version: 7.1.7
Database version: MySQL 5.6.35

**Comment by rich20** [comment]
Is strange, I've this tab as moderator or admin only in my own profile. Not in another profile, neither with Crypsis nor with Blue Eagle.

**Comment by sshcli** [comment]
> Is strange, I've this tab as moderator or admin only in my own profile. Not in another profile

Exactly, it should be available for registered users too (You need it If you are a moderator trying to see all unapproved messages from an specific user)

> neither with Crypsis nor with Blue Eagle.

The blue eagle screenshot is from K.4, it means the unapproved tab was available in k.4

**Comment by 810** [comment]
Leave a comment
