### ISSUE TITLE
Error when using make_spectrogram

### ISSUE THREAD

**Issue by dotanrs** [Kunena/Kunena-Forum#5503]
#### Steps to reproduce the issue

Run the function with a recent numpy version

#### Expected result

a spectrogram should appear

#### Actual result

error:
TypeError: slice indices must be integers or None or have an __index__ method

#### Additional comments

This can be easily fixed by changing line 937 from
step = seg_length // 2
to
step = int(seg_length // 2)

(I'm new to open source and didn't know how to create a pull request, so I wrote it here)

**Comment by 810** [comment]
I think you have created an issue for the wrong software product, we don't have any make_spectrogram code.
