### ISSUE TITLE
Lazyload not working correctly

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5509]
#### Steps to reproduce the issue
enable lazyload

#### Expected result

not all images requests should be loaded

#### Actual result

All requests are loaded

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by JoshJourney** [comment]
As an enthusiast of LazyLoad I'm glad there is a PR for this.

**Comment by 810** [comment]
yes, but for some reason i don't get it to work. need to check it.

**Comment by JoshJourney** [comment]
I should have checked, works on my end. I use the plugin called "LLFJ - Lazy Load for Joomla" which seems to operate a little better in my opinion than other one's I've used in the past. Tested with default Joomla template and default Kunena theme.

**Comment by 810** [comment]
Closing this one, lazyload should be done by serviceworker, not by external plugin.
