### ISSUE TITLE
The preview remain empty with BBCode Editor (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5515]
I had accidentally tested this patch https://github.com/Kunena/Kunena-Forum/pull/5511 with Crypsisb3. Therefore I had marked it as "Success". Now I have noticed, that this patch is only for Crypsis. Therefore I have tested again it with Crypsis, and established that the bug still exists. This bug are only in Crypsis present, not in Crypsisb3.

Crypsisb3 includes this code, and with this code it works also with Crypsis.

`<input id="kpreview_url" type="hidden" name="kpreview_url" value="<?php echo KunenaRoute::_('index.php?option=com_kunena&view=topic&layout=edit&format=raw', false) ?>"/>`

Path:
/components/com_kunena/template/crypsis/layouts/topic/edit/default.php line 92

I'm sorry, it was my mistake.

**Comment by 810** [comment]
both fixes are working for me

**Comment by rich20** [comment]
I've tried now with 3 different browsers (Firefox, Chromium and Opera). For me it works only with this code.
