### ISSUE TITLE
Caching issue with opengraph and custom module

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5520]
#### Steps to reproduce the issue
1. create a custom module with prepare content = yes
2. insert code {ochopengraph} (for content plugin to add full opengraph tags
3. assign and publish module to a template position and set to display on all menu items
4. look at any page and verify that opengraph tags are added

#### Expected result
Opengraph tags should be added on all pages inclusive kunena pages

#### Actual result
Opengraph tags are added on all pages incl. kunena but when pressing F5 the opengrapgh tags on the kunena pages disappear (they stay present (as they should) on all other joomla pages).

This is only on the kunena pages.

When turning off Joomla caching in the global settings then it works correct

#### System information (as much as possible)

Joomla version: 3.7.5
Kunena version: latest
Php version: 7.0.22
Database version: 5.6.36-82.1-log 

#### Additional comments

This is a very strange issue. the opengraph tags only appear once, pressing F5 should display the same page but then from cache. As it turns out, the cached page does not have the opengraph info....
They reappear (once) when clearing the Joomla cache...

Please see me via email so I can provide you with the opengraph plugin so you can test and confirm yourself.

EDIT: I use {jssocials} in the same way (with custom module): that works correct also when fressing F5. It are only the metatags that seem to 'reset' to kunena values...

EDIT2: when logged in, caching is disabled then it directly shows the metatags again. when logging out, the tags are gone > page comes from cache...

**Comment by Ruud68** [comment]
Found a work-around: when configuring the custom module wit caching = off then it works.

Maybe that is a pointer in where the issue is. On all other components view there is no need to

**Comment by Ruud68** [comment]
Sorry for posting again :)
could it be that com_kunena caches only the content and not the complete (result) page (with the metatags?)

**Comment by 810** [comment]
we cache only our own things, see the cache page com_kunena stuff.

If you want to cache the module, then you need to add caching on your module.

**Comment by Ruud68** [comment]
Caching IS enabled on the module. Disabling caching fixed it (workaround).
If this is due to kunena not using Joomla caching, then there are potentially others who have an issue.
But I do not think it is a big issue since no one reported :)
