### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5528]
#### Actual result

<pre>{ &quot;type&quot;: 1, &quot;message&quot;: &quot;Method KunenaLayoutTopicList::__toString() must not throw an exception, caught Error: Call to a member function setDisplayedPages() on null&quot;, &quot;file&quot;: &quot;/home/kunena/public_html/libraries/kunena/view.php&quot;, &quot;line&quot;: 0 }</pre>

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Can-you fill the Joomla! version and the php version ?

**Comment by 810** [comment]
Latest version, Its on k.org
When i enable the joomla debug, the bug is gone, but when i disable the debug, everything on kunena isn't working. see chat.

**Comment by 810** [comment]
not seeing the error anymore closing it now.
