### ISSUE TITLE
Profile ring should be gray when offline

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5534]
#### Steps to reproduce the issue
Login and go to edit profile

#### Expected result
Profile ring should be gray when "Show online = No"

#### Actual result
Profile ring always has a status color, even when "Show online = No"
<img width="750" alt="color" src="https://user-images.githubusercontent.com/12942731/29991136-4cc28a66-8f50-11e7-9d9a-9d6d20effe19.PNG">

#### System information (as much as possible)

Joomla version: 3.7.5
Kunena version: 5.0.11-dev
Php version: 7.1.9
Database version: 5.6.37

**Comment by trailsnail** [comment]
@sshcli Can you check if this issue can be marked as closed? I am new to github and don't really know, if changes for this issue are merged too with PR  #5623.

**Comment by sshcli** [comment]
@trailsnail The problem is solved.
I'm closing this issue right now.
Regards,
