### ISSUE TITLE
wrong count total topics when pagination

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5540]
#### Steps to reproduce the issue
https://www.kunena.org/forum/k5-0-support/148863-recent-topics-time-period-not-working#195034

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by rich20** [comment]
Not sure whether it's a bug. Maybe it is only a different setting between General Configuration and menu item configuration (see the solution)
https://www.kunena.org/forum/k5-0-support-archive/148863-recent-topics-time-period-not-working#196283

**Comment by 810** [comment]
is now fixed by the pr from yesterday.
