### ISSUE TITLE
The recount statistics process takes too long

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5549]
#### Steps to reproduce the issue
1. Go to backend->components->kunena forum->tools->Recount Statistics
2. Select all options and press the green button "Recount Statistics"

#### Expected result
The recount statistics process should be faster.
If this process can't be optimized, please feel free to close this ticket.

#### Actual result
The recount statistics process takes too long

#### System information (as much as possible)

Joomla version: 3.7.5
Kunena version: 5.0.11
Php version: 7.1.9
Database version: 5.6.37

**Comment by 810** [comment]
i did already made some improvement for k5.0
