### ISSUE TITLE
Wrong behavior when admin add new avatar to user

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5551]
#### Steps to reproduce the issue
1. Log in as admin/moderator
2. Try to add a new avatar for a registered user.

#### Expected result
The admin/moderator should be able to add a new avatar for a registered user without any problem.

#### Actual result
After you upload a new avatar and press the save button, the new avatar is assigned to the admin/moderator and not to the registered user.

#### System information (as much as possible)

Joomla version: 3.7.5
Kunena version: 5.0.11 and 5.0.12-DEV 2017-09-12
Php version: 7.1.9
Database version: 5.6.37

**Comment by sshcli** [comment]
The switch account problem also occurs when modify another field (Not only avatar)

**Comment by rich20** [comment]
Confirmed it's a bug

**Comment by 810** [comment]
fixed
