### ISSUE TITLE
Own Avatar gallery will not load

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5565]
#### Steps to reproduce the issue

https://www.kunena.org/forum/36-German/149520-avatargalerie-sub-kategorien-werden-nicht-mehr-angezeigt (German language)
1. Create a folder for own avaters "media/kunena/avatars/avatar gallery/**own avatars** and add a avatar in this folder
2. Go in frontend to your profile and try to choose this avatar

#### Expected result

The avatar should be available

#### Actual result

If you switch to the new folder, the console shows 404 (not found)
Address is ; /forum/profile/galleryimages?format=raw&gallery_name=own%20avatar
If you go back to the default galery you get also 404 (not found)
Address is : /forum/profile/galleryimages?format=raw&gallery_name=

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

#### Additional comments

I think, it lacks the refresh if you switch between galleries

**Comment by xillibit** [comment]
It doesn't like the space in the name of directory

**Comment by rich20** [comment]
I've also tried without space

**Comment by 810** [comment]
the correct dir is: media\kunena\avatars\gallery\own

**Comment by 810** [comment]
Ok, the ajax is broken. You will get this error when refreshing dir.

Error: 404 This user does not exist.
