### ISSUE TITLE
Method KunenaLayout::__toString() must not throw an exception

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#5568]
#### Steps to reproduce the issue

When you have an issue, it display this kind of fatal error : 

Fatal Error: Method KunenaLayout::__toString() must not throw an exception, caught Error: Call to a member function isImage() on null in components/com_kunena/template/blue_eagle5/layouts/topic/item/message/default.php on line 0

The method __toString() has already a try/catch : https://github.com/Kunena/Kunena-Forum/blob/K5.0/src/libraries/kunena/layout/base.php#L87 which return a string

#### Expected result

It's hard to debug because it doesn't show the line, it says just line 0 and it show the wrong file

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version: 7.x
Database version:

#### Additional comments

@mahagr : do-you any idea on this ?

**Comment by mahagr** [comment]
Please try to catch the following in addition to the Exception (which you still need for PHP5):

    catch (Throwable $t)

Not sure if you can write it in PHP5, so please try it in PHP5 and report back to me. :)

**Comment by 810** [comment]
also try:
go to "libraries/src/Exception/ExceptionHandler.php". After line 151/152 `if ($isException) {` then add afterwards add

print_r($e->getTrace());


Also debug will help

**Comment by 810** [comment]
I have just started with creating blue eagle 5 for K5.1. (new branch K5.1 on gitlab)
I haven't got this error. Where did you get that error?

**Comment by xillibit** [comment]
From a french user which uses blue eagle 5 in version 1.0.4

**Comment by 810** [comment]
ok so no k5.1 just k5.0

**Comment by xillibit** [comment]
Yes, i had put this error message just for the example, i can give you details later on skype

**Comment by rich20** [comment]
> I have just started with creating blue eagle 5 for K5.1. (new branch K5.1 on gitlab)
I haven't got this error. Where did you get that error?

You get this error, if you want to open a topic where rating is allowed.

**Comment by xillibit** [comment]
> Please try to catch the following in addition to the Exception (which you still need for PHP5):
> 
> catch (Throwable $t)
> 
> Not sure if you can write it in PHP5, so please try it in PHP5 and report back to me. :)

@mahagr : Tried both on php 5.6.19 and php 7.0.x, it works

**Comment by mahagr** [comment]
The new exception gets thrown only if you have badly written code (missing function call etc) which previously was a fatal error in PHP5. So it shouldn't really be an issue unless compiling PHP code fails. Though it can happen also if you change API and someone is trying to use old plugin that relays on that API.

**Comment by 810** [comment]
Leave a comment
