### ISSUE TITLE
Topic template won't load when switch category

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5573]
#### Steps to reproduce the issue
1. Backend->categories->Edit CategoryX->Category Name and Description->Topic Template = TestX
2. Backend->categories->Edit CategoryY->Category Name and Description->Topic Template = TestY
3. Try to create a topic in CategoryX and do not click the submit button
4. Try to switch to CategoryY

#### Expected result
The topic template from "CategoryY" should be inserted automatically in the textarea after click the "Replace" button.

#### Actual result
The topic template from "CategoryY" is not being inserted automatically in the textarea after click the "Replace" button.
In order to load the topic template for "CategoryY", you need to make a click in the category dropdown list.

#### System information (as much as possible)

Joomla version: 3.8
Kunena version: 5.1.0-ALPHA4-DEV
Php version: 7.1.9
Database version: MySQL 5.6.37

**Comment by rich20** [comment]
- [ ] **Replace content** adds only additional the new template content 
- [ ] **Replace content and keep existing** the content will doubled and it adds additional the content from the template
### Force users to pickup a category
- [ ] If exists, it shows always the template from the first main category (you must remove the content manually, if you choose another category)

**Comment by 810** [comment]
try again, should be fixed now

**Comment by sshcli** [comment]
Yes, it works. Now only need to improve language strings in modal

**Comment by 810** [comment]
whats wrong with the string?

**Comment by sshcli** [comment]
it's not optimized for the end user.
But this issue can be closed now, and we can check strings later., not a priority.
