### ISSUE TITLE
The Cancel button on Report Configuration generated only a page refresh

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5578]
#### Steps to reproduce the issue

Go to Kunena -> Tools -> Report Configuration
Click on Cancel

#### Expected result

It goes back to Tools

#### Actual result

It's only a refresh at the same site

#### System information (as much as possible)

Joomla version: 3.8.0 and 3.8.1-dev
Kunena version: 5.0.12-DEV
Php version: 7.0.20 and 7.1.6
Database version:

**Comment by sshcli** [comment]
Confirmed, it's a bug
