### ISSUE TITLE
Ordering disappears after toggle between site and administrator

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5579]
#### Steps to reproduce the issue
1. Backend->Menus->Kunena menu->Select "Administrator" from the Dropdown list
2. Backend->Menus->Kunena menu->Select "Site" from the Dropdown list
3. Now try to use the ordering arrows (aka sort by this column)

#### Expected result
<img width="388" alt="good" src="https://user-images.githubusercontent.com/12942731/30722852-59ae7cb0-9f01-11e7-8418-d5840b32b4bd.PNG">

#### Actual result
<img width="364" alt="bad" src="https://user-images.githubusercontent.com/12942731/30722855-5e0fb7a6-9f01-11e7-8a4c-2cb355f50bde.PNG">

#### System information (as much as possible)

Joomla version: 3.8
Kunena version: 5.0.11 and 5.0.12-DEV and 5.1.0-ALPHA4-DEV
Php version: 7.1.9
Database version: MySQL 5.6.37

**Comment by rich20** [comment]
That's with all joomla menus. If you switch from Site to Administrator (or conversely) you must select yor wanted menu (second drop down menu on right "Select Menu").

**Comment by sshcli** [comment]
You are right, it's a Joomla thing.
I'm closing this one
