### ISSUE TITLE
Ebay widget not working

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5591]
#### Steps to reproduce the issue

https://www.kunena.org/forum/k5-0-support/149633-ebay-widget-not-working
I know, that only bb codes without other content is not possible. But it seems, that all previously existing ebay widgets also not work anymore.
Unfortunately, I can't test it because I don't have any existing ebay widgets.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
is working correct for me, its a local server?? issue.
