### ISSUE TITLE
email error on Joomla 3.8

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5592]
#### Steps to reproduce the issue
1. create a reply to a topic

#### Expected result
mail should be sent to subscribed users

#### Actual result
```
0
Argument 1 passed to KunenaForumMessage::attachEmailBody() must be an instance of JMail, instance of Joomla\CMS\Mail\Mail given, called in /home/.../public_html/.../libraries/kunena/forum/message/message.php on line 408
It appears the page you were looking for doesn't exist. Sorry about that.
```

#### System information (as much as possible)

Joomla version: 3.8.0
Kunena version: 5.0.11
Php version: 7.0.23
Database version: 5.6.36-82.1-log

#### Additional comments
Message is created, but mail is not sent

**Comment by sshcli** [comment]
I think there is a temp fix here:
https://www.kunena.org/forum/k5-0-support/149533-posting-error#195777

**Comment by Ruud68** [comment]
unfortunately, there are more things that need fixing:

I changed line (1581, confirm kunena forum post from @810 )
```
0
Argument 1 passed to KunenaEmail::send() must be an instance of JMail, instance of Joomla\CMS\Mail\Mail given, called in /home/.../public_html/....nl/libraries/kunena/forum/message/message.php on line 409
It appears the page you were looking for doesn't exist. Sorry about that.
```

**Comment by xillibit** [comment]
Try to change at line 24 in file /libraries/kunena/email/email.php the 

```public static function send(JMail $mail, array $receivers)```

by

```public static function send(Joomla\CMS\Mail\Mail $mail, array $receivers)```

**Comment by Ruud68** [comment]
Top @xillibit this fixes the issue :)
btw. it IS confirmed as other users are also facing this issue: https://www.kunena.org/forum/k5-0-support/149533-posting-error

I haven't tested the two fixes on other Joomla versions (e.g. 3.7) so not sure if this will break B/C

**Comment by xillibit** [comment]
i think the fix will work only on J!3.8+

**Comment by rich20** [comment]
> i think the fix will work only on J!3.8+

You're right. I've tested it with Joomla 3.7.0 & php 7.0.20. You get this error. 

0 Argument 1 passed to KunenaEmail::send() must be an instance of Joomla\CMS\Mail\Mail, instance of JMail given, called in .../libraries/kunena/forum/message/message.php on line 409

**Comment by Ruud68** [comment]
Makes me wonder why the $mail is casted with Joomla\CMS\Mail\Mail or Jmail in the methods.

I can understand type casting as a means of e.g. security when there is user input that you cannot fully control, but in this case these methods are called from kunena itself so the passed $mail variable is always of the correct type.
or am I missing something?

**Comment by xillibit** [comment]
I will add the fix into K5.1 for now

**Comment by Ruud68** [comment]
Just did some testing on my test site where I didn't get the error message, but where it turned out that the emails (although no error) where NOT sent...

When omitting the type casting in the methods, everything works correct

when I do a
```
var_dump($mail)
```
I get
```
object(Joomla\CMS\Mail\Mail)
```
So the solution for all versions (3.7 and 3.8) should be to omit the type casting:
(I have tested this successful on my test environment)
```
public static function send($mail, array $receivers)
protected function attachEmailBody($mail, $subscription, $subject, $url, $once)
```

if somebody can test on Joomla! 3.7 (and 3.8)

**Comment by rich20** [comment]
@Ruud68 
You mean replace line 24 ?
from:
`public static function send(JMail $mail, array $receivers)`
to
`public static function send($mail, array $receivers)`
`protected function attachEmailBody($mail, $subscription, $subject, $url, $once)`

then I get this error with J3.8

0 syntax error, unexpected 'protected' (T_PROTECTED), expecting ';' or '{'

**Comment by Ruud68** [comment]
no, sorry for being unclear.
There are two references in the Kunena Libraries:
1. in ./libraries/kunena/email/email.php
change line 24 into:
```
public static function send($mail, array $receivers)
```
2. in ./libraries/kunena/forum/message/message.php
change line 1581 into
```
protected function attachEmailBody($mail, $subscription, $subject, $url, $once)
```

**Comment by rich20** [comment]
My test results:

- [x] tried with J 3.7 - sending mail without error
- [x] upgraded to Joomla 3.8 - sending mail without error

But I had also earlier not a mail error

**Comment by Ruud68** [comment]
Top, so the fix (for anyone having this issue) is to change the two files: email.php and message.php (drop the type casting).
I am also not sure why this is happening and why I sometimes get the error message and sometimes not.
Maybe provider setup related? (I am on siteground)

anyway if the type casting is unnecessary then this is an improvement regardless of having an issue or not :)

**Comment by xillibit** [comment]
i will remove the cast for now in 5.0

**Comment by Ruud68** [comment]
Question remains why casting was there in the first place...

**Comment by xillibit** [comment]
when you create a function you should set the type for parameters of method, in this case it's not casting
