### ISSUE TITLE
It lacks two language strings in en-GB.com_kunena.templates.ini

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5604]
#### Steps to reproduce the issue

The following both strings should be included between line 372 and 373 https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/components/com_kunena/language/en-GB/en-GB.com_kunena.templates.ini#L372
COM_KUNENA_TEMPLATE_DISPLAY_OPTIONAL_USERNAME
COM_KUNENA_TEMPLATE_DISPLAY_OPTIONAL_USERNAME_DESC
It's for the template setting -> Feature -> Show Name or Username

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
This feature is not available yet.
We need the feature first, before add label and description
