### ISSUE TITLE
Some fields are not responsive

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5606]
#### Steps to reproduce the issue
Go to example.com/forum/profile/edit/id-username

#### Expected result
<img width="301" alt="good" src="https://user-images.githubusercontent.com/12942731/31063366-5aeeaabc-a700-11e7-9c62-e6df6a7a5c9b.PNG">

#### Actual result
<img width="242" alt="bad" src="https://user-images.githubusercontent.com/12942731/31063420-af0c75d4-a700-11e7-97a4-907a93c079cb.PNG">

#### System information (as much as possible)

Joomla version: 3.8
Kunena version: 5.0.11
Php version: 7.1.9
Database version: MySQL 5.6.37

**Comment by trailsnail** [comment]
I will have a look on this

**Comment by 810** [comment]
This is a joomla template issue, closing this one.
