### ISSUE TITLE
Feature: Add position for each user

### ISSUE THREAD

**Issue by Shtier** [Kunena/Kunena-Forum#5621]
com_kunena\template\NAME_TEMPLATE\layouts\user\profile\default.php

There is a position
`'kunena_profile_default'`

You can add more
`'kunena_profile_default _'. $ user-> userid);`

**Comment by Sulpher** [comment]
Such approach will allow generating unique content for various users instead of the same module. 
I hope to see this PR in the upcoming version of the forum.
