### ISSUE TITLE
Some buttons are missing in category view

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5635]
#### Steps to reproduce the issue

This 3 buttons should be available in category view (image). But it seems, the buttons will displayed not at all categories.
![bildschirmfoto von 2017-11-22 20-13-04](https://user-images.githubusercontent.com/888847/33146142-66c61fb4-cfc3-11e7-9943-ad814b9e2847.png)
Example:
Here is only the New Topic button
https://www.kunena.org/forum/general-user-contributions
Here is only the Subscribe button
https://www.kunena.org/forum/customising-kunena
I'm not sure if it's a general problem or only at k.org

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
if you have access to write then new topic will be showed, but when you allow only in sub, like on k.org then you haven't got permission to write.

And subscribe is only showed if you are not subscribes already. there is no unscribe button

**Comment by rich20** [comment]
> And subscribe is only showed if you are not subscribes already. there is no unscribe button

If you have subscribed then you get the unsubbscribe button (image from k.org)
![bildschirmfoto von 2017-11-24 20-08-57](https://user-images.githubusercontent.com/888847/33221964-e646f880-d153-11e7-9987-cee404b936e3.png)

But that's why I did not report it. I've few times noticed in some categories that are unread messages in it. But I can't find this unread messages and also not mark as read. I must marked the complete forum as read to remove this newchar.

We can close this issue and I will further to observe it. If no other user have this problem on his forum, then it's not important and can stay closed.
