### ISSUE TITLE
Editor | The poll symbol is available in all categories

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5652]
#### Steps to reproduce the issue

1. Open the category Welcome Mat and click on new topic
2. Click on the poll symbol and the modal opens
You can create a poll but this poll will not shown (when it's not allowed in this category)

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by 810** [comment]
duplicated issue, closing this one

**Comment by rich20** [comment]
After this fix https://github.com/Kunena/Kunena-Forum/issues/5752 the bug is back again.

**Comment by 810** [comment]
Leave a comment
