### ISSUE TITLE
can't create announcements 

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5658]
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Can-you precise the issue ?

**Comment by 810** [comment]
when save a new announcement, you will see the message that is saved, but i can't see the announcements anywhere.

after the save you will be redirected to a 404 Not Found error, and the message its saved

**Comment by sshcli** [comment]
I see this 404 error  just after create one:
<img width="455" alt="seethis" src="https://user-images.githubusercontent.com/12942731/33504458-e8bca99c-d6bd-11e7-9e78-a2d05bc09e01.PNG">
