### ISSUE TITLE
Deleted topic should be linkeable (Backend)

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5660]
#### Steps to reproduce the issue
backend->kunena forum->trashbin

#### Expected result
Deleted topic should be linkeable

#### Actual result
<img width="930" alt="link" src="https://user-images.githubusercontent.com/12942731/33490773-934ededc-d68e-11e7-88a8-e00629347002.PNG">

#### System information (as much as possible)

Joomla version: 3.8.2
Kunena version: 5.0.12 and 5.1
Php version: 7.1.12
Database version: MySQL 5.6.38

**Comment by xillibit** [comment]
What do-you by linkeable ? It should open the topic in frontend ?

**Comment by sshcli** [comment]
> It should open the topic in frontend ?

Exactly
