### ISSUE TITLE
Hide subscribe checkbox on edit

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5663]
#### Steps to reproduce the issue
1. Edit an existing topic from any user

#### Expected result
The subscribe checkbox should be hidden when editing because it doesn't make sense to be there.
<img width="462" alt="edit2" src="https://user-images.githubusercontent.com/12942731/33505545-16925a48-d6c2-11e7-9aa5-e120b414bb56.PNG">

#### Actual result
The subscribe checkbox is always visible

<img width="468" alt="edit" src="https://user-images.githubusercontent.com/12942731/33505549-1bce9bf2-d6c2-11e7-9f80-b121083a7fc5.PNG">

#### System information (as much as possible)

Joomla version: 3.8.2
Kunena version: 5.0.12
Php version: 7.1.12
Database version: MySQL 5.6.38

**Comment by sshcli** [comment]
Sorry, but I have changed the title and description because I just notice that the subscribe checkbox doesn't work on edit at all, it's not only admin/mod, it doesn't work for anyone.

So, the fix should be hide it for everyone on edit view.

Sorry again for any inconvenience caused

**Comment by 810** [comment]
Leave a comment
