### ISSUE TITLE
cancel button in edit form not working correct

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5677]
#### Steps to reproduce the issue
1. login to kunena forum
2. select the [Edit]  button to edit a post
3. switch between the preview and write tab multiple times
4. press the cancel button

#### Expected result
pressing the cancel button should cancel the writing / editing of the message

#### Actual result
The button has to be pressed multiple times (as many times as you switched between the tab write / preview?) to finally cancel the writing / editing

#### System information (as much as possible)

Joomla version: 3.8.2
Kunena version: 5.0.12
Php version: 7.1.12
Database version: 5.7.20

**Comment by sshcli** [comment]
I can't reproduce this issue

**Comment by Ruud68** [comment]
hi @sshcli thanks for trying.
What I see is that every click on a tab is 'recorded' as a new visited page in the browser's history (see image).
The cancel button does a 'window.history.back' so it makes sense that it needs to be pressed 4 times (in example) to finally come back to the actual previous page.

Why on my sites (multiple, also multiple templates) this pressing tab is recorded as a page load in the browser history and on e.g. the Kunena forum it is not, beats me... I really have no clue as to where to look for this :(

**Comment by Ruud68** [comment]
and just after posting the previous comment it hit me :)
The cullprit is in the Gavick template framework: gk.scripts.js
This script checks for clicks on tabs with '#' and if clicked, it does a smooth scroll etc. By doing so it sets the browser history.
So what I have done is changed the script to check if we are on a  kunena page  (div id="kunena") and if so, skip this part of the gk.scripts.js

Posting here so if somebody encounters the same issue they have a clue as to where to find the solution :)
