### ISSUE TITLE
User can't edit his first message when replies are not allowed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5704]
#### Steps to reproduce the issue

https://www.kunena.org/forum/general-questions-and-how-tos/150300-category-where-user-can-post-and-edit-post-but-no-one-can-reply

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by Sophist-UK** [comment]
It may be that the user actually has permissions to edit their topic, but it is simply not being displayed in a dropdown button option.

**Comment by rich20** [comment]
> It may be that the user actually has permissions to edit their topic, but it is simply not being displayed in a dropdown button option.

Yes, you're right, I've tested it. The permission is ok, only it lacks the button.

**Comment by Sophist-UK** [comment]
That was my experience - if you know the URL then you can edit it. Hence the comment. But I am a newcomer to the Kunena code base and am not quite sure what is going on under the covers.

**Comment by Sophist-UK** [comment]
I have just installed K5.1.0 RC1 and this functionality is NOT working as I would expect.

Having removed myself and another user as moderators (of any form) and cleared the Kunena cache we are both still able to edit and reply to any post in a category where users are supposed to only be able to post and not reply.

Not sure whether this is just my environment or something I have done wrong or a bug in this code.

**Comment by Sophist-UK** [comment]
With some Global configuration options untweaked on our site, this functionality is working as expected.
