### ISSUE TITLE
message unread feature

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5714]
#### Steps to reproduce the issue
We have only a topic unread feature, we should also having a message unread feature.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
if possible, add a new button or option to "mark as unread" 
Like the behavior on email clients, sometimes you need to "Mark as unread" to not forget read the message/topic later.

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/commit/2043e3fd8741c87fea53b5dff17ba542cff5fe41

**Comment by 810** [comment]
duplicated issue, closing this one
