### ISSUE TITLE
Attachment reference is not being deleted

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5716]
#### Steps to reproduce the issue
1. Create a topic and attach a file
2. Click the "insert" button, to insert the attachment reference in the text area
3. Go to attachment manager in frontend and delete the file from there

#### Expected result
The attachment reference inserted in the text area should be also deleted automatically.
Just like it does when you delete the file while editing the topic.

#### Actual result
The attachment reference stays intact, showing the error message" Attachment not found"

#### System information (as much as possible)

Joomla version: 3.8.3
Kunena version:  5.1.0-RC1 and 5.0.13
Php version: 7.1.13
Database version: MySQL 5.6.38

**Comment by xillibit** [comment]
I'am not sure if it will possible to do that, to avoid the message "Attachment not found" we need to edit the content of message and removing the right reference

**Comment by sshcli** [comment]
Ok,
I have created this issue because I saw it was possible to remove it automatically when you delete the attachment while editing a topic.

But that's ok if this can't be done.
Please feel free to close this issue if this definitively not gonna happen

**Comment by xillibit** [comment]
> Kunena version: 3.8.3

That's an old Kunena version 😄

**Comment by sshcli** [comment]
> That's an old Kunena version 😄

Edited: Thanks!

**Comment by rich20** [comment]
**Editor**
- [x] Attachments which have been inserted one by one can be removed one by one
- [ ] The button "Remove all" removes nothing
- [ ] Attachments which have been inserted with the button "Insert all" all will be removed if you want only remove a single attachment

**Frontend attachment manager**
- [x] Images which have been inserted one by one will be removed correctly when text is in the message too
- [ ] Images which have been inserted one by one will be removed but when no text is in the message, one of this code remains
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but the code remains in the message

**Backend file manager**
- [ ] The code always remains in the message

**Comment by rich20** [comment]
**Editor**
- [x] Attachments which have been inserted one by one can be removed one by one
- [ ] The button "Remove all" removes the attachments only from the attachment form but not from the text field. After submitting the attachments are present in the message.
- [ ] Attachments which have been inserted with the button "Insert all" all will be removed from the text field if you want only remove a single attachment. You must to insert again the remained attachments (see image).  You see, the text field is empty, but the attachment form shows "In Message"
![Bildschirmfoto von 2019-12-31 15-56-56](https://user-images.githubusercontent.com/888847/71625639-34b6f000-2be9-11ea-893e-160582394450.png)


**Frontend attachment manager**
- [x] Images which have been inserted one by one will be removed correctly when text is in the message too
- [ ] Images which have been inserted one by one will be removed but when no text is in the message, one of this code remains
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but the code remains in the message

**Backend file manager**
- [x] Images which have been inserted one by one will be removed correctly when text is in the message too
- [ ] Images which have been inserted one by one will be removed but when no text is in the message, one of this code remains
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but the code remains in the message

**Comment by rich20** [comment]
**Editor**
- [x] Attachments which have been inserted one by one can be removed one by one
- [x] The button "Remove all" removes the attachments only from the attachment form but not from the text field. After submitting the attachments are present in the message.
- [ ] Attachments which have been inserted with the button "Insert all" all will be removed from the text field if you want only remove a single attachment. You must to insert again the remained attachments.  The text field is empty, but the attachment form shows "In Message"

**Frontend attachment manager**
- [x] Images which have been inserted one by one will be removed correctly when text is in the message too
- [**?**] Images which have been inserted one by one will be removed **but when no text is in the message,** one of this code remains
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but all codes remain in the message

**Backend file manager**
- [x] Images which have been inserted one by one will be removed correctly when text is in the message too
- **[?]** Images which have been inserted one by one will be removed **but when no text is in the message,** one of this code remains
- [ ] Attachments which have been inserted with the button "Insert all" will be removed but all codes remain in the message

**Additional context**
- **[?]** For me are these two extra marked issues not necessarily a bug. When a message has no text and all images has been removed is indifferent if remain either the code or an empty message.
So remain only the question, why the codes of attachments always remain (also when there are text in the message) when they have been inserted with the button "Insert all".
