### ISSUE TITLE
Changes in category permissions will not correctly saved

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5721]
#### Steps to reproduce the issue

Example: 
Choose user groups
Change the category permission from public to registered (or choose more options) and save it

#### Expected result

the permission should be saved

#### Actual result

The new setting will saved only in the backend, but not the permission itself. The permission remain the same as you had before upgrade to Kunena 5.1 RC2

#### System information (as much as possible)

Joomla version: 3.8.3 and 3.8.4-dev
Kunena version: 5.1 RC2
Php version: 7.0.25 and 7.1.11
Database version:

**Comment by 810** [comment]
for me its ok,

**Comment by rich20** [comment]
> Quote from the backend: "You can disable secondary group by setting it to have the same value as Primary User Group."

Example: 
Primary User Group: = Registered
Secondary User Group: = Registered
Primary Includes Child Groups = Yes
Secondary Includes Child Groups: Yes
- [ ] Public can see the category

Primary User Group: = Registered
Secondary User Group: = Registered
Primary Includes Child Groups = No
Secondary Includes Child Groups: No
- [ ] Registered can't see the category

**Comment by 810** [comment]
i have reverted the change, please look again

**Comment by rich20** [comment]
- [x] works again
