### ISSUE TITLE
Joomla content plugins not triggered (5.1 RC2)

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5722]
#### Steps to reproduce the issue
1. enable (if not already) system plugin - kunena
2. set in plugin 'Joomla Content Plugin Support' = Yes
3. select all values in 'Run plugins on'
4. modify a content plugin to var_dump($context)

#### Expected result
On Kunena Forum pages $context variable must be dumped

#### Actual result
$context variable is NOT dumped > the content plugin is NOT triggered

#### System information (as much as possible)

Joomla version: 3.8.3
Kunena version: 5.1 RC2
Php version: 7.1
Database version:

**Comment by 810** [comment]
try now

**Comment by Ruud68** [comment]
Top, that was my original approach isn't it? anyway,
there are two 'challenges':

- The recent view can have two different view names
- The topic and new topic view have the same view name

So the $context to trigger the content plugins for kunena are are:
**recent** (home)> com_kunena.**home**
**recent** > com_kunena.**topics**
index > com_kunena.category
**topic** > com_kunena.**topic**
**new topic** > com_kunena.**topic**
search > com_kunena.search

**Comment by 810** [comment]
You need to use the layout names.
`$layout = $this->input->get('layout');`

**Comment by Ruud68** [comment]
Okay, that resolves to:
recent (home)> com_kunena.home | layout = default
recent > com_kunena.topics | layout = default
index > com_kunena.category | layout = list
topic > com_kunena.topic | layout = default
new topic > com_kunena.topic | layout = create
search > com_kunena.search | layout = default

So targetting the recent view would in the above case mean:
if layout = default AND (view != search AND view != topic)

not optimal, but doable I guess

A way around this is to make 'home' a layout instead of a view, as home does not have an actual view (it is the view of the view selected as home)

**Comment by 810** [comment]
we are using hmvc not mvc.
