### ISSUE TITLE
Change icon to subscribe button

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5726]
#### Expected result
<img width="239" alt="goodicon" src="https://user-images.githubusercontent.com/12942731/35648013-c03c1c88-06aa-11e8-8b7b-11080d731f5c.PNG">

#### Actual result
<img width="254" alt="badicon" src="https://user-images.githubusercontent.com/12942731/35648044-d3c65106-06aa-11e8-876a-bdf371f234e2.PNG">

#### System information (as much as possible)

Joomla version: 3.8.3
Kunena version: 5.0.13 and 5.1.0.RC3
Php version: 7.1.13
Database version: MySQL 5.6.38

#### Additional comments
Because the subscription method used in kunena is via email, the icon should be related to email (e.g email, envelope, letter, etc.)

**Comment by rich20** [comment]
I've tested it now. It should be the same icon also for category subscription.

**Comment by 810** [comment]
i just added it also

**Comment by rich20** [comment]
Sorry, it was my mistake
