### ISSUE TITLE
Two Factor Authentication setting should be available in Kunena profile edit

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5736]
#### Steps to reproduce the issue

If this Joomla plugin is enabled, it's only the enter field enabled in Kunena. So the user can't request the code from Google or YubiKey. He need access to the Joomla user profile for this setting.

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
> If this Joomla plugin is enabled, it's only the enter field enabled in Kunena.

I don't understand this part

**Comment by 810** [comment]
its missing the 2fa options, to enable or disable and adding the keys on the kunena edit page.

There is no easy way to load the user settings for 2fa. Now we need to do it ourself.

**Comment by rich20** [comment]
>There is no easy way to load the user settings for 2fa. 

At the moment it is only possible via the Joomla User Edit menu item.

![bildschirmfoto von 2018-03-04 16-09-56](https://user-images.githubusercontent.com/888847/36947086-96ca85f2-1fc7-11e8-998f-5c8811846318.png)

**Comment by 810** [comment]
Temp fix. ^^

**Comment by rich20** [comment]
Yes it works. It goes in the Joomla profile now.
