### ISSUE TITLE
Possible Cross-Site Request Forgery vulnerability

### ISSUE THREAD

**Issue by James-OHara** [Kunena/Kunena-Forum#5737]
#### Steps to reproduce the issue
For a joomla website using kunena-forum navigate to [baseurl]/forum. This is the recent topics view that includes the dropdown form timeselect for selecting the time period to show recent topics from.  

#### Expected result
This form has an anti-csrf token that is included in the form submission and authenticates the token is correct before processing the request.

#### Actual result
This form does not appear to have an anti-csrf token and could be tricking users into accessing a website hosted by the attacker, or clicking a malicious url. More information:
 https://www.acunetix.com/websitesecurity/csrf-attacks/
https://www.owasp.org/index.php/Cross-Site_Request_Forgery
http://www.cgisecurity.com/csrf-faq.html

#### System information (as much as possible)

Joomla version: 3.8.5
Kunena version: 5.0.13
Php version: 7.2
Database version: N/A

**Comment by 810** [comment]
Please use the email: security@kunena.org for security issues.
