### ISSUE TITLE
Deleted topic inks in the trash to work only when Direct Component Access is allowed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5745]
#### Steps to reproduce the issue

When Direct Component Access is No, you get the error 404 Component not found

#### System information (as much as possible)

Joomla version: 3.8.5
Kunena version: 5.1.0-RC4-DEV
Php version: 7.0.25 and 7.1.11
Database version:

**Comment by 810** [comment]
Could you add more details, i can't reproduce this issue.

I got set direct to "No"
Then i go to trashed item, and i still i can view the topic.

**Comment by sshcli** [comment]
The bug is real, I can confirm it.
The URL is the same for both (With and without Direct Component Access enabled)

URL format:
example.com/index.php?option=com_kunena&view=topic&catid=2&id=11&mesid=17

**Comment by rich20** [comment]
> The URL is the same for both (With and without Direct Component Access enabled)

Yes, this is correct, in the backend it shows the same URL, but with allowed direct component access there is a redirect, and the second link works.
Example
URL will redirected from
/index.php?option=com_kunena&view=topic&catid=2&id=53&mesid=151
to
/index.php?option=com_kunena&view=topic&catid=2&id=53&Itemid=3809

When is set Direct Component Access = No, it shows the first address with Error 404
