### ISSUE TITLE
BBcode: Image with link not working 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5755]
#### Steps to reproduce the issue
1. Create a new topic and insert this in the content:
`[url=https://example.com][img]https://www.google.org/assets/static/images/homepage/pratham-books-2x-2bf3b580cbb10c21b3b5bb43864f5a3b.jpg[/img][/url]`

#### Expected result
When click the image, a new browser window must be opened with the page example.com
The combination of [url][img][/img][/url] should work in the same way as it was in K.5.0.x and K.4.0.x

#### Actual result
When click the image, it will open the image in a Lightbox.

#### System information (as much as possible)

Joomla version: 3.8.5
Kunena version: 5.1.0-RC4-DEV
Php version: 7.1.14
Database version: MySQL 5.6.38

**Comment by sshcli** [comment]
This problem is caused by a conflict with lazyload

**Comment by rich20** [comment]
- [x] Success
