### ISSUE TITLE
Confirmation modal should not popup when content is empty

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5756]
#### Steps to reproduce the issue
1. Backend-> Define a topic template for "Suggestion Box" Category
2. Frontend-> Go to example.com/forum/newtopic
3. Switch from "Welcome Mat" to "Suggestion Box"

#### Expected result
Confirmation modal should not popup if the text area is empty or a topic template is not defined in "Welcome Mat"

#### Actual result
Confirmation modal always popup, even if there is no content to lose.

#### System information (as much as possible)

Joomla version: 3.8.5
Kunena version: 5.1.0-RC4-DEV
Php version: 7.1.14
Database version: MySQL 5.6.38

**Comment by xillibit** [comment]
For me it opens the modal only when the Topic Template is filled. I have just tried, with the Topic Template filled for welcome mat and not for suggestion box, when i switch to suggestion box, the modal hasn't been open.

**Comment by 810** [comment]
Yes confirmed, i see the modal.

because the textarea has text: Enter your message here

````
<textarea name="message" tabindex="7" class="span12 markItUpEditor invalid" id="editor" aria-invalid="true" required="required" placeholder="Enter your message here" rows="12">Enter your message here</textarea>
````

**Comment by 810** [comment]
fixed try now

**Comment by rich20** [comment]
- [ ] There is no modal now, but you see also not the template if you switch to the category Suggestion Box. Earlier we had the modal, and with click on Replace content, was inserted the correct template

**Comment by 810** [comment]
@rich20 try now

**Comment by rich20** [comment]
- [x] Confirmation modal should not popup when content is empty

**Switch from a category with template to another category with template**
- [x] Replace content - Success
- [x] Replace content and keep existing - Success

**Switch from a category with template to a category without template**
- [ ] <del>The content remain in the text field</del>

**Comment by 810** [comment]
for me the content remain as wanted when i change to normal category

**Comment by rich20** [comment]
Yes, I had seen this now with a older Kunena version. It was always so. In this case it works all correct.
- [x] All Success
