### ISSUE TITLE
Edited topic in moderated category does not appear in moderation queue.

### ISSUE THREAD

**Issue by Sophist-UK** [Kunena/Kunena-Forum#5761]
#### Steps to reproduce the issue

Create a moderated category.

Create a topic - which is sent to queue for moderation.

Check that it immediately appears in moderation queue.

Approve the post.

Reedit the topic to send it back to moderation.

Check that the topic immediately appears in moderation queue.

#### Expected result

Topic appears in moderation queue immediately it is created or edited.

#### Actual result

Topic does not immediately appear in moderation queue but can be seen greyed out in category topic list.

#### System information (as much as possible)

Joomla version: 3.8.4
Kunena version: 5.1 RC3
Php version: 7.1
Database version: MySQL 5.6

**Comment by 810** [comment]
is this moderation queue view by menu item, or just on the category itself

**Comment by Sophist-UK** [comment]
Menu item I think.

**Comment by sshcli** [comment]
use this
<img width="287" alt="all" src="https://user-images.githubusercontent.com/12942731/36488085-fa1efb92-16f8-11e8-90f9-64b78eaa2a3e.PNG">

**Comment by Sophist-UK** [comment]
Its the default menu item that comes with Kunena I think. But I'll take a look.

**Comment by Sophist-UK** [comment]
I don't have translated strings for Userid and the popover description, so I have no idea what the Userid field does. See #5763

**Comment by Sophist-UK** [comment]
Ok - I have created menu items for Recent Unapproved Topics and Recent Unapproved Posts, so next time someone does something that needs moderation I will let you know what happens with each of these menu items.

**Comment by Sophist-UK** [comment]
Ok - we had a new **topic** entered into the moderated forum.

It did **not** appear under Moderator Topics menu item, or under Recent Topics - Unapproved menu item, but it did appear under Recent Posts - Unapproved menu item.

**Comment by 810** [comment]
Ok i figured out what the moderation menu item do.

If a user post a topic, and a mod/admin replies, and then the user replied again. It will show on the view.

So this is only showing posts who is replied by mod and then normal user replied again.

I didn't know we had this feature. was added by matias.

**Comment by Sophist-UK** [comment]
@810 - So, this is "a feature" rather than a bug and is not going to be fixed?

As a user, what we need is one place (i.e. one menu item) where moderators can view all the topics and posts that need moderating and that they have rights to moderate. I am not worried what the menu item is, but it has to deal with both topics and posts in one screen. 

And why a **Topic** that needs moderation appears on "Recent **Posts** - Unapproved", I have no idea?

And whatever the solution is, it needs to be provided as a default menu item when you first install Kunena.
