### ISSUE TITLE
Moderator email has untranslated string

### ISSUE THREAD

**Issue by Sophist-UK** [Kunena/Kunena-Forum#5762]
#### Steps to reproduce the issue

Edit a topic in a moderated category, sending topic back for moderation.

Wait for notification email to arrive.

#### Expected result

EMail has language strings translated.

#### Actual result

First line of email body (a title line also containing the web site name) starts with COM_KUNENA_POST_EMAIL_MOD3.

#### System information (as much as possible)

Joomla version: 3.8.4
Kunena version: 5.1 RC3
Php version: 7.1
Database version: MySQL 5.6

**Comment by 810** [comment]
fixed, the string was missing

**Comment by Sophist-UK** [comment]
See commit comments re English grammar and use of appending strings rather than sprintf

**Comment by 810** [comment]
Do you have any suggestion for the style.

i want to change to:
````
email title = [board_title] Topic name 

email message = 

email header
reason
subject
categoryname
author name

message link

message
-------
notification message
````

**Comment by sshcli** [comment]
Yes, a suggestion for the message link.
Please add parameters in the URL for easy track in Google Analytics.

Example URL format:
https://example.com/?utm_source=newsletter&utm_medium=email&utm_campaign=subscription

**Comment by Sophist-UK** [comment]
1. Email subject (i.e. what you call title) needs to have a call to action if it requires action

So, perhaps "[board_title] Category: Topic (Topic / Post awaiting moderation)"

2. I think that the body needs to depend on what the email is for.

2a. If it is a subscription then the email is for info only and should focus on the content, with View More, Reply, Unsubscribe and Report buttons.

2b. If it is an action required email, then it should focus on what the recipient needs to do and the primary information needed to make a decision, followed by action buttons or a link, and then all remaining secondary information (like the IP address of the user, number of posts etc. that the recipient might need if e.g. this is a borderline case or they need to decide whether to ban the users etc.).

Having two distinct styles is also helpful - as a user can then distinguish between subscriptions to read later and action emails that might be higher priority.

Does this help?

**Comment by Sophist-UK** [comment]
@sshcli I agree about tracking.

@810 Jelle - I would prefer to see buttons than links.

**Comment by 810** [comment]
if you have an example email (image) then i will change it to that.

**Comment by Sophist-UK** [comment]
No - sorry. My comments were theoretical from experience not based on any Kunena emails I have already received.

**Comment by sshcli** [comment]
> Having two distinct styles is also helpful - as a user can then distinguish between subscriptions to read later and action emails that might be higher priority.

I agree, It could be something as simple as two different colors 
(For example: Red for admin/moderator emails and Blue for all others emails)

**Comment by Sophist-UK** [comment]
Colours are indeed a good way to distinguish between types of email, however IMO it cannot be "as simple as two different colours" i.e. you cannot rely only on the colour because e.g. some people get emails converted to plain text without colours and some people are colour blind.

But also, since you need to distinguish in the subject line, so that people don't have to open the email to know whether it needs their attention, colours cannot help there
