### ISSUE TITLE
Recent Posts menu settings has untranslated strings

### ISSUE THREAD

**Issue by Sophist-UK** [Kunena/Kunena-Forum#5763]
#### Steps to reproduce the issue

1. Try to create a new menu item
2. Choose Kunena Recent Posts as menu type.

#### Expected result

Labels and popovers translated.

#### Actual result

COM_KUNENA_MENU_USERID
COM_KUNENA_MENU_USERID_DESC

#### System information (as much as possible)

Joomla version: 3.8.4
Kunena version: 5.1 RC3
Php version: 7.1
Database version: MySQL 5.6

**Comment by Sophist-UK** [comment]
Hmmm - it is in the language file `Kunena-Forum/src/administrator/components/com_kunena/language/en-GB/en-GB.com_kunena.sys.ini` in the Github K5.0 branch but NOT in the K5.1 branch.

I wonder how many other differences there are between K5.0 and K5.1 branches...

**Comment by 810** [comment]
Should be fixed, could you recheck again.

**Comment by 810** [comment]
closing for now.
