### ISSUE TITLE
kunena plugin interface not triggering plugin's onExtensionAfterSave

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5771]
#### Steps to reproduce the issue
I have created a plugin for displaying ochBlog avatars and profiles in Kunena (like plugin plg_kunena_easyprofile).
My plugin has a function onExtensionAfterSave that I use to set a download key to the plugins #__update_sites row (field: extra_query).
That update key is required to be able to use the joomla updater (subscription based plugin).

1. In kunena open the plugins overviews
2. set the download id in the corresponding field
3. click save / save and close

#### Expected result
the entered download id should be added to the extra_query field in #__update_sites

#### Actual result
it is not because the function onExtensionAfterSave is not triggered?

#### System information (as much as possible)

Joomla version: 3.8.5
Kunena version: 5.0.latest
Php version: 
Database version:

#### Additional comments
When opening the pluging via the Joomla plugin manage, everything works as expected :)

**Comment by 810** [comment]
could you check it, if its correct.

**Comment by Ruud68** [comment]
I will check :)
BTW, I did some changes to Joomla (available from joomla 3.8.3) where you as a developer can stop 'duplicating' all the plugin code into you own extension. You can now fully utilize the plugins via the com_plugin modals.
So only thing you need to develop is an overview of your plugins and when you click them the com_plugins modal will open and you can do all things possible out of the box with plugins.
This way there is no code duplication and when com_plugin changes in core, it also changes for you :)
see video for short demo.
https://office.onlinecommunityhub.nl/nextcloud/s/YqDYAoNpPm3nwjt

**Comment by Ruud68** [comment]
Hello @810 tested this and it didn't work.
been looking how to fix, but that took to long so I have a code proposal (as stated above) with which you can remove a lot of (duplicated) code from Kunena.
You can test for yourself by replacing ./administrator/components/com_kunena/template/plugins/default.php with this one: https://office.onlinecommunityhub.nl/nextcloud/s/E98FYQttxbqoiCH
This file is based on the 5.0.13 version.

**Comment by 810** [comment]
I think thats a wrong file you uploaded, i see only redirect file.

**Comment by Ruud68** [comment]
Ooops :S please retry :) link is the same.

**Comment by 810** [comment]
Thnx looks ok for me, will remove the plugin codes.

**Comment by Ruud68** [comment]
Cool :) it is a quick (working) mock-up I did, but you see the concept: no more hassles with duplicated code :)
