### ISSUE TITLE
Quick reply button not working 

### ISSUE THREAD

**Issue by brandonaaws** [Kunena/Kunena-Forum#5775]
#### Steps to reproduce the issue
Quick reply button does nothing on page. 

#### Expected result
It should go to reply page or should show popup

#### Actual result

Nothing happen when we click on quick reply 

#### System information (as much as possible)

Joomla version: 3.8.5 It was not working on 3.7.5 as well.
Kunena version: 5.0.13
Php version: 7.0
Database version:

**Comment by 810** [comment]
3rt party Kunena template issue. Closing this issue.
