### ISSUE TITLE
Social - YouTube and OK in Kunena 5.1

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#5781]
Add YouTube and OK in \libraries\kunena\user\user.php

Link YouTube: https://www.youtube.com/###
`' youtube ' => array ( ' url ' => ' https://www.youtube.com/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_YOUTUBE ' ), ' nourl ' => ' 0 ' ),`

Odnoklassniki: https://ok.ru/username
`'ok ' => array ( ' url ' => ' https://ok.ru/## VALUE ## ' , ' title ' => JText :: _ ( ' COM_KUNENA_MYPROFILE_OK ' ), ' nourl ' => ' 0 ' ),`

https://github.com/Kunena/Kunena-Forum/issues/5440

In translation and in \components\com_kunena\template\crypsis\layouts\user\item\social\default.php they are already added.

**Comment by 810** [comment]
i have fixed it already 4 days ago: https://github.com/Kunena/Kunena-Forum/commit/ca44ab20de54a02c38e68eb4e5b9ac6f114edb33

**Comment by mc-hovanskiy** [comment]
Sorry, i did not see.

Can you check the translation for the editor WYSIWYG? I did not see him on the transfix.

And I saw the FontAwesome icons do not work in the social buttons:
![2018-03-08_164232](https://user-images.githubusercontent.com/29813939/37157382-63306ee6-22f1-11e8-9668-dfa6b3afa1ad.png)

In FontAwesome 5 for brands you need to use the prefix fab.
Example: `<i class="fab fa-twitter"></i>`

**Comment by rich20** [comment]
> Can you check the translation for the editor WYSIWYG? I did not see him on the transfix.

You find the codes in site/com_kunena.templates.ini but the translation will not help. The editor used the hardcoded language from /components/com_kunena/template/crypsis/assets/js/jquery.wysibb.js

**Comment by 810** [comment]
it should load:
components\com_kunena\template\crypsis\assets\js\wysibb.lang.js

**Comment by rich20** [comment]
Yes, in principle it should load from this file. But does will not loaded. Also a Joomla language override does not help. It loads always from jquery.wysibb.js the language.

**Comment by mc-hovanskiy** [comment]
> Yes, in principle it should load from this file. But does will not loaded. Also a Joomla language override does not help. It loads always from jquery.wysibb.js the language.

I confirm.
The file wysibb.lang.js is connected, but does not translate. Only edit the file jquery.wysibb.js

**Comment by 810** [comment]
ok fixed the issue.

the translations are on the components\com_kunena\language\ru-RU\ru-RU.com_kunena.templates.ini file


on transifex: https://www.transifex.com/Kunena-Forum/Kunena/language/ru_RU/
site/com_kunena.templates.ini

**Comment by rich20** [comment]
- [x] Yes, now works

**Comment by mc-hovanskiy** [comment]
Thanks! It works now.
I did the translation for the frontend, I just could not understand why the editor was not translated.

**Comment by rich20** [comment]
hm.. I found a new problem. Quick Reply do not load the file wysibb.lang.js

**Comment by 810** [comment]
ok, fixed now also fdbfc7a6a0b1f5f558c12fdd98c3277d147eda15

**Comment by mc-hovanskiy** [comment]
I paste the video from YouTube - after saving the video there is no post.

**Comment by 810** [comment]
try this fix: 08e729d559f3605f25aeed1a90535481b8748e79

**Comment by 810** [comment]
this is the real fix for new posts: 28e4dc838cb277b61d8ac53ac0dd14292c7d963c

**Comment by mc-hovanskiy** [comment]
No, it does not help.
Something that cuts out the iframe tag, instead saw an empty space. But when editing a video there is an editor.
Disconnected Font Avesome 5 - did not help.

**Comment by mc-hovanskiy** [comment]
> this is the real fix for new posts: 28e4dc8

Thanks! It works now.
