### ISSUE TITLE
WYSIWYG button bar not respecting configured buttons

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5787]
#### Steps to reproduce the issue
In Template: Crypsis tab [Bbcode], set editor to WYSIWYG

#### Expected result
Configured buttons (show yes / no) should be respected in the WYSIWYG button bar

#### Actual result
The buttons configuration is not respected

#### System information (as much as possible)

Joomla version: 
Kunena version: 5.1.0-RC4-DEV (Development Snapshot)
Php version:
Database version:

**Comment by mc-hovanskiy** [comment]
This is the settings for the BB-Code editor.

**Comment by Ruud68** [comment]
>This is the settings for the BB-Code editor.

If these settings are for the BB-Code editor only then they should be hidden when WYSIWYG editor is selected to avoid confusion.
The next question then is how to configure the buttons for the WYSIWYG editor?

**Comment by Ruud68** [comment]
Hi, just tested this with todays nightly: works partly.
the confidential button is not NOT showing although enabled, there are others that are not showing as well (instagram, soundcloud, etc.)

**Comment by rich20** [comment]
If you stay in the column with the mouse, you see the tooltip: "If you choose WYSIWYG the extra bbcode plugins will not work."
![bildschirmfoto von 2018-03-16 14-15-11](https://user-images.githubusercontent.com/888847/37522819-6876b560-2925-11e8-87ee-2f72d7e7825e.png)

**Comment by Ruud68** [comment]
a, okay, is this something that will change?

**Comment by rich20** [comment]
> a, okay, is this something that will change?

I'm not sure. Jelle has added last night some codes, but now I have still less buttons.
https://github.com/Kunena/Kunena-Forum/commit/851155d9fbe157170bcfee1ae819365b4b95343f

**Comment by 810** [comment]
All extra plugins will be added, when the extra plugins are working on the editor.

All basic options are now working correct with the settings. But you need to click on save, before the options are available.
