### ISSUE TITLE
Recent Topics not working

### ISSUE THREAD

**Issue by brianmcardle** [Kunena/Kunena-Forum#5789]
I upgraded from 5.0.13 to 5.0.14 and my 'Recent Topics' page is now giving a 500 error. I can't find any similar bugs here, and I haven't been able to pinpoint where the toString method is being called.

#### Steps to reproduce the issue
Click on recent topics tab.

#### Expected result
List of recent topics.

#### Actual result

> 500 Internal Server Error
> Fatal Error was detected!
> Please contact the site owner.

#### System information (as much as possible)

Joomla version: Joomla! 3.7.2 Stable
Kunena version: 5.0.14
Php version: 7.1.15
Database version: 5.6.39-cll-lve

#### Additional comments
Error message:
```
Data
{
    "type": 1,
    "message": "Method KunenaLayoutTopicList::__toString() must not throw an exception, caught Error: Class 'Joomla\\CMS\\Uri\\Uri' not found",
    "file": "<snip>/components/com_kunena/template/crypsis/pages/topics/default/default.php",
    "line": 0
}
```
The contents of that default.php file:
```
<?php
/**
 * Kunena Component
 * @package     Kunena.Template.Crypsis
 * @subpackage  Pages.Topics
 *
 * @copyright   (C) 2008 - 2018 Kunena Team. All rights reserved.
 * @license     https://www.gnu.org/copyleft/gpl.html GNU/GPL
 * @link        https://www.kunena.org
 **/
defined('_JEXEC') or die;

$content = $this->execute('Topic/List/Recent')
	->setLayout('recent');

$this->addBreadcrumb(
	$content->headerText,
	'index.php?option=com_kunena&view=topics&layout=default'
);

echo $content;
echo $this->subRequest('Widget/WhoIsOnline');
echo $this->subRequest('Widget/Statistics');

```

Thanks in advance for any pointers.

**Comment by 810** [comment]
You need to update joomla to 3.8.6.

Joomla! 3.7.2 isn't supported anymore.
