### ISSUE TITLE
Start and End time should use same timezone

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5791]
#### Steps to reproduce the issue
1. Ban a user
2. Go to Ban History

#### Expected result
<img width="248" alt="goodtime" src="https://user-images.githubusercontent.com/12942731/37530942-28205c50-2911-11e8-84ab-eac902db1f6c.PNG">

#### Actual result
<img width="252" alt="badtime" src="https://user-images.githubusercontent.com/12942731/37530937-248dacd2-2911-11e8-9444-65f047f3bc07.PNG">

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by xillibit** [comment]
You don't have set the timezone in Joomla! configuration panel

**Comment by sshcli** [comment]
What I mean is that:
The value for "End Time" is being taken from my computer
and
The value for "Start Time" is being taken from the Server Time Zone

A fix for this issue is to take the decision to use "Server Time Zone" or "Local Computer" for both (End and Start Time)

**Comment by xillibit** [comment]
I have looked the différents calls for expiration date of ban and ban creation date and there isn't timezone set, so it's taken from joomla! settings

**Comment by sshcli** [comment]
Please look deeper for "End Time" as it is taking the time from your local computer.
You can make some test by changing the time in your local computer.

**Comment by sshcli** [comment]
<img width="307" alt="sametime" src="https://user-images.githubusercontent.com/12942731/37558068-ae135870-29e4-11e8-9dfd-d2cdeebc771a.PNG">

**Comment by 810** [comment]
That's loaded by the browser and the browser loaded system, we can't change that.

That's the plugin.
