### ISSUE TITLE
Reported message should reply to user

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5793]
#### Steps to reproduce the issue
1. As a registered user, report a message in the forum
2. As a moderator, open the email you receive and click the reply button

#### Expected result
When the moderator reply the email, the reply should be sent to the user that reported the message.

#### Actual result
When the moderator reply the email, the reply is sent to the webmaster.

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by xillibit** [comment]
There should be a way to define a mail adress for mail reply, i have no idea how to do it

**Comment by sshcli** [comment]
> There should be a way to define a mail adress for mail reply, i have no idea how to do it

This example form has that function, you can take an idea from there.
[form.zip](https://github.com/Kunena/Kunena-Forum/files/1821880/form.zip)

**Comment by 810** [comment]
````from Root User <root@localhost> ````

**Comment by 810** [comment]
reply to is correct, only you will see the sender is root user.
