### ISSUE TITLE
SEO: Add exception for rel="nofollow"

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5800]
#### Expected result
Don't use rel="nofollow" if the link targets your own domain.

#### Actual result
Right now we have problems with internal linking, this is caused by the use of rel="nofollow"
rel="nofollow" is being used even for own domain.

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
where do you have this issue

**Comment by sshcli** [comment]
components\com_kunena\template\crypsis\layouts\bbcode\url\default.php
Line 20

**Comment by sshcli** [comment]
Better explanation of the problem on these links:
https://moz.com/learn/seo/internal-link
https://yoast.com/internal-linking-for-seo-why-and-how/

**Comment by 810** [comment]
but what is your bbcode looks like?

**Comment by sshcli** [comment]
> but what is your bbcode looks like?

It looks fine.
The issue I'm reporting here does not have any visible defect for the human eye, but for google crawler bots and other search engines.

What you need to do is to remove the nofollow when someone insert a URL in the text area that is pointing to another page in the same domain, for example:

```
if   URL in the content = The same domain where the kunena forum is installed
{
	$rel = 'rel="noopener noreferrer"';
}
else
{
	$rel = 'rel="nofollow noopener noreferrer"';
}
```

This way you are letting googlebot and other search engines to find and index your content quicker.

**Comment by sshcli** [comment]
In other words, 
The use of nofollow should be only for external links

**Comment by sshcli** [comment]
As a workaround for this.
Maybe we just need an additional bbcode tag for URL

One for external links (the current one) with rel=nofollow
Another one for internal links without rel=nofollow

If necessary,  also add a button for the internal link in the bbcode editor
