### ISSUE TITLE
Improve categories search results

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5804]
#### Steps to reproduce the issue
1. Create a category named: Sdfgugu**ñ**sdf
2. Search for a category named: Sdfgugu**n**sdf

#### Expected result

<img width="232" alt="good" src="https://user-images.githubusercontent.com/12942731/37617505-b6d22a44-2b89-11e8-9705-dbcc618ab193.PNG">

#### Actual result

<img width="256" alt="n" src="https://user-images.githubusercontent.com/12942731/37617053-497bf746-2b88-11e8-9f22-1d5a219a14da.PNG">

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
is working for me:

![screencapture-kunena-test-new-administrator-index-php-2018-03-21-01_57_01](https://user-images.githubusercontent.com/876623/37690441-dd687784-2ca2-11e8-9ce6-397f949cccd8.png)

**Comment by 810** [comment]
did you have Unicode Aliases enabled on joomla config

**Comment by sshcli** [comment]
Replace the ñ for a n on the search

**Comment by sshcli** [comment]
in example.com/forum/search you can search words with "n" and will find also words with "ñ"
This is not possible in category search.

**Comment by sshcli** [comment]
> did you have Unicode Aliases enabled on joomla config

No. it is disabled
