### ISSUE TITLE
Undefined property via __get(): youtube

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5807]
#### Steps to reproduce the issue
Update from 5.0.14 to 5.1.0-RC4-DEV

#### Expected result
You should not have any PHP Warning

#### Actual result
PHP Notice:  Undefined property via __get(): youtube in /home/username/public_html/components/com_kunena/template/crypsis/layouts/user/edit/profile/default.php on line 127 in /home/username/public_html/libraries/kunena/user/user.php on line 2137

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by rich20** [comment]
Profile -> Edit -> Profile Information
![bildschirmfoto von 2018-03-20 17-31-45](https://user-images.githubusercontent.com/888847/37668552-18576cee-2c65-11e8-9eb2-a8352faf5f28.png)

**Comment by sshcli** [comment]
I have upgraded from  k5.1.0-RC4-DEV_2018-03-19 to  k5.1.0-RC4-DEV_2018-03-21 and still having the problem.

**Comment by 810** [comment]
Only official releases are supported by updates. 
So rc 3 to rc4.
