### ISSUE TITLE
Undefined property via __get(): ok

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5808]
#### Steps to reproduce the issue
Update from 5.0.14 to 5.1.0-RC4-DEV

#### Expected result
You should not have any PHP Warning

#### Actual result
PHP Notice:  Undefined property via __get(): ok in /home/username/public_html/components/com_kunena/template/crypsis/layouts/user/edit/profile/default.php on line 127 in /home/username/public_html/libraries/kunena/user/user.php on line 2137

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
Undefined property via __get(): youtube  #5807
