### ISSUE TITLE
Locked topics lacks class_sfx (Part 2)

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5809]
#### Expected result
Apply fix https://github.com/Kunena/Kunena-Forum/commit/d93f9351180c0cd7086c403da552108178398a26 also for messages in profile view:
example.com/user/id-username

#### Actual result
The view example.com/user/id-username lacks the class tr.category.locked

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

#### Additional comments
See issue https://github.com/Kunena/Kunena-Forum/issues/5724 for more details

**Comment by 810** [comment]
Leave a comment
