### ISSUE TITLE
Ban from forum does not work

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5814]
#### Steps to reproduce the issue
Try to ban a user (Ban From forum)

#### Expected result
Ban from forum should work

#### Actual result
Ban from forum does not work

#### System information (as much as possible)

oomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by rich20** [comment]
It only works the first time. If you unban this user and ban again, the user will only logged out and the tab switched from "New Ban" to "Edit  Ban".
But the user can login again and still write.
