### ISSUE TITLE
Topic Template: Modal won't popup when Editor = WYSIWYG

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5820]
#### Steps to reproduce the issue
1. Backend->Kunena Forum->Templates->BBcode->Editor = WYSIWYG
2. Set a Topic Template for category "Welcome Mat"
3. Set a Topic Template for category "Suggestion Box" 
4. Go to example.com/forum/newtopic
5. Try to switch between categories

#### Expected result
Confirmation modal should popup

#### Actual result
Confirmation modal won't popup

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by sshcli** [comment]
In fact, WYSIWYG editor is presenting the same errors with topic template that have been already fixed in BBcode editor

**Comment by 810** [comment]
I see the modal,
but you need to click outside kunena, to see the second topic template

**Comment by sshcli** [comment]
> I see the modal,
but you need to click outside kunena, to see the second topic template

Me too.

**Comment by sshcli** [comment]
To close this issue, only need to apply the following fix for the WYSIWYG editor: https://github.com/Kunena/Kunena-Forum/commit/f2871c93a8dd7b6655fc3fd9ff4e93cb6bce3422

**Comment by rich20** [comment]
Replaced by CKeditor
