### ISSUE TITLE
Topic Template: Modal should popup when switch to blank

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5821]
#### Steps to reproduce the issue
1. Backend->Kunena Forum->Templates->BBcode->Editor = BBcode
2. Set a Topic Template for category "Welcome Mat"
3. Go to example.com/forum/newtopic
4. Try to switch to category "Suggestion Box" (or another category without Topic Template)

#### Expected result
The confirmation modal should popup

#### Actual result
The confirmation modal does not popup

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
is working correctly for me.

**Comment by sshcli** [comment]
only the "Welcome Mat" should have a Topic Template.
Leave all others categories in blank, without Topic Template

**Comment by 810** [comment]
oh so, no this is correct. If there is no template, it should be there. No modal, because there is nothing to add.

**Comment by sshcli** [comment]
then the content that was loaded automatically without asking to the user must be removed automatically when the user switch to a blank category.

**Comment by 810** [comment]
Could you test one more, i think it got it, but im not sure.

**Comment by sshcli** [comment]
Test results = ✔️Pass
