### ISSUE TITLE
BBcode toggle button does not work

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5822]
#### Steps to reproduce the issue
1. Backend->Kunena Forum->Templates->BBcode->Editor = WYSIWYG
2. Disable all bbcode buttons in Backend->Kunena Forum->Templates->BBcode
3. Go to example.com/forum/newtopic

#### Expected result
<img width="508" alt="goodbbcode" src="https://user-images.githubusercontent.com/12942731/37736717-043cc6d2-2d28-11e8-83b2-d2656818c5ff.PNG">

#### Actual result
<img width="492" alt="badbbcode" src="https://user-images.githubusercontent.com/12942731/37736709-fe4ce1e4-2d27-11e8-8d33-18c4330e2f2a.PNG">

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC4-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
This needs a button for the wysiwyg editor

**Comment by sshcli** [comment]
The button is not working after disable all bbcode options.
You click the button and nothing happens.
In my opinion, it should be fixed or add the option to remove it from there.
