### ISSUE TITLE
Use white font for submenu selected buttons

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5827]
#### Steps to reproduce the issue
Create some submenus items under the same kunena menu item

#### Expected result
You should use white font for submenu selected buttons
<img width="238" alt="white" src="https://user-images.githubusercontent.com/12942731/37930115-c37c88bc-310f-11e8-838f-cdda78411960.png">

#### Actual result
The submenu selected buttons are using black font, making more difficult to read

<img width="257" alt="selection" src="https://user-images.githubusercontent.com/12942731/37930106-bf42ee44-310f-11e8-88e6-233a57b4fc3e.png">

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC5-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

#### Additional comments

**Comment by 810** [comment]
this is a joomla template issue.
