### ISSUE TITLE
Logs: Several operations not working

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5829]
#### Steps to reproduce the issue
Backend->Kunena forum->Logs->Operation
<img width="566" alt="logs" src="https://user-images.githubusercontent.com/12942731/37931068-7f3f78d2-3112-11e8-9e59-1de51f5ee7f3.png">

#### Expected result
All operations should work in logs

#### Actual result
Several operations are not working in logs

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC5-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by xillibit** [comment]
All secure posts something, this does't exist in Kunena, i need to check the others items
