### ISSUE TITLE
Categories manager : add colors on items

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#5831]
#### Steps to reproduce the issue

Add colors on items, like you see on the red box : 
![ddtred](https://user-images.githubusercontent.com/876395/37981285-8e43954e-31ed-11e8-81cc-bd7576e6766b.png)

**Comment by Sophist-UK** [comment]
I would agree - having the cross as red and the tick as green would be nice.

**Comment by Sophist-UK** [comment]
A very easy one to do. So I did it.
