### ISSUE TITLE
Message title length value can be skipped

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5834]
#### Steps to reproduce the issue
1. Backend->components->kunena forum->Templates->Crypsis->Message title length = 10
2. Install [Opera Mini](https://play.google.com/store/apps/details?id=com.opera.mini.native&hl=en) in your smartphone
3. Using Opera mini, create a new topic in the kunena forum and insert more than 10 characters in the subject 

#### Expected result
Nobody should be allowed to insert more than 10 characters in the subject and if the opera mini browser is not supported by kunena, then the access to kunena should be restricted when using opera mini.

#### Actual result
Anyone using opera mini can override/skip the Message title length defined value

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC5-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
This is a browser issue, can't fixed it.
