### ISSUE TITLE
Purging IP addresses does not purge IP addresses from  the user list

### ISSUE THREAD

**Issue by c-schmitz** [Kunena/Kunena-Forum#5836]
#### Steps to reproduce the issue
I have deactivated the capturing of IP addresses in the general settings. Now I run the purge tool to purge all IP addressess from the system that are older than 0 days (so all of them).

#### Expected result
All IP address are purged from forum messages **and** the kunena user table.

#### Actual result
Only the IP addresses from forum messages are purged.

#### System information (as much as possible)

Joomla version: 3.8
Kunena version: 5.0.14
Php version: 5.9.11
Database version: MySQL 5.6

#### Additional comments
As you might be aware this might be critical in regards to the upcoming EU-GDPR privacy law which becomes active in May.

**Comment by 810** [comment]
i have added the option.
