### ISSUE TITLE
Kunena collects unwanted IP addresses in the users table

### ISSUE THREAD

**Issue by c-schmitz** [Kunena/Kunena-Forum#5837]
#### Steps to reproduce the issue
I have deactivated the capturing of IP addresses in the Kunena settings (I know this was mainly meant for forum messages) for legal reasons
If a user logs/writes message in/to Kunena then apparently the IP address is captured in the kunena_users table.

#### Expected result
No capturing of IP addresses.

#### Actual result
IP addresses are still captured in the kunena_users table

#### System information (as much as possible)

Joomla version: 3.8
Kunena version: 5.0.14
Php version: 5.9.11
Database version: MySQL 5.6

#### Additional comments
As you might be aware this might be critical in regards to the upcoming EU-GDPR privacy law which becomes active in May.

**Comment by 810** [comment]
Fixed, the issue was on quickreply.

Also i have added a option to remove it. tools->Cleanup IP Addresses
