### ISSUE TITLE
Topics remains after read marked as Unread

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5840]
#### Steps to reproduce the issue

Login and to open a unread topic

#### Expected result

after read the New indicator should be gone

#### Actual result

the topic remain marked as unread

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by rich20** [comment]
Supplement: I've noticed, if you write a answer, then disappears the New indicator.

**Comment by 810** [comment]
its only on k.org, other site are ok for me. so i think there is conflict somewhere.

**Comment by rich20** [comment]
No, I see the same problem on my test pages.
