### ISSUE TITLE
items per page shows the wrong number

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5842]
#### Steps to reproduce the issue
backend->components->kunena forum->categories->items per page

#### Expected result
100 should be 100

#### Actual result
100 is 10
<img width="506" alt="cat" src="https://user-images.githubusercontent.com/12942731/38196755-baba127e-3652-11e8-999a-3658dc77364c.png">

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC5-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by rich20** [comment]
hm.. I've tested it with 2 different test pages. 100 is 100.
That which in the dropdown is marked as blue is only the position from the mouse cursor. You can mark all position with it.
![bildschirmfoto von 2018-04-02 16-00-15](https://user-images.githubusercontent.com/888847/38199161-f78d359a-368f-11e8-8a74-6b3aa5c8e05f.png)

**Comment by sshcli** [comment]
Are you testing with PHP 7.2.3 + J3.8.6 + K5.1.0-RC5-DEV + MySQL 5.6.38 ????

**Comment by rich20** [comment]
No, tested with php 7.0.25 and 7.2.1

**Comment by sshcli** [comment]
There is no problem in Firefox.
Please test it with Google Chrome and you will see the issue

**Comment by rich20** [comment]
I use Chromium for Linux. Maybe another user can test it with Google Chrome.

**Comment by 810** [comment]
for me its also fine, no issue

**Comment by sshcli** [comment]
> for me its also fine, no issue

Google Chrome?

**Comment by 810** [comment]
yes.

**Comment by sshcli** [comment]
This is what I see:

![100to10](https://user-images.githubusercontent.com/12942731/38227079-76833536-36ca-11e8-8fca-d2155de775ae.gif)

**Comment by 810** [comment]
you have just 6 items, so if you select more, then it will just show your 6 items
