### ISSUE TITLE
Improve heading tags

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5843]
#### Expected result
<img width="234" alt="hgood" src="https://user-images.githubusercontent.com/12942731/38222165-40d6f652-36b1-11e8-947d-8e707096a942.PNG">

#### Actual result
<img width="234" alt="hbad" src="https://user-images.githubusercontent.com/12942731/38222161-3e72337c-36b1-11e8-8ed5-fb906f533902.PNG">

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC5-DEV
Php version: 7.2.3
Database version: MySQL 5.6.38

**Comment by 810** [comment]
then i have 1 more validation error.

**Comment by sshcli** [comment]
> then i have 1 more validation error.

Sorry, I don't understand. Could you please explain more on this?

**Comment by 810** [comment]
please check the changes with: https://validator.w3.org/

**Comment by sshcli** [comment]
I see 169 Warnings/Errors in my forum.
However, I'm not able to test the version with changes, because there is no fix to test against.

**Comment by sshcli** [comment]
btw, this issue was created to use model `<H1><H2><H3>` on index

```
<H1> Section Name</H1>
<H2> Category Name</H2>
<H3> SubCategory Name</H3>
```

<H1> Section Name</H1>
<H2> Category Name</H2>
<H3> SubCategory Name</H3>

**Comment by 810** [comment]
You may have just 1 H1. So if you have more section, your html markup is wrong.

**Comment by sshcli** [comment]
ok, I understand that part.
But at least set a value for H2, right now is empty.
It should have something.
