### ISSUE TITLE
Fontawesome for attachments are too big

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5844]
#### Steps to reproduce the issue

The symbol for attachments should not be many higher size as for thumbnails
![bildschirmfoto von 2018-04-03 02-54-45](https://user-images.githubusercontent.com/888847/38223545-c324c15e-36eb-11e8-8ab9-a758adbfc06e.png)

#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by xillibit** [comment]
Is this issue still present ? In crypsis it's not here : 

![image](https://user-images.githubusercontent.com/876395/88485217-90c1d700-cf74-11ea-98ea-28ee075210fd.png)

**Comment by rich20** [comment]
Your attachment symbol is from bootstrap 2.
Here with Fontawesome.

![Bildschirmfoto von 2020-07-26 20-58-06](https://user-images.githubusercontent.com/888847/88487175-13ea2980-cf83-11ea-9076-f91320184669.png)
