### ISSUE TITLE
Outdated FA class

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5857]
#### Steps to reproduce the issue
Go to https://www.kunena.org/forum/21-Language-Specific

#### Expected result
Icons should use the class for FA 5.0.10

#### Actual result
![class](https://user-images.githubusercontent.com/12942731/38743568-6eafaf38-3f0d-11e8-8933-80ef10b0e54f.PNG)

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC6-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by 810** [comment]
is setting option
