### ISSUE TITLE
Ampersand is not rendering as it should

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5861]
#### Steps to reproduce the issue
1. Create a new topic and insert this into subject and content: **test & test**
2. Go to recent topics and hover the mouse over the topic to see the description tooltip

#### Expected result
You should see: `test & test`

#### Actual result
Yo see: `test &amp; test`

![testbad](https://user-images.githubusercontent.com/12942731/38834699-3302f332-4197-11e8-9847-acaa1c64b373.png)

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC6-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by 810** [comment]
![untitled](https://user-images.githubusercontent.com/876623/38993823-f444ffdc-43e4-11e8-8c7e-42c38e117499.jpg)

**Comment by sshcli** [comment]
Insert `test & test` also in the text area of the topic, not only in the subject

**Comment by 810** [comment]
![untitled](https://user-images.githubusercontent.com/876623/38994203-fa6672aa-43e5-11e8-8252-571d5ef200d8.jpg)

**Comment by sshcli** [comment]
@rich20 or @xillibit 
Are you able you reproduce this bug?

**Comment by 810** [comment]
ok, got it now also

**Comment by sshcli** [comment]
This bug was introduced in k.5.0 BETA1
Does not exist in K.4.x

**Comment by 810** [comment]
this issue is also on Crypsisb3 on replied box on the topic message

**Comment by xillibit** [comment]
I will make some search to find what has changed in the K5.1 beta1

**Comment by 810** [comment]
libraries\kunena\layout\layout.php getTopicLink

i have changed it, to remove some bbcodes.
