### ISSUE TITLE
Can't set a value for search results

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5863]
#### Steps to reproduce the issue
1. Backend->components->kunena forum->configuration->frontend->Search Results = 2
2. Make a search in the forum of a common word that returns a lot of results

#### Expected result
You should see only two results 

![good](https://user-images.githubusercontent.com/12942731/38903834-dd60db54-4274-11e8-88a0-adcf62e65134.PNG)

#### Actual result
You see all results 

![bad](https://user-images.githubusercontent.com/12942731/38903829-d80f338a-4274-11e8-85fe-e46f7bca51b3.PNG)

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC7-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by rich20** [comment]
Confirmed, it shows the same number of results per page, as is set Topics Per Page.

**Comment by sshcli** [comment]
I think the problem is here:
https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/libraries/kunena/config.php

**Comment by sshcli** [comment]
More details about this issue provided by @rich20 on https://github.com/Kunena/Kunena-Forum/issues/5989

> **Describe the bug**
> https://www.kunena.org/forum/36-German/152869-suchergebnis-im-forum-beschnitten-nicht-navigierbar
> 
> **To Reproduce**
> Enter the search keyword Joomla at kunena.org
> 
> **Expected behavior**
> All search results
> 
> **Actual result**
> You get only 30 results (the same number as topics per page)
> You get always the same number of search result as is setting Topics per page
> 
> **System information (please complete the following information)**
> Joomla version: 3.8.8
> Kunena version: 5.1.2-DEV

**Comment by vincentwolsink** [comment]
Do you maybe have any info on the progress of this issue? I see it has been delayed a couple of times? I think a working search function is quite crucial for a forum :)

Maybe you can give me some pointers where to look for the solution? Then I will try to fix it myself (and am happy to open a PR here if I succeeded).

**Comment by sshcli** [comment]
// Everything working perfect back in K.5.0.13
<img width="261" alt="5 0 13" src="https://user-images.githubusercontent.com/12942731/43992627-323ca826-9d4f-11e8-9506-740e50d2388a.PNG">

// The pagination was removed in K.5.1.0.RC1
<img width="275" alt="5 1 0 rc1" src="https://user-images.githubusercontent.com/12942731/43992628-324d066c-9d4f-11e8-8fdd-d8eac9680577.PNG">

// Configuration->frontend->Search Results stop working in K.5.1.0.RC2
<img width="256" alt="5 1 0 rc2" src="https://user-images.githubusercontent.com/12942731/43992629-325d5d64-9d4f-11e8-9c95-cdb21b10ed38.PNG">
