### ISSUE TITLE
Can't save message: Subject is empty

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5864]
#### Steps to reproduce the issue
1. Backend->components->kunena forum->configuration->frontend->Let users edit the subject = No
2. user1 creates topic1
3. user2 try to quick reply topic1

#### Expected result
user2 should be able to quick reply topic1

#### Actual result
No one is able to to quick reply  topic1.
You always get this error: Cannot save message: Subject is empty!

![error](https://user-images.githubusercontent.com/12942731/38934589-2b0a1710-42ea-11e8-86a0-fcdb0cbdcbe2.PNG)

#### System information (as much as possible)

Joomla version: 3.8.6
Kunena version: 5.1.0-RC7-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by 810** [comment]
i can quick reply. as normal user.

**Comment by sshcli** [comment]
Type Quickreply = Default
Try to quick reply as admin

**Comment by sshcli** [comment]
Test results = ✔️Pass
