### ISSUE TITLE
Missing language string in backend

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5867]
#### Steps to reproduce the issue
Backend->Components->Kunena Forum->Users->Edit->Forum Settings->Select the time limit for pages

#### Expected result
The menu option should show the text in the proper language 

#### Actual result
The menu option is showing the language constant

![lang](https://user-images.githubusercontent.com/12942731/39021713-fffe2bd0-43ff-11e8-81ed-21e50ebe6ada.png)

#### System information (as much as possible)

Joomla version: 3.8.7
Kunena version: 5.1.0-RC7-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by rich20** [comment]
Also on Hide E-mail lacks a strig. It's these two:
COM_KUNENA_SHOW_ALL
COM_KUNENA_A_ONLY_REGISTERED
