### ISSUE TITLE
Topic template won't load in category/topic/create

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5869]
#### Steps to reproduce the issue
1. Define a topic template for the category "welcome-mat"
2. Go to example.com/welcome-mat/topic/create

#### Expected result
Topic template should be available when creating a topic using both URLs:
example.com/welcome-mat/topic/create
example.com/forum/newtopic

#### Actual result
Topic template is only available when creating a topic using this URL:
example.com/forum/newtopic

#### System information (as much as possible)

Joomla version: 3.8.7
Kunena version: 5.1.0-RC7-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by 810** [comment]
This is working correct for me. Its loading the correct topic template

**Comment by sshcli** [comment]
You are right.
Seems like it was a cache issue when testing.
i'm closing this issue right now.
