### ISSUE TITLE
Translation strings do not include substitution parameters

### ISSUE THREAD

**Issue by Sophist-UK** [Kunena/Kunena-Forum#5873]
#### Steps to reproduce the issue

I wanted to change the topic and reply header strings.

Kunena currently displays them like `{user name} created the topic: {topic}` and `{user name} replied the topic: {topic}`.

I might want to change this to e.g. `"{topic}" created by {user name}` or possibly some languages like German might require a structure something like `by {user name} was "{topic}" created`.

I went to Joomla Language overrides to change the string and found it did not have substitution and was simply `created the topic:`.

This Kunena output is created in `/components/com_kunena/template/crypsis/layouts/message/item/top/default.php` at line 53:
```
echo (!$isReply)
    ? $avatarname . ' ' . JText::_('COM_KUNENA_MESSAGE_CREATED') . ' ' . KunenaForumMessage::getInstance()->getsubstr($this->escape($message->subject), 0, $subjectlengthmessage) 
    : $avatarname . ' ' . JText::_('COM_KUNENA_MESSAGE_REPLIED') . ' ' . KunenaForumMessage::getInstance()->getsubstr($this->escape($message->subject), 0, $subjectlengthmessage);
```

As you can see the avatarname and topic title are in fixed locations rather than being substituted.
Joomla's advice about this is [here](https://docs.joomla.org/Formatted_fields_in_language_translation_strings).

So IMO this should instead be:
```
$title = KunenaForumMessage::getInstance()->getsubstr($this->escape($message->subject), 0, $subjectlengthmessage);
$lngstr = $isReply ? 'COM_KUNENA_MESSAGE_REPLIED' : 'COM_KUNENA_MESSAGE_CREATED';
echo JText::sprintf($lngstr, $avatarname, $title);
```
with the CREATED language string not `created the topic:` but `%s created the topic: %s`.

Then if you wanted to make this `"{topic}" was created by {user name}` you could have a language string `"%2$s" was created by %1$s`.

#### System information (as much as possible)

Joomla version: 3.8.4
Kunena version: 5.1 RC7
Php version: 7.1
Database version: 5.6

#### Additional comments

NOTE: The above is an example - this is probably a Kunena-wide issue, and so presumably for K5.2.

**Comment by 810** [comment]
I have added this one crypsis, for some reason it doesn't work for crypsisb3, so i left it to the old behaviour.
