### ISSUE TITLE
Shortkey not working if button is disabled

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5885]
#### Steps to reproduce the issue
1. Backend->components->kunena forum->templates->crypsis->bbcode->Show Bold button = No
2. Go to example.com/forum/newtopic
3. Put the cursor in the message text area
4. Press Crtl+B

#### Expected result
The following tags should be inserted: 
`[b][/b]`
Shortkey should work even if button is disabled

#### Actual result
Nothing happens.
Shortkey not working if button is disabled

#### System information (as much as possible)

Joomla version: 3.8.7
Kunena version: 5.1.0-RC8-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

#### Additional comments
The same problem with most of shortkeys, if not all.

**Comment by 810** [comment]
its handled by js,
If you don't enabled it, then there is no function
 so im closing this issue
