### ISSUE TITLE
My topics is showing non related topics

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5888]
#### Steps to reproduce the issue
1. user1 creates topic1
2. admin1 replies topic1
3. admin1 perm delete the reply from topic1
4. admin1 goes to "My Topics" menu (example.com/forum/mylatest)

#### Expected result
admin1 should not see topic1 in "My Topics" menu

#### Actual result
admin1 is able to see topic1 in "My Topics" menu

#### System information (as much as possible)

Joomla version: 3.8.7
Kunena version: 5.1.0-RC8-DEV
Php version: 7.2.4
Database version: MySQL 5.6.38

**Comment by 810** [comment]
Its because you are still subscribed to the topic.

**Comment by sshcli** [comment]
Well,
In that case please feel free to close this issue if this is not considered a bug or just leave it open if you plan to do something later.
