### ISSUE TITLE
Submit button does not respond

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5891]
#### Steps to reproduce the issue
1. Templates->Crypsis->bbcode->Editor = WYSIWYG
2. Go to example.com/forum/newtopic
3. Leave all fields empty
4. Press the submit button

#### Expected result
You should be warned about empty fields

#### Actual result
Nothing happens

#### System information (as much as possible)

oomla version: 3.8.7
Kunena version: 5.1.0-RC8-DEV
Php version: 7.2.5
Database version: MySQL 5.6.38

**Comment by 810** [comment]
i get the message:
Cannot save message: Message body is empty!

**Comment by sshcli** [comment]
and you @rich20 ?

**Comment by rich20** [comment]
>Cannot save message: Message body is empty!

I get this message only on New Topic, not on Reply or Quick Reply

- [x] New Topic - Cannot save message: Message body is empty!
- [ ] Reply - nothing
- [ ] Quick Reply - nothing

**Comment by sshcli** [comment]
I did uninstall/Install kunena again, and I keep getting the same results. (Button does not respond)

This is the error I get in the console:
![error](https://user-images.githubusercontent.com/12942731/39631906-8b049a3e-4f81-11e8-84b1-7e37b956cebb.PNG)

**Comment by sshcli** [comment]
Some ideas:
https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

**Comment by 810** [comment]
- [x] New Topic - Cannot save message: Message body is empty!
- [x] Reply - Cannot save message: Message body is empty!
- [x] Quick Reply - Cannot save message: Message body is empty!

**Comment by rich20** [comment]
I get the same error in my console:
An invalid form control with name='message' is not focusable.

**Comment by sshcli** [comment]
Tests Results based on https://github.com/Kunena/Kunena-Forum/commit/d2cacc0387162fe166e2ffb616a92c1e4c4d9c2f = ✔️Pass/Good/Ok
