### ISSUE TITLE
Add noindex,follow to category/topic/create

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5893]
#### Steps to reproduce the issue
1. As a guest, DO NOT Login
2. Go to example.com/category/topic/create
3. View source code

#### Expected result
It should be:
<meta name="robots" content="noindex, follow">

#### Actual result
It has nothing defined, which by default is: index, follow 

#### System information (as much as possible)

oomla version: 3.8.7
Kunena version: 5.1.0-RC8-DEV
Php version: 7.2.5
Database version: MySQL 5.6.38

**Comment by sshcli** [comment]
I forgot to say that this is as a guest, DO NOT Login

**Comment by 810** [comment]
i get the joomla setting result.

**Comment by sshcli** [comment]
I mean this login page:

![capture](https://user-images.githubusercontent.com/12942731/39779042-fa58bfee-52d5-11e8-83ed-22ff1974d88c.PNG)



This page should be set to **noindex,follow** in all places it's being used

**Why?**
Poor title
Poor description
Duplicated
Errors on Google Search Console
Etc..
