### ISSUE TITLE
Several alias per category being stored

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5906]
**Describe the bug**
This bug is only present when upgrading from K5.0 to K5.1
This bug does not exist on new installations of K5.1
The problem is that many alias are stored, and it should not.
it should be only 1 alias per category in order to avoid duplicate content issues.

**Steps to reproduce the behavior:**
1. Install K.5.0
2. Upgrade to K.5.1
3. Backend->components->kunena forum->categories->Edit category Welcome Mat->Alias = Cat1
4. Click save button

**Expected behavior**
The new alias should be: **cat1**

![good](https://user-images.githubusercontent.com/12942731/39968887-048cb7ca-56a2-11e8-9fbc-2a42bb07d795.PNG)

**Actual result**
You now have two category alias: **cat1** and **welcome-mat**

![bad](https://user-images.githubusercontent.com/12942731/39968899-51a065b6-56a2-11e8-81c6-a94b6a1518c4.PNG)

**System information (please complete the following information)**

Joomla version: 3.8.7
Kunena version: 5.1.0
Php version: 7.2.5
Database version: MySQL 5.6.39

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google Chrome]
 - Version [Version 66.0.3359.170]

**Comment by xillibit** [comment]
I'am not sure if it's really a bug, to remove an alias you just need to uncheck them and save

**Comment by sshcli** [comment]
I reported this because the behavior between 5.0 and 5.1 is different

**Comment by sshcli** [comment]
Also, if you change the category name and click the save and close button, you wont be aware of the duplicate problem until is too late

**Comment by sshcli** [comment]
This bug does not exist anymore.
When you are changing the alias, you can still see the old alias if you clic the save button, but if you clic save and close, the old alias will be removed.
I'm closing this issue
