### ISSUE TITLE
Category template is null when async = true

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5911]
**Expected behavior**
Category template should work without any problem

**Actual result**
Category template is null when async = true

**System information (please complete the following information)**
Joomla version: 3.8.7
Kunena version: 5.1.1-DEV
Php version: 7.2.5
Database version: MySQL 5.6.39

**Desktop (please complete the following information):**
OS: [Windows]
Browser [Google Chrome]
Version [Version 66.0.3359.170]

**Comment by xillibit** [comment]
I will check it later
