### ISSUE TITLE
Birthdate values reset when user saves preferences 

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5921]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sozzled** [comment]
Test data:

Birthdate = 15 August 1921

You can enter the date as 08-15-1921, save the date, and the date is properly saved.  The date, however, is displayed as 1921-08-15 (see #6001)
