### ISSUE TITLE
on reply, add image attach, post topic on clicking remove inline button

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#5927]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xillibit** [comment]
Can-you describe the issue ?
