### ISSUE TITLE
Add class for locked and sticky topics

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5950]
**Expected behavior**
We should also have:
div.badger-left.badger-info.message-published-**locked** for locked topics
div.badger-left.badger-info.message-published-**sticky** for sticky topics

**Actual result**
We only have:
div.badger-left.badger-info.message-published

**Screenshots**
![class](https://user-images.githubusercontent.com/12942731/40570415-a14f6fac-6058-11e8-8938-1dd6b1ed44cc.png)

**System information (please complete the following information)**
Joomla version: 3.8.8
Kunena version: 5.1.1-DEV-GIT
Php version: 7.2.5
Database version: 5.5.5-10.1.32-MariaDB

**Desktop (please complete the following information):**
OS: [Windows]
Browser [Google Chrome]
Version [Version 66.0.3359.181]

**Comment by 810** [comment]
locked and sticky are assigned to topics not messages.

**Comment by sshcli** [comment]
Ok, I understand.
Maybe there is another workaround that I'm not aware of that can be used to give some beautiful and unique styles to sticky or locked topics.

**Comment by 810** [comment]
it has now topic-locked and  topic-sticky classes on top
