### ISSUE TITLE
Previous ban blocks ability for Thank you

### ISSUE THREAD

**Issue by baticag** [Kunena/Kunena-Forum#5955]
**Describe the bug**
When you ban a user on forum and that ban expires, he still cannot use the Thank you option on any post.

**To Reproduce**
1. Ban a user
2. Unban the user or wait for ban to expire
3. Try to give Thank you on some post

**Expected behavior**
User should have the ability to use Thank you option after the ban expires.

**Actual result**
User doesn't have the ability to use Thank you option after the ban expires.

**Screenshots**

**System information (please complete the following information)**

Joomla version:  3.8.8
Kunena version: 5.0.8
Php version: 5.6.30
Database version: 3.8.6-2018-02-14

**Desktop (please complete the following information):**
Any desktop.

**Smartphone (please complete the following information):**
Any smartphone.

**Additional context**
I tried to identify the source of the problem and I saw that problem occurs when user's row in **joomla_kunena_users** table has a date in **banned** field and not **NULL**. When you unban the user or ban expires that value doesn't change back to **NULL**.

**Comment by 810** [comment]
For me its ok, but there is a issue, that the time as saved as utc. this can be your issue

**Comment by 810** [comment]
I think i have fix it, from now its the server time instead utc.

**Comment by xillibit** [comment]
The fix cause other issue : https://github.com/Kunena/Kunena-Forum/issues/5966, so i reopen it

**Comment by xillibit** [comment]
I don't find this issue, so feel free to open an new issue on 5.2 if you are still able to repdroduce it
