### ISSUE TITLE
We need another message when someone try to enable not needed Kunena plugins

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5956]
With the new plugin check you can not enable integration plugins when the extension is not installed. But nevertheless you get the message "Plugin enabled" if you click on it.

**Comment by xillibit** [comment]
> With the new plugin check you can not enable integration plugins when the extension is not installed

In which change is there that ?

**Comment by 810** [comment]
on the first plugin, you will now get a notice plugin enabled, but if disable the plugin by database, but the message is still showing enabled.

We are now using the joomla plugin modal. I have tried to set a other message, but I couldn't get it right, I have tried also onExtensionAfterSave or onAfterSave

**Comment by xillibit** [comment]
This issue is to improve this change : https://github.com/Kunena/Kunena-Forum/commit/e9331be7692540451b71c7d262254860389a56cb#diff-70ddd7a60143ecdaf91d591a5f429224abd313d0a9ca95b4a1732f19fdffbf8a
