### ISSUE TITLE
External avatar provider not working with 5.1

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5963]
**Describe the bug**
In 5.0.14 crypsis icon type = fontawesome worked correct, avatar was taken from plugin that provides avatar via public function _getURL($user, $sizex, $sizey)

in 5.1 crypsis icon type = fontawesome OVERRIDES the avatar with a fontawesome icon, I need to switch icon type to images-legacy to show the avatar, but then all icons are also images legacy

**Expected behavior**
avatar should be taken from plugin, not from icon type = fontawesome

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**
5.0.14 (correct)
![image](https://user-images.githubusercontent.com/2733197/40837924-4dbe5576-659c-11e8-8979-bb714fd3d6e1.png)

5.1 with icontype = fontawesome (NO AVATAR)
![image](https://user-images.githubusercontent.com/2733197/40837965-6d41ef7a-659c-11e8-818b-53c93a762d27.png)

5.1. with icontype = image - legacy (AVATAR, 'wrong' icons)
![image](https://user-images.githubusercontent.com/2733197/40837995-92f260ec-659c-11e8-9205-a3b7a1017b37.png)

**System information (please complete the following information)**

Joomla version: 3.8.8
Kunena version: 5.1
Php version: 7.1.17
Database version: 5.7.22

**Comment by Ruud68** [comment]
Okay,
just found what might be the cause of this.
When I switch off the plugin that provides the avatar
switch on avatar and profile is yes in the kunena pugin
login and add an avatar (random image)

switch on the avatar providing plugin, then the avatar from the plugin is shown.

So it turns out that when there is NO avatar set for a user in the KUNENA profile, no avatar will be used from other plugins....

This is not good, the avatar provided by the plugin should always be used regardless if the user has a Kunena avatar or not :)

**Comment by 810** [comment]
if you want images.
backend - kunena - config - avatars - Default avatar type set to image

**Comment by Ruud68** [comment]
OMG, totally missed that, closing now :)
