### ISSUE TITLE
Custom class for bbcode tag [url][/url]

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5977]
**Is your feature request related to a problem? Please describe.**
Yes,
Because:
1. You can't have specific styles for the URLs inside a topic.
2. You can't use JS features targeted to the bbcode link because of the lack of a class or id 
3. Can't use other features like form popup, iframe, etc..

That's why, I'm requesting a single feature, and that single feature is the option to manually add a custom class to the URLs in the bbcode editor

Right now, it is not possible to add a class for a link in bbcode format:
The link is pretty simple, for example:
[url=https://example.com]Test Link[/url]

**Describe the solution you'd like**

I would like to see the option to add a custom class name in the link, for example:
[url=https://example.com class="customclassname"]Test Link[/url]

**Comment by 810** [comment]
You need to use:
[url=https://example.com class=customclassname]Test Link[/url]
