### ISSUE TITLE
Subscrition e-mail from forum not working

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#5978]
**Describe the bug**
wit the upgrade to Kunena version 5.1 no mails are sent via the form (new topics / topic replies)

**To Reproduce**
create a new topic

**Expected behavior**
Mail sent to moderator that new topic is created

**Actual result**
No mail sent
error message:
```
Error 0: Argument 1 passed to KunenaForumMessage::attachEmailBody() must be an instance of Joomla\CMS\Mail\Mail, instance of JMail given, called in /var/www/html/kunena_test/libraries/kunena/forum/message/message.php on line 494
```

This happens on multiple sites, I think the $mail object is 'converted' to a JMail object by another component (e.g. acymailing?).

**System information (please complete the following information)**

Joomla version: 3.8.8
Kunena version: 5.1.0
Php version: multiple
Database version: nultiple

**Additional context**
same issue as described and fixed here: https://github.com/Kunena/Kunena-Forum/issues/5592
same fix in this issue also fixes the issue in 5.1.0

**Comment by 810** [comment]
Looks like that pr isn't merged into 5.1 during the development. will do it.

**Comment by Ruud68** [comment]
it is not, doing it manually fixes the issue. the mail class has some 'glitches' that need precaution when following 'the coding rules' (like chaining not 100% working resulting in Boolean mail 'object': I have learned the hard way :))

**Comment by 810** [comment]
@Ruud68 could you try the nightly and look if the issue still there.

**Comment by xillibit** [comment]
Closed because no answers, open new issue if problem still exist with last version
