### ISSUE TITLE
Buttons in attachments when creating or editing a theme or post

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#5980]
After downloading the file, the buttons appear. In them icons Icomoon.
![2018-06-10_142754](https://user-images.githubusercontent.com/29813939/41201189-c77aa218-6cbb-11e8-8287-aec24c1637dd.png)

Kunena 5.1
Templates - Cripsis
Font Icon - FontAwesome 5

Can you tell what the **Remove inline** button does, or else I can not translate it correctly?

**Comment by mc-hovanskiy** [comment]
FontAwesome 5
Upload:
`<i class="fas fa-upload"></i>`
https://fontawesome.com/icons/upload?style=solid

Trash:
`<i class="fas fa-trash-alt"></i>`
or
`<i class="far fa-trash-alt"></i>`
https://fontawesome.com/icons/trash-alt?style=regular

**Comment by 810** [comment]
we need to redo the js part.

**Comment by 810** [comment]
> Can you tell what the Remove inline button does, or else I can not translate it correctly?

This will remove the attachment from the attachment list under the message, So if you have inserted the image, you can now remove it from the bottom list.
