### ISSUE TITLE
Translation in admin panel

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#5984]
**In the control panel 4 phrases:**
Changelog
Get Support
Check Updates:
Donate:
![2018-06-12_173028](https://user-images.githubusercontent.com/29813939/41299841-05901986-6e6d-11e8-8625-8f5a31748bee.png)

**In the category settings:**
Topic Template
![2018-06-12_180955](https://user-images.githubusercontent.com/29813939/41299879-1ea9bc06-6e6d-11e8-85e4-6d7a605b4299.png)

**Templates page:**
Price
![2018-06-12_181331](https://user-images.githubusercontent.com/29813939/41299956-490729e8-6e6d-11e8-8dd2-27a03b178a6e.png)

I looked through the entire admin panel, the rest is all translated.
Kunena 5.1.1

**Comment by sshcli** [comment]
@xillibit has solved this problem.
This issue should be closed.
