### ISSUE TITLE
Insert attachments in topics didn´t runs 

### ISSUE THREAD

**Issue by DevelPott** [Kunena/Kunena-Forum#5986]
**Describe the bug**
I can upload Attachements without problems, but can´t insert this in a topic. The Button "Insert Attachement" (Alle einfügen) didn´t runs.
Test it with BlueEagle and Crybsis Template 
Think is core problem.

**Actual result**
The Submit Buttons are inactive

**System information (please complete the following information)**

Joomla version: 3.8.8
Kunena version: 5.1.1
Php version: 7.1.18 
Database version: 5.6.35-1 

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Firefox, Chrome, Edge

**Additional context**
Open an thread here:
https://www.kunena.org/forum/k5-1-support/152776-kunena-5-1-cant-insert-attachments-images-in-topic

**Comment by 810** [comment]
Do you have still this issue?

**Comment by xillibit** [comment]
No update, so i close
