### ISSUE TITLE
Rename social Odnoklassniki

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#5988]
Change the name of the social network. It is necessary that instead of **ok** there was **odnoklassniki**.
This creates problems with FontAwesome icons.

www\libraries\kunena\user\user.php
line 2138:
`'odnoklassniki'         => array('url' => 'https://ok.ru/##VALUE##', 'title' => JText::_('COM_KUNENA_MYPROFILE_OK'), 'nourl' => '0'),`

I edit the 2084 line in this file so:
`return '<a href="' . $this->escape($url) . '" ' . ' target="_blank" title="' . $title . ': ' . $value . '"><span class="fab fa-' . $name . '"></span></a>';`

All the buttons I use are displayed correctly except for classmates, since they have an icon:
`<i class="fab fa-odnoklassniki"></i>`
https://fontawesome.com/icons/odnoklassniki?style=brands

Can I put these buttons social networks in a file that I can override later, so that I do not manually delete unnecessary social networks?
Thanks!

**Comment by mc-hovanskiy** [comment]
And remove from the list of social networks **icq**. This is an obsolete messenger and has long been unused. ICQ is dead.

**Comment by 810** [comment]
This shoulbe be done by language file only.

icq is still live.

**Comment by mc-hovanskiy** [comment]
Can I rename it?

www\libraries\kunena\user\user.php 
line 2138:
`'odnoklassniki' => array('url' => 'https://ok.ru/##VALUE##', 'title' => JText::_('COM_KUNENA_MYPROFILE_OK'), 'nourl' => '0'),`

**Comment by 810** [comment]
No, then you need to change database also, so I have ok for the code. And use Odnoklassniki on the language strings.

**Comment by mc-hovanskiy** [comment]
Sorry, after correction to the class, the icon in the user's profile will be "odnoklassniki"? I need to rename the button class css in the user profile. I thought the class is taken from the code I specified.


icq bought mail.ru (he buys dead projects that were once popular). For 8 years nobody has been using ICQ, but the site exists.
I do not insist, I just decided to let you know because I know ICQ and when I used it.

**Comment by mc-hovanskiy** [comment]
It is necessary that the ccc class be: **kicon-profile kicon-profile-odnoklassniki**
Now: kicon-profile kicon-profile-ok

![2018-06-27_151537](https://user-images.githubusercontent.com/29813939/41973453-a6e30e04-7a1d-11e8-85b9-7101e049b5e4.png)

**Comment by 810** [comment]
For now we need to use ok.
For Kunena 6.0 we can use the full name. Else there will be b/c issues with templates.

The kicon-profile-ok is correct.
