### ISSUE TITLE
Search result is the same as the number of topic per page

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#5989]
**Describe the bug**
https://www.kunena.org/forum/36-German/152869-suchergebnis-im-forum-beschnitten-nicht-navigierbar

**To Reproduce**
Enter the search keyword **Joomla** at kunena.org

**Expected behavior**
All search results

**Actual result**
You get only 30 results (the same number as topics per page)
You get always the same number of search result as is setting Topics per page

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.8.8
Kunena version: 5.1.2-DEV
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sshcli** [comment]
Duplicated. See https://github.com/Kunena/Kunena-Forum/issues/5863

**Comment by rich20** [comment]
Ah.. sorry, I close this here
