### ISSUE TITLE
Search box in 404 Kunena view is not useful

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#5992]
**Steps to reproduce the behavior:**
1. Type a wrong URL in your address bar to see the kunena 404 error page.
For example: Type **example.com/foru** in the address bar instead of **example.com/forum**

**Expected behavior**
The search box in the 404 Kunena view is not useful and should be removed
or
Make the proper fix in order to make it useful for search into kunena content 

**Actual result**
<img width="515" alt="search" src="https://user-images.githubusercontent.com/12942731/41427118-e2545ed8-6fd3-11e8-9cd3-7a3ab2912661.PNG">

<img width="269" alt="bad2" src="https://user-images.githubusercontent.com/12942731/41427738-dbecb00c-6fd5-11e8-9144-3d13466db36e.PNG">

**System information (please complete the following information)**
Joomla version: 3.8.8
Kunena version: 5.1.1 and 5.1.2-DEV 2018-06-13
Php version: 7.2.6 and 7.1.18
Database version: MySQL 5.6.39

**Desktop (please complete the following information):**
OS: [Windows]
Browser [Google Chrome]
Version [Version 67.0.3396.87]

**Comment by mc-hovanskiy** [comment]
Here, Kunena has nothing to do. This is site template page, not the forum.
Here she is: www\templates\protostar\error.php

There is a plugin Kunena Search, there settings.
