### ISSUE TITLE
Birthdate (frontend) date format wrong

### ISSUE THREAD

**Issue by sozzled** [Kunena/Kunena-Forum#6001]
**Describe the bug**
See also #6000 and #5921
1)  Date defaults to today
2)  US date format (mm/dd/yyyy) does not match tooltip

**To Reproduce**
1. Go to frontend, login, select user, edit user
2. View "Profile Information"  (see attached screenshot)
![k511_birthdate-frontend](https://user-images.githubusercontent.com/877778/41629207-9f19b158-746b-11e8-8bc5-6623ecb298d6.png)

3. If the user has not entered a birthdate, the date defaults to today; the date is displayed in US date format, the displayed date does not match the tooltip

**Expected behavior**
1)  If no birthdate entered, there should be no "default" date displayed
2)  The date format should be (a) selectable, or (b) "international date format", or (c) clearly dd-mmm-yyyy

**Actual result**
Press save and the date displayed is saved in the user profile.

**System information (please complete the following information)**

Joomla version: 3.8.8
Kunena version: 5.1.1
Php version: 5.6.36
Database version:  MySQL 5.6.38

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  MS Windows (7, 8.1, 10)
 - Browser:  Firefox, Chrome

**Comment by 810** [comment]
duplicated

**Comment by sozzled** [comment]
This is not a duplicate.  It's a different problem.  Although there are similarities between this issue and the issue described in #5921, I was unable to replicate the conditions in #5921.
