### ISSUE TITLE
RSS: Add value "None" to Characters Per Item

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6002]
**Steps to reproduce the behavior:**
Configuration->RSS->Limit Number of Characters Per Item

**Expected behavior**
![good5](https://user-images.githubusercontent.com/12942731/41736570-ef53844c-755a-11e8-9d06-1d4d4cb56b89.png)

**Actual result**
![bad5](https://user-images.githubusercontent.com/12942731/41736577-f331ba02-755a-11e8-8f48-c17502feb6df.png)

**System information (please complete the following information)**
Joomla version: 3.8.8
Kunena version: 5.1.1
Php version: 7.2.6
Database version: MySQL 5.6.39

**Desktop (please complete the following information):**
OS: [Windows]
Browser [Google Chrome]
Version [Version 67.0.3396.87]

**Comment by sshcli** [comment]
If option "None" is selected, People won't be able to steal content from your website via RSS

**Comment by 810** [comment]
but then there is no message, so the rss feed isn't correctly displayed

**Comment by sshcli** [comment]
Yes, it will show topics title only, without any description. 
Still useful if you want people to get notified about the new topics on the forum without let them copy the whole content via RSS.

Limiting the number of character is not enough to stop content thief, they use tools that overrides that setting.

However, is just an idea, please feel free to close this issue if not possible. No hard feelings
