### ISSUE TITLE
[object Object] when click attachment icon

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6003]
**Steps to reproduce the behavior:**
1. Create a topic and add a .png picture as attachment
2. Go to the topic and make a click in the attachment icon

**Expected behavior**
When you click the icon of the attachment, You should not see the message [object Object] in a modal

**Actual result**
When you click the icon of the attachment, you will see the message [object Object] in a modal

![bad6](https://user-images.githubusercontent.com/12942731/41737532-929e4860-755d-11e8-9233-4224d8161fa8.PNG)

**System information (please complete the following information)**
Joomla version: 3.8.8
Kunena version: 5.1.1
Php version: 7.2.6
Database version: MySQL 5.6.39

**Desktop (please complete the following information):**
OS: [Windows]
Browser [Google Chrome]
Version [Version 67.0.3396.87]

**Additional context**
This bug does not exist in K.5.0.14

**Comment by xillibit** [comment]
Is-it a dupicate with this one https://github.com/Kunena/Kunena-Forum/issues/5997 ?

**Comment by sshcli** [comment]
Yes. Sorry.
I'm closing this one.

**Comment by cypisekcypisek** [comment]
Hello,
I do realise that you have closed this tread but I cannot find anywhere solution to this problem, which I currently experiencing after changing to blue eagle template. Reverting to Crypsis doesn't work either.  Could you please help with it or direct me to an answer. Why template opens this object object window message when click?  The funny thing is when I do right mouse click on attachment I can download it.  Thank you

**Comment by sshcli** [comment]
@cypisekcypisek I can confirm that this problem has been solved.
Please make sure you are running the latest kunena version (K5.1.3)

If you are using Blue Eagle 5 you should report the problem here:
https://www.kunena.org/forum/blue-eagle-5

**Comment by cypisekcypisek** [comment]
Thank you for your quick reply. Yes I'm running the latest version of kunena, and cleared joomla cache as well but the bug still prevails. When I revert to Crypsis3 I get unable to access the file message instead. I updated joomla and kunena before installing the new eagle template. Before then attachments worked when clicked but it wasn't showing an icon and the popover was displaying white font on light gray background so nobody could see the name of the attachment hence the change to new template, however now the attachments now don't work at all on click. 
Unfortunately I cannot access the blue-eagle forum I get 403 forbidden error (I'm logged in)

**Comment by rich20** [comment]
I'm sorry, but Github is not intended for support. If you have problems, ask in the Kunena forum please.
