### ISSUE TITLE
Log shows not all actions

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6010]
**Describe the bug**
Log shows not all actions

**To Reproduce**
1. Go to configuration -> tab Users and set "Define if you want to log action or moderation = Yes"
2. Edit a message in the frontend and remove the complete content
3. Save it (the message will deleted)

**Expected behavior**
This action should be in the Logs

**Actual result**
It willl no logged so you don't know, whether it was a delete action by Moderator or User

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.8.8
Kunena version: 5.1.2-DEV
Php version: 7.2.1
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 810** [comment]
then I will get: Cannot save message: Message body is empty!
