### ISSUE TITLE
Uploaded avatar will not saved

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6020]
**To Reproduce**
1. Open the console and upload a avatar 
2. Click on 'Save'

**Actual result**
Each click on Save shows this error:
An invalid form control with name='websiteurl' is not focusable.

**System information (please complete the following information)**

Joomla version: 3.8.10 and 3.8.11-dev
Kunena version: 5.1.2-DEV
Php version: 7.0.20 and 7.2.1
Database version:

**Desktop (please complete the following information):**
 - Browser [e.g. Chromium, Opera]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 810** [comment]
Is already been fixed on nightly build

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/commit/41f8a3d346409d9c9614b283bd78af3590b75512

**Comment by rich20** [comment]
This issue is solved
