### ISSUE TITLE
Bootstrap 3 template and Crypsisb3 : You can't scroll the page when you click on quick reply

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6022]
**Describe the bug**
https://www.kunena.org/forum/36-German/153342-fehler-bei-kurzantwort-funktion

**To Reproduce**
1. Go to Crypsisb3 and set 'Type Quickreply = Default'
2. Click in the frontend on 'Quick Reply'
3. Try to scroll the page

**Expected behavior**
To scroll should be possible

**Actual result**
You can't scroll
It's this code in the bootstrap.css which cause the problem. The scrollbar from the browser window will also hidden with this code:
```
.modal-open {
  overflow: hidden;
}
```
This code in the Kunena custom.less solve it, but I'm not sure if that's only a workaround

```
.modal-open {
  overflow: auto;
}
```
**System information (please complete the following information)**
Joomla version: 3.8.10
Kunena version: 5.1.2-DEV
Php version: 7.0.25
Database version:

**Desktop (please complete the following information):**
 - Tested with Joomla Templates: [Purity III and  t3_bs3_blank]
 - Browser [e.g. Chromium, Opera and Firefox]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 810** [comment]
We can't fix this one.

It should be added on the joomla template css, or on the kunena custom. 
But I can't be on the main kunena less files. Because we can't control the body.
