### ISSUE TITLE
 Ban from forum does not work (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6023]
**To Reproduce**
Try to ban a user (Ban From forum)

**Expected behavior**
Ban from forum should work

**Actual result**
Ban from forum does not work. If you ban a user from the Forum, he is only logged out. The user can login again and still write. 
Here is part 1 of this issue: https://github.com/Kunena/Kunena-Forum/issues/5814

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.8.11-dev
Kunena version: 5.1.2-DEV
Php version: 7.2.1 and 7.0.25
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rich20** [comment]
**Found more informations:**

Example:
1. Ban a logged in user only from the Forum
result
The user will only logged out but shows in the ban history as banned
2. Unban this user now
3. Try again this user ban from the Forum
it adds only a new row in the ban history but the user will not banned

It's not possible to ban a user from the Forum, when this user already is listed in the ban history, unless you remove the user from the table #__kunena_users_banned.

**Comment by WebGuy99** [comment]
I'm also getting the same problem. I try to ban a user from the Kunena Forum, click New Ban, site refreshes back to the homepage but the user isn't banned.
I can ban the user from the backend>Kunena>Users page but that doesn't allow me to specify various fields such as Public Reason for Ban, Ban End Time etc.

System information

Joomla version: 3.8.10
Kunena version: 5.1.1
Php version: 5.6
Database version:

Desktop (please complete the following information):

    OS: [e.g. Windows 10]
    Browser [e.g. Firefox]

**Comment by xillibit** [comment]
Is-this issue still exist ? I have just tried to reproduce but i'am not able

**Comment by rich20** [comment]
> 1. Ban a logged in user only from the Forum
result
The user will logged out and shows in the ban history as banned
> 2. Unban this user now
> 3. Try again this user ban from the Forum
it adds only a new row in the ban history but the user will not banned

> It's not possible to ban a user from the Forum, when this user already is listed in the ban history, unless you remove the user from the table #__kunena_users_banned.

The problem still exists. it's not possible to ban a user a second time from the forum (tested with K5.1.19-dev).

**Comment by rich20** [comment]
> Is-this issue still exist ? I have just tried to reproduce but i'am not able

hmm... on k.org I'm also not able to reproduce this error. It seems to be a special problem, but I do not think it's a php problem. I had since my first post here and today several php upgrades.
