### ISSUE TITLE
Warn users before delete category

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6033]
**Steps to reproduce the behavior:**
Go to the backend and delete a category that contains several topics.

**Expected behavior**
Users should be warned when they attempt to delete a category in the backend, because once deleted all the topics in that category will be inaccessible.

**Actual result**
There is no warning

**System information (please complete the following information)**
Joomla version: 3.8.10
Kunena version: 5.1.1
Php version: 7.2.7
Database version: MySQl 5.6.39

**Comment by rich20** [comment]
It should be an extensive warning. It deletes also the related content from the tables kunena_topics, kunena_messages and kunena_messages_text and restore is only with a database backup possible.
