### ISSUE TITLE
Edit the poll after someone has voted

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6034]
**Describe the bug**
We have in the backend this option:
Set if you want allow the user to edit the poll when someone has voted. 
But edit is only possible, when no vote exists.
- [ ] It should be always possible, edit the poll when no vote or answer in this poll topic exists (so can the user potential errors to correct)
- [ ] **If you want** allow the user to edit the poll when someone has voted (edit is currently not possible)
- [ ] **If you not want** allow the user to edit the poll when someone has voted (with this setting you can also not edit when no vote exist)
- [ ] There is no modal hint when edit is not allowed

**Comment by xillibit** [comment]
> It should be always possible, edit the poll when no vote or answer in this poll topic exists (so can the user potential errors to correct)

I have tried with the last build, for me it's possible

> If you want allow the user to edit the poll when someone has voted (edit is currently not possible)

It's the case since 5.1.0 or even before

The settings added doesn't allow to edit poll when someone has voted, the autorisation check need to be changed

**Comment by rich20** [comment]
> > If you want allow the user to edit the poll when someone has voted (edit is currently not possible)
> 
> It's the case since 5.1.0 or even before

I'm not sure but I think it was even before. But we have this option only since K5.1. I've tested now a older K5.1.0-dev build from 2018-05-19, and in this version is this setting option not yet available.

We have now:

- [x] **Allow** the user to edit the poll when someone has voted
- [x] **Not allow** the user to edit the poll when someone has voted
- [ ] There is no modal hint when edit is not allowed
- [ ] It should be always possible, edit the poll when no vote or answer in this poll topic exists (so can the user potential errors to correct. Currently you can only edit, when edit after vote is allowed)
- [ ] Allow edit when someone has voted:  If you remove a option where already has votest, it remain the number of voters (see image)
![bildschirmfoto von 2018-07-16 15-20-33](https://user-images.githubusercontent.com/888847/42761174-0ed16148-890d-11e8-8965-a7b4c6f704de.png)

**Comment by xillibit** [comment]
> There is no modal hint when edit is not allowed

It was present before with my last changes

> It should be always possible, edit the poll when no vote or answer in this poll topic exists (so can the user potential errors to correct. Currently you can only edit, when edit after vote is allowed)

I will change the check even if edit poll isn't allowed, to allow to edit if there are no votes or no answers

> Allow edit when someone has voted: If you remove a option where already has votest, it remain the number of voters (see image)

When you remove a poll option, it doesn't remove the users who has voted for the option. I have found an old TODO from mathias on this point : 

```
// TODO: Votes in #__kunena_polls_users will be off and there's no way we can fix that
				// Maybe we should allow option to reset votes when option gets removed
				// Or we could prevent users from editing poll..
```

**Comment by rich20** [comment]
- [x] **Allow** the user to edit the poll when someone has voted
- [x] **Not allow** the user to edit the poll when someone has voted
- [x] It should be always possible, edit the poll when no vote or answer in this poll topic exists (so can the user potential errors to correct. Currently you can only edit, when edit after vote is allowed)

In principle all works as it should, but you get the edit modal also when edit is not allowed anymore.

**Comment by xillibit** [comment]
I will take a look for the modal

**Comment by xillibit** [comment]
Replaced by : https://github.com/Kunena/Kunena-Forum/issues/7730
