### ISSUE TITLE
PDFs in messages

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6035]
**Describe the solution you'd like**

Earlier it was displayed like this (image) in the post and click on it has opened the PDF. You could read the pdf in full size. Now is the PDF minimized to the message window and hard to read. 
Website operators should have the choice whether a PDF is displayed directly or handle as file.

![bildschirmfoto von 2018-07-10 17-14-11](https://user-images.githubusercontent.com/888847/42522232-e3eb9774-846a-11e8-9922-875e5ab90914.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by mc-hovanskiy** [comment]
Also this problem.
Previously Kunena-5.0.x PDF was opened in the browser, now downloaded.
Is there any way to make the PDF open in the browser?

**Comment by mc-hovanskiy** [comment]
And is it possible if a PDF file is attached to display it with the corresponding icon?

FontAwesome 5
`<i class="fas fa-file-pdf"></i>`

In Icomoon which by default in Joomla there is no icon of PDF. You can put:
`<i class="icon-file-2"></i>`

**Comment by 810** [comment]
This are browsers choices we can't change that.

![image](https://user-images.githubusercontent.com/876623/44006110-be258cec-9e7e-11e8-8658-f70781ba0b5f.png)

For the icons, we have a open issue for ext images, will be added on k6.0
