### ISSUE TITLE
Limit max links in messages also affects uploaded pictures

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6039]
**To Reproduce**

1. Set Max Links in message = 0
2. Set Limit Attachments = 8 (default value)
3. Login as normal user and add images in the message
4. Click on Submit

**Expected behavior**
The images should be embed in the message

**Actual result**
You have too many links in your message, please decrease them!

**System information (please complete the following information)**

Joomla version: 3.8.10 and 3.8.11-dev
Kunena version: 5.1.2-dev
Php version: 7.0.25 and 7.2.1
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pgasiorowski** [comment]
It seems that [this regex](https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/components/com_kunena/controllers/topic.php#L1094) is too wide: 
```php
preg_match_all('@\(((https?://)?([-\\w]+\\.[-\\w\\.]+)+\\w(:\\d+)?(/([-\\w/_\\.]*(\\?\\S+)?)?)*)\)@', $text, $matches);
```

One way to address the issue could be to also count either:
- `/<img\s[^>]*src=\"([^\"]*)\"[^>]*>/siU`
or more generally
- `<img |<object |<iframe `
and subtract the result from $countlink . Happy to provide a PR if you agree this is a good solution.

**Comment by 810** [comment]
then only img are counted, but spammers use also normal urls. 
Also we have automatic autolink.

So we need to find a other fix for it.

**Comment by 810** [comment]
Oh you wanted added extra code. Then its ok. Please create a pr for it. If you have more fixes, you can always do a pr.

**Comment by pgasiorowski** [comment]
Correct, I should be able to send a PR either today or tomorrow

**Comment by pgasiorowski** [comment]
PR in place. Slightly different approach than originally proposed as I came across a number of hmm's and ahhh's for detecting images (autolinking, non-image attachements, emojis, 3rd party plugins)

Generally my thinking is that spam would always link to external resources and internal links are harmless thus I can't see a good reason why Kunena should need to block them.
This is also implied by the description of the config option:
`Max Links in message` - `Enter here the max links in a message to prevent spam`

Worth considering: Renaming option "Max Links in message" to "Max external links in message"

Let me know what you think

**Comment by 810** [comment]
Looks good, I have merged the pr.
