### ISSUE TITLE
Kunena mails are not sent to the moderators

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#6044]
https://www.kunena.org/forum/k5-1-support/151272-problem-with-email?start=10

**Comment by Kubik-Rubik** [comment]
I've just posted my workaround and a solution here: https://www.kunena.org/forum/k5-1-support/151272-problem-with-email?start=20#202683

Keep up the good work!

**Comment by xillibit** [comment]
Can-be closed this one ?

**Comment by 810** [comment]
i was waiting for confirmation that the fix worked, but still no replies

**Comment by mijalis** [comment]
partially ok...
get('mailfrom'), get('fromname'), gets vars from Joomla, it should get them from Kunena's config.

**Comment by xillibit** [comment]
> 
> 
> partially ok...
> get('mailfrom'), get('fromname'), gets vars from Joomla, it should get them from Kunena's config.

I see no places anymore where the mail and fromname are used from Joomla!
