### ISSUE TITLE
Linkedin company is not saved

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6052]
**Steps to reproduce the behavior:**
Profile->Edit->Edit Profile Information->Linkedin Company

**Expected behavior**
Linkedin company should be saved

**Actual result**
Linkedin company is not saved

**System information (please complete the following information)**
Joomla version: 3.8.10
Kunena version: 5.1.3-DEV
Php version: 7.2.7
Database version: MySQL 5.6.39

**Comment by xillibit** [comment]
In frontend or backend or both part ?

**Comment by sshcli** [comment]
My test was in frontend only
![linked](https://user-images.githubusercontent.com/12942731/42939434-a4495b82-8b23-11e8-9c03-12ff51b98495.PNG)
