### ISSUE TITLE
Kunena 5.1.x system plugin breaks display JoomGallery images

### ISSUE THREAD

**Issue by MrMusic** [Kunena/Kunena-Forum#6053]
Hi Developers, 
unfortunately, the detail/original images in JoomGallery Frontend are no longer displayed when the plugin System-Kunena is activated.

Steps to reproduce the issue:
Joomla 3.8.10
JoomGallery 3.3.4
Kunena 5.1.2 with activated system plugin

Joomla Global Configuration:
Search Engine Friendly URLs: Yes
Add Suffix to URL: Yes

see also:
http://www.en.joomgallery.net/faq/general-faq/problem-with-certain-system-plugins.html
and
https://www.kunena.org/forum/k5-1-support/153320-kunena-5-1-1-crashes-current-joomgallery-3-3-4-with-joomlasef-enabled
Thank you for your attention.

**Comment by 810** [comment]
For me its working normally, 
Default install
I added new category
Uploaded some fotos

created a menu item: joomgallery - > category view
selected the category.

Then I check frontend, and all is working fine.

(I'm running nightly build from Joomla, maybe they fixed the joomla bug)

**Comment by MrMusic** [comment]
>Then I check frontend, and all is working fine.

The problem only affects the detail/original images, not the thumbnails.


>Joomla Global Configuration:
>Search Engine Friendly URLs: Yes
>Add Suffix to URL: Yes

Do you tried with the same settings?


>(I'm running nightly build from Joomla, maybe they fixed the joomla bug)

I tried with current Joomla 3.8.11 again and the problem still exist.
