### ISSUE TITLE
PHP Warning:  explode() expects parameter 2 to be string

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6055]
**Steps to reproduce the behavior:**
1. Upgrade from 5.1.1 to 5.1.2
2.  Upgrade from 5.1.2 to 5.1.3-dev

**Expected behavior**
No PHP Warnings in error_log

**Actual result**
PHP Warning:  explode() expects parameter 2 to be string, array given in /home/username/public_html/components/com_kunena/models/search.php on line 131

**System information (please complete the following information)**
Joomla version: 3.8.10
Kunena version: 5.1.3-DEV
Php version: 7.2.7
Database version: MySQL 5.6.39

**Comment by sshcli** [comment]
IMO, the cause could be one of these changes:
https://github.com/Kunena/Kunena-Forum/commit/52b1e2f
https://github.com/Kunena/Kunena-Forum/commit/965d181

**Comment by 810** [comment]
updating does not use the search model, which search options did you test

**Comment by 810** [comment]
Leave a comment
