### ISSUE TITLE
BreadcrumbList is duplicated 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6060]
**Steps to reproduce the behavior:**
1. Run Structured Data validation in the following link:
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fk51.jobsnear.net%2Fforum%2Findex

**Expected behavior**
Only one BreadcrumbList type  is needed.

![1](https://user-images.githubusercontent.com/12942731/43208040-71f1b976-8ff7-11e8-9345-fe0214aacc3e.PNG)

**Actual result**
There are two BreadcrumbList type, one for each Breadcrumb in the page.

![2](https://user-images.githubusercontent.com/12942731/43208044-750b2c28-8ff7-11e8-9012-8c6aa2800b1b.PNG)

**System information (please complete the following information)**
Joomla version: 3.8.10
Kunena version: 5.1.3-DEV
Php version: 7.2.7
Database version: MySQL 5.6.39

**Additional context**
The use of json-ld is the most recommended solution for this (above all others)
More information at:
https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by 810** [comment]
I know, but we have 2x the breadcrumb module position. So this is correct.
