### ISSUE TITLE
Invalid property value max-width: auto;

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6072]
**Steps to reproduce the behavior:**
1. Create a new topic and insert this:
`[img]https://us-east-1.tchyn.io/snopes-production/uploads/2017/05/earth_cosmic_rays_fb.jpg[/img]`
2. Open the console and select the image

**Expected behavior**
![autogood](https://user-images.githubusercontent.com/12942731/43462774-0060d28a-94a5-11e8-9437-ebd2a3a75dc3.PNG)

**Actual result**
Invalid property value max-width: auto;

![autobad](https://user-images.githubusercontent.com/12942731/43462759-fb396f92-94a4-11e8-828b-98480300b1f6.PNG)

**System information (please complete the following information)**
Joomla version: 3.8.10
Kunena version: 5.1.3-DEV
Php version: 7.2.8
Database version: MySQL 5.6.39

**Comment by 810** [comment]
we need this for responsive images

**Comment by sshcli** [comment]
Maybe `max-width: 100%;`

**Comment by sshcli** [comment]
What I mean is that "Auto" is not allowed in max-width.
Should use something else

**Comment by 810** [comment]
the auto is the one correct, else it will break. So I will leave it.
