### ISSUE TITLE
Search results pagination broken

### ISSUE THREAD

**Issue by vincentwolsink** [Kunena/Kunena-Forum#6081]
**Describe the bug**
The search results pagination seems broken. The results are always maximum one page. At the bottom of the page the counter displays as if only 1 result was found. `Displaying 1 - 30 out of 1 results.`

This also happens on your own forum installation.

**To Reproduce**
1. Go to https://www.kunena.org/forum/search
2. Search for some common keyword like 'site'
3. Only 30 results are displayed.
4. Scroll to the bottom of the page to see there is no pagination and only `1 results.`

**Expected behavior**
Display all search results in a paginated way and show the actual number of results in the counter at the bottom of the page.

**Actual result**
`Displaying 1 - 30 out of 1 results.`

**System information (please complete the following information)**

This is my own Kunena installation information, but it also happens on the kunena.org forum.

Joomla version: 3.8.11 Stable
Kunena version: 5.1.2
Php version: 7.0

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by sshcli** [comment]
Duplicated. See https://github.com/Kunena/Kunena-Forum/issues/5863

**Comment by vincentwolsink** [comment]
Although I think the behaviour is different from #5863 it may have the same cause. Will close this one then.
