### ISSUE TITLE
Fag fuckers

### ISSUE THREAD

**Issue by roboticstogo** [Kunena/Kunena-Forum#6086]
Fuck you and stupid fucking gay ass code. Get your own, bitches. 

Post A Prayer
www.postaprayer.org

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sophist-UK** [comment]
Spam - user needs to be reported to Github ops.
