### ISSUE TITLE
Rating: Instead of stars you have only 5 points, displayed in a vertical line

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6095]
**To Reproduce**
1. Set in the configuration -> tab Frontend "Allow rating = Yes"
2. Choose a category and allow rating
3. Rate a topic

**Expected behavior**
Should be displayed correctly

**Actual result**
You see everywhere (in topics, on recent topics page and so on) instead of stars only points in vertical positions

**System information (please complete the following information)**

Joomla version: 3.8.11 and 3.8.12-dev
Kunena version: 5.1.4-DEV
Php version: 7.0.30 and 7.2.7
Database version: 5.5.58

**Additional context**
This problem exists in Crypsis and Crypsisb3

**Comment by sshcli** [comment]
Screenshot please, I can't see the problem

**Comment by rich20** [comment]
Tested with Firefox, Chromium and Opera, so it's not a browser issue. Also tested on different test pages.


![bildschirmfoto von 2018-08-23 00-59-58](https://user-images.githubusercontent.com/888847/44495674-3970a900-a671-11e8-9687-c49c9bab21d6.png)

**Comment by sshcli** [comment]
Yes, I can see the error now.
Tested with latest nightly build:
pkg_kunena_v5.1.4-DEV_2018-08-22.zip

**Comment by sshcli** [comment]
<img width="426" alt="error" src="https://user-images.githubusercontent.com/12942731/44496116-fac2fa80-a640-11e8-814a-cb144c1e3400.PNG">
