### ISSUE TITLE
Birthdate issue - YY instead of YYYY in edit mode

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#6108]
**Describe the bug**
I have been registered a new user via Joomla back-end.
Then go to front-end > Kunena > log in as the new user and go to Edit profile.
I see the following date:
09/04/18
I click on date picker, select any date and see this one:
09/10/1918

There is a problem with the year. There is YY instead of  YYYY when we edit profile first time.

**Expected behavior**
There should be YYYY all the time.

**Screenshots**
![screen shot 2018-09-04 at 22 02 16](https://user-images.githubusercontent.com/3432048/45052222-dcbcb780-b08e-11e8-841c-aa61ddf59b17.png)
![screen shot 2018-09-04 at 22 02 24](https://user-images.githubusercontent.com/3432048/45052223-df1f1180-b08e-11e8-954e-bcb553ed6718.png)

**System information (please complete the following information)**

Joomla version: 3.8.12
Kunena version: 5.1.3
Php version: 7.0.31
Crypsis3 template

**Comment by 810** [comment]
should be fixed now (5.1.6)
