### ISSUE TITLE
Backend: no action when I clicking on Moderator icon

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#6112]
**Describe the bug**
I go to Site Backend > Kunena > Users and click on Moderator icon. It takes no action.
![screen shot 2018-09-12 at 09 44 47](https://user-images.githubusercontent.com/3432048/45406966-c0adad00-b670-11e8-8281-0058887bbd2a.png)

 

Joomla version: 3.8.12
Kunena version: 5.1.3

**Comment by 810** [comment]
We have only show if moderator, it should not set a moderator because of the permissions.

**Comment by 810** [comment]
maybe I can add only unmoderated to it.
