### ISSUE TITLE
DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6115]
**Steps to reproduce the behavior:**
1. UserX has this value as birthday: 0000-00-00
2. Try to change the rank to UserX

**Expected behavior**
No error

**Actual result**
DateTime::__construct(): Failed to parse time string (11/30/-0001) at position 5 (/): Unexpected character
<img width="547" alt="error" src="https://user-images.githubusercontent.com/12942731/45786634-5502ab80-bc3f-11e8-97d8-4fd12c8b9a5d.PNG">

**System information (please complete the following information)**
Joomla version: 3.9.0-Beta2
Kunena version: 5.1.4-DEV
Php version: 7.2.9
Database version: MySQL 5.6.40

**Comment by xillibit** [comment]
You have the issue only on J!3.9.0 beta not on J!3.8.x ?

**Comment by sshcli** [comment]
I remember I saw the error once in 3.8

**Comment by xillibit** [comment]
Only in backend not in frontend ?

**Comment by sshcli** [comment]
All times I saw the error was in the backend, never in the front.

**Comment by sshcli** [comment]
Use this query to check if you have users with this problem in your website:

SELECT * FROM `#_kunena_users` WHERE `birthdate` = '0000-00-00'

**Comment by sshcli** [comment]
In frontend you will see it like this when editing the profile:
![birth](https://user-images.githubusercontent.com/12942731/47593963-6aa67780-d947-11e8-984c-b1c91ca88f98.PNG)

**Comment by sshcli** [comment]
Also, we need the option to show/hide birthday in profile:

![bad10](https://user-images.githubusercontent.com/12942731/47594666-6760bb00-d94a-11e8-90ae-e67d7b56b39d.PNG)

![good10](https://user-images.githubusercontent.com/12942731/47594669-6d569c00-d94a-11e8-8efd-dd01df054174.PNG)

**Comment by sshcli** [comment]
You get also the error in frontend when user click save button on profile edit:

![error](https://user-images.githubusercontent.com/12942731/47594941-b529f300-d94b-11e8-8e6f-84966d9b927c.PNG)

**Comment by sshcli** [comment]
People having this error can't save/edit/remove other values from the profile like facebook, instagram, etc..

**Comment by sshcli** [comment]
1027 people that can't edit profile

![results](https://user-images.githubusercontent.com/12942731/47595530-ddffb780-d94e-11e8-9a05-507a8198a02e.PNG)

**Comment by sshcli** [comment]
In the meanwhile, I have fixed the problem only for my website with the following query:

`UPDATE `prefix_kunena_users` SET `birthdate` = '2018-10-26' WHERE `birthdate` = '0000-00-00'`

I prefer babies registered in my website than the error
