### ISSUE TITLE
Styles in editor Wyssibb

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#6118]
After update lost styles in Wyssibb editor.
Panel with buttons for desktop (wysibb-toolbar) - width: 70px;

Kunena version: 5.1.4
Templates: Crypsis, Protostar.

**Comment by 810** [comment]
For me it looking ok.
components/com_kunena/template/crypsis/assets/css/wbbtheme.css
The 70px is loaded on line 48.
But its overridden by line 907 to auto.


Could you add a screenshot.

**Comment by mc-hovanskiy** [comment]
Sorry, I have a problem with merge css (plugin).

Styles work correctly. Close this question.
