### ISSUE TITLE
Topic title will not changed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6119]
**Describe the bug**
Topic title will not changed

**To Reproduce**
1. Set in the configuration tab Frontend "Let users edit the subject = Yes" (is default)
2. Click on Reply and change the subject 

**Expected behavior**
If you change the title it should be changed if you save the message

**Actual result**
The original title remain

**System information (please complete the following information)**

Joomla version: 3.8.13-dev and 3.9.0-dev
Kunena version: 5.1.5-DEV
Php version: 7.2.7
Database version: 5.5.58

**Desktop (please complete the following information):**
 - Browser Chromium, Opera and Firefox

**Comment by 810** [comment]
should now be fixed
