### ISSUE TITLE
Several codes in the bbcode editor are hardcoded

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6122]
**Describe the bug**
https://www.kunena.org/forum/k5-0-support/154481-tooltip-text-not-translated

https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/components/com_kunena/template/crypsis/assets/js/markitup.editor.js#L46-L68
Line 46 - 68 should be changed to: 

						{name:Joomla.JText._("COM_KUNENA_EDITOR_SIZE_VERY_VERY_SMALL"), openWith:'[size=1]', closeWith:'[/size]' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_SIZE_VERY_SMALL"), openWith:'[size=2]', closeWith:'[/size]' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_SIZE_SMALL"), openWith:'[size=3]', closeWith:'[/size]' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_SIZE_NORMAL"), openWith:'[size=4]', closeWith:'[/size]' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_SIZE_BIG"), openWith:'[size=5]', closeWith:'[/size]' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_SIZE_SUPER_BIGGER"), openWith:'[size=6]', closeWith:'[/size]' }
						]},{className: 'colors', name:Joomla.JText._("COM_KUNENA_EDITOR_COLORS"), key:'', openWith:'[color=[![Color]!]]', closeWith:'[/color]',dropMenu: [
						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_BLACK"),	openWith:'[color=black]', 	closeWith:'[/color]', className:'col1-1' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_ORANGE"),	openWith:'[color=orange]', 	closeWith:'[/color]', className:'col1-2' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_RED"), 	openWith:'[color=red]', 	closeWith:'[/color]', className:'col1-3' },

						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_BLUE"), 	openWith:'[color=blue]', 	closeWith:'[/color]', className:'col2-1' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_PURPLE"), openWith:'[color=purple]', 	closeWith:'[/color]', className:'col2-2' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_GREEN"), 	openWith:'[color=green]', 	closeWith:'[/color]', className:'col2-3' },

						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_WHITE"), 	openWith:'[color=white]', 	closeWith:'[/color]', className:'col3-1' },
						{name:Joomla.JText._("COM_KUNENA_EDITOR_COLOR_GRAY"), 	openWith:'[color=gray]', 	closeWith:'[/color]', className:'col3-2' }
		]
	}, {separator: '|'}, {
		className: 'bulletedlistbutton',
		name: Joomla.JText._('COM_KUNENA_EDITOR_ULIST'),

Between line 23 - 63 It needs a completion https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/components/com_kunena/template/crypsis/layouts/topic/edit/default.php#L23-L63
This are missing strings:

Text::script('COM_KUNENA_EDITOR_COLOR_BLACK');
Text::script('COM_KUNENA_EDITOR_COLOR_ORANGE');
Text::script('COM_KUNENA_EDITOR_COLOR_RED');
Text::script('COM_KUNENA_EDITOR_COLOR_BLUE');
Text::script('COM_KUNENA_EDITOR_COLOR_PURPLE');
Text::script('COM_KUNENA_EDITOR_COLOR_GREEN');
Text::script('COM_KUNENA_EDITOR_COLOR_WHITE');
Text::script('COM_KUNENA_EDITOR_COLOR_GRAY');
Text::script('COM_KUNENA_EDITOR_ULIST');
Text::script('COM_KUNENA_EDITOR_LIST');
Text::script('COM_KUNENA_EDITOR_SIZE_VERY_VERY_SMALL');
Text::script('COM_KUNENA_EDITOR_SIZE_VERY_SMALL');
Text::script('COM_KUNENA_EDITOR_SIZE_SMALL');
Text::script('COM_KUNENA_EDITOR_SIZE_NORMAL');
Text::script('COM_KUNENA_EDITOR_SIZE_BIG');
Text::script('COM_KUNENA_EDITOR_SIZE_SUPER_BIGGER');

And the libraries.ini needs additional 2 strings
https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/administrator/components/com_kunena/language/en-GB/en-GB.com_kunena.libraries.ini
COM_KUNENA_EDITOR_COLORS = "Colors"
COM_KUNENA_EDITOR_TWEET = "Tweet"

**Comment by sshcli** [comment]
I will do a PR for it, Please assign this issue to me

**Comment by sshcli** [comment]
You can close this one
