### ISSUE TITLE
Select category doesn't work if JavaScript disabled

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6126]
**Steps to reproduce the behavior:**
1.  Configuration-> Force users to pickup a category = Yes
2. Category settings-> Review posts = Yes  (For all categories, a moderator needs to approve every new post/topic)
3. Disable javascript in your browser
4. Registered user create a new topic and don't choose any category from the dropdown 

**Expected behavior**
The user is forced to pickup a category:
![good2](https://user-images.githubusercontent.com/12942731/46713775-4f88f780-cc26-11e8-9576-e20621d1f0db.png)

If select a category, the new topic will be on hold until a moderator review it
![good](https://user-images.githubusercontent.com/12942731/46713446-b1486200-cc24-11e8-8fe2-5723165c2a75.PNG)

**Actual result**
Because  javascript is disabled in the browser, the new topic will be posted intermediately and you will see the following message:

![bad](https://user-images.githubusercontent.com/12942731/46713440-adb4db00-cc24-11e8-92f9-f618fcba45db.PNG)

**System information (please complete the following information)**
Joomla version: Joomla! 3.9.0-rc-dev
Kunena version: 5.1.4
Php version: 7.1.22
Database version: MySQL 5.6.41

**Comment by 810** [comment]
Kunena needs js.
