### ISSUE TITLE
Uncaught TypeError: document.postform.subject.focus is not a function

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6127]
**Steps to reproduce the behavior:**
1. Go to example.com/forum/newtopic and try to create a new topic

**Expected behavior**
No error in console

**Actual result**
You get this error in the console:
`Uncaught TypeError: document.postform.subject.focus is not a function`

![error2](https://user-images.githubusercontent.com/12942731/46714128-f9b54f00-cc27-11e8-9e5d-f4042a47e391.PNG)

**Additional context**
Line 472: src/components/com_kunena/template/crypsis/layouts/topic/edit/default.php
Line 505: src/components/com_kunena/template/crypsisb3/layouts/topic/edit/default.php

**System information (please complete the following information)**
Joomla version: Joomla! 3.9.0-rc-dev
Kunena version: 5.1.4
Php version: 7.2.10
Database version: MySQL 5.6.41

**Comment by 810** [comment]
Did you enable javascript? 

You need javascript

**Comment by sshcli** [comment]
JavaScript is enabled.

**Comment by 810** [comment]
I can't reproduce the issue

**Comment by sshcli** [comment]
I can't reproduce it my test environment.
I only see the error in my production environment.
Please allow me some time to bring more details on how to reproduce this.
Thanks in advance for your cooperation

**Comment by sshcli** [comment]
The option causing the error is **Let users edit the subject**

To reproduce the error, go to:
Configuration->Frontend->Let users edit the subject = No
