### ISSUE TITLE
WYSIWYG does not allow class in url

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6128]
**Steps to reproduce the behavior:**
1.  Configuration->Use all default settings 
2. Template Crypsis->Use all default settings 
3. Create a new topic and insert this in the content: `[url=https://example.com class="btn"]Button[/url]`
4. Save the topic
5. Now go to Templates->BBcode->Editor = WYSIWYG
6. Edit the topic created
7. Click the bbcode toggle button on editor

**Expected behavior**
On edit you should see the following code:
`[url=https://example.com class="btn"]Button[/url]`

When saved, You should see a bootstrap button in the same way you can see it with the bbcode editor 
![good3](https://user-images.githubusercontent.com/12942731/46714588-35511880-cc2a-11e8-92a4-f7ee3d57bb28.PNG)

**Actual result**
On edit, you will see the following code:
`[url=https://example.com class=]Button[/url]`
The class has been removed

When saved, you will see only a link, without the button, because the class has been removed in WYSIWYG editor
![bad3](https://user-images.githubusercontent.com/12942731/46714585-3124fb00-cc2a-11e8-9ee1-6175f7b54982.PNG)

**System information (please complete the following information)**
Joomla version: Joomla! 3.9.0-rc-dev
Kunena version: 5.1.4
Php version: 7.2.10
Database version: MySQL 5.6.41

**Comment by xillibit** [comment]
If you put the bbcode like that it works : 

[url=https://example.com class=btn]Button[/url]

**Comment by sshcli** [comment]
> If you put the bbcode like that it works : [url=https://example.com class=btn]Button[/url]

That solution is only valid when using only one class.
it is not possible to use multiple class like the example below:
`class="btn btn-success btn-large"`

**Comment by xillibit** [comment]
It works by doing that : 

`[url=https://example.com class="btn btn-success btn-large"]Button[/url]`
