### ISSUE TITLE
Layout broken when Trim Long URLs = No

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6130]
**Steps to reproduce the behavior:**
1. Configuration->BBCode->Trim Long URLs = No
2. Go to example.com/forum/newtopic
3. Paste a very long url in the text area
4. Click the preview tab

**Expected behavior**

![good](https://user-images.githubusercontent.com/12942731/46847637-6577f300-cdb3-11e8-9e35-3e80bde9bebd.PNG)

**Actual result**

![bad](https://user-images.githubusercontent.com/12942731/46847628-614bd580-cdb3-11e8-9896-92ca31962286.PNG)

**System information**
Joomla version: Joomla! 3.9.0-rc-dev
Kunena version: 5.1.4
Php version: 7.2.10
Database version: MySQL 5.6.41

**Comment by xillibit** [comment]
Why if you disable trim URL it should be even trimmed ?

**Comment by sshcli** [comment]
If (Trim Long URLs = No) {
Load the long version of the url inside the textarea using  2 or 3 lines if needed;
}

**Comment by xillibit** [comment]
Preview doesn't exist anymore in K5.2
