### ISSUE TITLE
Menu on mobile broken due to depency login

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#6131]
**Describe the bug**
when looking at the forum from a mobile device, the menu bar is 'empty'.

**To Reproduce**
1. Go to kunen plugin: Kunena - Joomla Integration
2. Set 'Enable Joomla login' to: No
3. goto the forum on the front-end on your desktop: the menu is visible
4. switch to mobile view: the menu is removed

**Expected behavior**
The menu bar should have the left-side 'hamburger' dropdown menu

**Actual result**
the left side hamburger menu is not rendered

**Screenshots**
Desktop:
![image](https://user-images.githubusercontent.com/2733197/46954335-95afe200-d090-11e8-981e-75acc0f3a3cf.png)

Mobile:
![image](https://user-images.githubusercontent.com/2733197/46954361-a3fdfe00-d090-11e8-9d17-8aa68c65b6cf.png)

**System information (please complete the following information)**

Joomla version: 3.8.13
Kunena version: 5.1.5 (and earlier)
Php version: 7.1.x
Database version: mysql 5.6.x

**Additional information**
when setting the enable joomla login to yes, the menu (and the login button is shown as you can see. But these two are not related! so should not be dependent on each other
![image](https://user-images.githubusercontent.com/2733197/46954498-0eaf3980-d091-11e8-9abc-569fefcae2e3.png)

**Comment by 810** [comment]
Mhh I can see the menu on mobile when I disable the kunena - Joomla login option

![image](https://user-images.githubusercontent.com/876623/48140776-c3f89a00-e2a9-11e8-9761-8493e97619cb.png)

**Comment by Ruud68** [comment]
I'm confident that this is not possible (when looking at the code), it should only shown when the plugin "Kunena - Joomla Integration" has " Enable Joomla Login" set to yes.

the crypsis menubar widget, displays the "desktop-visible" and then triggers the "Widget/Login" (via <?php echo $this->subRequest('Widget/Login'); ?>)

the Widget/Login 'bails' when login is disabled in plugin:
./controller/widget/login/display.php
```
                $login = KunenaLogin::getInstance();

                if (!$login->enabled())
                {
                        return false;
                }
```
so that only displays the login menu when the plugin is set to login = yes.
the mobile hamburger menu is part of the login / lougout widget!

Just install 5.1.6dev2 to rule out if that makes a difference.
I will email you the credentials and link to my test site. Maybe you can sport the setting that does the  magic'

**Comment by 810** [comment]
it was working until I saved the Kunena - Kunena Integration plugin.
