### ISSUE TITLE
Subject doesn't changed after the editting

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#6132]
**Describe the bug**

A topic has a few replied. 
The subject name is: **testing the feature 2**

I decided to edit the subject of the last message and changed its name to: 
**testing the feature 333**

But... The subject was not changed on the topic page.

Here are the screenshots illustrating this problem:
![screen shot 2018-10-17 at 11 58 03](https://user-images.githubusercontent.com/3432048/47075562-7ab2ae80-d205-11e8-95b6-582d3e393fce.png)
As you see, I added 333 to the topic name.

After clicking on "Save" button, I see the topic page and my edited message still has the old subject:
![screen shot 2018-10-17 at 11 57 16](https://user-images.githubusercontent.com/3432048/47075648-aa61b680-d205-11e8-84f5-cf4c56c38e5a.png)

But if I edit this post again, I see correct topic name: 
**testing the feature 333**

 
**System information (please complete the following information)**

Joomla version: 3.8.13
Kunena version: 5.1.5
Crypsis BS3 
PHP: 7.0.32

**Comment by sshcli** [comment]
This issue is related to this one: https://github.com/Kunena/Kunena-Forum/issues/4283
It doesn't mean it's duplicated.
