### ISSUE TITLE
Disallow new topic with empty message

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6135]
**Steps to reproduce the behavior:**
1. Create a new topic and insert this in the content: `[instagram].`

**Expected behavior**
You should get the error: `Cannot save message: Message body is empty!`

![good2](https://user-images.githubusercontent.com/12942731/47240719-45e65900-d3b7-11e8-800d-8a769c1ca3dc.PNG)

**Actual result**
The topic is posted with a huge blank square without content

![bad2](https://user-images.githubusercontent.com/12942731/47240727-4aab0d00-d3b7-11e8-86f3-04e97d5e23b2.PNG)

**System information**
Joomla version: Joomla! 3.9.0-rc2-dev	 
Kunena version: 5.1.6-DEV
Php version: 7.2.11
Database version: MySQL 5.6.41

**Comment by 810** [comment]
Error
Cannot save message: Message body is empty!

**Comment by sshcli** [comment]
You should include the `.` after [instagram]

**Comment by xillibit** [comment]
When i insert only  [instagram] in a message and do sumbit, it show "The message has been successfully deleted." and the message isn't created
