### ISSUE TITLE
No time in the calendar param when edit the poll

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#6136]
**Describe the bug**
Actually, it is not so bug, but it seems it something which deserves attention.
I have created a poll.
Now let's edit poll > click on Poll icon and get a modal window.
First time I see the date in the following format:
2018-10-24 00:00:00

When I click on calendar field, the format is changed to 
10/21/2018

I think the time should remain.

Tested with Kunena 5.1.5 and Crypsis template.

**Comment by 810** [comment]
should be fixed now (5.1.6)
