### ISSUE TITLE
Add Unread menu item during forum update

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#6141]
I noticed a new menu item Unread after a clean installation of Kunena 5.1.5.

However, this menu item wasn't created during Kunena upgrade from 5.0.
I even did not know about this new feature and noticed it after a clean install and I suppose a lot of people does not know too.

My proposal is to check out Kunena menu and add this menu item if not exist. 
It will help other people to discover this feature.

**Comment by 810** [comment]
we have not added because many users are created custom menu items and placed them on other menu's ect. So we decided not to add it by update. 


We wanted to add all features to our new website, but it still under development.

**Comment by Sulpher** [comment]
Yes, I understand. But in such a case it would be better to write an announce with a short overview of new features because users just do not know what is new was implemented. Some interesting features might be highlighted in the news and screenshots are preferable. It is just an advice. ;-)
