### ISSUE TITLE
invisible Captcha issue

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#6145]
**Describe the bug**
when setting in Jomla Global config the captcha to the new invisible captcha, Kunena still display the old captcha. As it turns out , Kunena doesn't use the configured captcha plugin, but the first captcha plugin it encounters
**To Reproduce**
1. Go to global config and set the captcha to the new invisble captcha
2. got o kunena forum and start e new topic
3. old captcha is displayed

**Expected behavior**
global selected captcha should be displayed

**Actual result**
old captcha is displayed

**System information (please complete the following information)**

Joomla version: 3.9
Kunena version: 5.1.5
Php version: 7.2
Database version:

**Additional context**
when reordering the captcha plugins in the pluginmanager, it turns out that Kunena doesn't use the globally configured plugin, but the first ordered plugin (which is by defaul the old plugin)

**Comment by 810** [comment]
Is already be merged into K6.0 as a new feature. We do now support Joomla captcha.
