### ISSUE TITLE
Kunena Installation Failed!

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6150]
**Steps to reproduce the behavior:**
1. Components->Kunena Forum->Tools->Uninstall Kunena
2. Install from url->https://update.kunena.org/nightlybuilds/pkg_kunena_v5.1.7-DEV_2018-11-11.zip

**Expected behavior**
Should be installed without any problem.

**Actual result**
You get this error:

![error1](https://user-images.githubusercontent.com/12942731/48308389-cf61f480-e539-11e8-8611-6d60abc142d2.PNG)

**System information (please complete the following information)**
Joomla version: 3.9.0
Kunena version: Kunena 5.1.7-DEV
Php version: 7.2.11
Database version: 5.6.41

**Comment by rich20** [comment]
https://www.kunena.org/forum/installation-issues/154673-kunena-5-1-6-install-fails
Confirmed, this bug exists already in Kunena 5.1.6, so it's not possible to install this version on a new page. You must install Kunena 5.1.5 previously, then upgrade.

**Comment by xillibit** [comment]
Maybe related to this change : https://github.com/Kunena/Kunena-Forum/commit/9426cf84d743f120f885c8270ab13f0ddaf1d842
