### ISSUE TITLE
Alt attribute is duplicated

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6151]
**Steps to reproduce the behavior:**
1. Create a new topic and insert this tag: 
`[img size=100 alt=test image]https://i.ytimg.com/vi/XfmiTMRIbZA/maxresdefault.jpg[/img]`
2. Take a look to the source code of the page

**Expected behavior**
Only one alt attribute should be used and blank space should be allowed by adding " "

**Actual result**
There are two alt attributes. 
Also, the alt attribute generated from the bbcode tag does not accept blank space.
See image below:
![error3](https://user-images.githubusercontent.com/12942731/48308485-747dcc80-e53c-11e8-904e-5dcfbb7068ea.PNG)

**System information (please complete the following information)**
Joomla version: 3.9.0
Kunena version: Kunena 5.1.6
Php version: 7.2.11
Database version: 5.6.41

**Comment by 810** [comment]
for me its ok:

``<img style="max-height: 8000px; max-width:100px;" alt="test" src="https://i.ytimg.com/vi/XfmiTMRIbZA/maxresdefault.jpg">``

**Comment by sshcli** [comment]
This is the alt causing the problem:

<img width="779" alt="alt" src="https://user-images.githubusercontent.com/12942731/49234529-95fd0600-f3ce-11e8-87a3-46f5bdc9f4f8.PNG">

**Comment by sshcli** [comment]
We should keep only the one generated automatically by the filename.

**Comment by sshcli** [comment]
The bbcode tag is causing the double alt.
if you use html it won't happen.

You can also reproduce this problem in the kunena custom content menu item.

This issue is real, it should be reopened because is not solved yet.
I can provide more details if needed
