### ISSUE TITLE
PHP Warning: imagecolorclosest() expects parameter 2 to be integer

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6158]
**Steps to reproduce the behavior:**

Still trying to reproduce the exact steps to reproduce this.
I will update this issue once I find it.

**Expected behavior**
You should not see any warnings in php error_log file.

**Actual result**
You see the following warnings in php error_log file:

`PHP Warning:  imagecolorclosest() expects parameter 2 to be integer, float given in /home/username/public_html/libraries/kunena/image/image.php on line 76`

`PHP Warning:  Division by zero in /home/username/public_html/libraries/kunena/image/image.php on line 76`

**System information (please complete the following information)**
Joomla version: 3.9.0
Kunena version: Kunena 5.1.6.1
Php version: 7.2.12
Database version: 5.6.41

**Comment by 810** [comment]
See: https://github.com/Kunena/Kunena-Forum/issues/6100

**Comment by sshcli** [comment]
> See: #6100

Yes, I remember that issue. 
But is was not fixed at that time, and the error is back.
It seems like if it is something caused by a very particular condition, because I don't see this error too often.

Also, it has been very hard to find the way to reproduce it.

**Comment by xillibit** [comment]
This will be fixed by replacing the kunena image class by a better another image manipulation class or wait J!4.0 ?

**Comment by sshcli** [comment]
Maybe it could be related to the issue, or maybe not. 
But sometimes I see errors in images uploaded bu the user.

For example, the following picture has been damaged after uploaded and resized to 144 (it now has all those black squares)
![avatar266180](https://user-images.githubusercontent.com/12942731/53446445-623f7580-39e9-11e9-82e9-c98f880387ac.png)

**Comment by sshcli** [comment]
The size200 of this picture is ok without problems.

**Comment by xillibit** [comment]
The code which used the method  imagecolorclosest() has been removed in K6.0
