### ISSUE TITLE
Some datepickers are not translated

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6170]
**Steps to reproduce the behavior:**
1. Go to example.com/forum/search
2. Go to example.com/forum/profile/edit/id-username

**Expected behavior**
All datepickers should be translated.
For example:
<img width="591" alt="yes" src="https://user-images.githubusercontent.com/12942731/49236502-9f886d00-f3d2-11e8-8af0-e0c10f34cfee.PNG">

**Actual result**
Some datepickers are not translated.
For example:
<img width="440" alt="not" src="https://user-images.githubusercontent.com/12942731/49236466-8a134300-f3d2-11e8-960a-05cec2441507.PNG">

<img width="433" alt="not2" src="https://user-images.githubusercontent.com/12942731/49236473-8e3f6080-f3d2-11e8-8be3-7a75629a8c84.PNG">

**System information (please complete the following information)**
Joomla version: 3.9.1
Kunena version: 5.7 and 5.1.8-DEV
Php version: 7.2.12
Database version: MySQL 5.7.24

**Comment by xillibit** [comment]
There are some new language strings /components/com_kunena/template/crypsis/assets/js/locales/bootstrap-datepicker.kunena.js added in previous Kunena version. I'am not sure if it has been translated in all language @sshcli is-it right translated in your language file ?
