### ISSUE TITLE
Two menus

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#6172]
In code Kunena there are two menus, one of which is hidden by styles.
It is not right. They switch at the expense of classes **visible-desktop** and **hidden-desktop**.
HTML validator sees errors: duplicate id **klogin** and id of login buttons through social networks, displayed in module position of dropdown-menu.

File www\components\com_kunena\template\crypsis\layouts\widget\menubar\default.php

Template - Crypsis
Kunena - 5.1.7

**Comment by 810** [comment]
this should be fixed already.

chrome doesn't show this error. I just fixed 2 other dom issues.

**Comment by Inter-Net-Pro** [comment]
Validator HTML (https://validator.w3.org/) easily finds duplicate IDs and marks them as an error.

Dubli id: `id="klogin"` and `id="userdropdown"`

Screenshots from site Kunena, page: https://www.kunena.org/forum/index in confirmation:

![2018-12-09_041349](https://user-images.githubusercontent.com/32765749/49692762-1c51de80-fb6b-11e8-9d63-dfdb557fa222.png)

![2018-12-09_041426](https://user-images.githubusercontent.com/32765749/49692766-2b389100-fb6b-11e8-8534-4fdfa3d8cec4.png)

**Two menus in code:**

![2018-12-09_041147](https://user-images.githubusercontent.com/32765749/49692774-5b802f80-fb6b-11e8-8f46-102956921cd2.png)

**Comment by mc-hovanskiy** [comment]
Validator HTML (https://validator.w3.org/) easily finds duplicate IDs and marks them as an error.

Dubli id: `id="klogin"` and `id="userdropdown"`

Screenshots from site Kunena, page: https://www.kunena.org/forum/index in confirmation:

![2018-12-09_041349](https://user-images.githubusercontent.com/29813939/49692792-b87be580-fb6b-11e8-96f5-2bc01d1f9b6d.png)

![2018-12-09_041426](https://user-images.githubusercontent.com/29813939/49692793-c5003e00-fb6b-11e8-8fee-e1a81a8445d9.png)

**Two menus in code:**

![2018-12-09_041147](https://user-images.githubusercontent.com/29813939/49692802-e5c89380-fb6b-11e8-844f-6c0c0a6adf21.png)
