### ISSUE TITLE
Users can change the complete title in a topic

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6177]
**To Reproduce**
1. Set in the configuration tab Frontend "Let users edit the subject = Yes" (is default)
2. Click on Reply and change the subject

**Expected behavior**
The title should be changed only at the answer message

**Actual result**
The topic title will be changed for the complete topic, so it's possible to change a topic title from another author

**System information (please complete the following information)**
Joomla version: 3.1.9
Kunena version: 5.1.8-DEV
Php version: 7.2.11
Database version:

**Comment by 810** [comment]
The author of the topic can change the topic subject, if the setting is enabled.
