### ISSUE TITLE
Editing removes the subscription

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6195]
**Describe the bug**
https://www.kunena.org/forum/k5-1-support/156534-reply-edit-resets-subscribe-flag
I confirm this bug.

**To Reproduce**
1. Subscribe a topic
2. Edit a message in this topic 

**Actual result**
Editing removes your subscription

**Comment by rich20** [comment]
This fix added only the checkbox on edit with the setting of the backend. It's not logical, if you edit any message at some point and must according to the backend setting you must either again subscribe or unsubscribe.
My opinion it's no matter, which option the user has chosen in his first post of a topic (subscribed or not), this should remain for the complete topic unless the user change itself the option.

**Comment by xillibit** [comment]
You have two settings : one in backend and one another in user profile, so it makes something complex
