### ISSUE TITLE
Wrong author meta tags when is set "Display User Name = No"

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6197]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/156599-editing-disabling-open-graph-meta-tags

**To Reproduce**
1. Set in the configuratio (tab Users) "Display User Name = No"
2. Open a topic and see the source code of this page

**Expected behavior**
It should be displayed the real author name (the same as in the Kunena topic)

**Actual result**
Nevertheless it shows the user name although this in the Kunena setting is disabled
Example: `<meta property="og:author" content="rich" />`

**Comment by Ruud68** [comment]
Hi, I think og:author is a non existing tag.
Author can be used in a context (like article:author or video:author but then that name should point to a opengraph profile.
![selection_330](https://user-images.githubusercontent.com/2733197/51799544-6299f480-2222-11e9-87c6-42615e5a9bfc.jpg)

**Comment by yourVirtualAssistant01** [comment]
I also have this problem. I hope somebody could help.
