### ISSUE TITLE
Thumbnails should be hidden, when images are inserted in messages

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6199]
There is no way to hide thumbnails when image inserted in messages. This question gives again and again. Earlier it was default in old Kunena versions (before Crypsis I think)
https://www.kunena.org/forum/119-Feature-Requests/156953-change-the-way-attachments-are-displayed

The thumbnails makes only sense when the images are not inserted in the message.

**Comment by xillibit** [comment]
I think we need to let the choice to display the thumbnails for people want it and hide it for others.

In the upload form, what do-you think to add a checkbox "show thumbnails(s) in message" ?

**Comment by xillibit** [comment]
There is already something which handle that on Crypsis but it wasn't in Aurelia
