### ISSUE TITLE
Validation error - form inside h2

### ISSUE THREAD

**Issue by mc-hovanskiy** [Kunena/Kunena-Forum#6200]
Search in forum topics is inserted inside H2 tag.
HTML validator sees this as an error:
> Element form not allowed as child of element h2 in this context.

Probably need to replace H2 on div.

![2019-02-11_122443](https://user-images.githubusercontent.com/29813939/52558256-80f31900-2dfa-11e9-916e-d5ca9994d786.png)

**Comment by mc-hovanskiy** [comment]
Also in code identifier is duplicated
`id="topic-actions"`

**Comment by sshcli** [comment]
A fix has been merged. This issue should be closed.

**Comment by xillibit** [comment]
Half of the issue has been fixed
