### ISSUE TITLE
Deleted posts view don't have option to move items

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6222]
**To Reproduce**
1. Create a menu for deleted posts
2. Delete some posts/topics
3. Go to deleted posts menu in front end and try to move a topic

**Expected behavior**
You should be able to move your deleted topics/posts.
![good2](https://user-images.githubusercontent.com/12942731/53444450-919fb380-39e4-11e9-90f7-6d2d7b736a41.png)

**Actual result**
There is no option to move deleted posts/topics
![bad](https://user-images.githubusercontent.com/12942731/53444026-7a13fb00-39e3-11e9-92b3-1736796013a7.png)

**System information (please complete the following information)**
Joomla version: 3.9.3
Kunena version: 5.1.9
Php version: 7.2.15
Database version: MySQL 5.7.25

**Comment by xillibit** [comment]
For me, it displayed correctly : 

![lljhj](https://user-images.githubusercontent.com/876395/53837615-44e34c00-3f93-11e9-98b0-2169e4e3fbb3.png)

**Comment by sshcli** [comment]
The Problem is only with Deleted Posts, not with Deleted Topics
