### ISSUE TITLE
Crypsis b3 | Quick reply content not preserved when switching to full editor

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6233]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/157353-quick-reply-content-not-preserved-when-switching-to-full-editor

This issue seems only for Crypsis fixed, but not for Crypsis b3. (I can't find a commit here for this question)

**Comment by xillibit** [comment]
There was this change, it has been done to crypsis and crypsis b3 : https://github.com/Kunena/Kunena-Forum/issues/4790

**Comment by rich20** [comment]
hm... no idea why it not work. Recover crash and store fields works on Quick Reply but if you go to the editor, the text field remain empty.

**Comment by rich20** [comment]
- [x] Quick reply default - Success
- [x] Quick reply modal - Success
- [ ] Quick reply always visible - Failed | **With this option it also not work with Crypsis**
