### ISSUE TITLE
Defective avatar when use Bicubic + Cropping

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6260]
**To Reproduce**
1. Avatar Resize Method = Bicubic (Best Slower)
2. Avatar Cropping = Yes
<img width="383" alt="settings" src="https://user-images.githubusercontent.com/12942731/54240391-48775580-44f4-11e9-8485-aa359cc3c535.PNG">

3. Change your avatar and use a .jpg file 113 x 164
Example avatar:
![test](https://user-images.githubusercontent.com/12942731/54240423-604ed980-44f4-11e9-9c47-3377b44121d8.jpg)
4. Go to one of your topics and take a look to the avatar

**Expected behavior**
The avatar image should not have any error or defect.
<img width="250" alt="good6" src="https://user-images.githubusercontent.com/12942731/54240447-6fce2280-44f4-11e9-970d-54ae23021cb8.PNG">

**Actual result**
The avatar will show a lot of tiny squares.
<img width="239" alt="bad6" src="https://user-images.githubusercontent.com/12942731/54240451-7361a980-44f4-11e9-907e-03d84747076e.PNG">

**System information (please complete the following information)**
Joomla version: 3.9.4
Kunena version: 5.1.11-DEV
Php version: 7.3.2
Database version: MySQL 5.7.25

**Comment by xillibit** [comment]
I think this one is related to : https://github.com/Kunena/Kunena-Forum/issues/6158, in J4.0 the JImage has been a bit improved we can use it instead our own code or use third party library

**Comment by xillibit** [comment]
The option "Avatar resize method" has been removed and some code which handled that has been removed too : https://github.com/Kunena/Kunena-Forum/commit/7467b530dde09d8d9fd1e27f5abe235c25eaa2d8
