### ISSUE TITLE
http addresses will changed to https when saved the message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6271]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/157244-problem-with-entering-of-a-link-in-bbcode-editor-https-prefix-problem
It's not possible to save a link without https in messages. If you enter a url such as http://websiteaddress it changes after the submit to https://websiteaddress

**To Reproduce**
Save a url with http and you see it. You have a https address now.
I've tested it and confirm this error

**Comment by 810** [comment]
Fixed?

**Comment by rich20** [comment]
No idea when or where the bug has been fixed, but I've tested now with Joomla 3.9.10 and Kunena 5.1.12.1 and it seems, the bug is gone.

**Comment by rich20** [comment]
I think,this issue can be closed
