### ISSUE TITLE
preg_replace_callback(): Compilation failed: invalid range in character class

### ISSUE THREAD

**Issue by ghost** [Kunena/Kunena-Forum#6282]
**Describe the bug**
`Warning: preg_replace_callback(): Compilation failed: invalid range in character class at offset 18 in /home/***/public_html/components/com_kunena/views/topics/view.html.php on line 203`

Might be from an unescaped "-" character in the regex?

**To Reproduce**
Showing up with the latest topics module enabled.
https://www.debuggex.com/r/4ZpBSGGal_BTjeNo

**Expected behavior**
"-" character should be escaped

**Actual result**
"-" is not escaped

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.9.x
Kunena version: 5.1.10.1
Php version: 7.2
Database version: MySQL

**Desktop (please complete the following information):**
 - OS: CentOS Linux
 - Browser: Chrome
 - Version: 73

**Additional context**
Might be able to fix by changing lines 203 and 212 to this (haven't been able to test yet):

`$contents = preg_replace_callback('|\[K=(\w+)(?:\:([\w\-_]+))?\]|', array($this, 'fillTopicInfo'), $contents);`

**Comment by ghost** [comment]
Changing the regex to this seems to pass? Needs testing

https://www.debuggex.com/r/cbjqVVRsXo9YBW-K

**Comment by 810** [comment]
i use a other site to test it, and there it was correct:

https://regex101.com/r/IS0DkD/1

ps there was a error, i need to add \ before it.

**Comment by 810** [comment]
please try the nightly build. its on our download page on the bottom.
