### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#6284]
az-AZ.com_kunena.views.ini
el-GR.com_kunena.views.ini
et-EE.com_kunena.views.ini
fi-FI.com_kunena.views.ini
hr-HR.com_kunena.install.ini
it-IT.com_kunena.views.ini
km-KH.com_kunena.views.ini
ko-KR.com_kunena.views.ini
kz-KZ.com_kunena.views.ini
lt-LT.com_kunena.views.ini
mk-MK.com_kunena.views.ini
nb-NO.com_kunena.views.ini
pl-PL.com_kunena.views.ini
pt-PT.com_kunena.views.ini
sq-AL.com_kunena.views.ini
sr-YU.com_kunena.views.ini
ug-CN.com_kunena.views.ini
vi-VN.com_kunena.views.ini
zh-CN.com_kunena.views.ini
ar-AA.com_kunena.templates.ini
sk-SK.com_kunena.templates.ini
th-TH.com_kunena.templates.ini

all example links should be www.kunena.org

**Comment by rich20** [comment]
It was for all this languages in both files (kunena.views.ini and kunena.templates.ini) a wrong address. 
I've changed all addresses and hope I've nothing overlooked. 
Only in the hr-HR.com_kunena.install.ini I can nothing to find. The string for the welcome message is not translated and is comment out. And other lines contain no address.

**Comment by 810** [comment]
COM_KUNENA_INSTALL_MIGRATE_HINT change www.kunena.com to org

**Comment by rich20** [comment]
Yes, that I had overlooked because in the source text is not a url in this line. All is done now.

**Comment by 810** [comment]
ok, thnx will close this one.
