### ISSUE TITLE
Different birth date values in the profile and database

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6285]
**Describe the bug**
https://www.kunena.org/forum/k5-1-support/158175-bug-can-t-modify-user-in-version-5-1-12-1
Confirmed

**To Reproduce**
1. Edit an user profile, empty the birthday field and save
2. After save you have this date 11/30/-0001 in this field
3. Check the database, it shows the date of birth 0000-00-00
4. Now try edit and save something in the profile

**Actual result**
You get this error:
DateTime::__construct(): Failed to parse time string (11/30/-0001) at position 5 (/): Unexpected character

**System information (please complete the following information)**
Joomla version: 3.9.5
Kunena version: 5.1.12.1 and 5.1.13-dev
Php version: 7.3.3
Database version: 5.5.58 Collation utf8mb4_general_ci

**Comment by sshcli** [comment]
The bug is related to this one: https://github.com/Kunena/Kunena-Forum/issues/6115

**Comment by rich20** [comment]
Yes, you're right, but the other bug report is already closed although the error still exists.

**Comment by sshcli** [comment]
@rich20 sorry if there was a misunderstood, the intention of my comment is to help quickly identify error background and all related commits to fix the problem, is not for close this issue. I agree with this new issue.

**Comment by rich20** [comment]
No problem @sshcli 
The problem seems the script of the calendar. It's not possible in the frontend manually to enter this date of birth 01/01/0001. Try it, the date will cutted to 01/01/1 and after save it is changed to 01/01/2001

**Comment by sshcli** [comment]
When using the default settings for the bootstrap datetimepicker, the field is disabled and insert data is only posible by using the picker.

Maybe a definitive solution to this problem, could be remove all custom modifications and use the datepicker with default settings and values, with no extra code.

**Comment by rich20** [comment]
<strike>This solution would only work if you can choose the year on the datetimepicker. When the default value is 01/01/0001 you need currently 1999 x 12 clicks if your birth date is in the year 01/01/2000. You can go for- or backwards only per month.</strike>
Sorry, was nonsense what I've written.

**Comment by xillibit** [comment]
MySql since 5.7 has changed the supported range for datetime value, so i think it's the main reason why we have this kind of issue in Kunena : https://dev.mysql.com/doc/refman/5.7/en/datetime.html
