### ISSUE TITLE
Can't expand the subscriptions modal

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6288]
**To Reproduce**
Backend->Components->Kunena Forum->Users->Add subscriptions to categories

**Expected behavior**
You should be able to expand the modal as needed
<img width="81" alt="good" src="https://user-images.githubusercontent.com/12942731/56697412-84d5ce00-66bc-11e9-9508-3d1bdbc7935b.PNG">

**Actual result**
You can't expand the modal
<img width="550" alt="bad" src="https://user-images.githubusercontent.com/12942731/56697415-8901eb80-66bc-11e9-8308-229916e90214.PNG">

**System information (please complete the following information)**
Joomla version: 3.9.5
Kunena version: 5.1.12.1
Php version: 7.3.4
Database version: MySQL 5.7.25

**Comment by 810** [comment]
that can only done by text input, this is a modal, so we can't do that.
