### ISSUE TITLE
Regression: malformed URL in topic preview

### ISSUE THREAD

**Issue by demis-palma** [Kunena/Kunena-Forum#6291]
In global Joomla SEO setting, enable "SEF URLs", "URL rewriting" and "URL suffix".
Post a new message in the forum, either as a new topic or in reply to an existing topic.
When writing the message, pass on the "Preview" tab.
Here the ajax call points to a **malformed** URL (half SEF, half non-sef), which is not guaranteed to be parsed correctly by Joomla, and which alerts some Web Application Firewall since the php file called (/forum/5-category/topic/**index.php**) does not exists in the filesystem (see below).

Taken from the "Network" section of the browser development tools:
Given that the topic URL is
`http:// site.com/forum/5-category/topic/create.html`
and the preview URL is a **relative URL**
`index.php?option=com_kunena&view=topic&layout=edit&format=raw`
then the actual preview URL called by the ajax call will be as follows:
`http:// site.com/forum/5-support/topic/index.php?option=com_kunena&view=topic&layout=edit&format=raw`
which is wrong.
The file site.com/index.php exists, while the file topic/index.php does not exists in the filesystem.

The patch proposed here https://github.com/Kunena/Kunena-Forum/pull/5070 has been implemented partially and incorrectly. As a result, the problem has been limited to configurations where "SEF URLs", "URL rewriting" and "URL suffix" are all enabled. However under this configuration, the problem is still there.

I also wanted to point out that there is no reason to respect the current SEF options in ajax calls. That's why the patch mentioned always creates a non-sef (but always valid) URL for the ajax call:
JUri::root(true) . '/index.php?option=com_kunena&view=topic&layout=edit&format=raw'

But if you want to respect the Joomla SEF URL settings, at least please build valid SEF urls.

On request, I can provide a sample Web Application Firewall plugin for Joomla, that blocks such kind of malformed URLS, and with which Kunena is incompatible, just to make the problem clearer.

**Comment by xillibit** [comment]
The change made #5070 isn't here anymore, actually the code is the following :

`<input id="kpreview_url" type="hidden" name="kpreview_url"
		       value="<?php echo KunenaRoute::_('index.php?option=com_kunena&view=topic&layout=edit&format=raw', false) ?>"/>`

**Comment by demis-palma** [comment]
@xillibit 

> actually the code is the following

Yes, in fact as I said above: _"The patch proposed here #5070 has been implemented partially and incorrectly."_

As you can [see here](https://github.com/Kunena/Kunena-Forum/pull/5070/commits/24106ad642b096e665caffc279ec2d1e1c395b58) the patch proposed to replace the bugged line you mentioned:

`value="<?php echo KunenaRoute::_('index.php?option=com_kunena&view=topic&layout=edit&format=raw', false) ?>"`

with this one:
`value="<?php JUri::root(true) . '/index.php?option=com_kunena&view=topic&layout=edit&format=raw' ?>"`

but this part of the pull request has not been accepted without providing any reason for that.

Florian, do you confirm at least that the URL hit by the "Preview" ajax call is still like this?
`/forum/5-category/topic/index.php`

**Comment by demis-palma** [comment]
Ok, I've found the reason why the PR was not implemented as submitted.

My changes to the php are wrong: I wrote
`<?php JUri::root(true) .`
while it should be
`<?php echo JUri::root(true) .`

It's my fault, I've not tested it enough before submitting the PR.
I'll submit a new PR shortly to clear the mess.

**Comment by demis-palma** [comment]
Done. It's here: https://github.com/Kunena/Kunena-Forum/pull/6565
