### ISSUE TITLE
All categories along with sections are automatically in the subscribe list

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6300]
**To Reproduce**
Create a topic or answer as admin or global mod, then go in your profile -> tab subscription. You have now all categories along with the sections in the subscriptions list.

**Additional context**
A normal registered user has instead of the list this error:
Exception in layout Category/List!Unknown column 'map.group_id' in 'on clause'

**Comment by 810** [comment]
please try again, i don't have this issue

**Comment by rich20** [comment]
Seems ok now
