### ISSUE TITLE
[K6] Can't convert reply into new topic

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6312]
**To Reproduce**
1. Reply any topic
2. Move the reply to act a new topic

**Expected behavior**
The reply should be converted into a new topic 

**Actual result**
You get this error:

> Error
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON DUPLICATE KEY UPDATE `category_id`=VALUES(`category_id`), `posts`=VALUES(`pos' at line 4
<img width="584" alt="error1" src="https://user-images.githubusercontent.com/12942731/57931835-6e6bfe00-7887-11e9-960b-b4f0b28ede83.PNG">

**System information (please complete the following information)**
Joomla version:  4.0.0-alpha8
Kunena version:  6.0.0-ALPHA3-DEV
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by sshcli** [comment]
With the latest build, now I get this error:
<img width="616" alt="now" src="https://user-images.githubusercontent.com/12942731/58829909-00f5f680-8617-11e9-86db-e0bd14e1583c.PNG">

**Comment by xillibit** [comment]
I don't have this error : 
![Sansiitre](https://user-images.githubusercontent.com/876395/58833094-9feb1480-8650-11e9-850d-a301f1422989.png)

**Comment by sshcli** [comment]
Do you see the error @rich20 @810 ?

**Comment by 810** [comment]
i get A query must be a string or a Joomla\Database\QueryInterface instance, a KunenaDatabaseQuery instance was given.

**Comment by xillibit** [comment]
I got it too, i found where is the issue, i will fix them tomorrow
