### ISSUE TITLE
[K6] Selectable Topic Icons are not visible

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6320]
**To Reproduce**
Backend->components->kunena forum->configuration->frontend->Selectable Topic Icons = Yes

**Expected behavior**
You should see the Selectable Topic Icons

**Actual result**
Selectable Topic Icons are not visible
<img width="355" alt="icons" src="https://user-images.githubusercontent.com/12942731/57970410-008b0980-794f-11e9-99f8-86372b8dc967.PNG">

**System information (please complete the following information)**
Joomla version:  4.0.0-alpha8
Kunena version:  6.0.0-ALPHA3-DEV
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by 810** [comment]
Can't reproduce this issue.

**Comment by sshcli** [comment]
Let's wait for @xillibit or @rich20  confirmation.

**Comment by rich20** [comment]
It seems, it has to do with Aurelia. In the backend are both listed: Crypsisb4 and Aurelia. If you choose Crypsisb4 as default it works but with Aurelia I confirm the error.

**Comment by rich20** [comment]
Ok, it's not a bug. Aurelia has the default setting for bootstrap3 icons. If you change to fontawesome, it works.

**Comment by sshcli** [comment]
> Ok, it's not a bug. Aurelia has the default setting for bootstrap3 icons. If you change to fontawesome, it works.

I can confirm that, that is the problem. A PR is needed to change to font awesome as default

**Comment by rich20** [comment]
Yes, default setting for Aurelia should be Fontawesome

**Comment by sshcli** [comment]
I can change it
