### ISSUE TITLE
[K6] Can't edit Aurelia Template

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6330]
**To Reproduce**
1. Install 4.0.0-alpha10-dev + 6.0.0-ALPHA3-DEV-GIT
2. Backend->Try to change something in Aurelia template 

**Expected behavior**
The change should be saved

**Actual result**
The change is not saved and you get this message:

<img width="540" alt="bad" src="https://user-images.githubusercontent.com/12942731/57977202-55676800-79c1-11e9-970f-bcaceb4b9819.PNG">

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10-dev
Kunena version:  6.0.0-ALPHA3-DEV-GIT
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by 810** [comment]
can't reproduce this issue.

**Comment by rich20** [comment]
I saw this message too, but if you mark Aurelia and click on Edit and Save, then the error is gone.

**Comment by sshcli** [comment]
> I saw this message too, but if you mark Aurelia and click on Edit and Save, then the error is gone.

You are right. If you click the save button without changing anything, the error will disappear.

**Comment by xillibit** [comment]
I'am not able to reproduce the issue : the buttons "save" and "save&close" save right the changes

**Comment by rich20** [comment]
It seems a temporary problem. But this error occur again and again. Maybe we have still a remnant from the old template Crypsisb4?
Try this: Logout -> login -> go to Templates and click directly on Aurelius and then save.
