### ISSUE TITLE
Background color of quote should not be #000

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6338]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sshcli** [comment]
There are also spacing \n problems.
Take a look:
<img width="328" alt="poblem" src="https://user-images.githubusercontent.com/12942731/58442458-7878d280-80b9-11e9-8f4b-4d1e3799dea0.PNG">
