### ISSUE TITLE
Error when Recount Statistics

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6341]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `a` LEFT JOIN `rich_users` AS `b`ON a.userid=b.id WHERE banned='1000-01-01 00' at line 2

Joomla version: 4.0.0-alpha10-dev
Kunena version: 6.0.0-ALPHA3-DEV
Php version: 7.3.3 and 7.3.5
Database version: 5.7.25

**Comment by xillibit** [comment]
When i recount stats from backend, i have an error but it's not the same error

**Comment by rich20** [comment]
You're right, the error messages are not the same anymore since the database adjustments. Now is the error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 20

**Comment by rich20** [comment]
This issue is solved
