### ISSUE TITLE
Error when you add an attachment and save the message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6345]
Exception throw at line 419 in file .../libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php with message Incorrect integer value: '' for column 'protected' at row 1

Joomla version: 4.0.0-alpha10-dev
Kunena version: 6.0.0-ALPHA3-DEV
Php version: 7.3.3 and 7.3.5
Database version: 5.7.25

**Comment by rich20** [comment]
The error is related to this bug https://github.com/Kunena/Kunena-Forum/issues/6367, so I close this ticket.

**Comment by xillibit** [comment]
The error mentionned in this issue doesn't appear anymore ?

**Comment by rich20** [comment]
When the folder "core" including content is available in media/kunena then is no error anymore.
