### ISSUE TITLE
We get some mistakes because the paths do not exist

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6346]
**Read a topic and open the console**
... /media/kunena/core/css/jquery.atwho.css (canceled)
.../media/kunena/core/js/jquery.caret.js (404)
.../media/kunena/core/js/jquery.atwho.js (404)

**Open the membership list below**
.../components/com_kunena/template/aurelia/assets/css/jquery.atwho.css (canceled)
.../components/com_kunena/template/aurelia/assets/js/jquery.caret.js (404)
.../components/com_kunena/template/aurelia/assets/js/jquery.atwho.js (404)

**Comment by 810** [comment]
can't reproduce this issue, i see no error on console.

**Comment by 810** [comment]
ok, i see them on memberlist page.
