### ISSUE TITLE
Replace KunenaDatabaseQuery to joomla database

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#6349]
``
$query = new KunenaDatabaseQuery;
``

To

``
$query = $this->_db->getQuery(true);
		$query->select('*')
			->from($this->_db->quoteName('#__kunena_rate'))
			->where($this->_db->quoteName('topic_id') . ' = ' . $this->_db->quote($this->topic_id));
		$this->_db->setQuery($query, $start, $limit);
``

**Comment by mahagr** [comment]
If I remember correctly, our version was slightly different from Joomla one, possibly implementing or fixing something that didn't work in Joomla. Also, Kunena had this class before it was added to Joomla back in 2009(ish), I just remember updating the class at some point to better match Joomla version of the class.

In most queries I do not think there's a reason to keep the old class -- but be careful when you are converting the more complicated queries to use Joomla class.
