### ISSUE TITLE
[K6] Modal to uninstall kunena not loading properly

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6368]
**To Reproduce**
Try to uninstall kunena via backend

**Expected behavior**
The confirmation modal should load properly 

**Actual result**
<img width="573" alt="bad" src="https://user-images.githubusercontent.com/12942731/58441854-9e02dd80-80b3-11e9-8d04-10f30d065f61.PNG">

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10-dev
Kunena version:  6.0.0-ALPHA3-DEV-GIT
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by rich20** [comment]
The same error if you want to show a log action (Logs -> click on ACD or ERR)
