### ISSUE TITLE
[K6] Favorite button using wrong class 

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6371]
**To Reproduce**
Go to any topic and take a look to the favorite button.

**Expected behavior**
It should be an empty star 

**Actual result**
<img width="416" alt="wrong" src="https://user-images.githubusercontent.com/12942731/58442321-30a57b80-80b8-11e9-969b-1b9e52cf9f0f.PNG">

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10-dev
Kunena version:  6.0.0-ALPHA3-DEV-GIT
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by 810** [comment]
for me its working, please check Icon Type option.

**Comment by sshcli** [comment]
ok, I found what was the problem.
Load External CDN Fontawesome = No

I'm closing this issue
