### ISSUE TITLE
Syntax error in the backend statistics

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6376]
An error has occurred.
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2

 **| Function | Location**
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:135
2 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:943
3 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1841
4 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/libraries/kunena/database/object/finder.php:261
5 | KunenaDatabaseObjectFinder->count() | JROOT/administrator/components/com_kunena/models/statistics.php:72
6 | KunenaAdminModelStatistics->getTotal() | JROOT/libraries/src/MVC/Model/ListModel.php:243
7 | Joomla\CMS\MVC\Model\ListModel->getPagination() | JROOT/libraries/src/MVC/View/AbstractView.php:146
8 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/administrator/components/com_kunena/views/statistics/view.html.php:34
9 | KunenaAdminViewStatistics->displayDefault() | JROOT/libraries/kunena/view.php:209
10 | KunenaView->displayLayout() | JROOT/libraries/kunena/view.php:137
11 | KunenaView->displayAll() | JROOT/libraries/kunena/controller.php:437
12 | KunenaController->display() | JROOT/libraries/kunena/controller.php:324
13 | KunenaController->executeTask() | JROOT/libraries/kunena/controller.php:215
14 | KunenaController->execute() | JROOT/administrator/components/com_kunena/kunena.php:80
15 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:69
16 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:382
18 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:116
19 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
20 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:241
21 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
22 | require_once() | JROOT/administrator/index.php:36

**Comment by xillibit** [comment]
it's the same issue that this one : https://github.com/Kunena/Kunena-Forum/issues/6341

**Comment by rich20** [comment]
Sorry I was inattentive, so I close this ticket.
