### ISSUE TITLE
"Hide Super Users in user list" does not hidden the admin

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6383]
Configuration-> Tab Extra -> Hide Super Users in user list = Yes
This option makes hides the admin only in the frontend statistics, but in the user list the admin remain.

**Comment by 810** [comment]
For me the admin should be listed on the backend

**Comment by rich20** [comment]
Sorry, when I've written it misleading.
Should be:
This option makes hides the admin only in the frontend statistics, but in the **frontend** user list the admin remain.
