### ISSUE TITLE
Instead of pictures, the text is displayed - You do not have permissions to access this page.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6384]
Add more then one image in a message and save it. Only the first image will displayed. Instead of the next images it shows the text - You do not have permissions to access this page.

**Comment by xillibit** [comment]
@mahagr : it seems there is an issue with `loadObjectList('id', 'KunenaAttachment')` https://github.com/joomla/joomla-cms/issues/24857#issuecomment-498331528

It's used in the file : https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/libraries/kunena/attachment/helper.php#L241

The only way i have found to make it working, it's to load the instance of KunenaAttachment on each object returned : 

```
try
{
	$results = (array) $db->loadObjectList('id');
}
catch (RuntimeException $e)
{
	KunenaError::displayDatabaseError($e);
}

foreach ($ids as $mesid)
{
	if (!isset(self::$_messages [$mesid]))
	{
		self::$_messages [$mesid] = array();
	}
}

foreach ($results as $id => $instance)
{
	$instance = KunenaAttachmentHelper::get($id);
        self::$_instances [$id]                  = $instance;
	self::$_messages [$instance->mesid][$id] = $instance;
}
```

The changes : https://github.com/xillibit/Kunena-forum/commit/21954a344c27e10040ab11ed1956c6cfe878b365

It can be fixed like that ?

**Comment by rich20** [comment]
This fix does not change this problem. It is still the same, and the second (or more) added attachment(s) will listed in the backend diagnostic tool as orphaned.

**Comment by xillibit** [comment]
The second attachment or more doesn't have the mesid filled so it explains why it's displayed as orphaned

**Comment by mahagr** [comment]
Sorry, back from my vacation...

This may be difference between our database methods and Joomla one? I didn't really take a look into the code, but make sure you load everything by using just a single database query, otherwise you will cause major slowdown if there are multiple posts with a lot of attachments.
