### ISSUE TITLE
Trash | Purge items is not possible, only the Cancel button is active

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6389]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xillibit** [comment]
I'am not sure if this one will fix this too : https://github.com/Kunena/Kunena-Forum/pull/6403/files, but i have a stange things there is in topics trash an topic with id 35 but i don't find it in database... So we need to clean the database and re-try with proper things after applying my last PR

**Comment by xillibit** [comment]
You need to select items in order to restore or delete them
