### ISSUE TITLE
The Index page does not recognize any read topics

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6394]
1. Open the profile dropdown and mark all as read (all folders are now in blue color)
2. Create a new topic or write an answer in an exist topic
3. Go to the Index

The folder of this category is now green, and you can read this topic as often you want, it shows this category has an unread topic

**Comment by 810** [comment]
old bug:
todo  Currently new topics needs to be calculated manually, make it automatic.

**Comment by rich20** [comment]
This error no longer exist.
