### ISSUE TITLE
Hide Super Users in user list | At the statistic option Most Active Posters the admin is still displayed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6400]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 810** [comment]
Hide Super Users in user list, is only for the userlist, not for statistics

**Comment by sshcli** [comment]
In K5.1 is hidden in both when the option is enabled

**Comment by xillibit** [comment]
I'am not to able to see the issue, when i set in configuration settings don't show admins in userlist i'am not able to see it

**Comment by rich20** [comment]
In the user list he is hidden, but with Kunena 5.1 the admin is also hidden at all options in the frontend statistics.

**Comment by rich20** [comment]
Here a double screenshot with both settings

![g1135](https://user-images.githubusercontent.com/888847/59704067-925e8e80-91fb-11e9-93b4-70ea9fb2f570.png)
