### ISSUE TITLE
If you purge items you must navigate new to Kunena

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6422]
Go in backend to the trash, mark a message and click on Purge Items. This click close the toggle menu on left. If you want back to Kunena, you must navigate from the beginning again  "Components -> Kunena Forum -> Dashboard".
On all other options such as Prune Categories etc.. the toggle menu will open again correctly after an action, or you have a cancel button.

**Comment by xillibit** [comment]
Is this still happens with last build of K6.0 ?

**Comment by rich20** [comment]
Yes, it's the same. The left menu is closed and there are also not a Back button.


.
![Bildschirmfoto von 2019-12-21 19-14-29](https://user-images.githubusercontent.com/888847/71312023-937cac80-2426-11ea-98ed-145c9666538a.png)

**Comment by rich20** [comment]
Is not a big problem but it's the only option where it is so.

**Comment by rich20** [comment]
This iissue do not exist anymore.
