### ISSUE TITLE
[K6] Plg System Untranslated strings

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6426]
**To Reproduce**
Go to example.com/index.php/component/users/profile?Itemid=1

**Expected behavior**
You should see the human readable words

**Actual result**
<img width="667" alt="bad" src="https://user-images.githubusercontent.com/12942731/58829600-351ce780-8616-11e9-9a0e-86fcfab84aa4.PNG">

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10-dev
Kunena version:  6.0.0-ALPHA4-DEV-GIT
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by 810** [comment]
its not a kunena bug.
