### ISSUE TITLE
[K6] No highlight when different settings

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6427]
**To Reproduce**
Go to backend->Kunena configuration

**Expected behavior**
<img width="536" alt="good2" src="https://user-images.githubusercontent.com/12942731/58830243-e7a17a00-8617-11e9-901b-754ebc708ca0.PNG">

**Actual result**
<img width="578" alt="bad2" src="https://user-images.githubusercontent.com/12942731/58830236-e4a68980-8617-11e9-9334-297e8af0178b.PNG">

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10-dev
Kunena version:  6.0.0-ALPHA4-DEV-GIT
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by rich20** [comment]
Solved by this PR https://github.com/Kunena/Kunena-Forum/pull/9626
