### ISSUE TITLE
SEO: Page title is duplicate in user list pagination

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6433]
**To Reproduce**
Go to user list in frontend and navigate to page 2, 3 4 and so on..

**Expected behavior**
Page title should be unique

**Actual result**
Page title is duplicate in user list pagination

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10-dev and 3.9.6
Kunena version:  6.0.0-ALPHA4-DEV-GIT and 5.1.12.1
Php version: 7.3.5
Database version: MySQL 5.7.26

**Comment by 810** [comment]
Page title is ok for me: User List (2/2) - Kunena

**Comment by sshcli** [comment]
The method (2/2) is deprecated in kunena, it was removed because page title is changing very often.
We should use Page 2 instead (Same method used in recent topics, etc..)
