### ISSUE TITLE
[5.1] PHP 5.6 Compatibility issues

### ISSUE THREAD

**Issue by pgasiorowski** [Kunena/Kunena-Forum#6452]
**Describe the bug**
```
Fatal error: Default value for parameters with a class type hint can only be NULL in /components/com_kunena/controllers/user.php on line 1347

Fatal error: Cannot use Joomla\CMS\Factory as Factory because the name is already in use in /libraries/kunena/log/entry.php on line 13
```

Although not a big deal for me as I'm running production with PHP 7.
One of the test servers is still on 5.6 which is giving this error so I thought I'd let you know.

I'm reporting this because : 
> Kunena 5.1 requires  ... PHP: version 5.6.8 or greater (>= 7.1.9 recommended)

**To Reproduce**
1. Go to user profile
2. Edit something and save
3. See error

**Expected behavior**
Save successful 

**Actual result**
Fatal error.

Joomla version: 3.9.6
Kunena version: 5.1.12.1
Php version: 5.6.40
Database version: 5.7

**Comment by xillibit** [comment]
Thanks for reporting the issue, it has been a while that we don't use Php 5.6.x but i will make some test with Php 5.6.40
