### ISSUE TITLE
Profile: Move single message moves the complete topic

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6461]
1. Log in in the frontend as admin or global mod
2. Klick on tab Profile
3. Mark with the checkbox a single message of a topic and move them

**Expected behavior**
Only this one post should be moved

**Actual result**
It moves the complete topic

**Comment by 810** [comment]
The latest post are topics not messages,

**Comment by rich20** [comment]
>2. **Klick on tab Profile**
>3. Mark with the checkbox a single message of a topic and move them

Try it with K5.1 and you see the difference:
The Post has been successfully moved.

**Comment by rich20** [comment]
Here a example:
Kunena 5.1 moves only the one with checkbox marked message. But Kunena 6.0 moves all messages of this topic (red marked).
![Bildschirmfoto von 2019-08-08 20-35-01 png](https://user-images.githubusercontent.com/888847/62729495-55a25d00-ba1e-11e9-9a9a-b9cb780938fa.png)

**Comment by xillibit** [comment]
Fixed by : https://github.com/Kunena/Kunena-Forum/pull/9109
