### ISSUE TITLE
After submit a Reply, Quick Reply or Edit, you landing on top

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6479]
After submit a Reply, Quick Reply or Edit, you landing on top and you must scroll down to the message.

**Comment by xillibit** [comment]
This issue doesn't appears on crypsis on K5.1 ?

**Comment by rich20** [comment]
No, with Crypsis you landing directly on the message which you've written.

**Comment by 810** [comment]
i can;t reproduce this issue, for me its loading the correct scroll

**Comment by xillibit** [comment]
i'am not able to reproduce the issue neither
