### ISSUE TITLE
Activation pending accounts are being deleted

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6497]
**To Reproduce**
Backend->Components->Kunena->Tools->Synchronize Users->Delete lifetime ban users

**Expected behavior**
It should not delete the user accounts that are pending of activation.
if this is mandatory, at least must keep those created the current day.

**Actual result**
It will delete all user accounts that are pending of activation 

**System information (please complete the following information)**
Joomla version: 3.9.8 and 4.0.0-alpha10-dev
Kunena version: 5.1.12.1 and 6.0.0-ALPHA4-DEV
Php version: 7.3.6
Database version: MySQL 5.7.26

**Comment by sshcli** [comment]
Please reopen, this issue must be solved also in K5.1

**Comment by xillibit** [comment]
@sshcli : i have changed the datetime format on K6.0 to follow new mysql format, but on K5.1 it's the same as before. So the fix can't be applied but i will look to make a fix.

**Comment by xillibit** [comment]
I close it, it's in K5.1 and K6.0
