### ISSUE TITLE
Setting "Edit avatar by clicking on avatar" results in an error

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6501]
**Describe the bug**
If you click on avatar, it goes to the first tab and the console shows this error:

jquery.min.js?3.4.1:2 Uncaught Error: Syntax error, unrecognized expression: .nav-tabs a[href=#editavatar]
>DevTools failed to parse SourceMap: .../media/vendor/bootstrap/js/bootstrap.bundle.min.js.map

![Bildschirmfoto von 2019-07-13 17-23-29](https://user-images.githubusercontent.com/888847/61173601-cd9f7380-a595-11e9-9c66-e9043a3b4df0.png)

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10 and 4.0.0-alpha11-dev
Kunena version: 6.0.0-ALPHA4-DEV
Php version: 7.3
Database version:

**Additional context**
This one message you get on all pages, so I think, maybe it's a Joomla issue:
>DevTools failed to parse SourceMap: .../media/vendor/bootstrap/js/bootstrap.bundle.min.js.map

**Comment by xillibit** [comment]
> If you click on avatar, it goes to the first tab and the console shows this error:

You need to enable the setting "Edit avatar by clicking on avatar" to be able to do that

> This one message you get on all pages, so I think, maybe it's a Joomla issue:
> 
> > DevTools failed to parse SourceMap: .../media/vendor/bootstrap/js/bootstrap.bundle.min.js.map

I don't have this error with last build of J!4.0
