### ISSUE TITLE
When delete last exist message of a topic deletes not the database entries

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6502]
**Describe the bug**
1. Create a new topic (without replies)
2. Delete this message via the message delete button
3. Delete this message now permanently via this button
4. Go in the backend to the diagnostic tool
You have now a broken item "topicMissingMessages"
5. Delete (fix) this broken item
After delete you get two more broken items userReadOrphaned and userTopicOrphaned

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10 and 4.0.0-alpha11-dev
Kunena version: 6.0.0-ALPHA4-DEV
Php version: 7.3
Database version:

**Additional context**
This problem exists only with K 6

**Comment by xillibit** [comment]
I think this issue still exists on K6.1.x ?

**Comment by rich20** [comment]
This error is no longer present.
