### ISSUE TITLE
 Frontend | Kunena Internal Error when you ban or unban an user

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6511]
**Describe the bug**
Ban or unban works but you get the message:
Kunena Internal Error: Please contact the site administrator to fix this issue!
The debug mode shows also not more

**System information (please complete the following information)**
Joomla version: 4.0.0-alpha10 and 4.0.0-alpha11-dev
Kunena version: 6.0.0-ALPHA4-DEV
Php version: 7.3.6

**Comment by xillibit** [comment]
I don't able to reproduce this issue

**Comment by rich20** [comment]
I've tried as Global Moderator. As Super User I see more:
Exception throw at line 440 in file .../libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php with message Column 'banned' cannot be null

Tried with Joomla version: 4.0.0-alpha10 and 4.0.0-alpha11-dev

**Comment by xillibit** [comment]
I'am still not able to reproduce this issue, even if i let empty the expiration date of ban

**Comment by rich20** [comment]
Use you the github or installed version? Maybe is a difference between these versions?
I've the installed version. If you use the same I will close this issue for now.

**Comment by xillibit** [comment]
I'am using github version of Kunena, and github version of Joomla!

**Comment by rich20** [comment]
I'm use this Joomla versions:
https://github.com/joomla/joomla-cms/releases/tag/4.0.0-alpha10
https://developer.joomla.org/nightly-builds.html (last build Tuesday, 16 July 2019 02:01:15 UTC)
And I use a Kunena install package from the current Branch of K.6.0

**Comment by xillibit** [comment]
Can-you check in your table #__kunena_users if the column "banned" in the table definition has right for default value "1000-01-01 00:00:00" ?

**Comment by rich20** [comment]
The Super User (cannot be banned) has 1000-01-01 00:00:00
Users which are already was banned and the ban has been removed have the current time of ban 
2019-07-16 13:48:35

**Comment by rich20** [comment]
Found it. It was a Joomla user table error 
I've noticed it as I had removed Kunena complete and saw not my Super user login name after the installation. JLIB_USER_ERROR_UNABLE_TO_LOAD_USER
But nevertheless I could login without problems.
I've installed Joomla complete new and it works now. Sorry for your time. 
![Bildschirmfoto von 2019-07-16 17-40-19](https://user-images.githubusercontent.com/888847/61309454-84982b00-a7f2-11e9-9ac1-d96278c13b63.png)

**Comment by xillibit** [comment]
> The Super User (cannot be banned) has 1000-01-01 00:00:00

That's is the value when there is no ban to the user

**Comment by rich20** [comment]
Ok, I found the cause of this problem.
1. Set in the Kunena configuration (tab Users) the option "Define if you want to log action or moderation = Yes"
2. Now ban an user in the frontend and sou see this error:

Exception throw at line 445 in file /.../libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php with message Column 'banned' cannot be null
