### ISSUE TITLE
Original Forum Topic Keeps Spam Post Subject after Spam Post is Deleted

### ISSUE THREAD

**Issue by eSilverStrike** [Kunena/Kunena-Forum#6535]
**Describe the bug**
Forum posts must be approved.
A spammer posts in a forum topic that has a bunch of other real posts. As Admin I use the front end to delete the spam post. The original forum topic still displays the spam post subject.

**To Reproduce**

**Expected behavior**
Forum topic should keep original subject

**Actual result**
Forum topic displays deleted spam post subject

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.9.10
Kunena version: 5.1.13.1
Php version: 7.1.30

**Comment by rich20** [comment]
Thanks for reporting this issue but it's the same issue as here https://github.com/Kunena/Kunena-Forum/issues/6272 so I close this second ticket.

The title should only changed for this one message (when you changes the title), or if you reply directly a changed message. Not if you reply the topic with the button "Reply Topic" on bottom.

Disable the option "Let users edit the subject" in the configuration (tab Frontend) for now,  Admins and mods can change the title anyway.
