### ISSUE TITLE
Convert database charset to utf8mb4 and utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by ZerooCool** [Kunena/Kunena-Forum#6572]
I tested to integrate a Unicode image in a Joomla article, which worked perfectly, but, I also tried to integrate a unicode image in my Kunena forum, and, that failed.

I converted the base to utf8mb4 with utf8mb4_unicode_ci collation and it works now. I am surprised that it did not work on the Kunena forum.

I use a new installation, my website was installed 01/01/2019 with official repo.

I have use this script to convert all tables from my database :
https://github.com/ZerooCool/charset-utf8mb4-collation-utf8mb4_unicode_ci-mysql-mariadb/blob/master/utf8-utf8mb4.sh

Now, i can add unicode picture.

This upgrade is ok or with a risk ?

**Comment by 810** [comment]
For new Kunena installation we have a check if the global database has utf8mb4, then kunena will also have utf8mb4, else the database will get the global option.

our check: https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/administrator/components/com_kunena/install/install.script.php#L697

For already installed kunena versions:

1) Install akeeba tools
2) Then convert the database by the tool.

We are waiting for the final version of Joomla 4.0 then we will have the automatic upgrade by the installer.

**Comment by 810** [comment]
Also see:
https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/administrator/components/com_kunena/install/sql/migrate/mysql/utf8mb4-conversion.sql

**Comment by ZerooCool** [comment]
Your last script seems to specify each of the tables one by one.

My proposed script, it converts all the references base, tables, columns, utf8mb4 + utf8mb4_unicode_ci and that, automatically.

I especially hope that I did not do badly, in the case where one or more tables or columns should not be converted.

For the moment, it works with use.

https://www.visionduweb.fr/forum/base-de-donnees/132-enregistrer-les-caracteres-unicode-avec-l-encodage-utf8mb4#154

**Comment by 810** [comment]
Yes we want only change the kunena database tables, 3rt party extensions should not touch the core and other 3rt party tables.

If you want to change it, we recommend tools like Akeeba Tools, who migrating all tables automatically. Just within joomla itself, so no needed for extra knowledge. Simple click.
