### ISSUE TITLE
Statistics | Error 1064 - You have an error in your SQL syntax

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6579]
**Describe the bug**
If you click in the backend on Statistics you get this error:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:149
2 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:1051
3 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1862
4 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/libraries/kunena/database/object/finder.php:263
5 | KunenaDatabaseObjectFinder->count() | JROOT/administrator/components/com_kunena/models/statistics.php:72
6 | KunenaAdminModelStatistics->getTotal() | JROOT/libraries/src/MVC/Model/ListModel.php:242
7 | Joomla\CMS\MVC\Model\ListModel->getPagination() | JROOT/libraries/src/MVC/View/AbstractView.php:146
8 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/administrator/components/com_kunena/views/statistics/view.html.php:34
9 | KunenaAdminViewStatistics->displayDefault() | JROOT/libraries/kunena/view.php:209
10 | KunenaView->displayLayout() | JROOT/libraries/kunena/view.php:137
11 | KunenaView->displayAll() | JROOT/libraries/kunena/controller.php:436
12 | KunenaController->display() | JROOT/libraries/kunena/controller.php:324
13 | KunenaController->executeTask() | JROOT/libraries/kunena/controller.php:215
14 | KunenaController->execute() | JROOT/administrator/components/com_kunena/kunena.php:80
15 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:69
16 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:383
18 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:117
19 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:160
20 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:242
21 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
22 | require_once() | JROOT/administrator/index.php:36

**System information (please complete the following information)**

Joomla version: ‎4.0.0-beta1-dev
Kunena version: 6.0.0-ALPHA4-DEV
Php version: 7.3.6
Database version: 5.7.26

**Comment by sozzled** [comment]
I don't know what the backend statistics function does.  I have never been able to obtain any results from the feature but, perhaps, there's a setting that needs to be enabled, somewhere?

I can't find Joomla 4.0.0-beta1-dev on GitHub, sorry.  I haven't seen any announcement about its release.  UPDATE:  Forget this last sentence; there's a nightly build (unofficial release) for J! 4 beta available https://developer.joomla.org/nightly-builds.html

**Comment by rich20** [comment]
You must enable the option "Define if you want to log action or moderation" (tab Users), then you should get a statistic about the moderator actions.

**Comment by sozzled** [comment]
Thank you for that information, Rich.
