### ISSUE TITLE
Ban users in the frontend is not possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6596]
**Describe the bug**
Ban users in the frontend is not possible, but it works in the backend.

**To Reproduce**
- [ ] If you want ban from the forum you get the message:
**User ban successfully removed.**
- [ ] If you want ban from the site you get the message:
**User account successfully enabled.**

**System information (please complete the following information)**
Joomla version: ‎4.0.0-beta1-dev
Kunena version: 6.0.0-ALPHA4-DEV
Php version: 7.3.6
Database version: 5.7.26

**Comment by xillibit** [comment]
This is just a fix related to the issue but it not fix it

**Comment by xillibit** [comment]
> If you ban an user only from the Forum (not from the site) and you set a time where the ban ended, then the user should not have write access before the ban ended. But the user remain a normal user without ban and can nevertheless write posts.

The user banned should be logged out when the mod/admin do the ban
