### ISSUE TITLE
Kunena installation is not possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6612]
Call stack
--
# | Function | Location
1 | () | JROOT/administrator/components/com_kunena/install/model.php:2813
2 | KunenaControllerInstall->__construct() | JROOT/administrator/components/com_kunena/install.php:41
3 | require_once() | JROOT/administrator/components/com_kunena/kunena.php:25
4 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:69
5 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
6 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:383
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:117
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:160
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:230
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
11 | require_once() | JROOT/administrator/index.php:36

**System information (please complete the following information)**
Joomla version: ‎4.0.0-beta1-dev
Kunena version: 6.0.0-ALPHA4-DEV
Php version: 7.3.11
Database version: 5.7.26

**Comment by xillibit** [comment]
You have this issue just when you are installing Kunena ?

**Comment by rich20** [comment]
Yes, the installation will cancelled with this error. I've tried with a complete clean Joomla 4.0 Nightly build and also an update on a second page. Both pages shows the same error.
The Kunena packed is created with the last merges from today.

**Comment by rich20** [comment]
Addition. The Joomla dashboard shows afterwards "Pleas complete Kunena installation"
