### ISSUE TITLE
Unknown fetch type '8' 

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#6619]
**Describe the bug**
Unknown fetch type '8'

JROOT/libraries/kunena/forum/category/helper.php:101

**To Reproduce**
K6.0

See:
https://github.com/joomla/joomla-cms/issues/24857

**Comment by xillibit** [comment]
Where do-you have this issue now ?

**Comment by 810** [comment]
Do git pull, then composer install. The Joomla/database Will be updates. Then you Will have this issue

**Comment by xillibit** [comment]
I have updated Joomla! but not composer, i will try it
