### ISSUE TITLE
Checking for the presence of a checkbox in Cryspis category template does not work.

### ISSUE THREAD

**Issue by Bozhkov85** [Kunena/Kunena-Forum#6623]
com_kunena/template/crypsis/layouts/category/item/default.php
row 18

> $cols            = empty($this->checkbox) ? 5 : 6;

regardless of checkbox availability always returns 5. In this regard, the table is not built correctly and there are errors on the page.

**Comment by xillibit** [comment]
The row 18 in file com_kunena/template/crypsis/layouts/category/item/default.php has been modified :

`$cols            = empty($this->checkbox) ? 7 : 6;`

Feel to open a new issue if the issue is till here
