### ISSUE TITLE
Please add this strings in the frontend com_kunena.ini

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6628]
Currently are the string in the administrator libraries.ini and will not displayed in the frontend.

COM_KUNENA_EDITOR_SECURE_REPLY_TAB = "Secure reply"
COM_KUNENA_EDITOR_SECURE_REPLY_PALCEHOLDER = "Enter your private message here"
COM_KUNENA_BBCODE_SECURE_TEXT = "This message contains secure information"

**Comment by xillibit** [comment]
The file ```\administrator/components/com_kunena/language/en-GB/en-GB.com_kunena.libraries.ini``` is right loaded in frontend and so these strings too

**Comment by rich20** [comment]
hm.. on my second test page it works, so I close this issue.
