### ISSUE TITLE
Getting PHP error: 'invalid argument for foreach() in bbcode.php line 409"

### ISSUE THREAD

**Issue by PhracturedBlue** [Kunena/Kunena-Forum#6633]
Kunena version: 5.1.15
PHP: 7.3.12

For some threads, I see this in the logs:
Invalid argument supplied for foreach() in /var/www/html/libraries/kunena/bbcode/bbcode.php on line 409

The only thing odd I see is a malformed link in one of the messages:
```
http://walkera-fans.de/downloads/.................

http://walkera-fans.de/download/sender/Devo_10/Devo10%20Firmware%200.8A%20und%200.8B.zip
```
I was able to work around this by altering line 409 to be:
```foreach ((array)$search as $index => $token)```
But I doubt that is the right answer.

**Comment by 810** [comment]
Could you please add a example bbcode from a topic where this issue comes from. (So copy message to this issue report)

**Comment by PhracturedBlue** [comment]
I don't understand your request.  I pasted the only message I see in the topic which might be causing the issue (I don't know how to be sure which message it is, since the data sent to the foreach loop is NULL)

**Comment by xillibit** [comment]
Can-you give please the links which produce this issue ?

**Comment by PhracturedBlue** [comment]
I believe it is this message:

https://deviationtx.com/forum/stock-firmware-help/4749-devo-10-firmware-upgrade#37275

If I edit this message as admin, it has the contents I listed above, but when you view it in the browser, the 1st link is missing.

**Comment by rich20** [comment]
Maybe the user has entered a wrong link. A link with many points at the end is not a correct link. Remove the points and the error should be gone.
