### ISSUE TITLE
where to pull request on blue_eagle5 theme improvement?

### ISSUE THREAD

**Issue by alexrayne** [Kunena/Kunena-Forum#6643]
Hallow!
i`ve introduce hihglighting new answers notyficaton, and quoted text more strong highlight.
where i can publish this patch?

**Comment by 810** [comment]
Hello alexrayne, because blue eagle is a paid template, we have set it to private. You can send the edited files, or whole template to jelle@kunena.org, and i will merge it to the template, and will add a thank you on the release.
