### ISSUE TITLE
Notice: Undefined index when message body is empty (Part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6666]
It seems this fix https://github.com/Kunena/Kunena-Forum/issues/6663 is not complete.
You get the hint "Please fill in this field" when the subject is empty, but not when the text field is empty.
When the text field is empty, you get only:
Error
Cannot save message: Message body is empty!

For comparison, K5.1 shows this:
![Bildschirmfoto von 2019-12-27 15-27-38](https://user-images.githubusercontent.com/888847/71521418-01aaee80-28c1-11ea-99cf-1fb1740c8c4d.png)

**Comment by xillibit** [comment]
> You get the hint "Please fill in this field" when the subject is empty, but not when the text field is empty.

I had removed it lastly in K6.0 because it was preventing working a feature
