### ISSUE TITLE
Trashbin: Purge or restore topics is not possible (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6686]
https://github.com/Kunena/Kunena-Forum/issues/6678 It's only possible to purge or restore the automatically created topic Welcome Mat
- [ ] If you want to restore other topics, it makes only a page refresh
- [ ] Purge indicates - These **0 items** will be permanently deleted from your forum! Are you sure?

**Comment by xillibit** [comment]
Just checked, i have created a new topic and delete it, then when i restore and purge it, the both functions works. Restore function : 

![restore](https://user-images.githubusercontent.com/876395/71624037-cb32e380-2be0-11ea-908f-07ae1d640046.png)

For purge :  

![purge_warning](https://user-images.githubusercontent.com/876395/71624042-d71ea580-2be0-11ea-8be1-33f0d8595dd0.png)

![purge_success](https://user-images.githubusercontent.com/876395/71624044-dbe35980-2be0-11ea-8dc6-f52a343affb6.png)

**Comment by rich20** [comment]
I've now removed complete K alpha 5 and installed alpha 6. It works and I close this here for now, but I will have to observe it, because I had this error on 2 independent different test pages.
