### ISSUE TITLE
When editing a message as admin from an another user, the subject change for the topic

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#6692]
**Describe the bug**

When editing a message as admin maybe moderator too from an another user, the subject change for the topic even if it's not desired

**To Reproduce**
1. Edit an existing message from another user in a topic as admin or mod
2. Then submit the subject has changed for the entire topic

**Expected behavior**
The subject shouldn't change if it hasn't been edited

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.9.x
Kunena version: 5.1.15
Php version: 7.3.13
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rich20** [comment]
I've already reported this bug. https://github.com/Kunena/Kunena-Forum/issues/6272

**Comment by xillibit** [comment]
I didn't seen it, so i close this one
