### ISSUE TITLE
Error when deleting topics

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6697]
**To Reproduce**
1. Let the complete Kunena setting as default
2. Upload an Avatar for you
3. Create a new topic or write a reply 
4. Now use the button Moderation and delete the Topic

**Result**
The topic is deleted but you get this error:
Warning: DOMDocument::load(.../media/kunena/topic_icons/default/user/svg/.svg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /.../libraries/kunena/icons/svg.php on line 66

Warning: DOMDocument::load(): I/O warning : failed to load external entity ".../media/kunena/topic_icons/default/user/svg/.svg" in /.../libraries/kunena/icons/svg.php on line 66

**Comment by rich20** [comment]
hm.. this error occur also with a complete clean installation without uploaded Avatars, when I delete Welcome Mat.

**Comment by xillibit** [comment]
It's missing the corresponding icons to B4 from this line : https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/media/kunena/topic_icons/default/topicicons.xml#L31 and until : https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/media/kunena/topic_icons/default/topicicons.xml#L36
