### ISSUE TITLE
The plus symbol in the poll modal opens the calendar

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6707]
**System information**
Joomla version: ‎4.0.0-beta1-dev
Kunena version: 6.0.0-ALPHA6-DEV
Php version: 7.3.11
Database version: 5.7.28

**Comment by xillibit** [comment]
I'am not able to reproduce this issue, when i click on plus icon it opens right the new field

**Comment by rich20** [comment]
Maybe a browser issue?
I've tested with Chromium, Firefox and Opera (all Linux) and also on 2 different test pages.
![path817](https://user-images.githubusercontent.com/888847/71781081-e9c32100-2fca-11ea-829e-fdab142adc14.png)

**Comment by xillibit** [comment]
I have tested only with Firefox, but do-you have d'abord bootstrap 4
setting ? Because in my case i have fontawesome enabled

Le dim. 5 janv. 2020 à 14:53, Richard Binder <notifications@github.com> a
écrit :

**Comment by rich20** [comment]
Yes, you're right. I've the default setting bootstrap 4. With fontawesome it works.

**Comment by rich20** [comment]
This problem no longer exists
