### ISSUE TITLE
Synchronize Users [Delete lifetime ban users] empties the complete table #_kunena_users

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6720]
**To Reproduce**
Choose the option "**Delete lifetime ban users**" on user synchronization and click on Sync

**Actual result**
The complete #_kunena_user table has been emptied. You can fill the table again with the sync option "Add user profiles to everyone" but the profile informations of all users (like avatars, signatures, birthdays etc..) are lost.
Maybe this isue is related to this error: https://github.com/Kunena/Kunena-Forum/issues/6695

**System information**
Joomla version: ‎4.0.0-beta1-dev
Kunena version: 6.0.0-ALPHA6-DEV
Php version: 7.3.11
Database version: 5.7.28

**Comment by xillibit** [comment]
Not possible to reproduce it now
