### ISSUE TITLE
Can't save profile when Signatures = No

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6748]
**To Reproduce**
1. Backend->Configuration - > Users->Signatures = No
2. Frontend-> example.com/forum/profile/edit ->Edit Profile Information
3. Personal Text = Hello World
4. Click the save button 

**Expected behavior**
The Personal Text should be "Hello World"

**Actual result**
The Personal Text is not being saved

**System information (please complete the following information)**
Joomla version: 3.9.15 and 4.0.0-beta1-dev 
Kunena version: 5.1.15 and  6.0.0-ALPHA6-DEV 
Php version: 7.3.14 and 7.2.26
Database version:  MySQL 5.7.29 and MariaDB 5.5.5-10.3.21

**Comment by rich20** [comment]
Additional info: This only applies to options that are included in the tab Profile Informations. The options in other tabs like Forum Settings etc.. you can save.

**Comment by sshcli** [comment]
This problem also exists in K.6

**Comment by rich20** [comment]
Cross-system K5.1 bugs do not require an additional label for K.6.
