### ISSUE TITLE
Display error for the number of views of a message?

### ISSUE THREAD

**Issue by ZerooCool** [Kunena/Kunena-Forum#6753]
From my website : https://www.visionduweb.fr/forum/lire-les-cgu

I see : 

```
Politique de gestion des cookies					 		 			 			 			 					  		 			Sujet démarré							il y a 1 an 1 mois, 						par			Visionduweb | Réponses:0 		Vues:12.50 | Dernier message							 par Visionduweb					 						 						il y a 1 an 1 mois
-- | -- | --
  | 
```

Vues:12.50

The number should be displayed as: Vues: 1.250 , or , Vues:1250 , or, Vues:1 250

I don't know if this is a problem with Kunena or with the crypsis template.

**Comment by 810** [comment]
i think the language string is missing the K, so it should be 12.50K views

**Comment by ZerooCool** [comment]
My Kunena is up to date. Would it be a Kunena problem? Template? My Joomla?

**Comment by rich20** [comment]
It's an error in the French translation in the fr-FR.com_kunena.libraries.ini line 492 (/administrator/language/fr-FR/)
COM_KUNENA_THOUSAND = "0"
should be
COM_KUNENA_THOUSAND = "k"
Therefore it adds the number 0 instead of k. Correct is 12.5k

**Comment by ZerooCool** [comment]
Error French translation, ok, everyday !
Thank you for your answer.

12.5 k, then, give 1250 ?
Personally, I prefer this notation, 1250 rather than speaking in kilo visits.

**Comment by rich20** [comment]
>Personally, I prefer this notation, 1250 rather than speaking in kilo visits.

Then add a second 0 in this language string or create a language override.
12.5 k are 12.500 not 1250
This number remains as long the same, until the next hundred are reached.

Either 12.5k > 12.6k > 12.7k or with double 0 it shows 12.500 > 12.600 and so on.

**Comment by ZerooCool** [comment]
I forgot part of my explanation yesterday.
In fact, I am amazed that this post would already have 12,500 views even with the passage of bots.
I guess precisely, I'm only supposed to be at 1250 views, but, I can be wrong, but, that's what it would seem, compared to the other counters on the other forum posts.

At the same time, this message given as an example is the message concerning the T & Cs and Cookies, whose link on the home page refers to this post, so it could be consistent.

Ok, I'll do as you suggest, and add a 0

Kunena's translations are doing well on Transiflex, for an improvement proposal?
I can't find the " 0 "

It's the good way ?
https://www.transifex.com/Kunena-Forum/Kunena/translate/#fr/admin-com_kunena-libraries/9218276

**Comment by rich20** [comment]
If you add two zeros then it is a workaround for you at the moment. But it works not for numbers between 10000 until 10100.
10000 are 10k or with 2 zeros 1000 (wrong)
So you have between 10000 until 10100 incorrect information. Beginning from the number 10100 it is right again.
10100 are 10.1k with 2 zeros 10.100
Therefore I suggest changing it to k. I think it's the only correct solution. But I'm not sure because I don't know the French definitions for numbers.

>I can't find the " 0 "
It's the good way ?
https://www.transifex.com/Kunena-Forum/Kunena/translate/#fr/admin-com_kunena-libraries/9218276

Search by key
key:COM_KUNENA_THOUSAND

**Comment by ZerooCool** [comment]
If I understood correctly, I can do nothing to modify the display and I am obliged to do with this value in kilo, in the case of a normal use of Kunena (Without trying to modify the body of Kunena.)

I went up the correction in the language file fr and I made point a notification towards this conversation.

Thank you for the excellent explanations.

File : /administrator/language/fr-FR/fr-FR.com_kunena.libraries.ini
Line 492 ( Or 464 with my configuration. )
Search COM_KUNENA_THOUSAND for found the good line.

Translation file :
https://www.transifex.com/Kunena-Forum/Kunena/translate/#fr/admin-com_kunena-libraries/9218276

Translation for COM_KUNENA_THOUSAND : https://www.transifex.com/Kunena-Forum/Kunena/translate/#fr/admin-com_kunena-libraries/4582973?q=key%3ACOM_KUNENA_THOUSAND
