### ISSUE TITLE
Got error 'PHP message: PHP Notice:  Undefined variable: config

### ISSUE THREAD

**Issue by ZerooCool** [Kunena/Kunena-Forum#6755]
Debian 10
Apache 2.4
PHP 7.3

Got error 'PHP message: PHP Notice:  Undefined variable: config in /var/www/visionduweb.fr/components/com_kunena/views/topics/view.feed.php on line 162

PHP message: PHP Notice:  Trying to get property 'board_title' of non-object in /var/www/visionduweb.fr/components/com_kunena/views/topics/view.feed.php on line 162'

Line 162 :
$this->document->setGenerator($config->board_title);

**Comment by 810** [comment]
On which url do you got this error?

**Comment by ZerooCool** [comment]
Good question.

I did not try to make the relation between the message of error.log and the link which I must I suppose to find in access.log

I will try to see because it is a message that comes up often, with bad ip.

**Comment by ZerooCool** [comment]
From access.log : 
IP - - [DATE] "GET /forum/topics/posts?format=feed HTTP/1.1" 200 8740 "-" "-"

**Comment by 810** [comment]
Ok, fixed.

**Comment by ZerooCool** [comment]
Thank you.
