### ISSUE TITLE
Hardcoded language in markitup.editor.js

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6756]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/159364-bbcode-translate-issue

We have this file https://github.com/Kunena/Kunena-Forum/blob/K5.1/src/components/com_kunena/template/crypsis/assets/js/markitup.editor.js but Crypsis installs a hardcoded markitup.editor.js in this language, which is chosen for the backend language.

**Additional context**
This error is only with Crypsis, Crypsisb3 installs the correct file.

**Comment by 810** [comment]
Can you try again, i can't reproduce the issue

**Comment by rich20** [comment]
This error still exists. You can reproduce this issue:
1. Choose any backend language
2. Install Kunena
3. Now open the /crypsis/assets/js/markitup.editor.js

You will see, the language in this file is hardcoded
