### ISSUE TITLE
The spoiler cannot be opened

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6766]
**To Reproduce**
1. Create a spoiler text
2. Try to open the spoiler

**Actual result**
You see Warning: Spoiler! with link to expand
![Bildschirmfoto von 2020-03-22 16-27-03](https://user-images.githubusercontent.com/888847/77253827-5c07e100-6c5d-11ea-9518-f9d88ed58ea2.png)
Clicking on expand it only hides this link, or depending on browser it's no reaction

**System information (please complete the following information)**
Joomla version: 3.9.17-dev
Kunena version: 5.1.17-DEV
Php version: 7.3.11
Database version: 5.7.28

**Desktop (please complete the following information):**
 - Browser Firefox, Opera and Chromium (Linux)

**Comment by 810** [comment]
try ctrl + F5, or try clean browser cache

**Comment by rich20** [comment]
This helps only at Chromium. It's the only one browser which have a reaction. The other both browsers (Firefox and Opera) can't open the spoiler.
