### ISSUE TITLE
Empty messages can't be deleted

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6773]
**To Reproduce**
1. Add one or more images in a message and save it 
2. Edit the message and remove the attachment/s and save it
3. Try to delete this empty message now

**Actual result**
You get the message "Cannot save message: Message body is empty!"

**System information (please complete the following information)**
Joomla version: 3.9.16 and 3.9.17-dev
Kunena version: 5.1.17-DEV
Php version: 7.3.11
Database version: 5.7.28

**Comment by xillibit** [comment]
It seems that i had already fixed something similar in K6.0 : https://github.com/Kunena/Kunena-Forum/pull/6713

**Comment by rich20** [comment]
Yes, but this bug is new in K5.1. If you try to submit with empty message body, you get the hint "Fill in this field". But if you edit the message and you remove the attachment there is no hint and you can save the message. During the saves it removes also the attachment codes from the message and the result is an empty message.

**Comment by xillibit** [comment]
>     3\. Try to delete this empty message now

~~I don't see the message saved, i can't save the message because i have the "Cannot save message: Message body is empty!"~~

**Comment by rich20** [comment]
I've tested it again. The error began with builds which have been created after the 12.April

**Comment by xillibit** [comment]
I can't save on edit it ask me to fill the textarea : 
![image](https://user-images.githubusercontent.com/876395/79797042-df991880-8356-11ea-827f-7c6bc331deb2.png)

**Comment by rich20** [comment]
> I can't save on edit it ask me to fill the textarea :

Have you emptied the text field manually? When I empty the text field I get the same info as you. You must not remove the code from the text field if you want to reproduce this issue. Only the image must be removed.
Please try again:
1. Insert an image in a message and save
2. Edit the message and remove the image with the button Remove File
3. Click on Submit

Kunena removes the code during save and you have an empty post.

**Comment by xillibit** [comment]
With this fix, i don't able to reproduce the issue: https://github.com/Kunena/Kunena-Forum/pull/6780

**Comment by rich20** [comment]
I've already tested with this fix. It's still the same. This error exist only, if you the attachments remove with the button Remove file.
