### ISSUE TITLE
No notifications about new replies after  updating from 5.1.15 to 5.1.16

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Forum#6794]
Here are the details:
https://www.kunena.org/forum/k5-1-support/159382-notifications-delay?start=10#213089

I created a topic and replied there - the notification was received immediately.
Then I updated Kunena to 5.1.16 and repeated the action: new topic and reply under another user: no notification was received.

Here is the commit:
https://github.com/Kunena/Kunena-Forum/commit/b617f7fa305327c2a718be8780458261a0fea36b

I suppose this code should be investigated.
Thank you.

**System information (please complete the following information)**

Joomla version: 3.9.18
Kunena version: 5.1.16
Php version: 7.2

**Comment by 810** [comment]
I have reverted the feature commit, should work on the nightly build.
