### ISSUE TITLE
Some options don't have tooltip

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6827]
**Expected behavior**
Tooltip should be available when possible

**Actual result**
The following options are not showing the tooltip:
•Menu Item Type->my topics->details-> Header Text (By Plugin only)
•Menu Item Type->my topics->main settings-> Page Header
•Menu Item Type->recent posts->main settings-> Page Header
•Search box located above topics
•"More" button located under profile icon (Beside topics)

**System information (please complete the following information)**
Joomla version: 3.9.19
Kunena version: 5.1.17
PHP version: 7.3.18
Database version: MySQL 5.7.30

**Comment by xillibit** [comment]
It's not totally finished, it's missing the following : 
•Search box located above topics
•"More" button located under profile icon (Beside topics)

**Comment by xillibit** [comment]
@jelle : where-is the place where the icons are generated in svg ?

**Comment by 810** [comment]
https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/libraries/kunena/Icons/svgicons.php
