### ISSUE TITLE
Font size selection in the Blue Eagle-5-v1-5-3 template editor does not work

### ISSUE THREAD

**Issue by Leen29** [Kunena/Kunena-Forum#6832]
**Describe the bug**
Since the new version we can not make words bigger anymore like before, the size!
no more text is shown

![blank text](https://user-images.githubusercontent.com/17086048/84563233-500e5580-ad5a-11ea-85f8-69ad197e34f0.jpg)
![with text](https://user-images.githubusercontent.com/17086048/84563240-5a305400-ad5a-11ea-8b49-b2924aaba519.jpg)

And I find out that problem is in Update from Kunena _v5.1.16_2020-03-17 to _Kunena_v5.1.17_2020-06-09 itself.
I have / had just tested this problem myself by bringing kunena back to Kunena _v5.1.16_2020-03-17
and then the text is visible again

**Comment by 810** [comment]
try 5.1.17 again,,also the language package. Then go to backend- kunena - plugins - rebuild.

These will rebuild the language strings.

**Comment by Leen29** [comment]
I have tried several times but it is not working.
Also cleaning cache etc gives no result afterwards
![notext](https://user-images.githubusercontent.com/17086048/84565608-8f44a280-ad6a-11ea-9e0f-299f204d69aa.JPG)

**Comment by 810** [comment]
ok, then try to copy the file from crypsis to blue eagle: markitup.editor.js

**Comment by Leen29** [comment]
I have tried several times but it is also not working.

**Comment by 810** [comment]
ok, i will close this issue, and copy the issue, to our private template repository, i will check it, and will fix it if i can reproduce the issue. If i need extra info i will reply on this issue.

**Comment by 810** [comment]
its a know issue, will be fixed on next blue eagle update

**Comment by Leen29** [comment]
Okay thank you then we wait until the next Blue eagle update

**Comment by Leen29** [comment]
Today this temporary solution came on kunena forum.

[https://www.kunena.org/forum/blue-eagle-5/159849-font-size-select-drop-has-no-text-since-5-1#213600
](url)
