### ISSUE TITLE
[K6.0] Alpha not working

### ISSUE THREAD

**Issue by C-Lodder** [Kunena/Kunena-Forum#6853]
I installed Kunena 6.0 alpha (nightly) and am now trying to add a menu item. As per normal, Kunena automatically adds a new menu item itself but it's disabled.

When going to the menu manager and looking at the meun items created by Kunena, it saying:

> Component `com_kunena` does not exist

**Screenshots**
![screeny2](https://user-images.githubusercontent.com/2019801/86476618-cb9e6980-bd3e-11ea-8595-5f9210957224.png)

**System information (please complete the following information)**

Joomla version: 4.0 Beta 2
Kunena version: 6.0-alpha
PHP version: 7.4

**Comment by 810** [comment]
see: https://github.com/joomla/joomla-cms/issues/29552

**Comment by C-Lodder** [comment]
@xillibit Is this now fixed?

**Comment by xillibit** [comment]
Yes, we have made a workaround check with last change

**Comment by C-Lodder** [comment]
Installation works now, however when I go to create a new menu item, I can't set it to the Kunena Forum.
It doesn't exist.

**Comment by xillibit** [comment]
I re-open
