### ISSUE TITLE
Add option to define sender name for email notifications

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6854]
**Expected behavior**
Add option in backend->configuration to define sender name for email notifications

**Actual result**
By default the sitename is used as sender name

**System information (please complete the following information)**
Joomla version: 3.9.19
Kunena version: 5.1.18
PHP version: 7.3.19
Database version: MySQL 5.7.30

**Comment by xillibit** [comment]
The sender in mail is in two parts : the mail and the name

So if you change the name you need to change the mail in same time ?

**Comment by sshcli** [comment]
> So if you change the name you need to change the mail in same time ?

No

You can already define the email visible to users in:
Backend->Configuration->General->Basic Settings->Forum E-mail Address
Backend->Configuration->Users->Subscriptions->Visible E-mail Recipient

The new requested field, is only to define the name.
Because right now is something like this:
`$this->config->board_title`

and it should be something like:
`$this->config->sender_name`
