### ISSUE TITLE
PHP Notice: Undefined property via __get(): qqsocial

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#6878]
**How to reproduce the issue**
I saw the error when restored a backup copy of my website in another hosting

**Expected behavior**
No PHP warning

**Actual result**
[24-Jul-2020 20:10:00 Europe/London] PHP Notice: Undefined property via __get(): qqsocial in /public_html/components/com_kunena/template/crypsis/layouts/user/edit/profile/default.php on line 133 in /public_html/libraries/kunena/user/user.php on line 2187

**System information (please complete the following information)**
Joomla version: 3.9.20
Kunena version: 5.1.18
PHP version: 7.3.20
Database version: 5.5.5-10.3.23-MariaDB-cll-lve

**Comments**
This problem is not affecting me anymore, I have reported this just to investigate further, in case someone else have it

**Comment by xillibit** [comment]
Do-you have still this backup ? Do-you have checked if in kunena user table the column qqsocial was right here ?

**Comment by sshcli** [comment]
Sorry, I can't reproduce it anymore

**Comment by sshcli** [comment]
Please reopen.
The error is back again.

**This time, I'm using:**
Joomla version: 3.9.20
Kunena version: 5.1.19
PHP version: 7.4.9
Database version: MySQL 5.7.31

**Comment by sshcli** [comment]
The error occurs when edit profile and save the new information

**Comment by sshcli** [comment]
It has been solved in the past:
See issue https://github.com/Kunena/Kunena-Forum/issues/5807 and commit https://github.com/Kunena/Kunena-Forum/commit/80a8d0d0e0688a3f93bf47007e33fe5898829d8f
