### ISSUE TITLE
Allow Kunena's translation of menus via language constants

### ISSUE THREAD

**Issue by 4digitalworld** [Kunena/Kunena-Forum#6889]
**Is your feature request related to a problem? Please describe.**
Currently, to translate the menu items of the Kunena forum (if the site has 2 or more languages), you need to create new menu items.

**Describe the solution you'd like**
Allow Kunena's translation of menus via `Language Constants`. Thus, it will not be necessary to create new menu items in another language (if the site has 2 or more languages).

**Describe alternatives you've considered**
I saw that this method for translating the menu is [used](https://documentation.jomsocial.com/wiki/Translate_Toolbar) in @JomSocial and I really liked this way, it's really amazing!

**Additional context**
I think it would be very great if we could do the same way of translating menu items in the Kunena forum!

**Comment by 810** [comment]
duplicated issue: https://github.com/Kunena/Kunena-Forum/issues/628

closing this one.
