### ISSUE TITLE
font-awesome pro (5.x) are not displayed with kunena 5.1.19

### ISSUE THREAD

**Issue by carabao72** [Kunena/Kunena-Forum#7442]
****Describe the bug**
A clear and concise description of what the bug is.**

Hello,

I just updated to 5.1.19 and coincidence or not, my font-awesomne PRO icons no longer appear, they are replaced by a circle with one!

At first glance, the font classes have been changed from version 5.1.18. They start with svg...
All my CSS changes in custom.css are broken.

**To Reproduce**

upgrade 5.1.18 --> 5.1.19

pro icons are broken (5.x). My font-awesome kit pro  is called by a script placed in head

**Screenshots**

![kunena-fontawesome](https://user-images.githubusercontent.com/8301011/90338868-f4c44200-dfec-11ea-86a7-9afdefeb12be.png)

**System information (please complete the following information)**

Joomla version: 3.9.20
Kunena version: 5.1.19
web: https://www.caravane-camping.be/forum/index

**Comment by rich20** [comment]
@carabao72 Configuration report removed.
Please do not add a configuration report on Git. Otherwise all users and guests can read the confidential information in it.

**Comment by rich20** [comment]
You have chosen in your Crypsis template setting "Load External CDN Fontawesome", however external Fontawesome contains not all symbols. Please change this setting.

**Comment by carabao72** [comment]
Indeed, I forgot to set this parameter to NO after my test. but this does not change anything the icons still do not display despite this parameter is NO

**Comment by 810** [comment]
try to change the class names on the category:

like:

 far fa-backpack (please add space before far)

**Comment by rich20** [comment]
I've noticed, all symbols, which are included in a free version, are displayed correctly on his page. The problem exists only with the additional symbols, which are contained in the Pro version.

**Comment by carabao72** [comment]
I added a space in front of  "far fa-backpack", nothing has changed.    category "le camping"

Indeed, it is the PRO icons that do not appear.

**Comment by xillibit** [comment]
Try to undo this change done in K5.1.19 : https://github.com/Kunena/Kunena-Forum/commit/242d744b711e3f217b68f26d98e291965ef51eea#diff-5e12dbd1943a1f80098b86365805a94e

**Comment by carabao72** [comment]
Thank You,

If I understand correctly, if I download these different files 5.1.18 on my kunena 5.1.19 installation via FTP, the problem should be solved. I can recover the files in the zip of the 5.1.18

In case of problem, return to version 5.1.19 of these files by downloading version 5.1.19 of these files.

**Comment by xillibit** [comment]
In the link above you need to apply the change manually, else you can download the file from 5.1.18 https://github.com/Kunena/Kunena-Forum/blob/5.1.18/src/components/com_kunena/template/crypsis/template.php and replace the one on your Joomla! install

**Comment by carabao72** [comment]
Fixed issue, font-awesome-pro icons are displayed  by replacing template.php
--> https://github.com/Kunena/Kunena-Forum/blob/5.1.18/src/components/com_kunena/template/crypsis/template.php

And my CSS changes are operational again.

What will happen with the next kunena updates?  Will the problem return?

Thank You 810, Xillibit , rich20

**Comment by xillibit** [comment]
Thanks for the report

I will made a fix for Kunena 5.2, now we have stopped the developpement of Kunena 5.1

**Comment by carabao72** [comment]
Thank You and good luck with the 5.2
