### ISSUE TITLE
The counter in deleted posts is empty

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7447]
**Steps to reproduce the issue**
1.Backend->Create menu item type Recent Posts->Deleted Posts
2.Frontend->Delete any topic
3.Frontend->Go to menu

**Expected behavior**
The counter in deleted posts should work

**Actual result**
The counter in deleted posts is empty
<img width="308" alt="deleted" src="https://user-images.githubusercontent.com/12942731/90546881-b0ee4b80-e158-11ea-8dac-0e69d7e5f51c.PNG">

**System information (please complete the following information)**
Joomla version: 3.9.20
Kunena version: 5.1.19
PHP version: 7.4.9
Database version: MySQL 5.7.31

**Comment by sshcli** [comment]
The error occurs when edit profile and save the new information

**Comment by sshcli** [comment]
@rich20 can you confirm this one?

**Comment by xillibit** [comment]
I have this error when going on the deleted menu : 

> Rendering Error in layout Message/List: Property "messagemore" is not defined in C:\Users\florian\git\Kunena-forum\src\components\com_kunena\template\crypsis\layouts\message\list\default.php on line 31
Layout was rendered in C:\Users\florian\git\Kunena-forum\src\components\com_kunena\template\crypsis\pages\topics\posts\default.php on line 21
