### ISSUE TITLE
Preview does not work when Direct Component Access = No

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7448]
**Steps to reproduce the issue**
1. Backend->Configuration->General->Direct Component Access = No
2. Start creating a new topic and click the preview tab in editor

**Expected behavior**
No error
Preview should work

**Actual result**
The preview message does not work when Direct Component Access = No
You get this error in console:
https://example.com/index.php?option=com_kunena&view=topic&layout=edit&format=raw 404  /media/jui/js/jquery.min.js?ab496920302908f5b77ef31150161780

**System information (please complete the following information)**
Joomla version: 3.9.20
Kunena version: 5.1.19
PHP version: 7.4.9
Database version: MySQL 5.7.31

**Comment by rich20** [comment]
Confirmed
/index.php?option=com_kunena&view=topic&layout=edit&format=raw 404
