### ISSUE TITLE
Change the message received when post is approved (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7470]
Is it possible to replace the forum title with an %s in the translation?

Example we have this code: COM_KUNENA_POST_EMAIL_NOTIFICATION_APPROVED_MESSAGE
English translation is: Your message has been approved by a moderator on the
The result in the mail is now this text plus of the Forum Title such as
Your message has been approved by a moderator on the Kunena Test Forum

But in other languages must be the forum title within the phrase.
Example in German language:
Dein Beitrag im **Kunena Test Forum** wurde von einem Moderator freigegeben.
or
Dein Beitrag wurde von einem Moderator im **Kunena Test Forum** freigegeben.

**Comment by rich20** [comment]
Possible (or maybe better?) would be to send it without forum title. You see it at the sender address wherefrom comes the mail.
Example:
Your message has been approved by a moderator

**Comment by sshcli** [comment]
> Your message has been approved by a moderator

I vote for this one. 👍

**Comment by sshcli** [comment]
Also, as we are talking about part 2...
 it is necessary to also add the changes here https://github.com/Kunena/Kunena-Forum/commit/0e2ddacdbafc05c8a7d8b45272ef3a70c9e404d7 to B3 and B4
