### ISSUE TITLE
Wysiwyg Editor | The end bracket of the BBCode symbol is always on the next row.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7474]
https://www.kunena.org/forum/blue-eagle-5/159963-toolbar-spacing

The end bracket of the BBCode symbol is always on the next row. Also if you use with Protostar the fluid layout where all symbols are in the same line, this bracket is in the next row.
![path817](https://user-images.githubusercontent.com/888847/91453586-3a4ffd00-e880-11ea-8ed6-ca3d035774c9.png)

**Comment by xillibit** [comment]
Replaced by CKEditor
