### ISSUE TITLE
Implement CKeditor into Kunena

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#7502]
Implement CKeditor 4 in replacement of two existings editors in Kunena, this should fixes the followings : #1901, #5179, #5187, #7474

- [x] Remove existings editors
- [x] Add specific buttons : confidential, hide, spoiler, code,  maps, twitter, instagram, video, soundcloud, ebay 
- [x] Missing polls 
- [x] Check video modal to have the same settings that the actual bbcode editor
- [x] Set deprecated preview code
- [ ] Get the language used by the user defined in Joomla! profile and load the right language file
- [ ] Check language strings

**Comment by rich20** [comment]
- [x] Remove existings editors
- [x] Add specific buttons : confidential, hide, spoiler, code, polls, maps, twitter, instagram, video, soundcloud, ebay
- [ ] Check video modal to have the same settings
- [x] Set deprecated preview code
- [ ] Check language strings
- [ ] Only emoticons from the first modal row are usable

**Comment by 810** [comment]
Emoticons is missing subdomain support.

**Comment by xillibit** [comment]
> Emoticons is missing subdomain support.

It should work if you site is called test.example.com

**Comment by rich20** [comment]
I've installed my test pages in subfolders like 
websiteaddress.at/**subfolder**
but the editor want load the smilies from
websiteaddress.at/media/kunena/emoticons/ instead of
websiteaddress.at/**subfolder**/media/kunena/emoticons/ 
so I must change the address in the ckeditor_config.js to make it work
from
/media/kunena/emoticons/
to
../media/kunena/emoticons/

**Comment by rich20** [comment]
- [x] Remove existings editors
- [x] Add specific buttons : confidential, hide, spoiler, code, polls, maps, twitter, instagram, video, soundcloud, ebay
- [ ] Check video modal to have the same settings
- [x] Set deprecated preview code
- [ ] Check language strings
- [ ] Emoticons is missing subdomain support
- [ ] Poll button is not available

**Unneeded Buttons**

- [x] Create Div Container
- [x] Anchor
- [x] Insert Page Break for Printing
- [x] Show Blocks
- [x] Block Quote and Quote (do we need both?)

**Is it possible to better sorting?**
Example: Social Share Buttons (see image)
![path821](https://user-images.githubusercontent.com/888847/94024334-93477e00-fdb7-11ea-9d23-8a85ea44b631.png)

**Comment by rich20** [comment]
**Summary of remaining issues**

- [ ] Check video modal to have the same settings
- [ ] Check language strings
- [ ] Emoticons is missing subdomain support
- [ ] Poll button is not available

**Is it possible to better sorting?**
Maybe the button for image link would be better on the list for maps and videos

**Some buttons does not work correctly**

- [ ] Map - it adds no type and zoom level
- [ ] Videos by provider - it does not add the provider name (you must enter it manually)
- [ ] Videos by provider - the option Size of the video adds the entered size value to type=
- [ ] Videos by provider - without entered size values it shows only the code in the message
- [ ] Increase does not work - (I think the buttons decrease and increase are only for forms)
- [ ] Table - after submit the table is gone and all characters are in the same line
- [ ] Insert Horizontal Line - there is no line after submit
- [ ] Styles, Format, Font and Size - are not accepted
- [ ] Button Background Color - no background color behind the characters after submit 
- [ ] All additional added Kunena buttons like Quote, Spoiler, Social share, Code and so on... removes the marked text. So you must enter the code first, then place the cursor and then you can enter the text.

**Comment by rich20** [comment]
If you click on Reply or New Topic:
Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 131072 bytes) in components/com_kunena/template/crypsis/layouts/topic/edit/default.php on line 400

**Comment by rich20** [comment]
Open the console and then a topic. You get this error.

edit.js:281 Uncaught ReferenceError: CKEDITOR is not defined
    at HTMLDocument.<anonymous> (edit.js:281)

**Comment by rich20** [comment]
> edit.js:281 Uncaught ReferenceError: CKEDITOR is not defined
at HTMLDocument. (edit.js:281)

I get still this error

**Comment by xillibit** [comment]
Try to clean cache

**Comment by rich20** [comment]
I've emptied all caches before test inclusive the cache in media/kunena

**Comment by xillibit** [comment]
I had read too quickly, i thought the issue was on new topic

**Comment by rich20** [comment]
<strike>Sorry, it was the browser. I've emptied the last 24h, now works</strike>

**Comment by rich20** [comment]
Sorry, it was my second mistake. After delete the last 24h of the cache, I was logged out. This error still exists if you are logged in.

**Comment by rich20** [comment]
- [x] Success

**Comment by rich20** [comment]
Set the base path when subfolder to load smileys https://github.com/Kunena/Kunena-Forum/pull/7579
It want still to load the smileys from root/media/kunena/emoticons if the installation is in a subfolder

**Comment by rich20** [comment]
Kunena know the right path. After submit, the smileys are in the message.
Only the editor recognizes not the correct path and therefore you have no preview (see image).
![Bildschirmfoto von 2020-10-11 02-38-32](https://user-images.githubusercontent.com/888847/95668184-ae184180-0b70-11eb-8be5-81324206f8f0.png)

**Comment by xillibit** [comment]
Open others issues if needed
