### ISSUE TITLE
Avatar upload is not possible anymore when direct component is not allowed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7520]
**To Reproduce**
1. Choose in the configuration -> tab General -> Direct Component Access = No
2. Try upload an avatar

**Actual result**
The avatar will not uploaded
The console shows /index.php?option=com_kunena&view=user&task=upload&format=json 404 

**System information (please complete the following information)**
Joomla version: 3.9.22-dev and 3.10.0-alpha1
Kunena version: 5.1.19 and  5.2-ALPHA1-DEV 
Kunena template name and version: Crypsis, Crypsisb3 and Blue Eagle
Php version: 7.3.17 and 7.4.5
Database version: 5.7.28

**Additional context**
Maybe it has something to do with this merge https://github.com/Kunena/Kunena-Forum/pull/6893

**Comment by sshcli** [comment]
This issue is something like the Part 2 of this PR: https://github.com/Kunena/Kunena-Forum/pull/7454
