### ISSUE TITLE
Annymous posts | It shows the real name of the topic author, when setting Display User Name = No

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7537]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/160062-error-with-anonymous-posts-with-setting-show-username-no
If is No in the "Show user name" settings i.e. output the real name, it shows the name of the user when he enter an anonymous post.

**To Reproduce**
1. Configuration -> tab Users -> Display User Name = No
2. Category setting - Allow anonymous posts
3. Create a new topic as anonymous user

**Expected behavior**
The topic author should be displayed as Anonymus

**Actual result**
It shows the real name

**Additional context**
<strike>This error occurs only on the first message if you create a new topic. For answers it works correctly.</strike>

**Comment by xillibit** [comment]
> If is No in the "Show user name" settings i.e. output the real name, it shows the name of the user when he enter an anonymous post.

The setting **Display User Name** display usernames to be displayed instead of real names, but it's not intented to be displayed as anonymous

**Comment by rich20** [comment]
https://www.kunena.org/forum/general-questions-and-how-tos/160062-error-with-anonymous-posts-with-setting-show-username-no#214241
I've it only tested and confirmed. But you're right I can also not see a logic in this topic. 
On the one hand the user choose in the Kunena configuration that the real name is displayed, and on the other hand he made a hack that all users get the ID 0 for an Anonymous user.
So I think, this can be closed.
