### ISSUE TITLE
New Topic | The checkbox should be already marked when set is Post as Anonymous user

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7538]
**To Reproduce**
1. Category setting - Allow anonymous posts
2. Second Setting - By default post replies as Anonymous user
3. Create a new topic

**Expected behavior**
The checkbox should be marked

**Actual result**
The checkbox is empty

**Additional context**
This error occurs only on the first message if you create a new topic. For answers the checkbox is already marked.

**Screenshots**
![Bildschirmfoto von 2020-09-24 14-26-58](https://user-images.githubusercontent.com/888847/94152131-855b3100-fe7b-11ea-90df-2ae14523d907.png)

**Comment by xillibit** [comment]
Not able to reproduce this issue : 

![image](https://user-images.githubusercontent.com/876395/95016093-1c30a600-0651-11eb-9200-c5c32e68a98b.png)

**Comment by rich20** [comment]
Hmm... I see now, that's only if you use the menu item New Topic and this category is chosen per default (it's always the first category). Then also it lacks the alert info.
![path817](https://user-images.githubusercontent.com/888847/95016865-17222580-0656-11eb-9fa2-73b7cc66d2ad.png)
