### ISSUE TITLE
Current IP Lookup Tool provider does not support IPv6

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7553]
**Expected behavior**
We should another provider able to handle IPv6
For example:
https://www.ultratools.com/tools/ipWhoisLookupResult 

**Actual result**
Current provider does not resolve ipv6 like this: 2800:370:11d:24e0:d9a8:5789:2e7f:f1d7 
https://www.geodatatool.com/en/?ip=2800:370:11d:24e0:d9a8:5789:2e7f:f1d7   

**System information (please complete the following information)**
Joomla version: 3.9.21
Kunena version: 5.1.19
PHP version: 7.4.10
Database version: MySQL 5.7.31

**Comment by xillibit** [comment]
I prefer this one : https://dnslytics.com/ipv6/2800:370:11d:24e0:d9a8:5789:2e7f:f1d7
