### ISSUE TITLE
Subscription New Topics - notification is sent for each new message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7573]
**Describe the bug**
https://www.kunena.org/forum/k5-1-support/160022-even-if-no-subscription-on-a-topic-a-notification-is-sent-for-each-new-message
I've tested and can confirm this error. When a user subscribes a category, he gets a mail on each message, also when the setting is "send mails only for new topics".

**To Reproduce**
Configuration:
Category Subscriptions = Email New Topics
Topic Subscriptions = First Update

**Expected behavior**
A mail when a new topic is created

**Actual result**
You get a mail on each message

Joomla version: 3.9.20 and 3.9.23-dev
Kunena version: 5.1.19 and 5.2.0-dev
Kunena template name and version: Crypsis
Php version: 7.3.22
Database version: 5.7.28

**Comment by sshcli** [comment]
I have received several server warning caused by this bug.
it now makes sense to me

**Comment by gerard1090** [comment]
Hello,
this is a real issue that impacts our web site. Too many mails are issued by Kunena, as there is a real bug in Kunena.
How can we see this issue open again ? and when can we expect a fix date ?
Many thanks

**Comment by jmmatrat** [comment]
Hello,
I confirm this is a big issue for us, as the experience is not was it was before, from my understanding it looks like a regression that took place in June 20
Regards

**Comment by xillibit** [comment]
> Hello,
> I confirm this is a big issue for us, as the experience is not was it was before, from my understanding it looks like a regression that took place in June 20
> Regards

In june 2020 we had released  Kunena 5.1.18, i need to check a change related to that
