### ISSUE TITLE
PHP Notice:  Undefined property via __get(): qqsocial

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7574]
**Steps to reproduce the issue**
1. Edit your profile and clic the save button
2. Go to error_log file

**Expected behavior**
No PHP Warnings or Notice

**Actual result**
PHP Notice:  Undefined property via __get(): qqsocial in /home/username/public_html/components/com_kunena/template/crypsis/layouts/user/edit/profile/default.php on line 133 in /home/username/public_html/libraries/kunena/user/user.php on line 2187

**System information (please complete the following information)**
Joomla version: 3.9.22
Kunena version: 5.1.19
PHP version: 7.4.11
Database version: MySQL 5.7.31

**Additional comments**
This error is similar to:
https://github.com/Kunena/Kunena-Forum/issues/6878
https://github.com/Kunena/Kunena-Forum/issues/5808
https://github.com/Kunena/Kunena-Forum/issues/5807

**Comment by xillibit** [comment]
Can-you make a screenshot to see exactly where is the error message ?

**Comment by sshcli** [comment]
> Can-you make a screenshot to see exactly where is the error message ?

The error is not visible in the frontend or backend
It is only visible in the error_log file located in the root directory of the server.

**Comment by sshcli** [comment]
I have manually applied this change in 5.1.9, and still getting the error?
This fix only works in 5.2?

The error occurs only by visiting the edit profile page, don't need to click save button

**Comment by xillibit** [comment]
I will try to reproduce it

**Comment by xillibit** [comment]
In table #__kunena_users do-you right the field qqsocial ?

**Comment by rich20** [comment]
When I rename back this column to the old name "qq" I get exactly the same error.

**Comment by sshcli** [comment]
> In table #__kunena_users do-you right the field qqsocial ?

That was the problem, for some reason my database was not updated with new qqsocial. I have change the database to qqsocial and it is working now without errors. Thanks

If you don't need to do additional changes, please feel free to close this issue as solved.
Thanks again
