### ISSUE TITLE
Unhandled exception - Exception

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [Kunena/Kunena-Forum#7584]
**Describe the bug**
Been getting emails advising of an unhandled exception

**To Reproduce**
Not sure if these happen when I log to the site, or can be triggered by others

**System information (please complete the following information)**
A PHP Exception occurred on your site. Here you can find the stack trace:

Exception Type: Exception
File: /www/libraries/src/MVC/View/HtmlView.php
Line: 712
Message: Presentación no encontrada.

#0 /www/libraries/src/MVC/View/HtmlView.php(230): Joomla\CMS\MVC\View\HtmlView->loadTemplate(NULL)
#1 /www/libraries/kunena/view.php(209): Joomla\CMS\MVC\View\HtmlView->display(NULL)
#2 /www/libraries/kunena/view.php(137): KunenaView->displayLayout()
#3 /www/libraries/kunena/controller.php(441): KunenaView->displayAll()
#4 /www/libraries/kunena/controller.php(324): KunenaController->display()
#5 /www/libraries/kunena/controller.php(215): KunenaController->executeTask('display')
#6 /www/components/com_kunena/kunena.php(114): KunenaController->execute('display')
#7 /www/libraries/src/Component/ComponentHelper.php(402): require_once('/../wwww/...')
#8 /www/libraries/src/Component/ComponentHelper.php(377): Joomla\CMS\Component\ComponentHelper::executeComponent('/../www/...')
#9 /www/libraries/src/Application/SiteApplication.php(194): Joomla\CMS\Component\ComponentHelper::renderComponent('com_kunena')
#10 /www/libraries/src/Application/SiteApplication.php(233): Joomla\CMS\Application\SiteApplication->dispatch()
#11 /www/libraries/src/Application/CMSApplication.php(196): Joomla\CMS\Application\SiteApplication->doExecute()
#12 /www/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#13 {main}
Request information

GET variables

Array
(
    [option] => com_kunena
    [view] => topic
    [Itemid] => 139
)
POST variables

Array
(
)
COOKIE variables

Array
(
    [xxxx] => xxxx
    [joomla_user_state] => logged_in
    [xxxx] => xxxx
)
REQUEST variables

Array
(
    [option] => com_kunena
    [view] => topic
    [Itemid] => 139
    [layout] => 
    [limitstart] => 
)
SERVER variables

Array
(
    [PATH] => /usr/local/bin:/usr/bin:/bin
    [TZ] => America/New_York
    [REDIRECT_HANDLER] => application/x-httpd-ea-php73
    [REDIRECT_STATUS] => 200
    [UNIQUE_ID] => xxxx
    [SCRIPT_URL] => /forum
    [SCRIPT_URI] => www/forum
    [HTTPS] => on
    [SSL_TLS_SNI] => www
    [HTTP_HOST] => www
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
    [HTTP_ACCEPT] => */*
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_REFERER] => www/forum
    [HTTP_DNT] => 1
    [HTTP_CONNECTION] => keep-alive
    [HTTP_COOKIE] => xxxxx; joomla_user_state=logged_in; xxxxx
    [HTTP_SEC_GPC] => 1
    [HTTP_X_HTTPS] => 1
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache
    [SERVER_NAME] => www
    [SERVER_ADDR] => ip
    [SERVER_PORT] => 443
    [REMOTE_ADDR] => ip
    [DOCUMENT_ROOT] => /www
    [REQUEST_SCHEME] => https
    [CONTEXT_PREFIX] => /cgi-sys
    [CONTEXT_DOCUMENT_ROOT] => /usr/local/cpanel/cgi-sys/
    [SERVER_ADMIN] => webmaster@www
    [SCRIPT_FILENAME] => /www/index.php
    [REMOTE_PORT] => 57582
    [REDIRECT_URL] => /index.php
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => option=com_kunena&layout=&view=topic&Itemid=139
    [REQUEST_URI] => /forum
    [SCRIPT_NAME] => /index.php
    [ORIG_SCRIPT_FILENAME] => /usr/local/cpanel/cgi-sys/ea-php73
    [ORIG_PATH_INFO] => /index.php
    [ORIG_PATH_TRANSLATED] => /www/index.php
    [ORIG_SCRIPT_NAME] => /cgi-sys/ea-php73
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1602474027.4857
    [REQUEST_TIME] => 1602474027
    [argv] => Array
        (
        )

    [argc] => 0
)

Joomla version: Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
Kunena version: Version:
    5.1.19
Codename:
    Tethys
Kunena template name and version: 

  | Crypsis |   | Kunena Team | 5.1.19
-- | -- | -- | -- | --

Php version:7.3.21 
Database version: 5.7.31-cll-lve

**Comment by xillibit** [comment]
So by reading the stack trace it seems the issue occurs when someone select "Display All" in drop-down list in recent discussions page. Maybe there are too much things to load and it fails...

Which kunena template are-you using ?

**Comment by basking-in-the-sun2000** [comment]
Thanks for taking a look

the template is 


Crypsis Kunena Team  5.1.19

**Comment by basking-in-the-sun2000** [comment]
any updates?

**Comment by xillibit** [comment]
I try to call this kind of url, i have the same error : index.php?option=com_kunena&layout=&view=topic&Itemid=130 but i don't know where you have get this wrong url

**Comment by basking-in-the-sun2000** [comment]
Been getting a ton of these lately

Not sure if there is a misconfiguration on the site, but would like these fixed

<details>
<summary>PHP Exception text</summary>
A PHP Exception occurred on your site. Here you can find the stack trace:

Exception Type: Error
File: /www_folder/plugins/system/GoogleAnalytics/GoogleAnalytics.php
Line: 64
Message: Call to a member function getType() on null

#0 /www_folder/libraries/joomla/event/event.php(70): plgSystemGoogleAnalytics->onAfterRender()
#1 /www_folder/libraries/joomla/event/dispatcher.php(160): JEvent->update(Array)
#2 /www_folder/libraries/src/Application/BaseApplication.php(108): JEventDispatcher->trigger('onafterrender', Array)
#3 /www_folder/libraries/src/Application/CMSApplication.php(1096): Joomla\CMS\Application\BaseApplication->triggerEvent('onAfterRender')
#4 /www_folder/libraries/src/Application/SiteApplication.php(778): Joomla\CMS\Application\CMSApplication->render()
#5 /www_folder/libraries/src/Application/CMSApplication.php(209): Joomla\CMS\Application\SiteApplication->render()
#6 /www_folder/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#7 {main}
Request information

GET variables

Array
(
    [option] => com_kunena
    [catid] => 8
    [format] => feed
    [type] => rss
    [view] => category
    [Itemid] => 139
)
POST variables

Array
(
)
COOKIE variables

Array
(
    [daf9f7f37f83eb0b81f1ad3633bdf6c5] => 547c7d1336ea2bfca9fc40af9146a94f
)
REQUEST variables

Array
(
    [daf9f7f37f83eb0b81f1ad3633bdf6c5] => 547c7d1336ea2bfca9fc40af9146a94f
    [option] => com_kunena
    [catid] => 8
    [format] => feed
    [type] => rss
    [view] => category
    [Itemid] => 139
    [limitstart] => 
    [message] => 
)
SERVER variables

Array
(
    [PATH] => /usr/local/bin:/usr/bin:/bin
    [TZ] => America/New_York
    [REDIRECT_HANDLER] => application/x-httpd-alt-php74
    [REDIRECT_STATUS] => 200
    [UNIQUE_ID] => YFVmSrbrm3TGiQMZ09@MgAAAAFA
    [SCRIPT_URL] => /forum/coronavirus/cafe/rss
    [SCRIPT_URI] => https://www.website.com/forum/coronavirus/cafe/rss
    [HTTPS] => on
    [SSL_TLS_SNI] => www.website.com
    [HTTP_IF_MODIFIED_SINCE] => 
    [HTTP_IF_NONE_MATCH] => 
    [HTTP_USER_AGENT] => AwarioRssBot/1.0 (+https://awario.com/bots.html; bots@awario.com)
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [HTTP_HOST] => www.website.com
    [HTTP_CONNECTION] => Keep-Alive
    [HTTP_COOKIE] => daf9f7f37f83eb0b81f1ad3633bdf6c5=547c7d1336ea2bfca9fc40af9146a94f
    [HTTP_ACCEPT_ENCODING] => gzip,deflate
    [HTTP_X_HTTPS] => 1
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache
    [SERVER_NAME] => www.website.com
    [SERVER_ADDR] => server_ip
    [SERVER_PORT] => 443
    [REMOTE_ADDR] => 88.99.62.159
    [DOCUMENT_ROOT] => /www_folder
    [REQUEST_SCHEME] => https
    [CONTEXT_PREFIX] => /cgi-sys
    [CONTEXT_DOCUMENT_ROOT] => /usr/local/cpanel/cgi-sys/
    [SERVER_ADMIN] => webmaster@website.com
    [SCRIPT_FILENAME] => /www_folder/index.php
    [REMOTE_PORT] => 26652
    [REDIRECT_URL] => /index.php
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => option=com_kunena&catid=8&format=feed&type=rss&view=category&Itemid=139
    [REQUEST_URI] => /forum/coronavirus/cafe/rss
    [SCRIPT_NAME] => /index.php
    [ORIG_SCRIPT_FILENAME] => /usr/local/cpanel/cgi-sys/alt-php74
    [ORIG_PATH_INFO] => /index.php
    [ORIG_PATH_TRANSLATED] => /www_folder/index.php
    [ORIG_SCRIPT_NAME] => /cgi-sys/alt-php74
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1616209482.7491
    [REQUEST_TIME] => 1616209482
)
</details>

**Comment by 810** [comment]
that plugin is not ours: plugins/system/GoogleAnalytics

This is the issue, please update that plugin, or contact their developers.
