### ISSUE TITLE
[CKeditor] No poll symbol available if you switch the category in the editor dropdown

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7586]
1. Click on New Topic
2. Switch in the dropdown to the Suggestion Box

Result:
No poll symbol

**Comment by rich20** [comment]
- [ ] If you go via Index -> Category -> New Topic, you have in all categories the poll symbol
- [ ] If you click on the menu item New Topic and switch from Welcome Mat to Suggestion Box, the symbol is gone (This occurs only if the category Welcome Mat is enabled. If you disable this category, remains the symbol also for all categories if you switch)

**Comment by rich20** [comment]
> if you click on the menu item New Topic and switch from Welcome Mat to Suggestion Box, the symbol is gone

<strike>I have noticed many times that errors occur with the Category Welcome Mat. Maybe you should ignore this one issue and only to make a fix, so the symbol is available only when poll is allowed.</strike>

**Comment by rich20** [comment]
- [x] If you go via Index -> Category -> New Topic, you have in all categories the poll symbol
- [ ] If you click on the menu item New Topic and switch from Welcome Mat to Suggestion Box, the symbol is gone (This occurs only if the category Welcome Mat is enabled. If you disable this category, remains the symbol also for all categories if you switch)
- [ ] Setting : Force users to pickup a category -  No poll symbol available

**Comment by xillibit** [comment]
I have moved the file edit.js under core/kunena/js but it is not loaded now

**Comment by rich20** [comment]
- [x] If you go via Index -> Category -> New Topic, you have in all categories the poll symbol
- [ ] Setting : Force users to pickup a category -  No poll symbol available

**Comment by rich20** [comment]
- [x] Setting : Force users to pickup a category - No poll symbol available

It seem, it has to do with the setting of the first category. If you allow polls in the first category, te editor shows per default the symbol for all categories.

**Comment by xillibit** [comment]
@rich20 : can-you check it with last update ?

**Comment by rich20** [comment]
- [x] Setting : Force users to pickup a category - No poll symbol available
These optiion works now correct.

But now is the symbol available as default for all categories, also if no poll is allowed if you go via Index -> Category -> New Topic.

**Comment by rich20** [comment]
- [x] Setting : Force users to pickup a category - No poll symbol available
- [x] But now is the symbol available as default for all categories, also if no poll is allowed if you go via Index -> Category -> New Topic.
These options work now correct. But only a small issue is still present.
If you open the menu item New topic, it shows the symbol as default. Only after a switch with the dropdown it will be hidden the symbol when no poll is allowed and afterwards it shows for all categories right (hidden or available depending on category setting).
