### ISSUE TITLE
[CKeditor] It's not possible to add own smileys to the editor emoticon bar

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7589]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Kunena template name and version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xillibit** [comment]
It was possible before ?

**Comment by rich20** [comment]
Yes it was possible (Backend -> Kunena -> Emoticons)
![Bildschirmfoto von 2020-10-17 14-14-56](https://user-images.githubusercontent.com/888847/96336962-8995fb00-1083-11eb-8cce-bc8d4204a5f2.png)
