### ISSUE TITLE
PHP Warning:  array_diff(): Expected parameter 2 to be an array

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7592]
**Steps to reproduce the issue**
1. Make some changes in backend->components->kunena forum->categories
2. Check the to error_log file located in /public_html/administrator/

**Expected behavior**
No PHP Warnings

**Actual result**
`PHP Warning:  array_diff(): Expected parameter 2 to be an array, null given in /home/username/public_html/administrator/components/com_kunena/controllers/categories.php on line 517`

**System information (please complete the following information)**
Joomla version: 3.9.22
Kunena version: 5.1.19
PHP version: 7.4.11
Database version: MySQL 5.7.31

**Comment by xillibit** [comment]
>     1. Make some changes in backend->components->kunena forum->categories

What king of changes ?

**Comment by sshcli** [comment]
> What king of changes ?

Just create a category and you will see the error in the error_log file

**Comment by sshcli** [comment]
I have applied the fix to 5.1 and I get the error:
`PHP Warning:  array_diff(): Expected parameter 2 to be an array, null given in /home/username/public_html/administrator/components/com_kunena/controllers/categories.php on line 519`

**Comment by sshcli** [comment]
Please reopen

**Comment by sshcli** [comment]
Yes, the problem is solved now.
Thanks
