### ISSUE TITLE
PHP Warning: Use of undefined constant JREQUEST_ALLOWRAW

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7593]
**Steps to reproduce the issue**
Check the to error_log file located in /public_html/administrator/

**Expected behavior**
No PHP Warnings

**Actual result**
`PHP Warning:  Use of undefined constant JREQUEST_ALLOWRAW - assumed 'JREQUEST_ALLOWRAW' (this will throw an Error in a future version of PHP) in /home/username/public_html/administrator/components/com_kunena/controllers/users.php on line 106`

**System information (please complete the following information)**
Joomla version: 3.9.22
Kunena version: 5.1.19
PHP version: 7.4.11
Database version: MySQL 5.7.31

**Comment by 810** [comment]
JRequest is deprecated, so i move this to 6.0.

**Comment by xillibit** [comment]
Seems already fixed in K6.0
