### ISSUE TITLE
Force users to pickup a category - Poll symbol available by default

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#7601]
Only a small issue is still present.
If you open the menu item New topic, it shows the symbol as default. Only after a switch with the dropdown it will be hidden the symbol when no poll is allowed and afterwards it shows for all categories right (hidden or available depending on category setting).

_Originally posted by @rich20 in https://github.com/Kunena/Kunena-Forum/issues/7586#issuecomment-712999583_

**Comment by rich20** [comment]
In principle, it has not direct to do with the setting Force users to pickup a category. It's generally if you use the menu item New Topic.
