### ISSUE TITLE
[CKeditor] Remove image from the message removes all line breaks too

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7613]
**To Reproduce**

1. Write a text (use line breaks too)
2. Add an image in the message
3. Write again a text
4. Add again a image (and so on)
5. Now remove an image

**Actual result**
It removes all line breaks

**Screenshots**
You see the results before and after remove

Entered in message
![Bildschirmfoto von 2020-10-24 17-42-52](https://user-images.githubusercontent.com/888847/97086087-9d140980-1621-11eb-95cd-3f8ab92a1793.png)
After remove an image
![Bildschirmfoto von 2020-10-24 17-43-23](https://user-images.githubusercontent.com/888847/97086119-c16fe600-1621-11eb-9034-502d186c14c7.png)

**Comment by xillibit** [comment]
It seems similar to this one : https://github.com/Kunena/Kunena-Forum/issues/7438

**Comment by rich20** [comment]
Yes, I've tested it now. It's the same bug, so I close this here.
