### ISSUE TITLE
The console shows errors 400 and 403 when social share buttons enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7651]
**To Reproduce**
1. Open the console
2. Open a topic

**Actual result**
You see errors 400 and 403

Example:
`jquery.min.js?80759583712babb574a265ce4b657466:2 GET https://cors-anywhere.herokuapp.com/https://www.stumbleupon.com/services/1.01/badge.getinfo?url=https%3A%2F%2Fwww.kunena.org%2Fforum%2Fgeneral-questions-archive%2F160144-users-can-t-post 403 (Forbidden)`

**Comment by xillibit** [comment]
With which kunena template ?

**Comment by rich20** [comment]
With both, Crypsis and Crypsisb3. You see it also on k.org

**Comment by rich20** [comment]
This error will be showing with all templates, inclusive Crypsisb4 and Blue Eagle

**Comment by xillibit** [comment]
Now https://www.stumbleupon.com/ has moved to mix.com so it can explain why it doesn't work but we need to remove it because it doesn't work with mix.com
