### ISSUE TITLE
The console shows facebook errors when social share buttons enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7660]
**To Reproduce**

1. Open the console
2. Open a topic

**Actual result**
You see errors 400

Example:
`jquery.min.js?80759583712babb574a265ce4b657466:2 GET https://graph.facebook.com/?id=https%3A%2F%2Fwww.kunena.org%2Fforum%2Finstallation-issues%2F160191-websites-gone-missing 400`

**System information (please complete the following information)**

- Joomla version: 3.9.22 and 3.9.23-dev
- Kunena version: 5.1.19 and 5.2.0-RC2-DEV
- Kunena template name and version: Tested with all Kunena templates
- Php version: 7.3.22 and 7.4.10
- Database version: 5.7.28

**Comment by xillibit** [comment]
To call/use the graph API from facebook it requires an access token, i'am looking if i can remove this call
