### ISSUE TITLE
Limit allowed BBCode for the new users in theyr profiles (no urls, images)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7678]
New users which have the limit, nevertheless can to enter all info such as:

- Location
- Website Address 
- Social Share
- URL in the signature

**Actual result**
```
The links or images has been removed from your signature because your aren't allowed to add them.
Your profile has been saved.
```
Although he receives this message, it will all published.

**Comment by xillibit** [comment]
Outside of the signature it's intended
