### ISSUE TITLE
Php 8.0 issues

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#7708]
Fixed:
PHP Deprecated:  Required parameter $parent follows optional parameter $len in C:\Git\Kunena-Forum\src\libraries\kunena\view.php on line 406
PHP Deprecated:  Required parameter $category_iconset follows optional parameter $filename in C:\Git\Kunena-Forum\src\libraries\kunena\template\template.php on line 1695
Warning: Undefined array key "mode" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3391
Warning: Undefined array key "content" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3725
Warning: Undefined array key "after_tag" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3097
Warning: Undefined array key "before_endtag" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3101
Warning: Undefined array key "before_tag" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3781
Warning: Undefined array key "mode" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3479
Warning: Undefined array key "after_endtag" in C:/Git/Kunena-Forum/src/libraries/kunena/external/nbbc/nbbc.php on line 3786

**Comment by xillibit** [comment]
Fixed:

On page /index.php/forum/topics/mode-topics?format=feed&type=rss : 

When post attachment the ajax query is index.php/forum/topic/task-upload?format=json and the error :

0 Call to a member function flip() on string
\Kunena-forum\src\libraries\kunena\image\image.php:180

0 Unsupported operand types: string * int
\Kunena-forum\src\components\com_kunena\models\topics.php:296

**Comment by xillibit** [comment]
These ones has been fixed by last commits
