### ISSUE TITLE
[CKEditor] Is it possible to adjust the dropdown lists of the Add Link option?

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7710]
**To Reproduce**

- Click on Add Link symbol
- Now you see 2 dropdown menus

**Link Type**

- [x] URL
- [x] E-mail
- [ ] Link to text anchor - can be removed
- [ ] Phone - can be removed

**Protocol**

- [ ] http and https - Is it possible to change the order of rows? On the first place is http and at the second place https so you must always change from http to https before you add a link.
- [ ] ftp - not neeeded
- [ ] news - not needed
- [ ] other - not needed

-

**Comment by xillibit** [comment]
>     * http and https - Is it possible to change the order of rows? On the first place is http and at the second place https so you must always change from http to https before you add a link.

Not sure if it's configurable in the default CKeditor plugin links
