### ISSUE TITLE
The menu item Recent Topics redirects to the next page

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7712]
**Describe the bug**
If you have written, edited or moderated a topic and afterwards click on the menu item Recent Topics, you will always be landing on page 2.

**To Reproduce**

1. Write, edit or moderate a post/topic and save the action.
2. Click on menu item Recent Topics

**Result**
With each refresh you will be landing on the next page.

**Additional context**
I've noticed it on k.org

**Comment by 810** [comment]
looks like it is fixed on the latest build.

**Comment by rich20** [comment]
This error no longer exists.
