### ISSUE TITLE
[CKEditor] Remove attachments changes all BBCode to HTML Codes

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7717]
**To Reproduce**

1. Create a message and use one or more BBCodes from the editor
2. Upload an image (indifferent if you insert in the message or not)
3. Click on the button Source
4. Now remove the image

**Actual result**
All codes have been changed to html

**Comment by xillibit** [comment]
@rich20 : can-you test with this change ?

**Comment by rich20** [comment]
Now it's the other way around.  Remove attachments works now, but we have now the problem if you insert an attachment in the message.

1. Create a message and use one or more BBCodes from the editor
2. Upload an image
3. Click on the button Source
4. Now insert the image

**Actual result**
All codes have been changed to html

**Comment by rich20** [comment]
This bug is already fixed
