### ISSUE TITLE
Url tags are displayed if you enter an url without display text

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7727]
**Describe the bug**
Enter an url like this:
`[url]https://www.kunena.org/[/url]`

**Actual result**
![Bildschirmfoto von 2020-11-28 20-04-09](https://user-images.githubusercontent.com/888847/100524051-2684a180-31b5-11eb-80cf-c32816070e3a.png)

**System information (please complete the following information)**
- Joomla version: 3.9.24-dev
- Kunena version: 5.2.0-RC3-DEV 
- Kunena template name and version: all ours
- Php version: 7.4.10
- Database version: 5.7.28

**Comment by rich20** [comment]
I've noticed, this issue occur only if as the setting is chosen "Auto-Link URLs = Yes".

**Comment by xillibit** [comment]
your change has no effect

**Comment by 810** [comment]
for me it is, because its not loading the layout anymore

**Comment by xillibit** [comment]
it doesn't work only if you put youtube link into url tag
