### ISSUE TITLE
[CKEditor] Insert and remove attachments duplicates the text

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7749]
**To Reproduce**

1. Write a text in the text field
2. Add an attachment
3. Remove the attachment

**Result**
The text is doubled

It is even worse if the attachment will insert in the message

- Insert - the text is doubled
- Remove - the text is 4 times
- It remain the ttachment code in the message
![Bildschirmfoto von 2020-12-05 18-13-29](https://user-images.githubusercontent.com/888847/101259006-93a0b580-3726-11eb-880e-5c547030589b.png)

**System information (please complete the following information)**
Joomla version: 3.9.24-dev
Kunena version: 5.2.0-RC3-DEV 
Kunena template name and version: all ours
Php version: 7.4.10
Database version: 5.7.28

**Comment by xillibit** [comment]
But now this issue still still exist : https://github.com/Kunena/Kunena-Forum/issues/7717
