### ISSUE TITLE
 Warning: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by nightw0lv** [Kunena/Kunena-Forum#7769]
**Describe the bug**
 Warning: Trying to access array offset on value of type bool in /var/www/html/forum/libraries/kunena/forum/message/message.php on line 333

**To Reproduce**
update php 8.0
try to reply in post then open full editor to reply

Joomla version: Joomla! 3.10.0-alpha3
Kunena version: 5.1.19
Kunena template name and version: Crypsis
Php version: 8
Database version: mariadb 10.5.6

**Comment by xillibit** [comment]
This is fixed in Kunena 5.2.0, for support of Php 8.0.0 you should use Kunena 5.2.0 with Joomla!3.9.23 (Joomla! 3.9.24 will fix some remaining issues)

**Comment by nightw0lv** [comment]
how to make the update there is not any available update on kunena plugin

**Comment by xillibit** [comment]
Hello, you should download the 5.2.0 version on this page : https://www.kunena.org/download and install it by the Joomla! installer

**Comment by nightw0lv** [comment]
http://prntscr.com/w5q4t2 i get this error when i try to install it

**Comment by xillibit** [comment]
The alpha3 of Joomla! 3.10 is being old is better to use a nightly build : https://developer.joomla.org/nightly-builds.html

Try with the lastest build of Joomla! 3.10 is you still encounter the issue
