### ISSUE TITLE
Template settings for BBCode are ineffective

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#7774]
**Describe the bug**

**To Reproduce**
in template settings tab [bbcode] configure the following settings to 'no'
- Show Twitter button
- Show Ebay button
- Show Instagram button
- Show Soundcloud button

**Expected behavior**
buttons not showing in editor

**Actual result**
buttons showing in editor

**Screenshots**
![image](https://user-images.githubusercontent.com/2733197/102757701-00948c00-4372-11eb-941f-fbe7dacad1e7.png)

**System information (please complete the following information)**

Joomla version: 3.9.23
Kunena version: 5.2
Kunena template name and version: crypsis
Php version: 7.4

**Comment by rich20** [comment]
@Ruud68 
It should be possible by adding names of the buttons in the ckeditor_config.js
.../media/kunena/core/js/ckeditor_config.js lines 33 until 43

### In the template setting (tab BBCode) are this options (no one of these buttons can be deactivated)
Maybe we should remove this setting options (except the social share buttons)? Or we keep these options, but then they should work.
- [ ] Show Video button
- [ ] Show Maps button
- [ ] Show Emoticons button
- [ ] Show Twitter button
- [ ] Show Ebay button
- [ ] Show Link button
- [ ] Show Picture button
- [ ] Show Hide button
- [ ] Show Spoiler button
- [ ] Show Table button - can be removed (tables do not work with CKEditor)
- [ ] Show Code button
- [ ] Show Quote button
- [ ] Show Instagram button
- [ ] Show Soundcloud button
- [ ] Show Confidential button
- [ ] Show Superscript button
- [ ] Show Subscript button
- [ ] Show Numbering button
- [ ] Show Bullets button
- [ ] Show Align Right button
- [ ] Show Center button
- [ ] Show Underline button
- [ ] Show Italic button
- [ ] Show Bold button
- [ ] Show Strikethrough button
- [ ] Show Colors drop menu
- [ ] **Show Size drop menu** - is available four times
- [ ] **Show Size drop menu**
- [ ] **Show Size drop menu**
- [ ] **Show Size drop menu**

**Comment by Ruud68** [comment]
Hi @rich20 , thanks for looking into this.
This is okay for a temp solution, but as this is a Kunena 'core' hack, any changes will not survive a Kunena upgrade. So the setting in the template should be pulled in by this js file and removed when configured to do so.

I'm still undecided if I want the new editor (not that there is a choice), as the editor as it is now is to 'bloated': on a mobile the editor buttons take half the edit screen which is not okay.
Is that something that will be looked at or is that as it will be 'forever' ?

**Comment by rich20** [comment]
Yes, it was only a temporary solution for you. The setting options muss be fixed.
I don't know the reason for changing to CKEditor, but he will remain I think. I've added now the bug label.
> I'm still undecided if I want the new editor (not that there is a choice), as the editor as it is now is to 'bloated': on a mobile the editor buttons take half the edit screen which is not okay.

Yes, I noticed that. A lot of space is wasted by the order of the symbols.
![Bildschirmfoto von 2020-12-23 18-40-21](https://user-images.githubusercontent.com/888847/103025563-5a53ac80-4552-11eb-9e37-72c2d4131596.png)

**Comment by Ruud68** [comment]
CKEditors added value (for me) is WYSIWYG, the bb-code that was showing in the text makes it 'unusable' for not-so-nerdy users :) This is definitely an improvement, although moving from bb-code to HTML would IMO even be a better option as that way you can have a choice of editor inline with the rest of your site.
Would definitely be my choice when starting-over. conversion from old posts bb-code could be handled by an import or even on the fly with a plugin.

**Comment by Ruud68** [comment]
not fixed, please reopen.
All settings are still there and not working

**Comment by xillibit** [comment]
For me it has worked with that change on crypsis

**Comment by Ruud68** [comment]
Version 5.2.1.
Also none of the settings are working (e.g. switching confidential = no, displays the confidential button)
![image](https://user-images.githubusercontent.com/2733197/103217170-44f6cd80-4918-11eb-8107-95d3ef4837b7.png)

**Comment by rich20** [comment]
Can't be deactivated
- [ ] Show Align Right button
- [ ] Show Textcolor button on editor

**Comment by rich20** [comment]
I think, this can be closed unless you want to make the remaining symbols deactivatable.
![Bildschirmfoto von 2020-12-29 15-46-33](https://user-images.githubusercontent.com/888847/103292585-6a560b00-49ee-11eb-9cec-e2d62dea6e81.png)
