### ISSUE TITLE
[CKEditor] Kunena does not recognize all text size values

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7838]
The editor dropdown contain among others the values for the text sizes 30 and 300. But these both values will not recognized by Kunena. Should we remove these both values from the dropdown list?

**Comment by rich20** [comment]
Addition: the value 120 will also not recognized

**Comment by xillibit** [comment]
There are only the followings size which are supported : 50, 85, 100, 150 and 200

**Comment by rich20** [comment]
Is it possible to remove not supported sizes from the  dropdown list?
