### ISSUE TITLE
Make ebay affiliate id configurable & check the current ID

### ISSUE THREAD

**Issue by mahagr** [Kunena/Kunena-Forum#784]
We need to review, whose affiliate ID Kunena uses and if it is valid. We also need to make it configurable by site administrator.

See proposal from:
http://www.kunena.org/forum/114-User-written-hacks/103222-Location-of-Ebay-Widget-code?start=10#125218

@fxstein, do you have some insight on this one?

**Comment by Qato30** [comment]
I liked all of these details. I am also using the app for the [sms automotive](https://www.heymarket.com/automotive/) campaigns and must tell you that it is very affordable. I am getting very good results and the best thing is that managing campaigns on my own is extremely easy with this app. The interface is cool and easily understandable.
