### ISSUE TITLE
Protected attachments show an extract of the protected file name

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7841]
**Describe the bug**
https://www.kunena.org/forum/k-5-2-support/160466-attachment-getfilename-returns-the-protected-name

**Additional context**
Kunena 5.1 and older versions displays the attachments in the forum with his file names and extension such as image.png
Now, with K5.2 it shows an extract of the protected file name depending on the number of characters which you allow for file names in the configuration.
I'm not sure if it's correct, therefore I've not added a bug label. <br>
![embedded](https://user-images.githubusercontent.com/888847/103570484-739d1700-4ec9-11eb-8627-b13e85409fb7.png)

**Comment by xillibit** [comment]
This change https://github.com/Kunena/Kunena-Forum/issues/6084 at the begining of developpement of K5.2 has made a filename displaying like a hash
