### ISSUE TITLE
User image not exist after change

### ISSUE THREAD

**Issue by nightw0lv** [Kunena/Kunena-Forum#7842]
**Describe the bug**
image of user not showing after change

**To Reproduce**
just change image

**Expected behavior**
show the changed image

**Actual result**
image link not exist if i try to copy link location from image 

**Screenshots**
https://prnt.sc/whhbtf
https://prnt.sc/whhdc4

**System information (please complete the following information)**

Joomla version: 3.10.0-alpha4-dev
Kunena version: 5.2.1
Kunena template name and version: Crypsisb4 5.2.1
Php version: 8.0.0
Database version: mariadb 10.5.6

**Comment by xillibit** [comment]
It's a know issue with Php 8.0.0 and the fix is present in Joomla! 3.9.24, i don't when it will merged into Joomla! 3.10
