### ISSUE TITLE
[K5.2.2] Reason for editing is hidden

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7859]
**Steps to reproduce the issue**
Try to edit any topic

**Expected behavior**
Reason for editing should be visible
<img width="397" alt="good2" src="https://user-images.githubusercontent.com/12942731/104653322-d1cbb600-5690-11eb-9fc8-db6b3aa94cc2.PNG">

**Actual result**
Reason for editing is hidden
<img width="499" alt="bad2" src="https://user-images.githubusercontent.com/12942731/104653342-d7c19700-5690-11eb-8f5b-7cbf44e4be46.PNG">

**System information (please complete the following information)**
Joomla version: 3.9.24
Kunena version: 5.2.2
PHP version: 7.4.14
Database version: MySQL 5.7.32

**Comment by sshcli** [comment]
This happens because Crypsis is the default template when you install kunena.
This does not happen if you choose Crypsisb4 + Joomla bootstrap4 template

**Comment by rich20** [comment]
I you add this code to the Joomla template custom.css it would be only a workaround for the templates Crypsis and Crypsisb3. For Crypsisb4 would have this code a negative effect, because this template not needs a correction for this option.

```
.cke_chrome {
    margin-bottom: 3em; /* or 35px */
}
```
