### ISSUE TITLE
[K5.2.2] Topic Template does not load in CKeditor

### ISSUE THREAD

**Issue by sshcli** [Kunena/Kunena-Forum#7874]
**Steps to reproduce the issue**
1. Backend->Categories->Edit Category X->Topic Template = Insert some Value here
2. Frontend-> Try to make a new post in Category X

**Expected behavior**
Topic Template should load in CKeditor

**Actual result**
Topic Template does not load in CKeditor

**System information (please complete the following information)**
Joomla version: 3.9.24
Kunena version: 5.2.2
PHP version: 7.4.14
Database version: MySQL 5.7.33

**Comment by xillibit** [comment]
When i go on K5.1 or K5.2 in a category when the topic template has been defined and create new topic the topic template text is inserted in textarea. I have the modal only when i new topic from the Kunena menu

**Comment by rich20** [comment]
In principle, it's the same issue. https://github.com/Kunena/Kunena-Forum/issues/7869
The topic template works if you go to the category and creates a new topic. 
With the menu item it works only if you use a topic template in the first category like Welcome Mat.
As far I remember, the modal options have never worked correctly and only ensured confusion. In my opinion, the modal should be removed.

**Comment by rich20** [comment]
- [x] Success - This fix solved the problem https://github.com/Kunena/Kunena-Forum/issues/7869
