### ISSUE TITLE
Poll in categories which contain subcategories are not possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7923]
**To Reproduce**

1. Create a subcategory for the Suggestion Box
2. Go in the frontend to Index -> Suggestion Box -> click on New Topic
3. The poll symbol is gray colored
4. Now unpublish the subcategory
5. Refresh the page in the frontend and the poll symbol is available

If you publish the subcategory once more, the poll symbol is also gray again (it's only possible to create a poll in the sub category)

**System information (please complete the following information)**

- Joomla version: 3.9.25-dev
- Kunena version: 5.2.3-DEV
- Php version: 7.4.14
- Database version: 5.7.28

**Comment by xillibit** [comment]
It's because in that case, there is the category list which appears : 

![image](https://user-images.githubusercontent.com/876395/109400367-a94e0180-7948-11eb-852d-bfffce113baf.png)
