### ISSUE TITLE
The changelog is a PHP file

### ISSUE THREAD

**Issue by shoulders** [Kunena/Kunena-Forum#7924]
**Describe the bug**
In the file **pkg_kunena_v5.2.2_2021-01-13.zip** the changelog is `CHANGELOG.php` and this is an issue for external software that reads the changelog. I would never parse a php file as if it were plain text. In fact my software does not recognise the changelog in php format

**To Reproduce**
just look in the package
 https://github.com/Kunena/Kunena-Forum/blob/K5.2/COPYRIGHT.php

**Expected behavior**
change from `php` format to standard text or Markdown so external software can parse the changelog.

In my software I am using https://keepachangelog.com/en/1.0.0/

Thanks

**Comment by xillibit** [comment]
The COPYRIGHT.php file isn't a changelog file but anyway i will add a chnagelog file in markdown
