### ISSUE TITLE
Where can i change date format

### ISSUE THREAD

**Issue by Joomron** [Kunena/Kunena-Forum#7928]
Hello,

where can i change dataformat profiel 
![birth](https://user-images.githubusercontent.com/13587871/109432055-b2eb6e00-7a09-11eb-8f0a-e10cc8aa6801.png)
I want change this from **data-date-format="mm/dd/yyyy"** to **data-date-format="dd/mm/yyyy"** 

We use template blue_eagle5

Greatings Ron

**Comment by xillibit** [comment]
It's hardcoded for all Kunena templates so it can't be changed easily

**Comment by Joomron** [comment]
Okay, in they new templates in Joomla 4 it will come in there ?

Greatings Ron

**Comment by xillibit** [comment]
Kunena 6.0 which is in developpement will have the same  template than crypsisb4, but this is more a feature request

**Comment by N6REJ** [comment]
the date system is totally fubar'd.  It's apparently hard coded to YYYY-mm-dd and changing the template date format does nothing.

**Comment by N6REJ** [comment]
@xillibit can you respond please.

**Comment by xillibit** [comment]
> the date system is totally fubar'd. It's apparently hard coded to YYYY-mm-dd and changing the template date format does nothing.

Yes it's hardcoded, so i need to add a new setting to change the date format and it's why i have labelled this issue as feature
