### ISSUE TITLE
Cannot hide admins in userlist

### ISSUE THREAD

**Issue by sozzled** [Kunena/Kunena-Forum#793]
See http://www.kunena.org/forum/168-K-17-Support/123164-Remove-user-from-Userlist#125445 for details

**Comment by xillibit** [comment]
I have re-tested it now, it's works well with K3.0.x but with K3.1.0 it doesn't work i need to check what's going on

**Comment by rich20** [comment]
It works also with K.1.0 but vice versa in Blue Eagle.
In Blue Eagle you must set "Show Super Users in user list = Yes", then he is hidden. 
In Crypsis it works correct.

**Comment by xillibit** [comment]
Can-you write here : https://github.com/Kunena/Kunena-Forum/pull/2718 if it's working now ?

**Comment by 810** [comment]
Is now fixed, is now in K3.1, Im closing this issue
