### ISSUE TITLE
Error 500 string to array conversion

### ISSUE THREAD

**Issue by ghost** [Kunena/Kunena-Forum#7930]
**Describe the bug**
When saving a kunena category an error 500 is fired with "String to array conversion" message

Joomla version: 3.9.24
Kunena version: 5.2.2
Kunena template name and version:
Php version: 7.0.18
Database version: 5.7.19

In administrator/components/com_kunena/controllers/categories.php on line 518 the `diff_array` is done on two different structured arrays. The first one, `$aliases_all` is an simple array with list of aliases, the second one, `$aliases` is an associative array.

I think that you should use them as:

```php
$aliases = array_diff($aliases_all, $aliases['aliases']);
```

rather than the actual:

```php
$aliases = array_diff($aliases_all, $aliases);
```

**Comment by xillibit** [comment]
I had already fixed a similar issue previously : https://github.com/Kunena/Kunena-Forum/issues/7592

**Comment by ghost** [comment]
Oh sorry I miss that an issue was already opened about this.

**Comment by ghost** [comment]
But in your patch the `$aliases` is still an associative array and the `$aliases_all` is not, so the `array_diff()` will still throw a notice about string to array conversion.

**Comment by xillibit** [comment]
> Oh sorry I miss that an issue was already opened about this.

The issue is closed but i will check to avoid to have this notice

**Comment by ghost** [comment]
Nice, it will prevent having an error 500 in the backend, not serious but annoying ;-)
