### ISSUE TITLE
Type mismatch in libraries/bbcode/bbcode.php

### ISSUE THREAD

**Issue by ghost** [Kunena/Kunena-Forum#7933]
In this file, the class `Nbbc\BBCodeLibrary` is extended by `KunenaBbcodeLibrary` class, but the first parameter `$bbcode` of some methods has not the `Nbbc\BBCode` type as in the extended class.

Rather than:

```php
	public function DoEmail($bbcode, $action, $name, $default, $params, $content)
	{
		if ($action == Nbbc\BBCode::BBCODE_CHECK)
		{
			return true;
		}
…
```

You should have:

```php
	public function DoEmail(Nbbc\BBCode $bbcode, $action, $name, $default, $params, $content)
	{
		if ($action == Nbbc\BBCode::BBCODE_CHECK)
		{
			return true;
		}
…
```

See lines 1220 (DoEmail), 1269 (DoURL), 1372 (DoSize), 1437 (DoList), 1528 (DoSpoiler), 1577 (DoHide), 1627 (DoConfidential), 1717 (DoMap), 1773 (DoEbay), 1876 (DoArticle), 2022 (DoQuote), 2054 (DoCode), 2122 (doTableau), 2184 (DoVideo), 2467 (DoAttachment), 2628 (DoFile), 2720 (DoImage), 2816 (DoTerminal), 2845 (DoTweet), 3136 (DoSoundcloud) and 3181 (DoInstagram).

[patch.txt](https://github.com/Kunena/Kunena-Forum/files/6067689/patch.txt)

**Comment by xillibit** [comment]
Thanks for that, i will integrate your changes but next time you can do a pull request like that you don't need to send a text file

**Comment by ghost** [comment]
Ok I will do it if necessary next time!

Franck Lévy - CEPN IT Admin – Operating Crocker’s rules (http://sl4.org/crocker.html)
