### ISSUE TITLE
{KunenaFactory::getProfile() in quote

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#7943]
**To Reproduce**
Click on the Quote button

**Actual result**
You see this before the quoted text:
{KunenaFactory::getProfile()-&gt;getProfileName(KunenaUser, richi)} wrote:

**System information (please complete the following information)**

Joomla version: 3.9.26-dev
Kunena version: 5.2.3-dev
Php version: 7.4.14
Database version:

**Comment by xillibit** [comment]
whith which templates ?

**Comment by rich20** [comment]
With Crypsis as well Crypsisb3. I've tried now also with Joomla 3.9.24 and it's the same. So it must be the error on our K5.2.3-dev version

**Comment by rich20** [comment]
Addition: The same with Crypsisb4
