### ISSUE TITLE
Names not displayed

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#7947]
**Describe the bug**
update to 5.2.3, names are not shown (see image for two examples)
![image](https://user-images.githubusercontent.com/2733197/110299628-343c9500-7ff6-11eb-8142-be2dc78e8489.png)

**To Reproduce**
1. install 5.2.3

**Expected behavior**
names should show

**Actual result**
names empty

**System information (please complete the following information)**

Joomla version: 3.9.25
Kunena version: 5.2.3
Kunena template name and version: crypsis
Php version: 7.4.latest

**Additional context**

**Comment by xillibit** [comment]
Which Kunena integration plugin do-you have enabled ?

**Comment by Ruud68** [comment]
- Content - Kunena Discuss
- Kunena - Joomla Integration
- Kunena - Kunena Integration
- Kunena - ochBlog Integration
- OSMap - Kunena Plugin
- Quick Icon - Kunena Forum
- System - Kunena Forum

the Kunena-ochBlog Integration is used to get the avatar from a Joomla Custom user Field and to get the userlist / user profile to resp. the authoroverview and authorprofile page.

Nothing 'name' related.
If I disable this plugin the names still remain 'empty'

**Comment by Ruud68** [comment]
@xillibit you can reproduce when you set in Kunena - Kunena Integration setting 'Enable Kunena Profiles' to no.

**Comment by Ruud68** [comment]
I can fix in my own plugin by adding function getProfileName($user, $visitorname, $escape)

doing a returning a parent::getProfileName is not working, probably because the parent has set the profile to 'no'.
So I have to duplicate all the code from the kunena plugin into my own plugin.

Not sure what is in release 5.2.3 that triggered this behavior? Would be nice if these changes / implications would somehow be on the release notes (for the developers out there that build upon Kunena).

**Comment by Ruud68** [comment]
sorry for the follow up :)
I think that when you set Enable Kunena Profile to NO, it should still show the name (only not linked to the profile).
So I think this is a bug in Kunena

**Comment by xillibit** [comment]
I have removed the method `getname()` from class `KunenaUser` and created a method instead for that in each integration plugin of Kunena, all the calls `$user->getName()` should be replaced by `KunenaFactory::getProfile()->getProfileName($user)`

In the method  the method `getname()` from class `KunenaUser` there was check to show username or name depending of settings used by Community Builder else it just show the username but it wasn't the right place to do it

**Comment by Ruud68** [comment]
okay, thanks, but why when I disable the Kunena Profile (in the Kunena Integration plugin), there is no name showed anymore (instead of a name without a link to the profile)?

**Comment by svanschu** [comment]
@xillibit I saw you reimplemented the getName method. Which ist the way to go now? $user->getName() or KunenaFactory::getProfile()->getProfileName($user) ??

**Comment by xillibit** [comment]
I had deleted the $user->getName() in K5.2.3 but it has caused plenty of issues. You should still use $user->getName(), just wait the release of Kunena 5.2.4.
