### ISSUE TITLE
Can't add an attachment to the message when Add Suffix to URL and rewrite url is enabled

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#7997]
**Describe the bug**
See : https://www.kunena.org/forum/k-5-2-support/161237-can-t-add-a-file-or-a-picture-to-a-post?start=0#216934

**To Reproduce**
Enable in Joomla! configuration the "Add Suffix to URL" and others settings for rewrrite URL
When you add an attachment to your message you will see in the developpement console of your browser that the url called by ajax is malformed, and the attachment can't added because the url is unreachable : 

`yoursite.com/forum/topic/task-upload.json?5426de347cf6c7493b=1`

The url should be like that instead :

`yoursite.com/forum/topic/task-upload?format=json&5426de347cf6c7493b=1`

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.9.26
Kunena version: 5.2.5-dev
Kunena template name and version: crypsis and maybe others
Php version: 7.4.16
Database version: MySQL 5.7.31

**Comment by ghost** [comment]
Any advice to avoid URL rewriting for this particular URL in the .htaccess?

**Comment by ghost** [comment]
It's not a URL rewritting issue but a problem in the kunena code.

Workaround: in file `libraries/kunena/image/image.php`, line **104**:

Replace 

```php
            $exif  = @exif_read_data($filename);
```

By
```php
            $exif  = false; //@exif_read_data($filename);
```

And everything is alright except that images are not more rotated if necessary; might be less important than blocking attachment, isn't it?

Note that it's only for the 5.2 version of Kunena, not tested yet with the 6.0

**Comment by xillibit** [comment]
Thanks for looking to it. In Kunena 6.0 this part of code is pretty similar, since Php 7.2.x the exif_read_data() function return exception when it fails so in Kunena 6.0 i can add a try catch on this

**Comment by ghost** [comment]
> Thanks for looking to it. In Kunena 6.0 this part of code is pretty similar, since Php 7.2.x the exif_read_data() function return exception when it fails so in Kunena 6.0 i can add a try catch on this

I just updated Kunena with the last release 5.2.5 but running with PHP 7.0 (I have to upgrade, I know) I still have the same issue so I had to patch again the 5.2.5 as I described above. The try…catch seems not enough with my configuration. Weird!

**Comment by xillibit** [comment]
At this line : https://github.com/Kunena/Kunena-Forum/blob/5b0f3759b49ebcddea980df090073e816ab61e26/src/libraries/kunena/image/image.php#L112 try to replace : 

`$exif = @exif_read_data($filename);`

by

`$exif = exif_read_data($filename);`

**Comment by ghost** [comment]
Just tried but same result, with or without @ the attachment (JPEG picture) is not uploaded, still weird and I don't understand why I have this behavior!

**Comment by xillibit** [comment]
Can-you share the image which you try to upload or one to reproduce the issue ?

**Comment by ghost** [comment]
> Can-you share the image which you try to upload or one to reproduce the issue ?

![computerrage](https://user-images.githubusercontent.com/76808728/120449162-7d9b4700-c38f-11eb-9fd9-561aab1ba2a9.jpg)

**Comment by ghost** [comment]
With `$exif = exif_read_data($filename);` (inside try … catch), see https://nextcloud.cepn.asso.fr/s/77iangc3Ap6SibZ

Progress bar remains empty, Submit button becomes disabled, and in the console :

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://example.com/forum/topic/task-upload.json?01ae6a1b4b1d314c66aab90678c46cc1=1 → 
{
  "version": "1.0",
  "errors": [
    {
      "message": "exif_read_data(8b076cf4c83abff809194effacc01865): Illegal IFD size",
      "code": 500
    }
  ]
}
```

With `$exif = false;`, see https://nextcloud.cepn.asso.fr/s/eeeJee88s2psX74

Progress bar becomes full, Submit button stays enabled, and I can remove the attachment.

**Comment by xillibit** [comment]
The error Illegal IFD size is a bug in Php 7.2/7.3, probably this bug : https://bugs.php.net/bug.php?id=75785

Try to switch to a newer Php version 7.4 or more or stick with Php 7.1

**Comment by xillibit** [comment]
Now Kunena 6.x needs Php 7.4 and retied now but i'am not able to reproduce this issue anymore
