### ISSUE TITLE
custom.css requiring parent identifier for classes.

### ISSUE THREAD

**Issue by N6REJ** [Kunena/Kunena-Forum#8009]
**Describe the bug**
when using custom.css in kunena for some strange reason the parent of the class is being required to be specified.
something simple like 
``` 
.btn-link{ color: green; }
```
will not be picked up if the parent is ```<a class="btn-link">foo</a>```
but will if 
``` a.btn-link{ color: green; } ```
is used.

Also if I use nesting it's ignored as well.  Such as
```
body.com_kunena {

    #container_main {
        background-color: pink;
     }
}
```
This is happening with crypsis.
I've attached my relevant .css files

**To Reproduce**
use the included .css files.

**Expected behavior**
css behaves exactly the same as if the code was put directly into the templates custom.css file.

**Actual result**
template style is maintained.

**System information (please complete the following information)**

Joomla version:  3.9.25
Kunena version: 5.2.4
Kunena template name and version: cyrpsis 5.2.4
Php version:  7.4.16
Database version:  10.3.28-MariaDB-cll-lve

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10 x64 pro
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**
 - Version [e.g. 22] Version 89.0.4389.114

**Additional context**

[custom-kunena.css.txt](https://github.com/Kunena/Kunena-Forum/files/6312865/custom-kunena.css.txt)
[custom.css.txt](https://github.com/Kunena/Kunena-Forum/files/6312866/custom.css.txt)

**Comment by N6REJ** [comment]
still waiting

**Comment by xillibit** [comment]
Do-you have tried to clean the cache ?

**Comment by N6REJ** [comment]
yes, it has to do with the .less compiler.  Please look @ the included files for a better understanding.

**Comment by rich20** [comment]
If you want to use the codes without parent,  then use the custom.less. That is why this file exists.
> **Expected behavior**
css behaves exactly the same as if the code was put directly into the templates custom.css file.

I see no difference, it's indifferent if I add your code in the  Template custom.css or in the Kunena custom.less

**Comment by N6REJ** [comment]
@rich20 I agree thats how it should be but clearly its not.  The import is correct which means ANYTHING SHOULD BE the same as if I had put it in the custom.css itself.
The exact same code put directly into the template custom.css doesn't have the issue
