### ISSUE TITLE
Unable to resize/crop avatar on upload

### ISSUE THREAD

**Issue by N6REJ** [Kunena/Kunena-Forum#8023]
**Describe the bug**
When the user is adding an image to their profile they should be able to position the useable area as indicated here
![image](https://user-images.githubusercontent.com/1850089/115553065-9a157100-a272-11eb-91d3-7635b7ac0fb2.png)
instead it is simply saved.

**To Reproduce**
1. go to front end of forum and select user preferences
2.  go to avatar and upload a non square image
3. attempt to select the useable area

**Expected behavior**
able to select useable area

**Actual result**
image is instantly saved.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 3.9.26
Kunena version: 5.2.4
Kunena template name and version: Crypsis 5.2.4
Php version: 7.4.1
Database version:

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10 x64 pro
 - Browser [e.g. chrome, safari]  Chrome
 - Version [e.g. 22] 90

**Comment by N6REJ** [comment]
@xillibit I've posted several bugs this week with no responses.. please check things out.

**Comment by xillibit** [comment]
I'am working on Kunena 5.2 and 6.0 on free time, please wait if it's not answered couple of hours after

This setting isn't intented to have a selectable area when you upload an new avatar. This setting when enabled, on click on avatar just redirect you on edit profile page, that's all.
