### ISSUE TITLE
Wrong update infos

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8160]
**To Reproduce**

- Install the beta on a clean Joomla
- Go to the Joomla Dashboard
- You see Updates available
- Click on it and you see:
- Installed **6.0.0-BETA1** - Available **6.0.0-ALPHA2**

**System information (please complete the following information)**

- Joomla version: 4.0.0-rc2-dev
- Kunena version: 6.0.0-BETA1
- Kunena template name and version: Aurelia
- Php version: 8.0.1 and 7.4.14
- Database version: 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Success
