### ISSUE TITLE
On Kunena menu item Home it lacks the option Default Menu Item

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8164]
**Describe the bug**
So it's not possible to choose the landing page in this menu item (see images).

**Menu in K5.2**
![Bildschirmfoto von 2021-06-08 20-20-24](https://user-images.githubusercontent.com/888847/121238991-fcfdae80-c898-11eb-9d2b-2b887710ae83.png)
**Menu in K6.0**
![Bildschirmfoto von 2021-06-08 20-13-57](https://user-images.githubusercontent.com/888847/121239115-1a327d00-c899-11eb-9180-866f1192d723.png)

**System information (please complete the following information)**
- Joomla version: 4.0.0-rc2-dev
- Kunena version: 6.0.0-BETA1
- Kunena template name and version: Aurelia
- Php version: 8.0.1 and 7.4.14
- Database version: 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
I have just tried and re-created all the Kunena menus and i have that now : 

![image](https://user-images.githubusercontent.com/876395/141528282-0e8c90b8-0bf6-408b-87af-92cb0cb8510a.png)

**Comment by rich20** [comment]
> I have just tried and re-created all the Kunena menus and i have that now 

Your image shows the menu type Alias in the main menu, not the Kunena menu item Home in the Kunena menu. 
The field Menu Item Type is empty at Kunena Home if you (re)create the menu. 
Open it, and try to enter the Menu Item Type, then you will see the problem.
This menu item makes the problems with the pagination.
