### ISSUE TITLE
The Kunenamenu will not created on a installation

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8165]
Also, the option Restore Kunena Menu has no effect. The button is not active and there are no reaction.

**Comment by xillibit** [comment]
I had fixed the issue with restore menu yesterday, need to fix the issue with modal which appears in first place for now it's disabled

**Comment by rich20** [comment]
Yes, restore the Kunena menu works now, but it creates not automatically the menu items during the first Kunena installation.
