### ISSUE TITLE
Only with PHP 8 - Rendering Error in layout Widget/Forumjump  on Index page

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8168]
**Describe the bug**
Instead of the jump option, you get this error on top. But this error occur only with php 8. Tested with php 8.0.1, php 8.0.6 and php 8.0.7 
With php 7.4.19 is it ok, the jump option is available.

.../libraries/src/Router/SiteRouter.php on line 445

Rendering Error in layout Widget/Forumjump: array_merge(): Argument #1 must be of type array, null given in /.../components/com_kunena/template/aurelia/layouts/widget/forumjump/default.php on line 28
Layout was rendered in /.../components/com_kunena/template/aurelia/layouts/category/index/default.php on line 39

**System information (please complete the following information)**
- Joomla version: 4.0.0-rc2-dev
- Kunena version: 6.0.0-BETA1
- Kunena template name and version: Aurelia
- Php version: 8.0.1 and 7.4.14
- Database version: 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
I don't see this error, tested with Php 8.0.7

**Comment by rich20** [comment]
Maybe you must create a new category to see this error.

**Comment by rich20** [comment]
Maybe this error is related with this error:  https://github.com/Kunena/Kunena-Forum/issues/8169

**Comment by rich20** [comment]
Since restore Kunena menu is possible, this error is gone. It seems, the error was caused by missing or wrong menu items.
