### ISSUE TITLE
Rendering error with sample data or created categories (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8169]
**To Reproduce**
Create a new category and you see this message:
`Kunena\Forum\Libraries\Forum\Category\KunenaCategory::addAlias(): Return value must be of type bool, none returned`
Go to the dashboard and back to the category manger. The category has been created.

When this category is added as top level (section), you see it on index page. But when is an assigned category, you get this error:

Rendering Error in layout Category/Index: Kunena\Forum\Libraries\Icons\KunenaIcons::caticon(): Argument #1 ($categoryicon) must be of type string, null given, called in /.../components/com_kunena/src/Layout/Category/CategoryIndex.php on line 105 in /.../components/com_kunena/src/Layout/Category/CategoryIndex.php on line 105
Layout was rendered in /.../components/com_kunena/template/aurelia/pages/category/list/default.php on line 27

In the category manager is the category not listed as child element (see image).

**Screenshots**
![Bildschirmfoto von 2021-06-10 17-11-00](https://user-images.githubusercontent.com/888847/121561526-dcf4f900-ca18-11eb-8528-98b316177ff7.png)

**System information (please complete the following information)**
- Joomla version: 4.0.0-rc2-dev
- Kunena version: 6.0.0-BETA1
- Kunena template name and version: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.7 
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
I have created a top level category, and then a sub-category attached to this top level category but i don't have seen these errors.

**Comment by rich20** [comment]
This error is now solved with you new build.
