### ISSUE TITLE
Ban not completely solved

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#8172]
https://github.com/Kunena/Kunena-Forum/issues/8170
Applying the fix (update tables in database) works when viewing banned profile from users that were banned before update to 5.2.5. No more error.
Problem that it is impossible to ban from site still exists.
![Yndi 20210613-592](https://user-images.githubusercontent.com/8941310/121797928-90313e00-cc23-11eb-8e87-0e0a44ae413d.jpg)

![Yndi 20210613-593](https://user-images.githubusercontent.com/8941310/121797929-90c9d480-cc23-11eb-845b-3515db2b2e05.jpg)

**Comment by xillibit** [comment]
I have just tried, when i ban the user from site : 

![image](https://user-images.githubusercontent.com/876395/121802309-e3af8600-cc3b-11eb-8bed-28cb4baf1ea0.png)

In backend it's right disabled : 

![image](https://user-images.githubusercontent.com/876395/121802322-ff1a9100-cc3b-11eb-805b-07e282afc9cf.png)

**Comment by Pinkeltje** [comment]
Thx for checking. Caused by override for user/ban/form/default.php.
