### ISSUE TITLE
Topic Template: Code tags goes to the last row

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8175]
**Describe the bug**
https://www.kunena.org/forum/k-5-2-support/161853-topic-template-possibilities
(I've tested it and confirm it)

**To Reproduce**
Create a topic template like this:
```
[quote]quoted text[/quote]
[b]bold text[/b]
[color=#e74c3c]red text[/color]
default text
```
**Result**
It copies all end tags to the last row in the text field
```
[quote]quoted text
[b]bold text
[color=#e74c3c]red text
default text[/color][/b][/quote]
```

**System information (please complete the following information)**
- Joomla version: 3.9.28-dev
- Kunena version: 5.2.5 and 5.2.6-DEV
- Kunena template name and version: Crypsis and Blue Eagle 1.6.5-dev
- Php version: 7.4.19 and 8.0.6
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by baticag** [comment]
Same happening here.

**Comment by Ruud68** [comment]
related: #8166

**Comment by rich20** [comment]
Solved by this fix https://github.com/Kunena/Kunena-Forum/pull/8202
