### ISSUE TITLE
All content below an image link will removes on edit

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8176]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/161839-auto-embed-youtube-videos,-external-image-url-and-edit-topic
(I've tested it and confirm it)

**To Reproduce**

- Enter an image url like` [img]image-address[/img]`
- Enter text or some others below the image link
- Submit and then edit the  message  (or switch  between Normal and Source mode)

**Actual result**
All content below the image link will remove

**System information (please complete the following information)**
- Joomla version: 3.9.28-dev
- Kunena version: 5.2.5 and 5.2.6-DEV
- Kunena template name and version: Crypsis and Blue Eagle 1.6.5-dev
- Php version: 7.4.19 and 8.0.6
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by baticag** [comment]
Happening to us also.

**Comment by Ruud68** [comment]
related: #8166

**Comment by rich20** [comment]
Solved by this fix https://github.com/Kunena/Kunena-Forum/pull/8202
