### ISSUE TITLE
Wysiwyg: Remove attachment from message, duplicates the code tags

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8228]
**To Reproduce**

- Insert an- or more images to a message
- Remove an- or all images

**Result**
- [ ] Insert or Insert All image needs 2 clicks
- [ ] If you remove images, it adds additional the image code into the message, in place of remove the code

**Comment by xillibit** [comment]
With CKeditor i'am not able to reproduce the issue

**Comment by rich20** [comment]
This problem occurred only with Wysiwyg. After this editor was deactivated, so I think, this problem is no longer relevant.
