### ISSUE TITLE
Notice: Undefined variables

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#8234]
Notice: Undefined variable: results in C:\Users\schum\GitHub\kunena\src\libraries\kunena\database\object\finder.php on line 229

Notice: Undefined variable: count in C:\Users\schum\GitHub\kunena\src\libraries\kunena\database\object\finder.php on line 277

Notice: Undefined variable: count in C:\Users\schum\GitHub\kunena\src\libraries\kunena\database\object\finder.php on line 277

**Comment by xillibit** [comment]
Where did-you see that ?

**Comment by 810** [comment]
Unread page

**Comment by xillibit** [comment]
I'am not able to see these errors

**Comment by rich20** [comment]
> I'am not able to see these errors

I also cannot reproduce it
