### ISSUE TITLE
[6.0-BETA 1] Error when trying to create category

### ISSUE THREAD

**Issue by C-Lodder** [Kunena/Kunena-Forum#8238]
**To Reproduce**
1. Go to `administrator/index.php?option=com_kunena&view=categories`
2. Click on `New Category`
3. Enter a name
4. Click `Save`

**Actual result**
The category is created, but it also returns an error on the page:

> Return value of Kunena\Forum\Libraries\Forum\Category\KunenaCategory::addAlias() must be of the type bool, none returned

**Screenshots**
![Screenshot 2021-07-21 at 06-56-05 Error 0](https://user-images.githubusercontent.com/2019801/126438377-f308850e-3871-4195-bbe2-c41d67948914.png)

**System information (please complete the following information)**
Joomla version: 4.0-dev (latest git)
Kunena version: 6.0 BETA 1
Php version: 7.4.4

**Comment by xillibit** [comment]
I'am not able to reproduce this issue with lastest changes in the branch
