### ISSUE TITLE
Quick Reply and go to editor - it only keeps the content if you use the button at the last message on each side

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8243]
**To Reproduce**
1. Go to a topic
2. Click at any post on Quick Reply
3. Write something and click on Go to editor

**Result**
It keeps only the content, if you use the Quick Reply button of the last message on each side. It happens with both editor (tested with CKE and BBCode editor). 

**System information (please complete the following information)**
- Joomla version: 3.9.29-dev and 10.0-rc2-dev
- Kunena version: 5.2.6 and 5.2.7-DEV
- Kunena template name and version: Crypsis and Blue Eagle 1.6.5-dev
- Php version: 7.4.19 and 8.0.6
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
I have tested with CKeditor, i have wrote something in the quick reply then when i click on Go to editor it keeps the content 

It's what is expected to keep the content

**Comment by rich20** [comment]
> It keeps only the content, if you use the Quick Reply button of the last message on each side.

Test it before the last message of a page
