### ISSUE TITLE
Rendering Error when setting Show Moderators in Category Index

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8250]
**Describe the bug**
Show Moderators in Category Index (it's default setting)
Choose a user as Moderator an go to the Index

**Result**
Rendering Error in layout Category/Index: Argument 2 passed to KunenaProfileKunena::getProfileURL() must be of the type string, null given, called in /.../libraries/kunena/src/User/KunenaUser.php on line 1148 in /.../components/com_kunena/template/aurelia/layouts/category/index/default.php on line 214
Layout was rendered in /.../components/com_kunena/template/aurelia/pages/category/list/default.php on line 27

**System information**
- Joomla version: 4.0.0-rc6-dev
- Kunena version: 6.0.0-BETA2-GIT
- Kunena template name and version: Aurelia
- Php version: 7.4.19 and 8.0.7 
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
~~i'am not able to reproduce this issue~~ i can reproduce it now
