### ISSUE TITLE
Default Type Quickreply puts a modal background over the page

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8257]
**Describe the bug**

- Use Quick Reply Default
- If you click on Quick Reply puts a modal background over the page and you must refresh, otherwise you can do nothing.

**System information**
- Joomla version: 4.0.0-rc6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template name and version: Aurelia
- Php version: 7.4.19 and 8.0.7 
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
The problem is still here. Why you have closed ?

**Comment by xillibit** [comment]
New issue : https://github.com/Kunena/Kunena-Forum/issues/8257
