### ISSUE TITLE
Trying to publish a Kunena plugin breaks the complete web page

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8286]
**Describe the bug**
Trying to publish a Kunena plugin like Gravatar, Community, it breaks the complete web page. The only way to call the page again, if you remove the plugin from the database.

**Actual result**
Fatal Error
in /.../plugins/kunena/community/community.php (line 87)
`     */    public function onKunenaGetLogin(): ?KunenaLoginCommunity    {        if (!$this->params->get('login', 1))        {            return;        }        return new KunenaLoginCommunity($this->params);    }`

**Additional context**
This error exists with these plugins:

in /.../plugins/kunena/altauserpoints/altauserpoints.php (line 101)
in /.../plugins/kunena/community/community.php (line 87)
in /.../plugins/kunena/gravatar/gravatar.php (line 55)

0 plgKunenaComprofiler::__construct(): Argument #2 ($config) must be of type object, array given, called in /.../libraries/src/Extension/ExtensionManagerTrait.php on line 242

**System information**
- Joomla version: 4.0.0-rc6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19 and 8.0.7 
- Database version: Server-Version: 10.4.19-MariaDB and 10.5.10-MariaDB-1:10.5.10

**Comment by xillibit** [comment]
i's not totally fixed, when enabled community plugin by example and if Jomsocial isn't installed you have some errors

**Comment by rich20** [comment]
**Two plugins are not instalable** (therefore fails the nightly build installation).

**Gravatar** (there is no class.php in ...src > plugins > plg_kunena_gravatar)

JInstaller: :Install: File does not exist /.../tmp/install_610bd97a55d5f/plg_kunena_gravatar/class.php
Plugin Update: Could not copy files from the source.

**Easyblog**
JInstaller: :Install: File does not exist /.../tmp/install_610bd81bddfda/plg_kunena_easyblog/index.html
Plugin Install: Could not copy files from the source.

**Comment by xillibit** [comment]
The next part is here : https://github.com/Kunena/Kunena-Forum/issues/8291
