### ISSUE TITLE
Topic pagination: 404 View not found [name, type, prefix]: topic, html, site

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8311]
**To Reproduce**

- Choose a low number for Messages Per Page (if there is no topic with multiple pages)
- Go in the frontend to Recent Topics
- Open a topic with more than one page
- You see an address like .../forum/test-category/7-poll-test
- Go to the next page
- Now ist the address  .../component/kunena/test-category/7-poll-test?defaultmenu=211&Itemid=101&start=3
- Go back to the first page
- The address is now .../?defaultmenu=211&catid=2&view=topic&id=7&layout=default&start=0 and you get an error 404

**Call stack
 | Function | Location**
1 | () | JROOT/libraries/src/MVC/Controller/BaseController.php:898
2 | Joomla\CMS\MVC\Controller\BaseController->getView() | JROOT/libraries/src/MVC/Controller/BaseController.php:641
3 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_content/src/Controller/DisplayController.php:125
4 | Joomla\Component\Content\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
6 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/components/com_content/src/Dispatcher/Dispatcher.php:55
7 | Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
8 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:206
9 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:245
10 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
12 | require_once() | JROOT/index.php:32

**Additional context**
I think, it's related to this bug: https://github.com/Kunena/Kunena-Forum/issues/8190

**System information**
- Joomla version: 4.0.0-rc6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.7 
- Database version: 10.4.19-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Comment by xillibit** [comment]
@mahagr : do-you have an idea about this bug ?

**Comment by rich20** [comment]
It seems to be  a conflict between Joomla Home and the menu item Kunena Home. I've noticed, when is selected Kunena Home as parent Home, all navigation problems are gone.
I think, the Kunena menu item Home is the problem and need a repair (see also here: https://github.com/Kunena/Kunena-Forum/issues/8164 ).
<br />
![Bildschirmfoto von 2021-10-28 16-28-41](https://user-images.githubusercontent.com/888847/139285348-86eb9486-b2cd-4d11-8102-2c82babdd645.png)

**Comment by xillibit** [comment]
I have tried to set on "Home" like on your screenshot but it's even worse, i lost the kunena menu when i go on the forum on frontend

**Comment by rich20** [comment]
Solved by this fix https://github.com/Kunena/Kunena-Forum/pull/8705
