### ISSUE TITLE
Loading external icons reduces the size of the forum pages by about half

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8313]
**To Reproduce**

- Choose in Aurelia Load external icons = Yes 
- Go in the frontend to the Forum and you se the issue

**System information**

- Joomla version: 4.0.0-rc7-dev and 4.1.0-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.7 
- Database version: 10.4.19-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-lo

**Desktop**
- OS Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment]
> Choose in Aurelia Load external icons = Yes

Which icons should be loaded with this option?

**Comment by xillibit** [comment]
It's load that : netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css

**Comment by rich20** [comment]
Do we still need this when glyphicons and bootstrap 4 symbols respectively are no longer supported?
