### ISSUE TITLE
The bar for selectable topic icons lacks in the editor

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8324]
**Describe the bug**
Also, when selectable Topic icons are allowed, there is no icon bar, indifferent which symbols you use (bootstrap5 or font awesome)

**System information**
- Joomla version: 4.0.1-dev and 4.1.0-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.9 
- Database version: 10.4.20-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I don't understand exactly the problem

**Comment by rich20** [comment]
When selectable topic icons are allowed, you should have the topic icon bar in the editor.
<br />
![Bildschirmfoto von 2021-08-22 21-17-05](https://user-images.githubusercontent.com/888847/130367451-1c4b3c69-8e13-4d89-a8a4-eeda44f3b231.png)

**Comment by rich20** [comment]
If you create a new topic, it lacks this topic icon bar

![Bildschirmfoto von 2021-11-19 17-48-01](https://user-images.githubusercontent.com/888847/142661098-7a98b912-25a7-4e6a-9993-135b6ab77cc5.png)
