### ISSUE TITLE
Confusing sorting in the category manager

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8342]
https://www.kunena.org/forum/k-6-0-support/162461-change-order-categories
**Describe the bug**
It always inserts new sections or categories at the highest position. This sorting cannot be changed (see image).
Also, you can't see subordinate categories because they are not indented. Indented works only with the sample data or in the first section but not for sub categories.
**Note**: Everything is displayed correctly in the frontend, <br />
![g3442](https://user-images.githubusercontent.com/888847/130482015-b57e90e2-e2fa-465a-8061-643807c91d1d.png)
<br />
**System information**
- Joomla version: 4.0.1-dev and 4.1.0-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.9 
- Database version: 10.4.20-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by AliciaRaven** [comment]
I also see this.
The frontend drop down category lists also seem to treat all subcategories as top level appart from 3 of the 4 sub categories of my second top level category. I have compared the entries in the database and see no difference between sub categories that are showing under their top level category and all the others that just get listed as top level in the drop down list.

**Comment by rich20** [comment]
Is fixed now: https://github.com/Kunena/Kunena-Forum/commit/8a81f2a23bbd916f7cb620893896be7cfcb7f06b
