### ISSUE TITLE
Super user, Admins and Global Moderators can ban himself

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8343]
**Describe the bug**

- Log in the frontend as Super User
- Ban an user from the site

**Result**
The user and yourself are banned, and you can't log in the backend anymore.
Message:
Login denied! Your account has either been blocked or you have not activated it yet.

**System information**
- Joomla version: 4.0.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.9 
- Database version: 10.4.20-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Fixed by commit : https://github.com/Kunena/Kunena-Forum/commit/145c5fedaa368ba07b9275adca04c6df3273fd28
