### ISSUE TITLE
Click on green New indicator: 404 View not found [name, type, prefix]: topic, html, site

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8344]
**Describe the bug**

Go to Recent Topics and click on the green New indicator (if you have an unread topic)
If you click on the green New indicator, it's in principle the same problem as here: https://github.com/Kunena/Kunena-Forum/issues/8311

**Result**

Call stack

# | Function | Location
1 | () | JROOT/libraries/src/MVC/Controller/BaseController.php:898
2 | Joomla\CMS\MVC\Controller\BaseController->getView() | JROOT/libraries/kunena/src/Controller/KunenaController.php:426
3 | Kunena\Forum\Libraries\Controller\KunenaController->display() | JROOT/libraries/kunena/src/Controller/KunenaController.php:342
4 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:233
5 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:113
6 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:206
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:245
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
11 | require_once() | JROOT/index.php:32

</div>

**Comment by xillibit** [comment]
When i click on UNREAD item on recent topics page i don't have this kind of issue

**Comment by rich20** [comment]
It's not the Unread item where occur the error. The error occur, if you click on the green indicator "New".

**Comment by xillibit** [comment]
I'am not able to reproduce it now

**Comment by rich20** [comment]
This, and similar errors, have been reported several times in the meantime.
These all have something to do with the navigation.
Select Direct Component Access = No in the configuration and try an answer in a topic. You will get a similar error.
As long as not everything works with the setting Direct Component Access = No, we will not get rid of the navigation problems.  Also not, when Direct Component Access is allowed.

**Comment by rich20** [comment]
I have now tested it with a redirect in the .htaccess. 
```
# Kunena URL redirect
RewriteEngine on
Redirect 301 /joomla4/component/kunena/ http://localhost/joomla4/forum/
```
With this workaround the navigation works everywhere without errors, even if direct component access is not allowed.
But the error with the green indicator remain. So has this error nothing to do with the navigation.

**Comment by xillibit** [comment]
When i enable sef and i set direct component access on no, the 404 error coming from the method which check the access in the dispatcher of Kunena : 

![image](https://user-images.githubusercontent.com/876395/146797418-86c01354-8983-417c-af94-9bcd8e5b8103.png)

When the Kunena menu are disappear it's normal to have this error

**Comment by rich20** [comment]
> When i enable sef and i set direct component access on no, the 404 error coming from the method which check the access in the dispatcher of Kunena

With this setting you can not do anything in the forum. You can't reply, no quote, not even the "Thank you" button works.

**Comment by rich20** [comment]
This error is still present and was also reported by another user.
https://www.kunena.org/forum/k-6-0-support/163877-404-error-reading-unread-items

**Comment by xillibit** [comment]
I'am not able to reproduce it anymore

**Comment by rich20** [comment]
@xillibit What link do you see when you mouse over the green New indicator? For me it goes to
**.../forum/welcome-mat/17-topictitle/unread**

Maybe we get a responce of this user, if it's now solved on his page or not.
https://www.kunena.org/forum/k-6-0-support/163877-404-error-reading-unread-items

**Comment by xillibit** [comment]
Yes it's link like that and yes i have tried with direct component access on no and yes : /index.php/forum/category-general/14180-configuration-plugin/unread

The routing issue was when url starting by http://joomla-40-dev-kunena-60/index.php/component/kunena/

**Comment by rich20** [comment]
Without SEO the address:
.../index.php?option=com_kunena&view=topic&catid=2&id=17&**Itemid=1835**&layout=unread
The **itemid 1835** is the menu item for Kunena Home and I think, that's correct. No idea where the error is coming from.
