### ISSUE TITLE
Error on index page when selecting from dropdown category selector

### ISSUE THREAD

**Issue by sluc69** [Kunena/Kunena-Forum#8349]
**Describe the bug**
Index page -> select any item from the dropdown board selector

**To Reproduce**
1. Go to 'index page'
2. Click on 'board categories'
3. select any item from the dropdown
4. See error '500 Joomla\CMS\MVC\Controller\FormController::__construct: Can't get or parse class name.'

**Expected behavior**
board category selected

**Actual result**
error: 500 Joomla\CMS\MVC\Controller\FormController::__construct: Can't get or parse class name.

**Screenshots**
![image](https://user-images.githubusercontent.com/82952282/130599996-815845c9-db4c-46ba-bbb7-fe6f9fa1d3ce.png)

**System information (please complete the following information)**

Joomla version:  4.0.0
Kunena version: 6 rc1
Kunena template name and version: default
Php version: 7.4
Database version: 5.6.

**Comment by xillibit** [comment]
It was a mistake we haven't release a RC1 of Kunena 6.0 but we have a beta1 and beta2, so try with beta2 instead

**Comment by xillibit** [comment]
Don't exist anymore in beta2
