### ISSUE TITLE
 User manager: User log out does not work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8355]
**Describe the bug**
Go in the backend to the Kunena user manager
Mark a user
Click on top the button Logout

**Result**
COM_KUNENA_A_USER_LOGOUT_DONE
But the user remain logged in

**System information**
- Joomla version: 4.0.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.9 
- Database version: 10.4.20-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Not able to reproduce it the user is right logout

**Comment by rich20** [comment]
You're right, this bug does not exist anymore, so I close this ticket.
