### ISSUE TITLE
Logs and Statisics remain empty

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8362]
**Describe the bug**

- Select in the configuration (tab Users) Define if you want to log action or moderation = Yes
- Take a moderator action like delete a topic, or ban a user

**Result**
Logs and Statisics remain empty

**System information**
- Joomla version: 4.0.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19, 8.0.6 and 8.0.9 
- Database version: 10.4.20-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by 810** [comment]
closing this one for duplicated issues open.
