### ISSUE TITLE
Guest post error

### ISSUE THREAD

**Issue by sluc69** [Kunena/Kunena-Forum#8368]
**Describe the bug**
Configured allowing guest to post topics. (public board)

**To Reproduce**
Configured allowing guest to post topics.
Create a New Topic (click button)
 See error: The requested page can't be found.
![image](https://user-images.githubusercontent.com/82952282/131208057-5d6bd5cc-8006-4e42-a6a3-6a7d50291c46.png)

**Expected behavior**
Open the messgae editor

**System information (please complete the following information)**

Joomla version: 4.0.2
Kunena version: 6 beta2 (nightly)
Kunena template name and version: default
Php version: 7.4.3
Database version: 8.0.26-0ubuntu0.20.04.2

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser edge, chrome, firefox, sidekick
 - Version: latest

joomla logfile:
2021-08-28T05:43:23+00:00	DEBUG 192xxxxx0	kunena	Redirect from /index.php/public-board/topic/create (101) to /index.php/forum/public-board/topic/list (143)
2021-08-28T05:43:23+00:00	CRITICAL 192.xxxx0	error	Uncaught Throwable of type Exception thrown with message "View not found [name, type, prefix]: topic, html, site". Stack trace: #0 /var/www/j4/libraries/kunena/src/Controller/KunenaController.php(426): Joomla\CMS\MVC\Controller\BaseController->getView()
#1 /var/www/j4/libraries/kunena/src/Controller/KunenaController.php(342): Kunena\Forum\Libraries\Controller\KunenaController->display()
#2 /var/www/j4/libraries/kunena/src/Controller/KunenaController.php(233): Kunena\Forum\Libraries\Controller\KunenaController->executeTask()
#3 /var/www/j4/components/com_kunena/src/Dispatcher/Dispatcher.php(113): Kunena\Forum\Libraries\Controller\KunenaController->execute()
#4 /var/www/j4/libraries/src/Component/ComponentHelper.php(389): Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch()
#5 /var/www/j4/libraries/src/Application/SiteApplication.php(206): Joomla\CMS\Component\ComponentHelper::renderComponent()
#6 /var/www/j4/libraries/src/Application/SiteApplication.php(245): Joomla\CMS\Application\SiteApplication->dispatch()
#7 /var/www/j4/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#8 /var/www/j4/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#9 /var/www/j4/index.php(32): require_once('/var/www/j4/inc...')

**Comment by rich20** [comment]
> Kunena version: 6 beta2 (nightly)

Please try it with the beta3 nightly,

**Comment by rich20** [comment]
Hmm.. I see now on your image, it's the same error message as here: https://github.com/Kunena/Kunena-Forum/issues/8344
Does the error occur with topics that are displayed as unread?

**Comment by xillibit** [comment]
I'am not able to reproduce it

**Comment by rich20** [comment]
I'm also not able to reproduce this error. 
But also a guest topic or message shows the unread indicator for registered users.
It is exactly the same error message (bug) as here: https://github.com/Kunena/Kunena-Forum/issues/8344 
Therefore, I don't think it's a guest message bug, the error occurs when you try to open an unread message via the unread indicator or the left topic symbol.

**Comment by xillibit** [comment]
I'am able to reproduce the issue with direct component access set on no, but it give now the same 404 error than this one : https://github.com/Kunena/Kunena-Forum/issues/8344#issuecomment-998062510

**Comment by rich20** [comment]
> I'am able to reproduce the issue with direct component access set on no, but it give now the same 404 error than this one : https://github.com/Kunena/Kunena-Forum/issues/8344#issuecomment-998062510

I think this error no longer exists, I can't reproduce it.

**Comment by xillibit** [comment]
Re-open an new issue if it's still exists
