### ISSUE TITLE
Aurelia ICON type set to bootstrap 5 cause errors

### ISSUE THREAD

**Issue by sluc69** [Kunena/Kunena-Forum#8369]
**To Reproduce**
1. Go to template configuration Aurelia
2. Menu FEATUERS
3. Set ICON TYPE to BOOTSTRAP 5

**Actual result**
![image](https://user-images.githubusercontent.com/82952282/131208324-97f8da7f-38da-4d72-888c-3efbe7146e0c.png)

**System information (please complete the following information)**

Joomla version: 4.0.2
Kunena version: beta2 nightly
Kunena template name and version: aurelia
Php version: 7.4.3
Database version: 8.0.26-0ubuntu0.20.04.2

**Comment by rich20** [comment]
> Kunena version: beta2 nightly

Please try it with the beta3 nightly, this issue should be already solved

**Comment by sluc69** [comment]
I installed the nightly builds, still the same.
You should install from a clean environment

**Comment by 810** [comment]
for me its working, can you check your file permissions.

Looks like you are missing the svg icons on media\kunena\core\svg

**Comment by 810** [comment]
try also to edit the template on backend, and save it, we don't have B5 icons anymore.
