### ISSUE TITLE
Only a small blemish: It lacks a space in the user Profile -> Edit (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8371]
https://github.com/Kunena/Kunena-Forum/issues/8354
**Describe the bug**
We need an own language code for profile edit, otherwise we have another blemish. <br />
![Bildschirmfoto von 2021-08-28 17-34-59](https://user-images.githubusercontent.com/888847/131223744-fa1b8a43-4b42-41cd-91aa-33ee3668f3ed.png)
Should be:
COM_KUNENA_USER_PROFILE = "Profile for" 
COM_KUNENA_USER_PROFILE_EDIT = "Profile for %s" 

 https://github.com/Kunena/Kunena-Forum/blob/3a0c6a1ac28a2fce0b60a6293feae576a630a6b8/src/site/language/en-GB/en-GB.com_kunena.templates.ini#L339

https://github.com/Kunena/Kunena-Forum/blob/3a0c6a1ac28a2fce0b60a6293feae576a630a6b8/src/site/template/aurelia/layouts/user/edit/default.php#L34
should be
`<?php echo Text::sprintf('COM_KUNENA_USER_PROFILE_EDIT', $this->escape($this->profile->getName())); ?> 
`

**Comment by xillibit** [comment]
why do-you want do that ?

**Comment by rich20** [comment]
Because it shows only on Profile Edit correct. But in the profile itself you see the characters %s
![Bildschirmfoto von 2021-08-28 17-34-59](https://user-images.githubusercontent.com/888847/131223744-fa1b8a43-4b42-41cd-91aa-33ee3668f3ed.png)
