### ISSUE TITLE
Warning when Smart Auto Linking is enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8377]
**To Reproduce**

- Choose in the configuration (tab BBCode) Smart Auto Linking = Yes
- Add a link in a message and submit the post

**Result**
You see this warning in the message:
Warning: file_get_contents(https://www.kunena.org/): Failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests in libraries/kunena/bbcode/bbcode.php on line 372

**System information**
- Joomla version: 3.10.1-dev
- Kunena version: 5.2.6 and 5.2.7-DEV
- Kunena template name and version: Crypsis and Crypsisb3
- Php version: 7.4.19 and 8.0.6
- Database version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I'am not able to reproduce it

**Comment by rich20** [comment]
Maybe a php problem? I've tested it now, I get the error with php 8.0.6.

**Comment by rich20** [comment]
Try reloading the post a few times. I noticed that every now and then the link loads correctly.

**Comment by xillibit** [comment]
~~I have tried too with php 8.0.x no issue neither, i have tried to reload a few times the page. What kind of link do-you have in the message ?~~

I get it now

**Comment by xillibit** [comment]
When putting link to kunena.org you have this error, it's just a limit on server on kunena.org side

**Comment by rich20** [comment]
Yes, I've linked to k.org
So we can close this issue?
