### ISSUE TITLE
Kunena Beta3 plugins language files exchanged

### ISSUE THREAD

**Issue by Leen29** [Kunena/Kunena-Forum#8387]
I notice that the language files in
plg_kunena_community_v6.0.0-BETA3-DEV.zip
plg_kunena_comprofiler_v6.0.0-BETA3-DEV.zip
have been exchanged 
ps
the contents of the files seem swapped

**Comment by rich20** [comment]
The plg_kunena_community = JomSocial 
https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/plugins/plg_kunena_community/language/en-GB/en-GB.plg_kunena_community.sys.ini <br />
The plg_kunena_comprofiler = CommunityBuilder
https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/plugins/plg_kunena_comprofiler/language/en-GB/en-GB.plg_kunena_comprofiler.sys.ini

It is the same in Kunena 5.2. Is that what you mean?
<br />
![path1101](https://user-images.githubusercontent.com/888847/132349251-08f586e9-5534-44b1-8003-219f8739613f.png)

**Comment by Leen29** [comment]
Hi,
I may not be able to explain well but the contents of the language file
language\en-GB\en-GB.plg_kunena_comprofiler.sys.ini
so belongs to
  language\en-GB\en-GB.plg_kunena_community.sys.ini
and otherwise also

**Comment by xillibit** [comment]
I don't see neither why the content of language\en-GB\en-GB.plg_kunena_comprofiler.sys.ini should be belongs to
language\en-GB\en-GB.plg_kunena_community.sys.ini

Can-you said what kind of thing which make you see see something like that ?

**Comment by Leen29** [comment]
maybe the translation rules or am I not seeing that correctly.? 
![inhoud-comproefiel](https://user-images.githubusercontent.com/17086048/132453603-75b4d1d1-8438-4508-9d2a-69f6f10443d7.jpg)
![inhoud-community](https://user-images.githubusercontent.com/17086048/132453627-68573269-b1c8-4ca2-a770-388cb361c549.jpg)

**Comment by rich20** [comment]
The files and translations are correct.  The word "Community" does not mean the CommunityBuilder.

The plg_kunena_**community = JomSocial**
The plg_kunena_**comprofiler = CommunityBuilder**

I think the confusion comes from the fact, that the names of all plugins are hard coded.

It should actually be displayed like this:
plg_kunena_community -> **Kunena - JomSocial Integration**
plg_kunena_comprofiler -> **Kunena - Community Builder Integration**

**Comment by Leen29** [comment]
ok then I misunderstood thanks for the explanation
