### ISSUE TITLE
[CKEditor] Line break shows the html code in the message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8389]
**Describe the bug**
Write a text with line break and submit the post.

**Result**
![path1159](https://user-images.githubusercontent.com/888847/132734853-90cdc623-914f-4dda-94de-b3aaeea3c0ba.png)

**System information**
- Joomla version: 3.10.2-dev
- Kunena version: 5.2.7-DEV
- Kunena template name and version: Crypsis
- Php version: 7.4.19 and 8.0.6
- Database version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment]
Hmm... I see now, this occurs with all codes.
![Bildschirmfoto von 2021-09-09 19-52-01](https://user-images.githubusercontent.com/888847/132737729-c8fb16b5-0b55-4444-a738-92aac22e671c.png)

**Comment by xillibit** [comment]
It seems the bbcode plugin of ckeditor was missing when i have done the update to 4.16.2
