### ISSUE TITLE
Upgrade from K5.2 with exists statistics to K6.0 results in errors

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8410]
**Describe the bug**
Upgrade K5.2 which contain Kunena statistics to K6.0
Go in the backend to Kunena -> Statistics

**Result**
Instead of the statistics, there are these three errors for each entry

Warning: Attempt to read property "user_id" on int in /.../administrator/components/com_kunena/src/Model/StatisticsModel.php on line 241

Warning: Undefined array key "" in /.../administrator/components/com_kunena/src/Model/StatisticsModel.php on line 241

Warning: Attempt to read property "operation" on int in /.../administrator/components/com_kunena/src/Model/StatisticsModel.php on line 243

**System information**
- Joomla version: 4.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19 and 8.0.10 
- Database version: 10.4.21-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Tried on upgrade from K5.2 i don't see these errors on statistics in backend
