### ISSUE TITLE
Upgrade from K5.2 with exists Logs to K6.0 results in errors

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8411]
**Describe the bug**
Upgrade K5.2 which contain Kunena Logs to K6.0
Go in the backend to Kunena -> Logs

**Result**
<blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kunena\Forum\Administrator\View\Logs\HtmlView::getType(): Argument #1 ($id) must be of type int, null given, called in /.../administrator/components/com_kunena/tmpl/logs/default.php on line 272</blockquote><div style="box-sizing: border-box; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack

 | Function | Location
1 | () | JROOT/administrator/components/com_kunena/src/View/Logs/HtmlView.php:231
2 | Kunena\Forum\Administrator\View\Logs\HtmlView->getType() | JROOT/administrator/components/com_kunena/tmpl/logs/default.php:272
3 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
4 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:218
5 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Logs/HtmlView.php:112
6 | Kunena\Forum\Administrator\View\Logs\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:692
7 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:66
8 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
10 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
14 | Joomla\CMS\Application\CMSApplication->execut() | JROOT/administrator/includes/app.php:63
15 | require_once() | JROOT/administrator/index.php:32
</div>

**System information**
- Joomla version: 4.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19 and 8.0.10 
- Database version: 10.4.21-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Is-it fixed ?

**Comment by rich20** [comment]
<blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; display: inline-block; padding: 0.3rem 0.2rem; font-size: 0.75rem; font-weight: 700; line-height: 1; color: rgb(255, 255, 255); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.2rem; background-color: rgb(73, 80, 87) !important; margin-bottom: 0px;">0</span><span> </span>Kunena\Forum\Administrator\View\Logs\HtmlView::getType(): Argument #1 ($id) must be of type int, null given, called in /opt/lampp/htdocs/joomla4/administrator/components/com_kunena/tmpl/logs/default.php on line 299</blockquote><div style="box-sizing: border-box; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack
--
# | Function | Location
1 | () | JROOT/administrator/components/com_kunena/src/View/Logs/HtmlView.php:231
2 | Kunena\Forum\Administrator\View\Logs\HtmlView->getType() | JROOT/administrator/components/com_kunena/tmpl/logs/default.php:299
3 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
4 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:218
5 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Logs/HtmlView.php:112
6 | Kunena\Forum\Administrator\View\Logs\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:692
7 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:66
8 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
10 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
15 | require_once() | JROOT/administrator/index.php:32

</div>

**Comment by 810** [comment]
same issue as on stats, all is null
