### ISSUE TITLE
Error in the template manager - Table template not supported.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8417]
**To Reproduce**

- Go to Kunena -> Templates
- Mark the checkbox of Aurelia
- Click on button Edit

**Actual result**
<blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span> </span>Table template not supported. File not found.</blockquote><div style="box-sizing: border-box; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/MVC/Model/BaseDatabaseModel.php:247
2 | Joomla\CMS\MVC\Model\BaseDatabaseModel->getTable() | JROOT/libraries/src/MVC/Controller/FormController.php:371
3 | Joomla\CMS\MVC\Controller\FormController->edit() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
4 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
5 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
6 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
7 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
8 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
10 | require_once() | JROOT/administrator/index.php:32
</div>

**System information**
- Joomla version: 4.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.19 and 8.0.10 
- Database version: 10.4.21-MariaDB and 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I don't have this error with the last changes

**Comment by rich20** [comment]
I have no idea which differences are in our installations. I've today created a complete new Joomla page and installed the nightly build Kunena | 2021-09-19 [ Git Repository ]. It contains exactly the same error.

**Comment by xillibit** [comment]
I have changed couple of things in this area in my last PR, so wait a new build to try
