### ISSUE TITLE
Error during the installation: Message - Duplicate column name

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8424]
**Describe the bug**
https://www.kunena.org/forum/k-6-0-support/162764-install-pkg_kunena_v6-0-0-beta4-dev_2021-09-18-zip
Confirmed

**To Reproduce**
Install v6.0.0-BETA4-_2021-09-18 (Kunena | 2021-09-19 [ Git Repository ])
At the end of the installation you get the message::

Duplicate column name 'sampleData'
Error installing package

Now go to the frontend
**The Forum is currently offline for maintenance**

**Comment by xillibit** [comment]
So only when update from k5.2 ?

**Comment by rich20** [comment]
No, on a new installation you get this error.
