### ISSUE TITLE
User manager: Add moderator result in an error

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8427]
**To Reproduce**
Go to the user mannager and try to add a user as moderator

**Actual result**

Exception throw at line 189 in file /opt/lampp/htdocs/joomla4/libraries/kunena/src/Tables/KunenaTable.php with message Field 'params' doesn't have a default value

An error has occurred.
0 Kunena\Forum\Libraries\Forum\Category\User\KunenaCategoryUser::save(): Return value must be of type bool, null returned

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Forum/Category/User/KunenaCategoryUser.php:203
2 | Kunena\Forum\Libraries\Forum\Category\User\KunenaCategoryUser->save() | JROOT/libraries/kunena/src/Access/KunenaAccess.php:528
3 | Kunena\Forum\Libraries\Access\KunenaAccess->setModerator() | JROOT/administrator/components/com_kunena/src/Controller/UserController.php:236
4 | Kunena\Forum\Administrator\Controller\UserController->setModerate() | JROOT/administrator/components/com_kunena/src/Controller/UserController.php:171
5 | Kunena\Forum\Administrator\Controller\UserController->saveInternal() | JROOT/administrator/components/com_kunena/src/Controller/UserController.php:87
6 | Kunena\Forum\Administrator\Controller\UserController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
13 | require_once() | JROOT/administrator/index.php:32

**Comment by xillibit** [comment]
~~You set as moderator by editing an user ?~~

Found it need to set an user as moderator to a specific category, it works else as global moderator

**Comment by rich20** [comment]
I have found out the cause of this problem. It only occurs with users who have never logged in before in the forum (e.g. when have been created a new user in the backend).
This will happen rather rarely in practice.

**Comment by xillibit** [comment]
For me it happens even if the user has been loggued in Kunena in frontend

**Comment by rich20** [comment]
Go with this user in the profile -> edit and save it.

**Comment by rich20** [comment]
Try to go with this user to the profile -> edit and save it.
But I've also noticed, if you install Kunena new, the table #__kunena_users not automatically will filled (remain empty) and so you must synchronize the users first.

**Comment by xillibit** [comment]
I have edited the profile of user in frontend and saved it but i have still the error in backend when i want to set it as moderator

**Comment by rich20** [comment]
It seems to be a temporary error. I've tried now again with 2 different users, after login and save the profile it works. But it does not help, if you as admin his profile saves. This user must be logged in himself.
