### ISSUE TITLE
Removing Kunena via Tools - The Execute process button has no effect

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8435]
**Describe the bug**
https://www.kunena.org/forum/k-6-0-support/162763-removing-kunena-version-6-beta-3-4
Confirmed

Although, you can nevertheless remove Kunena by use the Enter key. So it's only a small issue but should be fixed too.

**Comment by xillibit** [comment]
it's weird because i had used couple of times lately the uninstall Kunena from tools and it's worked but i haven't checked all the times if the kunena tables was present

**Comment by rich20** [comment]
The tables has been correctly removed on all my tests. The option Remove Kunena itself seems to work correct.
It's only, you can do it not with the button "Execute the Process", you must use the Enter key of your keyboard instead. Therefore, I think, it's only a small issue.

**Comment by rich20** [comment]
Meanwhile, the user Leen who reported this bug has also confirmed that it works correctly with the Enter key.
