### ISSUE TITLE
Error install on J4.0.3

### ISSUE THREAD

**Issue by xhorizont** [Kunena/Kunena-Forum#8444]
JInstaller: :Install: Error SQL Specified key was too long; max key length is 767 bytes
Extension installation aborted.
Package Install: There was an error installing an extension: com_kunena_v6.0.0-BETA3.zip

**Comment by xillibit** [comment]
~~What is you mysql version ?~~

Found it, it happens for old mysql 5.6 and previous version, i will fix that for clean installation of Kunena 6.0 because the minimum mysql version supported by Joomla! 4.0 and Kunena 6.0 is mysql 5.6.x

**Comment by xillibit** [comment]
FYI : Mysql 5.6.x isn't supported except if you take paid support since february 2021 and it's advised to upgrade to Mysql 5.7 or later version
