### ISSUE TITLE
Aurelia want load for some action buttons glyphicon symbols

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8471]
**Describe the bug**

- Choose bootstrap 5 symbols (it's default)
- In Aurelia, select Show default actions = No
- Go to a topic

These glyphicons does not exist
.../media/kunena/core/svg/glyphicon glyphicon-envelope.svg 404
.../media/kunena/core/svg/glyphicon glyphicon-share-alt.svg 404
.../media/kunena/core/svg/glyphicon glyphicon-star-empty.svg 404
![Bildschirmfoto von 2021-09-30 00-24-57](https://user-images.githubusercontent.com/888847/135733750-d942efc7-a00f-4198-9d1d-8d23f6ac858c.png)

Correct would be:
.../media/kunena/core/svg/envelope.svg
.../media/kunena/core/svg/reply.svg
.../media/kunena/core/svg/star.svg

**Comment by rich20** [comment]
Addendum:
After subscribe and favorite it should change to:
.../media/kunena/core/svg/envelope-open.svg
.../media/kunena/core/svg/star-fill.svg.svg

**Comment by 810** [comment]
i have removed b5 try again.

**Comment by rich20** [comment]
It want still load the glyphicons.svg

.../media/kunena/core/svg/glyphicon glyphicon-envelope.svg 404
.../media/kunena/core/svg/glyphicon glyphicon-share-alt.svg 404
.../media/kunena/core/svg/glyphicon glyphicon-star-empty.svg 404

Only at the Moderation button it has added an icon now.
![Bildschirmfoto von 2021-10-03 02-46-39](https://user-images.githubusercontent.com/888847/135735648-bfea8147-5d87-4ae9-9440-8dfa0db5930e.png)

**Comment by rich20** [comment]
The symbols for these actions are correct now, but now it lacks symbols for other buttons.
![Bildschirmfoto von 2021-10-03 16-03-16](https://user-images.githubusercontent.com/888847/135757459-682a77cd-3691-472f-b0b3-c5ab8290c7d8.png)
