### ISSUE TITLE
[K6.0] Quick reply doesn't open modal when click

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#8472]
**Describe the bug**
 Quick reply doesn't open modal when click.  (Option quick reply: default)
 
 The modal stays hidden after click.

**Comment by xillibit** [comment]
It's the same that : https://github.com/Kunena/Kunena-Forum/issues/8257

**Comment by 810** [comment]
No, this is just the js issue.

The other one was a conflict with modal.

We need to show the js modal correctly by js. When i remove the inline css ``display:none``, then its showed correctly.

**Comment by rich20** [comment]
The modal itself works properly, when setting is Type Quickreply = Modal.
When setting Type Quickreply = Default, it should only open the quick reply text field below the message.

**Comment by 810** [comment]
Fixed by ecaeb0c
