### ISSUE TITLE
Wrong address for smileys

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8481]
**Describe the bug**
Enter a smiley code like B) or :) in a message and submit
Kunena wants to load the smileys from:
.../**smileys**/media/kunena/emoticons/smile.svg

**Result**
Only image placeholders are displayed 
![Bildschirmfoto von 2021-10-04 22-48-39](https://user-images.githubusercontent.com/888847/135923568-3583a3ae-5ecd-44a5-9466-b2efb6464fa4.png)

**Comment by rich20** [comment]
This fix has changed the ending from svg to png but the wrong prefix in the address still remain.
**smileys**/media/...
shoud be
<strike>smileys</strike>/media/...

**Comment by xillibit** [comment]
The path is now : /media/kunena/emoticons/cool.svg

**Comment by rich20** [comment]
Yes, I see it now. Has the KunenaBBCode.php been updated again, or it was my mistake? But it's indifferent, it works now correctly.

**Comment by xillibit** [comment]
Some smileys aren't displayed : 

![image](https://user-images.githubusercontent.com/876395/139579579-5a7ff015-4f21-4b1c-ad9e-7c97ea11d1e4.png)
