### ISSUE TITLE
 Links without definition text are not displayed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8501]
**Describe the bug**
Go to the first created message "Welcome to Kunena" and you see the issue.

This link will not displayed: `[url]https://www.kunena.org/[/url]`
This link works: `[url=https://www.kunena.org/]https://www.kunena.org/[/url]`
<br>
![Bildschirmfoto von 2021-10-23 22-47-20](https://user-images.githubusercontent.com/888847/138571513-0be85717-f385-4db6-bd89-511a205c9c22.png)

**System information**
- Joomla version: 4.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA4-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.23 and 8.0.11 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I don't see what you mean : 
![image](https://user-images.githubusercontent.com/876395/138572263-cae7a7ee-53e8-4856-81f9-5e1d23b90d77.png)

**Comment by rich20** [comment]
It seems, it's only on upgraded installations. On a new installation I see also not this problem.

**Comment by rich20** [comment]
I've tested it again. The error occur:
- [ ] If you upgrade a page to J4.0 and K6.0
- [ ] Or if you have already an upgraded page and you install the last build over it

**Comment by xillibit** [comment]
because you have keeped old sample data

**Comment by rich20** [comment]
It has nothing to do with example data. 

1. I've now installed new the last build from you, without sample data.
2. Then created a section and a category
3. Created a topic with such a link in the message
Result is `[url][/url]`
4. Installed an older worked build over it
Result: The link is correct
5. Upgraded again to the last build
Result: The link is gone again

**Comment by xillibit** [comment]
I have retried and i'am able to reproduce the issue in all cases (upgrade or not)

I have tried to compare with K5.2 but i don't found what it has changed on this side, on K5.2 it works
