### ISSUE TITLE
Rendering Error when Smart Auto Linking is enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8502]
**Describe the bug**

- Enable Smart Auto Linking (configuration -> tab BBCodes)
- Add a link in a message

**Result**
Rendering Error in layout Message/Item: Kunena\Forum\Libraries\BBCode\KunenaBBCode::get_title(): Return value must be of type string, none returned in .../components/com_kunena/template/aurelia/layouts/message/item/default.php on line 67
Layout was rendered in .../components/com_kunena/template/aurelia/layouts/topic/item/message/default.php on line 36

**System information**
- Joomla version: 4.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA4-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.23 and 8.0.11 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I'am not able to reproduce the problem. When i paste a link in the message and submit it doesn't appear. It appear only if i use the bbcode url option in toolbar

**Comment by xillibit** [comment]
Try if you have still the issue since this change : https://github.com/Kunena/Kunena-Forum/pull/8509 ?

With or without  Smart Auto Linking enabled, links without bbcode are showed as text : 

![image](https://user-images.githubusercontent.com/876395/139579333-cc575fe2-f4fa-4e7c-ab66-9e35b8376f25.png)

**Comment by rich20** [comment]
> With or without Smart Auto Linking enabled, links without bbcode are showed as text :

Confirmed
- [ ] Links without bbcode are showed as text
- [ ] Links with text definition - it shows only the link
This link (with bbcode)
`[url=https://www.kunena.org/]0000000000000000[/url]`
display this:
`https://www.kunena.org/`

**Comment by xillibit** [comment]
It's better with this fix : https://github.com/Kunena/Kunena-Forum/pull/8511

**Comment by rich20** [comment]
- [x] Links without bbcode are showed as text
- [ ] Rendering Error when Smart Auto Linking is enabled - still exists
- [ ] Links with text definition - it shows only the link
This link (with bbcode)
`[url=https://www.kunena.org/]0000000000000000[/url]`
display this:
`https://www.kunena.org/`
