### ISSUE TITLE
New installation: Smileys and rank images are missing if you do not install sample data

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8512]
The ranks are displayed in the frontend but are not available in the backend.
Smileys are missing in the front- and backend.

**System information**
- Joomla version: 4.0.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA4-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.23 and 8.0.11 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
On K5.2 and previous versions you haven't the choice you have all the time the sample data are installed, so when you don't install sample data you shouldn't have access to the ranks and smileys

**Comment by rich20** [comment]
If it is compelling to install the sample data, there should at least be a hint.
The second problem, on a new installation with sample data, you have an incomplete smiley list.

**Comment by xillibit** [comment]
Duplicate with : https://github.com/Kunena/Kunena-Forum/issues/9724
