### ISSUE TITLE
Conflict between Joomla user activation and Kunena?

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8514]
**Describe the bug**
https://www.kunena.org/forum/36-German/163207-6-0-0-beta4-git-system-plugin-fehler#219878
Confirmed

**To Reproduce**
Select in the Joomla user manager

1. Allow User Registration = Yes
2. New User Account Activation = Administrator

- Register a new user (via the frontend)
- Activate this user in the Joomla user manager

**Result**
Although the user will activated, there is this error message:
0 Argument 4 passed to plgSystemKunena::onUserAfterSave() must be of the type string, null given, called in /.../libraries/src/Plugin/CMSPlugin.php on line 285

**Comment by 810** [comment]
try now

**Comment by rich20** [comment]
- [x] Success
