### ISSUE TITLE
Upgrades from K5 do not work anymore

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8521]
**Describe the bug**
It shows no error during the upgrade, but there are no categories. The dashboard shows all as sections, but the Category manager is empty.
Also the rank manager is empty.
And in the user list it shows many errors such as: 

Notice: Undefined property: stdClass::$rankId in /.../libraries/vendor/joomla/database/src/DatabaseDriver.php on line 1382

Notice: Undefined property: stdClass::$rankSpecial in /.../libraries/kunena/src/User/KunenaUser.php on line 1843

Notice: Undefined property: stdClass::$rankTitle in /.../libraries/kunena/src/User/KunenaUser.php on line 1859

Notice: Undefined property: stdClass::$rankMin in /.../libraries/kunena/src/User/KunenaUser.php on line 1843

**System information**
- Joomla version: 4.0.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA4-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.23 and 8.0.11 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I'am not able to reproduce what you said, when i do an upgrade from K5.2, i have categories in category manager and i have ranks in ranks manager. I don't have such errors in users manager

**Comment by rich20** [comment]
I don't know what's the difference. I've tried it on different test pages with PHP 7.4.23 as well as with PHP 8.0.11.
With an older build it works, but not with the beta 5.
