### ISSUE TITLE
reply form not working

### ISSUE THREAD

**Issue by fabvincent** [Kunena/Kunena-Forum#8525]
**Describe the bug**
my reply to post form doesn't open up

**To Reproduce**
1. Go to 'https://www.sovdzo.com/component/kunena/materiel-perdu/topic?Itemid=101#kreply1_form'
2. Click on 'Reponse rapide' to participate
3. form doesn't appear

**Expected behavior**
Form should appear

**Actual result**
form to reply doesn't appear

**Screenshots**

**System information (please complete the following information)**

Joomla version: 4.0.4
Kunena version: 6.0.0-BETA4-GIT
Kunena template name and version: Pitech joomshapers
Php version: 7.4.11
Database version: 5.5.49-log 

**Desktop (please complete the following information):**
 - OS: mac
 - Browser firefox

**Comment by xillibit** [comment]
Thanks for the report, but your issue is already here : https://github.com/Kunena/Kunena-Forum/issues/8483
