### ISSUE TITLE
png and gif images will be changed to JPEG during upload

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8531]
**Describe the bug**
If you upload png or gif images, they will be changed to the image type JPEG. Indeed, the file ending png or gif remains, but when you check the image, it is of type JPEG. Instead of transparency is color and animations are not possible. 

**To Reproduce**
Upload a gif and png and check the image type after upload

**System information**
- Joomla version: 4.0.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA5-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.23 and 8.0.11 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by 810** [comment]
for me: PNG File (.png) and for gif: GIF File (.gif)

**Comment by rich20** [comment]
The file remains the same, but the file type changes and so animation or transparency is not possible.
![Bildschirmfoto von 2021-11-13 21-13-09](https://user-images.githubusercontent.com/888847/141657986-57df5f54-41db-4091-87f5-f79e6d175c18.png)

**Comment by 810** [comment]
![image](https://user-images.githubusercontent.com/876623/141658741-3432dacf-d3b4-4263-9882-7b7344d33c92.png)

**Comment by rich20** [comment]
Works for you if you upload an animated gif?

**Comment by xillibit** [comment]
I have tried with png with transparency, the transparency is replaced by black when uploaded : 
![image](https://user-images.githubusercontent.com/876395/141693121-8eff210f-8a60-4541-9b23-9892a5ad493a.png)

The png image on gimp before the upload : 

![image](https://user-images.githubusercontent.com/876395/141693141-201204f4-3ffb-4afb-bca4-f4836733ac7c.png)

**Comment by xillibit** [comment]
> Works for you if you upload an animated gif?

The gif is converted in jpg on upload. Even png are converted in jpg on upload
