### ISSUE TITLE
Changing the category alias keeps the old one active

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8543]
**Describe the bug**
https://www.kunena.org/forum/36-German/163354-fragen-zu-kategorien-und-alias-k6
Confirmed

If you change the category alias, the old one remains active and it is not possible to remove it (except in the database).
<br />
![Bildschirmfoto von 2021-11-15 18-25-47](https://user-images.githubusercontent.com/888847/141828279-8403e26a-ab71-42ea-b4d6-e1d6b2db95bf.png)

**System information**
- Joomla version: 4.0.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA5-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.23 and 8.0.11 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It seems it still exists : https://www.kunena.org/forum/k6-1-0-support-archive/168083-category-change-alias-bug-still-there

**Comment by xillibit** [comment]
Now with my fix https://github.com/Kunena/Kunena-Forum/commit/5539a34c400c981b8d05e76051923f17c2070710 if you uncheck them they are removed
