### ISSUE TITLE
Many options for the Dashboad are hard coded

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8556]
[/Kunena-Forum/src/admin/tmpl/cpanel/default.php](https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/admin/tmpl/cpanel/default.php)
If you search by the keyword class="mb-0 in this file, you get many hits with hardcoded results.
This is not the most important thing at the moment, but it should be changed at some point.

**Comment by rich20** [comment]
https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/admin/tmpl/cpanel/default.php

**Hard coded words and numbers**
- [ ] Line 189 - Today
- [ ] Line 242 - Last Edit: Welcome
- [ ] Line 292 - photo.png (topic id: 44343)
- [ ] The file count does not work, only the number 1 is displayed
- [ ] Line 397 - Groups
- [ ] Line 438 - 12
- [ ] Line 458 - 12
- [ ] Line 478 - 12

**Comment by xillibit** [comment]
It remains only the word Today hardcoded in the file
