### ISSUE TITLE
If used SCEditor: With every Kunena update the editor switches back to the CKEditor

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8563]
**System information**
- Joomla version: 4.0.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA6-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.25 and 8.0.12 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
In the nightly build available on kunena.org there is a params.ini present in Aurelia config directory but this file isn't present in K6.0 repository
