### ISSUE TITLE
QR and go to editor - Text is not transferred to the editor

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8582]
**Describe the bug**

- Enter a text in Quick Reply and go to the editor
- Text is not transferred to the editor

**System information**
- Joomla version: 3.10.4-dev
- Kunena version: 5.2.6 and 5.2.7-DEV
- Kunena template name and version: Crypsis and Blue Eagle 1.6.7-dev
- Php version: 7.4.25 and 8.0.10
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
How do-i need to do to reproduce this ?

**Comment by rich20** [comment]
Enter a text in Quick Reply field and go to the editor
