### ISSUE TITLE
Crypsisb4/b3:Change of the cat switches to legacy symbols (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8590]
**Describe the bug**
https://www.kunena.org/forum/k-5-2-support-archive/161444-no-category-structure-on-forum-home-page-after-installation#217280

**Hint: This happens only with the CKEditor**
**To Reproduce**

1. Choose in te tempate setting "Icon type = bootstrap3 or 4 symbols (depending of the template)
2. Click on tab New Topic (the topic icons are b3/b4 symbols)
3. Switch in the editor dropdown list to another category

**Actual result**
The topic symbols changes to legacy symbols

**Comment by xillibit** [comment]
Not able to reproduce with CKeditor and BBCode, tried on CrypsisB4 :

https://user-images.githubusercontent.com/876395/143787968-a0555645-4940-40fb-af3b-cb6287d0e4e9.mp4

**Comment by rich20** [comment]
I gave this hint: This happens only with the CKEditor
You use the BBCode editor

**Comment by xillibit** [comment]
I had noticed after, i have tested but still not able to reproduce : 

https://user-images.githubusercontent.com/876395/143788536-abe7fc03-ace6-49b0-a4b6-dd3b1483b74f.mp4

**Comment by rich20** [comment]
Hmm.... I have the problem still wiih both teḿplates. (Crypsisb3 and b4)

**Comment by rich20** [comment]
I know it now. The problem exist when Joomla is installed in a sub folder.

**Comment by xillibit** [comment]
Fixed by : https://github.com/Kunena/Kunena-Forum/pull/8610
