### ISSUE TITLE
Crypsisb4 want to load bootstrap 2 instead of svg

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8600]
**To Reproduce**

- Select COM_KUNENA_TEMPLATE_BOOTSRAP4 symbols in the temlate configuration (this string is not translated)
- Go to Recent Topics and check the file symbol left (**it's a SVG**)
- Go to the Index (you see no folders)
- Check with the Browser tool the empty place

**Result**
It will load bootstrap 2 icons:
`<i class="icon  icon-big " alt="New Posts" aria-hidden="true"> </i>`

- [ ] Should also be loaded SVG symbols
- [ ] The  selction list in the  template setting should be adjusted from to SVG instead of bootstrap4 symbols

**System information**
- Joomla version: 3.10.4-dev
- Kunena version: 5.2.7-DEV
- Kunena template name and version: Crypsisb4
- Php version: 8.0.12
- Database version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
> * The  selction list in the  template setting should be adjusted from to SVG instead of bootstrap4 symbols

It's not very clear this sentence

**Comment by xillibit** [comment]
The settings in KunenaIcons library haven't been updated for CrypsisB4 but in BS4 glyphicons (provided in BS3 and BS2) has been dropped : https://getbootstrap.com/docs/4.1/extend/icons/

**Comment by rich20** [comment]
As far as I know Bootstrap 4 doesn't have its own icon library. That's why in Kunena 6.0 we have the option to select SVG.
![Bildschirmfoto von 2021-12-04 14-19-53](https://user-images.githubusercontent.com/888847/144712969-16363dd6-7942-4db5-803a-bf2a2f37da15.png)

The select option SVG is not present for Crypsisb4.
![Bildschirmfoto von 2021-12-04 14-44-02](https://user-images.githubusercontent.com/888847/144712977-7bf62aef-289d-43bb-973b-31cef94a70cb.png)

But if you choose "Icon type = bootstrap 4" instead, you have on the Recent Topic page nevertheless SVG symbols, and on the Index page lacks the symbols, because Kunena want to display bootstrap 2 symbols.
![Bildschirmfoto von 2021-12-04 14-52-41](https://user-images.githubusercontent.com/888847/144712999-164f7be1-c70b-4bbd-a24c-d7aa24913a4d.png)    ![Bildschirmfoto von 2021-12-04 14-52-52](https://user-images.githubusercontent.com/888847/144713005-99a962c4-cb8f-4288-b5f7-09854e92e19b.png)

For me, selecting for Bootstrap 4 icons makes no sense (for both Crypsisb4 and Aurelia) if there is no own library for Bootstrap 4 icons. There should be only the selection for SVG instead.

**Comment by xillibit** [comment]
The svg feature is only present in K6.0, so in crypsisB4 i will remove the option COM_KUNENA_TEMPLATE_BOOTSTRAP4 and set fa by default
