### ISSUE TITLE
Uploaded .gif avatar breaks the page in the frontend and in the backend the userlist

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8619]
**To Reproduce**

- Upload a .gif image as avatar
- Go to Recent Topics (must contain a last post of this user)

**Result with PHP 7.4.25**
This error is only temporary and after page refresh gone

Warning: imagecolorsforindex(): Color index 31 out of range in .../libraries/src/Image/Image.php on line 725
Notice: Trying to access array offset on value of type bool in .../libraries/src/Image/Image.php on line 726

**Result with PHP 8.0.12**
Page refresh does not help, the error remain, and you can't go to backend user manager

Rendering Error in layout Topic/Row: imagecolorsforindex(): Argument #2 ($color) is out of range in .../plugins/kunena/kunena/avatar.php on line 142
Layout was rendered in .../components/com_kunena/template/aurelia/layouts/topic/list/default.php on line 174

**Backend user manager**

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Image/Image.php:725
2 | imagecolorsforindex() | JROOT/libraries/src/Image/Image.php:725
3 | Joomla\CMS\Image\Image->resize() | JROOT/libraries/kunena/src/Image/KunenaImageHelper.php:102
4 | Kunena\Forum\Libraries\Image\KunenaImageHelper::version() | JROOT/plugins/kunena/kunena/avatar.php:142
5 | KunenaAvatarKunena->_getURL() | JROOT/libraries/kunena/src/Integration/KunenaAvatar.php:215
6 | Kunena\Forum\Libraries\Integration\KunenaAvatar->getURL() | JROOT/libraries/kunena/src/Integration/KunenaAvatar.php:131
7 | Kunena\Forum\Libraries\Integration\KunenaAvatar->getLink() | JROOT/libraries/kunena/src/User/KunenaUser.php:1040
8 | Kunena\Forum\Libraries\User\KunenaUser->getAvatarImage() | JROOT/administrator/components/com_kunena/tmpl/users/default.php:238
9 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
10 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:218
11 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Users/HtmlView.php:79
12 | Kunena\Forum\Administrator\View\Users\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:692
13 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:66
14 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
15 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
16 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
17 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
18 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
19 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
20 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
21 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: 4.0.5-dev and 4.0.5-rc3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA6-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.25 and 8.0.12 
- Database version: 10.4.21-MariaDB and 10.5.11-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
For me i don't see this error : 

https://user-images.githubusercontent.com/876395/145721964-0481398e-d339-47d2-b2df-d9f688428395.mp4

The avatar image that i have set is right animated, the only weird thing i see is that the image isn't animated after the upload

**Comment by rich20** [comment]
The image is also displayed for me, but there is additional the error message.
Whereby, there is a difference depending on which php version is in use.

**Comment by xillibit** [comment]
Tested with Php 7.4.26 and 8.0.13 but i don't see the error

**Comment by rich20** [comment]
Maybe it is because the installation is in a subdirectory? However, the fact that the image is displayed speaks against this.
