### ISSUE TITLE
On Kunena menu item Home lacks the option Default Menu Item (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8621]
**To Reproduce**

- Go to the Kunena menu and edit the first item Forum
- Choose the Kunena menu item type Kunena Home
- Choose at Default Menu Item  a landing page like Recent Topics  or Index and save
- Now you have a address like   index.php?option=com_kunena&view=**H**ome&defaultmenu=1288

![Bildschirmfoto von 2021-12-08 00-00-47](https://user-images.githubusercontent.com/888847/145120646-3e58512d-7895-4d48-8610-3e1af34516c1.png)

**Result**
The problem is the capital letter in the address, and so you get no menu tabs in the frontend. When I change in the database this letter of this menu item to lower case the tabs are back, the target page also works, but the menu item in the Kunena menu switch back to the old one before this fix. https://github.com/Kunena/Kunena-Forum/pull/8618

![Bildschirmfoto von 2021-12-08 00-33-47](https://user-images.githubusercontent.com/888847/145122416-d1537201-ecfa-4ce2-827b-f1a34130dcf2.png)

**Comment by xillibit** [comment]
Not possible to reproduce now : 

https://user-images.githubusercontent.com/876395/146086751-3bf15d67-acc9-49c4-9b67-d6c350a5d06e.mp4

**Comment by rich20** [comment]
Did I miss something? I wrote this seven days ago. Now also the option "Restore Kunena Menu" creates the correct menu item Home.
Unfortunately, it does not fix the main problem with navigation.
But this ticket is now obsolete, and  I close it.

**Comment by xillibit** [comment]
I had reproduced the issue couple of days ago, seems the last changes in Joomla! does something
