### ISSUE TITLE
Community Builder avatars are not displayed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8622]
**Describe the bug**
https://www.kunena.org/forum/12-Community-Builder/163619-avatar-integration-with-kunena-5-2-7-fails
Confirmed

If you use Community Builder avatars and upgrade to Kunena 5.2.7 it shows only the "no photo" image from CB

**Comment by beat** [comment]
Proposing an easy and tested fix in #8634
Cheers! :slightly_smiling_face:
