### ISSUE TITLE
It  lacks the rating option at topics

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8658]
**Describe the bug**
As you can see on image 1, rating is enabled. But there are no rating stars at top of the topic  (image2). <br />
![Bildschirmfoto von 2021-12-21 03-13-06](https://user-images.githubusercontent.com/888847/146860623-fb46d127-b106-4934-a1ab-dd057bd26b19.png)

-------------------------------------------

![Bildschirmfoto von 2021-12-21 03-14-02](https://user-images.githubusercontent.com/888847/146860667-15b7ee37-46c4-406e-bbb5-f7c260ebf05f.png)

----------------------------------------

**System information**
- Joomla version: 4.0.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA7-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.25 and 8.0.13 
- Database version: 10.4.22-MariaDB and 10.5.11-MariaDB

**Comment by xillibit** [comment]
On recent discussions or list of topics of a category when rating is enabled i can't see the rating stars

**Comment by rich20** [comment]
You're right. It seems, you see it only at the first created category.
