### ISSUE TITLE
The requested page can't be found.

### ISSUE THREAD

**Issue by sluc69** [Kunena/Kunena-Forum#8686]
**Describe the bug**
error: "The requested page can't be found."

**To Reproduce**
1. Go to index
2. Click on a category
3. select a topic

![image](https://user-images.githubusercontent.com/82952282/147632328-dac8e0ff-c5a5-4c45-9387-6180acc11197.png)

**System information (please complete the following information)**

Joomla version: 4.05
Kunena version: 6 beta 6
Kunena template name and version: Aurelia
Kunena editor in use: 
Php version: 8.0.14
Database version:  8.0.27-0ubuntu0.20.04.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 11
 - Browser [e.g. firefox, chrome, safari] chrome
 - Version [e.g. 22] latest

**Additional context**
already a problem in previous beta versions.
From the "recent Topics" menu, no problem!
If i delete the "layout=list&" from the URL the topic is displayed correct!

**Comment by xillibit** [comment]
We aren't able to reproduce your issue

**Comment by sluc69** [comment]
if this may help

**Please don't here your Kunena report configuration it's done only to copy it in your message on kunena.org forum. It's now in the text file in attachment without some confidential data** 

The installation in question is an upgrade from J3 to J4. 
How are you testing? From a blank J4 installation??
Other website run fine on this server, so I don't think it is a server issue unless you can point out one to me.

[kunena_report_configuration.txt](https://github.com/Kunena/Kunena-Forum/files/7797588/kunena_report_configuration.txt)

**Comment by xillibit** [comment]
I have put your kunena report configuration in the text file and i have removed in it the mail and the website

I'am testing locally with a backup from a real site running on Kunena 5.2.7

Why you have plenty of menu items in mainmenu pointing to Kunena ? You should have just the one created by default not more

**Comment by xillibit** [comment]
Fixed by https://github.com/Kunena/Kunena-Forum/commit/cfa76e3f0dc1d9bcb269da2a43fe22629382cfdb
