### ISSUE TITLE
Error at announcements: View not found [name, type, prefix]: ...

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8727]
**Describe the bug**
https://www.kunena.org/forum/36-German/163961-6-0-0-beta7-dev-git-2022-01-07-fehler-in-ank%C3%BCndigungen

Confirmed

**To Reproduce**
Click at announcement the link Read More
Click on Control Panel or breadcrumb (see image)
![Bildschirmfoto von 2022-01-08 03-15-36](https://user-images.githubusercontent.com/888847/148628060-71eda9e1-9c23-45c8-b874-71a3bbfe66f8.png)

**Result**

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/MVC/Controller/BaseController.php:898
2 | Joomla\CMS\MVC\Controller\BaseController->getView() | JROOT/libraries/kunena/src/Controller/KunenaController.php:430
3 | Kunena\Forum\Libraries\Controller\KunenaController->display() | JROOT/libraries/kunena/src/Controller/KunenaController.php:349
4 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:240
5 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:113
6 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:206
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:245
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
11 | require_once() | JROOT/index.php:32

**System information**
- Joomla version: 4.0.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA7-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.26 
- Database version: 10.5.11-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I have fixed for button "Control Panel" but i haven't found how to fix it for breadcrumb
