### ISSUE TITLE
Kunena-Forum Beta 6 - Can't open thread from other user

### ISSUE THREAD

**Issue by michalnh** [Kunena/Kunena-Forum#8729]
**Describe the bug**
If i create a post/thread as "user a", "user b" can't read/open it. Even an admin does not.

**To Reproduce**
1 Post a new thread in a forum as "user a"
2 try to open with "user b" 
3 errormessage
404
View not found [Name, type, prefix]: topic, html, site

**Expected behavior**
User should be able to read in a forum, where he has rights

**Actual result**
errormessage
404
View not found [Name, type, prefix]: topic, html, site
If i click on my own created thread, there are no problems.
So "user a" can read and open/read his own created threads.

**Screenshots**

**System information (please complete the following information)**
Joomla: 4.0.5
Kunena version: 6.0.0-BETA6-GIT
Php version: PHP 8.1
Database version: MariaDB 10

Desktop (please complete the following information):
Windows 10 21H1

Smartphone (please complete the following information):
Android

**Additional context**
de version, language

**Comment by rich20** [comment]
Please go to our download page and scroll down. Install the Nightly Build 6.0.0-BETA7-DEV_2022-01-07 for tests.
https://www.kunena.org/download 

I think, you mean this bug https://github.com/Kunena/Kunena-Forum/issues/8344
If yes, then close this issue, please.

**Comment by michalnh** [comment]
Hi rich20,
i installed "Nightly Build 6.0.0-BETA7-DEV_2022-01-07" and it works!
Thank you for your quick answer and help.
-> closed
