### ISSUE TITLE
Wrong link output from Transifex

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8753]
We have a problem with Transifex. @xillibit You may have noticed that not everything on your French test page seems to be translated.
But the problem is Transifex. It does not transfer such links correctly. You can see it in the team credits.

The links will be changed
from source text
`<a target=\"_blank\" href=\"%s\">contributed</a>`
translated text output
`<a target=\\"_QQ_"_blank\\"_QQ_" href=\\"_QQ_"%s\\"_QQ_">contributed</a>`

It breaks the ini file and has the effect that all following lines are not displayed. You can see only the codes on the page.

(Are the lines **65 and 76** in the frontend views.ini)

source text file
https://github.com/Kunena/Kunena-Forum/blob/89a4a6a3311ce4ad0cf7ceafe0d62aa5fdb0e2f1/src/site/language/en-GB/en-GB.com_kunena.views.ini#L65

translated text file
https://github.com/Kunena/Kunena-Forum/blob/89a4a6a3311ce4ad0cf7ceafe0d62aa5fdb0e2f1/src/site/language/fr-FR/fr-FR.com_kunena.views.ini#L65

**Comment by xillibit** [comment]
@rich20 : not sure if it will be updated on transifex like that

**Comment by rich20** [comment]
The output from Transifex is wrong. 
`<a target=\\"_QQ_"_blank\\"_QQ_" href=\\"_QQ_"%s\\"_QQ_">contributed</a>`

The output should be without slashes.
`<a target="_QQ_"_blank"_QQ_" href="_QQ_"%s"_QQ_">contributed</a>`

**Comment by rich20** [comment]
@xillibit In this case, all translated frontend views.ini files are broken. Only the source file works.
