### ISSUE TITLE
How to upgrade kunena for Joomla 3 to Joomla 4?

### ISSUE THREAD

**Issue by kolkov** [Kunena/Kunena-Forum#8789]
Hi!
I try to upgrade Joomla from 3x to 4x. And then I try to update Kunena forum from 5x to 6x, but existing installation not working now.
Whats wrong? Or migrating feature not exist yet?

**Comment by 810** [comment]
At this point we don't support J4 yet, we have a rc build, that is for clean install.

We are working on it.

**Comment by kolkov** [comment]
Thanks!
