### ISSUE TITLE
For labels lacks the background color

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8792]
**Describe the bug**
https://www.kunena.org/forum/36-German/164315-6-0-0-beta7-git-2022-01-18-mit-fontawesome-keine-etiketten-angezeigt#221663

It lacks the background color for labels, this makes it look like the topic title is indented.

![Bildschirmfoto von 2022-02-01 03-01-34](https://user-images.githubusercontent.com/888847/151903239-049cd272-9f86-4e59-bf03-54cc87f85628.png)

**Comment by xillibit** [comment]
Fixed : 
![image](https://user-images.githubusercontent.com/876395/216714727-6782dfee-770c-4ec3-9ed8-a7bba78ed960.png)
