### ISSUE TITLE
Only with Kunena 6.0 and CKEditor: It displays link code tags in the message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8794]
**To Reproduce**
Use the link symbol and enter a link without text
`[url]https://www.kunena.org/[/url]`

**Result**
![Bildschirmfoto von 2022-02-01 17-42-02](https://user-images.githubusercontent.com/888847/152013287-13c1748f-1d50-4b6d-a20f-f1d3e96bbd71.png)

**Comment by xillibit** [comment]
I'am not able to reproduce this issue for me it was fixed with https://github.com/Kunena/Kunena-Forum/commit/0f569ba0fe7548fb0cdc4fa896ea6d19824a80c8

https://user-images.githubusercontent.com/876395/152014870-ee80ed08-ebc9-49d8-bb90-99239f4ca230.mp4

**Comment by rich20** [comment]
hmm.. I've tested it with the current version with all changes of the last days.

**Comment by rich20** [comment]
Interesting, after the last two fixes, the error disappeared. But I re-imported the complete files, maybe I had a corrupted file.
