### ISSUE TITLE
Kunena - Tools - Uninstall Kunena no longer works

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8799]
**Describe the bug**
Kunena - Tools - Uninstall Kunena no longer works. At first I thought it was my installation and completely reinstalled Joomla and Kunena. It is the same with a clean installation.

**Result**

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/kunena/joomla/login.php:57
2 | KunenaLoginJoomla->loginUser() | JROOT/libraries/kunena/src/Login/KunenaLogin.php:126
3 | Kunena\Forum\Libraries\Login\KunenaLogin->loginUser() | JROOT/administrator/components/com_kunena/src/Controller/ToolsController.php:973
4 | Kunena\Forum\Administrator\Controller\ToolsController->uninstall() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
6 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
11 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: 4.0.7-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-BETA8-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.26 
- Database version: 10.5.11-MariaDB
**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Leen29** [comment]
I can confirm this with my live site doesn't work either 
An error has occurred.

    0 KunenaLoginJoomla::loginUser(): Argument #3 ($rememberme) must be of type bool, null given, called in /home/mijnsite/domains/mijnsite.eu/public_html/libraries/kunena/src/Login/KunenaLogin.php on line 126
