### ISSUE TITLE
If the value for "Email to multiple recipients" is greater than 0, no emails will be sent

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8825]
**Describe the bug**
https://www.kunena.org/forum/k-5-2-support/164452-kunena-5-2-6-email-notification-error
Confirmed

**To Reproduce**

- Go to the configuration - tab Users
- Enter at E-mail to Multiple Recipients the value 5 or higher
- E-mail Recipient Privacy BCC
- Enter a email address at Visible E-mail Recipient 
- Add multiple users to a category subscription
- Log in to the frontend and reply to a topic

**Result**
Only this user gets a mail, who has the same email address in his profile as the one entered at Visible E-mail Recipient

**Additional context**
If you enter a different email address, the send seems to work

**Comment by kroonsbe** [comment]
Same issue here with Joomla 4 and Kunena 6.0 RC latest version

**Comment by xillibit** [comment]
I have found the culprit, when a mail address is filled in "Visible E-mail Recipient" and it's added in first in KunenaMail to the list of mails to send then adding the others adresses and it's have the same as defined in "Visible E-mail Recipient" just return false and do nothing that's explain why one the user which have the mail in "Visible E-mail Recipient" receive a mail

**Comment by rich20** [comment]
- [x] Success in K.6

**Comment by rich20** [comment]
Sorry, we need this fix also in K5.2, so I reopen this issue.
