### ISSUE TITLE
Uninstall via Tools removes only the kunena tables from the database and folders in libraries

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8826]
**Describe the bug**
Uninstall via Tools removes only the kunena tables from the database and the folders and files from the libraries are deleted, everything else is kept. And so it's not possible, to install Kunena again.

1146 Table '#__kunena_configuration' doesn't exist
Call stack
--
# | Function | Location
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:141
2 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:1048
3 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1900
4 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/libraries/kunena/src/Config/KunenaConfig.php:1682
5 | Kunena\Forum\Libraries\Config\KunenaConfig->load() | JROOT/libraries/kunena/src/Config/KunenaConfig.php:1658
6 | Kunena\Forum\Libraries\Config\KunenaConfig::getInstance() | JROOT/administrator/components/com_kunena/api/api.php:24
7 | require_once() | JROOT/plugins/system/kunena/kunena.php:58
8 | plgSystemKunena->__construct() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:242
9 | Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
10 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:94
11 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT/libraries/src/Plugin/PluginHelper.php:236
12 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT/libraries/src/Plugin/PluginHelper.php:194
13 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT/libraries/src/Application/CMSApplication.php:739
14 | Joomla\CMS\Application\CMSApplication->initialiseApp() | JROOT/libraries/src/Application/AdministratorApplication.php:354
15 | Joomla\CMS\Application\AdministratorApplication->initialiseApp() | JROOT/libraries/src/Application/AdministratorApplication.php:165
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
18 | require_once() | JROOT/administrator/index.php:32

</div>

**Comment by xillibit** [comment]
Do-you have still this issue ?

**Comment by rich20** [comment]
It's already fixed
