### ISSUE TITLE
Tag code not show 

### ISSUE THREAD

**Issue by specialworld83** [Kunena/Kunena-Forum#8834]
**Describe the bug**
The code tag is not visible in the topic. Instead inside the editor yes.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 4.1.0
![kunena_1](https://user-images.githubusercontent.com/9156314/154649764-b390640f-be5a-40f7-8155-bcb6999e3d33.png)
![kunena_2](https://user-images.githubusercontent.com/9156314/154649769-08126594-973d-4f78-a701-9590c9f3f83c.png)

Kunena version: 6.0-dev
Kunena template name and version: Aurelia 6.0-dev
Kunena editor in use: ckeditor
Php version: 7.4.28
Database version: mysql 8

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Browser: firefox
 - Version: 97

**Comment by xillibit** [comment]
Fixed by https://github.com/Kunena/Kunena-Forum/pull/8954
