### ISSUE TITLE
Upgrade from older K6.0 to current K6.0 isn't possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8841]
**Describe the bug**
https://www.kunena.org/forum/k-6-0-support/164539-upgrade-to-beta-7-missing-all-categories#222155
Confimed

It is not possible to upgrade a Kunena version that was released before the database upgrade.
This also affects all users who are using the currently released Beta 7 from our download page and have already set up their forum.
I've tried it many times, but an upgrade is not possible.
There is an error like this:
```
JInstaller: :Install: Error SQL Duplicate entry '1' for key 'PRIMARY'
Extension installation aborted.
Package Update: There was an error installing an extension: com_kunena_v6.0.0-RC1-DEV.zip
×
danger
Error installing package
```
![ScreenShot2022-02-23at1 46 11PM](https://user-images.githubusercontent.com/888847/155575373-f32d59b1-667d-4cb3-94d3-614b471037da.png)

**Comment by xillibit** [comment]
For now i don't know exactly where this sql error comes from

**Comment by 810** [comment]
i will check it.

**Comment by xillibit** [comment]
I hve tried this change, now there is another error : `JInstaller: :Install: Error SQL Field 'allow_anonymous' unknown in u7wdl_kunena_categories`

**Comment by xillibit** [comment]
The usage of ignore in queries alter table has been removed in MySQL 5.7 : https://dev.mysql.com/worklog/task/?id=7395...

**Comment by 810** [comment]
> I hve tried this change, now there is another error : `JInstaller: :Install: Error SQL Field 'allow_anonymous' unknown in u7wdl_kunena_categories`

We need to add hotfix, or add a sql if its that version to add component id with version to _schema table.

**Comment by 810** [comment]
SHould be fixed now, please test

**Comment by rich20** [comment]
I get still this error

Warning
JInstaller: :Install: Error SQL Unknown column 'allow_anonymous' in 'gztr_kunena_categories'
Extension installation aborted.
Package Update: There was an error installing an extension: com_kunena_v6.0.0-RC1-DEV.zip
×
Error installing package

**Comment by xillibit** [comment]
Fixed or me with last changes
