### ISSUE TITLE
Fontawesome icons are not placed correctly

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8842]
**Describe the bug**
https://www.kunena.org/forum/36-German/164571-6-0-0-rc1-dev-git-konfiguration-beitrag-melden
Confirmed

**To Reproduce**
Select in Aurelia Symbol type Fontawesome
Load external Fontawessome = Yes

**Actual result**
Thank you and Unthank you symbols are too big
It lacks the Report message symbol

![path8023](https://user-images.githubusercontent.com/888847/155893478-f6b75b10-2def-48e1-83c6-12e655999682.png)

**Additional context**
Even with old icons only text is displayed there "kicon-report Report This", but legacy symbols will removed anyway I think.

**System information**
- Joomla version: 4.1.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC1-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.26 
- Database version: 10.5.11-MariaDB
- 
**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment]
In Fontawesome, two icons overlap on the "Thank you" button and therefore there are two different tooltips depending on how exactly the mouse is placed on the thankyou symbol. I think, that's the problem.

![Bildschirmfoto von 2022-03-08 03-57-42](https://user-images.githubusercontent.com/888847/157158102-e52ea4f1-7c8c-4289-9de1-16b0b92629e6.png)
![Bildschirmfoto von 2022-03-08 03-58-06](https://user-images.githubusercontent.com/888847/157158124-fc2e5883-4683-4e1d-af3b-b2e406ea48a8.png)

**Comment by rich20** [comment]
This bug should be fixed, otherwise it is not possible to use external Fontawesome

**Comment by xillibit** [comment]
Seems ok now  : 
![image](https://user-images.githubusercontent.com/876395/216714397-b4a09c4d-7e11-4639-b78a-f75687bb6d11.png)
