### ISSUE TITLE
Language files (backend views.ini) do not match

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8863]
Why are there such big differences between the backend views.ini files?
The source file has 1346 lines https://github.com/Kunena/Kunena-Forum/blob/1e7ccd613c7e3fe8a958d5b7934cab020f6c69c4/src/admin/language/en-GB/en-GB.com_kunena.views.ini#L1346
the translated files 1337 lines https://github.com/Kunena/Kunena-Forum/blob/1e7ccd613c7e3fe8a958d5b7934cab020f6c69c4/src/admin/language/fr-FR/fr-FR.com_kunena.views.ini#L1337
and on Transifex are for the same file only 13 lines
https://www.transifex.com/Kunena-Forum/kunena-forum-6/viewstrings/#de_DE/src-admin-language-en-gb-en-gb-com-kunena-views-ini--k6-0/409863998

**Comment by xillibit** [comment]
With the upload of last source file on transifex others languages same number of lines
