### ISSUE TITLE
[6.0-RC1] Invalid error when editing topic for unknown/deleted user  

### ISSUE THREAD

**Issue by jschmi102** [Kunena/Kunena-Forum#8890]
**Describe the bug**
When edit/save post of deleted user you get error **Cannot save user topic: User 0 doesn't exist!** 
Though error is shown  changed post is saved.

**To Reproduce**
1. edit a post of a deleted/unknown user 
2. save chenges
3. See error
4. check changed post 

**Expected behavior**
should save changes done with edit and show success.

**Actual result**
saved changes but issues error 

**System information (please complete the following information)**
Joomla version: 4.1.2
Kunena version: 6.0-rc1
Kunena template name and version: aurelia
Php version: 7.4.14
Database version: 5.7.36

**Comment by xillibit** [comment]
Please try with RC2

**Comment by jschmi102** [comment]
hi,
with RC2 still same error ist displayed - I think the behaviour sending an **error** is wrong - instead  a **warning/information** message should be sent.

**Comment by rich20** [comment]
Confirmed. If you delete a user first and then edit his posts, you will get this error.. **Cannot save user topic: User 0 doesn't exist!**
