### ISSUE TITLE
[6.0-RC1] Various Errors using Kuena

### ISSUE THREAD

**Issue by jschmi102** [Kunena/Kunena-Forum#8897]
tried to use/test Kuena 6.0-RC1 with Jommla 4.1.2 and stuck with misc. problems. For me this seems to be more a beta-version than a release candidate... 

- lots of missing strings for messages in frontend and backend
- modal popups ("Report This" and "Quick Reply") are not working correctly (wrong positioning and layout) 
- default.php in  "components\com_kunena\template\aurelia\layouts\widget\login\login" had to be corrected
- took me quite a time to customize aurelia template as lot of topics have been changed compared to V5.2.8 with cripsis or cipsisb3 
- only english language supported

Here are some keys for missing text strings:

front-end:
COM_KUNENA_POST_SUCCESS_DELETE
COM_KUNENA_POST_SUCCESS_UNDELETE
COM_KUNENA_POST_SUCCESS_EDIT
COM_KUNENA_ACTION_TOPIC_SUCCESS_MOVE
COM_KUNENA_POST_SUCCESS_POSTED

dashboard:
COM_KUNENA_CPANEL_LABEL_KUNENA_VERSION_CHECK
COM_KUNENA_CPANEL_LABEL_LAST_UPDATE_CHECK Today
COM_KUNENA_CPANEL_LABEL_INSTALL
COM_KUNENA_CPANEL_LABEL_SAMPLE_DATA
COM_KUNENA_CPANEL_LABEL_INSTALL_SAMPLE_DATA
COM_KUNENA_CPANEL_LABEL_TEMPLATES_INSTALLED
COM_KUNENA_CPANEL_LABEL_ITEM

Templates:
COM_KUENA_A_TEMPLATE_MANAGER_EDITSCSS
COM_KUNENA_A_TEMPLATE_MANAGER_TYPE
COM_KUNENA_A_TEMPLATE_MANAGER_PAID
COM_KUNENA_A_TEMPLATE_MANAGER_CONFIGURATION_SAVED

Emoticons
COM_KUNENA_SMILEY_SAVED 
COM_KUNENA_SMILEY_DELETED 	

ranks
COM_KUNENA_RANK_SAVED
COM_KUNENA_RANK_DELETED

configuration
COM_KUNENA_ADMIN_CONFIG_PROFILER
COM_KUNENA_EMAIL_HEADER_SIZEY
COM_KUNENA_EMAIL_HEADER_SIZEY_DESC
COM_KUNENA_EMAIL_HEADER_SIZEX
COM_KUNENA_EMAIL_HEADER_SIZEX_DESC
COM_KUNENA_A_USE_UTM_SOURCE
COM_KUNENA_A_USE_UTM_SOURCE_DESC

tools
all descriptions (COM_KUENA_**_DESC)

**Comment by xillibit** [comment]
Please try with RC2 just released yersterday, you need to install the language to have others language supported

**Comment by jschmi102** [comment]
hi,
exactly same problems with RC2 - nothing changed regarding this issue.

**Comment by rich20** [comment]
What language do you use? Do these problems also occur with the English language?

**Comment by jschmi102** [comment]
there is only english language available - can not use any  other language! ... just install/try RC2 - you'll see those errors.

**Comment by rich20** [comment]
Please check whether in the folders
/language/en-GB
and
/administrator/language/en-GB
kunena ini files are present. If yes, delete these files, except files for extensions like Kunena latest (if you have installed)
It should solve some problems

**Comment by jschmi102** [comment]
hi,
thank you for your help. Deleting ini-files almost fixed the problems with text strings. in addition to it I had to correct code of  "../administrator/components/com_kunena/src/Controller/TemplateController.php".  

Added missing  statement (provide language for class "TemplateController"):
` KunenaFactory::loadLanguage('com_kunena.controllers', 'admin');  `
after Line 70 of TemplateController.php".

Now all backend text strings seem to be clean.

Frontend Text strings were still missing - after some search I found that text string for  "topic" and "topic.php" in "en_GB.com_kunena.controllers.ini"  had to be copied to "en_GB.com_kunena.kunena.ini". That fixed all of the missing frontend text strings, 

 Modal popups ("Report This" and "Quick Reply") are still not working correctly (wrong positioning and layout) - I'm circumventing this by using template (aurelia) config-option "Always visible" (instead of "Default" or "Modal").  
Do you have a clue howto fix this?

**Comment by xillibit** [comment]
> Modal popups ("Report This" and "Quick Reply") are still not working correctly (wrong positioning and layout) - I'm circumventing this by using template (aurelia) config-option "Always visible" (instead of "Default" or "Modal").
> Do you have a clue howto fix this?

Which Joomla! template are-you using ?

**Comment by jschmi102** [comment]
hi,
I'm using purity III from joomlart. If I'm switchin to "modal" i get javascript error:

```
Uncaught TypeError: 'querySelector' called on an object that does not implement interface Element.
    findOne http://localhost/myjoomla/media/vendor/bootstrap/js/dom.min.js?5.1.3:1
    _showElement http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
    show http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
    execute http://localhost/myjoomla/media/vendor/bootstrap/js/dom.min.js?5.1.3:1
    show http://localhost/myjoomla/media/vendor/bootstrap/js/dom.min.js?5.1.3:1
    _showBackdrop http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
    show http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
    toggle http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
    <anonymous> http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
    o http://localhost/myjoomla/media/vendor/bootstrap/js/dom.min.js?5.1.3:1
    addHandler http://localhost/myjoomla/media/vendor/bootstrap/js/dom.min.js?5.1.3:1
    on http://localhost/myjoomla/media/vendor/bootstrap/js/dom.min.js?5.1.3:1
    <anonymous> http://localhost/myjoomla/media/vendor/bootstrap/js/modal.min.js?5.1.3:1
```
and the displayed page is blocked.
switiching to "default", a misplaced and incomplete popup is displayed:

 
![kunena](https://user-images.githubusercontent.com/69053785/164969366-fd100ebc-c321-4165-a3f0-7d9cd3d7f732.jpg)

**Comment by xillibit** [comment]
It uses Bootstrap v3.4.1, kunena aurelia template is designed to works only on bootstrap 5.1 like it provided by Joomla! 4.x

**Comment by jschmi102** [comment]
hi,

...I can live with this.

you should check your code for missing language interfaces - e.g. I had to correct/add
**KunenaFactory::loadLanguage('com_kunena.controllers');**  to **CategoryController.php** after line 46...
