### ISSUE TITLE
[CKeditor] text is not displayed if with bbcode marked

### ISSUE THREAD

**Issue by jschmi102** [Kunena/Kunena-Forum#8907]
**Describe the bug**
**This is a very serious bug as it will make kunena unusable** 
bbcode markups will delete text if message is saved.

**To Reproduce**
1. edit  topic and mark text  with a bbcode e.g. use:  &#91;color=#e74c3c]] some text
2. within editor text shows marked correctly (shows red text)
3. Save topic 
4. marked text is deleted (source shows `"<a href="/your-joomla-root"></a>"`

**Expected behavior**
marked text should be displayed correctly after saved

**Actual result**
marked text is deleted (source shows `"<a href="/your-joomla-root"></a>"`

**System information (please complete the following information)**
Joomla version:  4.1.2
Kunena version: 6.0RC2 (same happens with 6.0RC1)
Kunena template name and version: aurelia
Kunena editor in use: ckeditor
Php version: 7.4.14
Database version: 5.7.36

**Screen shots**

![kunena-1](https://user-images.githubusercontent.com/69053785/163556304-a9b14bc9-5fef-456a-ab30-e09408f3ee9a.jpg)

![kunena-2](https://user-images.githubusercontent.com/69053785/163556315-38a28d98-1042-4ac6-b891-e8f345665971.jpg)

![kunena-3](https://user-images.githubusercontent.com/69053785/163571043-284d4a1c-1345-4f9f-a57f-b4b149e06824.jpg)

**Comment by rich20** [comment]
Confirmed. In principle, everything within color tags is not displayed.

**Comment by jschmi102** [comment]
hi,
to clarify! This problem is **not** a CKeditor problem - the editor creates the correct data with its bbcodes, which is then stored into the database. The causer of the problem is the wrong translation of bbcodes into html-tags done by **kunenaBBCode.php** (from library/kunena/src/BBCode). I checked this changing processing of ` code` at line 1013 of  **kunenaBBCode.php** into 
```
		'code'          => [
			'simple_start' => "<pre style='width: fit-content'>",
			'simple_end'   => "</pre>",
			'class'        => 'block',
			'allow_in'     => ['listitem', 'block', 'columns'],
			'plain_start'  => "<i>",
			'plain_end'    => "</i>",
		],
```
This fixed the problem using bbode: ` [code]`

**Comment by xillibit** [comment]
i have tried the change suggested but for me it has no effect, btw i have found the thing which make this behaviour in \libraries\kunena\External\Nbbc\src\BBCode.php. I will try to find a fix
