### ISSUE TITLE
Quick reply does not keep the content when you go to the editor, regardless of which quick reply is being used

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8929]
**System information**
- Joomla version: 4.1.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.28 and 8.0.13 
- Database version: 10.5.11-MariaDB and 10.4.22-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It works only if options "always visible" is set
