### ISSUE TITLE
The same language code is displayed correctly only once

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8931]
**To Reproduce**
1. edit Aurelia
2. click on Save & Close - the text is displayed correct
3. edit Aurelia again
4. clik on Save - now it shows the key COM_KUNENA_A_TEMPLATE_MANAGER_CONFIGURATION_SAVED

Both options use te same language key. You find this key COM_KUNENA_A_TEMPLATE_MANAGER_CONFIGURATION_SAVED
 only in the 
backend controllers.ini https://github.com/Kunena/Kunena-Forum/blob/306e4995b974c177423a7e263e8924b4b33fba95/src/admin/language/en-GB/en-GB.com_kunena.controllers.ini#L64
and in the TemplateController.php two times 
https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/admin/src/Controller/TemplateController.php

**Comment by 810** [comment]
i can't reproduce this, i still see Template configuration saved

**Comment by rich20** [comment]
After deleting the language files and reinstalling it works.
