### ISSUE TITLE
[6.0-RC2]Cannot save user profile

### ISSUE THREAD

**Issue by jschmi102** [Kunena/Kunena-Forum#8935]
**Describe the bug**
after change of user profile save fails with "**Unknown column 'github' in 'field list'** " 
If you add column  "**github**" in table **#__kunena_users** you'll get  "**Unknown column 'vimeo' in 'field list'** " 

**To Reproduce**
1. set "Allow social providers" to "No" in kunena config option for users
2. select "user" in kunena config options and select/edit an user
3. change and try to save user settings 
4. get error Unknown column 'github' in 'field list'

**Expected behavior**
As social providers will not be used, user profile should be saved.

**Actual result**
User is not saved

**Additional context**
This error is caused by missing columns "**github**" and "**vimeo**" in table **#__kunena_users**
If you add missing columns, error is fixed  and user profile may be saved successfully.

**Comment by xillibit** [comment]
The fields "github" and "vimeo"  are added on new install of Kunena and these fields are added too in the update process of Kunena. So you have done an update which hasn't worked

**Comment by jschmi102** [comment]
hi,

you are right - however I've tried a couple of times to get a completel successful installation and always ran into database problems - it seems that the upgrade process is not working correctly or the instructions howto correctly upgrade to V6.x are incomplete or incorrect.
I found out that doing a deinstall on joomla3 and reinstall kunena V6 on joomla4 does not work as the database was not correctly upgraded (or not upgraded at all). Therefore I did the database upgrade manually based on RC1's - database upgrade data. 

I did not try to upgrade a deactivated kunena v5 on Joomla v4 - may be this could have resulted in a successful install.
Is there any doc describing this?

**Comment by xillibit** [comment]
If you have done an install of K6.0 and it hasn't worked properly it could have some Kunena entries in the table #__mail_templates. If you have some entries for Kunena 6.0 in the table #__kunena_version  the update process will get the most recent version and do the update from there.
