### ISSUE TITLE
Click on Last Post leads to the first post

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8949]
**Describe the bug**
Click on Last Post leads to the first post

**To Reproduce**
1. Go to Recent Topics
2. click on Last Post on the right side of a topic that has multiple replies

**Actual result**
It leads to the first post

**System information**
- Joomla version: 4.1.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC3-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.28 and 8.0.13 
- Database version: 10.5.11-MariaDB and 10.4.22-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I'am not able to reproduce it : 

https://user-images.githubusercontent.com/876395/164721027-595c2917-a935-40e8-93a4-09f5d3ed22fd.mp4

**Comment by rich20** [comment]
Try it with a topic which has more than one page

**Comment by xillibit** [comment]
The topic on the video has two pages

**Comment by rich20** [comment]
I've deleted the complete installation and restored again. Now it works.
