### ISSUE TITLE
Issues with mail notifications

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#8979]
Tested on RC3-dev-2022.05.09
[x] **Category subscription** - success
[x] **Topic subscription** - fixed now with last commit
[ ] **Report message**
- issue with key string with variables not replaced : 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/876395/169664534-7e561398-1938-4771-943a-cd3a5e2fa32c.png)
- ~~admin gets mail only if there is no moderator (is it correct?)~~ it's the same behaviour than K5.2
- ~~no content~~
- ~~small blemish (it lacks the colon between the subject)~~

**Comment by jschmi102** [comment]
hi

notification **only** works for moderator not for owner or subscriber of topic.
Found that moderator gets successfully email notification if a new reply has been entered  - but if moderator or any other user replies to topic,  subscriber (or owner) of topic will  not be informed.
