### ISSUE TITLE
Language string missing

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#8985]
**Describe the bug**
COM_KUNENA_RECAPTCHA language string is missing

**Screenshots**
![image](https://user-images.githubusercontent.com/2733197/167887020-18d54302-1219-4d49-8e60-1c5b9d684c91.png)

**Comment by rich20** [comment]
Confirmed. This language string is not present in any ini file. It belongs to this code:
src/site/template/aurelia/layouts/topic/edit/default.php:501:	`<?php echo Text::_('COM_KUNENA_RECAPTCHA'); ?>`
