### ISSUE TITLE
No working smilies with newly installed Kunena

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8989]
**To Reproduce**
1. install a clean Kunena
2. install the sample data
3. go back to Kunena -> Emoticons

**Actual result**
You can see some svg smilies, but none of them work. You can try it in the frontend. 

**Additional context**
Smileys only work if you upgrade Kunena 5.2 to K6.0, because the migrated png smileys are available.

**System information**
- Joomla version: 4.1.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC3-GIT
- Kunena template: Aurelia
- Php version: 7.4.28 and 8.0.13 
- Database version: 10.5.11-MariaDB and 10.4.22-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Some smileys aren't displayed in the "insert smiley" dialog : 
![image](https://user-images.githubusercontent.com/876395/170825823-61fbd3b6-0610-4c56-8ab9-9f46a471034b.png)

And then when submit message : 
![image](https://user-images.githubusercontent.com/876395/170825836-03e91681-b7e7-4ea3-81a8-75015356d6b9.png)

**Comment by rich20** [comment]
I do not see any difference. The smiley list is still incomplete and the few smileys are not usable because they are huge in the post.

**Comment by xillibit** [comment]
I have forgot a part

**Comment by rich20** [comment]
## Backend
- [ ] the smiley list is not complete  (see image). Either we shoud remove these links, or add the missing smileys
- [ ] If you want edit a smiley, it will displayed extremely large

**This is a part of the backend list, much more are missing**
![Bildschirmfoto vom 2022-05-29 03-37-28](https://user-images.githubusercontent.com/888847/170848734-8bafc0aa-5760-410d-868f-ae12234bb03c.png)

## Frontend
- [ ] The smiley modal is still not complete
- [ ] Smileys in messages have size 100 x 100 px
- [ ] Smileys in messages are positioned in the center
- [ ] If you go to the source code and switch back, smileys are displayed extremely large in the editor
- [ ] If you edit a message, smileys are displayed extremely large in the editor

**Smiley modall**
![Bildschirmfoto vom 2022-05-29 03-52-47](https://user-images.githubusercontent.com/888847/170849101-16e133f5-0da6-4808-99a9-da9c666acec8.png)

**Editor**
![Bildschirmfoto vom 2022-05-29 04-06-00](https://user-images.githubusercontent.com/888847/170849124-4999acc8-921a-4f3c-9984-97caf51ee81d.png)

**Message**
![Bildschirmfoto vom 2022-05-29 04-05-25](https://user-images.githubusercontent.com/888847/170849189-ab28063a-e804-48d9-945d-92626362cfb5.png)

**Comment by rich20** [comment]
Fixed by this merge: https://github.com/Kunena/Kunena-Forum/pull/9069
