### ISSUE TITLE
Category manager - The windows of "Access level' and "User Groups Allowed To Post" are a little bit small

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#8992]
**Describe the bug**
https://www.kunena.org/forum/k-6-0-support/165006-some-questions-after-installation-of-kunena-6#223116

![image](https://user-images.githubusercontent.com/888847/168112770-3aac49e8-b397-4e26-b327-6b35c34e8390.png)

**System information**
- Joomla version: 4.1.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC3
- Kunena template: Aurelia
- Php version: 7.4.28 and 8.0.13 
- Database version: 10.5.11-MariaDB and 10.4.22-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Solved by https://github.com/Kunena/Kunena-Forum/commit/ebb4c2a8a7402d843e2ee431d4854e7fea1238fc and https://github.com/Kunena/Kunena-Forum/commit/12b93fd95aa775d5b51c188c2d44bb185629825b : 

![image](https://user-images.githubusercontent.com/876395/184237235-f78a3abf-7ac4-4058-89b6-8c0227a46c63.png)
