### ISSUE TITLE
Announcement not displayed

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#8996]
**Describe the bug**
Announcements not displayed

**To Reproduce**
create an anouncement, publish it and make sure all display options are correct
also check if show announcements in config is set to yes

**Expected behavior**
announcement displayed on forum pages

**Actual result**
announcement not displayed on any forum page

**System information (please complete the following information)**

Joomla version: 4.1.3
Kunena version: K6.0.0 RC3

**Comment by rich20** [comment]
I cannot reproduce this problem, the announcement is displayed. But I get an error when I delete an announcement. Maybe this is related?

**404 View not found [name, type, prefix]: announcement, html, site**

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/MVC/Controller/BaseController.php:903
2 | Joomla\CMS\MVC\Controller\BaseController->getView() | JROOT/libraries/kunena/src/Controller/KunenaController.php:413
3 | Kunena\Forum\Libraries\Controller\KunenaController->display() | JROOT/libraries/kunena/src/Controller/KunenaController.php:348
4 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:239
5 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:113
6 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:204
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:243
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
11 | require_once()

**Comment by Ruud68** [comment]
> I cannot reproduce this problem, the announcement is displayed. But I get an error when I delete an announcement. Maybe this is related?

Where is it displayed? Also e.g. for visitors on the recent topics page or category index page? That is the issue for me.
When going to /announcement/listings I see the announcements and I can open them there, but that is not where i am missing them.

in the below gif you see the announcement as item, but not on the recent topics page (or any other page)
![announcements](https://user-images.githubusercontent.com/2733197/169080293-9a7815c1-7bfd-40f5-aab8-62fafa3f6582.gif)

**Comment by rich20** [comment]
What view is that? I don't see buttons or the title in your .gif
<br />
![Bildschirmfoto vom 2022-05-18 18-07-58](https://user-images.githubusercontent.com/888847/169091458-ffedc0f2-d29d-488b-bbca-98a34bd1840d.png)

**Comment by Ruud68** [comment]
There are no buttons because I am not logged in, so it just shows the message. The buttons are shown when logged in.

I am not logged in to show that the message is available for the visitor: it is only not showing on e.g. recent topics view

**Comment by rich20** [comment]
I found this error message in this context. If you unpublish the announcement and you call as guest this address .../forum/announcement/id-xx you get the error message below instead of 403 Forbidden:

Error in layout Widget/Error: Property "message" is not defined in ..:/components/com_kunena/template/aurelia/layouts/widget/error/default.php on line 20
Layout was rendered in .../components/com_kunena/template/aurelia/layouts/page/default.php on line 48

**Comment by Ruud68** [comment]
okay, now I feel stupid :S, for some reason everytime I build my changes it resets the showannouncement back to no....
Closing this one, sorry for the false alarm :)
