### ISSUE TITLE
Template Edit CSS and Edit SCSS buttons not working

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#8997]
**Describe the bug**

**To Reproduce**
select template
click edit css or edit scss

**Expected behavior**
edit screen for css or scss

**Actual result**
page reloads, nothing (visible) happens

**Screenshots**
![Peek 2022-05-13 14-07](https://user-images.githubusercontent.com/2733197/168279994-790b1927-1b75-4aa3-a855-5cea8d1f9e93.gif)

**System information (please complete the following information)**

Joomla version: 4.1.3
Kunena version: K6.0.0RC3

**Comment by rich20** [comment]
https://github.com/Kunena/Kunena-Forum/issues/8547 It's the same, so I'll close the other one.

**Comment by Ruud68** [comment]
sorry, didn't check for duplicates, was doing this quickly because otherwise i would forget :)

**Comment by rich20** [comment]
Not a problem :)

**Comment by erikthegamer1242** [comment]
Sorry for necroposting but I am having the same issues and just wondering when will it be resolved?

**Comment by rich20** [comment]
Now we have these errors

**Edit CSS**

Warning: foreach() argument must be of type array|object, bool given in /.../administrator/components/com_kunena/tmpl/template/choosecss.php on line 47

**Edit SCSS**

 | Function | Location
1 | () | JROOT/libraries/src/MVC/View/HtmlView.php:416
2 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:199
3 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Template/HtmlView.php:87
4 | Kunena\Forum\Administrator\View\Template\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:635
5 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:55
6 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:668
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:139
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:351
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:139
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:182
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:290
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
13 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: 4.2.1-rc3
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.3-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by erikthegamer1242** [comment]
How did you get the logs?

**Comment by xillibit** [comment]
You need to apply the last change : https://github.com/Kunena/Kunena-Forum/pull/9227 and doing edit CSS

**Comment by rich20** [comment]
It seems to be a problem with the upper case letters and the resulting different paths. If I replace the S with a lower case letter in both the chooseScss and editScss files, the edit window opens and a custom.scss is also created. https://github.com/Kunena/Kunena-Forum/tree/K6.0/src/admin/tmpl/template
However, the entered content is not saved.

The same should be the case with edit Css, but here the following error occurs, so I cannot test it.
Warning: foreach() argument must be of type array|object, bool given in /.../administrator/components/com_kunena/tmpl/template/choosecss.php on line 47

**Comment by xillibit** [comment]
Now it can loads the differents CSS and SCSS files, but i need to work another time on it

**Comment by rich20** [comment]
> Now it can loads the differents CSS and SCSS files, but i need to work another time on it

Ok. These errors are still present at the moment.

### Edit CSS

- [ ] No custom.css is created
- [ ] When you open a CSS for editing, this error occurs: 
Warning: Undefined property: Kunena\Forum\Administrator\View\Template\HtmlView::$cssPath in /.../administrator/components/com_kunena/tmpl/template/editcss.php on line 39

### Edit SCSS

- [ ] Codes entered in the custom.scss are not saved
- [ ] Clicking on Edit SCSS and Cancel gives this error:

500 Layout default not found.

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/MVC/View/HtmlView.php:416
2 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:199
3 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Template/HtmlView.php:128
4 | Kunena\Forum\Administrator\View\Template\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:635
5 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:55
6 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:668
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:139
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:351
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:139
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:182
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:290
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
13 | require_once() | JROOT/administrator/index.php:32
