### ISSUE TITLE
Call to a member function getLink() on null - K6.0.0 Latest module (beta)

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9003]
**To Reproduce**
1. Go to 'admin Joomla > Latest module'
2. Click on 'Category Filter set to "Show categories" > "User Avatar set to YES"
3.Go to FrontEnd

**Actual result**
Call to a member function getLink() on null 

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Cassiopeia

**Comment by rich20** [comment]
Confirmed.

Call stack
--
# | Function | Location
1 | () | JROOT/modules/mod_kunenalatest/tmpl/default_row.php:25
2 | include() | JROOT/libraries/kunena/src/View/KunenaView.php:715
3 | Kunena\Forum\Libraries\View\KunenaView->loadTemplateFile() | JROOT/components/com_kunena/src/View/Topics/HtmlView.php:380
4 | Kunena\Forum\Site\View\Topics\HtmlView->displayTopicRows() | JROOT/components/com_kunena/src/View/Topics/HtmlView.php:252
5 | Kunena\Forum\Site\View\Topics\HtmlView->displayRows() | JROOT/modules/mod_kunenalatest/tmpl/default.php:25
6 | include() | JROOT/libraries/kunena/src/View/KunenaView.php:647
7 | Kunena\Forum\Libraries\View\KunenaView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:220
8 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/libraries/kunena/src/View/KunenaView.php:544
9 | Kunena\Forum\Libraries\View\KunenaView->render() | JROOT/components/com_kunena/src/View/Topics/HtmlView.php:149
10 | Kunena\Forum\Site\View\Topics\HtmlView->displayDefault() | JROOT/libraries/kunena/src/View/KunenaView.php:283
11 | Kunena\Forum\Libraries\View\KunenaView->displayLayout() | JROOT/libraries/kunena/src/Forum/KunenaForum.php:542
12 | Kunena\Forum\Libraries\Forum\KunenaForum::display() | JROOT/modules/mod_kunenalatest/class.php:108
13 | ModuleKunenaLatest->_display() | JROOT/libraries/kunena/src/Module/KunenaModule.php:112
14 | Kunena\Forum\Libraries\Module\KunenaModule->display() | JROOT/modules/mod_kunenalatest/mod_kunenalatest.php:39
15 | include() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:54
16 | Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:57
17 | Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch() | JROOT/libraries/src/Helper/ModuleHelper.php:295
18 | Joomla\CMS\Helper\ModuleHelper::renderRawModule() | JROOT/libraries/src/Helper/ModuleHelper.php:167
19 | Joomla\CMS\Helper\ModuleHelper::renderModule() | JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:102
20 | Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render() | JROOT/libraries/src/Document/HtmlDocument.php:706
21 | Joomla\CMS\Document\HtmlDocument->countModules() | JROOT/templates/cassiopeia/index.php:109
22 | require() | JROOT/libraries/src/Document/HtmlDocument.php:779
23 | Joomla\CMS\Document\HtmlDocument->_loadTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:838
24 | Joomla\CMS\Document\HtmlDocument->_fetchTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:641
25 | Joomla\CMS\Document\HtmlDocument->parse() | JROOT/libraries/src/Application/CMSApplication.php:1025
26 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:802
27 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:284
28 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
29 | require_once() | JROOT/index.php:32

</div>

**Comment by xillibit** [comment]
Fixed by : https://github.com/Kunena/Kunena-Addons/commit/11608e1d04e2af86867b20695754250838535711
