### ISSUE TITLE
Template Aurelia - Load Tooltips bug

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9004]
**To Reproduce**
1. Go to 'Kunena > Templates > Aurelia'
2. Click on 'Load Tooltips > NO'
3. Go to frontend
4. See error Rendering Error in layout > User/Profile, Message/Item etc...

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Cassiopeia

**Comment by Leen29** [comment]
then i get
Kunena\Forum\Libraries\Template\KunenaTemplate::tooltips(): Return value must be of type string, none returned

**Comment by Ruud68** [comment]
@Leen29 did you try this PR https://github.com/Kunena/Kunena-Forum/pull/9010 ?

**Comment by LinelabCZ** [comment]
Fixed. Thank you.

**Comment by Leen29** [comment]
but now applied your fix only my line numbers didn't quite match 
but it seems to work well now.
so thanks
