### ISSUE TITLE
Class 'Html' not found  - K6.0.0 Latest module (beta)

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9005]
To Reproduce
    Go to 'admin Joomla > Latest module'
   SET "More link" to YES
    Go to FrontEnd
    See error

Actual result
Class 'Html' not found

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Cassiopeia

**Comment by Leen29** [comment]
yes that's right also happens on my site 
and my logo image is then shown twice
![error1](https://user-images.githubusercontent.com/17086048/168768323-23d6724a-e692-4be3-8113-6b107422ab5c.jpg)

**Comment by xillibit** [comment]
Fixed by https://github.com/Kunena/Kunena-Addons/commit/086544c9c0f1141c218a9f719826107eb7b6a316

**Comment by Leen29** [comment]
tested the modified changes and works well here too
