### ISSUE TITLE
Field 'status_text' doesn't have a default value - Synchronize Users

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9009]
**To Reproduce**
1. Go to 'Admin Joomla > Tools > Synchronize Users with Joomla users'
2. Click on ' Sync'

**Actual result**
Error: Field 'status_text' doesn't have a default value 

**System information (please complete the following information)**

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Php version: 7.4.28

**Comment by LinelabCZ** [comment]
The same error appears when I delete messages
Trashbin > MysqliStatement.php with message Field 'status_text' doesn't have a default value

**Comment by LinelabCZ** [comment]
Delete message frontend > Exception throw at line 435 in file libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php with message Field 'status_text' doesn't have a default value

**Comment by xillibit** [comment]
> Error: Field 'status_text' doesn't have a default value

I have tried with the following but not able to reproduce : 
![image](https://user-images.githubusercontent.com/876395/170825673-2dc5d3e0-c63b-40e1-99d6-cf0bb4c9827e.png)

**Comment by xillibit** [comment]
Please say if use mysql or mariadb and which version, if you have still the issue with recent version of Kunena please re-open a new issue
