### ISSUE TITLE
Language string issue

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9013]
**Describe the bug**
in ./src/site/template/aurelia/layout/user/profile/default.php the following language string is used:
```
		<span class="heading btn btn-outline-primary border btn-xs heading-less hasTooltip"
              style="display:none;"
              data-original-title="<?php echo Text::_('COM_KUNENA_USER_PROFILE_TOOLTIP_LABEL_SCSS') ?>"><?php echo KunenaIcons::arrowup(); ?><?php echo Text::_('COM_KUNENA_USER_PROFILE_BUTTON_LABEL_SCSS') ?></span>
```
I think this should be COM_KUNENA_USER_PROFILE_TOOLTIP_LABEL_LESS and COM_KUNENA_USER_PROFILE_BUTTON_LABEL_LESS but that this was replaced by _SCSS by a less to scss refactor action?

**Comment by xillibit** [comment]
In Kunena 6.0 we are using SCSS instead of LESS so need to change these strings

**Comment by Ruud68** [comment]
No, the text on the button should be l'ess' as opposed to 'more' :)
See the context where the string is used

**Comment by xillibit** [comment]
yes there are mix in there
