### ISSUE TITLE
Uundefined  Class 'Forum' not found - Smart Search

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9022]
**To Reproduce**
1. Go to 'Backend Joomla > Smart Search >  Indexed Content'
2. Click on 'Index'

**Actual result**
Popup > Uundefined  Class 'Forum' not found 

Joomla version: 4.1.3
Kunena version: 6.0.0-RC3
Php version: 7.4.28
Plugin Kunena - Finder Integration, Smart Search - Kunena Forum enabled

**Comment by LinelabCZ** [comment]
Resolved. Language override problem from previous version.

**Comment by LinelabCZ** [comment]
Hi, I'm sorry, but the problem still persists.

**Comment by rich20** [comment]
Problem confirmed.

**Comment by xillibit** [comment]
@LinelabCZ @rich20 : can-you test it please ?

**Comment by rich20** [comment]
Hmm... I get still the same error
