### ISSUE TITLE
Profile for "Name" is missing

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9028]
Profile for "Name" is missing. (When I change the frontend language to English, the user's name is displayed.)

`COM_KUNENA_VIEW_USER_DEFAULT = "Profile for %s"`

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Php version: 7.4.28
Cassiopeia

**Comment by xillibit** [comment]
In which language it doesn't work ?

**Comment by LinelabCZ** [comment]
Czech language.

**Comment by xillibit** [comment]
Please try the files modified in this commit : https://github.com/Kunena/Kunena-Forum/commit/d36cff64f94bc07a41009b6e8657a9e8d08e2c9a#diff-7fbe1978d32945045c7785692db351a14bb08b01cbb34fc5c6c0ba6530293707
