### ISSUE TITLE
We need this string in the backend views.ini - COM_KUNENA_USRL_EMAIL = "E-mail"

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9032]
**Describe the bug*
If you go to Kunena user management and open the sorting table, you will see this problem.
<br />
![Bildschirmfoto vom 2022-05-19 19-44-13](https://user-images.githubusercontent.com/888847/169364483-bbb9b893-f37d-4b43-a1a1-74641d01704d.png)

**Comment by Leen29** [comment]
some tests show that at
"mysites\administrator\components\com_kunena\language\en-GB\en-GB.com_kunena.views.ini"
This line was missing "COM_KUNENA_USRL_EMAIL = "Email""
put this in now name Email.
But I don't know if it works that way for all languages.
![bijmakenl](https://user-images.githubusercontent.com/17086048/169643995-99ec07f0-8caa-4843-99fb-981e9890e09d.JPG)
![Emallivesite](https://user-images.githubusercontent.com/17086048/169643998-ee94cd15-052d-44e0-974f-d2d2d7582670.JPG)

**Comment by xillibit** [comment]
When the en-GB is updated and send on transifex then the others language get the new changes
