### ISSUE TITLE
"Thank you" section/widget issue

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9052]
The "Thank you" section/widget will not appear after the message. 
"horizontal-message" layout

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Php version: 7.4.28
Cassiopeia

**Comment by xillibit** [comment]
I don't see what you mean : 
![image](https://user-images.githubusercontent.com/876395/170572123-37b63929-1ede-40f6-936c-25789c6907cb.png)

**Comment by LinelabCZ** [comment]
![Screenshot 2022-05-27 at 08-40-04 Kunena 6 0 RC3 Released for Joomla! 4 1](https://user-images.githubusercontent.com/105653787/170645493-7d9003d8-67ef-4d87-9b09-2cf8ff33ccc0.png)

**Comment by rich20** [comment]
Is that what you mean? I see the unthank button, but I can't see the thank you, although it should be here. 
<br />
![image](https://user-images.githubusercontent.com/888847/170717616-60f454be-79c4-4c4a-97ee-4fe95feef953.png)

**Comment by LinelabCZ** [comment]
Yes, that's the problem.
