### ISSUE TITLE
Quality of thumbs + js error

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9053]
The quality of the cropped thumbnails is very poor.

```
bootstrap.Popover is not a constructor
    popoverList components/com_kunena/template/aurelia/assets/js/main.js
```

Joomla version: 4.1.3
Kunena version: 6.0.RC3
Php version: 7.4.28
Cassiopeia

**Comment by Ruud68** [comment]
popover error should be fixed in dev version (so not yet in RC3)

**Comment by xillibit** [comment]
for me it works
