### ISSUE TITLE
Failed to start the session because headers have already been sent by "" at line 0.

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9060]
**Describe the bug**
when submitting a new topic or reply to topic there is a runtime exception: Failed to start the session because headers have already been sent by "" at line 0.

**this started directly after upgrading Joomla from 4.1.3 to 4.1.4**

**To Reproduce**
![Peek 2022-05-26 11-03](https://user-images.githubusercontent.com/2733197/170456661-551ca8ce-f5fc-4d14-9319-2565a0334967.gif)

Joomla version: 4.1.4
Kunena version: latest dev build (5 minutes ago) v6.0.0-RC4-DEV_2022-05-26
Php version: 7.4.29
Database version: mysql 8.0.29-0ubuntu0.20.04.3

**Additional context**
no issue on Joomla 4.1.3, issue started after upgrading Joomla!

**Comment by Ruud68** [comment]
on production this error is not present, but when I restore my production site back to localhost (development) then I have the issue again. So must be something localhost related.
makes it difficult to develop / test :(

Anyone else seeing this behavior on localhost?

**Comment by rich20** [comment]
I have found the cause and can reproduce this error. Sending mails does not work on the local server. When you try a Joomla test mail, you get this hint: The mail function could not be instantiated.
Therefore, you will get this error if you have users with subscriptions (or settings where moderators are notified about new posts).
If you set in the Kunena configuration (tab General) Send E-mails to Users = No, the error should be gone..

**Comment by Leen29** [comment]
I suddenly noticed this problem too.
and what Rich mentions here works the same way here.
on test send the email Kunena turned off everything goes well. is indeed correct now turned on and then error occurs again on the local pc with xampp and wamp servers

**Comment by Leen29** [comment]
local with xammp 
if I set in Kunena Forum: Configuration tab subscriptions Allow Subscriptions to no.
and in the security tab E-mail Moderators and E-mail Administrators on Unapproved Posts setting
works locally here now.
but I think  this will be the same as in the kunena configuration Send E-mails to Users to no.
![allowsubscriptkunena](https://user-images.githubusercontent.com/17086048/170963475-957d5b95-15f9-4f33-9466-aaa5f9a22e10.jpg)
![hierzithetergens](https://user-images.githubusercontent.com/17086048/170963543-09dbca33-849e-4683-bfa7-e7697a9f21af.JPG)

**Comment by xillibit** [comment]
The issue showed here is when PhpMailer try to send the mail, it trying to do it infinitely.

**Comment by Leen29** [comment]
yes that is the case with my test.
but when I set it(joomla) on php mail happens
this error also as with kunena configuration tab security
Set Email Moderators and Email Administrators to all new mail.

**Comment by Ruud68** [comment]
test please: https://github.com/Kunena/Kunena-Forum/pull/9071

**Comment by Leen29** [comment]
i tried the changes on wampserver webtest
no real error message anymore but warning
that mailer could not send.
he then returned to the message with blank editor screen
but answer saved in topic
![zendmail1](https://user-images.githubusercontent.com/17086048/171371830-77c47cec-56b2-41ef-a594-36cc3926a808.jpg)
![mailer1](https://user-images.githubusercontent.com/17086048/171371842-eeb7dbee-0b50-462a-bbbd-d635671e5781.jpg)
![slaatwelop1](https://user-images.githubusercontent.com/17086048/171371860-fcf2a040-8bcd-4ff5-b1fd-b789f938d1c3.JPG)

**Comment by Ruud68** [comment]
Hi Leen, so the messages are working and correctly displayed and not hard breaking the site. That is good. :)
There was no change in the logic of where to return to after an error occurred, I think that is set to return to the page where you where on. So this is as designed.
Although I agree that it can be confusing as the message was posted correct (and it should say that with a success message).

So this is due to showing the error to the users, if we do not do that then you will get a success post message, but no error displayed (other then in the log file).

I think one of the maintainers should decide here what to do in case of an error.

**Comment by Leen29** [comment]
Yes that's right
I notice that with a quick reply message is immediately saved and editor is closed and only notification comes
"Could not execute: /usr/sbin/sendmail"
but I just do answer(replay), so the "Could not execute: /usr/sbin/sendmail" message comes but I also return in message with empty editor screen.
 as well with a test in Wampserver php 7.4.27  and also test Xammp server PHP Version 8.0.15

**Comment by Ruud68** [comment]
@Leen29 could you comment out the throw $e (you have added it via the PR in file src/libraries/kunena/src/Email/KunenaEmail.php) and see if that is more conform expectations? You will then not receive an error but if correct a success message and the redirect etc. should be accordingly

**Comment by Leen29** [comment]
nice that is indeed then i get
"Your message has been successfully posted."
and also looking forward to an overview of the topi
![okehelpt](https://user-images.githubusercontent.com/17086048/171378484-f54ed7b2-f37a-4d3b-a580-5fffb66871ce.jpg)
c

**Comment by Ruud68** [comment]
ok, I will remove the throwing of the error for further handling, if the maintainers want it in we know where to add it :)

**Comment by Leen29** [comment]
yes it is clear
I have now also made this adjustment on a live test and it seems to have no side effects either

**Comment by Ruud68** [comment]
@Leen29  and emails are send correct on live site?

**Comment by Leen29** [comment]
yes they are coming in but
I still on in a domain NL environment
that I do get the E-mail but only with content text "COM_CONFIG_SENDMAIL_BODY "
And on another domain EU, the E-mail content also comes with it, so that's good.
I must have set something different in the Dutch Domain settings than in the EU domain, but so far I have not been able to find it.
The strange thing is, however, that the Joomla test mails do arrive well. (so that's why I can't find whether it's in my settings or in Kunena test version)

**Comment by Ruud68** [comment]
The contents of the mail (I also noticed the COM_CONFIG_SENDMAIL_COPY which is a totally unrelated email string for kunena, so no clue as to why this is being used) is not 'fixed' by this PR.

**Comment by Leen29** [comment]
partly found, it turns out that on test domain nl
at administrator Mail Templates kunena was missing.
and in hpmyadmin there were still old wrong remains
and at Eu domain they were there
so imported this via phpmyadmin and now it works as
my eu domain.
![mailtestzes](https://user-images.githubusercontent.com/17086048/171412641-c877978c-136a-4c3a-a942-82f8679fee18.jpg)
![mainieuwsberichten](https://user-images.githubusercontent.com/17086048/171412673-7857070c-e469-4a4e-b2b1-9f7b4dc68a16.jpg)
![phpmyadminmailtestzes](https://user-images.githubusercontent.com/17086048/171412932-72ba7632-1620-4249-bbdc-9e2b1d6f6258.jpg)
![phpmyadminmainieuwsberichten](https://user-images.githubusercontent.com/17086048/171412952-ae803e32-0520-44c8-b403-8d9a4d30f0d7.jpg)
![zomailin](https://user-images.githubusercontent.com/17086048/171413877-b91a1b43-2115-4e51-80d7-5500a7d98cb8.jpg)

**Comment by Ruud68** [comment]
top: good find, there is actually a bug here, will create a new one for this
