### ISSUE TITLE
Delete last post issue

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9061]
When I delete the last post in a discussion, it causes the topic to no longer correctly display the last post (creation date) in the discussion. 
If a previous post was put in the topic e.g. two days earlier, it suddenly shows that the last post was put there last year. 

The point is that such a topic then disappears from the last topics list.

Kunena 6.0.0RC3

**Comment by rich20** [comment]
Confirmed. If you delete the last post, and go to Recent Topics, "Last post by" linked to the first post of the topic.

**To Reproduce**
1. open a topic with severals replies
2. delete the last post of this topic
3. go to Recent Topics

**Result**
"Last post by" shows the creation date of this topic and linked to the first post. This is the reason why a topic is moved too far back in the list of recent topics when the creation date is longer ago.
