### ISSUE TITLE
Kunena 5.2.8 button add ext. does not work

### ISSUE THREAD

**Issue by sietwolt** [Kunena/Kunena-Forum#9072]
The new release Kunena 5.2.8 has solved a lot of problems. However, answering a message it is not possible anymore to use the button Add ext. f.e. a photo. Can this be solved?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 
Kunena version:
Php version:
Database version:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rich20** [comment]
I cannot reproduce this problem.

**Comment by xillibit** [comment]
I can't reproduce the issue, feel free to open a new one with more details if the problem is still here with K5.2.11
