### ISSUE TITLE
Mail Templates not working

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9073]
**Describe the bug**
mail templates are created without extension column

**To Reproduce**
in mail templates extension try to find kunena templates: they are not there.
In the table they are, but are missing the extension column (com_kunena).

**Expected behavior**
mail templates should be created with extension column filled

**Actual result**
they are not and are thus not used

**Screenshots**
![image](https://user-images.githubusercontent.com/2733197/171421931-6b9b4176-2ec6-406a-8537-d69135d13713.png)

**Additional context**
this should be the coe in create_tables.utf8.sql
```
INSERT INTO `#__mail_templates` (`template_id`, `extension`, `language`, `subject`, `body`, `htmlbody`, `attachments`, `params`)
VALUES ('com_kunena.reply', 'com_kunena', '', 'COM_KUNENA_SENDMAIL_REPLY_SUBJECT', 'COM_KUNENA_SENDMAIL_BODY', '', '',
        '{"tags":["mail", "subject", "message", "messageUrl", "once"]}');
INSERT INTO `#__mail_templates` (`template_id`, `extension`, `language`, `subject`, `body`, `htmlbody`, `attachments`, `params`)
VALUES ('com_kunena.replymoderator', 'com_kunena', '', 'COM_KUNENA_SENDMAIL_REPLYMODERATOR_SUBJECT', 'COM_KUNENA_SENDMAIL_BODY', '', '',
        '{"tags":["mail", "subject", "message", "messageUrl", "once"]}');
INSERT INTO `#__mail_templates` (`template_id`, `extension`, `language`, `subject`, `body`, `htmlbody`, `attachments`, `params`)
VALUES ('com_kunena.report', 'com_kunena', '', 'COM_KUNENA_SENDMAIL_REPORT_SUBJECT', 'COM_KUNENA_SENDMAIL_BODY_REPORTMODERATOR', '', '',
        '{"tags":["mail", "subject", "message", "messageUrl", "once"]}');
```
but i cannot do a PR as there are other places (upgrade / install routines) that I have not yet 'mastered' :)

**Comment by xillibit** [comment]
I will take a look to it

**Comment by Leen29** [comment]
at my own test site I had today via phpmyadmin at "xxxxx_mail_templates"
added this code with insert .
the xxxxx_ is of course the Database Tables Prefix  I think Ruud68 has one more line
`INSERT INTO `xxxxx_mail_templates` (`template_id`, `extension`, `language`, `subject`, `body`, `htmlbody`, `attachments`, `params`) VALUES
('com_kunena.reply', 'com_kunena', '', 'COM_KUNENA_SENDMAIL_REPLY_SUBJECT', 'COM_KUNENA_SENDMAIL_BODY', '', '', '{\"tags\":[\"mail\", \"subject\", \"message\", \"messageUrl\", \"once\"]}'),
('com_kunena.reply', 'com_kunena', 'en-GB', 'A new reply has been posted on topic : {SUBJECT}', 'A new reply has been posted on the Forum. Message Subject : {SUBJECT}. Posted by : {NAME}. URL : {MESSAGEURL}. Message: {MESSAGE}', '<p>A new reply has been posted on the Forum. Message Subject : {SUBJECT}. Posted by : {NAME}. URL : {MESSAGEURL}. Message: {MESSAGE}</p>', '', '{\"alternative_mailconfig\":true,\"mailfrom\":\"\",\"fromname\":\"\",\"replyto\":\"\",\"replytoname\":\"\",\"mailer\":\"mail\",\"sendmail\":\"\\/usr\\/sbin\\/sendmail\",\"smtphost\":\"localhost\",\"smtpport\":25,\"smtpsecure\":\"none\",\"smtpauth\":false,\"smtpuser\":\"\"}'),
('com_kunena.report', 'com_kunena', '', 'COM_KUNENA_SENDMAIL_REPORT_SUBJECT', 'COM_KUNENA_SENDMAIL_BODY_REPORTMODERATOR', '', '', '{\"tags\":[\"mail\", \"subject\", \"message\", \"messageUrl\", \"once\"]}'),
('com_kunena.report', 'com_kunena', 'en-GB', 'Message reported {SUBJECT}', 'A message has been reported on the Forum. Message Subject : {SUBJECT}. Posted by : {NAME}. URL : {MESSAGEURL}. Message: {MESSAGE}', '<p>A message has been reported on the Forum. Message Subject : {SUBJECT}. Posted by : {NAME}. URL : {MESSAGEURL}. Message: {MESSAGE}</p>', '', '{\"alternative_mailconfig\":true,\"mailfrom\":\"\",\"fromname\":\"\",\"replyto\":\"\",\"replytoname\":\"\",\"mailer\":\"mail\",\"sendmail\":\"\\/usr\\/sbin\\/sendmail\",\"smtphost\":\"localhost\",\"smtpport\":25,\"smtpsecure\":\"none\",\"smtpauth\":false,\"smtpuser\":\"\"}');`
