### ISSUE TITLE
Controller Kunena\Forum\Site\Controller\Topic\List\ not exist (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9077]
https://github.com/Kunena/Kunena-Forum/pull/9076
1. The TopicListModeratorDisplay.php has been renamed to TopicListingModeratorDisplay.php but the old file remain after an upgrade. Should it be deleted if exists?

2. Now are these errors:

Notice: Trying to get property 'pagesCurrent' of non-object in /.../components/com_kunena/src/Controller/Topic/Listing/ListDisplay.php on line 159

Notice: Trying to get property 'pagesTotal' of non-object in /..../components/com_kunena/src/Controller/Topic/Listing/ListDisplay.php on line 160

Topics Needing Attention (
Notice: Trying to get property 'total' of non-object in /.../components/com_kunena/template/aurelia/layouts/topic/list/default.php on line 54

Rendering Error in layout Topic/List: Argument 1 passed to Kunena\Forum\Libraries\Forum\Category\KunenaCategory::totalCount() must be of the type int, null given, called in /...components/com_kunena/template/aurelia/layouts/topic/list/default.php on line 54 in /.../components/com_kunena/template/aurelia/layouts/topic/list/default.php on line 54
Layout was rendered in /.../components/com_kunena/template/aurelia/pages/topics/moderator/default.php on line 25

**Comment by xillibit** [comment]
The file TopicListModeratorDisplay.php doesn't exist on github, so if you have installed the new build on existing install it has keeped old file

**Comment by rich20** [comment]
> if you have installed the new build on existing install it has keeped old file

Yes, that is what I meant. That's why I asked "should be deleted if it exists?".

**Comment by xillibit** [comment]
yes you can delete it

**Comment by rich20** [comment]
I have already deleted this file in my installation. I just thought if this should happen automatically during the upgrade.

**Comment by Leen29** [comment]
it seems to work with all the latest changes with no error or warnings.
but I can't select or view a moderator topic yet
But it could also be that I'm not doing something right yet
ps
and
I only get a notification when I accidentally log out off the moderator categories
"Rendering Error in layout Widget/Error: Property "message" is not defined in /home/mydomain/public_html/test/components/com_kunena/template/aurelia/layouts/widget/error/default.php on line 20
Layout was rendered in /home/mydomain/public_html/test/components/com_kunena/template/aurelia/layouts/page/default.php on line 48"

![seemstowork](https://user-images.githubusercontent.com/17086048/171825605-35f0f2e6-3183-4396-b889-f9e642eebd71.jpg)
t
