### ISSUE TITLE
Incorrect mail notification for reviewing posts

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9081]
**To Reproduce**

1. use the default settings E-mail Moderators and E-mail Administrators = Unapproved Posts
2. set a category to review
3. reply with a normal user or create a topic in this category

**Actual result**

- [ ] mail subject "A message has been reported on topic"
- [ ] maill message "A new reply has been posted on the Forum" (in K5.2 we had: A new post has been made to a category to which you have assigned as moderator on the Kunena)
- [ ] admins receive the mail twice

**System information**
- Joomla version: 4.1.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC4-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.28 and 8.0.16 
- Database version: 10.5.11-MariaDB and 10.4.22-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
@rich20 : The first two points are already fixed if i'am remember right ?

**Comment by xillibit** [comment]
@rich20 : this one could be potentialy solved too with the last changes on K6.0 ?

**Comment by xillibit** [comment]
Fixed by : https://github.com/Kunena/Kunena-Forum/commit/7e4f3161bac19c5d836deed6028b757b972fcf65
