### ISSUE TITLE
Guests allowed to view images / attachments even if set to NO

### ISSUE THREAD

**Issue by pippo8765** [Kunena/Kunena-Forum#9113]
Parameter Allow images / attachments for guests set to No, but they ARE allowed to view images / attachments in post as well as clickable thumbs in post bottom. Template Aurelia.

To reproduce just set this to No and attach image in topic. Do not login and visit topic.

**Expected behavior**
Dissallowed view.

Joomla version: 4.1.4
Kunena version: 6.0
Php version: 8.x

**Comment by Ruud68** [comment]
@pippo8765 can you test https://github.com/Kunena/Kunena-Forum/pull/9117 ?

**Comment by rich20** [comment]
- [x] Success
