### ISSUE TITLE
The Kunena menu type "Create New Topic" has no selection options

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9123]
**Describe the bug**
https://www.kunena.org/forum/k-6-0-support/165212-k6-0-0-create-a-subject,-no-more-category-option
Confirmed.
The Kunena menu type "Create New Topic" has no selection options. It is not possible to select a category in which topics should be created by default.

**System information**
- Joomla version: 4.1.5-rc3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.1-DEV
- Kunena template: Aurelia
- Php version: 8.0.16
- Database version: 10.5.15-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Leen29** [comment]
Hi Rich,
I think it's about the adminstrator section when creating a new kunena menu item category-list, there you could previously choose which category should be displayed.
and also create a new topic
![k5categorielist](https://user-images.githubusercontent.com/17086048/174483771-23d7239d-aa4e-40ee-a1a4-dc208c808219.jpg)
![k5newtopic](https://user-images.githubusercontent.com/17086048/174483777-3168645c-d62d-4e9c-b000-2857cb9db5bb.jpg)
![k6newtopic](https://user-images.githubusercontent.com/17086048/174483782-7b2a7671-d6b4-4ddf-acce-3194b94767c9.jpg)
![k6categorielist](https://user-images.githubusercontent.com/17086048/174483783-fe1bedb5-8d2a-4135-b758-b34c1959cdbe.jpg)
c

**Comment by Leen29** [comment]
I forgot to mention that if you create a menu item topic, this one at the front then suddenly gives the option to choose category
![K6frontmenuitem](https://user-images.githubusercontent.com/17086048/174484152-7179f803-1a96-47fe-b75d-0a8e2ef81496.jpg)
.

**Comment by rich20** [comment]
@Leen29 With this option it will create the topics in the selected category, regardless of how the categories are sorted.

------------------------------------------------------

Works now
