### ISSUE TITLE
CKEditor : It lacks the button for Fontsize

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9126]
**Describe the bug**
https://www.kunena.org/forum/36-German/165224-fehlender-button-f%C3%BCr-schriftgr%C3%B6%C3%9Fe
Confirmed

Since the CKeditor update to [version 4.19.0](https://github.com/Kunena/Kunena-Forum/pull/9097) lacks the fontsize button

**Comment by xillibit** [comment]
It should be the case on K6.0 too

**Comment by rich20** [comment]
Yes, this is also the case with K.6
