### ISSUE TITLE
Bootstrap loaded in search page(s) even if set to DO NOT LOAD BOOTSTRAP in template

### ISSUE THREAD

**Issue by pippo8765** [Kunena/Kunena-Forum#9131]
I have bootstrap of my own with Joomla template, so I don't need core's one. So I choose not to load bootstrap in kunena template config, because it creates conflicts, but it still loads on search pages

Set as described above, so set kunena template not to load bootstrap, go to forum search and you'll see bootstrap loaded.

Problem location: \components\com_kunena\template\aurelia\layouts\search\form\default.php
Line 25: HTMLHelper::_('dropdown.init');

This creates dropdown object which then calls init and whole Joomla's core Bootstrap in \libraries\src\HTML\Helpers\Dropdown.php

Possible solution: adding "if" with "params->get('bootstrap')" in \components\com_kunena\template\aurelia\layouts\search

Joomla version: 4.x
Kunena version: 6
Php version: 8.x

**Comment by Ruud68** [comment]
hi @pippo8765 , can you test #9132
