### ISSUE TITLE
New users can add picture in their messages or profile even if it is not allowed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9142]
**To Reproduce**
New users can add picture in their messages or profile even if it is not allowed

1. Configuration -> Security - set Prevent that new users are able to add url and image in his messages or profile to Yes.
2. login with a new user and upload an image

**Result**
The image is uploaded and will be shown
If you copy the bbcode, the image can be used in the signature, even when the message wil not be submitted

**Additional context**
It is not a security issue, as this feature is disabled by default, but it should still work.

**System information**
- Joomla version: 3.10.11-dev
- Kunena version: 5.2.10-DEV
- Kunena template name and version: Crypsis and Blue Eagle 1.6.7-dev
- Php version: 8.0.16
- Database version: 10.5.15-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Do-you have reproduced the issue on K6.0 ?

**Comment by rich20** [comment]
Yes, it's the same with K6.0.
