### ISSUE TITLE
Changing username in frontend causes error. J4.1.5 - K6.0.0

### ISSUE THREAD

**Issue by nZambi-** [Kunena/Kunena-Forum#9150]
Joomla! 4.1.5 Stable (Fresh Install)
Kunena 6.0.0_2022-06-10 (Fresh Install)
When a user changes username in frontend it fails with error.
In **components\com_kunena\src\Controllers\UserController.php** beginning at line **600** we attempt to change the username for the user in the session table.
Trying to get **$table = Table::getInstance('session', 'JTable')** returns False and consequently **$table->load($session->getId())**  triggers the error **Call to a member function load() on bool**

I know there are breaking changes in J4 regarding session but have not spent time looking into that (yet). Is this process even necessary though? The session may be getting updated by J! when the user is saved. I simply commented out the session table **Get**, **Load**, **Update**, **Store** and the name change saves properly AND the session table is updated anyway.

**To Reproduce**
- Enable Change Username in J!
- Enable Error Reporting
- Edit Kunena profile in frontend changing the Username
- Save

**Expected behavior**
Profile Saves, returns to Profile

**Actual result**
Fails with PHP Error - Call to a member function load() on bool 
![Capture](https://user-images.githubusercontent.com/10344273/178080323-3d0159f5-4784-4603-83e7-2582bfad8315.JPG)

**System information (please complete the following information)**
Joomla version: 4.1.5 Stable (Fresh Install)
Kunena version: 6.0.0_2022-06-10 (Fresh Install)
Php version: 7.4
Database version: 10.3.35-MariaDB-log-cll-lve

**Comment by rich20** [comment]
Confirmed

**Tested with**
- Joomla version: 4.1.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.1-DEV
- Kunena template: Aurelia
- Php version: 8.0.20 and 8.1.7
- Database version: 10.5.15-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera
