### ISSUE TITLE
No entries are added to statistics and logs

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9157]
**To Reproduce**
1. select in the configuration (tab Users) - Define if you want to log action or moderation = Yes
2. do an action in the frontend as moderator like permanently delete
3. check the Logs and Statistics

**Actual result**
No new entry

**System information**
- Joomla version: 4.1.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.2-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.15-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Just gived a check the logs are right availaible in backend logs view

**Comment by xillibit** [comment]
I have stats too in backend stats view
