### ISSUE TITLE
Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /.../libraries/src/Installer/InstallerScript.php on line 322

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#9158]
**Describe the bug**
if you install K6 via the Joomla installer, yo get this hint:
 
Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /.../libraries/src/Installer/InstallerScript.php on line 322

Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in /.../tmp/install_62c9d41eed19f/script.php on line 333

I get this hint only with php 8.1.7 not with php 8.0.20

**Comment by xillibit** [comment]
@rich20 : i have fixed the Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in \joomla-42-beta3\tmp\install_62cc5b845d64b\script.php on line 333 for the other one i think is more related to Joomla!

**Comment by rich20** [comment]
Thanks, the one of those two error is gone now.
