### ISSUE TITLE
PHP 8.1 - hints for Deprecated strings

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9162]
### Backend

-  [ ] **Statistics**
`Deprecated : Function strftime() is deprecated in /.../libraries/src/HTML/HTMLHelper.php on line 1199`

-  [ ] **Report configuration settings**
```
Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in
/.../administrator/components/com_kunena/src/Model/ToolsModel.php on line 885

Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in
/.../administrator/components/com_kunena/src/Model/ToolsModel.php on line 885
```

### Frontend

-  [ ] **When Kunena Latest is enabled**
`Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /.../libraries/kunena/src/Forum/KunenaForum.php on line 490`

**System information**
- Joomla version: 4.1.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.2-DEV
- Kunena template: Aurelia
- Php version: 8.1.7
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
> * **Statistics**
>       `Deprecated : Function strftime() is deprecated in /.../libraries/src/HTML/HTMLHelper.php on line 1199`

This is coming from Joomla! libraries

**Comment by xillibit** [comment]
> Deprecated: version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated in
> /.../administrator/components/com_kunena/src/Model/ToolsModel.php on line 885
> 
> Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in
> /.../administrator/components/com_kunena/src/Model/ToolsModel.php on line 885

~I don't see that~ I found it, you have CB installed

**Comment by rich20** [comment]
<strike>I've tested now also local with php 8.1.5. I'ts the same hint as with php 8.1.7. 
Error Reporting must be Maximum.</strike>
Yes, CB is installed but complete disabled.
