### ISSUE TITLE
quick icon update notification not 'translated'

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9165]
**Describe the bug**
![Selection_001](https://user-images.githubusercontent.com/2733197/178231605-f4fbf3cd-2c6d-43af-b1a3-6be3fdb0e4f8.jpg)

**Expected behavior**
it should say that update is available

**Actual result**
language string displayed

Joomla version: 4.1.5
Kunena version: 6.0.1 (with update available for 6.0.1.1)

**Comment by rich20** [comment]
The string is correctly present in the language folder of the plugin, but is not displayed. This string is displayed only if it is included in the com_kunena.sys.ini backend file.
So we should add this string to backend com_kunena.sys.ini:
PLG_QUICKICON_KUNENA_UPDATE_NOW = "Update now!"

**Comment by xillibit** [comment]
we may have the same issue with others strings :

`PLG_QUICKICON_KUNENA_UPDATE_ADDONS = "Update %d add-ons!"`
`PLG_QUICKICON_KUNENA_UPDATE_NOW = "Update now!"`
`PLG_QUICKICON_KUNENA_UPDATE_DISABLED = "Updates disabled"`
`PLG_QUICKICON_KUNENA_COMPLETE_INSTALLATION = "Please complete Kunena installation!"`

**Comment by rich20** [comment]
> we may have the same issue with others strings :

Yes, that is probably possible. Maybe you should add all 4 strings to the kunena.sys.ini.
