### ISSUE TITLE
Messge report : Mails are sent according to the number of moderators

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9203]
**Describe the bug**
https://www.kunena.org/forum/36-German/165645-beitrag-an-moderator-melden
Confirmed

Depending on how many moderators you have, this is how many mails are sent to each moderator.

**To Reproduce**
Example:

1. assign 4 user as global moderator
2. report a message

**Result**
Moderators get 4 times the same mail

**System information**
- Joomla version: 4.1.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.2-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment]
It's the same with subscription emails. The more users have subscribed to a category, the more mails each user receives.

**Comment by xillibit** [comment]
> **To Reproduce** Example:
> 
>     1. assign 4 user as global moderator
> 
>     2. report a message
> 
> 
> **Result** Moderators get 4 times the same mail

I've tried with 3 global moderator, when do a report i can see only 3 mails send one for each moderator

**Comment by rich20** [comment]
Did any of these moderators report the post?
**2 moderators**
.
![Bildschirmfoto vom 2022-08-07 16-03-28](https://user-images.githubusercontent.com/888847/183295706-2f4375a3-210b-4819-9be5-416376ebc471.png)
.
The same with subcriptions
**3 subscriber**
.
![Bildschirmfoto vom 2022-08-07 16-27-00](https://user-images.githubusercontent.com/888847/183295850-20555f07-81c5-497f-8bb5-8e34e5f624a1.png)

**Comment by xillibit** [comment]
Yes a moderator has made the report i will try with a simple user

**Comment by rich20** [comment]
Please try it with this setting (it's the default setting):

- E-mail to Multiple Recipients = 0
- E-mail Recipient Privacy = BCC
- Visible E-mail Recipient - leave empty

**Comment by xillibit** [comment]
It's the settings that i have

**Comment by rich20** [comment]
Solved by this fix: https://github.com/Kunena/Kunena-Forum/issues/9327
