### ISSUE TITLE
[PHP 8.1] When Show Images for Guests = No | Deprecated: htmlspecialchars(): Passing null to parameter #1...

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9221]
**To Reproduce**

1. set in the configuration (tab Attahments) Show Images for Guests = No
2. insert an image into a message
3. visit as guest this topic

**Result**
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /.../libraries/kunena/External/Nbbc/src/BBCode.php on line 1435

**To Reproduce**

**System information**
- Joomla version: 4.2.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.2
- Kunena template: Aurelia
- Php version: 8.1.7
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Leen29** [comment]
strange I don't 
I get in Dutch language that I have to log in to view picture
![nowarning](https://user-images.githubusercontent.com/17086048/185352628-2eea11f4-0c8c-4669-bd4e-52b9740a1495.JPG)
PHP Built On 	Linux xxxx.zxcs.nl 3.10.0-962.3.2.lve1.5.60.el7.x86_64 #1 SMP Fri Jul 23 07:07:00 EDT 2021 x86_64
Database Type 	mysql
Database Version 	10.3.27-MariaDB-cll-lve
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	No
PHP Version 	8.0.14
Web Server 	Apache/2
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 4.2.0 Stable [ Uaminifu ] 16-August-2022 13:05 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

**Comment by xillibit** [comment]
The issue happens with Php 8.1.x, you are using Php 8.0.14

**Comment by Leen29** [comment]
ha okay just php version upgraded to PHP Version 8.1.1 as test and indeed warnings.
"xxxx/public_html/libraries/kunena/External/Nbbc/src/BBCode.php on line 1435"
and also various community builder I notice
/public_html/libraries/CBLib/CBLib/DependencyInjection/Container.php
online
894 and more numbers
