### ISSUE TITLE
It lacks the menu item type for Create New Topic

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9223]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/165737-can-t-access-new-topic-menu-error-403

**To Reproduce**

1. go to the Kunena menu and click New
2. click at Menu Item Type the button Select
3. search the menu item type Create New Topic

**Result**
The Menu Item Type is not in this list (see image)

![Bildschirmfoto vom 2022-08-18 18-16-33](https://user-images.githubusercontent.com/888847/185447147-1ff68623-2933-4c93-bd8a-a7cd2d63c084.png)

**Comment by rich20** [comment]
I have tested it again. The problem occurs only with new installations and starts with Kunena 6.0.1.

**Comment by Leen29** [comment]
yes, but I do notice that in a clean joomla and kunena installation
I notice that you do have the button on the front create topic that also works.
![frontcreate](https://user-images.githubusercontent.com/17086048/185681871-ce95c0dd-a906-41ce-9365-7493535055f0.JPG)

**Comment by Leen29** [comment]
if I'm correct, a clean kunena install with pkg_kunena_v6.0.1.1_2022-07-09.zip "create.xml in the folder site\components\com_kunena\tmpl\topic\tmpl\ is missing
with an upgrade from an earlier version eg pkg_kunena_v6.0.0-RC4-DEV_2022-06-09.zip then that file is there in the folder
![create3leeg](https://user-images.githubusercontent.com/17086048/186083164-d7d122fa-ad83-4c53-b447-34f4134799aa.JPG)
![create2](https://user-images.githubusercontent.com/17086048/186083221-b2f73d3c-6769-4c40-91d0-b6f1f38e5fa5.JPG)
![create1](https://user-images.githubusercontent.com/17086048/186086984-d2737044-d6b4-4409-8169-40a3b129402f.JPG)

**Comment by xillibit** [comment]
When you will install K6.0.3 or if you install K6.0.3-DEV the create.xml will be in site\components\com_kunena\tmpl\topic\tmpl\, if the file is present too in site\components\com_kunena\tmpl\topic\ it does anything
