### ISSUE TITLE
Wrong message if you edit and save the SCSS

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9230]
**To Reproduce**

- Go to Aurelia
- Edit the custom.scss and save it

**Result**
The entered codes are saved, but the message is wrong
Operation Failed: COM_KUNENA_A_TEMPLATE_MANAGER_FAILED_OPEN_FILE. 
(should be File Saved)

**System information**
- Joomla version: 4.2.1-rc3
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.3-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Fixed by : https://github.com/Kunena/Kunena-Forum/pull/9235
