### ISSUE TITLE
Plugin 'Smart Search - Kunena Forum' SQL error in Maintenance - Optimise

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9272]
**Describe the bug**
https://www.kunena.org/forum/k-6-0-support/166438-plugin-smart-search-kunena-forum-sql-error-in-maintenance-optimise

**To Reproduce**

1. Enable the plugin [Smart Search - Kunena Forum
2. Go to Components -> Smart Search -> Index and start the indexer
3. Click on top Maintenace -> Optimise

**Result**
1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 5

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:141
2 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:1048
3 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1900
4 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/administrator/components/com_finder/src/Indexer/Adapter.php:281
5 | Joomla\Component\Finder\Administrator\Indexer\Adapter->onFinderGarbageCollection() | JROOT/libraries/src/Plugin/CMSPlugin.php:279
6 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
7 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:107
8 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/administrator/components/com_finder/src/Controller/IndexController.php:58
9 | Joomla\Component\Finder\Administrator\Controller\IndexController->optimise() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
10 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
11 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
16 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: 4.2.3-rc2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.3-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by pfitzer** [comment]
`protected $table = '#__kunena_messages';` is missing in plgFinderKunena
