### ISSUE TITLE
Mobile view: At Recent Topics and Recent Posts lacks the right column "Last Post by"

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9298]
**Describe the bug**
https://www.kunena.org/forum/36-German/166363-anmeldung-und-darstellungsprobleme-aurelia-vorlage-kunena-6-0-2
Confirmed
.
![Bildschirmfoto vom 2022-10-08 20-44-28](https://user-images.githubusercontent.com/888847/194723080-c85e355d-f2e5-4e4e-b8a5-90f3e7d8b04f.png)
.
**System information**
- Joomla version: 4.2.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.4-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
Hi,
these views have the same info as Kunena 5.x, so imo this is not a bug but a feature request?

![image](https://user-images.githubusercontent.com/2733197/194750169-a3303ec6-adb8-40c3-be18-5102316a510d.png)

**Comment by rich20** [comment]
I was not sure because I myself do not use a mobile phone for the Internet. But if K5 has the same view, I close this ticket again.
