### ISSUE TITLE
Prevent Kunena 5.2 from trying to prepare for installation on Joomla 4.x

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9315]
https://www.kunena.org/forum/installation-issues/166989-install-fails-kunena-5-2-10-1
We should to prevent Kunena 5.2 from starting to prepare for installation on Joomla 4. There is no message that Kunena 5.2 does not meet the requirements. The preparation just stops after some time.
After that, if you try to install Kunena 6.0, it wants to perform a migration even though there are no 5.2 tables in the database. It breaks the whole backend and it is not possible to restore the website without import K5.2 tables or without backup.

**Comment by xillibit** [comment]
I have tried locally with a site on Joomla! 3.10 with Kunena 5.2 and Kunenadiscuss 5.2 to launch the update to Joomla! 4.2.3. The pre-update checker just said that system plugin kunena was not compatible so i disabled it.
After the update to Joomla! 4.2.3, on the backend dashboard there was a fatal error coming from kunena discuss.

I have disabled discuss plugin on the database then installed Kunena 6.0 then the topics and all was here. So : 

- Kunenadiscuss 5.2 should be indicated as not compatible to update to J! 4.x
- Plugin integration for Alteruserpoints ~should be removed in K6.0~ and the one from K5.2 deleted during update to K6.0

**Comment by rich20** [comment]
> Kunenadiscuss 5.2 should be indicated as not compatible to update to J! 4.x

Kunena Discuss is shown correctly as not compatible in the pre-update checker. At least in my tests it was so.
But this is not what I meant. There are users who try to install Kunena 5.2 on Joomla 6.0. Then Kunena 5.2 starts to prepare the installation and then stops at some point. After that, K6.x also fails to install because it tries to update even though there are no 5.2 database tables. After that the backend is destroyed.
Kunena 5.2 should give a warning and not start the installation preparation if the Joomla version is too high.

It was my fault because it has nothing to do with Kunena 6.0 and I added the wrong label. Sorry.

**Comment by xillibit** [comment]
ok i got it, i will look later how to block install of K5.2 on Joomla! 4.x
