### ISSUE TITLE
Upgrade: 1054 Unknown column 'sampleData' in 'field list' 

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9325]
**To Reproduce**

1. Upgrade from K5 to K6
2. Go to the Kunena User manager

**Actual result** 
The sampleData column is missing in the #__kunena_version table, that's why there is this error:

<blockquote class="blockquote">
                            <span class="badge bg-secondary">1054</span>
                            Unknown column 'sampleData' in 'field list'                        </blockquote>
                                                    <div>
                                

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:141
2 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:1048
3 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1900
4 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/libraries/kunena/src/Forum/KunenaForum.php:378
5 | Kunena\Forum\Libraries\Forum\KunenaForum::buildVersion() | JROOT/libraries/kunena/src/Forum/KunenaForum.php:336
6 | Kunena\Forum\Libraries\Forum\KunenaForum::version() | JROOT/libraries/kunena/src/Version/KunenaVersion.php:51
7 | Kunena\Forum\Libraries\Version\KunenaVersion::getVersionHTML() | JROOT/libraries/kunena/src/Version/KunenaVersion.php:39
8 | Kunena\Forum\Libraries\Version\KunenaVersion::getLongVersionHTML() | JROOT/administrator/components/com_kunena/tmpl/users/default.php:344
9 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:410
10 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
11 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Users/HtmlView.php:79
12 | Kunena\Forum\Administrator\View\Users\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:639
13 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:55
14 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
15 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
16 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
17 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
18 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
19 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
20 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
21 | require_once() | JROOT/administrator/index.php:32

</div>

**System information**
- Joomla version: 4.2.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.4-DEV - build [2022-10-24]
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Did-you done the upgrade from K5.1 or K5.2 ?

**Comment by rich20** [comment]
I had performed the upgrade with K5.2 tables.

**Comment by rich20** [comment]
The same with K5.1 tables
