### ISSUE TITLE
No labels at Moderate Topic

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9346]
**To Reproduce**

1. Aurelia setting - Icon Type = SVG, Show Labels = Topic id
2. Configuration (tab) Frontend - Selectable Topic Icons = No
3. Go in frontend to a topic and moderate this topic

**Actual result**
There are no labels, where moderators e.g. can mark topics as solved (like at k.org).

**Screenshot from Crypsis**

![Bildschirmfoto vom 2022-11-02 03-36-46](https://user-images.githubusercontent.com/888847/199383974-d07e1bc2-c005-4b13-8a96-96a34d153843.png)

**System information**
- Joomla version: 4.2.5-rc2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.5-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
@rich20 should be fixed with #9350

**Comment by rich20** [comment]
Yes, it's fixed.
