### ISSUE TITLE
use PSR-12 codestyle

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9353]
currently I see some code style irregularities (tabs / spaces / etc.).
'world' standard nowadays is PSR-12.
Joomla recently switched from their own code style to PSR-12 (they have a script to convert the complete code base).

I think this also makes sense for this repository as it makes the life of developers (like me :)) easier!

**Comment by xillibit** [comment]
If such things should be done it should applied on K6.1 branch but where did-you see this script ?

**Comment by Ruud68** [comment]
This is what I did for my own extensions (adjusted for kunena > External directory exclude):

check in the src directory:

```
phpcs --standard=PSR12 --extensions=php --ignore=vendor,External .
```
and then when no errors:
```
phpcbf --standard=PSR12 --extensions=php --ignore=vendor,External .
```
Just did a test-run in my fork > branch K6.1 > PSR12

**Comment by xillibit** [comment]
I have modified the Joomla! script : https://github.com/joomla/joomla-cms/blob/4.2-dev/build/psr12/psr12_converter.php to target only the Kunena directories ~~but i have this issue:~~

`Could not open input file: C:\Users\xillibit\git\joomla-cms-4.2-dev/libraries/vendor/bin/phpcbf
Error PHPCBF completed with error code: 1`

I have copied the bin directory from vendor from kunena i have another issue with the script:

`Fix plugins/kunena/kunena

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../squizlabs/php_codesniffer/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/phpcbf" "$@"`

**Comment by xillibit** [comment]
> and then when no errors:
> 
> ```
> phpcbf --standard=PSR12 --extensions=php --ignore=vendor,External .
> ```
> 
> Just did a test-run in my fork > branch K6.1 > PSR12

I have tried that, then there will be changes on all files and merging from K6.0 will more difficult

> A TOTAL OF 120294 ERRORS WERE FIXED IN 687 FILES
> ---------------------------------------------------------------------------------------------------------------------------------------------

> Time: 3 mins, 35.61 secs; Memory: 58MB

**Comment by Ruud68** [comment]
yes, merging is an issue as every tab converted to space is seen as change.
So one strategy could be to do merge all of 6.0 into 6.1 (changes) and then do the psr12 on the 6.0 branch first, test if everything is working correct and release this in a next 6.x release. Then on the 6.1 branch do the psr12 as well. next changes on 6.0 can then be merged into 6.1 as it was 'before'

**Comment by xillibit** [comment]
I close because juste done in both K6.0 & K6.1

**Comment by Ruud68** [comment]
Thanks, this makes life easier :)

**Comment by xillibit** [comment]
Done too on Kunena Addons : https://github.com/Kunena/Kunena-Addons/commit/1aee1664f0388f7d07dc2ed611ba2472300726b6
