### ISSUE TITLE
Uninstalling and reinstalling via the Joomla installer is not possible without database access

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9366]
**Describe the bug**
https://www.kunena.org/forum/installation-issues/167205-bug-in-deinstaller-of-kunena-6-0-4
Confirmed

If you want un and reinstall Kunena, you get the error JInstaller: :Install: Fout SQL Duplicate entry 'com_' for key 'PRIMARY' 
In this case you must remove the Kunena entries in the table #__mail_templates, because the mail templates can not be uninstalled in the backend.
A solution is needed, otherwise it is not possible for users without database knowledge or access, in case of problems, Kunena de- and then reinstall again.

**Comment by xillibit** [comment]
Like for this issue: https://github.com/Kunena/Kunena-Forum/issues/9371, it's needed now a change in the update process to the sql changes to be applied

**Comment by xillibit** [comment]
When the users whill update to K6.0.5 the entries to Kunena in table #__mail_templates will be cleaned
