### ISSUE TITLE
Poll: Voting not possible because no vote button available (part 3)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9371]
**Describe the bug**
https://github.com/Kunena/Kunena-Forum/pull/9370

Kunena 6.0.4 has the entry in the column **polltimetolive default =  NULL**
Kunena 6.0.5-DEV get the entry **polltimetolive default =  1000-01-01 00:00:00** during a new installation
- [ ] But if you upgrade from Kunena 6.0.4 to Kunena 6.0.5-DEV the column will not updated and it remain the value **polltimetolive default =  NULL**. This leads to the fact that no voting is possible.

- [x] The second problem is, if you adjust the column manually, or have an absolutely newly installed Kunena 6.0.5-DEV, the poll voting works, but it shows that was ended 1000-01-01 00:00:00.
.
![Bildschirmfoto vom 2022-11-06 23-43-21](https://user-images.githubusercontent.com/888847/200222028-3ef6e143-ef52-4f74-adc6-92b3e103b4e6.png)

**Comment by xillibit** [comment]
> * But if you upgrade from Kunena 6.0.4 to Kunena 6.0.5-DEV the column will not updated and it remain the value **polltimetolive default =  NULL**. This leads to the fact that no voting is possible.

Just tried to update from K6.0.4 to K6.0.5-dev, the update is right done when going to the kunena dashboard : 
![image](https://user-images.githubusercontent.com/876395/201543452-1c7bd74b-7b43-4a8d-ae7a-2a4e16c6c831.png)

Then the colunm polltimetolive in table #__kunena_polls is right updated
