### ISSUE TITLE
Content of custom.scss is removed with each installation

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9385]
**To Reproduce**
1. Go to Aurelia
2. Enter a code in the custom.sccs
3. Install Kunena

**Result**
The custom.scss is empty

**System information**
- Joomla version: 4.2.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.5-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by makitso** [comment]
Kunena version 6.3.10 removed the contents of the custom.css file.
