### ISSUE TITLE
No mail sent to moderator when moderator email == forum email

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9401]
**Describe the bug**
When moderator has same mailadress as forum ($emailVisibleAddress) he will not receive a mail message when a new topic is created

**To Reproduce**
Set the emailaddress of the (global) moderator account the same as the configured visible email address for the forum.

create a new topic

**Expected behavior**
The moderator should receive a mail message that a new topic has been created

**Actual result**
No mail is sent

**System information (please complete the following information)**

Joomla version: 4.2.5
Kunena version: k6.0.5
Php version: 8.1

**Additional context**
the 'issue' is in ./libraries/kunena/src/forum/message/KunenaMessage.php
line 522-525
```
if ($config->emailVisibleAddress != $emailTo->email) {
                    $receivers[$emailTo->subscription][] = $emailTo->email;
                    $sentusers[]                         = $emailTo->id;
                }
```
the emailVisibleAddress == $emailTo->email and there for the moderator is not added to the recipients list

So this can be 'fixed' by removing the if check, but there must be a reason why that check is there?

**Comment by xillibit** [comment]
This check was added to fix an another issue : https://github.com/Kunena/Kunena-Forum/commit/4a7dff3b4e30d45cc95dd1522355a742e0e46950

**Comment by Ruud68** [comment]
Hi, thanks for this. I suspected as much :)

what if we change the condition to:
```
if ($config->emailVisibleAddress != $emailTo->email || $emailTo->moderator)
```

That way, the moderator will always get the mail even when he has the same mail address as the forum (which I think is a valid use case)

**Comment by xillibit** [comment]
If Pphmailer found an identical mail in BCC or CC than the one which is in $config->emailVisibleAddress it just send to the one set in $config->emailVisibleAddress

**Comment by Ruud68** [comment]
Okay,
so the issue here is that when setting a different mail for the moderator, he will receive all mails 2 times: 1 time on his mail address and 1 time on the site visible email address.

When the emails are the same, then the moderator will only receive the email when at least 1 other user is subscribed to the topic.
otherwise, the list of receivers stays empty.

now with this code, both scenarios would work (currently testing this on my own forum):
```
if ($config->emailVisibleAddress != $emailTo->email || (count($emailToList) == 1 && $emailTo->moderator))
```
so this change will send the email when a new topic is created to the moderator (because he is the only one and moderator, his email will be added to the receivers list), when there are other subscribers he will not be added but he will receive the notification mail via the site mail address (which is his email address)

Would this work in all uses cases @xillibit or am I missing something?

**Comment by xillibit** [comment]
seems good
