### ISSUE TITLE
Small bug topic.js + search form Bootstrap 5

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9402]
The WhatsApp Messenger icon should only appear on mobile.

Fix topic.js:
`$('.jssocials-share-whatsapp').addClass('d-block d-sm-none');`

The search form is not formatted correctly with Boostrap 5.
`<fieldset class="col-md-6 row">`  etc...

 The correct formatting can be found [here](https://www.joomlaportal.cz/forum/search)

System information 

Joomla version: 4.2.5
Kunena version: k6.0.5

Thank you.

**Comment by Ruud68** [comment]
Hi,
can you tell me what is wrong with the search form (provide screenshot). I do not see anything wrong.

**Comment by LinelabCZ** [comment]
[default.zip](https://github.com/Kunena/Kunena-Forum/files/10146101/default.zip)

[default_original.zip](https://github.com/Kunena/Kunena-Forum/files/10146107/default_original.zip)

**Comment by LinelabCZ** [comment]
![search](https://user-images.githubusercontent.com/105653787/205434572-22eb6a2f-dc18-4f92-afec-5342a7d8659b.png)

**Comment by Ruud68** [comment]
is this one better? https://onlinecommunityhub.nl/forum/search
if so I can propose this full BS5 form instead of the 'partially' converted one aurelia has now

**Comment by LinelabCZ** [comment]
Yes, this is better. Thank you.

**Comment by Ruud68** [comment]
@xillibit before doing a PR to get the search from my own template into Aurelia, is this something you are working on? Would it make sense to back-port my template search into Aurelia?

**Comment by LinelabCZ** [comment]
I'm not working on anything.

**Comment by Ruud68** [comment]
> I'm not working on anything.

The question was for Xillibit :)

**Comment by xillibit** [comment]
> @xillibit before doing a PR to get the search from my own template into Aurelia, is this something you are working on? Would it make sense to back-port my template search into Aurelia?

@Ruud68 : no,i'am on this one actually : https://github.com/Kunena/Kunena-Addons/issues/304, you can back-port your template search if it's better

**Comment by Ruud68** [comment]
@LinelabCZ can you test PR please.

ps not changing whatsapp as whatsapp is NOT limited to mobile devices any more, so should also be able to display on desktop.
If you want more control, you can use your own socials sharing solution (that is why I a long time ago introduced the custom sharing tag).

I use my own ochJSsocials solution and by doing that I can have full control over what buttons to show on what devices etc.

ps2 jsSocials script used in Kunena  is in my opinion abandoned: the developer is non-responsive (that is why I stopped contributing on that script and forked it for my own plugin)
