### ISSUE TITLE
Add Announcements Joomla 4

### ISSUE THREAD

**Issue by LinelabCZ** [Kunena/Kunena-Forum#9403]
Kunena has a system to show Announcements in the frontend. There is no way to add announcements in Joomla 4.
Kunena login module for joomla! 4 is not available.

System information 

Joomla version: 4.2.5
Kunena version: k6.0.5

**Comment by xillibit** [comment]
Why do-you say there is no way to add announcements in Joomla 4 ?

**Comment by LinelabCZ** [comment]
Hi, Sorry for the inaccuracy. How exactly add a notification in Kunena (Joomla 4)?
https://www.kunena.org/docs/en/faq/announcements
I can't find any way to add the announcement.

**Comment by Ruud68** [comment]
... removed image ...

**Comment by LinelabCZ** [comment]
Sorry, wrong settings for the Aurelia template. Resolved.
