### ISSUE TITLE
User list: The values are not assigned to the correct columns

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9408]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/167540-list-of-members-date-displaced
Confirmed

**To Reproduce**
Go to the user list and you see this issue

**Screenshots**
![image12540](https://user-images.githubusercontent.com/888847/204829680-d14c68c8-ebac-4876-9fc3-aca068e990c8.png)

**System information**
- Joomla version: 4.2.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.7-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment]
Addendum: The status is only displayed for logged-in users (it lacks the background-color for these labels).
.
![image101](https://user-images.githubusercontent.com/888847/204833999-ce3067a7-a2ab-4e10-ba2e-faac8e4ad807.png)

**Comment by Rolli1962** [comment]
Thanks for opening the issue. Seems I have found the coding-issue. Wrong class is set. After change it is working (here).
Script: components/com_kunena/template/aurelia/layouts/user/list/default.php

For userlistJoinDate and userlistLastVisitDate
It has to be replaced
class="col-md-2 d-none d-sm-block"
again
class="col-md-2 d-none d-md-table-cell"

Hope this will help to fix.

**Comment by Leen29** [comment]
that is correct there is a mistake in line 285 and 293 something seems to have been forgotten there when you adjust it with
<td class="col-md-1 d-none d-md-table-cell">
then it's okay

![1_foutje](https://user-images.githubusercontent.com/17086048/205011340-fd780cc7-16c5-41a1-b7cc-7652da7f823c.JPG)
