### ISSUE TITLE
On index page when there are sub-categories there are displayed vertically

### ISSUE THREAD

**Issue by xillibit** [Kunena/Kunena-Forum#9419]
The sub-categories there are displayed vertically :

![image](https://user-images.githubusercontent.com/876395/206932062-bb900158-5b93-4007-b006-eebbd7af6a90.png)

Expected result the same as Kunena 5.2 : 

![image](https://user-images.githubusercontent.com/876395/206932105-da1fd94f-d15e-4b9b-805d-d326a94bb1f1.png)

**Comment by xillibit** [comment]
@Ruud68 : do-you have an idea how to fix this one ?

**Comment by Ruud68** [comment]
I'll check this tomorrow, wanted to check earlier but dropped of my screen due to long todo list :)
