### ISSUE TITLE
Large icons are displayed in sub categories when a category CSS class suffix has been added

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9424]
**To Reproduce**
go in the backend to categories
add to a category which contain sub categories a CSS class suffix like --green
.
![Bildschirmfoto vom 2022-12-15 21-00-09](https://user-images.githubusercontent.com/888847/207956107-498835a5-cf9a-4849-9c6b-66128cf68f0b.png)

**Actual result**
It replaces the small symbols with large ones
.
without CSS class
.
![Bildschirmfoto vom 2022-12-15 21-32-18](https://user-images.githubusercontent.com/888847/207961446-743ed234-2267-4335-8ca3-d33b3782d1ea.png)
.
with CSS class suffix
.
![Bildschirmfoto vom 2022-12-15 21-31-52](https://user-images.githubusercontent.com/888847/207961641-ac84abac-bcc8-489d-9e15-412de3abc3c7.png)

**System information**
- Joomla version: 4.2.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.8-DEV
- Kunena template: Aurelia
- Php version: 8.0.20
- Database version: 10.5.16-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
Hi @rich20 , I did a PR. If you can test that would be great!
