### ISSUE TITLE
404 - Affichage introuvable [name, type, prefix]&amp;#160;: topic, html, site

### ISSUE THREAD

**Issue by carabao72** [Kunena/Kunena-Forum#9448]
Hello,

I have an error when I want to edit a message on the forum

**Describe the bug**

<div id="errorboxheader">404 - Affichage introuvable [name, type, prefix]&amp;#160;: topic, html, site</div>
            <div id="errorboxbody">
            <p><strong>Il est possible que vous ne puissiez visiter cette page en raison de :</strong></p>
            <ol>
                <li>un <strong>lien/favori obsolète</strong></li>
                <li>un moteur de recherche possède un listing <strong>périmé</strong> pour ce site</li>
                <li>une adresse <strong>erronée</strong></li>
                <li>vous <strong>n'avez pas</strong> accès à cette page</li>
                <li>La ressource demandée est <strong>introuvable</strong></li>
                <li>Une erreur est survenue pendant l'exécution de la requête.</li>
            </ol>
            <p><strong>Veuillez essayer l'une des pages suivantes :</strong></p>
            <ul>
                <li><a href="https://www.caravane-camping.be/index.php">Page d'accueil</a></li>
            </ul>
            <p>Si les difficultés persistent, merci de contacter l'administrateur de ce site et de signaler les erreurs ci-dessous.</p>
            <div id="techinfo">
            <p>
                Affichage introuvable [name, type, prefix]&amp;#160;: topic, html, site                                    <br>/home/salmigon/domains/caravane-camping.be/public_html/libraries/src/MVC/Controller/BaseController.php:816
                            </p>
                            <div>
                    

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/MVC/Controller/BaseController.php:816
2 | Joomla\CMS\MVC\Controller\BaseController->getView() | JROOT/libraries/kunena/src/Controller/KunenaController.php:382
3 | Kunena\Forum\Libraries\Controller\KunenaController->display() | JROOT/libraries/kunena/src/Controller/KunenaController.php:319
4 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:226
5 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:108
6 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:200
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:241
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
11 | require_once() | JROOT/index.php:32

</div></div></div>404 - Affichage introuvable [name, type, prefix]&#160;: topic, html, site

Il est possible que vous ne puissiez visiter cette page en raison de :

    un lien/favori obsolète
    un moteur de recherche possède un listing périmé pour ce site
    une adresse erronée
    vous n'avez pas accès à cette page
    La ressource demandée est introuvable
    Une erreur est survenue pendant l'exécution de la requête.

Veuillez essayer l'une des pages suivantes :
```

    [Page d'accueil](https://www.caravane-camping.be/index.php)

Si les difficultés persistent, merci de contacter l'administrateur de ce site et de signaler les erreurs ci-dessous.

Affichage introuvable [name, type, prefix]&#160;: topic, html, site
/home/salmigon/domains/caravane-camping.be/public_html/libraries/src/MVC/Controller/BaseController.php:816
Call stack
# 	Function 	Location
1 	() 	JROOT/libraries/src/MVC/Controller/BaseController.php:816
2 	Joomla\CMS\MVC\Controller\BaseController->getView() 	JROOT/libraries/kunena/src/Controller/KunenaController.php:382
3 	Kunena\Forum\Libraries\Controller\KunenaController->display() 	JROOT/libraries/kunena/src/Controller/KunenaController.php:319
4 	Kunena\Forum\Libraries\Controller\KunenaController->executeTask() 	JROOT/libraries/kunena/src/Controller/KunenaController.php:226
5 	Kunena\Forum\Libraries\Controller\KunenaController->execute() 	JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:108
6 	Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:355
7 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/SiteApplication.php:200
8 	Joomla\CMS\Application\SiteApplication->dispatch() 	JROOT/libraries/src/Application/SiteApplication.php:241
9 	Joomla\CMS\Application\SiteApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:294
10 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/includes/app.php:61
11 	require_once() 	JROOT/index.php:32

```

**To Reproduce**
1. Go to 'https://www.caravane-camping.be/'
2. Click on ' Les dernières réponses -->  https://www.caravane-camping.be/forum/2-0-acces-internet/36-existe-t-il-une-solution-pour-amplifier-un-signal-wifi-sur-250m#138
3. ACTION, éditer

**Expected behavior**

Joomla version: 4.2.6
Kunena version: 6.0.7
Php version: 8.1.11
Database version: MySQLi 5.7.39 

**Desktop (please complete the following information):**
 - OS: FEDORA 37
 - Browser Firefox 108.0.1

**Comment by rich20** [comment]
Please use the forum for support requests. Here is a possible solution: https://www.kunena.org/forum/k6-0-support-archive/167572-registered-users-can-t-edit-own-posts-any-longer

**Comment by carabao72** [comment]
solved: https://www.kunena.org/forum/24-French/167622-404-affichage-introuvable-name,-type,-prefix-160-topic,-html,-site

Solution, by-pass?

**Comment by rich20** [comment]
The error was caused by an incorrectly configured menu item.
