### ISSUE TITLE
Messages can't be moved to another topic "Cannot move topic to unknown target."

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9455]
**To Reproduce**
Try to merge an or more message/s to another topic

**Actual result**
Cannot move topic to unknown target.

**System information**
- Joomla version: 4.2.7-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.9-DEV
- Kunena template: Aurelia
- Php version: 8.0.26
- Database version: 10.5.18-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by rich20** [comment]
I've noticed, that the field for manual entry of the topic ID is also not opened when this option is selected.

- [ ] Messages can't be moved to another topic
- [ ] It is not possible to enter the ID manually (it lacks the input field)

**Comment by xillibit** [comment]
> * Messages can't be moved to another topic

Seems happens only on topics migrated from K5.2 not news topics

**Comment by rich20** [comment]
I've created 2 new topics but can't merge these.

**Comment by rich20** [comment]
Sorry , not yet tested the fix.

**Comment by rich20** [comment]
Cannot move topic to unknown target.

**Comment by xillibit** [comment]
> Sorry , not yet tested the fix.

You need to test with that : https://github.com/Kunena/Kunena-Forum/commit/4eaae2b1029a1b361f068f7dd624649f50ab5aa2

**Comment by rich20** [comment]
- [x] Messages can't be moved to another topic
- [x] It is not possible to enter the ID manually (it lacks the input field)
Success
