### ISSUE TITLE
Slovenian Language 6.0.8 is not UTF 8

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9457]
**Describe the bug**
https://www.kunena.org/forum/107-Translations/167649-kunena-language-pack-6-0-8-not-utf-8
Confirmed
.
![Bildschirmfoto vom 2023-01-23 15-54-19](https://user-images.githubusercontent.com/888847/214078227-282e7e32-6f99-4781-9eac-492c95f90f06.png)
.
**Additional context**
This language is only 34.47% translated.

**Comment by xillibit** [comment]
Only the file sl-SI.com_kunena.ini has issues
