### ISSUE TITLE
The spoiler changes from Click to expand to true (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9458]
**Describe the bug**
https://github.com/Kunena/Kunena-Forum/issues/9456

Now it changes the button "Click to expand" only to another color instead of "Click to hide".
.
![Bildschirmfoto vom 2023-01-23 16-40-25](https://user-images.githubusercontent.com/888847/214082215-e947a0b4-78d0-4442-ac50-e1a6b48f1e7c.png)
.
![Bildschirmfoto vom 2023-01-23 16-19-13](https://user-images.githubusercontent.com/888847/214081674-0b0ae1f9-0c5a-42ad-864b-6d7536379ddf.png)

**System information**
- Joomla version: 4.2.7-rc2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.9-DEV
- Kunena template: Aurelia
- Php version: 8.0.26
- Database version: 10.5.18-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
When you click and don't hover the mouse: 

![image](https://user-images.githubusercontent.com/876395/214119414-0956ff75-0191-4004-b69f-0d253ece0f90.png)

**Comment by rich20** [comment]
It seems browser related. It works for me with Chromium and Opra, but not with Firefox.

**Comment by xillibit** [comment]
i'am using firefox

**Comment by rich20** [comment]
Ok, maybe the Firefox for Linux is different. So I close this issue.

**Comment by rich20** [comment]
I reopened this topic. It seems to affect all Linux versions with Firefox.
https://www.kunena.org/forum/36-German/167653-k6-0-8-configuration-report-spoiler-true#227295

**Comment by xillibit** [comment]
It's use the Boostrap 5.0 collaspe : https://getbootstrap.com/docs/5.0/components/collapse/, is the example working with firefox on linux ?

**Comment by rich20** [comment]
I see now, it's another problem. It works only at the first message in a page. As you can see on image, are both spoiler open. But the button changes only in the first message correctly to "Hide". I can close or open both spoiler with click on button at one of the message.
.
![Bildschirmfoto vom 2023-01-24 20-27-02](https://user-images.githubusercontent.com/888847/214390723-02633cbd-d3ca-43d6-9a25-794184630f92.png)
