### ISSUE TITLE
Error in the announcement table

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9465]
Click at k.org as guest on the Announcment

**Result**
![Bildschirmfoto vom 2023-02-09 14-47-34](https://user-images.githubusercontent.com/888847/217835749-9df4cecf-7dc4-4f27-ac1e-17fc2074c2dc.png)

**Comment by Ruud68** [comment]
Hi @rich20 , what is the error here?
What is the expected result when clicking on the announcement?
Or is it the column header for ID that is on the wrong column?

**Comment by rich20** [comment]
**Logged in view**
![image140](https://user-images.githubusercontent.com/888847/218103933-4864313b-93cf-4ec6-9d78-de9285aeb7d1.png)

**Logged out view**
![image1880](https://user-images.githubusercontent.com/888847/218103372-7a056e95-1725-4d16-83ab-e3d2a62b89e2.png)

**Comment by rich20** [comment]
Addendum: I have now noticed that only mods and admins have the correct view.
