### ISSUE TITLE
Pasting an image to a message results in data:url garbage after saving

### ISSUE THREAD

**Issue by c-schmitz** [Kunena/Kunena-Forum#9475]
**Describe the bug**
When pasting an image to a message it results in data:url garbage after saving.

**To Reproduce**
1. In Windows open a png file in your favorite picture view application and copy the picture to clipboard (do NOT copy/use an image from the browser)
2. Create a new message in Kunena (new topic or reply)
3. Insert the PNG by pressing CTRL-V.
4. See a nice image in the editor.
5. Save.
6.  Look at the message. 
**Expected behavior**
You should see the picture in the message.

**Actual result**
Instead of the picture you see data image contents.

**Screenshots**

![image](https://user-images.githubusercontent.com/1364282/222575097-0c4a9596-7b2c-4ef1-81a5-22bdba92cc56.png)

![image](https://user-images.githubusercontent.com/1364282/222575183-a5a79e8d-7eb6-4aa5-b915-b95f2ccc0638.png)

**System information (please complete the following information)**

Joomla version: 4.2.8
Kunena version: 6.0.9.1
Php version: 8.0
Database version: n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:  Firefox
 - Version 110.1

**Comment by c-schmitz** [comment]
Allowing data:urls would be a bad decision in general because data: images are huge, and subvert the settings for attachments.
I'd rather block pasting them in general - note that this would not affect img URLs (typical when you copy and paste a picture from another website)

**Comment by rich20** [comment]
Confirmed. I thought we had already prevented images from being copied directly into the text box. It is now prevented when you drag the image in, but not when you insert it with CTRL-V.

**Comment by xillibit** [comment]
The PR is merged now
