### ISSUE TITLE
The kunena cache is not created

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9481]
**To Reproduce**

1. Remove manually the folder media/kunena/**cache**
2. Refresh the Page

**Result**
The kunena cache is not created (not even during an installation), and thus the kunena.css is no loaded.

**System information**
- Joomla version: ‎4.2.9-rc2-dev and ‎4.3.0-beta5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-DEV
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Do-you have this issue on K6.0 too or not ?

**Comment by rich20** [comment]
No, this problem only exists on K6.1
