### ISSUE TITLE
Kunena Tools : Clean up IP addresses does not work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9486]
**Describe the bug**
If you want to rermove the IPs from the last xxx days you get: **No stored IP addresses were found.**
If you want to Delete all users IPs you get: **Column 'ip' cannot be null**

**System information**
- Joomla version: ‎4.2.10-dev and ‎4.3.0-beta5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA1
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
> If you want to rermove the IPs from the last xxx days you get: **No stored IP addresses were found.**

It depends on the days that you have selected

> If you want to Delete all users IPs you get: **Column 'ip' cannot be null**

I don't get this one

**Comment by rich20** [comment]
> If you want to rermove the IPs from the last xxx days you get: 

Sorry, that was my mistake. I had chosen to remove IPs older than 30 days instead of 0 days

> If you want to Delete all users IPs you get: Column 'ip' cannot be null

I am only getting this on the Joomla 4.2 installation, so I am closing this ticket for now.
