### ISSUE TITLE
Recent Post pagination is not working

### ISSUE THREAD

**Issue by alecrespi78** [Kunena/Kunena-Forum#9489]
**Describe the bug**
The very first page looks ok but after if you scroll or change page it only show one page.

**To Reproduce**
1. Go to 'Your profile'
2. You will see several pages of "recent Posts".
3. Click on 'Page 2', or 3 or 4, or End
4. See error (it will shows up a single page with only one result/row)

**Expected behavior**
Showing selected page.

**Actual result**
One single page (instead of the selected page number). 

**Screenshots**
Screenshots.
![kunena6-page1](https://user-images.githubusercontent.com/89710784/227630805-776d936d-25c1-4898-a9e7-b765322b46d8.jpg)
![kunena6-page2](https://user-images.githubusercontent.com/89710784/227630811-75be35d6-8b3a-4ffd-ab87-4065c7f3a4e8.jpg)

**System information (please complete the following information)**

Joomla version: 4.2.9
Kunena version: 6.0.9.1
Php version: 7.4 to 8.2
Database version: 5.7.32-35

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 111.0.5563.111

**Additional context**
Migrated from Kunena 5.2 / Joomla 3.10

**Comment by alecrespi78** [comment]
The same issue is applicable to "Attachments" section.

**Comment by rich20** [comment]
This is not a bug, you have to choose the time period.
.
![image15470](https://user-images.githubusercontent.com/888847/227679191-c38731c4-ea1a-4976-bb3e-db77b7713b89.png)

**Comment by alecrespi78** [comment]
> This is not a bug, you have to choose the time period. . ![image15470](https://user-images.githubusercontent.com/888847/227679191-c38731c4-ea1a-4976-bb3e-db77b7713b89.png)

Correct! it works as expected right now.

Is there something similar for the profile >>> attachment list?
I'm have similar issue over there... #9491
