### ISSUE TITLE
Attachment manager pagination links 

### ISSUE THREAD

**Issue by alecrespi78** [Kunena/Kunena-Forum#9491]
**Describe the bug**
On the very first page navigation buttons are all functional.
After navigating to a different page (page2, next or end buttons) the navigation links seems to be disabled.

**To Reproduce**
1. Go to 'Your profile'
2. Select "Attachment Manager" tab.
3. Click on 'Page 2' or Next or End
4. Navigation links are disabled and you cannot change page anymore

**Expected behavior**
Active navigation links.

**Actual result**
Navigation links are disabled. 

**Screenshots**
Screenshots.
![kunena-attachments-page1](https://user-images.githubusercontent.com/89710784/227712461-a2c928e8-1abf-4075-b805-9ee7a125f809.jpg)
![kunena-attachments-mouse-hover](https://user-images.githubusercontent.com/89710784/227712468-a8915ab0-2533-48e1-9cc3-1625c27bdfe7.jpg)
![kunena-attachments-no-mouse-hover-navigation](https://user-images.githubusercontent.com/89710784/227712474-a3157446-7070-4ba0-b0c0-2112b48e6883.jpg)

**System information (please complete the following information)**

Joomla version: 4.2.9
Kunena version: 6.0.9.1
Php version: 7.4 to 8.2
Database version: 5.7.32-35

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 111.0.5563.111

**Additional context**
Migrated from Kunena 5.2 / Joomla 3.10

**Comment by rich20** [comment]
Confirmed
It is not possible to go back from page 2 to page 1. Pagination is disabled as soon as another page is called up.

**Comment by rich20** [comment]
This error only occurs when beadcrumbs are enabled in Aurelia.
