### ISSUE TITLE
Discussbot not showing "File Size"

### ISSUE THREAD

**Issue by alecrespi78** [Kunena/Kunena-Forum#9493]
**Describe the bug**
Attachment file size shows up as COM_KUNENA_USER_ATTACHMENT_FILE_WEIGHT instead of "KB".

**To Reproduce**
1. Go to a page with the 'discussbot'
2. You will see "COM_KUNENA_USER_ATTACHMENT_FILE_WEIGHT" instead of "KB".
3. Click on 'Post in discussion...' link
4. You will correctly see "KB".

**Expected behavior**
Showing KB on both pages.

**Actual result**
Language file not fully translated inside Discussbot plugin. 

**Screenshots**
Screenshots.
![kunena-forum-kb](https://user-images.githubusercontent.com/89710784/227727630-fa621701-f727-422b-9468-a6a507103ab3.jpg)
![kunena-discussbot-kb](https://user-images.githubusercontent.com/89710784/227727637-a9b371c3-1ca9-40e7-b346-e7c0cccbe3cc.jpg)

**System information (please complete the following information)**

Joomla version: 4.2.9
Kunena version: 6.0.9.1
Php version: 7.4 to 8.2
Database version: 5.7.32-35

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 111.0.5563.111

**Additional context**
Migrated from Kunena 5.2 / Joomla 3.10

**Comment by alecrespi78** [comment]
Manually adding this line
`COM_KUNENA_USER_ATTACHMENT_FILE_WEIGHT = "KB"`
to `language/en-GB/en-GB.com_kunena.ini ` file temporarily solves the problem.

**Comment by rich20** [comment]
> 1. Go to a page with the 'discussbot'

Can you please be more specific about what you mean by "Go to a page with the discussbot"? I am not able to reproduce this error. The string is available in en-GB.com_kunena.templates.ini and works for me.

**Comment by alecrespi78** [comment]
1. I was referring to a page with the plugin enabled (Kunena Discuss Package).
I've downloaded it from the kunena website.
https://www.kunena.org/download

![image](https://user-images.githubusercontent.com/89710784/228551153-bfdc68bc-79e7-4764-8d1d-262d5f4e6b81.png)

Here you can see a live link:
https://www.commandsandcolors.net/tideofiron/scenarios/western-front/319-achtung-panzer.html

I can confirm the line 
COM_KUNENA_USER_ATTACHMENT_FILE_WEIGHT = "KB
is present inside
/language/en-GB/en-GB.com_kunena.templates.ini

but it seems like the discussbot plugin is searching for that field inside 
/language/en-GB/en-GB.com_kunena.ini

**Comment by rich20** [comment]
Ok, this error occurs when files, e.g. a zip file, are uploaded to the forum and inserted into the post. 
Then you see the language code on the Joomla discussion page.

**Comment by xillibit** [comment]
I have moved the string into : /language/en-GB/en-GB.com_kunena.ini
