### ISSUE TITLE
In the configuration report the chosen time period is missing for Recent Topics

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9495]
In K5. this was always displayed.

**Comment by xillibit** [comment]
Where do-you see that in the report configuration of K5.x ?

**Comment by rich20** [comment]
Hm.. it seems that I was mistaken, I was firmly of the opinion that this was displayed in K5.2.

**Comment by xillibit** [comment]
The time period it's present already in the configuration settings, but you mean the user settings from his profile ?
