### ISSUE TITLE
Smilies are incorrectly mapped to image files

### ISSUE THREAD

**Issue by c-schmitz** [Kunena/Kunena-Forum#9499]
**Describe the bug**
When writing a happy smiley I get a dignified one shown.
The smilie images don't match the intended expression from the smilie table

**To Reproduce**

Write a :-) smiley in the forum.
Save.

**Expected behavior**
Get shown a happy smiley

**Actual result**
A neutral/pouting smiley is shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/1364282/229442683-1411c6b5-ed5c-4bac-a40d-cb0282bf9f29.png)

**System information (please complete the following information)**

Joomla version: Latest 4.x
Kunena version: Latest 5.x
Php version: n/a
Database version: n/a

**Comment by xillibit** [comment]
I have tried on Kunena 6.2 i'am not able to reproduce the problem, if you have still the issue with this version please open a new issue.
