### ISSUE TITLE
Reply with PM to a message containing a PM results in an error

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9504]
**To Reproduce**
write a PM
reply to this message with a PM

**Result**
Duplicate. Identical message has been ignored.

Kunena\Forum\Libraries\Table\KunenaTableMap::add(): Argument #1 ($id) must be of type int, null given, called in .../components/com_kunena/src/Controllers/TopicController.php on line 1152 

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Table/KunenaTableMap.php:255
2 | Kunena\Forum\Libraries\Table\KunenaTableMap->add() | JROOT/components/com_kunena/src/Controllers/TopicController.php:1152
3 | Kunena\Forum\Site\Controllers\TopicController->postPrivate() | JROOT/components/com_kunena/src/Controllers/TopicController.php:893
4 | Kunena\Forum\Site\Controllers\TopicController->post() | JROOT/libraries/kunena/src/Controller/KunenaController.php:319
5 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:226
6 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:108
7 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
8 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
9 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
10 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
12 | require_once() | JROOT/index.php:32

**System information**
- Joomla version: ‎4.2.10-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA2-DEV
- Kunena template: Aurelia
- Php version: 8.0.28
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Not able to reproduce : 


https://user-images.githubusercontent.com/876395/232200367-6445f929-64a2-46de-908a-24bf14d7aa52.mp4

**Comment by rich20** [comment]
Try it with a normal registered user. If it works the first time, then write again a PM with the same user.

**Comment by xillibit** [comment]
No error neither with normal user : 

https://user-images.githubusercontent.com/876395/232290794-71306634-5d55-475f-8c63-38e9e9a7ca64.mp4

**Comment by rich20** [comment]
If I knew exactly what was causing the error, I would have given more information. Try writing only a few PMs in a row and leave the message field empty.
