### ISSUE TITLE
KunenaImage.php uses exif_read_data() which is not available on many PHP installations

### ISSUE THREAD

**Issue by vvsvvsvvs** [Kunena/Kunena-Forum#9506]
KunenaImage.php uses exif_read_data() which is not available on many PHP installations, thus, the code produces errors on image uploads (long lasting problem, stressed in some reports).
Maybe, better to quote it with
if(function_exists("exif_read_data"))

**Comment by xillibit** [comment]
If exif_read_data() method isn't available or not enabled it will throw an exception
