### ISSUE TITLE
The table #___kunena_private_user_map is not updated during an update

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9507]
![image65410](https://user-images.githubusercontent.com/888847/231559854-3be1ea3f-4c65-4265-adf9-9ab6b913f76c.png)

**System information**
- Joomla version: ‎4.2.10-dev and ‎4.3.0-rc3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA2
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Just tried the update from K6.1 beta1 and the columns are right updated in the table

**Comment by rich20** [comment]
I've updated from the first beta2 to the last beta2

**Comment by xillibit** [comment]
Are-you tried from beta 1 to beta 3 ?

**Comment by rich20** [comment]
When upgrading from Beta 1 to Beta 3, it works. So I am closing this issue.
