### ISSUE TITLE
Please complete Kunena installation!

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9508]
1. Install Kunena 6.1.0-BETA2
2. Go to the Joomla dashboard and you see this message

**System information**
- Joomla version: ‎4.2.10-dev and ‎4.3.0-rc3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA2
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
it should affects K6.0 too

**Comment by Leen29** [comment]
I also see this message on the front "Class "ScssPhp\ScssPhp\Compiler" not found"
and in administrator part indeed at Home Dashboard "Please complete Kunena installation!"
update
after changing the code as shown here it was solved
https://github.com/Kunena/Kunena-Forum/commit/4394057604c9c85947b84e584f7ede65cc8dfc43
