### ISSUE TITLE
Error when remove Kunena via tools if Community Builder integration is enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9509]
**Describe the bug**

**To Reproduce**
<blockquote class="blockquote">
                            <span class="badge bg-secondary">0</span>
                            Call to a member function getQuery() on null                        </blockquote>
                                                    <div>
                                

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Route/KunenaRoute.php:223
2 | Kunena\Forum\Libraries\Route\KunenaRoute::prepare() | JROOT/libraries/kunena/src/Route/KunenaRoute.php:191
3 | Kunena\Forum\Libraries\Route\KunenaRoute::current() | JROOT/plugins/kunena/comprofiler/KunenaLoginComprofiler.php:70
4 | Kunena\Forum\Plugin\Kunena\Comprofiler\KunenaLoginComprofiler->loginUser() | JROOT/libraries/kunena/src/Login/KunenaLogin.php:122
5 | Kunena\Forum\Libraries\Login\KunenaLogin->loginUser() | JROOT/administrator/components/com_kunena/src/Controller/ToolsController.php:903
6 | Kunena\Forum\Administrator\Controller\ToolsController->uninstall() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
13 | require_once() | JROOT/administrator/index.php:32

</div>

**System information**
- Joomla version: ‎4.2.10-dev and ‎4.3.0-beta5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA2
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
@Beat : Could be related to CB, do-you have an idea ?

**Comment by beat** [comment]
@xillibit Looking at error ( Call to a member function getQuery() on null) and file of error (JROOT/libraries/kunena/src/Route/KunenaRoute.php:223 https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/libraries/kunena/src/Route/KunenaRoute.php#L223 ) and call stack, I doubt it is related to CB. It more looks like the Kunena uninstaller is not uninstalling the "JROOT/plugins/kunena/comprofiler" plugin https://github.com/Kunena/Kunena-Forum/tree/K6.0/src/plugins/plg_kunena_comprofiler of Kunena ?

**Comment by xillibit** [comment]
@beat  : Thanks to have take a look, finally i have made a fix in KunenaRoute
