### ISSUE TITLE
Error when remove Kunena via tools if Community Builder integration is enabled (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9510]
https://github.com/Kunena/Kunena-Forum/issues/9509

Now there is the error message:
**Login failed to launch uninstall process**

**System information**
- Joomla version: ‎4.2.10-dev and ‎4.3.0-beta5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-BETA2
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
There is the same issue in K6.0
