### ISSUE TITLE
Something is wrong with the language string COM_KUNENA_A_CATEGORY_SAVE_FAILED

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9514]
**This was the old translation**
COM_KUNENA_A_CATEGORY_SAVE_FAILED = "Saving category %d failed: %s."

**On Transifex is now new**
COM_KUNENA_A_CATEGORY_SAVE_FAILED = "Saving category %s failed :"
https://github.com/Kunena/Kunena-Forum/blob/66d276efda55c1b5226cae28a519485d305bb9c7/src/admin/language/en-GB/en-GB.com_kunena.controllers.ini#L32

**Expected behavior**
Either the colon should be replaced by a dot or a Unicode character should be added after the colon.

**Comment by xillibit** [comment]
Why ? what is the issue ?

**Comment by rich20** [comment]
If there is a colon at the end of a sentence, a note must follow. A colon does not end a sentence, but is expected to be followed by a further explanation.
