### ISSUE TITLE
New smileys are displayed several times

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9521]
**To Reproduce**

1. go to the emoticons manager
2. upload a small image (new smiley)
3. create a new smiley with it

**Actual result**
The new smiley is displayed in many places (see image)
.
![image1a0](https://user-images.githubusercontent.com/888847/236468272-43324e42-bb43-42fa-b1c2-16a55850cecc.png)

**System information**
- Joomla version: ‎4.3.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.11-DEV and 6.1.0-BETA3
- Kunena template: Aurelia
- Php version: 8.0.28 and 8.1.16 
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I'am not able to reproduce it, i have  created this new smiley: 
![image](https://github.com/Kunena/Kunena-Forum/assets/876395/a07365f9-63f6-4123-9bd9-8d62abc010aa)

then in frontend it doesn't displayed like you show it

Which code did-you have set for your new smiley ?

**Comment by rich20** [comment]
https://www.kunena.org/forum/installation-issues/168180-sunglass-icon-displayed-after-punctuation-mark-in-descriptions-and-categories

**Comment by rich20** [comment]
Found the problem. The error occurs when in the smilie management the field for the smiley code is empty.

**Comment by xillibit** [comment]
In which cases is-it empty ?

**Comment by rich20** [comment]
Can have various causes. Either you forget the code for self-created smilies, or a smiley has been edited. It is also possible that a smiley is not migrated correctly during a migration.
