### ISSUE TITLE
Language strings for private messages missing

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9522]
These two language strings are currently only available in the English language.
https://github.com/Kunena/Kunena-Forum/blob/8a81f2a23bbd916f7cb620893896be7cfcb7f06b/src/site/language/en-GB/en-GB.com_kunena.templates.ini#L445

COM_KUNENA_MESSAGE_TAB_MESSAGE = "Message"
COM_KUNENA_MESSAGE_TAB_PRIVATE_MESSAGE = "Private message"

**Comment by xillibit** [comment]
I don't have yet set up transifex for Kunena 6.1

**Comment by rich20** [comment]
ok

**Comment by xillibit** [comment]
Fixed by commit : https://github.com/Kunena/Kunena-Forum/commit/b0173cb599203b1c2f45a91fa8bd4c147013036a
