### ISSUE TITLE
A normal registered user cannot give karma (neither plus nor minus).

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9531]
**To Reproduce**
As a registered user, try to give a karma (whether plus or minus).

**Actual result**
You can modify only one person's karma every six hours.
Please wait until this timeout period has passed before modifying any person's karma again.

**System information**
- Joomla version: ‎4.3.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.0-RC2-DEV
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It's the normal behaviour i have tried with normal user after that i have gived the karma and if i re-try i have this message

**Comment by rich20** [comment]
Yes, that's how it should be. The problem is that after the first click:

- [ ] the karma vote is not displayed
- [ ] you can't vote for another user after that either

**Comment by xillibit** [comment]
> * you can't vote for another user after that either

will be fixed in 6.2
