### ISSUE TITLE
You can't vote karma consecutive times on differents users (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9547]
https://github.com/Kunena/Kunena-Forum/issues/9536
This error still exists.

**To Reproduce**

1. As a registered user, try to give a karma (whether plus or minus)
2. Now try it with another user

**Actual result**
You can modify only one person's karma every six hours.
Please wait until this timeout period has passed before modifying any person's karma again.

**System information**
- Joomla version: ‎4.3.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.2-DEV
- Kunena template: Aurelia
- Php version: 8.1.16
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It has been fixed in 6.2 not in 6.1

**Comment by xillibit** [comment]
Implemented in K6.2 with : https://github.com/Kunena/Kunena-Forum/commit/bbdd0091e05f5b05e218435230972c5136c090b3

**Comment by rich20** [comment]
Works with K6.2
