### ISSUE TITLE
Deleting attachment from topic failing

### ISSUE THREAD

**Issue by aidanwhiteley** [Kunena/Kunena-Forum#9551]
**Describe the bug**
When a user wants to delete an attachment they have incorrectly added to a (new) topic, the action fails with a 403 permission denied. The underlying problem seems to be a mis-match between the parameter id in the delete Ajax request and the parameter expected on the server side PHP code

**To Reproduce**
1. Go New Topic
2. Create a new topic and text
3. Add an attachment
4. Then try to delete the attachment. 
5. Nothing is shown in the GUI but the browser console / networking tab show a 403 on the following request:
<domain>/forum/topic/task-removeattachments?format=json&<redacted>=1&files_id_delete=[1494]&editor_text= 403

**Expected behavior**
The attachment should be deleted

**Actual result**
There is no change / message in the web page GUI

**Screenshots**
![kunena-topic-file-removal](https://github.com/Kunena/Kunena-Forum/assets/2916053/f6ef24e6-edca-40da-9fae-77f05ee39780)
After proposed fix
![kunena-topic-file-removal-success-network](https://github.com/Kunena/Kunena-Forum/assets/2916053/a8aa4e34-e983-4eee-b8cc-1fd882e17e78)

**System information (please complete the following information)**

Joomla version: 4.3.3
Kunena version: 6.1.2
Php version: 8.0.29
Database version: 5.7.42

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 115.0.5790.111

**Smartphone (please complete the following information):**
n/a

**Additional context**
Changing line 275 of components/com_kunena/src/Controllers   TopicController.php
from
$attach_id = $this->input->getInt('file_id', 0);
to
$attach_id = $this->input->getInt('files_id_delete', 0);
to match the input parameter seems to solve the problem.

However, this comes with the huge caveat that I don't "do" PHP!

**Comment by xillibit** [comment]
I'am not able to reproduce this issue, when doing that i'am able to delete the attachment

**Comment by aidanwhiteley** [comment]
Hi,

wow - thanks - that was super speedy!

This isn't a problem for me as I have a working site, but just as a double check, was your test done running as an admin or mod? If so, you'd have passed the following test at line 279 of the above file (whereas my testing failed all 3 of the condition checks with the first check being problematic when then id of the attachment wasn't being found).

        if (
            KunenaUserHelper::getMyself()->userid == $instance->userid || KunenaUserHelper::getMyself()->isAdmin()
            || KunenaUserHelper::getMyself()->isModerator()
			....
		} else {
			throw new RuntimeException(Text::_('Forbidden'), 403);
		}
	
But happy for this to be closed if that's not the issue.
	
Cheers

**Comment by xillibit** [comment]
Yes you are right i have tried with normal user without moderator rights and i'am able to reproduce the issue

**Comment by xillibit** [comment]
Closed because it's fixed
