### ISSUE TITLE
Kunena should support keypass (webauthn) login  

### ISSUE THREAD

**Issue by jschmi102** [Kunena/Kunena-Forum#9552]
**Is your feature request related to a problem? Please describe.**
Since joomla 4.2.x webauthn (keypass) is supported, by joomla - e.g. to provide passwordless  login.   

**Describe the solution you'd like**
At this stage Kunena does not provide a similar interface in its login implementation.. Kunena should use joomla's interfaces to adopt support for its own login interface e.g. like or with joomla's login module.

**Comment by jschmi102** [comment]
I have implemented on my site ("https://www.jschmidt-systemberatung.de/index.php?option=com_kunena&view=category&layout=list&Itemid=1319&lang=en") a solution. Which is quite easy to adopt. If anybody is interested I will explain and help how to use it

**Comment by xillibit** [comment]
I'am interessed, if you can give me how you have integrated it so i can add it in a future version of Kunena

**Comment by jschmi102** [comment]
hi,

I'v provided a small doc on "https://www.jschmidt-systemberatung.de/index.php?option=com_content&view=article&id=354&Itemid=40&lang=en" - please read and check.

**Comment by jschmi102** [comment]
hi 
updated my doc [please read updated version](https://www.jschmidt-systemberatung.de/index.php?option=com_content&view=article&id=354&Itemid=40&lang=en)
