### ISSUE TITLE
Incorrect country code in ckeditor.js

### ISSUE THREAD

**Issue by Gindi50** [Kunena/Kunena-Forum#9553]
**Describe the bug**
Users from the Netherlands cannot open the ckeditor to reply in a post.
They can only reply to the post using the quick reply.

**To Reproduce**
Users from the English or German language area cannot reproduce the behavior

**Actual result**
To fix the problem, in the /media/kunena/core/js/ckeditor.js file, at the end of the file, change the last line "CKEDITOR.lang.languages={"nl":1};}()); " to "CKEDITOR.lang.languages={"en":1};}()); ".
After that the CKEditor works for the Dutch users.

**System information (please complete the following information)**

Joomla version: 4.3.3
Kunena version: 6.1.3
Php version: 8.1.21
Database version: 5.7.41-log

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 115.1.0 esr

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Leen29** [comment]
Yes I can confirm that

**Comment by xillibit** [comment]
Fixed in commit https://github.com/Kunena/Kunena-Forum/commit/9686a6ad548b6adf33c2f02c680ee502f08ff54e
