### ISSUE TITLE
Unpublished categories are shown as published

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9554]
https://www.kunena.org/forum/installation-issues/168032-forum-lost-categories-after-upgrade-to-j4

**Describe the bug**
Unpublish one or more categories

**Result**
The categories are still displayed as published, so that it is not possible to distinguish whether categories are published or not.

**System information**
- Joomla version: ‎4.3.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.4-DEV
- Kunena template: Aurelia
- Php version: 8.1.22
- Database version: 10.5.19-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Gindi50** [comment]
I have checked this in the different versions. In BETA versions of Kunena 6.1.0 up to version 6.1.0_RC2-DEV_2023-05-18, the unpublished sections and categories are also shown as unpublished.
From Kunena 6.1.0_2023-05-29 all sections and categories are shown as published.
Gindi
