### ISSUE TITLE
Cannot save message: Invalid email address!

### ISSUE THREAD

**Issue by alecrespi78** [Kunena/Kunena-Forum#9556]
**Describe the bug**

This message shows up while editing or moderating/deleting a post.
Forum contents/posts migrated from previous kunena version.

The error does not sow up in new posts (editing works as expected).

**To Reproduce**
1. Login on a Joomla website
2. Open a Kunena / Dashboard
3. Click on a migrated post (see sample)
4. Select "Action / Edit"
5. Click "Submit"

Sample post: https://www.commandsandcolors.net/thegreatwar/forum.html?view=topic&defaultmenu=916&catid=9&id=380&start=50#1273

**Expected behavior**
No error messages and changes saved.

**Actual result**
Error - Cannot save message: Invalid email address!
Changes unsaved.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 4.3.4
Kunena version: 6.1.3.1 | 2023-08-21
Php version: 8.2.7
Database version: 5.7.32-35

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 116.0.5845.141

**Comment by Leen29** [comment]
i can confirm that   I noticed that myself on my updated websites

**Comment by alecrespi78** [comment]
Kunena has been updated right now but the bug is still present.

Kunena version:  6.1.3.2   |   2023-09-05

**Comment by xillibit** [comment]
I'am not able to reproduce this one, i have tested on a backup on a site which was on K5.2

**Comment by Leen29** [comment]
I can no longer reproduce it after the update

**Comment by Deciman** [comment]
I can confirm that issue...

Joomla 4.4.0
Kunena 6.2.0 2023-10-17
Php 8.1
MySql 8.0

And I can reproduce it for not only one user (poster)
All in common for them is the email domain '@t-online.de'

Deci

**Comment by xillibit** [comment]
When updating from previous kunena version (before the 6.0.4) this query on update process is already applied, the users here which have the issue uses MySQL so needs to check with MySQL what's going on

**Comment by Deciman** [comment]
Reason war empty email field tab in _kunena_messages
Filled them with NULL and now it's working as expected

Deci

**Comment by xillibit** [comment]
I have found a way to avoid to have this issue, the fix is above in my PR
