### ISSUE TITLE
Wrong collation of type utf8_general_ci after upgrading from K5.2 to K6.x 

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9560]
**Describe the bug**
Only the table collations are adjusted, but not the column collations.

**To Reproduce**

1. Upgrade from K5.2 to K6.1
2. Create a configuration report

**Result**
The configuration report shows "wrong collation of type utf8_general_ci" because the column collations are not adjusted.

**System information**
- Joomla version: ‎4.3.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.1.4-DEV
- Kunena template: Aurelia
- Php version: 8.1.22
- Database version: 10.5.21-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Leen29** [comment]
Yes, I can confirm that too

**Comment by xillibit** [comment]
I have looked on the configuration report added to the messages on kunena.org, i have seen that the collation was in : `utf8_general_ci` or `utf8mb3_general_ci` or `utf8_unicode_ci`. So my changes check that and set when needed the correct collation to all column
