### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9563]
Running Joomla 4.3.4 and Kunena 6.1.3.2

Seeing lots of these errors in my log file:

PHP Warning: Undefined variable $target in /var/www/html/we/xxxxx/components/com_kunena/template/aurelia/layouts/bbcode/url/default.php on line 32
PHP Warning: Undefined variable $end_tag_params in /var/www/html/we/xxxxx/libraries/kunena/External/Nbbc/src/BBCode.php on line 2321

Comparing these two files to the same ones in kunena 3 I see that these variables are established
e.g. 
$target = ‘’;
$end_tag_params = ‘’;

So, I have added the to the kunena 4.3.4 files and the errors have gone away.
Is this a bug?

**Comment by xillibit** [comment]
I'am testing it on Kunena 6.2.0 but i'am not able to get these errors messages. 
For the Undefined variable $end_tag_params in /var/www/html/we/xxxxx/libraries/kunena/External/Nbbc/src/BBCode.php on line 2321 you can only have if you have enabled debug mode for BBCode

**Comment by makitso** [comment]
I think it was caused by FastCGI.  I turned it off and have not has the errors since then.

**Comment by xillibit** [comment]
I have just added that : https://github.com/Kunena/Kunena-Forum/commit/f1171fa90f14a110d72ac393634b69ebb85bcdf8 for the Undefined variable $target
