### ISSUE TITLE
Kunena 6.2.0 causes a fatal HTTP 500 error (in the frontend) when using with the "Astroid" template Framework (v2.6.6 .. v3.0.x)

### ISSUE THREAD

**Issue by BlackBrix** [Kunena/Kunena-Forum#9574]
**Describe the bug**
Kunena 6.2.0 causes a fatal HTTP 500 error (in the frontend) when using with the "Astroid" template Framework (v2.6.6 .. v3.0.x)
-> see here: 
https://github.com/templaza/astroid-framework/issues/412#issuecomment-1772273011
https://github.com/templaza/astroid-framework/issues/412#issuecomment-1774582474

**To Reproduce**
 - take a blank Joomla 4.4.0 Installation
 - install Astroid Framework 3.0.2
 - install a Astroid based template
 - install Kunena 6.1.4
 - choose the Astroid based template as default in Joomla backend
 - go to Front-End -> everything looks OK
 - upgrade to Kunena 6.2.0
 - go to Front-End -> still everything looks OK
 - go into the Kunena "dashboard" in the backend the first time
 - go to Front-End -> you will see the HTTP 500 error (backend still working)
 - (deinstall Kunena -> front end works again)

**Expected behavior**
no error in the frontend

**Actual result**
a HTTP 500 error in the Frontend  
`$number: null is not a number.: libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tp_business/scss/../../../../astroid/assets/vendor/bootstrap/scss/_functions.scss on line 13, at column 5  
Call Stack:  
#0 mixin _assert-ascending libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tp_business/scss/../../../../astroid/assets/vendor/bootstrap/scss/_variables.scss on line 494
#1 import libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tp_business/scss/../../../../astroid/assets/vendor/bootstrap/scss/_variables.scss libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tp_business/scss/../../../../astroid/assets/vendor/bootstrap/scss/bootstrap.scss on line 8
#2 import libraries/astroid/framework/library/astroid/./../../../../../media/templates/site/tp_business/scss/../../../../astroid/assets/vendor/bootstrap/scss/bootstrap.scss (unknown file) on line 1`  
and additional see here: https://github.com/templaza/astroid-framework/issues/412#issuecomment-1783364374

**System information (please complete the following information)**

Joomla version: 4.4.0
Kunena version: 6.2.0
Php version: 8.1.24
Database version: mysql 8.0.33-25

**Additional context**
other users can reproduce this issue
-> https://github.com/templaza/astroid-framework/issues/412#issuecomment-1783364374

you can't get astroid 3.0.x framework to work **with** kunena 6.2.0 -> apparently something "interferes" with each other (?):
- kunena 6.2.0 works well without astroid 3.0.x based templates.
- astroid 3.0.x based templates work well without kunena 6.2.0 (must be completely uninstalled or use K6.1.4 instead)
- astroid 3.0.x based templates together with kunena 6.2.0 does **not** work -> frontend shows HTTP 500 error (backend works fine)

so not sure if Astroid Framework or Kunena 6.2.0 is the root cause here ...

Astroid developer sais:
> It's because Astroid Cache stored the css. And you can see the front-end is working. But when you access to Kunena Dashboard, It remove all Astroid cache and it happens again. It's very strange when Kunena use a System plugin to trigger to another extension like that.

**Comment by xillibit** [comment]
I think it's because the astroid framework use the scssphp from Kunena. Because it's loaded with a generic name all under Joomla! can use it

`at /MyLocalhostPath/libraries/kunena/External/scssphp/scssphp/src/Compiler.php:565` the namescape is `ScssPhp\\ScssPhp\\`

I will look if i can change the namespace to put Kunena in it to avoid others use it

**Comment by BlackBrix** [comment]
> I will look if i can change the namespace to put Kunena in it to avoid others use it

OK, a namespace issue ?
maybe you can talk to each other not to use the same (generic) names / namespaces (?)
->https://github.com/sonvnn  
@sonvnn

I am not an expert in this ...

Thank you very much for taking care of this problem !

**Comment by rich20** [comment]
> I think it's because the astroid framework use the scssphp from Kunena.

Yes, if I disable the Kunena system plugin and refresh the page, the correct data is loaded. If I enable the Kunena plugin again afterwards, everything works as it should.

**Comment by xillibit** [comment]
In the Astroid framework, the same namespace is declared like in Kunena : https://github.com/search?q=repo%3Atemplaza%2Fastroid-framework%20ScssPhp&type=code

I don't know how Php handle that, it seems it loads just one

**Comment by xillibit** [comment]
I have just made a change for it

**Comment by BlackBrix** [comment]
will it be released in 6.2.1 then ?

**Comment by xillibit** [comment]
Yes this fix will be in the K6.2.1 release

**Comment by BlackBrix** [comment]
would it be possible to give me a "nightly K6.2.0" where these changes are already made ?
(I don't know how to create this myself out of the current K6.2.0 branch. https://github.com/Kunena/Kunena-Forum/tree/K6.2)
so that I can test everything ...

**Comment by xillibit** [comment]
Yes this is a nightly build : https://update.kunena.org/nightlybuilds/pkg_kunena_v6.2.1-DEV_2023-11-01.zip
