### ISSUE TITLE
Poll: click on vote results in an error

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9578]
**To Reproduce**

- Create a poll
- Clickk on Vote

**Result**
Kunena\Forum\Libraries\Forum\Topic\Poll\KunenaPoll::vote(): Argument #1 ($option) must be of type int, string given, called in .../components/com_kunena/src/Controllers/TopicController.php on line 2457

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Forum/Topic/Poll/KunenaPoll.php:363
2 | Kunena\Forum\Libraries\Forum\Topic\Poll\KunenaPoll->vote() | JROOT/components/com_kunena/src/Controllers/TopicController.php:2457
3 | Kunena\Forum\Site\Controllers\TopicController->vote() | JROOT/libraries/kunena/src/Controller/KunenaController.php:323
4 | Kunena\Forum\Libraries\Controller\KunenaController->executeTask() | JROOT/libraries/kunena/src/Controller/KunenaController.php:226
5 | Kunena\Forum\Libraries\Controller\KunenaController->execute() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:108
6 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
11 | require_once() | JROOT/index.php:32

**System information**
- Joomla version: ‎4.4.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.2.1-DEV
- Kunena template: Aurelia
- Php version: 8.1.22
- Database version: 10.5.22-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It's when you don't select any option then click on vote

**Comment by rich20** [comment]
Yes, if no option has been selected. There should be a hint instead of the error message if nothing has been selected.
