### ISSUE TITLE
New polls is created as expired by default

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9579]
**To Reproduce**

1. create a poll
2. let the Poll life span field empty
3. save the message

**Result**
The new poll has expired 

**System information**
- Joomla version: ‎4.4.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.2.1-DEV
- Kunena template: Aurelia
- Php version: 8.1.22
- Database version: 10.5.22-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I don't have that when i save the message i don't have an error message saying that poll has expired

**Comment by rich20** [comment]
I have this problem on one of my test pages. There it also shows outdated codes, although Kunena 6.2.1-DEV is installed.

Deprecated: DateTimeImmutable::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 105

Deprecated: Creation of dynamic property Kunena\Forum\Site\Controller\Topic\Poll\TopicPollDisplay::$intervalTimeToLive is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 106

Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Layout\KunenaLayout::$intervalTimeToLive is deprecated in .../libraries/kunena/src/Layout/KunenaBase.php on line 571
Poll: test (was ended )

**Comment by xillibit** [comment]
> 
> Deprecated: Creation of dynamic property Kunena\Forum\Site\Controller\Topic\Poll\TopicPollDisplay::$intervalTimeToLive is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 106
> 


The following commit : https://github.com/Kunena/Kunena-Forum/commit/c8881c459b1bcd410b15782890558bf7d0128330 should fix that

**Comment by rich20** [comment]
Partial success. The "Deprecated: DateTimeImmutable..." is now gone

- [x] Deprecated: DateTimeImmutable::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 105

- [ ] Deprecated: Creation of dynamic property Kunena\Forum\Site\Controller\Topic\Poll\TopicPollDisplay::$intervalTimeToLive is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 106

- [ ] Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Layout\KunenaLayout::$intervalTimeToLive is deprecated in .../libraries/kunena/src/Layout/KunenaBase.php on line 571

- [ ] Poll: Test (was ended )

**Comment by xillibit** [comment]
I don't reproduce this issue with J!5.0 and Php 8.2.x and MySQL 8.0 : 

https://github.com/Kunena/Kunena-Forum/assets/876395/c7c24c64-7aba-40d8-a9d0-2b0d7a77eea7

**Comment by rich20** [comment]
I believe you. Apparently, outdated code is not always displayed. In the case of this error https://github.com/Kunena/Kunena-Forum/issues/9562, nobody was able to confirm it for a long time, and yet it was actually there.

One message has now disappeared again with the last correction. 

- [x] Deprecated: DateTimeImmutable::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 105

- [x] Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Layout\KunenaLayout::$intervalTimeToLive is deprecated in .../libraries/kunena/src/Layout/KunenaBase.php on line 571

- [ ] Deprecated: Creation of dynamic property Kunena\Forum\Site\Controller\Topic\Poll\TopicPollDisplay::$intervalTimeToLive is deprecated in .../components/com_kunena/src/Controller/Topic/Poll/TopicPollDisplay.php on line 106


- [ ] Poll: Test (was ended )

**Comment by 810** [comment]
@rich20 can you try again, then we can close this one

**Comment by rich20** [comment]
Seems to be done
