### ISSUE TITLE
Upgrade from 6.2.0 to 6.2.1 - Kunena menu Custom Content fails to display articles

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9584]
Joomla 4.4, Kunena 6.2.1.
Have added several tabs to the Kunena Menu.  Menu type is Custom content, with Main Setting pointing to article [article=full]75[/article].
This has worked fine until the latest Kunena upgrade to 6.2.1.  Once updated the article does not display.  There are no errors in the developers platform or logs. 
Note:  reloading libraries/kunena from the 6.2.0 version and the articles appear as expected

**Comment by makitso** [comment]
As a test, I created a new install, Joomla and kunena. I then created one article. I then added a sub menu to the Kunena menu.  When I selected the forum menu tab nothing was displayed.

**Comment by makitso** [comment]
With kunena 6.2.0, the added kunena menu item worked correctly using the rules noted in https://docs.kunena.org/en/faq/rules-or-help-pages listed below:

Backend -> Menus -> Kunena Menu

    • Click New
    • Select Menu Item Type - Kunena Forum - Custom Content
    • Menu Title - Rules
    • Parent Item - Forum
    • Click (tab) Main Settings
    • Contents Format - BBCode **
    • Enter the article ID number – [article=full]123[/article]
    • Save & Close

The problem is that kunena 6.2.1 does not work with the [article=full]123[/article]

**Comment by rich20** [comment]
Confirmed.
Custom content works only with format HTML
- [x] HTML
- [ ] Text
- [ ] BBCode

**Comment by rich20** [comment]
- [x] Solved
