### ISSUE TITLE
Apple Safari styling fails with media statement

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9596]
**Describe the bug**
The kunena file template.css or template.min.css has the following entry selector:

@media (width >= 992px) {
    .container-header .mod-menu {
        flex-direction: row;
        flex: 1;
        display: flex;
    }
}
Safari does not recognize the width >=  and bypasses the entire selector.
Changing selector to this format and the selector works.
@media (min-width: 992px)

Joomla version:  4.4.1
Kunena version: 6.2.1
Php version: 8.1.25
Database version: 10.5.21-MariaDB

**Desktop (please complete the following information):**
 - OS: iOS Ventura
 - Browser Safari
 - Version 17

**Comment by 810** [comment]
Kunena uses only fixed operator like: `@media (max-width: 320px) {`

So im closing this issue
