### ISSUE TITLE
 [K 6.3]Deprecated: Creation of dynamic property on New Topic when captcha is enabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9597]
**To Reproduce**
Use captcha either for registered users or guests with write access
Create a new topic with an user or guest

**Actual result**
Deprecated: Creation of dynamic property Kunena\Forum\Site\Controller\Topic\Form\Create\TopicFormCreateDisplay::$captchaDisplay is deprecated in .../components/com_kunena/src/Controller/Topic/Form/Create/TopicFormCreateDisplay.php on line 175

**System information**
- Joomla version: ‎5.0.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.0-DEV
- Kunena template: Aurelia
- Php version: 8.2.9
- Database version: 10.5.22-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
did a small change in PR #9595 for this, can you test?

**Comment by rich20** [comment]
- [x] Success
