### ISSUE TITLE
Search by username: The suggestions are no longer listed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9598]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/168235-searching-username
Confirmed

**To Reproduce**
Log in and search for a user name

**Result**
In earlier versions, suggestions were listed (see image), this is no longer the case with Kunena 6.2.
.
![Bildschirmfoto vom 2023-12-19 14-48-26](https://github.com/Kunena/Kunena-Forum/assets/888847/e3a3ce5c-bfbb-4a90-8437-2a4a360bed62)

**Comment by xillibit** [comment]
I had changed something for this on the K6.3, it's availaible in the beta1 did-you have tested it ?

**Comment by xillibit** [comment]
Fixed in K6.3, open an new issue if it's still here
