### ISSUE TITLE
Karma: Unknown column 'karma_time' in 'field list'

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9599]
**Describe the bug**
https://www.kunena.org/forum/k-6-2-0-support/168260-karma-profile-issues
Confirmed

**To Reproduce**
Click on Karma plus or minus symbol and you see the error:
Unknown column 'karma_time' in 'field list'

**System information**
- Joomla version: ‎4.4.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.2.3-DEV
- Kunena template: Aurelia
- Php version: 8.2.9
- Database version: 10.5.22-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
I'am not able to reproduce it

**Comment by rich20** [comment]
It is probably related to the karma_time column that was removed from the kunena_users table.

In this context, you should also prevent this column from being created during a new installation. According to _creates_tables.utf8_.sql and _install.xml_, these are created even though this column is removed again during an upgrade.
_kunena.install.upgrade.xml_ : ALTER TABLE `#__kunena_users` DROP `karma_time`;

**Comment by xillibit** [comment]
Try with the two commits that i had done yestayday : https://github.com/Kunena/Kunena-Forum/commit/b71643a3c3a3314a9ea6e3ed9b50b98489a027e0 and https://github.com/Kunena/Kunena-Forum/commit/3f7c9d89c9cb191fd20708fc9f3fe947c0330654

**Comment by rich20** [comment]
In principle, karma now works. However, users can increase or decrease the karma indefinitely without a time limit. 
The first time you vote, everything is ok, but if you continue to vote after that, you will get each time additional the error message:
_Kunena Internal Error: Please contact the site administrator to fix this issue!_

**Comment by xillibit** [comment]
> In principle, karma now works. However, users can increase or decrease the karma indefinitely without a time limit.

if you are admin or mod it's normal but not if you are a simple user, i will check it

**Comment by xillibit** [comment]
With an User i can't set karma multiples times
