### ISSUE TITLE
EasyDiscuss to Kunena migrator

### ISSUE THREAD

**Issue by hans2103** [Kunena/Kunena-Forum#9601]
**Is your feature request related to a problem? Please describe.**

I want to switch from StackIdeas EasyDiscuss to Kunena Forum. Is there a way to import all content?

**Describe the solution you'd like**

EasyDiscuss has a migration tool from Kunena to EasyDiscuss... I would like to be able to do the same, but in reverse direction.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hans2103** [comment]
Any progress on this issue?
For the website JoomlaCommunity.nl I would love to switch from EasyDiscuss to Kunena.
I need your help for this

**Comment by hans2103** [comment]
Would be nice if Kunena would answer too.

**Comment by Ruud68** [comment]
Hi @hans2103 , I'm not Kunena :) but answering nonetheless. I think that for these kind of requests there is a place on the kunena forum: https://www.kunena.org/forum/custom-work

As a ballpark figure I think this will need appr. 40 hours to figure out and execute.
