### ISSUE TITLE
Remember me via Kunena Login does not work

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9602]
https://www.kunena.org/forum/k-6-2-0-support/168172-kunena-login-button-remember-me-does-not-work
Confirmed

If you login via Kunena and mark the "Stay logged in" checkbox, no remember_me cookie will be set.

**Comment by Pinkeltje** [comment]
Title should be "Remember me via Kunena Login does not work"

**Comment by Pinkeltje** [comment]
Patched my site and it works.
But shouldn't this be changed in layouts/widget/login/login/mobile.php as well?
