### ISSUE TITLE
Automatic language recognition in CKEditor

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9618]
Something still needs to be done so that it works for all country languages available in Joomla.
All languages that are available for Joomla as well as the CKEditor must be included in our language pack, even if some of them are not yet on Transifex or have not been translated for Kunena. 
Otherwise there will be no editor in these countries if they run their website in their language.
These languages must be added to Transifex as they are also available in Joomla:

- be-BY Belarusian 
- ka-GE Georgian
- ga-IE Irish
- kk-KZ Kazakh
- ps-AF Pashto, Afghanistan
- ta-IN Tamil, India

The five scripts I uploaded are not present at the CKEditor languages. So I have adapted 5 files so that the English language is used for these countries.
[language-scripts.zip](https://github.com/Kunena/Kunena-Forum/files/14014539/language-scripts.zip)

We also have to include the untranslated languages in our language pack if we want this feature to work 100%. Otherwise it lacks the language script, which the ckeditor_config.js wants to access.

Another solution would be to install all language.js in the .../core/js/lang folder during a Kunena installation. But that would be 75 scripts (with total size 1,6 MB)

**Comment by xillibit** [comment]
> * kk-KZ Kazakh

It's the same to kz-KZ
