### ISSUE TITLE
Profile option Forum Settings - Select Subscription as default

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9620]
If a registered user changes their profile/Forum Settings/Select Subscription as default  to "No"
![image](https://github.com/Kunena/Kunena-Forum/assets/5147603/29cfc401-7f8e-4d36-8a68-09f34af38ad8)

When replying to an existing post, they are still seeing the Subscribe option.

![image](https://github.com/Kunena/Kunena-Forum/assets/5147603/81d8acb2-89d3-4df3-b07f-c6d6817b25f5)

.

joomla 4.4.2
Kunena 6.2.3

**Comment by xillibit** [comment]
Try with the following change : https://github.com/Kunena/Kunena-Forum/commit/0496f1536e95655d0f0b2e9e301e04f96f497dfa

**Comment by makitso** [comment]
Test did not fix problem.

Test user is in group Registered.
Changed profile to No
![image](https://github.com/Kunena/Kunena-Forum/assets/5147603/23f43274-db5c-4c47-8d98-5cacac4f068d)
Went to post and did a reply, still see below.
![image](https://github.com/Kunena/Kunena-Forum/assets/5147603/b75015c2-06f2-44b7-871b-31c2d5a3b216)

However, the database after setting to No is:
![image](https://github.com/Kunena/Kunena-Forum/assets/5147603/17c2476a-8e1f-4168-b922-26a2343d35d5)

**Comment by makitso** [comment]
Since this issue is during the reply, shouldn't  this change be made to 

src/Controller/Topic/Form/Reply/TopicFormReplyDisplay.php

**Comment by xillibit** [comment]
try now

**Comment by makitso** [comment]
Yes, that fixed the problem when replying to post.
However, IMO, the code should not be changed in the create. I mean if your creating a new post then you want to see any replies.
