### ISSUE TITLE
User status "Busy" is not displayed in kunena

### ISSUE THREAD

**Issue by cmirnow** [Kunena/Kunena-Forum#9621]
**Describe the bug**
User status "Busy" is not displayed in kunena.

**Screenshots**

![kunena](https://github.com/Kunena/Kunena-Forum/assets/10660173/097f6845-5f2c-4ae2-81e3-7067d0808841)

**System information**

Joomla version:  5.0.2
Kunena version: 6.2.4
Php version: 8.2

**Comment by rich20** [comment]
Confirmed
The background colours for Busy and Invisible are missing
Should be:

.badge.bg-important {
  background-color: #a51f18;
}
.badge.bg-light {
  background-color: #6d757e !important;
  color: #fff !important;
}
