### ISSUE TITLE
Doing a respond to post and changing to private message fails for attachment

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9629]
joomla 4.4.2
Kunena 6.2.4

A user recently tried to use the "Private message" feature and got surprising results. The text of my message was apparently sent only to the target individual, but the attachment was posted globally as a public message without any text. 

Steps to reproduce:
Open post
Do a reply
Select Private message
attach file.

**Comment by xillibit** [comment]
Yes you are right, I need to improve that on a future version of Kunena
