### ISSUE TITLE
Threaded view: use message contents instead of message subject

### ISSUE THREAD

**Issue by mahagr** [Kunena/Kunena-Forum#963]
As all the messages usually have the same subject, there should be configuration option in threaded view to use beginning of the message:

http://www.kunena.org/forum/K-2-0-General-Questions/123708-How-do-I-change-the-default-title-of-the-response#127920

Maybe we should even leave subject empty and if not filled, use the first words..?

**Comment by 810** [comment]
we have removed the feature on crypsis, so im closing this issue
