### ISSUE TITLE
Backend Log | Clean entries not possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9646]
**To Reproduce**
Click on the "Clean entries" button, select a short time period and click on Submit

**Result**
No entries are removed

**System information**
- Joomla version: ‎5.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.0-BETA2
- Kunena template: Aurelia
- Php version: 8.2.16
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
Hi @rich20 you explicitly say 'short period', does it work when you set a long period?
When e.g. setting 30, it would remove all log entries older then 30 days.
What short period are you trying with?

**Comment by rich20** [comment]
Hi @Ruud68 
The default is 30 days, so only the logs from the last 30 days should be retained. I have tried it with 30 days, 10 days, 1 day, 300 days, 0 days, the result is always the same. All logs are retained, nothing is removed.

**Comment by Ruud68** [comment]
Hi @rich20 
found the issue (on multiple modals).
refactored the modals to J5 but that upped the minimum Joomla version also to 5, so yesterday did a quick implementation to refactor these modals to J4.4 compatible.
Was a rush job to get the beta2 out off the door.

modals where working (visual), only the submitting of these modals not (was missing some additional onclick code.

fixed here: https://github.com/Kunena/Kunena-Forum/pull/9647

**Comment by rich20** [comment]
Thanks, it works now.
