### ISSUE TITLE
Backend Category filter

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9649]
<strike>- [x] **Select Category** - all selection options work
- [x] **Select Category Level** - all selection options work
- [x] **Select Enabled = Published** - works
- [ ] **Select Enabled = Unpublished** - does not work
- [ ] **Select Access** - does not work at all
- [x] **Select Locked = No** - works
- [ ] **Select Locked = Yes** -  does not work
- [x] **Select Review = No** - works
- [ ] **Select Review = Yes** - does not work
- [x] **Select Polls = No** - works
- [ ] **Select Polls = Yes** - does not work
- [x] **Select Anonymous = No** - works  
- [ ] **Select Anonymous = Yes** - does not work
- [x] **Select Anonymous - Incorrect selection text.** instead of Anonymous user, the word must be **Yes**
and instead of Registered user the word **No** must be available for selection. This option only hides or shows categories in which anonymity is permitted.</strike>

**Comment by Ruud68** [comment]
Hi, so I think this needs some more thought / clearification.

e.g. the enabled filter > unpublished shows all categories that are unpublished but only (!) when also the section they reside in are unpublished.

When refactoring the backend views only the interface has changed and not the actual filtering, so this (not tested as this for me never worked) is the same behavior as in 6.2 (where it probably didn't filter at all)

So maybe @xillibit can shed some light on this?

As for the access level filtering: correct that was on my list to fix (but that list got lost). Will do that together with the renaming of the anonymous seltion text (yes/no)

**Comment by rich20** [comment]
> When refactoring the backend views only the interface has changed and not the actual filtering, so this (not tested as this for me never worked) is the same behavior as in 6.2 (where it probably didn't filter at all)

You are right, the filters did never work in the Kunena 6 series.

**Comment by Ruud68** [comment]
So when getting the published status of a category it always takes into account the status of the parent. So if the parent is not disabled, then the category is also not disabled and without knowing the implications / the why that is, I am reluctant to change that: there must be a reason why it works this way... That is what we need to find out.

**Comment by Ruud68** [comment]
@rich20 I am a bit lost on this as there where discussions in several places on this topic. Can you update the checklist and tell me what is in your opinion still not working correct?

**Comment by rich20** [comment]
The first list is now out of date and I have crossed it out.
All filters work so far, but you also have to select the parent section or category. However, this should only be an additional feature.
For example, if someone wants to find all their unpublished categories, they have to filter each parent category individually. It should generally be possible to display everything without having to know the category in which my search lands a hit.
I don't know if that's possible, but if not, I'll close this ticket.

**Comment by Ruud68** [comment]
Yes, I think that is possible but this is new as to how it was implemented in the past. Hence my question about why it is implemented the way it is.
I can do A PR to filter unpublished regardless of parent state (so on the state of the category instead of on the calculated state)
For me this makes more sense (as I was initially wondering the same why it was doing that as that was not what I was expecting)

Will spend some time on that tomorrow and do a PR

**Comment by Ruud68** [comment]
can you test: https://github.com/Kunena/Kunena-Forum/pull/9659
@rich20 @xillibit

**Comment by rich20** [comment]
Fixed by this PR https://github.com/Kunena/Kunena-Forum/pull/9659
