### ISSUE TITLE
User filter in logs view shows banned users as enabled and activated

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9652]
When a user is banned from the site, it shows him Activated (see image)
and if a user is only banned from the forum, both icons are green (Enabled & Activated)
.
![g13819](https://github.com/Kunena/Kunena-Forum/assets/888847/1c406496-6bc8-4b2d-b70a-c8b5d28a7383)

**Comment by Ruud68** [comment]
There are two user related 'bans':

- The user account can be disabled / blocked in Joomla User Manager > the user is then disabled (red cross) in Joomla user manager.
When 'fetching' the user in Kunena, this blocked user will be labeled banned as he is not able to login.
- The user can be banned in Kunena, the user is then NOT blocked in Joomla (so can still log in) but cannot post / reply in the forum. As these users are not blocked, they show up as enabled in the Joomla User Manager.

So what you are describing is actually correct and IMO not a bug / issue: this is how it has always been (and I didn't change that in the refactored users view) it only now shows now that the filters are working correct.

@xillibit correct me if I'm wrong here :)

**Comment by Ruud68** [comment]
and also: the user filter in logs view is the Joomla core user field so it doesn't know anything regarding banned or not banned in kunena).

**Comment by rich20** [comment]
Yes, it's true, blocked users are also displayed as activated in Joomla. Then it can stay that way I think.

One more off-topic question: Do you also have the user selection twice?
.
![image10](https://github.com/Kunena/Kunena-Forum/assets/888847/eea28d3f-41ce-44da-bff9-18a0faf53306)

**Comment by Ruud68** [comment]
Yes I have, that was one of the reasons to do the test PR because this can lead to confusion.
One field is to select the user, the second to select the target user. But because we use the Core Joomla User field we cannot change the label so for both it displays select user.

**Comment by rich20** [comment]
Okay, thank you very much. So far everything is working and can be merged.

**Comment by rich20** [comment]
Can be merged. https://github.com/Kunena/Kunena-Forum/pull/9651
