### ISSUE TITLE
Recounting statistics causes errors

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9653]
**To Reproduce**
Backend -> Kunena -> Tools
Try to recount statistics

**Actual result**
Unknown fetch type '8'

# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:501
2 | Joomla\Database\Mysqli\MysqliStatement->fetch() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:725
3 | Joomla\Database\DatabaseDriver->fetchObject() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1307
4 | Joomla\Database\DatabaseDriver->loadObjectList() | JROOT/libraries/kunena/src/Attachment/KunenaAttachmentHelper.php:528
5 | Kunena\Forum\Libraries\Attachment\KunenaAttachmentHelper::cleanup() | JROOT/administrator/components/com_kunena/src/Controller/ToolsController.php:532
6 | Kunena\Forum\Administrator\Controller\ToolsController->doRecount() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
13 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: ‎5.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.0-BET3-DEV
- Kunena template: Aurelia
- Php version: 8.2.16
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Gindi50** [comment]
I have just recounted the statistics on my test server with K6.3.0-BETA2 and also with K6.3.0-BETA3-DEV and clicked on all four statistics defaults. 
The result was: All category statistics were recounted.

**Comment by rich20** [comment]
Ok, found the issue. Due to the many tests, I had many orphaned database entries. After cleaning everything works again.
