### ISSUE TITLE
The time zone selected in Joomla is not adopted by Kunena in the backend

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9654]
**Describe the bug**
https://www.kunena.org/forum/k-6-3-0-support/168364-help-needed-logs-backend-view?start=20#230997
Confirmed

**To Reproduce**
Select a time zone in Joomla, e.g. Amsterdam or another

**Result**
The time is only adjusted in the frontend, not in the Kunena log files. This leads to a time difference between the actions in the frontend and in the log file

**Comment by Ruud68** [comment]
@rich, did a PR #9656 for this, can you check?

**Comment by rich20** [comment]
Fixed by this PR https://github.com/Kunena/Kunena-Forum/pull/9656
