### ISSUE TITLE
Error when trying to access the trash via the dashboard

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9655]
**Describe the bug**
https://www.kunena.org/forum/k-6-3-0-support/168371-kunena-6-3-0-beta3-dashboard-trash-error#230999
Confirmed

**To Reproduce**
Go to the Dashboard and click on Trash

**Actual result**
View not found [name, type, prefix]: trash, html, Administrator 
# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/src/MVC/Controller/BaseController.php:881
2 | Joomla\CMS\MVC\Controller\BaseController->getView() | JROOT/libraries/src/MVC/Controller/BaseController.php:655
3 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:62
4 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
6 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
11 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: ‎5.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.0-BET3-DEV
- Kunena template: Aurelia
- Php version: 8.2.16
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
Hi @rich20 , should be fixed here #9657, can you test?

**Comment by rich20** [comment]
Fixed by this PR https://github.com/Kunena/Kunena-Forum/pull/9657
