### ISSUE TITLE
Calling the configuration results in an error - Layout default not found

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9661]
**Describe the bug**
Try to open the configuration

**Result**
<h2 id="caption">Call Stack</h2>

# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/src/MVC/View/HtmlView.php:425
2 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:204
3 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_kunena/src/View/Config/HtmlView.php:61
4 | Kunena\Forum\Administrator\View\Config\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
5 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_kunena/src/Controller/DisplayController.php:62
6 | Kunena\Forum\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
13 | require_once() | JROOT/administrator/index.php:32

**System information**
- Joomla version: ‎5.0.4-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.0-BET3-DEV
- Kunena template: Aurelia
- Php version: 8.2.16
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
When open the Kunena configuration i don't get any error

**Comment by rich20** [comment]
Do you have a new version from today? It works for me with the Beta3-DEV from three days ago.

**Comment by xillibit** [comment]
Yes i have the last changes

**Comment by rich20** [comment]
Please send me this version in the chat

**Comment by rich20** [comment]
Thank you. There must have been a mistake somewhere in my versions.
