### ISSUE TITLE
Stats: links to front-end do not work

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9665]
**Describe the bug**
Links in Forum Statistics to not resolve (throw 404 error:  View not found [name, type, prefix]: topic, html, Administrator)

**To Reproduce**
Go to Forum Stats,
click on link in:

- Most Popular Topics
- Most Active Posters
- Most Thanked Users

**Expected behavior**
link should redirect to topic / userprofile on front-end

**Actual result**
Throws 404 error:  View not found [name, type, prefix]: topic, html, Administrator

**System information (please complete the following information)**

Joomla version: 5.0.3
Kunena version: 6.3.0.RC1

**Additional context**
I have tried to use the Joomla site router to create a front-end link as well as use the KunenaRouter, but both are not able to build the correct SEF url for the front-end.
So there must be some function in Kunena that I do not know of (yet) or we just need to remove the links and replace them with text.

**Comment by xillibit** [comment]
When you are in the backend the KunenaRouter return nothing when you call the methods to generate a url

**Comment by Ruud68** [comment]
Did a deeper dive and this is complex: what makes this strange is that the non sef URL that is generated (with the administrator in the url doesn't work when omitting the administrator part.
I tried to refactor the router to have a site / administrator 'toggle' parameter (just like the Joomla router allows you to return a site SEF URl when called from the back-end but had to stop due to time constrains. I don't think this can ever be implemented without making changes that might break a lot of things.
So for the time being i did a PR that will remove these faulty links in the stats view and replaces them with plain text. At least now there is no error.
