### ISSUE TITLE
{K6.2 / K6.3] Plugin Modals buttons not working on Joomla 5.1

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9670]
**Describe the bug**
Joomla 5.1 has an (undocumented) B/C break when it comes to modals.
This results in the plugin modals (kunena backend) not working correct anymore: the buttons save, save & close and close do not work any more, further more there are also buttons displayed on top which work but have an unexpected side effect (e.g. when clicking close, you would expect the modal to close but it doesn't)

Reported this here: https://github.com/joomla/joomla-cms/issues/43289

I have a 'quick' workaround, but pending the result of how Joomla is going to fix this bug it is better to wait to get some clearity on their approach.

I will do a PR here for K6.2 and 6.3 once we have an approach

**Comment by xillibit** [comment]
I will make the stable release of K6.3 in a couple of days so it's useless to continue to maintain K6.2 now

**Comment by Ruud68** [comment]
ok, that will save some time. K6.3 should still support J4 and J5.0 correct?

**Comment by xillibit** [comment]
yes K6.3.x support both J!4.4.x and J!5.x

**Comment by Ruud68** [comment]
ok, pr is in: #9672
