### ISSUE TITLE
Collection: Could not parse https://update.kunena.org/6.3/list.xml

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Forum#9674]
**Describe the bug**
![image](https://github.com/Kunena/Kunena-Forum/assets/2733197/6696436c-308a-421c-8fc9-da3fdce242eb)

**To Reproduce**

**System information (please complete the following information)**

Joomla version: 5.1
Kunena version: 6.3
Php version: 8.2
Database version:

**Comment by xillibit** [comment]
Just fixed now
