### ISSUE TITLE
Attachments are not displayed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9680]
**Describe the bug**
Attachments are not displayed if they are not inserted in the message.

![Bildschirmfoto vom 2024-04-30 17-22-51](https://github.com/Kunena/Kunena-Forum/assets/888847/4db23456-2c37-492f-8b74-a09a92ac0a31)

**System information**
- Joomla version: ‎5.1.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.1-DEV
- Kunena template: Aurelia
- Php version: 8.2.18
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It's seems coming from my latest change of yesterday : https://github.com/Kunena/Kunena-Forum/commit/cbd6686160c2c9dec4786227c3855f6aec5d2c7f
