### ISSUE TITLE
A language string is missing in the site .com_kunena.ini

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9682]
**Describe the bug**
https://www.kunena.org/forum/42-Dutch/168422-missing-translation
Confirmed

COM_KUNENA_EDITOR_INSERT_PRIVATE = "Als Privat setzen"
This code must be added to site .com_kunena.ini line 55. It is missing in all language files except the English language.

**Comment by rich20** [comment]
More language strings are missing. These strings are also only available in English ini files.

src/site/language/en-GB/en-GB.com_kunena.templates.ini:498:COM_KUNENA_MYPROFILE_BSKY_APP_DESC = "This is your BlueSky account."
src/admin/language/en-GB/en-GB.com_kunena.libraries.ini:477:COM_KUNENA_MYPROFILE_BSKY_APP = "BlueSky social"
src/admin/language/en-GB/en-GB.com_kunena.libraries.ini:478:COM_KUNENA_MYPROFILE_BSKY_APP_DESC = "This is your BlueSky username."

**Comment by xillibit** [comment]
> COM_KUNENA_EDITOR_INSERT_PRIVATE = "Als Privat setzen"

I don't know why it's not in others language in transifex i have changed it to COM_KUNENA_EDITOR_INSERT_PRIVATE_ATTACHMENT for transifex to be able to see the change

I have updated the file en-GB.com_kunena.ini on transifex it shows 9 untranslated strings but i have changed only one

**Comment by xillibit** [comment]
> src/site/language/en-GB/en-GB.com_kunena.templates.ini:498:COM_KUNENA_MYPROFILE_BSKY_APP_DESC = "This is your BlueSky account."
> src/admin/language/en-GB/en-GB.com_kunena.libraries.ini:477:COM_KUNENA_MYPROFILE_BSKY_APP = "BlueSky social"
> src/admin/language/en-GB/en-GB.com_kunena.libraries.ini:478:COM_KUNENA_MYPROFILE_BSKY_APP_DESC = "This is your BlueSky username."

Updated too on github and transifex

**Comment by rich20** [comment]
Thank you! Now everything is on Transifex.
But there are now several untranslated strings in all three files.
I have noticed another error: In both "DESC" files we have two different texts. 

src/admin/language/en-GB/en-GB.com_kunena.libraries.ini:488:COM_KUNENA_MYPROFILE_X_SOCIAL_DESC = "T**his is your X (previously Twitter) username**."
src/site/language/en-GB/en-GB.com_kunena.templates.ini:480:COM_KUNENA_MYPROFILE_X_SOCIAL_DESC = "**This is your X username**."

**Comment by xillibit** [comment]
Updated on both github and transifex
