### ISSUE TITLE
Set attachment as private cannot be disabled

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9683]
**Describe the bug**
https://www.kunena.org/forum/76-Official-Announcements-and-News-about-Kunena/168408-kunena-6-3-0-stable-release-for-joomla-4-4-5-0#231253

You can disable private messages, but not private attachments. This should also be possible.

**Comment by rich20** [comment]
1. This fix only removes the "Set all attachments as private" button, but not the "Set as Private" button.
<strike>2. Where does this code COM_KUNENA_EDITOR_INSERT_PRIVATE come from (see image)?
Only this code is present in php as well ini files. COM_KUNENA_EDITOR_INSERT_PRIVATE_**ATTACHMENT**</strike>
.
![Bildschirmfoto vom 2024-05-06 12-18-22](https://github.com/Kunena/Kunena-Forum/assets/888847/7e9662b1-437e-4927-b68d-c7a24f2cfe22)

**Comment by xillibit** [comment]
I had renammned the COM_KUNENA_EDITOR_INSERT_PRIVATE by COM_KUNENA_EDITOR_INSERT_PRIVATE_ATTACHMENT, i can't find in files the COM_KUNENA_EDITOR_INSERT_PRIVATE anymore

it seems that you haven't all the lastest changes

**Comment by rich20** [comment]
> it seems that you haven't all the lastest changes

No, I'm up to date. My ini file show this code: COM_KUNENA_EDITOR_INSERT_PRIVATE_ATTACHMENT
I also can't find in files the COM_KUNENA_EDITOR_INSERT_PRIVATE. No idea where this code on the button comes from. 
.
![Bildschirmfoto vom 2024-05-06 12-18-22](https://github.com/Kunena/Kunena-Forum/assets/888847/7e9662b1-437e-4927-b68d-c7a24f2cfe22)

**Comment by rich20** [comment]
Found it:
`kunena_media/core/js/upload.main.js:276:        .html(Joomla.getOptions('com_kunena.icons.secure') + ' ' + Joomla.Text._('COM_KUNENA_EDITOR_INSERT_PRIVATE'))`

**Comment by rich20** [comment]
Sorry, my mistake, the folder media i forgot to update

**Comment by rich20** [comment]
Sorry, my mistake, the folder media i forgot to update, can be closed
