### ISSUE TITLE
Rendering Error in the history if the topic is not approved

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9687]
**Describe the bug**
https://www.kunena.org/forum/k-6-3-0-support/168431-forum-statistics-bug-return-value-must-be-of-type-array,-none-returned#231321
Confirmed

**To Reproduce**

1. enable in the configuration - Frontend tab the history (it is default setting)
2. define a category for review
3. create as registered user a new topic
4. go to this unapproved topic as administrator or moderator
5. click on Edit
6. scroll down to the history

**Actual result**
Warning: Undefined variable $messages in .../components/com_kunena/src/Controller/Topic/Form/History/TopicFormHistoryDisplay.php on line 92

Rendering Error in layout Topic/Edit: array_keys(): Argument #1 ($array) must be of type array, null given in /...components/com_kunena/src/Controller/Topic/Form/History/TopicFormHistoryDisplay.php on line 92
Layout was rendered in .../components/com_kunena/template/aurelia/pages/topic/edit/default.php on line 44

**System information**
- Joomla version: ‎4.4.5-dev and 5.1.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.1-DEV
- Kunena template: Aurelia
- Php version: 8.2.18
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Ruud68** [comment]
@rich20 can you give https://github.com/Kunena/Kunena-Forum/pull/9688 a try?

**Comment by rich20** [comment]
Completed
