### ISSUE TITLE
Maybe one double quote too much?

### ISSUE THREAD

**Issue by Gindi50** [Kunena/Kunena-Forum#9691]
**Describe the bug**
In the file /libraries/kunena/src/Factory/KunenaFactory.php there is possibly one double quote too much in row 269?
$contents = str_replace('_QQ_', '"\""', $contents);

This may be related to /libraries/vendor/joomla/languages/src/Parser/IniParser.php in rows 57-68
 // Check for any incorrect uses of _QQ_.
            if (strpos($line, '_QQ_') !== false) {
                $errors[] = 'The deprecated constant `_QQ_` is in use on line ' . $realNumber;

                continue;
            }

            // Check for odd number of double quotes.
            if (substr_count($line, '"') % 2 != 0) {
                $errors[] = 'There are an odd number of quotes on line ' . $realNumber;

                continue;

**To Reproduce**
1. Go to '/libraries/kunena/src/Factory/KunenaFactory.php...'
3. Scroll down to 'Line 269....'
4. See error in $contents = str_replace('_QQ_', '"\""', $contents);

**Expected behavior**

**Actual result**
A clear and concise description of what you see. Like an error message.

**Screenshots**

**System information (please complete the following information)**

Joomla version: 5.1.1
Kunena version: 6.3.1
Php version: 8.3.7
Database version: 10.6.15-MariaDB

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OpenSUSE Leap 15.3
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 115.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gindi50** [comment]
The backslash is not visible in this report

**Comment by xillibit** [comment]
This is not an issue the backslash is here to be have the quotes

**Comment by Gindi50** [comment]
What about the three quotes, is that ok or is one quote too much?
I only wrote the backslash because it is not displayed here in the text between the quotes.
