### ISSUE TITLE
Conversion from Twitter to X in the Kunena Forum

### ISSUE THREAD

**Issue by Gindi50** [Kunena/Kunena-Forum#9692]
**Is your feature request related to a problem? Please describe.**

I would like to help you with the changeover from Twitter to X in Kunena and have listed all the files that contain the term "Twitter".
The numbers behind the files are the line numbers. For the css files, which are single-line, it is the bit number. 
Unfortunately, I'm not sure where "Twitter" is replaced by "X" or "X-SOCIAL", otherwise I would have already done some preliminary work.
The list of files:
/administrator/components/com_kunena/install/sql/updates/php/5.2.15-2021-07-24_update_configuration.php :683-689
/administrator/components/com_kunena/media/css/theme_min.css :1164 :1276 :2376 :2380 :4218 :4410 :4546 :
/administrator/components/com_kunena/src/Controller/TemplateController.php :259 :260 :423 :424 
/administrator/components/com_kunena/src/Model/ConfigModel.php :1087 :1093 
/administrator/components/com_kunena/src/Model/ToolsModel.php :702 
/administrator/components/com_kunena/tmpl/config/default.php :1554 :1559 :1563 :1568

/components/com_kunena/src/Controller/Category/Index/CategoryIndexDisplay.php :440-443 
/components/com_kunena/src/Controller/Category/Topics/CategoryTopicsDisplay.php :252-255
/components/com_kunena/src/Controller/Topic/Item/TopicItemDisplay.php :598-561 
/components/com_kunena/src/Controller/Topic/Listing/Recent/TopicListingRecentDisplay.php :331 :375-378
/components/com_kunena/src/Controller/Topic/Listing/User/TopicListingUserDisplay.php :353-356
/components/com_kunena/src/Controllers/TopicController.php :1128 :1130 
/components/com_kunena/src/Layout/Topic/Edit/TopicEditEditor.php :60 
/components/com_kunena/template/aurelia/assets/js/sceditor.js :316 :317 :364 :371 :393 :396 :398 :699 :703 
/components/com_kunena/template/aurelia/assets/js/topic.js :91 
/components/com_kunena/template/aurelia/assets/scss/aurelia.css :24 
/components/com_kunena/template/aurelia/assets/scss/editor.css :115 
/components/com_kunena/template/aurelia/assets/scss/profile.css :44 :45 
/components/com_kunena/template/aurelia/assets/scss/twitter.css :1 :2 :7 :132 :143 :160 :175 :310 :316 :321 :511 :609 :852 :858 :1005 : 1072 
/components/com_kunena/template/aurelia/config/config.xml :285 
/components/com_kunena/template/aurelia/layouts/bbcode/twitter/default.php :25 :27 :30 :32 :38 :65 :77 :78 :84 :85 :96 :103 :110 
/components/com_kunena/template/battavia/assets/scss/aurelia.scss :24 
/components/com_kunena/template/system/layouts/bbcode/twitter/default.php :26 :28 :31 :33 :39 :66 :78 :79 :85 :86 :97 :104 :111 

/libraries/kunena/src/BBCode/KunenaBBCode.php :324 :2778 :2790 :2810 :2837 :2848 :2849 :2863 :2895 :2941 :2947 
/libraries/kunena/src/Config/KunenaConfig.php :210 :211 :1322 : 1328 
/libraries/kunena/src/Tables/KunenaUsers.php :262 :267 
/libraries/kunena/src/User/KunenaUser.php :2208 
/libraries/src/Environment/Browser.php :237 

/media/kunena/cache/aurelia/css/kunena.css :22839 :27030 :27087 :34939 :34965 :35028 :38730 :39085 :39118 :39549 :39772 :41975 :42033 :42104 :42184 :45775 :47443 :51637 :51781 :55918 :57020 from 58629b
/media/kunena/core/css/jssocials-theme-classic-min.css :17 :108 of 3595b
/media/kunena/core/css/jssocials-theme-classic.css :1 :6 
/media/kunena/core/css/jssocials-theme-flat-min.css :17 :83 of 3322b 
/media/kunena/core/css/jssocials-theme-flat.css :1 :5 
/media/kunena/core/css/jssocials-theme-minima-min.css :17 :78 :162 :215 :268 :336 :412 :488 from 8960b
/media/kunena/core/css/jssocials-theme-minima.css :1 :5 :9 :13 
/media/kunena/core/js/ckeditor_config.js :58 
/media/kunena/core/js/custom_ckeditor_config.js :53 
/media/kunena/core/js/custom_ckeditor_config.js :51 
/media/kunena/core/js/fancybox-min.js :63672 :64057 of 68253b
/media/kunena/core/js/jssocials.js :442 :444 
/media/kunena/core/js/plugins/twitter/plugin.js :10 :13 :19 :21

**Comment by Ruud68** [comment]
jssocials (https://github.com/tabalinas/jssocials) is an external script that as far as I know is not maintained anymore for a long time (appr. 6 years ago the last commit was done), so there should also be a decision on what to do with this script: fork or replace?

**Comment by xillibit** [comment]
> jssocials (https://github.com/tabalinas/jssocials) is an external script that as far as I know is not maintained anymore for a long time (appr. 6 years ago the last commit was done), so there should also be a decision on what to do with this script: fork or replace?

I don't know if there is a replacement for it which it's still maintained

Just made some changes : https://github.com/Kunena/Kunena-Forum/commit/9bb288c79f212d7745ee509b5380b4fc02331150

**Comment by Ruud68** [comment]
I have a fork that I use for my plugin ochJSsocials. I use that on my sites with Kunena via the custom tag {jssocials}  which is then replaced by the social buttons that are configured. Last feature I did on my forked repo was adding threads as platform. For me this is a dead-end as I am refactoring ochJSsocials into s solution that will not need a script and runs purely on html and css.
So my fork will also be abandoned sooner rather then later.

Maybe ask the community on the forum what their take on this is, if they use it and if they have an idea for another solution?

**Comment by xillibit** [comment]
I have created a poll yesterday for that : https://www.kunena.org/forum/77-General-Talk-about-Kunena/168466-future-of-social-icons-on-kunena

To render tweets part in Kunena it's based on v1 on twitter API, now they have moved on v2 but it's 100$/month to use it, just for the basic offer. I don't know if there are still users using it.
This could need another poll, for a replacement there a free API for BlueSky : https://docs.bsky.app/ and/or threads : https://developers.facebook.com/docs/threads/ (when it will compliant to DMA/DSA)

**Comment by Ruud68** [comment]
Saw the poll (filled in and shared (not using the share buttons :)) on facebook in the Joomla group.
The tweet rendering part is definitely something that needs a separate poll.
I had one blog site where I used it to capture reponses to tweets and then display them as comment (kunena discuss) on the blog: a lot of work (manually adding these replies / comments) but looked great.
Due the amount of work and the limited 'turn-over' I stopped doing that.
Interested in what other peoples use case are for this feature.

**Comment by xillibit** [comment]
I will remove the social feature in K6.4 and will do an another poll for X (twitter)

**Comment by xillibit** [comment]
I just created a another poll : https://www.kunena.org/forum/77-General-Talk-about-Kunena/168470-future-of-tweet-integration-in-kunena-messages

For this issue, if we remove twitter integration there won't be variables with twitter in the Kunena code anymore

**Comment by Gindi50** [comment]
There is a table "twitter" in the _kunena_users database, which should also be changed to "x".

**Comment by xillibit** [comment]
> There is a table "twitter" in the _kunena_users database, which should also be changed to "x".

That's is already changed on update, the column is renammed during update to K6.3.0
