### ISSUE TITLE
Not possible to move categories to other sections

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9693]
**Describe the bug**
https://www.kunena.org/forum/k-6-3-0-support/168462-categories
Confirmed

**To Reproduce**
Try to move a category to another section

**Result**
Categories can only be moved within a section

**System information**
- Joomla version: ‎5.1.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.2-DEV
- Kunena template: Aurelia
- Php version: 8.2.18
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
So the issue it's by drag&drop, @Ruud68 do-you have an idea on this ?

**Comment by Ruud68** [comment]
Good morning, we use the Joomla functionality / script here as it is used in eg com_content categries.
I think it is only possible to order within the category: that is what we have now.
Need to check if this is possible with Joomla articles: so create multi leven categories and not only sort them within its parent, but also move them to another parent.

**Comment by Ruud68** [comment]
Okay so just tested this is com_content / categories.
Same 'issue' here, you can only reorder categories within a category.

When you want to move a category then you actually move it: open the category and select a different parent.

There is probably a reason why Joomla does it this way. For me this is acceptable but that is that I am fine with the difference between moving a category and reordering a category (which in the interface might look the same, but in code is a completely different thing).

**Comment by rich20** [comment]
I have now tested it with Joomla 3.10 and see that it is also not possible to move categories across sections. So iI think, the ticket can closed here again.
