### ISSUE TITLE
Unable to edit css or scss in Joomla 4.4.5

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9695]
**Describe the bug**
Call to undefined method Joomla\Filesystem\File::getExt() 
[https://www.kunena.org/forum/k-6-3-0-support/168471-can-t-edit-css-scss#231479](url)

**To Reproduce**
Go to Kunena templates
Select template
Select either edit css or edit scss
Select file to edit

**Expected behavior**
Editor screen opening

**Actual result**
Error message: Call to undefined method Joomla\Filesystem\File::getExt() 

**Screenshots**

**System information (please complete the following information)**

Joomla version: 4.4.5
Kunena version: 6.3.1
Php version: 8.2.12 
Database version: 10.4.32-MariaDB 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 126.0.1 (64-bits)

**Additional context**

**Comment by rich20** [comment]
# if you want Edit SCSS

Call stack
# 	Function 	Location
1 	() 	JROOT/administrator/components/com_kunena/src/Controller/TemplateController.php:621
2 	Kunena\Forum\Administrator\Controller\TemplateController->editscss() 	JROOT/libraries/src/MVC/Controller/BaseController.php:693
3 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
4 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361
5 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:143
6 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:186
7 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:293
8 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:61
9 	require_once() 	JROOT/administrator/index.php:32 

# if you want Edit CSS

Call stack
# 	Function 	Location
1 	() 	JROOT/administrator/components/com_kunena/src/Controller/TemplateController.php:667
2 	Kunena\Forum\Administrator\Controller\TemplateController->editCss() 	JROOT/libraries/src/MVC/Controller/BaseController.php:693
3 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
4 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361
5 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:143
6 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:186
7 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:293
8 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:61
9 	require_once() 	JROOT/administrator/index.php:32

**Comment by xillibit** [comment]
Fixed in https://github.com/Kunena/Kunena-Forum/commit/3d1914949292ca7615e1530425b1f95e6fabdb98
