### ISSUE TITLE
@username inserts an example.com mail address into the post

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9696]
**Describe the bug**
https://www.kunena.org/forum/36-German/168490-nach-zeichen-im-beitrag-auswahl-von-threadbeteiligte-erstellt-mailadresse#231611
Confirmed

**To Reproduce**

1. Reply in a topic
2. Enter an @ followed by a letter
3. Select a name from the list (see image)
4. Submit the message

![Bildschirmfoto vom 2024-06-19 12-39-56](https://github.com/Kunena/Kunena-Forum/assets/888847/295d05bf-e131-48f7-8c07-0edcba16c748)

**Actual result**
It adds an example.com e-mail address
![Bildschirmfoto vom 2024-06-19 12-45-54](https://github.com/Kunena/Kunena-Forum/assets/888847/0275b8d8-1962-4fa2-8e53-bd42cc3e0a57)

**System information**
- Joomla version: ‎5.1.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.2
- Kunena template: Aurelia
- Php version: 8.2.18
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Gindi50** [comment]
I have installed fix 8ea4035 in my Kunena 6.3.3-DEV installation and now when I enter @(letter) in a reply post and click on a displayed name, it does not display @herbert but [mention userid=43]herbert[/mention].
gindi

**Comment by Gindi50** [comment]
In my installation, I changed the entry '[mention userid={userid}]{username}[/mention]' in edit.js to '<a href=">@{username}</a>: ' and added a ":" and a space after the user name.
Now @herbert: is displayed for me.
gindi
