### ISSUE TITLE
Protected Attachments shows only for Admins and Moderators

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9697]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/168491-images-not-shown-in-posts
Confirmed

**To Reproduce**

1. set protect attachments to Yes
2. write an answer in a topic
3. upload an attachment (do **not** insert it into the post) 
4. submit
5. go as Registered or Guest to this post

**Actual result**
No attachment is visible

**System information**
- Joomla version: ‎5.1.2-dev and 4.4.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.3-DEV
- Kunena template: Aurelia
- Php version: 8.2.18
- Database version: 10.5.23-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
Furthermore when Enable private message is set to NO, attachments that aren't inserted in the message aren't even showing for admins and moderators.

**Comment by xillibit** [comment]
I have made a fix for it, can-you check if it's ok now ?

**Comment by rich20** [comment]
Now also registered users can see the attachments but no guests, even it is set: Show Attachments for Guests and Show Images for Guests is yes.
Guests see: This message has an attachment file.
Please log in or register to see it.

- [x] Admins, mods and registered users can see attachments
- [ ] Guests cannot see attachments

**Comment by Pinkeltje** [comment]
Can confirm. And when setting Show Attachments for Guests and Show Images for Guests to **No**, then no message is shown.
Furthermore when inserting an image in the post, for registered users the image is shown but the thumbnail as well with a wrong layout (independent from setting show image for quest)

![2024-08-15 Screenshot 533](https://github.com/user-attachments/assets/24f84501-2192-4d1c-9f46-7abf7d66d6ae)

**Comment by xillibit** [comment]
Just committed a new change to fix that

**Comment by rich20** [comment]
- [x] Success


**Additional context**
What I noticed:
When setting Show Images for Guests and  Show Attachments for Guests = No
If you upload pictures or other attachments, but these are not inserted into the message, there is no hint for guests that they are not allowed to see the attachments.
Has this always been the case?

**Comment by Pinkeltje** [comment]
When setting Show Images for Guests and Show Attachments for Guests = No = **no notice** as I stated before. Really don't remember if this has always been the case, I know it worked and works well with inserted images.

**Inserted image for guests with settings = NO**
![2024-08-16 Screenshot 535](https://github.com/user-attachments/assets/c9820282-b22a-4fe1-8818-935b49e6b05a)

**Inserted image for registered: notice the fact that thumb is shown as well and with a weird layout**
![2024-08-16 Screenshot 536](https://github.com/user-attachments/assets/86d381bb-366f-4970-8df9-15650a1c871c)

**Uploaded image for guests: no notice**
![2024-08-16 Screenshot 539](https://github.com/user-attachments/assets/1e2f251c-7a72-4480-9a60-54c1d946f3db)

**Uploaded image for registered: notice the fact that thumb is in correct layout.**
![2024-08-16 Screenshot 537](https://github.com/user-attachments/assets/72a84b27-fd37-48b3-a356-a8a885430e77)

Just my findings. I am already very happy with the work you did and can live with it. The most important issues have been solved.

**Comment by Pinkeltje** [comment]
**Another finding:**
![2024-08-16 Screenshot 540](https://github.com/user-attachments/assets/571ee485-4e96-4192-bd3e-436f257e9582)
With multiple images, the text is displayed twice. So the constants COM_KUNENA_SHOWIMGFORGUEST_HIDEIMG_MULTIPLES and COM_KUNENA_SHOWIMGFORGUEST_HIDEIMG_SIMPLE are not used. 

When inspecting with language debug it shows constant COM_KUNENA_SHOWIMGFORGUEST_HIDEIMG.
![2024-08-17 Screenshot 541](https://github.com/user-attachments/assets/60043958-6034-40ef-820b-5e448108f91a)

This constant is found in KunenaAttachment.php and KunenaBBCode.php. 

No big problem either, but I think there is a conflict somewhere.
