### ISSUE TITLE
Remove X button from CKEditor toolbar no longer works

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9698]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/168492-remove-x-button-from-ckeditor-toolbar
Confirmed

**To Reproduce**
Select in the Aurelia configuration (tab BBcode) Show X symbol = No

**Actual result**
The symbol is still displayed in the editor

**Additional context**
It is possible that it no longer works due to the switch from Twitter to X.

**Comment by Gindi50** [comment]
I am somewhat puzzled by this error message.
In my installations, Ebay symbol in the editor, X symbol in the editor, Instagram symbol in the editor and Soundcloud symbol in the editor are listed in /Aurelia/BBCode, but in the frontend in the editor menu bar only "Tweet", (invisible without button) "Ebay", "soundcloud" and "instagram" are displayed in this group. I can also switch these visible buttons on and off in /Aurelia/BBCode.
An "X" or "Twitter" button is not available, so "X symbol in editor" has no function.
I also could not find this button in /libraries/kunena/src/BBCode/KunenaBBCode.php, /aurelia_editor.xml and editor.xml. "Tweet", "Ebay", "soundcloud" and "instagram" are mentioned there and have functions there.

**Comment by Pinkeltje** [comment]
Don't know if it helps, but in 6.3.1 at least hiding the button worked.  Showing button no image displayed.
![2024-06-28 Screenshot 475](https://github.com/Kunena/Kunena-Forum/assets/8941310/8fe0a1f6-f984-478f-9aa2-d51921936337)
![2024-06-28 Screenshot 476](https://github.com/Kunena/Kunena-Forum/assets/8941310/f502472a-123d-424f-9ca3-2ef0e072d677)

More findings;
When renaming \core\js\plugins\twitter\icons\**x_logo.png** to **twitter.png** and changing line 11 in plugin.js to `CKEDITOR.plugins.add( 'twitter', {
	icons: 'twitter',` x logo is shown.

In 6.3.3. dev when putiing back \core\js\plugins\twitter from 6.3.1 and deleting \core\js\plugins\x
and changing params.ini Line 57 back to Twitter="0"
and line 65 back to editorButtons="Smiley,Ebay,Twitter,Instagram,Soundcloud"
It works in 6.3.3. dev as well.

**Comment by Gindi50** [comment]
@pinkeltje: Unfortunately the suggestion doesn't work for me. I have two versions of the files in /core/js/plugins/, twitter/icons/twitter.png and x_social/icons/x_logo.png.
The two plugin.js are adapted accordingly. I have set the params.ini according to the settings from K6.2.4 (everything still worked there).
For testing I changed the group and the user for twitter and x_social with Chown but the X button was still displayed in the menu bar. 
In the text field I clicked right mouse button - Show page source and a file with the header "<!DOCTYPE html>" was displayed. 
From row 1519 the following was displayed:
 ```
<td width="40%"
                                                                    class="paramlist_key"><label id="jform_X_Social-lbl" for="jform_X_Social">
    Show <strong>X</strong> button</label>
</td>
                                                                <td class="paramlist_value"><select id="jform_X_Social" name="jform[X_Social]" class="form-select" aria-describedby="jform_X_Social-desc">
	<option value="0" selected="selected">No</option>
	<option value="1">Yes</option>
</select>
</td>
                                                                <td class="paramlist_key">Show <strong>X</strong> button on editor</td>
                                                            </tr>

```
The settings for ebay are above and instagram and soundcloud are below. The difference is that x_social has the text "Show <strong>x<strong> button</label>" and "<td class="paramlist_key">Show <strong>x</strong> button on editor</td>". 
It is possible that the "Show" prevents the button from being activated and deactivated.
