### ISSUE TITLE
No description showing for template configuration

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9703]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/168498-change-entry-in-aurelia-bbcode#231689

**To Reproduce**
1. Go to Kunena - Templates - Aurelia
2. Select Aurelia
3. Open any tab
4. Only field name and setting is displayed. No description.

**Expected behavior**
Show description

Joomla version: 5.1.1
Kunena version: 6.3.2 and earlier
Php version: 8.2

Can be solved by changing "administrator\components\com_kunena\tmpl\template\edit.php" from line 126 to
`  <?php if ($field->hidden) :
                                                                ?>
                                                            <tr style="display: none">
                                                                <td class="paramlist_key"><?php echo $field->label; ?></td>
                                                                <td class="paramlist_value"><?php echo $field->input; ?></td>
                                                                <td class="paramlist_key"><?php echo $field->description; ?></td>
                                                            </tr>
                                                            <?php else :
                                                                ?>
                                                            <tr>
                                                                <td width="40%"
                                                                    class="paramlist_key"><?php echo $field->label; ?></td>
                                                                <td class="paramlist_value"><?php echo $field->input; ?></td>
                                                                 <td class="paramlist_key"><?php echo Text::_($field->description); ?></td>
                                                            </tr>
                                                            <?php endif; ?>`

![2024-07-03 Screenshot 484](https://github.com/Kunena/Kunena-Forum/assets/8941310/565fdb2d-7acc-4130-b71f-1931dfe780cf)

**Comment by Gindi50** [comment]
I have tested it and it works perfectly

**Comment by Gindi50** [comment]
I have solved it in a simpler way and used row 131
 <td class="paramlist_key"><?php echo $field->description; ?></td>
and then in row 139 
<td class="paramlist_key"><?php echo Text::_($field->description); ?></td>
inserted.
