### ISSUE TITLE
Dashboard data incorrerct

### ISSUE THREAD

**Issue by N6REJ** [Kunena/Kunena-Forum#9706]
**Describe the bug**
Values displayed in dashboard are incorrect on "trash" and "tools"

**To Reproduce**
1.click on dashboard

**Expected behavior**
displayed values are correct.

**Actual result**
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/a081258e-2b17-4eeb-8422-2ad446748abe)
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/b08223af-17eb-490f-b039-ac2bd00d82e9)
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/ec5a00fe-49b7-4761-81a1-4b7d6e1dd75e)
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/c195186a-f150-48da-ab7d-8cfcbb30eb60)

**Screenshots**

**System information (please complete the following information)**

Joomla version:  5.1.1
Kunena version: 6.3.2

**Additional context**
This is on a fresh kunena install

**Comment by rich20** [comment]
It's a known issue https://github.com/Kunena/Kunena-Forum/issues/8556
