### ISSUE TITLE
Kunena menu doesn't exist and can't be restored/replaced

### ISSUE THREAD

**Issue by N6REJ** [Kunena/Kunena-Forum#9707]
**Describe the bug**
There is no kunena menu

**To Reproduce**
1. install new kunena
2. do not install kunena "menu"
3. use "rebuild menu" option from kunena tools

**Expected behavior**
default kunena menu will show

**Actual result**
menu is not restored and "login" is moved to left.
After deleting all kunena extensions and reinstalling ( no other changes made ) the profile is back on the right but still no menu

**Screenshots**
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/36ec4bf9-749e-400b-bc82-4e42470a2b4e)
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/304c4608-b5da-4005-a5e2-61ac9df09cee)+
![image](https://github.com/Kunena/Kunena-Forum/assets/1850089/9e86572c-614b-45b7-aa63-b2ba38f58e61)

**System information (please complete the following information)**

Joomla version:  5.1.1
Kunena version: 6.3.2
Php version: 8.1.39

COMMENT:
Since I've no idea what the menu should be I can't rebuild it manually either.

**Comment by rich20** [comment]
Please ask your questions in the forum. Github is for development and not for support. https://www.kunena.org/forum/recent

**Comment by rich20** [comment]
Solved by this topic; https://www.kunena.org/forum/installation-issues/168506-menu-missing
