### ISSUE TITLE
Backend -> Edit Kunena Users: Not all options are available

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9714]
**To Reproduce**
Go to Backend -> Kunena -> Users -> Edit a user -> Forum Settings

**Actual result**
2 options (see image) cannot be changed as the selection options are missing..

**Screenshots**
![nhju7](https://github.com/Kunena/Kunena-Forum/assets/888847/385cf0c2-66ba-46af-8654-bd824c8f1810)

**System information**
- Joomla version: ‎5.1.2-dev and 4.4.6-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.3-DEV
- Kunena template: Aurelia
- Php version: 8.2.20
- Database version: 10.5.25-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
In earlier versions also. Most of them can be solved by replacing
`'class="kinputbox form-control" size="1"',`
to
`'class="form-select" size="1"',`
In View/User/HtmlView.php

Can't find field Rank Title:

**Comment by Gindi50** [comment]
The solution for rank titles is in file /administrator/components/com_kunena/src/Model/UserModel.php , 
in row 234 you have to change the line: return HTMLHelper::_('select.genericlist', $yesnoRank, 'newRank', 'class="inputbox form-control" size="5"', 'value', 'text', $user->rank); 
change to
 return HTMLHelper::_('select.genericlist', $yesnoRank, 'newRank', 'class="inputbox form-control" size="1"', 'value', 'text', $user->rank);
size ="5" must be changed to size="1".

gindi

**Comment by Pinkeltje** [comment]
Nice! But I think you have to change the class as well.
