### ISSUE TITLE
ICQ was closed on 26 June 2024

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9715]
Should we keep this profile information for a while until K6.4, or can it be removed?

**Comment by xillibit** [comment]
So you mean to remove it too in K6.3 ?

**Comment by rich20** [comment]
The servers have also been closed. On the ICQ page there is only a note that the service stopped working and that you should switch to VK Messenger. 
We could therefore also remove ICQ from Kunena 6.3.
