### ISSUE TITLE
Switching to SCeditor and back to CKeditor removes the smiley button

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9717]
**Describe the bug**
https://www.kunena.org/forum/k-6-3-0-support/168515-ckeditor-the-emoticon-icon-disappears#231812
Confirmed

**To Reproduce**

1. go to Aurelia (tab BBcode) 
2. select the SCeditor and save
3. open again the tab BBcode
4. switch back to the CKeditor and save
5. click on Reply or New topic in the frontend

**Actual result**
No smiley symbol in the editor

**Additional context**
The icon can only be restored by clicking on Restore in the Aurelia settings

**System information**
- Joomla version: ‎5.1.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.3-DEV
- Kunena template: Aurelia
- Php version: 8.2.20
- Database version: 10.5.25-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
Joomla 5.1.2
Kunena 6.3.3

**Restored to default**
![2024-07-16 Screenshot 499](https://github.com/user-attachments/assets/25bbfb69-e9e0-46e9-8f7b-0450c6426229)

**Changed settings**
![2024-07-16 Screenshot 500](https://github.com/user-attachments/assets/ae655d3b-62ba-4f3b-a16c-37ccbb1bb746)

**Smileys gone, x button still visible. See also #9698** 
![2024-07-16 Screenshot 501](https://github.com/user-attachments/assets/016774f2-c201-425c-a378-f96622a2cd74)

**FYI:** This problem doesn't exist in Kunena 6.3.1. Only problem there is that when x logo is enabled it doesn't show the icon. But button can be disabled.
Tried to find differences, but no luck.

**Comment by Leen29** [comment]
problem is also in kunena 6.3.3

**Comment by rich20** [comment]
> problem is also in kunena 6.3.3

K 6.3.3 had already been released when I wrote this ticket

**Comment by Leen29** [comment]
the difference 631 is smiley line filed 260 > 263 is not there in new version 633 config.xml
if I add that extra the emoticons seem to stay after changing
only just like the X it is then no longer possible to turn it off
![namesmilynotthere](https://github.com/user-attachments/assets/570e69dc-e59e-4d59-bad6-58573764b98e)

**Comment by Pinkeltje** [comment]
I think it is caused by this #9689 
There are 2 different field names: emoticons and smileys. As far as I can see emoticons is used by SCEditor and smileys by CKEditor.
See also administrator\components\com_kunena\src\Controller\TemplateController.php lines 251 and 347
