### ISSUE TITLE
CKEditor language files are not loading anymore

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9720]
**Describe the bug**
CK editor is not loading language files anymore

**Expected behavior**
Button text should be translated and when hovering over editor icons tooltips should be translated 
![2024-07-20 Screenshot 511](https://github.com/user-attachments/assets/7c1d3dd7-feed-4bf8-a153-3f4ba5d43ab2)

**Actual result**

![2024-07-20 Screenshot 510](https://github.com/user-attachments/assets/09d08c85-ece0-4e08-9122-7e9934f8a118)

Buttons and tooltips stay English

**Screenshots**

**System information (please complete the following information)**

Joomla version: 5.1.2
Kunena version: 6.3.3
Php version: 8.2
Database version:

**Additional context**
I think this is caused by changes in components\com_kunena\template\aurelia\layouts\widget\editor\ckeditor.php line 31
**In Kunena 6.3.1** 
`$joomlaLanguage = Factory::getApplication()->getLanguage()->getTag();`
**In Kunena 6.3.3 but think it was already changed in 6.3.2**
$joomlaLanguage = Factory::getApplication()->getLanguage()->getDefault();

If I change line 31 back to how it was in Kunena 6.3.1 tooltips are translated again

**Comment by rich20** [comment]
You are right, since this change it only works individually for each user. This means that the language that the user has selected in their profile is displayed, but it no longer works with the default selection if this is not English.

**Comment by Pinkeltje** [comment]
It is strange. Here are as far as I can see the latest changes; [](url)https://github.com/Kunena/Kunena-Forum/commit/550db48c4895de3c57f210f6aef5ffa98be74efa
And just my 5 cents: I can't find language active in any of the user params as stated here: [](url)https://www.kunena.org/forum/k6-2-0-support-archive/168344-no-editor-showing?start=20#231512
Even when allowing user to change frontend language. 
In my opinion default active, just means to use default active site language unless changed. 
Will do some more tests with multilanguage site though.
And FYI: file components/com_users/forms/sitelang.xml already existed in J 4.4.0!

**Comment by xillibit** [comment]
Can-you test please with my commit : https://github.com/Kunena/Kunena-Forum/commit/34384667868625683ad47873986b7587add5b5ce ?

**Comment by rich20** [comment]
- [x] Success

**Comment by Pinkeltje** [comment]
Tested succesfully.
