### ISSUE TITLE
A thumbnail is displayed even though an image has been inserted into the post.

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9722]
**Describe the bug**
https://www.kunena.org/forum/36-German/168536-kunena-6-3-4-platzhalter-thumbnails-in-beitr%C3%A4gen-eingef%C3%BCgten-bildern#231957
Confirmed

**To Reproduce**Insert a picture into a message and you will see it

**Expected behavior**
No thumbnail

**Actual result**
The thumbnail is displayed

**Additional context**
This problem exists since K 6.3.4
https://github.com/Kunena/Kunena-Forum/issues/9697#issuecomment-2293060993

**System information**
- Joomla version: ‎5.1.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.4
- Kunena template: Aurelia
- Php version: 8.2.20
- Database version: 10.5.25-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
Furthermore the displayed attachments (thumbnails) have the wrong layout.

**Comment by Pinkeltje** [comment]
Better, but now buttons are pushed to the right.
![2024-09-11 Screenshot 579](https://github.com/user-attachments/assets/2c6d45ac-74da-454d-8cfa-62a15d592871)

Or even disappear behing Last edit bar when message has been edited.

![2024-09-11 Screenshot 580](https://github.com/user-attachments/assets/df20cc97-3ba6-4cad-bbb5-460498982480)

**Comment by Pinkeltje** [comment]
For what it is worth: A thumbnail has always been displayed in this case. Screenshot from Joomla 3 with Kunena 5.2.14 and Crypsis.
![2024-09-12 Screenshot 582](https://github.com/user-attachments/assets/448d829c-4b07-4497-b0e7-c47de376a577)

**Comment by Pinkeltje** [comment]
Don't think this is an improvement.
I goes wrong when inline attachment is removed from message. Furthermore layout is little bit off as it still shows `<div class="card pb-3 pd-3 mb-3">`

**Uploaded 2 attachments**
![2024-09-21 Screenshot 612](https://github.com/user-attachments/assets/41a4a115-1e32-4498-9c91-0d84e70dd910)
**Inserted attachments in message**
![2024-09-21 Screenshot 610](https://github.com/user-attachments/assets/e3111155-460a-4c92-8bd0-a1fba506a0f3)
**Result: both attachments shown in message**
![2024-09-21 Screenshot 609](https://github.com/user-attachments/assets/b8ae899c-15f0-4835-be60-f2d5982cd658)
**Removed inline attachment from message**
![2024-09-21 Screenshot 611](https://github.com/user-attachments/assets/077b4cf7-e520-4a7e-8cc8-5a765ca175a7)
**Result when removed from message**
![2024-09-21 Screenshot 608](https://github.com/user-attachments/assets/e3e36b28-5e76-42b2-a4ea-4d7dad45bc79)

**Comment by xillibit** [comment]
yes it remove the attachment on list below the message but it keeps the bbcode in the message

**Comment by Pinkeltje** [comment]
Tested with K 6.3.5. Now when removing attachment entire message text is gone and replaced by true
![2024-09-23 Screenshot 614](https://github.com/user-attachments/assets/c0378c5e-9f86-46d5-9c86-74c9e10623ec)
**Result after removing attachment**
![2024-09-23 Screenshot 616](https://github.com/user-attachments/assets/06e307ef-f939-4d07-b82a-a3ed14e960a7)

**Comment by Ruud68** [comment]
Can confirm, just ran into this issue on my own site.

and another issue: I saw the message was replaced with true so I didn't save the message but did a 'cancel'.
This retained the message itself but the attachment was deleted.

That makes me wonder if that is correct?
IMO The attachment should be deleted upon saving the message and not upon clicking delete on the attachment. Doing it that way will actually make you cancel the changes you did.

I know that this is not a bug but probably by 'design' but wanted to report it anyway :)

**Comment by xillibit** [comment]
> Tested with K 6.3.5. Now when removing attachment entire message text is gone and replaced by true
I had made this change : https://github.com/Kunena/Kunena-Forum/commit/c80df4d95311ec9cec26e53e93c47d0fa0723854 

@Ruud68 : yes it's a bug, there is already an issue for it : https://github.com/Kunena/Kunena-Forum/issues/9730

**Comment by Ruud68** [comment]
> > Tested with K 6.3.5. Now when removing attachment entire message text is gone and replaced by true
> > I had made this change : [c80df4d](https://github.com/Kunena/Kunena-Forum/commit/c80df4d95311ec9cec26e53e93c47d0fa0723854)
> 
> @Ruud68 : yes it's a bug, there is already an issue for it : #9730

I think this is different: what expect is that when I click the remove attachment button, the attachment is only removed once the message is saved and not when saving the message is cancelled.
