### ISSUE TITLE
CK editor not working for Danish language

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9723]
**Describe the bug**
https://www.kunena.org/forum/general-questions-and-how-tos/168537-cant-make-topic

**To Reproduce**
1.Install Danish language and set as default site language
2. Click on new topic
3. No ckeditor shown

**Expected behavior**
Showing ckeditor

**Actual result**
Uncaught TypeError: c[a] is undefined

**Screenshots**

![2024-08-19 Screenshot 550](https://github.com/user-attachments/assets/45b35379-0376-46da-86e6-06076e5f552f)

**System information (please complete the following information)**

Joomla version: 5.1.2
Kunena version: 6.3.4
Php version: 8.2.12
Database version:

**Additional context**
Due to latest change [https://github.com/Kunena/Kunena-Forum/blob/K6.3/src/site/template/aurelia/layouts/widget/editor/ckeditor.php](url) on line 38
`$this->doc->addScriptOptions('com_kunena.ckeditor_joomladefaultlanguage', substr($joomlaLanguage[3], 0, 2));`
When echoing `substr($joomlaLanguage[3], 0, 2)` for Danish it results in Da
When echoing `substr($joomlaLanguage[2], 0, 2)` for Danish it results in da and editor is shown.

Not enought knowledge to see if this is the real solution. When changing [3] to [2] Dutch, German and English still show editor.

**Comment by xillibit** [comment]
I have just made a commit and your change is ok after testing too

**Comment by ThomasDiesel** [comment]
It would be nice if there could be made a new language file with the changes, to download and install

**Comment by xillibit** [comment]
It doesn't need new language file, it's change just he way to get the value of the default language
