### ISSUE TITLE
Bug in Attachment Manager

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9729]
**Describe the bug**
https://www.kunena.org/forum/k-6-3-0-support/168551-huge-bug-in-attachment-manager
Confirmed

**To Reproduce**
1. Write a text and add an attachment into the message
2. Remove this attachment via Attachment Manager

**Result**
It removes the attachment together with the text and places the number 1 instead

**System information**
- Joomla version: ‎5.1.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.5-DEV
- Kunena template: Aurelia
- Php version: 8.2.20
- Database version: 10.5.25-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by RakhmetKotlin** [comment]
Hi. This problem also occurs when you remove attachment via Kunena Backend.

**Comment by Pinkeltje** [comment]
Just my five cents, but I think at least message text isn't removed when changing line 1316 to
` $message_text = $attachment->removeBBCodeInMessage($editor_text);`
Problem remains that bbcode isn't removed.
![2024-09-04 Screenshot 570](https://github.com/user-attachments/assets/586186d9-43cc-4323-8e5d-ae2db0a6540f)
![2024-09-04 Screenshot 571](https://github.com/user-attachments/assets/4cf2b3eb-794c-4f90-bd43-d6119c2c0230)

**Comment by xillibit** [comment]
> **Result**
> It removes the attachment together with the text and places the number 1 instead

Fixed in : https://github.com/Kunena/Kunena-Forum/commit/27825ec0cd82718707292ea2542c554dec51939e

**Comment by rich20** [comment]
Is already solved.
