### ISSUE TITLE
Kunena 6.3.5 update prevents attachi to post.

### ISSUE THREAD

**Issue by makitso** [Kunena/Kunena-Forum#9746]
Kunena 6.3.5, Php 8.3, Joomla 5.1.4
Updated site to Kunena 6.3.5.  Now, if a user wants to reply to post, the Attachments block  is no longer shown.

new
![image](https://github.com/user-attachments/assets/e2402db1-ff50-4941-9751-66280ccdca7a)
0ld
![image](https://github.com/user-attachments/assets/bbdbdddb-15bf-47f9-9a9c-0a26d9fcdaa2)

**Comment by makitso** [comment]
if you change:
/components/com_kunena/src/Controller/Topic/Form/Reply/TopicForumReplyDisplay.php
replace line 201
        $this->UserCanPostImage = $this->me->checkUserAllowedLinksImages();
with
if ($this->config->new_users_prevent_post_url_images && $this->me->posts < $this->config->minimal_user_posts_add_url_image) {
            $this->UserCanPostImage = false;
        }
this fixes reply.
If you change:
/components/com_kunena/src/Controller/Topic/Form/Edit/TopicForumEditDisplay.php
replace line 220
        $this->UserCanPostImage = $this->me->checkUserAllowedLinksImages();
with
if ($this->config->new_users_prevent_post_url_images && $this->me->posts < $this->config->minimal_user_posts_add_url_image) {
            $this->UserCanPostImage = false;
        }
this fixes edit.

**Comment by xillibit** [comment]
It's not a bug, it depends on these settings under security tab :
![image](https://github.com/user-attachments/assets/f3845864-5cde-4055-ac65-890a9cebfbd7)

**Comment by makitso** [comment]
My display is different than yours.  I do not have that box set to No

![image](https://github.com/user-attachments/assets/3a05714d-fbad-4adc-9863-0075c6d8fbce)

**Comment by xillibit** [comment]
I have tried by using these settings with an user which 8 posts actually, it displays the part to add attachment: 
![image](https://github.com/user-attachments/assets/fd6e7662-8e5c-438c-a617-a1524a772f16)

**Comment by makitso** [comment]
If I set the options as below then a regular registered user can add attachments. However, an admin user can not add an attachment.
Also, I am using not using the  CAPTCHA - hCaptcha plugin but i instead the 
CAPTCHA - Invisible reCAPTCHA plugin.

![image](https://github.com/user-attachments/assets/00428fea-a3c5-44a8-821f-0237ed430298)

**Comment by xillibit** [comment]
I have tried like that in admin i have the attachments part which is displayed

**Comment by makitso** [comment]
It fails for me as an administrator.  It worked just fine with 6.3.4 and fails with 6.3.5.

**Comment by rich20** [comment]
I have also tried everything, but cannot confirm this error. Could it perhaps be related to this? https://github.com/Kunena/Kunena-Forum/issues/9742

**Comment by makitso** [comment]
Yes, same problem.

**Comment by makitso** [comment]
If I look at /libraries/kunena/src/User/KenenaUser.php, and I am logged in as a moderator or administrator, why is line 2436 setting a return as false? So, if you change line 2436 to true and change && in line 2439 to || it works?

![image](https://github.com/user-attachments/assets/35a57c9c-dd77-49ea-9a21-7d48387b181b)

**Comment by xillibit** [comment]
Are-you using Aurelia template ? This check works for both admin and mod 

The method `checkUserAllowedLinksImages()` wasn't changed in my commit on K6.3.5, the return should reversed.

**Comment by makitso** [comment]
Yes, I am using the Aurelia template.  However, this instance of Joomla/Kunena is quite old, having started around 2010.

**Comment by makitso** [comment]
> The method checkUserAllowedLinksImages() wasn't changed in my commit on K6.3.5,
Is it possible that `checkUserAllowedLinksImages()` was broken before your patch?

**Comment by makitso** [comment]
I spun up a clean copy of Joomla and Kunena with test data. You are correct, the code works correctly in that test environment. 
Can you suggest anything that might help me figure out what my installation has that is preventing my tests from workiing?

**Comment by makitso** [comment]
I use an Aurelia override (copy Aurelia code to my template html folder ) to change some of the editor buttons.  
Unfortunatly, I was remis in that I did not update the original code to current levels.  When I did the problem was solved.
