### ISSUE TITLE
 Deprecated : Creation of dynamic property Kunena\Forum\Libraries\Config\KunenaConfig::$social is deprecated in ...

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9755]
**Describe the bug**
You will see this message in the front and back end

 Deprecated : Creation of dynamic property Kunena\Forum\Libraries\Config\KunenaConfig::$social is deprecated in .../libraries/kunena/src/Config/KunenaConfig.php on line 1832

**System information**
- Joomla version: ‎5.1.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.4 Beta 1
- Kunena template: Aurelia
- Php version: 8.2.24
- Database version: 10.5.26-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
Where did-you see that ? Is it KunenaUser::socials instead : https://github.com/Kunena/Kunena-Forum/commit/ded4e0d3f636b68630f8a3cb7b01052d38f044dd ?'

**Comment by rich20** [comment]
> Where did-you see that ? Is it KunenaUser::socials instead 

I don't know what you mean by that. If your link leads to a fix, that doesn't work.
If Error Reporting is set to maximum, you will see this message (Deprecated...) immediately at the top of the backend as well as the frontend.
You get this message when you upgrade from K6.3 to K.6.4

Deprecated : Creation of dynamic property Kunena\Forum\Libraries\Config\KunenaConfig::$social is deprecated in .../libraries/kunena/src/Config/KunenaConfig.php on line 1832

----------------------------------------------------------

And if I install Kunena 6.4 on a completely new Joomla 5.1.5.dev, I get this message:
Unknown colum greylocation
Installation failed

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
.../libraries/kunena/src/Forum/KunenaForum.php
on line
365


Deprecated
: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in
...libraries/kunena/src/Forum/KunenaForum.php
on line
316

**Comment by xillibit** [comment]
I'am able to reproduce too, the issue that i have discovered is with the beta1 there isn't entry in kunena_version table for this version. So i can't fix it before the release of beta2

**Comment by rich20** [comment]
I have discovered other bugs, but I don't know if they can be fixed by creating the kunena_version table. However, I can only test this once the error with the version table has been fixed. Because if I create this table entry manually, one error message is gone, but other problems remain, especially if it is a completely new installation.
