### ISSUE TITLE
CK Editor emoticons showing unauthorized when show images for guests is set to No

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9756]
**Describe the bug**
CK Editor emoticons showing unauthorized when show images for guests is set to No

**To Reproduce**

1. Set show images for guests to no
2. Use CK Editor
3. Insert emoticon in message
4. Emoticon not shown. Instead "This image is hidden for guests" (free translated from Dutch).

**Expected behavior**
Emoticon visible

**Actual result**
See above

**Screenshots**
**Logged in**
![2024-10-24 Screenshot 650](https://github.com/user-attachments/assets/98a50324-d01a-4dc6-9fe1-5e8b2e0bbedf)
**Guest**
![2024-10-24 Screenshot 651](https://github.com/user-attachments/assets/4805ac51-6d8f-4a0e-b0db-c530f20fac63)

**Comparison CKEditor and SCEditor**
![2024-10-24 Screenshot 652](https://github.com/user-attachments/assets/cb4d17fc-4a26-40eb-aa74-602cbb4f9a74)
SCEditor keeps the shortcode (even when using toolbar to insert emoticons. CK editor translates to image.
[img]/media/kunena/emoticons/shocked.png[/img]

**System information**

Joomla version: 5.2.0
Kunena version: 6.3.5

**Comment by rich20** [comment]
Yes, this bug has existed for a very long time. https://github.com/Kunena/Kunena-Forum/issues/7856

Is it possible, that a click on a smiley add the short code instead a image link? With short code the smileys will be displayed.

**Comment by Pinkeltje** [comment]
I think I found the solution: 
replace com_kunena/template/aurelia/layouts/bbcode/image/unauthorised.php
with
```
<?php

/**
 * Kunena Component
 *
 * @package         Kunena.Template.Aurelia
 * @subpackage      BBCode
 *
 * @copyright       Copyright (C) 2008 - 2024 Kunena Team. All rights reserved.
 * @license         https://www.gnu.org/copyleft/gpl.html GNU/GPL
 * @link            https://www.kunena.org
 **/

namespace Kunena\Forum\Site;

\defined('_JEXEC') or die();

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;

// Get the current request path
$requestPath = Factory::getApplication()->input->server->getString('REQUEST_URI');

// Check if the request is for an image in the attachments folder
$isAttachmentsImage = (
    strpos($requestPath, 'media/kunena/attachments') !== false && 
    preg_match('/\.(jpg|jpeg|png|gif|webp)$/i', $requestPath)
);

?>

<div class="kmsgattach">
    <em>
        <?php if ($isAttachmentsImage): ?>
            <?php echo $this->title; ?>
        <?php endif; ?>
    </em>
</div>

```
**Logged in:**
![2024-10-26 Screenshot 659](https://github.com/user-attachments/assets/31eff42b-4d99-460d-a590-3ccfede0ec23)

**Logged out**
![2024-10-26 Screenshot 660](https://github.com/user-attachments/assets/c32403aa-e772-4079-b1f7-7567ed328715)
