### ISSUE TITLE
Category manager | Deprecated: Creation of dynamic property Kunena\Forum\Libraries...

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9758]
**Describe the bug**

**After a new installation**

Go to the Kunena category manager in the backend. These 4 messages are displayed for each category created category.

Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Forum\Category\KunenaCategory::$up is deprecated in .../administrator/components/com_kunena/src/Model/CategoriesModel.php on line 480

Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Forum\Category\KunenaCategory::$down is deprecated in .../administrator/components/com_kunena/src/Model/CategoriesModel.php on line 481

Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Forum\Category\KunenaCategory::$reOrder is deprecated in .../administrator/components/com_kunena/src/Model/CategoriesModel.php on line 482

Deprecated: Creation of dynamic property Kunena\Forum\Libraries\Forum\Category\KunenaCategory::$editor is deprecated in .../administrator/components/com_kunena/src/Model/CategoriesModel.php on line 508

**After an upgrade from K6.3 to K.4**

After an upgrade there are additional also these messages. This messages can also be seen in the front end.

Deprecated: Creation of dynamic property Kunena\Forum\Libraries\User\KunenaUser::$bebo is deprecated in .../libraries/kunena/src/User/KunenaUser.php on line 685

**System information**
- Joomla version: ‎5.1.5-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.4.0-BETA2
- Kunena template: Aurelia
- Php version: 8.2.24
- Database version: 10.5.26-MariaDB

**Desktop**
- OS: Ubuntu 22.04.5 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
> Deprecated: Creation of dynamic property Kunena\Forum\Libraries\User\KunenaUser::$bebo is deprecated in .../libraries/kunena/src/User/KunenaUser.php on line 685

I don't find bebo in the file specified

@rich20 : please look in your table #__kunena_users and tell me if you still have the column bebo ? i have just tried an update from K6.3.5 to K6.4.0BETA2 and it remains the columns delicious and bsky_app but not bebo

**Comment by rich20** [comment]
I have only two columns for social share:
**socials**  and **socialshare**
I also don't have a list in my profile where you can enter this. This is the case with my new installation

If it is an upgrade, then the column **bebo is available**, and all other social columns

**Comment by rich20** [comment]
Addendum: The **socials** column is not added during an upgrade

**Comment by xillibit** [comment]
On update form K6.3.5 to K6.4.0, it has right applied that in my test : https://github.com/Kunena/Kunena-Forum/blob/K6.4/src/admin/install/kunena.install.upgrade.xml#L282 except there is a typo for blueskyApp and it's missing delicious. So you should have remaining only blueskyApp and delicious but not bebo

> **socials** and **socialshare**
> I also don't have a list in my profile where you can enter this. This is the case with my new installation

The column socialshare is useless now in K6.4, what do-you by mean _I also don't have a list in my profile where you can enter this_ ?

> Addendum: The **socials** column is not added during an upgrade

For me it does the same, i will look to fix it

**Comment by rich20** [comment]
> what do-you by mean I also don't have a list in my profile where you can enter this ?

I meant the list in the profile (profile infos) where users can enter their social accounts such as Facebook etc...


>The column socialshare is useless now in K6.4

I have now created a new build with your new fix from 2h ago

all social columns are gone now, except **socials** and **socialshare**

**Comment by xillibit** [comment]
> > Addendum: The **socials** column is not added during an upgrade
> 
> For me it does the same, i will look to fix it

With the latest changes it's ok, the column socials is right here on update
