### ISSUE TITLE
.../paidTemplatesK6.0.xml should be adjusted

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9760]
**Describe the bug**

https://update.kunena.org/paidTemplatesK6.0.xml
If you click on Kunena 6.x Templates or Download in the backend -> Kunena -> Templates, you will get to a page with error 404.

The detail URL should be changed to https://9themestore.com/index.php/products/kunena-templates

**Comment by xillibit** [comment]
Just changed in the XML
