### ISSUE TITLE
Private attachments are in the topic history

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9766]
**To Reproduce**
Write an answer and add a private attachment
Login with another user
Click on Reply and scroll down

**Actual result**
The attachment is available in the Topic History

**System information**
- Joomla version: ‎5.2.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.7-DEV
- Kunena template: Aurelia
- Php version: 8.2.24 & 8.3.12
- Database version: 10.5.26-MariaDB

**Desktop**
- OS: Ubuntu 22.04.5 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
Created Pull Request 
Still don't know how to remove old commits...........Sorry

**Comment by Pinkeltje** [comment]
Messed up. New pull request made. #9768
