### ISSUE TITLE
Edit mode : Protected attachments are always displayed as private

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9769]
**Describe the bug**
https://github.com/Kunena/Kunena-Forum/pull/9764
I found one more thing as I had tested protected attachments.  Protected attachments are always shown as private in edit mode. 

**To Reproduce**
1. set in the configuration Protect Attachments to Yes
2. upload some attachments (it does not matter whether it is inserted into the message or not)
3. Submit and then edit the message

**Result**
All attachments are displayed as private

**System information**
- Joomla version: ‎5.2.2-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.7-DEV
- Kunena template: Aurelia
- Php version: 8.3.12
- Database version: 10.11.8-MariaDB

**Desktop**
- OS: Ubuntu 22.04.5 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
Will check as soon as 6.4.0 B3 (or next version) is working.
