### ISSUE TITLE
Too many line breaks should be removed

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9771]
https://github.com/Kunena/Kunena-Forum/blob/3eab985d29a25789adca4c56d98e4728d09fd404/src/site/language/en-GB/com_kunena.site.templates.ini#L478

**Comment by xillibit** [comment]
You mean to remove this language string ?

**Comment by rich20** [comment]
No, I meant that the line breaks should be removed. In all template.ini files, the lines from 479 to line 498 are empty.
.
![image10999](https://github.com/user-attachments/assets/83a07f82-ed3d-4b13-93a5-ebeef1ce85ea)
