### ISSUE TITLE
 Too many line breaks should be removed (part 2)

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9774]
**Describe the bug**
https://github.com/Kunena/Kunena-Forum/blob/8b87b8e9fc20ebcaeb6e6904d236e39b722fea9b/src/admin/language/en-GB/com_kunena.admin.libraries.ini#L444

**Comment by xillibit** [comment]
I think when the key string for COM_KUNENA_MYPROFILE_* has been removed, it has been done by search&replace so it remains empty lines. I will look with a script to remove these empty lines
