### ISSUE TITLE
Fresh install of Kunena 6.4.0 B3 not installing language files

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9775]
**Describe the bug**
Not installing language files

**To Reproduce**
Create a fresh install of Joomla 5.2.1 and install 6.4.0 B3 

**Expected behavior**
See text instead of constants

**Actual result**

![2024-11-24 Screenshot 709](https://github.com/user-attachments/assets/833ef968-57bc-43fa-8df1-8905b2681ed5)

**Screenshots**

**System information (please complete the following information)**

Joomla version: 5.2.1
Kunena version: 6.4.0 B3
Php version: 8.2.12 
Database version: 10.4.32-MariaDB 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rich20** [comment]
The language files are installed but not found because they have been renamed. Perhaps the [findlanguagestrings.php](https://github.com/Kunena/Kunena-Forum/blob/K6.4/scripts/findlanguagestrings.php) needs to be adapted?

**Comment by Pinkeltje** [comment]
@rich20 they are **not** installed on a fresh Joomla install with K 6.4.0 B3 as I already stated. When checking my language folders en-GB for both site and admin there is nothing that is even remotely related to Kunena.

**Comment by xillibit** [comment]
I have sent seen it, i will adapt all install XML files for languages

Le dim. 24 nov. 2024, 15:04, Astrid van Eerd ***@***.***> a
écrit :

**Comment by rich20** [comment]
@Pinkeltje With a Kunena installation, only the English language is installed.
These are stored in 
/administrator/components/com_kunena/language/en-GB
and
/components/com_kunena/language/en-GB.

And when installing the language package are these saved in
/administrator/language/en-GB
and
/language/en-GB

**Comment by rich20** [comment]
Language files with the designation ‘site’ or ‘admin’ in the file name are not found.
When I use the debug mode, I see several paths where these are being searched for.
Example the com_kunena.admin.controllers.ini

    - /administrator/language/en-GB/com_kunena.controllers.ini
    - /administrator/language/en-GB/en-GB.com_kunena.controllers.ini
    - /administrator/components/com_kunena/language/en-GB/com_kunena.controllers.ini
    - /administrator/components/com_kunena/language/en-GB/en-GB.com_kunena.controllers.ini

But the correct path after a new Installation would be:

    - /administrator/components/com_kunena/language/en-GB/com_kunena.admin.controllers.ini

After an upgrade, the language only works because the old ini files are not removed. However, this should be done, as otherwise all Kunena language files will be available twice.

**Comment by xillibit** [comment]
I have noticied that too, i need to remove the site and admin in the filenames

**Comment by xillibit** [comment]
I have renammed the files in frontend and backend back to their names without the `site` and `admin` part, it should be changed in crowdin

**Comment by rich20** [comment]
Can you please check again? The files with 'site' in the filename will still be installed in the frontend.
https://github.com/Kunena/Kunena-Forum/tree/K6.4/src/site/language/en-GB
