### ISSUE TITLE
Whatsapp not pushed to K 6.4 B3?

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9777]
Just a question. Checking new user socials file I see 
`"whatsapp": {
        "value": "",
        "url": "##VALUE##",
        "title": "COM_KUNENA_MYPROFILE_WHATSAPP",
        "nourl": 1
    },
I've changed this in K 6.3 to include url and make icon clickable.`

See also: https://www.kunena.org/forum/k-6-3-0-support/168605-whatsapp-icon-not-displaying-correctly

**Comment by xillibit** [comment]
There was conflicts when i had tried to merge your changes into K6.4 branch, i need to look an another time

**Comment by Pinkeltje** [comment]
Think because you removed socials code to a separate file. My pull request was for KunenaUser.php
