### ISSUE TITLE
New Topic: SVG topic icons changes the size when switch to another category

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9785]
**To Reproduce**

- click on menu item New Topic
- switch to another category using the drop-down list

**Actual result**
The symbols are displayed in a smaller size

**Additional context**
I don't know if this solution is correct, but if in src/site/src/Controllers/TopicController.php line 2626 the word topicIcon has only lower case letters, it works correctly.
https://github.com/Kunena/Kunena-Forum/blob/8790d77e653f560db24486b10915c0dbbc160b10/src/site/src/Controllers/TopicController.php#L2626

**System information**
- Joomla version: ‎5.2.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.8-DEV
- Kunena template: Aurelia
- Php version: 8.3.14
- Database version: 10.11.8-MariaDB

**Desktop**
- OS: Ubuntu 22.04.5 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
When I change that line in a patched 6.3.7 version topicons disappear again. I think it is in edit.js.
Can you try this change: https://github.com/Pinkeltje/Kunena-Forum/blob/K6.3/src/site/template/aurelia/assets/js/edit.js
Only thing I still don't get is why the check icon changes
![2024-12-15 Screenshot 724](https://github.com/user-attachments/assets/cd258ab5-83da-43f0-a184-7c9c33074af1)

![2024-12-15 Screenshot 725](https://github.com/user-attachments/assets/7aff2bbe-0cee-45b1-8fc3-6776901a4b88)

**Comment by rich20** [comment]
> Only thing I still don't get is why the check icon changes

Yes, with your edit.js I get the same result as you.

**Comment by rich20** [comment]
I have found the cause.
If you click on New Topic, the symbols of
**/media/kunena/topic_icons/default/user/svg/** are loaded, and if you switch to another category, they are loaded from
**/media/kunena/core/svg/**. These are normally only used for the labels. 
Since the check.svg in both folders are not the same, this conflict arises.

In this image you can see that the check.svg in the label is without a circle.
![Bildschirmfoto vom 2024-12-15 18-08-36](https://github.com/user-attachments/assets/1fdb7e3c-b2f2-4ca4-a5bc-0bf3e40d15cf)

One solution would be, for example, to copy the same image check.svg into both directories.

**Comment by Pinkeltje** [comment]
Will have a look at it tomorrow. Personally I don't like the check-circle for the label or the normal check for the topic. But maybe there is another solution.

**Comment by Pinkeltje** [comment]
Think I found it. Can you please check?
https://github.com/Pinkeltje/Kunena-Forum/blob/K6.3/src/media/kunena/topic_icons/default/topicicons.xml

**Comment by rich20** [comment]
Yes, that's how it works. It needs both changes, in the edit.js for the correct size and in the topicicons.xml, so that the correct icons can be loaded.
- [x] the size remains the same
- [x] the correct symbols are loaded

**Comment by Pinkeltje** [comment]
OK thx. Will create pull request.
