### ISSUE TITLE
The following bug fixes are missing in K6.4.0-RC1

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9788]
**Describe the bug**
The following bug fixes are missing in K6.4.0-RC1

https://github.com/Kunena/Kunena-Forum/pull/9784/commits/1a20cef1921e25f6a4e6cb441c2ee6f9a5f1b960

https://github.com/Kunena/Kunena-Forum/pull/9786

**Comment by xillibit** [comment]
I had not merged changes from K6.3, just done it
