### ISSUE TITLE
‘Set all attachments as private’ saves the message

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#9789]
**Describe the bug**
Sorry, I had overlooked a mistake. If you click on the ‘Set all attachments as private’ button, the message is saved instead of the attachments being marked as private. 

**To Reproduce**
1. reply or create a new topic
2. enter a short text
3. upload one or more attachments
4. click on the button ‘Set all attachments as private’ 

**Result**
The message is saved, or if no text is entered, the message ‘Cannot save message: Message body is empty!’ is displayed.

**System information**
- Joomla version: ‎5.2.3-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.3.8-DEV
- Kunena template: Aurelia
- Php version: 8.3.14
- Database version: 10.11.8-MariaDB

**Desktop**
- OS: Ubuntu 22.04.5 LTS
- Browser: Chromium, Firefox and Opera

**Comment by Pinkeltje** [comment]
Should be fixed with latest pull request.
