### ISSUE TITLE
6.4.0-RC1 profile

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9793]
**Describe the bug**
Profile not correct
**To Reproduce**
Install RC1, login and go to profile

**Screenshots**
![2024-12-28 Screenshot 732](https://github.com/user-attachments/assets/acfc53c8-045a-4986-a094-7e360a5b20a6)
**go to Edit**
![2024-12-28 Screenshot 733](https://github.com/user-attachments/assets/0149f3ba-9357-4896-bcee-95f7764b69f6)
**Add avatar and go to tab Profile Information**
![2024-12-28 Screenshot 734](https://github.com/user-attachments/assets/56790b02-6a5d-4ebd-957d-b96457cee6c7)

`<input class="form-control hasTooltip" id="socialx_social" type="text" maxlength="50" name="socialx_social" value="Rendering Error in layout User/Edit/Profile: htmlspecialchars(): Argument #1 ($string) must be of type string, stdClass given. Please enable debug mode for more information.                                                                                                " data-bs-toggle="tooltip" title="This is your X (previously Twitter) username.">`

**System information (please complete the following information)**

Joomla version: 5.2.2
Kunena version: 6.4.0 RC1
Php version: 8.2.12

**Comment by Pinkeltje** [comment]
Made some fixes. Seems ok to me now;
components\com_kunena\template\aurelia\layouts\user\item\socials
[socials.zip](https://github.com/user-attachments/files/18269192/socials.zip)
libraries\kunena\src\User
[KunenaUserSocials.zip](https://github.com/user-attachments/files/18269193/KunenaUserSocials.zip)

**Comment by rich20** [comment]
If Kunena Debug is enabled, this error is present in Profile
and
Profile -> Edit -> Profile Information

Warning: Trying to access array offset on int in .../libraries/kunena/src/User/KunenaUserSocials.php on line 304

**Comment by rich20** [comment]
Addendum:
I've now noticed that the profile information is in the wrong order.
The following information is now listed at the bottom instead of before the social information.

Personal Text	
Birthdate
Location	
Gender
Web site Name	
Web site URL

**Comment by Pinkeltje** [comment]
Order changed:
components\com_kunena\template\aurelia\layouts\user\edit\profile
[default.zip](https://github.com/user-attachments/files/18272648/default.zip)
BTW: I would delete this from css as birthday field is too far to the left:
```
#kunena.layout #editprofile #birthdate {
	margin-left: -15px;
}
```

**Comment by Pinkeltje** [comment]
> If Kunena Debug is enabled, this error is present in Profile
> and
> Profile -> Edit -> Profile Information
> 
> Warning: Trying to access array offset on int in .../libraries/kunena/src/User/KunenaUserSocials.php on line 304
Unable to reproduce, but maybe this fix helps?
[socials (2).zip](https://github.com/user-attachments/files/18273056/socials.2.zip)

**Comment by xillibit** [comment]
> Order changed:
> components\com_kunena\template\aurelia\layouts\user\edit\profile
> [default.zip](https://github.com/user-attachments/files/18272648/default.zip)

There are no changes in your file

**Comment by rich20** [comment]
Can you check this please?
I get in all social share infos an error like this:

`<br /><b>Warning</b>:  Attempt to read property `
```

.../components/com_kunena/template/aurelia/layouts/user/edit/profile/default.php on line 141
" data-bs-toggle="tooltip" title="This is your X (previously Twitter) username."/> 
```

**Comment by Pinkeltje** [comment]
Just to make sure: did you do a clean install of 6.4.0 RC1 or an update from earlier version? I can't reproduce it in a clean install, but maybe it has something do do with update query for kunena_users table.

**Comment by rich20** [comment]
Yes, it was an upgrade. I have now tested it with a clean K6.3 and upgrade to K6.4 as well as with a clean K6.4.
You can test it:
1. enable Kunena debug
2. upload an avatar and save
3. go to Profile information
The error occurs, so to speak, when something has been changed in the profile. I had noticed it after I had uploaded an avatar during the new installation.

**Comment by rich20** [comment]
Addendum:
After saving the avatar, all social icons in the profile are gone if you refresh the page.

**Comment by Pinkeltje** [comment]
@xillibit  Can't see a patch for libraries\kunena\src\User\KunenaUserSocials

**Comment by xillibit** [comment]
> @xillibit Can't see a patch for libraries\kunena\src\User\KunenaUserSocials

because i don't see any changes in your file

**Comment by Pinkeltje** [comment]
There are changes. But as I don't have a fork for 6.4, they are only visible with i.e. winmerge.
![Schermafbeelding 2025-01-03 115000](https://github.com/user-attachments/assets/ce1f870b-f43d-469d-a1d1-0af0e62c781e)
