### ISSUE TITLE
6.4.0-RC1 Install sample data

### ISSUE THREAD

**Issue by Pinkeltje** [Kunena/Kunena-Forum#9794]
**Describe the bug**
Install sample data not working because administrator\components\com_kunena\src\View\Cpanel\HtmlView.php was not updated with fix

[Fix ](https://github.com/Kunena/Kunena-Forum/pull/9782)
https://github.com/Kunena/Kunena-Forum/commit/d96aefb4bec5290cfc256df4d8bf627dd1f8c5bc

**Comment by rich20** [comment]
Confirmed
It seems that K6.4.0-RC1 was created before the fix was merged into K6.4.

**Comment by xillibit** [comment]
I had merged some recent changes K6.3 just after the release of the RC1 of K6.4, it will be in the next release
