### ISSUE TITLE
5 star Rating

### ISSUE THREAD

**Issue by svanschu** [Kunena/Kunena-Forum#981]
http://www.kunena.org/forum/196-Developers---K-20-issues/67322-Kunena-2-0-5-Star-rating

**Comment by 810** [comment]
@xillibit could you check the code, and update it to K3.1

**Comment by xillibit** [comment]
I need to re-do it i think since this time plenty things should have changed, i want to focus of couple of things to finish K3.1 beofr to finish this one

**Comment by 810** [comment]
@xillibit could you update this code. thnx

**Comment by xillibit** [comment]
I will check it later

**Comment by 810** [comment]
merged
